/**
 * ESKİ gün tabanlı müfredatın konu modeline eşlenmesi — YALNIZCA göç ve denetim içindir.
 *
 * Bu dosyadaki gün numaraları hiçbir gezinmeyi, pratik seçimini, özet seçimini,
 * tamamlanmayı, hataları, ustalığı ya da istatistiği SÜRMEZ. Kullanım alanları:
 *   - kayıtlı ilerlemenin (v9 → v10) deterministik göçü,
 *   - eski derin bağlantıların (`#/gun/7`, `#/ozet/10/...`) yönlendirilmesi,
 *   - kapsam denetimi ("eski kavramların hepsi bir konuya eşlendi mi?").
 *
 * Üretim: tek seferlik göç betiği (eski `concepts.ts` → yeni konu kaydı).
 */

/** Eski özet konusu (gün bölümü) kimliği → yeni özet bölümü kimliği; `null` = emekli. */
export const LEGACY_SECTION_MAP: Record<string, string | null> = {
  'private.day1.vorstellung': 'greetings.introduce',
  'private.day1.alter-herkunft-wohnort': 'personal-info.age-origin',
  'private.day1.beruf': 'personal-info.job',
  'private.day1.kontakt-formular': 'personal-info.contact',
  'private.day1.fiil-cekimi': 'verbs.conjugation',
  'private.day1.diller-selamlasma': 'greetings.hello',
  'private.day2.artikel-belirli-belirsiz': 'articles.definite-indefinite',
  'private.day2.artikel-kein-mein-dein': 'articles.chain',
  'private.day2.cumle-olumlu': 'sentence-building.basic',
  'private.day2.cumle-olumsuz': 'articles.negation',
  'private.day2.sorular': 'questions.yes-no',
  'private.day2.haben-sein': 'verbs.haben-sein',
  'private.day2.gunluk-hayat': 'daily-routine.everyday-sentences',
  'private.day3.hedef': null,
  'private.day3.mogen-moechten-gern': 'likes.moegen-gern',
  'private.day3.es-gibt': 'akkusativ.es-gibt',
  'private.day3.yer-yon': 'places.prepositions',
  'private.day3.ayrilabilen-fiiller': 'separable-verbs.rule',
  'private.day3.refleksif': 'verbs.reflexive',
  'private.day3.sifat-ekleri': 'adjectives.endings',
  'private.day3.iyelik': 'pronouns.unser-ihr',
  'private.day3.miktar-cogul': 'articles.plural',
  'private.day3.zaman': 'time.expressions',
  'private.day3.cumle-dizilisi': 'sentence-building.v2',
  'private.day3.gunluk-hayat': 'vocabulary.weather-animals',
  'private.day3.master-cumleler': 'sentence-building.eight',
  'private.day3.tum-cumleler': 'sentence-building.eighty',
  'private.day5.hedef': null,
  'private.day5.leben': 'personal-info.leben',
  'private.day5.sayilar-onluklar': 'numbers.teens-tens',
  'private.day5.sayilar-yuzler': 'numbers.hundreds',
  'private.day5.kisisel-bilgiler': 'personal-info.form',
  'private.day5.dogum-yeri': 'personal-info.birthplace',
  'private.day5.medeni-hal': 'personal-info.marital',
  'private.day5.kendini-tanitma': 'personal-info.self-intro',
  'private.day5.baglaclar': 'sentence-building.und-aber',
  'private.day5.kelimeler': 'vocabulary.small-words',
  'private.day5.yiyecek': 'food.words-basic',
  'private.day6.hedef': null,
  'private.day6.iyelik-tablo': 'pronouns.possessive-table',
  'private.day6.cumle-kurma': 'pronouns.sentence',
  'private.day7.hedef': null,
  'private.day7.ev-odalar': 'home.rooms',
  'private.day7.mobilyalar': 'home.furniture',
  'private.day7.evi-tarif': 'adjectives.describe',
  'private.day7.artikel-zamir': 'pronouns.article-to-pronoun',
  'private.day7.yeni-fiiller': 'verbs.more-verbs',
  'private.day7.gefallen': 'likes.gefallen',
  'private.day7.essen-trinken': 'food.preferences',
  'private.day7.alisveris-siklik': 'shopping.frequency',
  'private.day7.miktar': 'shopping.quantities',
  'private.day7.yeni-yiyecek': 'food.words-more',
  'private.day7.fiyat': 'shopping.prices',
  'private.day7.brauchen': 'shopping.brauchen',
  'private.day7.faydali-kelimeler': 'vocabulary.daily-words',
  'private.day7.evimi-anlatiyorum': 'home.my-home',
  'private.day7.kaliplar': 'home.patterns',
  'private.day10.hedef': null,
  'private.day10.trennbar-nedir': 'separable-verbs.what',
  'private.day10.kern-verben': 'separable-verbs.core',
  'private.day10.mein-tag-sabah': 'daily-routine.morning',
  'private.day10.mein-tag-gun': 'daily-routine.day',
  'private.day10.mein-tag-aksam': 'daily-routine.evening',
  'private.day10.dann-danach': 'sentence-building.dann-danach',
  'private.day10.trennbar-nicht': 'separable-verbs.compare',
  'private.day10.uhrzeit-frage': 'time.question',
  'private.day10.uhrzeit-resmi': 'time.official',
  'private.day10.uhrzeit-gunluk': 'time.everyday',
  'private.day10.halb-viertel': 'time.halb',
  'private.day10.um-uhr': 'time.um',
  'private.day10.mein-tag-tam': 'daily-routine.full',
  'private.day10.wortschatz': 'vocabulary.more-words',
};

/** Eski kavram kimliği → yeni kavram kimliği. */
export const LEGACY_CONCEPT_MAP: Record<string, string> = {
  'private.day1.vorstellung.wie-heisst-du': 'greetings.vorstellung.wie-heisst-du',
  'private.day1.vorstellung.wie-ist-dein-name': 'greetings.vorstellung.wie-ist-dein-name',
  'private.day1.vorstellung.wer-bist-du': 'greetings.vorstellung.wer-bist-du',
  'private.day1.vorstellung.freut-mich': 'greetings.vorstellung.freut-mich',
  'private.day1.vorstellung.sich-vorstellen': 'greetings.vorstellung.sich-vorstellen',
  'private.day1.alter.wie-alt': 'personal-info.alter.wie-alt',
  'private.day1.herkunft.woher': 'personal-info.herkunft.woher',
  'private.day1.wohnort.wo-wohnst': 'personal-info.wohnort.wo-wohnst',
  'private.day1.herkunft.aus': 'personal-info.herkunft.aus',
  'private.day1.wohnort.in': 'personal-info.wohnort.in',
  'private.day1.beruf.frage': 'personal-info.beruf.frage',
  'private.day1.beruf.antwort-bin': 'personal-info.beruf.antwort-bin',
  'private.day1.beruf.als-bei': 'personal-info.beruf.als-bei',
  'private.day1.kontakt.email': 'personal-info.kontakt.email',
  'private.day1.kontakt.punkt': 'personal-info.kontakt.punkt',
  'private.day1.kontakt.telefon': 'personal-info.kontakt.telefon',
  'private.day1.kontakt.antwort-telefon': 'personal-info.kontakt.antwort-telefon',
  'private.day1.formular.felder': 'personal-info.formular.felder',
  'private.day1.formular.familienstand': 'personal-info.formular.familienstand',
  'private.day1.formular.kinder': 'personal-info.formular.kinder',
  'private.day1.formular.heimat': 'personal-info.formular.heimat',
  'private.day1.verben.sein': 'verbs.verben.sein',
  'private.day1.verben.heissen': 'verbs.verben.heissen',
  'private.day1.verben.kommen': 'verbs.verben.kommen',
  'private.day1.verben.essen': 'verbs.verben.essen',
  'private.day1.verben.sagen': 'verbs.verben.sagen',
  'private.day1.verben.sprechen': 'verbs.verben.sprechen',
  'private.day1.verben.kochen': 'verbs.verben.kochen',
  'private.day1.sprachen.welche': 'greetings.sprachen.welche',
  'private.day1.sprachen.antwort': 'greetings.sprachen.antwort',
  'private.day1.selamlasma.hallo': 'greetings.selamlasma.hallo',
  'private.day1.nezaket.entschuldigung': 'greetings.nezaket.entschuldigung',
  'private.day2.artikel.der-die-das-die-pl': 'articles.artikel.der-die-das-die-pl',
  'private.day2.artikel.ein-eine': 'articles.artikel.ein-eine',
  'private.day2.artikel.cogul-belirsiz-yok': 'articles.artikel.cogul-belirsiz-yok',
  'private.day2.artikel.was-ist-das': 'articles.artikel.was-ist-das',
  'private.day2.wortschatz.nesneler': 'articles.wortschatz.nesneler',
  'private.day2.artikel.kein-keine': 'articles.artikel.kein-keine',
  'private.day2.artikel.mein-meine': 'articles.artikel.mein-meine',
  'private.day2.artikel.dein-deine': 'articles.artikel.dein-deine',
  'private.day2.artikel.zincir': 'articles.artikel.zincir',
  'private.day2.artikel.wie-ist-dein': 'articles.artikel.wie-ist-dein',
  'private.day2.cumle.olumlu-yapi': 'sentence-building.cumle.olumlu-yapi',
  'private.day2.verben.machen': 'sentence-building.verben.machen',
  'private.day2.verben.gehen-zur': 'sentence-building.verben.gehen-zur',
  'private.day2.zaman.jeden-tag-heute': 'sentence-building.zaman.jeden-tag-heute',
  'private.day2.olumsuzluk.nicht': 'articles.olumsuzluk.nicht',
  'private.day2.olumsuzluk.kein-haben': 'articles.olumsuzluk.kein-haben',
  'private.day2.olumsuzluk.donusum': 'articles.olumsuzluk.donusum',
  'private.day2.sorular.evet-hayir-yapi': 'questions.sorular.evet-hayir-yapi',
  'private.day2.sorular.donusum': 'questions.sorular.donusum',
  'private.day2.sorular.ja-nein-cevap': 'questions.sorular.ja-nein-cevap',
  'private.day2.haben.tablo': 'verbs.haben.tablo',
  'private.day2.sein.tekrar': 'verbs.sein.tekrar',
  'private.day2.haben.kein-ile': 'verbs.haben.kein-ile',
  'private.day2.gunluk.okul-is': 'daily-routine.gunluk.okul-is',
  'private.day2.gunluk.kahve-spor': 'daily-routine.gunluk.kahve-spor',
  'private.day2.gunluk.kitap-okuma': 'daily-routine.gunluk.kitap-okuma',
  'private.day2.gunluk.mini-dialog': 'daily-routine.gunluk.mini-dialog',
  'private.day3.mogen.cekim': 'likes.mogen.cekim',
  'private.day3.moechten.cekim': 'modal-verbs.moechten.cekim',
  'private.day3.gern.kullanim': 'likes.gern.kullanim',
  'private.day3.mogen-gern-farki': 'likes.mogen-gern-farki',
  'private.day3.esgibt.temel': 'akkusativ.esgibt.temel',
  'private.day3.esgibt.akkusativ': 'akkusativ.esgibt.akkusativ',
  'private.day3.esgibt.genel-cogul': 'akkusativ.esgibt.genel-cogul',
  'private.day3.kontraksiyon.zum': 'places.kontraksiyon.zum',
  'private.day3.kontraksiyon.zur': 'places.kontraksiyon.zur',
  'private.day3.kontraksiyon.im': 'places.kontraksiyon.im',
  'private.day3.kontraksiyon.ins': 'places.kontraksiyon.ins',
  'private.day3.kontraksiyon.am': 'places.kontraksiyon.am',
  'private.day3.kontraksiyon.ans': 'places.kontraksiyon.ans',
  'private.day3.im-ins-farki': 'places.im-ins-farki',
  'private.day3.nach-hause': 'places.nach-hause',
  'private.day3.zu-hause': 'places.zu-hause',
  'private.day3.mit-dativ': 'places.mit-dativ',
  'private.day3.mit-meinen-freunden': 'places.mit-meinen-freunden',
  'private.day3.der-den-dem': 'places.der-den-dem',
  'private.day3.in-akkusativ-yon': 'places.in-akkusativ-yon',
  'private.day3.auf-dem': 'places.auf-dem',
  'private.day3.bei-der': 'places.bei-der',
  'private.day3.ayrilabilen.kural': 'separable-verbs.ayrilabilen.kural',
  'private.day3.aufstehen': 'separable-verbs.aufstehen',
  'private.day3.aufraeumen': 'separable-verbs.aufraeumen',
  'private.day3.zurueckkommen': 'separable-verbs.zurueckkommen',
  'private.day3.refleksif.temel': 'verbs.refleksif.temel',
  'private.day3.sich-duschen': 'verbs.sich-duschen',
  'private.day3.sich-ausruhen': 'verbs.sich-ausruhen',
  'private.day3.refleksif-ayrilabilen': 'verbs.refleksif-ayrilabilen',
  'private.day3.sifat.yuklem': 'adjectives.sifat.yuklem',
  'private.day3.sifat.ein-notr': 'adjectives.sifat.ein-notr',
  'private.day3.sifat.cogul-artikelsiz': 'adjectives.sifat.cogul-artikelsiz',
  'private.day3.iyelik.unser': 'pronouns.iyelik.unser',
  'private.day3.iyelik.ihr': 'pronouns.iyelik.ihr',
  'private.day3.iyelik.dativ-cogul': 'pronouns.iyelik.dativ-cogul',
  'private.day3.miktar.sise': 'shopping.miktar.sise',
  'private.day3.miktar.oda': 'articles.miktar.oda',
  'private.day3.cogul.genel': 'articles.cogul.genel',
  'private.day3.cogul.umlaut': 'articles.cogul.umlaut',
  'private.day3.zaman.um-uhr': 'time.zaman.um-uhr',
  'private.day3.zaman.am': 'time.zaman.am',
  'private.day3.zaman.im-mevsim': 'time.zaman.im-mevsim',
  'private.day3.zaman.dann': 'time.zaman.dann',
  'private.day3.zaman.morgen-cift-anlam': 'time.zaman.morgen-cift-anlam',
  'private.day3.dizilisi.verb-ikinci': 'sentence-building.dizilisi.verb-ikinci',
  'private.day3.dizilisi.zaman-basta': 'sentence-building.dizilisi.zaman-basta',
  'private.day3.moechten-infinitiv': 'modal-verbs.moechten-infinitiv',
  'private.day3.hava.ifadeler': 'vocabulary.hava.ifadeler',
  'private.day3.hayvanlar.kelime': 'vocabulary.hayvanlar.kelime',
  'private.day3.hobiler.kelime': 'vocabulary.hobiler.kelime',
  'private.day3.alisveris.kelime': 'shopping.alisveris.kelime',
  'private.day3.ev-kelime': 'home.ev-kelime',
  'private.day3.gunluk-rutin': 'daily-routine.gunluk-rutin',
  'private.day3.es-geht-mir': 'greetings.es-geht-mir',
  'private.day5.leben.anlam': 'personal-info.leben.anlam',
  'private.day5.leben.cekim': 'personal-info.leben.cekim',
  'private.day5.leben.wohnen-farki': 'personal-info.leben.wohnen-farki',
  'private.day5.sayilar.onlu-sayilar': 'numbers.sayilar.onlu-sayilar',
  'private.day5.sayilar.onluklar': 'numbers.sayilar.onluklar',
  'private.day5.sayilar.bilesik': 'numbers.sayilar.bilesik',
  'private.day5.sayilar.yuzler': 'numbers.sayilar.yuzler',
  'private.day5.sayilar.yuzler-bilesik': 'numbers.sayilar.yuzler-bilesik',
  'private.day5.sayilar.bin': 'numbers.sayilar.bin',
  'private.day5.form.alanlar': 'personal-info.form.alanlar',
  'private.day5.form.kinder': 'personal-info.form.kinder',
  'private.day5.dogum.soru-cevap': 'personal-info.dogum.soru-cevap',
  'private.day5.dogum.aciklik': 'personal-info.dogum.aciklik',
  'private.day5.medeni-hal.ledig-verheiratet': 'personal-info.medeni-hal.ledig-verheiratet',
  'private.day5.tanitma.model': 'personal-info.tanitma.model',
  'private.day5.tanitma.ornekler': 'personal-info.tanitma.ornekler',
  'private.day5.baglac.und': 'sentence-building.baglac.und',
  'private.day5.baglac.aber': 'sentence-building.baglac.aber',
  'private.day5.kelime.leider': 'vocabulary.kelime.leider',
  'private.day5.kelime.mehr': 'vocabulary.kelime.mehr',
  'private.day5.kelime.geschwister': 'vocabulary.kelime.geschwister',
  'private.day5.kelime.seit': 'vocabulary.kelime.seit',
  'private.day5.kelime.flughafen': 'vocabulary.kelime.flughafen',
  'private.day5.kelime.moment': 'vocabulary.kelime.moment',
  'private.day5.yiyecek.kelimeler': 'food.yiyecek.kelimeler',
  'private.day6.iyelik.sein-onun': 'pronouns.iyelik.sein-onun',
  'private.day6.iyelik.zincir': 'pronouns.iyelik.zincir',
  'private.day6.cumle.kalip': 'pronouns.cumle.kalip',
  'private.day7.ev.wohnung': 'home.ev.wohnung',
  'private.day7.ev.bad': 'home.ev.bad',
  'private.day7.ev.schlafzimmer': 'home.ev.schlafzimmer',
  'private.day7.ev.flur': 'home.ev.flur',
  'private.day7.ev.kueche': 'home.ev.kueche',
  'private.day7.ev.wohnzimmer': 'home.ev.wohnzimmer',
  'private.day7.ev.toilette': 'home.ev.toilette',
  'private.day7.moebel.genel': 'home.moebel.genel',
  'private.day7.moebel.schrank': 'home.moebel.schrank',
  'private.day7.moebel.bett': 'home.moebel.bett',
  'private.day7.moebel.sofa': 'home.moebel.sofa',
  'private.day7.moebel.sessel': 'home.moebel.sessel',
  'private.day7.moebel.fernseher': 'home.moebel.fernseher',
  'private.day7.moebel.teppich-regal': 'home.moebel.teppich-regal',
  'private.day7.moebel.herd-bad': 'home.moebel.herd-bad',
  'private.day7.moebel.auf-dem-sessel': 'home.moebel.auf-dem-sessel',
  'private.day7.tarif.hell': 'adjectives.tarif.hell',
  'private.day7.tarif.dunkel': 'adjectives.tarif.dunkel',
  'private.day7.tarif.breit': 'adjectives.tarif.breit',
  'private.day7.tarif.schmal': 'adjectives.tarif.schmal',
  'private.day7.tarif.kuehl': 'adjectives.tarif.kuehl',
  'private.day7.tarif.grau': 'adjectives.tarif.grau',
  'private.day7.tarif.gross-klein': 'adjectives.tarif.gross-klein',
  'private.day7.tarif.sein-sifat': 'adjectives.tarif.sein-sifat',
  'private.day7.zamir.der-er': 'pronouns.zamir.der-er',
  'private.day7.zamir.das-es': 'pronouns.zamir.das-es',
  'private.day7.zamir.die-sie': 'pronouns.zamir.die-sie',
  'private.day7.zamir.cumlede': 'pronouns.zamir.cumlede',
  'private.day7.fiil.kennen': 'verbs.fiil.kennen',
  'private.day7.fiil.kennen-cekim': 'verbs.fiil.kennen-cekim',
  'private.day7.fiil.geben': 'verbs.fiil.geben',
  'private.day7.fiil.geben-gibt': 'verbs.fiil.geben-gibt',
  'private.day7.fiil.es-gibt-fark': 'verbs.fiil.es-gibt-fark',
  'private.day7.fiil.anrufen': 'separable-verbs.fiil.anrufen',
  'private.day7.fiil.anrufen-ayrilabilen': 'separable-verbs.fiil.anrufen-ayrilabilen',
  'private.day7.fiil.stellen': 'verbs.fiil.stellen',
  'private.day7.fiil.nicht-yeri': 'articles.fiil.nicht-yeri',
  'private.day7.gefallen.anlam': 'likes.gefallen.anlam',
  'private.day7.gefallen.kalip': 'likes.gefallen.kalip',
  'private.day7.essen.frage': 'food.essen.frage',
  'private.day7.essen.antwort': 'food.essen.antwort',
  'private.day7.essen.nicht-gern': 'food.essen.nicht-gern',
  'private.day7.essen.lieblingsessen': 'food.essen.lieblingsessen',
  'private.day7.trinken.frage': 'food.trinken.frage',
  'private.day7.trinken.lieblingsgetraenk': 'food.trinken.lieblingsgetraenk',
  'private.day7.essen.kelimeler': 'food.essen.kelimeler',
  'private.day7.getraenke.kelimeler': 'food.getraenke.kelimeler',
  'private.day7.essen.hunger-durst': 'food.essen.hunger-durst',
  'private.day7.kaufen.frage': 'shopping.kaufen.frage',
  'private.day7.siklik.immer': 'shopping.siklik.immer',
  'private.day7.siklik.meistens': 'shopping.siklik.meistens',
  'private.day7.siklik.oft': 'shopping.siklik.oft',
  'private.day7.siklik.manchmal': 'shopping.siklik.manchmal',
  'private.day7.siklik.nie': 'shopping.siklik.nie',
  'private.day7.siklik.cumlede': 'shopping.siklik.cumlede',
  'private.day7.kaufen.pro-woche': 'shopping.kaufen.pro-woche',
  'private.day7.alisveris.einkaufszettel': 'shopping.alisveris.einkaufszettel',
  'private.day7.alisveris.einkaufswagen': 'shopping.alisveris.einkaufswagen',
  'private.day7.alisveris.ifadeler': 'shopping.alisveris.ifadeler',
  'private.day7.miktar.flasche': 'shopping.miktar.flasche',
  'private.day7.miktar.packung': 'shopping.miktar.packung',
  'private.day7.miktar.dose': 'shopping.miktar.dose',
  'private.day7.miktar.becher': 'shopping.miktar.becher',
  'private.day7.miktar.bund': 'shopping.miktar.bund',
  'private.day7.miktar.portion': 'shopping.miktar.portion',
  'private.day7.miktar.artikel': 'shopping.miktar.artikel',
  'private.day7.yiyecek.temel': 'food.yiyecek.temel',
  'private.day7.yiyecek.zwiebel': 'food.yiyecek.zwiebel',
  'private.day7.yiyecek.gurke': 'food.yiyecek.gurke',
  'private.day7.yiyecek.essig': 'food.yiyecek.essig',
  'private.day7.yiyecek.oel-pfeffer': 'food.yiyecek.oel-pfeffer',
  'private.day7.yiyecek.haehnchen': 'food.yiyecek.haehnchen',
  'private.day7.yiyecek.sahne': 'food.yiyecek.sahne',
  'private.day7.yiyecek.nuesse': 'food.yiyecek.nuesse',
  'private.day7.fiyat.kosten': 'shopping.fiyat.kosten',
  'private.day7.fiyat.was-kostet': 'shopping.fiyat.was-kostet',
  'private.day7.fiyat.antwort': 'shopping.fiyat.antwort',
  'private.day7.fiyat.wie-viel': 'shopping.fiyat.wie-viel',
  'private.day7.fiyat.teuer': 'shopping.fiyat.teuer',
  'private.day7.brauchen.frage': 'shopping.brauchen.frage',
  'private.day7.brauchen.antwort': 'shopping.brauchen.antwort',
  'private.day7.brauchen.kein': 'shopping.brauchen.kein',
  'private.day7.kelime.gluecklich': 'vocabulary.kelime.gluecklich',
  'private.day7.kelime.gast-leute': 'vocabulary.kelime.gast-leute',
  'private.day7.kelime.fuer-dafuer': 'vocabulary.kelime.fuer-dafuer',
  'private.day7.kelime.nur-etwas-viele': 'vocabulary.kelime.nur-etwas-viele',
  'private.day7.kelime.dazu-fertig-schmeckt': 'vocabulary.kelime.dazu-fertig-schmeckt',
  'private.day7.kelime.zusammen-dort': 'vocabulary.kelime.zusammen-dort',
  'private.day7.kelime.auch': 'vocabulary.kelime.auch',
  'private.day7.evim.model': 'home.evim.model',
  'private.day7.evim.toiletten': 'home.evim.toiletten',
  'private.day7.evim.mein-zimmer': 'home.evim.mein-zimmer',
  'private.day7.evim.schwester': 'home.evim.schwester',
  'private.day7.evim.ihr-zimmer': 'home.evim.ihr-zimmer',
  'private.day7.evim.wohnzimmer': 'home.evim.wohnzimmer',
  'private.day7.evim.balkon': 'home.evim.balkon',
  'private.day7.evim.kueche': 'home.evim.kueche',
  'private.day7.evim.katze': 'home.evim.katze',
  'private.day7.evim.karsilastirma-yok': 'home.evim.karsilastirma-yok',
  'private.day7.kalip.wir-haben': 'home.kalip.wir-haben',
  'private.day7.kalip.ist-sifat': 'home.kalip.ist-sifat',
  'private.day7.kalip.hat-auch': 'home.kalip.hat-auch',
  'private.day7.kalip.es-gibt': 'home.kalip.es-gibt',
  'private.day7.kalip.sira': 'home.kalip.sira',
  'private.day10.trennbar.kural': 'separable-verbs.trennbar.kural',
  'private.day10.trennbar.ornek': 'separable-verbs.trennbar.ornek',
  'private.day10.trennbar.saat-basta': 'separable-verbs.trennbar.saat-basta',
  'private.day10.verb.aufstehen': 'separable-verbs.verb.aufstehen',
  'private.day10.verb.aufwachen': 'separable-verbs.verb.aufwachen',
  'private.day10.verb.uyanma-farki': 'separable-verbs.verb.uyanma-farki',
  'private.day10.verb.anziehen': 'separable-verbs.verb.anziehen',
  'private.day10.verb.ausziehen': 'separable-verbs.verb.ausziehen',
  'private.day10.verb.anziehen-chunk': 'separable-verbs.verb.anziehen-chunk',
  'private.day10.verb.einkaufen': 'separable-verbs.verb.einkaufen',
  'private.day10.verb.einkaufen-cumle': 'separable-verbs.verb.einkaufen-cumle',
  'private.day10.verb.aufraeumen': 'separable-verbs.verb.aufraeumen',
  'private.day10.verb.aufraeumen-cumle': 'separable-verbs.verb.aufraeumen-cumle',
  'private.day10.verb.anrufen': 'separable-verbs.verb.anrufen',
  'private.day10.verb.anrufen-cumle': 'separable-verbs.verb.anrufen-cumle',
  'private.day10.verb.fernsehen': 'separable-verbs.verb.fernsehen',
  'private.day10.verb.fernsehen-cumle': 'separable-verbs.verb.fernsehen-cumle',
  'private.day10.verb.aufhoeren': 'separable-verbs.verb.aufhoeren',
  'private.day10.verb.vorbereiten': 'separable-verbs.verb.vorbereiten',
  'private.day10.verb.einladen': 'separable-verbs.verb.einladen',
  'private.day10.verb.mitbringen': 'separable-verbs.verb.mitbringen',
  'private.day10.verb.aufsetzen': 'separable-verbs.verb.aufsetzen',
  'private.day10.verb.zurueckkommen': 'separable-verbs.verb.zurueckkommen',
  'private.day10.verb.achtgeben': 'separable-verbs.verb.achtgeben',
  'private.day10.verb.gern-sorular': 'separable-verbs.verb.gern-sorular',
  'private.day10.sabah.gesicht': 'daily-routine.sabah.gesicht',
  'private.day10.sabah.zaehne': 'daily-routine.sabah.zaehne',
  'private.day10.sabah.duschen': 'daily-routine.sabah.duschen',
  'private.day10.sabah.fruehstueck-fark': 'daily-routine.sabah.fruehstueck-fark',
  'private.day10.sabah.fruehstuecken': 'daily-routine.sabah.fruehstuecken',
  'private.day10.gun.schule': 'daily-routine.gun.schule',
  'private.day10.gun.lernen': 'daily-routine.gun.lernen',
  'private.day10.gun.mittag': 'daily-routine.gun.mittag',
  'private.day10.gun.hausaufgaben': 'daily-routine.gun.hausaufgaben',
  'private.day10.gun.freunde': 'daily-routine.gun.freunde',
  'private.day10.aksam.abendessen': 'daily-routine.aksam.abendessen',
  'private.day10.aksam.ausziehen': 'daily-routine.aksam.ausziehen',
  'private.day10.aksam.buch': 'daily-routine.aksam.buch',
  'private.day10.aksam.bett': 'daily-routine.aksam.bett',
  'private.day10.aksam.spazieren': 'daily-routine.aksam.spazieren',
  'private.day10.dann.dann': 'sentence-building.dann.dann',
  'private.day10.dann.danach': 'sentence-building.dann.danach',
  'private.day10.dann.v2': 'sentence-building.dann.v2',
  'private.day10.karsi.besuchen': 'separable-verbs.karsi.besuchen',
  'private.day10.karsi.ipucu': 'separable-verbs.karsi.ipucu',
  'private.day10.karsi.liste': 'separable-verbs.karsi.liste',
  'private.day10.soru.wie-spaet': 'time.soru.wie-spaet',
  'private.day10.soru.wie-viel': 'time.soru.wie-viel',
  'private.day10.soru.einheiten': 'time.soru.einheiten',
  'private.day10.resmi.kural': 'time.resmi.kural',
  'private.day10.resmi.ornek': 'time.resmi.ornek',
  'private.day10.gunluk.nach-vor': 'time.gunluk.nach-vor',
  'private.day10.gunluk.viertel': 'time.gunluk.viertel',
  'private.day10.halb.anlam': 'time.halb.anlam',
  'private.day10.halb.ornek': 'time.halb.ornek',
  'private.day10.um.kural': 'time.um.kural',
  'private.day10.um.ornek': 'time.um.ornek',
  'private.day10.tam.model': 'daily-routine.tam.model',
  'private.day10.tam.sablon': 'daily-routine.tam.sablon',
  'private.day10.tam.uretim': 'daily-routine.tam.uretim',
  'private.day10.wort.ruhig': 'vocabulary.wort.ruhig',
  'private.day10.wort.beide': 'vocabulary.wort.beide',
  'private.day10.wort.badewanne': 'home.wort.badewanne',
  'private.day10.wort.zimmer-satz': 'home.wort.zimmer-satz',
  'private.day10.wort.kosten': 'shopping.wort.kosten',
  'private.day10.wort.ziemlich': 'vocabulary.wort.ziemlich',
  'private.day10.wort.frueh-lange': 'vocabulary.wort.frueh-lange',
};

/** Bilinçli olarak emekliye ayrılan eski kavramlar ve nedeni. */
export const RETIRED_LEGACY_CONCEPTS: Record<string, string> = {
  'private.day3.hedef.giris': 'Gün hedefi (ders meta bilgisi) — Almanca bir kavram değildir; konu modelinde anlamsız.',
  'private.day5.hedef.giris': 'Gün hedefi (ders meta bilgisi) — Almanca bir kavram değildir; konu modelinde anlamsız.',
  'private.day6.hedef.giris': 'Gün hedefi (ders meta bilgisi) — Almanca bir kavram değildir; konu modelinde anlamsız.',
  'private.day7.hedef.giris': 'Gün hedefi (ders meta bilgisi) — Almanca bir kavram değildir; konu modelinde anlamsız.',
  'private.day7.hedef.cekirdek': 'Gün hedefi (ders meta bilgisi) — Almanca bir kavram değildir; konu modelinde anlamsız.',
  'private.day10.hedef.giris': 'Gün hedefi (ders meta bilgisi) — Almanca bir kavram değildir; konu modelinde anlamsız.',
};

/**
 * Eski ders günü → o günde işlenen kanonik konular (ilk eleman = eski
 * derin bağlantının yönlendirileceği en ilgili konu).
 */
export const LEGACY_DAY_TOPICS: Record<number, string[]> = {
  1: ['topic.greetings', 'topic.personal-info', 'topic.verbs'],
  2: ['topic.articles', 'topic.sentence-building', 'topic.questions', 'topic.verbs', 'topic.daily-routine'],
  3: ['topic.sentence-building', 'topic.likes', 'topic.akkusativ', 'topic.places', 'topic.separable-verbs', 'topic.verbs', 'topic.adjectives', 'topic.pronouns', 'topic.articles', 'topic.time', 'topic.vocabulary'],
  5: ['topic.personal-info', 'topic.numbers', 'topic.sentence-building', 'topic.vocabulary', 'topic.food'],
  6: ['topic.pronouns'],
  7: ['topic.home', 'topic.adjectives', 'topic.pronouns', 'topic.verbs', 'topic.likes', 'topic.food', 'topic.shopping', 'topic.vocabulary'],
  10: ['topic.separable-verbs', 'topic.daily-routine', 'topic.sentence-building', 'topic.time', 'topic.vocabulary'],
};

/** Eski Genel Tekrar konu grubu kimliği → kanonik konu (ikinci taksonomi kaldırıldı). */
export const LEGACY_REVIEW_GROUP_MAP: Record<string, string> = {
  tanisma: 'topic.greetings',
  'kisisel-bilgiler': 'topic.personal-info',
  'fiil-cekimi': 'topic.verbs',
  artikeller: 'topic.articles',
  'cumle-kurma': 'topic.sentence-building',
  iyelik: 'topic.pronouns',
  'sevmek-istemek': 'topic.likes',
  'es-gibt': 'topic.akkusativ',
  'yer-yon': 'topic.places',
  sifatlar: 'topic.adjectives',
  'sayilar-miktar': 'topic.numbers',
  zaman: 'topic.time',
  saatler: 'topic.time',
  'gunluk-hayat': 'topic.daily-routine',
  yiyecek: 'topic.food',
  alisveris: 'topic.shopping',
  ev: 'topic.home',
  'ayrilabilen-fiiller': 'topic.separable-verbs',
  'mein-tag': 'topic.daily-routine',
  baglaclar: 'topic.sentence-building',
};

/**
 * Bilinçli olarak emekliye ayrılan eski alıştırmalar. Denemeleri kayıtta
 * kalır (geçmiş silinmez) ama oturumlara ve ustalığa girmez.
 */
export const RETIRED_LEGACY_EXERCISES: Record<string, string> = {
  'p3-hed-giris-mc': 'Günün hedefini soran meta soru; Almanca kullanımını ölçmüyor.',
  'p5-hed-giris-mc': 'Günün hedefini soran meta soru; Almanca kullanımını ölçmüyor.',
  'p6-hed-giris-mc': 'Günün hedefini soran meta soru; Almanca kullanımını ölçmüyor.',
  'p7-hed-giris-mc': 'Günün hedefini soran meta soru; Almanca kullanımını ölçmüyor.',
  'p7-hed-cekirdek-mc': 'Günün çekirdek kelime listesini soran meta soru; kelimeler kendi konularında çalışılıyor.',
  'p10-hed-giris-mc': 'Günün hedefini soran meta soru; Almanca kullanımını ölçmüyor.',
};

/** Eski gün derin bağlantısı için en ilgili konu. */
export function legacyDayTopic(day: number): string | undefined {
  return LEGACY_DAY_TOPICS[day]?.[0];
}
