/**
 * 1. Gün — yazilmis alistirma havuzu.
 *
 * Kapsam: alfabe, harf kombinasyonlari, telaffuz kurallari, Buchstabieren,
 * selamlasma ve vedalasma. Tamami `İlk 3 Hafta Özet.md` ve
 * `İlk 3 Hafta Alıştırma.md` icindeki 1. Gün materyaline dayanir.
 */

import type { AuthoredExercise } from '../types.ts';

const TELAFFUZ = 'day1.alfabe-telaffuz';
const SELAM = 'day1.selamlasma-vedalasma';

export const DAY1_EXERCISES: AuthoredExercise[] = [
  /* ---------------------------------------------------------------- */
  /* Kolay — tanıma                                                    */
  /* ---------------------------------------------------------------- */
  {
    id: 'd1-komb-au-mc',
    day: 1,
    topicId: TELAFFUZ,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day1.kombinasyon.au'],
    familyId: 'd1-komb-au',
    instruction: 'Bu harf kombinasyonu nasıl okunur?',
    prompt: 'au',
    answer: '"au" gibi',
    options: ['"au" gibi', '"oy" gibi', '"ay" gibi', 'uzun "i" gibi'],
    explanation: '`au` Türkçedeki gibi "au" okunur: `Haus` → "haus".',
    pronounce: ['Haus'],
  },
  {
    id: 'd1-komb-tsch-mc',
    day: 1,
    topicId: TELAFFUZ,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day1.kombinasyon.tsch'],
    familyId: 'd1-komb-tsch',
    instruction: 'Bu harf kombinasyonu nasıl okunur?',
    prompt: 'tsch',
    answer: '"ç" gibi',
    options: ['"ç" gibi', '"ş" gibi', '"ts" gibi', '"ç" ile "ş" arası'],
    explanation: '`tsch` tek bir "ç" sesidir: `Deutschland`, `tschüss`.',
    pronounce: ['Deutschland', 'tschüss'],
  },
  {
    id: 'd1-ozel-harfler-mc',
    day: 1,
    topicId: TELAFFUZ,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day1.alfabe.ozel-harfler'],
    familyId: 'd1-ozel-harfler',
    instruction: 'Almanca alfabede Türkçede olmayan, Almancaya özel harfler hangileridir?',
    answer: 'ä, ö, ü, ß',
    options: ['ä, ö, ü, ß', 'ç, ğ, ı, ş', 'ä, ö, ü, ç', 'ß, ş, ğ, ı'],
    explanation:
      'Almanca da Latin alfabesini kullanır; ek olarak `ä`, `ö`, `ü` ve `ß` harfleri vardır. `ç`, `ğ`, `ı`, `ş` ise Türkçeye özgüdür.',
    pronounce: ['ä, ö, ü, ß'],
  },
  {
    id: 'd1-eszett-mc',
    day: 1,
    topicId: TELAFFUZ,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day1.alfabe.eszett'],
    familyId: 'd1-eszett',
    instruction: '`ß` harfi (Eszett) hangi harflerin yerine geçer?',
    prompt: 'ß',
    answer: 'iki tane `s` (ss)',
    options: ['iki tane `s` (ss)', 'bir tane `s`', '`z` sesi', '`sch` sesi'],
    explanation: '`ß` harfinin adı "Eszett" / "scharfes S"tir ve `ss` anlamına gelir: `heißen`.',
    pronounce: ['heißen'],
  },
  {
    id: 'd1-sel-hallo-mc',
    day: 1,
    topicId: SELAM,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day1.selamlasma.hallo'],
    familyId: 'd1-sel-hallo',
    instruction: 'Günün her saatinde kullanabileceğin gayri resmî selamlaşma hangisi?',
    answer: 'Hallo',
    options: ['Hallo', 'Guten Morgen', 'Gute Nacht', 'Auf Wiedersehen'],
    explanation: '`Hallo` (ve `Hi`) saatten bağımsızdır; `Guten Morgen/Tag/Abend` saate bağlıdır.',
    pronounce: ['Hallo'],
  },
  {
    id: 'd1-sel-tag-mc',
    day: 1,
    topicId: SELAM,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day1.selamlasma.guten-tag'],
    familyId: 'd1-sel-tag',
    instruction: 'Öğleden sonra saat 14:00’te komşunla karşılaştın. Ne dersin?',
    answer: 'Guten Tag',
    options: ['Guten Tag', 'Guten Morgen', 'Guten Abend', 'Gute Nacht'],
    explanation: '`Guten Tag` öğleden sonra, yaklaşık 16–17’ye kadar kullanılır.',
    pronounce: ['Guten Tag'],
  },
  {
    id: 'd1-veda-tschuess-mc',
    day: 1,
    topicId: SELAM,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day1.vedalasma.tschuess'],
    familyId: 'd1-veda-tschuess',
    instruction: 'Yakın bir arkadaşınla gayri resmî vedalaşıyorsun. Hangisi en uygun?',
    answer: 'Tschüss!',
    options: ['Tschüss!', 'Auf Wiederhören!', 'Guten Abend!', 'Grüß Gott!'],
    explanation: '`Tschüss` (ya da `Ciao`) günlük, samimi bir vedalaşmadır.',
    pronounce: ['Tschüss'],
  },
  {
    id: 'd1-wortschatz-match',
    day: 1,
    topicId: TELAFFUZ,
    type: 'matching',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day1.wortschatz.gunluk'],
    familyId: 'd1-wortschatz',
    instruction: 'Kelime tekrarı: Almanca kelimeleri Türkçe karşılıklarıyla eşleştir.',
    pairs: [
      { left: 'nein', right: 'hayır' },
      { left: 'Haus', right: 'ev' },
      { left: 'Schule', right: 'okul' },
      { left: 'wie', right: 'nasıl' },
    ],
    pronounce: ['nein', 'Haus', 'Schule', 'wie'],
  },

  /* ---------------------------------------------------------------- */
  /* Orta — hatırlama ve uygulama                                      */
  /* ---------------------------------------------------------------- */
  {
    id: 'd1-oku-nein-fill',
    day: 1,
    topicId: TELAFFUZ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day1.kombinasyon.ei'],
    familyId: 'd1-komb-ei',
    instruction: 'Bu kelimenin yaklaşık okunuşunu Türkçe harflerle yaz.',
    validation: { approximation: true },
    prompt: 'nein',
    answer: 'nayn',
    acceptedAnswers: ['nayin'],
    hint: '`ei` kombinasyonunu hatırla.',
    explanation: '`ei` → "ay" okunur, bu yüzden `nein` → "nayn".',
    pronounce: ['nein'],
  },
  {
    id: 'd1-oku-schule-fill',
    day: 1,
    topicId: TELAFFUZ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day1.kombinasyon.sch'],
    familyId: 'd1-komb-sch',
    instruction: 'Bu kelimenin yaklaşık okunuşunu Türkçe harflerle yaz.',
    validation: { approximation: true },
    prompt: 'Schule',
    answer: 'şuule',
    acceptedAnswers: ['şule'],
    explanation: '`sch` → "ş" sesidir: `Schule` → "şuule".',
    pronounce: ['Schule'],
  },
  {
    id: 'd1-oku-wohnen-fill',
    day: 1,
    topicId: TELAFFUZ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day1.telaffuz.sessiz-h'],
    familyId: 'd1-sessiz-h',
    instruction: 'Bu kelimenin yaklaşık okunuşunu Türkçe harflerle yaz.',
    validation: { approximation: true },
    prompt: 'wohnen',
    answer: 'voonen',
    acceptedAnswers: ['vonen'],
    hint: 'Sesli harften sonra gelen `h` okunur mu?',
    explanation: '`w` → "v", ve sesliden sonraki `h` okunmaz, sadece `o`’yu uzatır: "voonen".',
    pronounce: ['wohnen'],
  },
  {
    id: 'd1-oku-wie-fill',
    day: 1,
    topicId: TELAFFUZ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day1.kombinasyon.ie'],
    familyId: 'd1-komb-ie',
    instruction: 'Bu kelimenin yaklaşık okunuşunu Türkçe harflerle yaz.',
    validation: { approximation: true },
    prompt: 'wie',
    answer: 'vii',
    acceptedAnswers: ['vi'],
    explanation: '`w` → "v", `ie` → uzun "i". Bu yüzden `wie` → "vii".',
    pronounce: ['wie'],
  },
  {
    id: 'd1-s-sagen-mc',
    day: 1,
    topicId: TELAFFUZ,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day1.telaffuz.s-z'],
    familyId: 'd1-s-z',
    instruction: '`sagen` kelimesinin başındaki `s` nasıl okunur?',
    prompt: '**s**agen',
    answer: '"z" gibi',
    options: ['"z" gibi', '"s" gibi', '"ş" gibi', '"ts" gibi'],
    explanation:
      'Kelime başında sesli harften önce gelen `s` çoğu zaman "z" gibi okunur: `sagen` → "zagen".',
    pronounce: ['sagen'],
  },
  {
    id: 'd1-oku-lehrer-fill',
    day: 1,
    topicId: TELAFFUZ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day1.telaffuz.kelime-sonu'],
    familyId: 'd1-kelime-sonu',
    instruction: 'Bu kelimenin yaklaşık okunuşunu Türkçe harflerle yaz.',
    validation: { approximation: true },
    prompt: 'Lehrer',
    answer: 'leera',
    acceptedAnswers: ['lehra', 'leraa'],
    hint: 'Sondaki `-er` net bir "er" değildir.',
    explanation:
      'Sesliden sonraki `h` okunmaz (uzatır), kelime sonundaki `-er` ise hafif bir "a" gibi okunur: "Lehra".',
    pronounce: ['Lehrer'],
  },
  {
    id: 'd1-oku-sport-fill',
    day: 1,
    topicId: TELAFFUZ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day1.kombinasyon.sp-st'],
    familyId: 'd1-sp-st',
    instruction: 'Bu kelimenin yaklaşık okunuşunu Türkçe harflerle yaz.',
    validation: { approximation: true },
    prompt: 'Sport',
    answer: 'şport',
    hint: 'Kelime başındaki `sp-` nasıl okunuyordu?',
    explanation:
      'Kelime başındaki `sp-` "şp", `st-` ise "şt" okunur: `Sport` → "şport", `Stuhl` → "ştuul".',
    pronounce: ['Sport', 'Stuhl'],
  },
  {
    id: 'd1-ch-sert-sec-mc',
    day: 1,
    topicId: TELAFFUZ,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day1.kombinasyon.ch-sert', 'day1.kombinasyon.ch-yumusak'],
    familyId: 'd1-ch',
    instruction: 'Hangi kelimede `ch` boğazdan gelen SERT "h" sesiyle okunur?',
    answer: 'doch',
    options: ['doch', 'ich', 'Milch', 'nicht'],
    explanation:
      '`ch` sesi kendinden önceki harfe bağlıdır: `a, o, u` sonrasında sert (`doch`), `e, i, ä, ö, ü` sonrasında yumuşaktır (`ich`, `Milch`, `nicht`).',
    pronounce: ['doch', 'ich'],
  },
  {
    id: 'd1-sel-ctx-morgen-frei',
    day: 1,
    topicId: SELAM,
    type: 'free-text',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day1.selamlasma.guten-morgen'],
    familyId: 'd1-sel-morgen',
    instruction: 'Saat sabah 08:30 ve öğretmeninle karşılaştın. Ne dersin?',
    answer: 'Guten Morgen!',
    acceptedAnswers: ['Guten Morgen', 'Hallo!', 'Hallo'],
    openEnded: true,
    explanation: '`Guten Morgen` sabah, yaklaşık saat 9’a kadar kullanılır.',
    pronounce: ['Guten Morgen'],
  },
  {
    id: 'd1-veda-ctx-telefon-frei',
    day: 1,
    topicId: SELAM,
    type: 'free-text',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day1.vedalasma.auf-wiederhoeren'],
    familyId: 'd1-wiederhoeren',
    instruction: 'Telefonda konuşman bitti. Nasıl vedalaşırsın?',
    answer: 'Auf Wiederhören!',
    acceptedAnswers: ['Auf Wiederhören'],
    hint: '`hören` = duymak.',
    explanation: 'Telefonda `Auf Wiederhören` denir, çünkü karşındakini görmüyor duyuyorsun.',
    pronounce: ['Auf Wiederhören'],
  },
  {
    id: 'd1-veda-ctx-gleich-frei',
    day: 1,
    topicId: SELAM,
    type: 'free-text',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day1.vedalasma.bis-kaliplari'],
    familyId: 'd1-bis',
    instruction: 'Arkadaşına birazdan geri geleceğini söyleyerek ayrılıyorsun. Ne dersin?',
    answer: 'Bis gleich!',
    acceptedAnswers: ['Bis gleich', 'Bis nachher!', 'Bis nachher'],
    openEnded: true,
    explanation: '`Bis gleich` = birazdan görüşürüz. `Bis nachher` = daha sonra görüşürüz.',
    pronounce: ['Bis gleich'],
  },
  {
    id: 'd1-dialog-abend-mc',
    day: 1,
    topicId: SELAM,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day1.selamlasma.guten-abend'],
    familyId: 'd1-sel-abend',
    instruction: 'Mini diyalog: B ne demeli?',
    prompt: 'A: Guten Abend!\nB: ______',
    answer: 'Guten Abend!',
    options: ['Guten Abend!', 'Gute Nacht!', 'Guten Morgen!', 'Auf Wiederhören!'],
    explanation: 'Selamlaşmaya aynı kalıpla karşılık verilir. `Gute Nacht` ise vedalaşmadır.',
    pronounce: ['Guten Abend'],
  },
  {
    id: 'd1-dialog-veda-frei',
    day: 1,
    topicId: SELAM,
    type: 'free-text',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day1.vedalasma.tschuess', 'day1.vedalasma.bis-kaliplari'],
    familyId: 'd1-veda-yuz',
    instruction: 'Mini diyalog: B ne diyebilir? Bir vedalaşma kalıbı yaz.',
    prompt: 'A: Tschüss!\nB: ______',
    answer: 'Tschüss!',
    acceptedAnswers: ['Tschüss', 'Bis bald!', 'Bis bald', 'Bis dann!', 'Bis dann', 'Ciao!'],
    openEnded: true,
    explanation: 'Vedalaşmaya `Tschüss`, `Bis bald` ya da `Bis dann` ile karşılık verebilirsin.',
    pronounce: ['Tschüss', 'Bis bald'],
  },
  {
    id: 'd1-sesli-selam',
    day: 1,
    topicId: SELAM,
    type: 'spoken',
    difficulty: 'medium',
    skill: 'speaking',
    conceptIds: [
      'day1.selamlasma.guten-morgen',
      'day1.selamlasma.guten-abend',
      'day1.vedalasma.auf-wiedersehen',
    ],
    instruction: 'Sesli görev: ekrana bakmadan sırayla söyle.',
    requirements: [
      'Sabah birini selamla.',
      'Akşam birini selamla.',
      'Yüz yüze vedalaş.',
      'Telefonda vedalaş.',
    ],
    pronounce: ['Guten Morgen', 'Guten Abend', 'Auf Wiedersehen', 'Auf Wiederhören'],
  },

  /* ---------------------------------------------------------------- */
  /* Zor — üretim ve düzeltme                                          */
  /* ---------------------------------------------------------------- */
  {
    id: 'd1-hata-gute-morgen',
    day: 1,
    topicId: SELAM,
    type: 'error-correction',
    difficulty: 'hard',
    skill: 'correction',
    conceptIds: ['day1.selamlasma.guten-morgen', 'day1.selamlasma.gute-nacht'],
    familyId: 'd1-gute-nacht',
    instruction: 'Cümledeki hatayı bul ve doğrusunu yaz.',
    prompt: 'Gute Morgen!',
    answer: 'Guten Morgen!',
    explanation:
      'Selamlaşma kalıplarında `Guten` kullanılır: `Guten Morgen`, `Guten Tag`, `Guten Abend`. Yalnızca vedalaşma kalıbı `Gute Nacht`ta `Gute` vardır.',
    pronounce: ['Guten Morgen'],
  },
  {
    id: 'd1-hata-wiedersehen-yuz',
    day: 1,
    topicId: SELAM,
    type: 'error-correction',
    difficulty: 'hard',
    skill: 'correction',
    conceptIds: ['day1.vedalasma.auf-wiedersehen', 'day1.vedalasma.auf-wiederhoeren'],
    familyId: 'd1-veda-yuz',
    instruction: 'Yüz yüze vedalaşıyorsun. Kalıbı düzelt.',
    prompt: 'Auf Wiederhören!',
    answer: 'Auf Wiedersehen!',
    explanation:
      '`sehen` = görmek, `hören` = duymak. Yüz yüzeyken `Auf Wiedersehen`, telefonda `Auf Wiederhören` denir.',
    pronounce: ['Auf Wiedersehen'],
  },
  {
    id: 'd1-veda-ctx-nacht-frei',
    day: 1,
    topicId: SELAM,
    type: 'free-text',
    difficulty: 'hard',
    skill: 'production',
    conceptIds: ['day1.selamlasma.gute-nacht'],
    familyId: 'd1-gute-nacht',
    instruction: 'Gece 22:00’de arkadaşından ayrılıyorsun. Doğru kalıbı yaz.',
    answer: 'Gute Nacht!',
    acceptedAnswers: ['Gute Nacht'],
    hint: 'Dikkat: bu kalıpta `Guten` değil…',
    explanation:
      '`Gute Nacht` bir vedalaşma kalıbıdır ve `Guten` değil `Gute` alır. Gece 20’den sonra kullanılır.',
    validation: { noTypoTolerance: true },
    pronounce: ['Gute Nacht'],
  },
  {
    id: 'd1-veda-ctx-woche-frei',
    day: 1,
    topicId: SELAM,
    type: 'free-text',
    difficulty: 'hard',
    skill: 'production',
    conceptIds: ['day1.vedalasma.bis-kaliplari'],
    familyId: 'd1-bis',
    instruction: 'Arkadaşınla gelecek hafta görüşeceksiniz. Vedalaşırken bunu söyle.',
    answer: 'Bis nächste Woche!',
    acceptedAnswers: ['Bis nächste Woche'],
    explanation: '`Bis` + zaman kalıbı: `Bis bald`, `Bis Montag`, `Bis nächste Woche`.',
    pronounce: ['Bis nächste Woche'],
  },
  {
    id: 'd1-oku-deutschland-frei',
    day: 1,
    topicId: TELAFFUZ,
    type: 'free-text',
    difficulty: 'hard',
    skill: 'recall',
    conceptIds: ['day1.kombinasyon.tsch', 'day1.kombinasyon.eu-aeu'],
    familyId: 'd1-komb-tsch',
    instruction: 'Bu kelimenin yaklaşık okunuşunu Türkçe harflerle yaz.',
    validation: { approximation: true },
    prompt: 'Deutschland',
    answer: 'doyçlant',
    acceptedAnswers: ['doyçland', 'doyçlant.'],
    hint: 'İki kural birleşiyor: `eu` ve `tsch`.',
    explanation: '`eu` → "oy", `tsch` → "ç". Kelime sonundaki `d` sert okunur: "doyçlant".',
    pronounce: ['Deutschland'],
  },
  {
    id: 'd1-buchstabiere-frei',
    day: 1,
    topicId: TELAFFUZ,
    type: 'free-text',
    difficulty: 'hard',
    skill: 'production',
    conceptIds: ['day1.alfabe.buchstabieren'],
    familyId: 'd1-buchstabieren',
    instruction: 'Adını söyledin ama karşındaki anlamadı. Harf harf söyleyeceğini nasıl belirtirsin?',
    answer: 'Ich buchstabiere.',
    acceptedAnswers: ['Ich buchstabiere'],
    explanation:
      '`Ich buchstabiere.` = "Harf harf söylüyorum." Anlaşılmadığında ismini kodlamaya başlamadan önce kullanılır.',
    pronounce: ['Ich buchstabiere'],
  },
  {
    id: 'd1-sec-dogru-kullanim-mc',
    day: 1,
    topicId: SELAM,
    type: 'multiple-choice',
    difficulty: 'hard',
    skill: 'recognition',
    conceptIds: [
      'day1.selamlasma.gute-nacht',
      'day1.selamlasma.guten-abend',
      'day1.selamlasma.guten-morgen',
    ],
    familyId: 'd1-sel-abend',
    instruction: 'Hangi seçenekte hem kalıp hem de kullanım şekli doğru?',
    answer: '`Guten Abend` — akşam selamlaşması',
    options: [
      '`Guten Abend` — akşam selamlaşması',
      '`Guten Nacht` — gece vedalaşması',
      '`Gute Morgen` — sabah selamlaşması',
      '`Gute Nacht` — sabah selamlaşması',
    ],
    explanation:
      'Doğru yazımlar: `Guten Morgen`, `Guten Tag`, `Guten Abend` (selamlaşma) ve `Gute Nacht` (vedalaşma).',
    pronounce: ['Guten Abend'],
  },
];
