/**
 * 2. Gün — yazilmis alistirma havuzu.
 *
 * Kapsam: kisi zamirleri, duzenli fiil cekimi, `sein` / `haben`, artikeller ve
 * isimlerin buyuk harfle yazilmasi. Kullanilan kelimeler 1.–2. Gün
 * materyalindekilerle sinirlidir (kommen, gehen, wohnen, heißen, trinken,
 * Wasser, Auto, Zeit, Hunger, müde, Tisch, Lampe, Buch, Lehrer, Vater).
 */

import type { AuthoredExercise } from '../types.ts';

const ZAMIR = 'day2.kisi-zamirleri';
const KONJ = 'day2.fiil-cekimi';
const SEIN = 'day2.sein-haben';
const ARTIKEL = 'day2.artikel';

export const DAY2_EXERCISES: AuthoredExercise[] = [
  /* ---------------------------------------------------------------- */
  /* Kolay                                                             */
  /* ---------------------------------------------------------------- */
  {
    id: 'd2-zamir-ich-fill',
    day: 2,
    topicId: ZAMIR,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day2.zamir.ich'],
    familyId: 'd2-zamir-ich',
    instruction: 'Türkçe zamirin Almancasını yaz.',
    prompt: 'ben',
    answer: 'ich',
    pronounce: ['ich'],
  },
  {
    id: 'd2-zamir-ihr-fill',
    day: 2,
    topicId: ZAMIR,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day2.zamir.ihr'],
    familyId: 'd2-zamir-ihr',
    instruction: 'Türkçe zamirin Almancasını yaz.',
    prompt: 'siz (2+ kişiye samimi)',
    answer: 'ihr',
    explanation: '`ihr` bir gruba samimi hitaptır; resmî "siz" ise `Sie`dir.',
    pronounce: ['ihr'],
  },
  {
    id: 'd2-zamir-sie-onlar-fill',
    day: 2,
    topicId: ZAMIR,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day2.zamir.sie-onlar'],
    familyId: 'd2-zamir-sie-onlar',
    instruction: 'Türkçe zamirin Almancasını yaz.',
    prompt: 'onlar',
    answer: 'sie',
    explanation:
      'Küçük harfle `sie` "onlar" demektir. Büyük harfle `Sie` ise resmî "siz"dir.',
    pronounce: ['sie'],
  },
  {
    id: 'd2-zamir-match',
    day: 2,
    topicId: ZAMIR,
    type: 'matching',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day2.zamir.ich', 'day2.zamir.du', 'day2.zamir.wir', 'day2.zamir.er-sie-es'],
    familyId: 'd2-zamir-genel',
    instruction: 'Zamirleri Türkçe karşılıklarıyla eşleştir.',
    pairs: [
      { left: 'ich', right: 'ben' },
      { left: 'du', right: 'sen' },
      { left: 'er', right: 'o (erkek)' },
      { left: 'wir', right: 'biz' },
    ],
    pronounce: ['ich', 'du', 'er', 'wir'],
  },
  {
    id: 'd2-konj-kok-mc',
    day: 2,
    topicId: KONJ,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day2.konjugation.kok'],
    familyId: 'd2-konj-kok',
    instruction: '`wohnen` fiilinin kökü nedir?',
    prompt: 'wohnen',
    answer: 'wohn',
    options: ['wohn', 'wohne', 'wohnen', 'ohnen'],
    explanation: 'Fiil kökünü bulmak için mastardaki `-en` atılır: `wohn-en` → `wohn`.',
    pronounce: ['wohnen', 'wohn', 'wohne', 'ohnen'],
  },
  {
    id: 'd2-artikel-lampe-mc',
    day: 2,
    topicId: ARTIKEL,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day2.artikel.kelimeler', 'day2.artikel.der-die-das'],
    familyId: 'd2-artikel-lampe',
    instruction: 'Doğru artikeli seç. (lamba)',
    prompt: '___ Lampe',
    answer: 'die',
    options: ['der', 'die', 'das'],
    explanation: '`die Lampe` — dişil. Her ismi artikeliyle birlikte ezberle.',
    validation: { noTypoTolerance: true },
    pronounce: ['die Lampe'],
  },
  {
    id: 'd2-sein-du-fill',
    day: 2,
    topicId: SEIN,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day2.sein.cekim'],
    familyId: 'd2-sein-du',
    instruction: '`sein` fiilini doğru çek.',
    prompt: 'du ___',
    answer: 'bist',
    pronounce: ['Du bist müde.'],
  },
  {
    id: 'd2-haben-wir-fill',
    day: 2,
    topicId: SEIN,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day2.haben.cekim'],
    familyId: 'd2-haben-wir',
    instruction: '`haben` fiilini doğru çek.',
    prompt: 'wir ___',
    answer: 'haben',
    pronounce: ['Wir haben Zeit.'],
  },

  /* ---------------------------------------------------------------- */
  /* Orta                                                              */
  /* ---------------------------------------------------------------- */
  {
    id: 'd2-zamir-du-ihr-mc',
    day: 2,
    topicId: ZAMIR,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day2.zamir.du-ihr-farki'],
    familyId: 'd2-zamir-du-ihr',
    instruction: 'Üç arkadaşına birlikte hitap ediyorsun. Hangi zamiri kullanırsın?',
    answer: 'ihr',
    options: ['ihr', 'du', 'Sie', 'wir'],
    explanation: '`du` tek kişiye, `ihr` iki ve daha fazla kişiye samimi hitaptır.',
    pronounce: ['ihr'],
  },
  {
    id: 'd2-zamir-resmi-sie-mc',
    day: 2,
    topicId: ZAMIR,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day2.zamir.sie-Sie-farki', 'day2.zamir.Sie-resmi'],
    familyId: 'd2-zamir-Sie',
    instruction: 'Yeni tanıştığın bir doktora hitap ediyorsun. Hangi zamiri kullanırsın?',
    answer: 'Sie',
    options: ['Sie', 'sie', 'du', 'ihr'],
    explanation:
      'Resmî "siz" büyük harfle `Sie` yazılır. Küçük harfli `sie` "onlar" (ya da "o — kadın") demektir.',
    validation: { caseSensitive: true },
    pronounce: ['Sie'],
  },
  {
    id: 'd2-konj-er-kommt-fill',
    day: 2,
    topicId: KONJ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day2.konjugation.er-t', 'day2.konjugation.duzenli-fiiller'],
    familyId: 'd2-konj-er-kommen',
    instruction: '`kommen` fiilini doğru çek.',
    prompt: 'er ___',
    answer: 'kommt',
    explanation: '`er/sie/es` ile düzenli fiiller `-t` takısı alır: `komm` + `t` = `kommt`.',
    pronounce: ['kommt'],
  },
  {
    id: 'd2-konj-ihr-fill',
    day: 2,
    topicId: KONJ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day2.konjugation.ihr-t', 'day2.konjugation.duzenli-fiiller'],
    familyId: 'd2-konj-ihr-trinken',
    instruction: '`trinken` fiilini doğru çek.',
    prompt: 'ihr ___',
    answer: 'trinkt',
    explanation: '`ihr` ile düzenli fiiller `-t` alır: `trink` + `t` = `trinkt`.',
    pronounce: ['trinkt'],
  },
  {
    id: 'd2-konj-sie-onlar-fill',
    day: 2,
    topicId: KONJ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day2.konjugation.sie-en', 'day2.konjugation.duzenli-fiiller'],
    familyId: 'd2-konj-sie-wohnen',
    instruction: '`wohnen` fiilini doğru çek.',
    prompt: 'sie (onlar) ___',
    answer: 'wohnen',
    explanation: '`wir` ve `sie/Sie` ile fiil mastar haliyle aynıdır: `-en`.',
    pronounce: ['wohnen'],
  },
  {
    id: 'd2-konj-heissen-du-fill',
    day: 2,
    topicId: KONJ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day2.konjugation.du-st', 'day2.konjugation.duzenli-fiiller'],
    familyId: 'd2-konj-du-heissen',
    instruction: '`heißen` fiilini doğru çek.',
    prompt: 'du ___',
    answer: 'heißt',
    acceptedAnswers: ['heisst'],
    explanation: '`heiß` + `st` → `heißt`. `ß` zaten bir `s` sesi taşıdığı için tek `t` yazılır.',
    pronounce: ['heißt'],
  },
  {
    id: 'd2-konj-match',
    day: 2,
    topicId: KONJ,
    type: 'matching',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: [
      'day2.konjugation.ich-e',
      'day2.konjugation.du-st',
      'day2.konjugation.er-t',
      'day2.konjugation.wir-en',
    ],
    familyId: 'd2-konj-tablo',
    instruction: '`gehen` fiilinin çekimlerini zamirlerle eşleştir.',
    pairs: [
      { left: 'ich', right: 'gehe' },
      { left: 'du', right: 'gehst' },
      { left: 'er', right: 'geht' },
      { left: 'wir', right: 'gehen' },
    ],
    pronounce: ['gehe', 'gehst', 'geht', 'gehen'],
  },
  {
    id: 'd2-konj-satz-er-fill',
    day: 2,
    topicId: KONJ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day2.konjugation.er-t'],
    familyId: 'd2-konj-er-wohnen',
    instruction: 'Boşluğu `wohnen` fiiliyle doğru çekimde doldur.',
    prompt: 'Er ___ in Berlin.',
    answer: 'wohnt',
    pronounce: ['Er wohnt in Berlin.'],
  },
  {
    id: 'd2-konj-satz-ihr-fill',
    day: 2,
    topicId: KONJ,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day2.konjugation.ihr-t'],
    familyId: 'd2-konj-ihr-trinken',
    instruction: 'Boşluğu `trinken` fiiliyle doğru çekimde doldur.',
    prompt: 'Ihr ___ Wasser.',
    answer: 'trinkt',
    pronounce: ['Ihr trinkt Wasser.'],
  },
  {
    id: 'd2-sein-ihr-fill',
    day: 2,
    topicId: SEIN,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day2.sein.cekim'],
    familyId: 'd2-sein-ihr',
    instruction: '`sein` fiilini doğru çek.',
    prompt: 'ihr ___',
    answer: 'seid',
    explanation: '`sein` düzensizdir: bin, bist, ist, sind, **seid**, sind.',
    pronounce: ['seid'],
  },
  {
    id: 'd2-haben-ihr-fill',
    day: 2,
    topicId: SEIN,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day2.haben.cekim'],
    familyId: 'd2-haben-ihr',
    instruction: '`haben` fiilini doğru çek.',
    prompt: 'ihr ___',
    answer: 'habt',
    explanation: '`haben` düzensizdir: habe, hast, hat, haben, **habt**, haben.',
    pronounce: ['habt'],
  },
  {
    id: 'd2-sein-haben-secim-mc',
    day: 2,
    topicId: SEIN,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day2.sein-haben.ayrim'],
    familyId: 'd2-sein-haben-secim',
    instruction: 'Hangi cümle doğru?',
    answer: 'Ich bin Lehrer.',
    options: ['Ich bin Lehrer.', 'Ich habe Lehrer.', 'Ich bin ein Auto.', 'Ich habe müde.'],
    explanation:
      'Kim olduğunu söylerken `sein` kullanılır: `Ich bin Lehrer.` Sahiplik için `haben`: `Ich habe ein Auto.`',
    pronounce: ['Mein Vater ist Lehrer.'],
  },
  {
    id: 'd2-haben-hunger-fill',
    day: 2,
    topicId: SEIN,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day2.haben.var-yok', 'day2.haben.cekim'],
    familyId: 'd2-haben-hunger',
    instruction: 'Boşluğu doğru fiille doldur. (Türkçesi: "Açım.")',
    prompt: 'Ich ___ Hunger.',
    answer: 'habe',
    hint: 'Almanca bu kalıpta "sahip olmak" fiilini kullanır.',
    explanation:
      '`Ich habe Hunger.` kelimesi kelimesine "açlığa sahibim" demektir ama Türkçeye "Açım" diye çevrilir.',
    pronounce: ['Ich habe Hunger.'],
  },
  {
    id: 'd2-artikel-cogul-mc',
    day: 2,
    topicId: ARTIKEL,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day2.artikel.cogul-die'],
    familyId: 'd2-artikel-cogul',
    instruction: 'Çoğul isimlerde hangi artikel kullanılır?',
    answer: 'her zaman `die`',
    options: ['her zaman `die`', 'her zaman `der`', 'her zaman `das`', 'ismin cinsiyetine göre değişir'],
    explanation: 'Çoğulda cinsiyet fark etmez; artikel her zaman `die`dir.',
  },
  {
    id: 'd2-artikel-ezber-mc',
    day: 2,
    topicId: ARTIKEL,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day2.artikel.ezber'],
    familyId: 'd2-artikel-ezber',
    instruction: 'Yeni bir Almanca isim öğrenirken en doğru yaklaşım hangisi?',
    answer: 'Kelimeyi artikeliyle birlikte ezberlemek',
    options: [
      'Kelimeyi artikeliyle birlikte ezberlemek',
      'Önce kelimeyi, artikeli sonra öğrenmek',
      'Artikeli kelimenin anlamından çıkarmak',
      'Artikeli kelimenin son harfinden bulmak',
    ],
    explanation:
      'Bir ismin artikelinin neden `der/die/das` olduğunun çoğu zaman mantıklı bir açıklaması yoktur; bu yüzden her kelime artikeliyle birlikte ezberlenir.',
  },
  {
    id: 'd2-artikel-birlikte-ezber-mc',
    day: 2,
    topicId: ARTIKEL,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day2.artikel.ezber', 'day2.artikel.der-die-das'],
    familyId: 'd2-artikel-ezber',
    instruction: 'Yeni bir Almanca isim öğrenirken en doğru yol hangisidir?',
    answer: 'der Tisch gibi artikeliyle birlikte öğrenmek',
    options: [
      'der Tisch gibi artikeliyle birlikte öğrenmek',
      'Önce yalnızca Tisch kelimesini öğrenmek',
      'Artikeli Türkçedeki anlamından tahmin etmek',
      'Artikeli cümlenin sonunda eklemek',
    ],
    explanation: 'Artikel çoğu zaman anlamdan tahmin edilmez. Bu yüzden ismi `der Tisch` gibi artikeliyle birlikte öğrenirsin.',
    pronounce: ['der Tisch'],
  },
  {
    id: 'd2-isim-buyuk-harf-mc',
    day: 2,
    topicId: ARTIKEL,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day2.artikel.isim-buyuk-harf'],
    familyId: 'd2-isim-buyuk',
    instruction: 'Hangi cümle yazım açısından doğru?',
    answer: 'Mein Vater ist Lehrer.',
    options: [
      'Mein Vater ist Lehrer.',
      'Mein vater ist lehrer.',
      'mein Vater ist Lehrer.',
      'Mein Vater ist lehrer.',
    ],
    explanation:
      'Almancada artikeli olan **her isim** cümle içinde büyük harfle başlar — sadece özel isimler değil.',
    validation: { caseSensitive: true },
    pronounce: ['Mein Vater ist Lehrer.'],
  },
  {
    id: 'd2-wortschatz-fiil-match',
    day: 2,
    topicId: KONJ,
    type: 'matching',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day2.wortschatz.gunluk', 'day2.konjugation.duzenli-fiiller'],
    familyId: 'd2-wortschatz',
    instruction: 'Kelime tekrarı: fiilleri Türkçe karşılıklarıyla eşleştir.',
    pairs: [
      { left: 'kommen', right: 'gelmek' },
      { left: 'wohnen', right: 'oturmak' },
      { left: 'heißen', right: 'adı olmak' },
      { left: 'trinken', right: 'içmek' },
    ],
    pronounce: ['kommen', 'wohnen', 'heißen', 'trinken'],
  },
  {
    id: 'd2-sesli-zamir',
    day: 2,
    topicId: KONJ,
    type: 'spoken',
    difficulty: 'medium',
    skill: 'speaking',
    conceptIds: ['day2.konjugation.er-t', 'day2.konjugation.ihr-t', 'day2.sein.cekim'],
    instruction: 'Sesli görev: her biri için tek bir cümle kur ve yüksek sesle söyle.',
    requirements: [
      '`er` + `wohnen` ile bir cümle.',
      '`ihr` + `trinken` ile bir cümle.',
      '`sein` ile kendini tanıtan bir cümle.',
    ],
    pronounce: ['Er wohnt in Berlin.', 'Ihr trinkt Wasser.', 'Ich bin Mustafa.'],
  },

  /* ---------------------------------------------------------------- */
  /* Zor                                                               */
  /* ---------------------------------------------------------------- */
  {
    id: 'd2-hata-ihr-seid',
    day: 2,
    topicId: SEIN,
    type: 'error-correction',
    difficulty: 'hard',
    skill: 'correction',
    conceptIds: ['day2.sein.cekim'],
    familyId: 'd2-sein-ihr',
    instruction: 'Cümledeki hatayı bul ve doğrusunu yaz.',
    prompt: 'Ihr sind müde.',
    answer: 'Ihr seid müde.',
    explanation: '`ihr` ile `sein` fiili `seid` olur; `sind` ise `wir` ve `sie/Sie` içindir.',
    pronounce: ['Ihr seid müde.'],
  },
  {
    id: 'd2-hata-er-kommen',
    day: 2,
    topicId: KONJ,
    type: 'error-correction',
    difficulty: 'hard',
    skill: 'correction',
    conceptIds: ['day2.konjugation.er-t'],
    familyId: 'd2-konj-er-kommen',
    instruction: 'Cümledeki hatayı bul ve doğrusunu yaz.',
    prompt: 'Er kommen aus Deutschland.',
    answer: 'Er kommt aus Deutschland.',
    explanation:
      '`kommen` fiilinin kökü `komm-`. `er/sie/es` ile düzenli fiiller `-t` alır: `komm` + `t` = `kommt`.',
    pronounce: ['Er kommt aus Deutschland.'],
  },
  {
    id: 'd2-hata-haben-sein',
    day: 2,
    topicId: SEIN,
    type: 'error-correction',
    difficulty: 'hard',
    skill: 'correction',
    conceptIds: ['day2.sein-haben.ayrim'],
    familyId: 'd2-sein-haben-secim',
    instruction: 'Cümledeki hatayı bul ve doğrusunu yaz. (Anlamı: "Bir arabam var.")',
    prompt: 'Ich bin ein Auto.',
    answer: 'Ich habe ein Auto.',
    explanation:
      'Sahiplik belirtirken `haben` kullanılır. `Ich bin ein Auto.` "Ben bir arabayım" demektir.',
    pronounce: ['Ich habe ein Auto.'],
  },
  {
    id: 'd2-satz-wir-trinken',
    day: 2,
    topicId: KONJ,
    type: 'sentence-builder',
    difficulty: 'hard',
    skill: 'production',
    conceptIds: ['day2.konjugation.wir-en', 'day2.konjugation.ornek-cumleler'],
    familyId: 'd2-konj-wir-trinken',
    instruction: 'Kelimelerle doğru Almanca cümleyi kur.',
    prompt: 'wir, trinken, Wasser',
    answer: 'Wir trinken Wasser.',
    pronounce: ['Wir trinken Wasser.'],
  },
  {
    id: 'd2-satz-du-gehen',
    day: 2,
    topicId: KONJ,
    type: 'sentence-builder',
    difficulty: 'hard',
    skill: 'production',
    conceptIds: ['day2.konjugation.du-st', 'day2.konjugation.ornek-cumleler'],
    familyId: 'd2-konj-du-gehen',
    instruction: 'Kelimelerle doğru Almanca cümleyi kur.',
    prompt: 'du, gehen, nach Hause',
    answer: 'Du gehst nach Hause.',
    explanation: '`du` ile `gehen` → `gehst`. Cümle büyük harfle başlar.',
    pronounce: ['Du gehst nach Hause.'],
  },
  {
    id: 'd2-ceviri-ich-habe-zeit',
    day: 2,
    topicId: SEIN,
    type: 'free-text',
    difficulty: 'hard',
    skill: 'production',
    conceptIds: ['day2.haben.var-yok', 'day2.haben.cekim'],
    familyId: 'd2-haben-ich',
    instruction: 'Seçenek yok — Almancaya çevir.',
    prompt: 'Zamanım var.',
    answer: 'Ich habe Zeit.',
    acceptedAnswers: ['Ich habe Zeit'],
    explanation: 'Türkçedeki "var" Almancada `haben` ile kurulur: `Ich habe Zeit.`',
    pronounce: ['Ich habe Zeit.'],
  },
  {
    id: 'd2-ceviri-du-kommst',
    day: 2,
    topicId: KONJ,
    type: 'free-text',
    difficulty: 'hard',
    skill: 'production',
    conceptIds: ['day2.konjugation.du-st', 'day2.konjugation.simdiki-genis'],
    familyId: 'd2-konj-du-kommen',
    instruction: 'Seçenek yok — Almancaya çevir.',
    prompt: 'Almanya’dan geliyorsun.',
    answer: 'Du kommst aus Deutschland.',
    acceptedAnswers: ['Du kommst aus Deutschland'],
    hint: '`du` ile fiil hangi takıyı alır?',
    explanation:
      'Almancada şimdiki zaman için ayrı bir çekim yoktur: `Du kommst` hem "geliyorsun" hem "gelirsin" demektir.',
    pronounce: ['Du kommst aus Deutschland.'],
  },
];
