/**
 * 3. Gün — yazilmis alistirma havuzu.
 *
 * Kapsam: kendini tanitma sorulari, `du` / `Sie` ayrimi, nerede oturdugunu ve
 * nereli oldugunu soyleme, `Wie geht's?` ve cevaplari, sayilar.
 * Cekimler 2. Gün'de ogrenilen kurallara dayanir.
 */

import type { AuthoredExercise } from '../types.ts';

const TANIT = 'day3.kendini-tanitma';
const NASIL = 'day3.nasilsin';
const SAYI = 'day3.sayilar';

export const DAY3_EXERCISES: AuthoredExercise[] = [
  /* ---------------------------------------------------------------- */
  /* Kolay                                                             */
  /* ---------------------------------------------------------------- */
  {
    id: 'd3-say-0-10-match',
    day: 3,
    topicId: SAYI,
    type: 'matching',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day3.sayilar.0-10'],
    familyId: 'd3-say-temel',
    instruction: 'Sayıları rakamlarıyla eşleştir.',
    pairs: [
      { left: 'drei', right: '3' },
      { left: 'fünf', right: '5' },
      { left: 'acht', right: '8' },
      { left: 'zehn', right: '10' },
    ],
    pronounce: ['drei', 'fünf', 'acht', 'zehn'],
  },
  {
    id: 'd3-say-4-fill',
    day: 3,
    topicId: SAYI,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day3.sayilar.0-10'],
    familyId: 'd3-say-4',
    instruction: 'Almancaya çevir:',
    prompt: '4',
    answer: 'vier',
    pronounce: ['vier'],
  },
  {
    id: 'd3-say-7-fill',
    day: 3,
    topicId: SAYI,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day3.sayilar.0-10'],
    familyId: 'd3-say-7',
    instruction: 'Almancaya çevir:',
    prompt: '7',
    answer: 'sieben',
    pronounce: ['sieben'],
  },
  {
    id: 'd3-say-0-fill',
    day: 3,
    topicId: SAYI,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day3.sayilar.0-10'],
    familyId: 'd3-say-0',
    instruction: 'Almancaya çevir:',
    prompt: '0',
    answer: 'null',
    pronounce: ['null'],
  },
  {
    id: 'd3-say-12-fill',
    day: 3,
    topicId: SAYI,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day3.sayilar.11-12'],
    familyId: 'd3-say-12',
    instruction: 'Almancaya çevir:',
    prompt: '12',
    answer: 'zwölf',
    acceptedAnswers: ['zwoelf'],
    explanation: '`11` ve `12` kuraldan bağımsız, ayrı ezberlenen sayılardır: `elf`, `zwölf`.',
    pronounce: ['zwölf'],
  },
  {
    id: 'd3-soru-wie-heisst-mc',
    day: 3,
    topicId: TANIT,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day3.soru.wie-heisst-du'],
    familyId: 'd3-wie-heisst',
    instruction: '"Adın ne?" Almancada nasıl sorulur? (samimi)',
    answer: 'Wie heißt du?',
    options: ['Wie heißt du?', 'Wer bist du?', 'Wo wohnst du?', 'Woher kommst du?'],
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'd3-cevap-heisse-fill',
    day: 3,
    topicId: TANIT,
    type: 'fill-blank',
    difficulty: 'easy',
    skill: 'recall',
    conceptIds: ['day3.cevap.ich-heisse'],
    familyId: 'd3-satz-heisse',
    instruction: 'Boşluğu `heißen` fiiliyle doğru çekimde doldur.',
    prompt: 'Ich ___ Mustafa.',
    answer: 'heiße',
    acceptedAnswers: ['heisse'],
    pronounce: ['Ich heiße Mustafa.'],
  },
  {
    id: 'd3-nasilsin-mc',
    day: 3,
    topicId: NASIL,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day3.nasilsin.wie-gehts-dir'],
    familyId: 'd3-nasilsin-soru',
    instruction: 'Bir arkadaşına "Nasılsın?" diye soruyorsun. Hangisi doğru?',
    answer: "Wie geht's dir?",
    options: ["Wie geht's dir?", 'Wie geht es Ihnen?', 'Wie heißt du?', 'Wer bist du?'],
    explanation: "`Wie geht's dir?` samimi, `Wie geht es Ihnen?` resmî kullanımdır.",
    pronounce: ["Wie geht's dir?"],
  },
  {
    id: 'd3-wortschatz-cevap-match',
    day: 3,
    topicId: NASIL,
    type: 'matching',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day3.nasilsin.cevaplar', 'day3.wortschatz.gunluk'],
    familyId: 'd3-wortschatz',
    instruction: 'Kelime tekrarı: cevapları Türkçe karşılıklarıyla eşleştir.',
    pairs: [
      { left: 'Super!', right: 'Süperim!' },
      { left: 'Es geht.', right: 'İdare eder.' },
      { left: 'Nicht so gut.', right: 'Pek iyi değilim.' },
      { left: 'Schlecht.', right: 'Kötüyüm.' },
    ],
    pronounce: ['Super!', 'Es geht.', 'Nicht so gut.', 'Schlecht.'],
  },
  {
    id: 'd3-soru-woher-mc',
    day: 3,
    topicId: TANIT,
    type: 'multiple-choice',
    difficulty: 'easy',
    skill: 'recognition',
    conceptIds: ['day3.soru.woher-kommst-du', 'day3.soru.wo-wohnst-du'],
    familyId: 'd3-woher',
    instruction: 'Birinin NERELİ olduğunu öğrenmek istiyorsun. Hangi soruyu sorarsın?',
    answer: 'Woher kommst du?',
    options: ['Woher kommst du?', 'Wo wohnst du?', 'Wer bist du?', 'Wie heißt du?'],
    explanation:
      '`Woher kommst du?` nereden geldiğini/nereli olduğunu, `Wo wohnst du?` ise nerede oturduğunu sorar.',
    pronounce: ['Woher kommst du?'],
  },

  /* ---------------------------------------------------------------- */
  /* Orta                                                              */
  /* ---------------------------------------------------------------- */
  {
    id: 'd3-say-11-fill',
    day: 3,
    topicId: SAYI,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day3.sayilar.11-12'],
    familyId: 'd3-say-11',
    instruction: 'Almancaya çevir:',
    prompt: '11',
    answer: 'elf',
    pronounce: ['elf'],
  },
  {
    id: 'd3-say-14-fill',
    day: 3,
    topicId: SAYI,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day3.sayilar.13-19'],
    familyId: 'd3-say-14',
    instruction: 'Almancaya çevir:',
    prompt: '14',
    answer: 'vierzehn',
    explanation: '`vier` + `zehn` = `vierzehn`. Önce birler, sonra onlar basamağı.',
    pronounce: ['vierzehn'],
  },
  {
    id: 'd3-say-18-fill',
    day: 3,
    topicId: SAYI,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day3.sayilar.13-19'],
    familyId: 'd3-say-18',
    instruction: 'Almancaya çevir:',
    prompt: '18',
    answer: 'achtzehn',
    explanation: '`acht` + `zehn` = `achtzehn`.',
    pronounce: ['achtzehn'],
  },
  {
    id: 'd3-say-20-mc',
    day: 3,
    topicId: SAYI,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day3.sayilar.onluklar'],
    familyId: 'd3-say-20',
    instruction: '`20` sayısı Almancada nasıl yazılır?',
    prompt: '20',
    answer: 'zwanzig',
    options: ['zwanzig', 'zweizehn', 'zweizig', 'dreißig'],
    explanation: 'Onluklar ayrı ezberlenir: `20` = `zwanzig`, `30` = `dreißig`.',
    pronounce: ['zwanzig'],
  },
  {
    id: 'd3-say-tersine-sechzehn',
    day: 3,
    topicId: SAYI,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day3.sayilar.16-17-istisna'],
    // `sechzehn` ve `siebzehn` ayni istisnanin iki yuzu — oturumda ayrilirlar.
    familyId: 'd3-say-istisna',
    instruction: 'Sayının Türkçesini rakamla yaz.',
    prompt: 'sechzehn',
    answer: '16',
    explanation: '`sechzehn` = 16. `sechs`in `s`si düşer — bu bir istisnadır.',
    pronounce: ['sechzehn'],
  },
  {
    id: 'd3-soru-name-fill',
    day: 3,
    topicId: TANIT,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day3.soru.wie-ist-dein-name'],
    familyId: 'd3-dein-name',
    instruction: 'Boşluğu doldur. (Anlamı: "Adın nedir?")',
    prompt: 'Wie ist ___ Name?',
    answer: 'dein',
    explanation: 'Samimi: `Wie ist dein Name?` — resmî: `Wie ist Ihr Name?`',
    pronounce: ['Wie ist dein Name?'],
  },
  {
    id: 'd3-soru-wer-bist-du-fill',
    day: 3,
    topicId: TANIT,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'recall',
    conceptIds: ['day3.soru.wer-bist-du'],
    familyId: 'd3-wer-bist',
    instruction: 'Boşluğu `sein` fiiliyle doğru çekimde doldur. (Anlamı: "Sen kimsin?")',
    prompt: 'Wer ___ du?',
    answer: 'bist',
    pronounce: ['Wer bist du?'],
  },
  {
    id: 'd3-cevap-wohne-fill',
    day: 3,
    topicId: TANIT,
    type: 'fill-blank',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day3.cevap.wohnen-in'],
    familyId: 'd3-satz-wohne',
    instruction: 'Boşluğa doğru edatı yaz.',
    prompt: 'Ich wohne ___ Istanbul.',
    answer: 'in',
    hint: '`wohnen` ile hangi edat kullanılıyordu?',
    explanation: '`wohnen` + `in` + şehir; `kommen` + `aus` + ülke.',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich wohne in Istanbul.'],
  },
  {
    id: 'd3-dialog-woher-frei',
    day: 3,
    topicId: TANIT,
    type: 'free-text',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day3.cevap.kommen-aus', 'day3.cevap.aus-der-tuerkei'],
    familyId: 'd3-satz-kommen',
    instruction: 'Yeni tanıştığın bir Alman sana soruyor. Cevap ver.',
    prompt: 'A: Woher kommst du?\nB: ______',
    answer: 'Ich komme aus der Türkei.',
    acceptedAnswers: ['Ich komme aus der Türkei'],
    explanation: '`kommen` fiilinden sonra ülke söylerken `aus` edatı kullanılır.',
    pronounce: ['Ich komme aus der Türkei.'],
  },
  {
    id: 'd3-dialog-heisst-frei',
    day: 3,
    topicId: TANIT,
    type: 'free-text',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day3.cevap.ich-heisse', 'day3.soru.wie-heisst-du'],
    familyId: 'd3-satz-heisse',
    instruction: 'Mini diyalog: adının Mustafa olduğunu söyle.',
    prompt: 'A: Hallo! Wie heißt du?\nB: ______',
    answer: 'Ich heiße Mustafa.',
    acceptedAnswers: ['Ich heiße Mustafa', 'Ich bin Mustafa.', 'Ich bin Mustafa'],
    openEnded: true,
    explanation: 'Hem `Ich heiße Mustafa.` hem de `Ich bin Mustafa.` doğru cevaptır.',
    pronounce: ['Ich heiße Mustafa.'],
  },
  {
    id: 'd3-dialog-gehts-frei',
    day: 3,
    topicId: NASIL,
    type: 'free-text',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day3.nasilsin.cevaplar'],
    familyId: 'd3-nasilsin-iyi',
    instruction: 'Bir arkadaşın soruyor. Bugün iyi olduğunu söyle.',
    prompt: "A: Wie geht's dir?\nB: ______",
    answer: 'Sehr gut.',
    acceptedAnswers: ['Gut.', 'Super!', 'Spitze!', 'Es geht mir gut.', 'Sehr gut'],
    openEnded: true,
    explanation: 'İyiden kötüye: `Super!` → `(Sehr) gut.` → `Es geht.` → `Nicht so gut.` → `Schlecht.`',
    pronounce: ['Sehr gut.', 'Es geht mir gut.'],
  },
  {
    id: 'd3-cevap-ich-bin-frei',
    day: 3,
    topicId: TANIT,
    type: 'free-text',
    difficulty: 'medium',
    skill: 'production',
    conceptIds: ['day3.cevap.ich-bin'],
    familyId: 'd3-satz-bin',
    instruction: 'Adının Mustafa olduğunu bu kez `sein` fiiliyle söyle.',
    answer: 'Ich bin Mustafa.',
    acceptedAnswers: ['Ich bin Mustafa'],
    explanation:
      'Kendini iki şekilde tanıtabilirsin: `Ich heiße Mustafa.` (adım …) ya da `Ich bin Mustafa.` (ben …yım).',
    pronounce: ['Ich bin Mustafa.'],
  },
  {
    id: 'd3-es-oznesi-mc',
    day: 3,
    topicId: NASIL,
    type: 'multiple-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day3.nasilsin.es-oznesi'],
    familyId: 'd3-es-oznesi',
    instruction: '`Es geht mir gut.` cümlesinde fiil hangi özneye göre çekilmiştir?',
    answer: 'es',
    options: ['es', 'mir', 'ich', 'du'],
    explanation:
      'Bu kalıpta özne sen değil `es`tir: kelimesi kelimesine "Bana iyi gidiyor." Fiil `es`e göre çekilir.',
    pronounce: ['Es geht mir gut.'],
  },
  {
    id: 'd3-sesli-tanitim',
    day: 3,
    topicId: TANIT,
    type: 'spoken',
    difficulty: 'medium',
    skill: 'speaking',
    conceptIds: [
      'day3.cevap.ich-heisse',
      'day3.cevap.kommen-aus',
      'day3.cevap.wohnen-in',
      'day3.soru.du-sie-ayrimi',
    ],
    instruction: 'Sesli görev: yeni tanıştığın birine kendini tanıt.',
    requirements: [
      'Adını söyle.',
      'Nereli olduğunu söyle.',
      'Nerede yaşadığını söyle.',
      'Aynı soruyu resmî (`Sie`) biçimde karşına sor.',
    ],
    pronounce: ['Ich heiße Mustafa.', 'Ich komme aus der Türkei.', 'Wie heißen Sie?'],
  },
  {
    id: 'd3-dinle-wie-heisst-du',
    day: 3,
    topicId: TANIT,
    type: 'listen-choice',
    difficulty: 'medium',
    skill: 'recognition',
    conceptIds: ['day3.soru.wie-heisst-du'],
    familyId: 'd3-wie-heisst-du-listen',
    instruction: 'Dinle: duyduğun soruyu seç.',
    audioText: 'Wie heißt du?',
    audio: { prompt: { text: 'Wie heißt du?', language: 'de-DE', role: 'prompt' } },
    answer: 'Wie heißt du?',
    options: ['Wie heißt du?', 'Wo wohnst du?', 'Wie geht es dir?', 'Woher kommst du?'],
    explanation: '`Wie heißt du?` samimi biçimde “Adın ne?” demektir.',
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'd3-dikte-wie-heisst-du',
    day: 3,
    topicId: TANIT,
    type: 'dictation',
    difficulty: 'hard',
    skill: 'recall',
    conceptIds: ['day3.soru.wie-heisst-du'],
    familyId: 'd3-wie-heisst-du-listen',
    instruction: 'Dinle ve duyduğun cümleyi Almanca yaz.',
    audioText: 'Wie heißt du?',
    audio: { prompt: { text: 'Wie heißt du?', language: 'de-DE', role: 'prompt' } },
    answer: 'Wie heißt du?',
    acceptedAnswers: ['Wie heißt du'],
    explanation: 'Bu samimi soru, karşıdaki kişinin adını sorar.',
    pronounce: ['Wie heißt du?'],
  },

  /* ---------------------------------------------------------------- */
  /* Zor                                                               */
  /* ---------------------------------------------------------------- */
  {
    id: 'd3-hata-wohnen-aus',
    day: 3,
    topicId: TANIT,
    type: 'error-correction',
    difficulty: 'hard',
    skill: 'correction',
    conceptIds: ['day3.cevap.wohnen-in', 'day3.cevap.kommen-aus'],
    familyId: 'd3-satz-wohne',
    instruction: 'Cümledeki hatayı bul ve doğrusunu yaz.',
    prompt: 'Ich wohne aus Istanbul.',
    answer: 'Ich wohne in Istanbul.',
    explanation:
      '`wohnen` (bir yerde oturmak) ile `in` kullanılır. `aus` ise `kommen` ile birlikte nereli olduğunu söylerken kullanılır.',
    pronounce: ['Ich wohne in Istanbul.'],
  },
  {
    id: 'd3-hata-sie-resmi',
    day: 3,
    topicId: TANIT,
    type: 'error-correction',
    difficulty: 'hard',
    skill: 'correction',
    conceptIds: ['day3.soru.wie-heissen-sie', 'day3.soru.du-sie-ayrimi'],
    familyId: 'd3-wie-heissen-sie',
    instruction: 'Yeni tanıştığın müdürüne soruyorsun. Cümleyi düzelt.',
    prompt: 'Wie heißt Sie?',
    answer: 'Wie heißen Sie?',
    explanation:
      'Resmî `Sie` ile fiil `-en` takısı alır (`wir`/`sie` gibi): `Wie heißen Sie?` `heißt` ise `du` içindir.',
    pronounce: ['Wie heißen Sie?'],
  },
  {
    id: 'd3-ceviri-woher-resmi',
    day: 3,
    topicId: TANIT,
    type: 'free-text',
    difficulty: 'hard',
    skill: 'production',
    conceptIds: ['day3.soru.woher-kommst-du', 'day3.soru.du-sie-ayrimi'],
    familyId: 'd3-woher',
    instruction: 'Seçenek yok — resmî (`Sie`) biçimde sor: "Nerelisiniz?"',
    answer: 'Woher kommen Sie?',
    acceptedAnswers: ['Woher kommen Sie'],
    hint: 'Resmî `Sie` ile fiil hangi takıyı alır?',
    explanation: 'Resmî biçimde fiil `-en` alır ve `Sie` büyük harfle yazılır: `Woher kommen Sie?`',
    validation: { caseSensitive: true },
    pronounce: ['Woher kommen Sie?'],
  },
  {
    id: 'd3-nasilsin-resmi-frei',
    day: 3,
    topicId: NASIL,
    type: 'free-text',
    difficulty: 'hard',
    skill: 'production',
    conceptIds: ['day3.nasilsin.wie-geht-es-ihnen', 'day3.soru.du-sie-ayrimi'],
    familyId: 'd3-nasilsin-soru',
    instruction: 'Seçenek yok — müdürüne resmî biçimde "Nasılsınız?" diye sor.',
    answer: 'Wie geht es Ihnen?',
    acceptedAnswers: ['Wie geht es Ihnen'],
    hint: 'Resmî biçimde `dir` yerine ne gelir?',
    explanation:
      'Samimi: `Wie geht\'s dir?` — resmî: `Wie geht es Ihnen?` Resmî biçimde `Ihnen` büyük harfle yazılır.',
    validation: { caseSensitive: true },
    pronounce: ['Wie geht es Ihnen?'],
  },
  {
    id: 'd3-say-29-fill',
    day: 3,
    topicId: SAYI,
    type: 'fill-blank',
    difficulty: 'hard',
    skill: 'recall',
    conceptIds: ['day3.sayilar.und-yapisi', 'day3.sayilar.onluklar'],
    familyId: 'd3-say-29',
    instruction: 'Almancaya çevir:',
    prompt: '29',
    answer: 'neunundzwanzig',
    hint: 'Önce birler, sonra `und`, sonra onlar.',
    explanation: '`neun` + `und` + `zwanzig` = `neunundzwanzig`. Türkçenin tam tersi sırada.',
    pronounce: ['neunundzwanzig'],
  },
];
