/**
 * Özel Ders — 2. Gün — yazılmış alıştırma havuzu.
 *
 * Kaynak: el yazısı özel ders notları (4 sayfa). Tüm kavramlar concepts.ts içindeki
 * private.day2.* kavramlarına bağlıdır; özet kapsamı Özel Ders Özet.md üzerinden doğrulanır.
 *
 * Kapsam guvenligi: bu havuzda `einen`, `keinen`, `meinen`, `deinen` gibi Akkusativ
 * bicimleri KULLANILMAZ — kaynak notlar Akkusativ ogretmiyor. Nesne konumunda eril
 * (der) isim gerektiren olumsuzlamalarda `kein/keine` yerine `nicht` kullanilir ve
 * nesne dusurulur (ör. "Ich trinke heute nicht." / "keinen Kaffee" degil).
 */

import type { AuthoredExercise } from '../types.ts';

const ART = 'private.day2.artikel-belirli-belirsiz';
const KMD = 'private.day2.artikel-kein-mein-dein';
const POS = 'private.day2.cumle-olumlu';
const NEG = 'private.day2.cumle-olumsuz';
const SOR = 'private.day2.sorular';
const HAB = 'private.day2.haben-sein';
const GUN = 'private.day2.gunluk-hayat';

export const PRIVATE_DAY2_EXERCISES: AuthoredExercise[] = [
  /* ================================================================
   * Belirli / Belirsiz Artikel — der/die/das, ein/eine, Was ist das? (14)
   * ================================================================ */

  {
    id: 'p2-art-vater-mc',
    day: 2, track: 'private', topicId: ART,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.artikel.der-die-das-die-pl', 'private.day2.wortschatz.nesneler'],
    familyId: 'p2-art-vater',
    instruction: 'Doğru belirli artikeli seç:',
    prompt: '_____ Vater (baba)',
    answer: 'der',
    options: ['der', 'die', 'das', 'ein'],
    pronounce: ['der Vater'],
  },
  {
    id: 'p2-art-mutter-mc',
    day: 2, track: 'private', topicId: ART,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.artikel.der-die-das-die-pl', 'private.day2.wortschatz.nesneler'],
    familyId: 'p2-art-mutter',
    instruction: 'Doğru belirli artikeli seç:',
    prompt: '_____ Mutter (anne)',
    answer: 'die',
    options: ['der', 'die', 'das', 'eine'],
    pronounce: ['die Mutter'],
  },
  {
    id: 'p2-art-kind-mc',
    day: 2, track: 'private', topicId: ART,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.artikel.der-die-das-die-pl', 'private.day2.wortschatz.nesneler'],
    familyId: 'p2-art-kind',
    instruction: 'Doğru belirli artikeli seç:',
    prompt: '_____ Kind (çocuk)',
    answer: 'das',
    options: ['der', 'die', 'das', 'ein'],
    pronounce: ['das Kind'],
  },
  {
    id: 'p2-art-blumen-mc',
    day: 2, track: 'private', topicId: ART,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.artikel.der-die-das-die-pl'],
    familyId: 'p2-art-blumen',
    instruction: 'Çoğul isimde doğru artikeli seç:',
    prompt: '_____ Blumen (çiçekler)',
    answer: 'die',
    options: ['der', 'die', 'das', 'ein'],
    pronounce: ['die Blumen'],
  },
  {
    id: 'p2-art-tisch-fill',
    day: 2, track: 'private', topicId: ART,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.der-die-das-die-pl', 'private.day2.wortschatz.nesneler'],
    familyId: 'p2-art-tisch',
    instruction: 'Boşluğu doldur:',
    prompt: '_____ Tisch (masa)',
    answer: 'der',
    pronounce: ['der Tisch'],
  },
  {
    id: 'p2-art-tasche-fill',
    day: 2, track: 'private', topicId: ART,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.der-die-das-die-pl', 'private.day2.wortschatz.nesneler'],
    familyId: 'p2-art-tasche',
    instruction: 'Boşluğu doldur:',
    prompt: '_____ Tasche (çanta)',
    answer: 'die',
    pronounce: ['die Tasche'],
  },
  {
    id: 'p2-art-ein-mc',
    day: 2, track: 'private', topicId: ART,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.artikel.ein-eine'],
    familyId: 'p2-art-ein-vater',
    instruction: 'Doğru belirsiz artikeli seç:',
    prompt: 'der Vater → _____ Vater',
    answer: 'ein',
    options: ['ein', 'eine', 'kein', 'keine'],
    pronounce: ['ein Vater'],
  },
  {
    id: 'p2-art-eine-mutter-fill',
    day: 2, track: 'private', topicId: ART,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.ein-eine'],
    familyId: 'p2-art-eine-mutter',
    instruction: 'Belirsiz artikele çevir:',
    prompt: 'die Mutter → _____ Mutter',
    answer: 'eine',
    pronounce: ['eine Mutter'],
  },
  {
    id: 'p2-art-ein-kind-fill',
    day: 2, track: 'private', topicId: ART,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.ein-eine'],
    familyId: 'p2-art-ein-kind',
    instruction: 'Belirsiz artikele çevir:',
    prompt: 'das Kind → _____ Kind',
    answer: 'ein',
    pronounce: ['ein Kind'],
  },
  {
    id: 'p2-art-cogul-belirsiz-mc',
    day: 2, track: 'private', topicId: ART,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day2.artikel.cogul-belirsiz-yok'],
    familyId: 'p2-art-cogul',
    instruction: 'Çoğul isimlerde belirsiz artikel nasıldır?',
    prompt: 'die Blumen → belirsiz hâli nedir?',
    answer: 'Belirsiz artikel yoktur, artikelsiz kullanılır (Blumen).',
    options: [
      'Belirsiz artikel yoktur, artikelsiz kullanılır (Blumen).',
      'eine Blumen',
      'ein Blumen',
      'die Blumen',
    ],
  },
  {
    id: 'p2-art-was-ist-das-wasser-mc',
    day: 2, track: 'private', topicId: ART,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.artikel.was-ist-das'],
    familyId: 'p2-art-was-ist-das',
    instruction: '"Was ist das?" sorusuna doğru cevabı seç:',
    prompt: 'Was ist das? (su)',
    answer: 'Das ist ein Wasser.',
    options: ['Das ist ein Wasser.', 'Das ist das Wasser.', 'Das ist eine Wasser.', 'Das Wasser ist.'],
    pronounce: ['Was ist das?', 'Das ist ein Wasser.'],
  },
  {
    id: 'p2-art-was-ist-das-tasche-fill',
    day: 2, track: 'private', topicId: ART,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.artikel.was-ist-das'],
    familyId: 'p2-art-was-ist-das-tasche',
    instruction: 'Bir nesneyi tanıt:',
    prompt: 'Was ist das? → Das ist _____ Tasche.',
    answer: 'eine',
    pronounce: ['Das ist eine Tasche.'],
  },
  {
    id: 'p2-art-was-ist-das-buch-free',
    day: 2, track: 'private', topicId: ART,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.artikel.was-ist-das', 'private.day2.wortschatz.nesneler'],
    familyId: 'p2-art-was-ist-das-buch',
    instruction: '"Bu bir kitap." cümlesini Almanca yaz:',
    prompt: 'Bu bir kitap. → ______',
    answer: 'Das ist ein Buch.',
    pronounce: ['Das ist ein Buch.'],
  },
  {
    id: 'p2-art-nesneler-matching',
    day: 2, track: 'private', topicId: ART,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day2.wortschatz.nesneler'],
    familyId: 'p2-art-nesneler-match',
    instruction: '2. Gün nesnelerini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'der Stuhl', right: 'sandalye' },
      { left: 'das Heft', right: 'defter' },
      { left: 'die Schuhe', right: 'ayakkabılar' },
      { left: 'das Buch', right: 'kitap' },
    ],
    pronounce: ['der Stuhl', 'das Heft', 'die Schuhe', 'das Buch'],
  },

  /* ================================================================
   * kein/keine, mein/meine, dein/deine — Artikel Zinciri (14)
   * ================================================================ */

  {
    id: 'p2-kmd-kein-vater-fill',
    day: 2, track: 'private', topicId: KMD,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.kein-keine'],
    familyId: 'p2-kmd-kein-vater',
    instruction: 'Olumsuz artikele çevir:',
    prompt: 'ein Vater → _____ Vater',
    answer: 'kein',
    pronounce: ['kein Vater'],
  },
  {
    id: 'p2-kmd-keine-mutter-fill',
    day: 2, track: 'private', topicId: KMD,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.kein-keine'],
    familyId: 'p2-kmd-keine-mutter',
    instruction: 'Olumsuz artikele çevir:',
    prompt: 'eine Mutter → _____ Mutter',
    answer: 'keine',
    pronounce: ['keine Mutter'],
  },
  {
    id: 'p2-kmd-kein-handy-mc',
    day: 2, track: 'private', topicId: KMD,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.artikel.kein-keine'],
    familyId: 'p2-kmd-kein-handy',
    instruction: 'Doğru olumsuz artikeli seç:',
    prompt: 'das Handy → ein Handy → _____ Handy',
    answer: 'kein',
    options: ['kein', 'keine', 'dein', 'mein'],
    pronounce: ['kein Handy'],
  },
  {
    id: 'p2-kmd-keine-blumen-mc',
    day: 2, track: 'private', topicId: KMD,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.artikel.kein-keine'],
    familyId: 'p2-kmd-keine-blumen',
    instruction: 'Doğru olumsuz artikeli seç:',
    prompt: 'die Blumen → _____ Blumen',
    answer: 'keine',
    options: ['kein', 'keine', 'dein', 'mein'],
    pronounce: ['keine Blumen'],
  },
  {
    id: 'p2-kmd-mein-vater-fill',
    day: 2, track: 'private', topicId: KMD,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.mein-meine'],
    familyId: 'p2-kmd-mein-vater',
    instruction: 'İyelik artikeline çevir (benim):',
    prompt: 'kein Vater → _____ Vater',
    answer: 'mein',
    pronounce: ['mein Vater'],
  },
  {
    id: 'p2-kmd-meine-mutter-fill',
    day: 2, track: 'private', topicId: KMD,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.mein-meine'],
    familyId: 'p2-kmd-meine-mutter',
    instruction: 'İyelik artikeline çevir (benim):',
    prompt: 'keine Mutter → _____ Mutter',
    answer: 'meine',
    pronounce: ['meine Mutter'],
  },
  {
    id: 'p2-kmd-dein-handy-fill',
    day: 2, track: 'private', topicId: KMD,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.dein-deine'],
    familyId: 'p2-kmd-dein-handy',
    instruction: 'İyelik artikeline çevir (senin):',
    prompt: 'kein Handy → _____ Handy',
    answer: 'dein',
    pronounce: ['dein Handy'],
  },
  {
    id: 'p2-kmd-deine-tante-fill',
    day: 2, track: 'private', topicId: KMD,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.dein-deine'],
    familyId: 'p2-kmd-deine-tante',
    instruction: 'İyelik artikeline çevir (senin):',
    prompt: 'keine Tante → _____ Tante',
    answer: 'deine',
    pronounce: ['deine Tante'],
  },
  {
    id: 'p2-kmd-chain-wasser-free',
    day: 2, track: 'private', topicId: KMD,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.artikel.zincir'],
    familyId: 'p2-kmd-chain-wasser',
    instruction: 'Artikel zincirinin devamını doğru sırada diz: das Wasser → ein Wasser → ? → ? → ?',
    prompt: 'kein Wasser / dein Wasser / mein Wasser',
    answer: 'kein Wasser dein Wasser mein Wasser',
    words: ['kein Wasser', 'dein Wasser', 'mein Wasser'],
    pronounce: ['kein Wasser', 'dein Wasser', 'mein Wasser'],
  },
  {
    id: 'p2-kmd-chain-kinder-free',
    day: 2, track: 'private', topicId: KMD,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.artikel.zincir'],
    familyId: 'p2-kmd-chain-kinder',
    instruction: 'Artikel zincirinin devamını doğru sırada diz: die Kinder → ? → ? → ?',
    prompt: 'keine Kinder / deine Kinder / meine Kinder',
    answer: 'keine Kinder deine Kinder meine Kinder',
    words: ['keine Kinder', 'deine Kinder', 'meine Kinder'],
    pronounce: ['keine Kinder', 'deine Kinder', 'meine Kinder'],
  },
  {
    id: 'p2-kmd-wie-ist-dein-buch-fill',
    day: 2, track: 'private', topicId: KMD,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.artikel.wie-ist-dein'],
    familyId: 'p2-kmd-wie-ist-dein-buch',
    instruction: 'Boşluğu doldur (senin):',
    prompt: 'Wie ist _____ Buch?',
    answer: 'dein',
    pronounce: ['Wie ist dein Buch?'],
  },
  {
    id: 'p2-kmd-mein-buch-ist-gut-fill',
    day: 2, track: 'private', topicId: KMD,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.artikel.wie-ist-dein'],
    familyId: 'p2-kmd-mein-buch-ist-gut',
    instruction: 'Cevap ver (benim):',
    prompt: '_____ Buch ist gut.',
    answer: 'Mein',
    pronounce: ['Mein Buch ist gut.'],
  },
  {
    id: 'p2-kmd-wie-ist-deine-schokolade-free',
    day: 2, track: 'private', topicId: KMD,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.artikel.wie-ist-dein'],
    familyId: 'p2-kmd-wie-ist-deine-schokolade',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Senin çikolatan nasıl? → ______',
    answer: 'Wie ist deine Schokolade?',
    pronounce: ['Wie ist deine Schokolade?'],
  },
  {
    id: 'p2-kmd-error-eine-vater',
    day: 2, track: 'private', topicId: KMD,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day2.artikel.ein-eine', 'private.day2.artikel.der-die-das-die-pl'],
    familyId: 'p2-art-ein-vater',
    instruction: 'Hata avı — doğru artikel hangisi?',
    prompt: 'Eine Vater ist zu Hause.',
    answer: 'Ein Vater ist zu Hause.',
    explanation: 'der Vater eril bir isimdir → ein, eine değil.',
    pronounce: ['Ein Vater ist zu Hause.'],
  },

  /* ================================================================
   * Olumlu Cümle Kurma (10)
   * ================================================================ */

  {
    id: 'p2-pos-machen-mc',
    day: 2, track: 'private', topicId: POS,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.verben.machen'],
    familyId: 'p2-pos-machen',
    instruction: '"machen" fiilinin anlamı nedir?',
    prompt: 'machen',
    answer: 'yapmak',
    options: ['yapmak', 'gitmek', 'içmek', 'gelmek'],
    pronounce: ['machen'],
  },
  {
    id: 'p2-pos-mache-sport-fill',
    day: 2, track: 'private', topicId: POS,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.verben.machen', 'private.day2.cumle.olumlu-yapi'],
    familyId: 'p2-pos-sport',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich _____ Sport. (machen)',
    answer: 'mache',
    pronounce: ['Ich mache Sport.'],
  },
  {
    id: 'p2-pos-order-sport',
    day: 2, track: 'private', topicId: POS,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.cumle.olumlu-yapi', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-sport',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / mache / jeden / Tag / Sport.',
    answer: 'Ich mache jeden Tag Sport.',
    words: ['Ich', 'mache', 'jeden', 'Tag', 'Sport'],
    pronounce: ['Ich mache jeden Tag Sport.'],
  },
  {
    id: 'p2-pos-trinke-kaffee-fill',
    day: 2, track: 'private', topicId: POS,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.zaman.jeden-tag-heute', 'private.day2.cumle.olumlu-yapi'],
    familyId: 'p2-pos-kaffee',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich _____ jeden Morgen ein Kaffee. (trinken)',
    answer: 'trinke',
    pronounce: ['Ich trinke jeden Morgen ein Kaffee.'],
  },
  {
    id: 'p2-pos-isst-um4-fill',
    day: 2, track: 'private', topicId: POS,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-isst',
    instruction: 'Boşluğu doldur (essen — tekrar):',
    prompt: 'Er _____ um 4 Uhr. (essen)',
    answer: 'isst',
    pronounce: ['Er isst um 4 Uhr.'],
  },
  {
    id: 'p2-pos-kochen-heute-fill',
    day: 2, track: 'private', topicId: POS,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day2.cumle.olumlu-yapi'],
    familyId: 'p2-pos-kochen',
    instruction: 'Boşluğu doldur (kochen — tekrar):',
    prompt: 'Ich _____ heute.',
    answer: 'koche',
    pronounce: ['Ich koche heute.'],
  },
  {
    id: 'p2-pos-zur-fill',
    day: 2, track: 'private', topicId: POS,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.verben.gehen-zur'],
    familyId: 'p2-pos-zur-arbeit',
    instruction: 'Boşluğu doldur — "zu" ve "der" kaynaşır:',
    prompt: 'Mein Vater geht jeden Tag _____ Arbeit.',
    answer: 'zur',
    pronounce: ['Mein Vater geht jeden Tag zur Arbeit.'],
  },
  {
    id: 'p2-pos-zur-schule-mc',
    day: 2, track: 'private', topicId: POS,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.verben.gehen-zur'],
    familyId: 'p2-pos-zur-schule',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Er geht zur Schule.',
    answer: 'O okula gider.',
    options: ['O okula gider.', 'O işe gider.', 'O eve gider.', 'O okuldan gelir.'],
    pronounce: ['Er geht zur Schule.'],
  },
  {
    id: 'p2-pos-builder-sport-tr',
    day: 2, track: 'private', topicId: POS,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.verben.machen', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-sport',
    instruction: 'Cümleyi kur:',
    prompt: 'Ben her gün spor yapıyorum.',
    answer: 'Ich mache jeden Tag Sport.',
    words: ['Ich', 'mache', 'jeden', 'Tag', 'Sport'],
    pronounce: ['Ich mache jeden Tag Sport.'],
  },
  {
    id: 'p2-pos-free-lesen',
    day: 2, track: 'private', topicId: POS,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.cumle.olumlu-yapi', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-gun-buch',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Her gün kitap okurum. → ______',
    answer: 'Ich lese jeden Tag ein Buch.',
    hint: 'lesen düzensizdir ama ich her zaman düzenli -e alır.',
    pronounce: ['Ich lese jeden Tag ein Buch.'],
  },
  {
    id: 'p2-pos-order-mutter-kocht',
    day: 2, track: 'private', topicId: POS,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.cumle.olumlu-yapi', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-mutter-kocht',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Meine / Mutter / kocht / heute.',
    answer: 'Meine Mutter kocht heute.',
    words: ['Meine', 'Mutter', 'kocht', 'heute'],
    pronounce: ['Meine Mutter kocht heute.'],
  },
  {
    id: 'p2-pos-builder-vater-wasser-tr',
    day: 2, track: 'private', topicId: POS,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.cumle.olumlu-yapi', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-vater-wasser',
    instruction: 'Cümleyi kur:',
    prompt: 'Babam her sabah bir su içer.',
    answer: 'Mein Vater trinkt jeden Morgen ein Wasser.',
    words: ['Mein', 'Vater', 'trinkt', 'jeden', 'Morgen', 'ein', 'Wasser'],
    pronounce: ['Mein Vater trinkt jeden Morgen ein Wasser.'],
  },
  {
    id: 'p2-pos-free-wir-schule',
    day: 2, track: 'private', topicId: POS,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.verben.gehen-zur', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-wir-schule',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Biz her gün okula gideriz. → ______',
    answer: 'Wir gehen jeden Tag zur Schule.',
    pronounce: ['Wir gehen jeden Tag zur Schule.'],
  },
  {
    id: 'p2-pos-wb-schwester-buch-tr',
    day: 2, track: 'private', topicId: POS,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.cumle.olumlu-yapi', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-schwester-buch',
    instruction: 'Türkçeden Almancaya kur — Kız kardeşim her gün kitap okur.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Kız kardeşim her gün kitap okur.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Meine' }, { id: 't2', text: 'Schwester' }, { id: 't3', text: 'liest' },
        { id: 't4', text: 'jeden' }, { id: 't5', text: 'Tag' }, { id: 't6', text: 'ein' }, { id: 't7', text: 'Buch.' },
        { id: 't8', text: 'nicht' },
      ],
      acceptedSequences: [['Meine', 'Schwester', 'liest', 'jeden', 'Tag', 'ein', 'Buch.']],
    },
    answer: 'Meine Schwester liest jeden Tag ein Buch.',
    pronounce: ['Meine Schwester liest jeden Tag ein Buch.'],
  },
  {
    id: 'p2-pos-order-tante-kommt',
    day: 2, track: 'private', topicId: POS,
    type: 'ordering', difficulty: 'easy', skill: 'production',
    conceptIds: ['private.day2.cumle.olumlu-yapi', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-tante-kommt',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Meine / Tante / kommt / heute.',
    answer: 'Meine Tante kommt heute.',
    words: ['Meine', 'Tante', 'kommt', 'heute'],
    pronounce: ['Meine Tante kommt heute.'],
  },
  {
    id: 'p2-pos-builder-kinder-sport-tr',
    day: 2, track: 'private', topicId: POS,
    type: 'sentence-builder', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.cumle.olumlu-yapi', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-kinder-sport',
    instruction: 'Cümleyi kur:',
    prompt: 'Çocuklar her gün spor yapar.',
    answer: 'Die Kinder machen jeden Tag Sport.',
    words: ['Die', 'Kinder', 'machen', 'jeden', 'Tag', 'Sport'],
    pronounce: ['Die Kinder machen jeden Tag Sport.'],
  },

  /* ================================================================
   * Olumsuz Cümle Kurma — nicht / kein (13)
   * ================================================================ */

  {
    id: 'p2-neg-nicht-mc',
    day: 2, track: 'private', topicId: NEG,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.olumsuzluk.nicht'],
    familyId: 'p2-neg-nicht-kural',
    instruction: '"nicht" neyi olumsuzlar?',
    prompt: 'nicht',
    answer: 'fiili / diğer bilgiyi',
    options: ['fiili / diğer bilgiyi', 'yalnızca isimleri', 'yalnızca artikelleri', 'yalnızca zamirleri'],
  },
  {
    id: 'p2-neg-kein-haben-mc',
    day: 2, track: 'private', topicId: NEG,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-kein-kural',
    instruction: '"kein/keine" en çok hangi fiille birlikte nesneyi olumsuzlar?',
    prompt: 'kein / keine',
    answer: 'haben',
    options: ['haben', 'gehen', 'machen', 'trinken'],
  },
  {
    id: 'p2-neg-arbeite-nicht-fill',
    day: 2, track: 'private', topicId: NEG,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.olumsuzluk.nicht'],
    familyId: 'p2-neg-arbeiten',
    instruction: 'Cümleyi olumsuz yap:',
    prompt: 'Ich arbeite heute _____.',
    answer: 'nicht',
    pronounce: ['Ich arbeite heute nicht.'],
  },
  {
    id: 'p2-neg-geht-nicht-schule-fill',
    day: 2, track: 'private', topicId: NEG,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.olumsuzluk.nicht'],
    familyId: 'p2-neg-gehen',
    instruction: 'Cümleyi olumsuz yap:',
    prompt: 'Sie geht heute _____ zur Schule.',
    answer: 'nicht',
    pronounce: ['Sie geht heute nicht zur Schule.'],
  },
  {
    id: 'p2-neg-kommt-nicht-fill',
    day: 2, track: 'private', topicId: NEG,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.olumsuzluk.nicht'],
    familyId: 'p2-neg-kommen',
    instruction: 'Boşluğu doldur (kommen):',
    prompt: 'Er _____ heute nicht zur Schule.',
    answer: 'kommt',
    pronounce: ['Er kommt heute nicht zur Schule.'],
  },
  {
    id: 'p2-neg-isst-nicht-fill',
    day: 2, track: 'private', topicId: NEG,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day2.olumsuzluk.nicht'],
    familyId: 'p2-neg-essen',
    instruction: 'Cümleyi olumsuz yap:',
    prompt: 'Meine Mutter isst _____.',
    answer: 'nicht',
    pronounce: ['Meine Mutter isst nicht.'],
  },
  {
    id: 'p2-neg-habe-kein-geld-fill',
    day: 2, track: 'private', topicId: NEG,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-geld',
    instruction: 'Cümleyi olumsuz yap — nesneyi olumsuzla:',
    prompt: 'Ich habe _____ Geld.',
    answer: 'kein',
    pronounce: ['Ich habe kein Geld.'],
  },
  {
    id: 'p2-neg-habe-keine-schwester-fill',
    day: 2, track: 'private', topicId: NEG,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-schwester',
    instruction: 'Cümleyi olumsuz yap — nesneyi olumsuzla:',
    prompt: 'Ich habe _____ Schwester.',
    answer: 'keine',
    pronounce: ['Ich habe keine Schwester.'],
  },
  {
    id: 'p2-neg-hat-keine-tasche-fill',
    day: 2, track: 'private', topicId: NEG,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-tasche',
    instruction: 'Cümleyi olumsuz yap — nesneyi olumsuzla:',
    prompt: 'Sie hat _____ Tasche.',
    answer: 'keine',
    pronounce: ['Sie hat keine Tasche.'],
  },
  {
    id: 'p2-neg-donusum-arbeiten-free',
    day: 2, track: 'private', topicId: NEG,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.donusum', 'private.day2.olumsuzluk.nicht'],
    familyId: 'p2-neg-arbeiten',
    instruction: 'Olumsuz yap:',
    prompt: 'Ich arbeite heute. → ______',
    answer: 'Ich arbeite heute nicht.',
    pronounce: ['Ich arbeite heute nicht.'],
  },
  {
    id: 'p2-neg-donusum-haben-free',
    day: 2, track: 'private', topicId: NEG,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.donusum', 'private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-geld',
    instruction: 'Olumsuz yap:',
    prompt: 'Ich habe Geld. → ______',
    answer: 'Ich habe kein Geld.',
    pronounce: ['Ich habe kein Geld.'],
  },
  {
    id: 'p2-neg-error-keine-schwester',
    day: 2, track: 'private', topicId: NEG,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-schwester',
    instruction: 'Hata avı — doğru artikel hangisi?',
    prompt: 'Ich habe kein Schwester.',
    answer: 'Ich habe keine Schwester.',
    explanation: 'die Schwester dişildir → keine.',
    pronounce: ['Ich habe keine Schwester.'],
  },
  {
    id: 'p2-neg-error-vater-arbeitet',
    day: 2, track: 'private', topicId: NEG,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day2.olumsuzluk.nicht', 'private.day2.verben.gehen-zur'],
    familyId: 'p2-neg-vater-arbeit',
    instruction: 'Hata avı — doğru fiil hangisi?',
    prompt: 'Mein Vater arbeitet nicht jeden Tag zur Arbeit.',
    answer: 'Mein Vater geht nicht jeden Tag zur Arbeit.',
    explanation: '"zur Arbeit" gehen fiiliyle kullanılır, arbeiten ile değil.',
    pronounce: ['Mein Vater geht nicht jeden Tag zur Arbeit.'],
  },
  {
    id: 'p2-neg-free-tante-kommt',
    day: 2, track: 'private', topicId: NEG,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.donusum', 'private.day2.olumsuzluk.nicht'],
    familyId: 'p2-pos-tante-kommt',
    instruction: 'Olumsuz yap:',
    prompt: 'Meine Tante kommt heute. → ______',
    answer: 'Meine Tante kommt heute nicht.',
    pronounce: ['Meine Tante kommt heute nicht.'],
  },
  {
    id: 'p2-neg-order-wir-schule',
    day: 2, track: 'private', topicId: NEG,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.nicht', 'private.day2.verben.gehen-zur'],
    familyId: 'p2-pos-wir-schule',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Wir / gehen / heute / nicht / zur / Schule.',
    answer: 'Wir gehen heute nicht zur Schule.',
    words: ['Wir', 'gehen', 'heute', 'nicht', 'zur', 'Schule'],
    pronounce: ['Wir gehen heute nicht zur Schule.'],
  },
  {
    id: 'p2-neg-free-kind-isst-tr',
    day: 2, track: 'private', topicId: NEG,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.nicht'],
    familyId: 'p2-neg-kind-isst',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Çocuğum bugün yemek yemiyor. → ______',
    answer: 'Mein Kind isst heute nicht.',
    pronounce: ['Mein Kind isst heute nicht.'],
  },
  {
    id: 'p2-neg-ich-habe-keine-tasche-fill',
    day: 2, track: 'private', topicId: NEG,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-tasche',
    instruction: 'Cümleyi olumsuz yap — nesneyi olumsuzla:',
    prompt: 'Ich habe _____ Tasche.',
    answer: 'keine',
    pronounce: ['Ich habe keine Tasche.'],
  },
  {
    id: 'p2-neg-free-schwester-liest-tr',
    day: 2, track: 'private', topicId: NEG,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.nicht', 'private.day2.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-schwester-buch',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kız kardeşim her gün okumaz. → ______',
    answer: 'Meine Schwester liest nicht jeden Tag.',
    pronounce: ['Meine Schwester liest nicht jeden Tag.'],
  },
  {
    id: 'p2-neg-wb-wasser-tr-de',
    day: 2, track: 'private', topicId: NEG,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-wasser',
    instruction: 'Türkçeden Almancaya kur — Bizim suyumuz yok.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Bizim suyumuz yok.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Wir' }, { id: 't2', text: 'haben' }, { id: 't3', text: 'kein' }, { id: 't4', text: 'Wasser.' },
        { id: 't5', text: 'keine' }, { id: 't6', text: 'nicht' },
      ],
      acceptedSequences: [['Wir', 'haben', 'kein', 'Wasser.']],
    },
    answer: 'Wir haben kein Wasser.',
    pronounce: ['Wir haben kein Wasser.'],
  },

  /* ================================================================
   * Evet/Hayır Soruları (10)
   * ================================================================ */

  {
    id: 'p2-sor-yapi-mc',
    day: 2, track: 'private', topicId: SOR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-yapi',
    instruction: 'Evet/hayır sorusunda fiil cümlenin neresinde durur?',
    prompt: 'Fiil + Özne + ... ?',
    answer: 'cümlenin başında',
    options: ['cümlenin başında', 'cümlenin ortasında', 'cümlenin sonunda', 'özneden sonra'],
  },
  {
    id: 'p2-sor-gehst-du-fill',
    day: 2, track: 'private', topicId: SOR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-gehen',
    instruction: 'Soruyu tamamla:',
    prompt: '_____ du heute zur Schule? (gehen)',
    answer: 'Gehst',
    pronounce: ['Gehst du heute zur Schule?'],
  },
  {
    id: 'p2-sor-machst-du-mc',
    day: 2, track: 'private', topicId: SOR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-machen',
    instruction: 'Doğru soruyu seç:',
    prompt: 'Spor yapıyor musun?',
    answer: 'Machst du Sport?',
    options: ['Machst du Sport?', 'Du machst Sport?', 'Machst Sport du?', 'Macht du Sport?'],
    pronounce: ['Machst du Sport?'],
  },
  {
    id: 'p2-sor-trinkst-du-fill',
    day: 2, track: 'private', topicId: SOR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-trinken',
    instruction: 'Soruyu tamamla:',
    prompt: '_____ du ein Kaffee? (trinken)',
    answer: 'Trinkst',
    pronounce: ['Trinkst du ein Kaffee?'],
  },
  {
    id: 'p2-sor-hast-du-fill',
    day: 2, track: 'private', topicId: SOR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-haben',
    instruction: 'Soruyu tamamla:',
    prompt: '_____ du eine Schwester? (haben)',
    answer: 'Hast',
    pronounce: ['Hast du eine Schwester?'],
  },
  {
    id: 'p2-sor-liest-du-mc',
    day: 2, track: 'private', topicId: SOR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-lesen',
    instruction: 'Bu sorunun Türkçesi nedir?',
    prompt: 'Liest du jeden Tag ein Buch?',
    answer: 'Her gün kitap okuyor musun?',
    options: ['Her gün kitap okuyor musun?', 'Her gün spor yapıyor musun?', 'Bugün okula gidiyor musun?', 'Bir kahve içer misin?'],
    pronounce: ['Liest du jeden Tag ein Buch?'],
  },
  {
    id: 'p2-sor-donusum-free',
    day: 2, track: 'private', topicId: SOR,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.sorular.donusum'],
    familyId: 'p2-sor-machen',
    instruction: 'Cümleyi soruya çevir:',
    prompt: 'Du machst Sport. → ______',
    answer: 'Machst du Sport?',
    pronounce: ['Machst du Sport?'],
  },
  {
    id: 'p2-sor-ja-antwort-free',
    day: 2, track: 'private', topicId: SOR,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.sorular.ja-nein-cevap'],
    familyId: 'p2-sor-gehen',
    instruction: 'Olumlu tam cümle ile cevap ver:',
    prompt: 'Gehst du heute zur Schule? → Ja, ______',
    answer: 'ich gehe heute zur Schule.',
    pronounce: ['Ja, ich gehe heute zur Schule.'],
  },
  {
    id: 'p2-sor-nein-antwort-schwester-free',
    day: 2, track: 'private', topicId: SOR,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.sorular.ja-nein-cevap'],
    familyId: 'p2-sor-haben',
    instruction: 'Olumsuz tam cümle ile cevap ver:',
    prompt: 'Hast du eine Schwester? → Nein, ______',
    answer: 'ich habe keine Schwester.',
    pronounce: ['Nein, ich habe keine Schwester.'],
  },
  {
    id: 'p2-sor-nein-antwort-kaffee-free',
    day: 2, track: 'private', topicId: SOR,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.sorular.ja-nein-cevap'],
    familyId: 'p2-sor-trinken',
    instruction: 'Olumsuz tam cümle ile cevap ver:',
    prompt: 'Trinkst du ein Kaffee? → Nein, ______',
    answer: 'ich trinke heute nicht.',
    pronounce: ['Nein, ich trinke heute nicht.'],
  },

  /* ================================================================
   * haben / sein — Kısa Tekrar (8)
   * ================================================================ */

  {
    id: 'p2-hs-habe-fill',
    day: 2, track: 'private', topicId: HAB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day2.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'ich → ______',
    answer: 'habe',
    pronounce: ['ich habe'],
  },
  {
    id: 'p2-hs-hast-fill',
    day: 2, track: 'private', topicId: HAB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day2.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'du → ______',
    answer: 'hast',
    pronounce: ['du hast'],
  },
  {
    id: 'p2-hs-hat-fill',
    day: 2, track: 'private', topicId: HAB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day2.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'er/sie/es → ______',
    answer: 'hat',
    pronounce: ['er hat'],
  },
  {
    id: 'p2-hs-haben-wir-fill',
    day: 2, track: 'private', topicId: HAB,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'wir → ______',
    answer: 'haben',
    pronounce: ['wir haben'],
  },
  {
    id: 'p2-hs-habt-fill',
    day: 2, track: 'private', topicId: HAB,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'ihr → ______',
    answer: 'habt',
    pronounce: ['ihr habt'],
  },
  {
    id: 'p2-hs-sein-review-mc',
    day: 2, track: 'private', topicId: HAB,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.sein.tekrar'],
    familyId: 'p2-hs-sein',
    instruction: 'sein çekimi (1. Günden tekrar):',
    prompt: 'du → sein',
    answer: 'bist',
    options: ['bin', 'bist', 'ist', 'sind'],
    pronounce: ['du bist'],
  },
  {
    id: 'p2-hs-haben-vs-sein-mc',
    day: 2, track: 'private', topicId: HAB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day2.haben.tablo', 'private.day2.sein.tekrar'],
    familyId: 'p2-hs-fark',
    instruction: '"Sahip olmak" anlamına gelen fiil hangisidir?',
    prompt: 'sahip olmak',
    answer: 'haben',
    options: ['haben', 'sein', 'machen', 'gehen'],
  },
  {
    id: 'p2-hs-kein-geld-matching',
    day: 2, track: 'private', topicId: HAB,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day2.haben.kein-ile'],
    familyId: 'p2-hs-kein-match',
    instruction: '"haben + kein/keine" cümlelerini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'Ich habe kein Geld.', right: 'Param yok.' },
      { left: 'Ich habe keine Schwester.', right: 'Kız kardeşim yok.' },
      { left: 'Sie hat keine Tasche.', right: 'Onun çantası yok.' },
    ],
    pronounce: ['Ich habe kein Geld.', 'Ich habe keine Schwester.', 'Sie hat keine Tasche.'],
  },

  /* ================================================================
   * Günlük Hayat Cümleleri — Sıralama / Listening / Dictation / Spoken (11)
   * ================================================================ */

  {
    id: 'p2-gun-order-arbeit',
    day: 2, track: 'private', topicId: GUN,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.gunluk.okul-is'],
    familyId: 'p2-gun-arbeit',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Mein / Vater / geht / jeden / Tag / zur / Arbeit.',
    answer: 'Mein Vater geht jeden Tag zur Arbeit.',
    words: ['Mein', 'Vater', 'geht', 'jeden', 'Tag', 'zur', 'Arbeit'],
    pronounce: ['Mein Vater geht jeden Tag zur Arbeit.'],
  },
  {
    id: 'p2-gun-order-schule',
    day: 2, track: 'private', topicId: GUN,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.gunluk.okul-is'],
    familyId: 'p2-gun-schule',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Er / geht / um / 2 / Uhr / zur / Schule.',
    answer: 'Er geht um 2 Uhr zur Schule.',
    words: ['Er', 'geht', 'um', '2', 'Uhr', 'zur', 'Schule'],
    pronounce: ['Er geht um 2 Uhr zur Schule.'],
  },
  {
    id: 'p2-gun-listen-kaffee',
    day: 2, track: 'private', topicId: GUN,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.gunluk.kahve-spor'],
    familyId: 'p2-gun-kaffee',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich trinke jeden Morgen ein Kaffee.',
    audioText: 'Ich trinke jeden Morgen ein Kaffee.',
    answer: 'Ich trinke jeden Morgen ein Kaffee.',
    options: [
      'Ich trinke jeden Morgen ein Kaffee.',
      'Ich mache jeden Tag Sport.',
      'Ich esse jeden Tag ein Brot.',
      'Ich lese jeden Tag ein Buch.',
    ],
    audio: { prompt: { text: 'Ich trinke jeden Morgen ein Kaffee.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p2-gun-listen-buch',
    day: 2, track: 'private', topicId: GUN,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day2.gunluk.kitap-okuma'],
    familyId: 'p2-gun-buch',
    instruction: 'Duyduğunu seç:',
    prompt: 'Liest du jeden Tag ein Buch?',
    audioText: 'Liest du jeden Tag ein Buch?',
    answer: 'Liest du jeden Tag ein Buch?',
    options: [
      'Liest du jeden Tag ein Buch?',
      'Machst du jeden Tag Sport?',
      'Trinkst du jeden Tag ein Kaffee?',
      'Gehst du jeden Tag zur Schule?',
    ],
    audio: { prompt: { text: 'Liest du jeden Tag ein Buch?', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p2-gun-dictation-schule',
    day: 2, track: 'private', topicId: GUN,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.gunluk.okul-is'],
    familyId: 'p2-gun-schule',
    instruction: 'Okul cümlesini duydun — aynen yaz:',
    audioText: 'Er geht um 2 Uhr zur Schule.',
    answer: 'Er geht um 2 Uhr zur Schule.',
    audio: { prompt: { text: 'Er geht um 2 Uhr zur Schule.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p2-gun-dictation-sport',
    day: 2, track: 'private', topicId: GUN,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.gunluk.kahve-spor'],
    familyId: 'p2-gun-sport-dictation',
    instruction: 'Spor cümlesini duydun — aynen yaz:',
    audioText: 'Ich mache jeden Tag Sport.',
    answer: 'Ich mache jeden Tag Sport.',
    audio: { prompt: { text: 'Ich mache jeden Tag Sport.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p2-gun-spoken-tanitim',
    day: 2, track: 'private', topicId: GUN,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day2.gunluk.okul-is', 'private.day2.gunluk.kahve-spor'],
    familyId: 'p2-gun-spoken',
    instruction: 'Sesli görev: günlük rutinini anlat.',
    requirements: ['Ich mache ...', 'Ich gehe ...'],
    sampleAnswer: 'Ich mache jeden Tag Sport. Ich gehe um 2 Uhr zur Schule.',
    pronounce: ['Ich mache jeden Tag Sport.', 'Ich gehe um 2 Uhr zur Schule.'],
  },
  {
    id: 'p2-gun-spoken-olumsuz',
    day: 2, track: 'private', topicId: GUN,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day2.olumsuzluk.nicht', 'private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-gun-spoken-neg',
    instruction: 'Sesli görev: bir şeyin olmadığını söyle.',
    requirements: ['Ich habe kein/keine ...', 'Ich ... nicht.'],
    sampleAnswer: 'Ich habe kein Geld. Ich arbeite heute nicht.',
    pronounce: ['Ich habe kein Geld.', 'Ich arbeite heute nicht.'],
  },
  {
    id: 'p2-gun-mini-dialog-schule-free',
    day: 2, track: 'private', topicId: GUN,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.gunluk.mini-dialog'],
    familyId: 'p2-gun-dialog',
    instruction: 'Mini diyalog: B ne demeli?',
    prompt: 'A: Gehst du heute zur Schule?\nB: ______',
    answer: 'Ja, ich gehe heute zur Schule.',
    acceptedAnswers: ['Nein, ich gehe heute nicht zur Schule.'],
    openEnded: true,
    pronounce: ['Ja, ich gehe heute zur Schule.'],
  },
  {
    id: 'p2-gun-mini-dialog-schwester-free',
    day: 2, track: 'private', topicId: GUN,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.gunluk.mini-dialog'],
    familyId: 'p2-gun-dialog',
    instruction: 'Mini diyalog: B ne demeli?',
    prompt: 'A: Hast du eine Schwester?\nB: ______',
    answer: 'Nein, ich habe keine Schwester.',
    acceptedAnswers: ['Ja, ich habe eine Schwester.'],
    openEnded: true,
    pronounce: ['Nein, ich habe keine Schwester.'],
  },
  {
    id: 'p2-gun-wb-geld-tr-de',
    day: 2, track: 'private', topicId: GUN,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-geld',
    instruction: 'Türkçeden Almancaya kur — Param yok.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Param yok.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'habe' }, { id: 't3', text: 'kein' }, { id: 't4', text: 'Geld.' },
        { id: 't5', text: 'keine' }, { id: 't6', text: 'Schwester.' },
      ],
      acceptedSequences: [['Ich', 'habe', 'kein', 'Geld.']],
    },
    answer: 'Ich habe kein Geld.',
    pronounce: ['Ich habe kein Geld.'],
  },

  /* ================================================================
   * Ek çeviri / word-bank alıştırmaları — konu dengesi (6)
   * ================================================================ */

  {
    id: 'p2-wb-schule-tr-de',
    day: 2, track: 'private', topicId: SOR,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-gehen',
    instruction: 'Türkçeden Almancaya kur — Bugün okula gidiyor musun?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Bugün okula gidiyor musun?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Gehst' }, { id: 't2', text: 'du' }, { id: 't3', text: 'heute' }, { id: 't4', text: 'zur' }, { id: 't5', text: 'Schule?' },
        { id: 't6', text: 'Machst' }, { id: 't7', text: 'Sport' },
      ],
      acceptedSequences: [['Gehst', 'du', 'heute', 'zur', 'Schule?']],
    },
    answer: 'Gehst du heute zur Schule?',
    pronounce: ['Gehst du heute zur Schule?'],
  },
  {
    id: 'p2-wb-vater-de-tr',
    day: 2, track: 'private', topicId: POS,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day2.verben.gehen-zur'],
    familyId: 'p2-pos-zur-arbeit',
    instruction: 'Almancadan Türkçeye çevir — Babam her gün işe gider.',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Mein Vater geht jeden Tag zur Arbeit.',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Babam' }, { id: 't2', text: 'her' }, { id: 't3', text: 'gün' }, { id: 't4', text: 'işe' }, { id: 't5', text: 'gider.' },
        { id: 't6', text: 'okula' },
      ],
      acceptedSequences: [['Babam', 'her', 'gün', 'işe', 'gider.']],
    },
    answer: 'Babam her gün işe gider.',
    audio: { prompt: { text: 'Mein Vater geht jeden Tag zur Arbeit.', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Mein Vater geht jeden Tag zur Arbeit.'],
  },
  {
    id: 'p2-wb-kein-vater-tr-de',
    day: 2, track: 'private', topicId: KMD,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day2.artikel.kein-keine'],
    familyId: 'p2-kmd-kein-vater',
    instruction: 'Türkçeden Almancaya kur — hiç baba değil',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'hiç baba değil',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'kein' }, { id: 't2', text: 'Vater' }, { id: 't3', text: 'ein' }, { id: 't4', text: 'mein' },
      ],
      acceptedSequences: [['kein', 'Vater']],
    },
    answer: 'kein Vater',
    pronounce: ['kein Vater'],
  },
  {
    id: 'p2-wb-artikel-mc',
    day: 2, track: 'private', topicId: ART,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day2.artikel.der-die-das-die-pl', 'private.day2.wortschatz.nesneler'],
    familyId: 'p2-art-heft',
    instruction: 'Doğru belirli artikeli seç:',
    prompt: '_____ Heft (defter)',
    answer: 'das',
    options: ['der', 'die', 'das', 'ein'],
    pronounce: ['das Heft'],
  },
  {
    id: 'p2-neg-extra-lese-nicht-fill',
    day: 2, track: 'private', topicId: NEG,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day2.olumsuzluk.nicht'],
    familyId: 'p2-gun-buch',
    instruction: 'Cümleyi olumsuz yap:',
    prompt: 'Ich lese _____ jeden Tag.',
    answer: 'nicht',
    pronounce: ['Ich lese nicht jeden Tag.'],
  },
  {
    id: 'p2-hs-extra-sind-fill',
    day: 2, track: 'private', topicId: HAB,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day2.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'sie/Sie → ______',
    answer: 'haben',
    pronounce: ['sie haben'],
  },
];
