/**
 * Özel Ders — 3. Gün — yazılmış alıştırma havuzu.
 *
 * Kaynak: öğrencinin ürettiği 80 Türkçe hedef cümle + kısmi Almanca denemeleri.
 * Tüm kavramlar concepts.ts içindeki private.day3.* kavramlarına bağlıdır; özet
 * kapsamı Özel Ders Özet.md üzerinden doğrulanır.
 *
 * Kapsam: bu gün, önceki private günlerin aksine bilinçli olarak Akkusativ
 * (einen, meinen, den) ve hafif Dativ (dem, der, meinen ... -n) biçimlerini
 * TANITIR — kaynak 80 cümlenin çoğu (es gibt, mit, in+yön, treffen) bunlar
 * olmadan doğru kurulamaz. Bu private.day2 kapsam sınırlamasını iptal etmez;
 * yalnızca 3. Güne özgü yeni bir kapsamdır.
 */

import type { AuthoredExercise } from '../types.ts';

const HED = 'private.day3.hedef';
const MG = 'private.day3.mogen-moechten-gern';
const EG = 'private.day3.es-gibt';
const YY = 'private.day3.yer-yon';
const AF = 'private.day3.ayrilabilen-fiiller';
const RF = 'private.day3.refleksif';
const SF = 'private.day3.sifat-ekleri';
const IY = 'private.day3.iyelik';
const MK = 'private.day3.miktar-cogul';
const ZI = 'private.day3.zaman';
const CD = 'private.day3.cumle-dizilisi';
const GH = 'private.day3.gunluk-hayat';

export const PRIVATE_DAY3_EXERCISES: AuthoredExercise[] = [
  /* ================================================================
   * Bugünün Hedefi (1)
   * ================================================================ */
  {
    id: 'p3-hed-giris-mc',
    day: 3, track: 'private', topicId: HED,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.hedef.giris'],
    familyId: 'p3-hed-giris',
    instruction: '3. Günün hedefi nedir?',
    prompt: '3. Gün ne üzerine kuruludur?',
    answer: '80 Türkçe cümleyi Almancaya kendi başına çevirebilmek',
    options: [
      '80 Türkçe cümleyi Almancaya kendi başına çevirebilmek',
      'Sadece yeni kelime ezberlemek',
      'Sadece dinleme yapmak',
      'Sadece sayıları tekrar etmek',
    ],
  },

  /* ================================================================
   * Sevmek ve İstemek — mögen, gern, möchten (14)
   * ================================================================ */
  {
    id: 'p3-mg-mag-cekim-mc',
    day: 3, track: 'private', topicId: MG,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.mogen.cekim'],
    familyId: 'p3-mg-mag-cekim',
    instruction: 'mögen çekimi — doğru formu seç:',
    prompt: 'ich ___ (mögen)',
    answer: 'mag',
    options: ['mag', 'magst', 'möchte', 'gern'],
    pronounce: ['ich mag'],
  },
  {
    id: 'p3-mg-magst-fill',
    day: 3, track: 'private', topicId: MG,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.mogen.cekim'],
    familyId: 'p3-mg-magst',
    instruction: 'mögen çekimi:',
    prompt: 'du ___ (mögen)',
    answer: 'magst',
    pronounce: ['du magst'],
  },
  {
    id: 'p3-mg-katzen-fill',
    day: 3, track: 'private', topicId: MG,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.mogen.cekim'],
    familyId: 'p3-mg-katzen',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich ___ Katzen. (kedileri severim)',
    answer: 'mag',
    pronounce: ['Ich mag Katzen.'],
  },
  {
    id: 'p3-mg-moechte-cekim-fill',
    day: 3, track: 'private', topicId: MG,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.moechten.cekim'],
    familyId: 'p3-mg-moechte-cekim',
    instruction: 'möchten çekimi:',
    prompt: 'ich ___ (möchten)',
    answer: 'möchte',
    pronounce: ['ich möchte'],
  },
  {
    id: 'p3-mg-moechtest-mc',
    day: 3, track: 'private', topicId: MG,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.moechten.cekim'],
    familyId: 'p3-mg-moechtest',
    instruction: 'möchten çekimi — doğru formu seç:',
    prompt: 'du ___ (möchten)',
    answer: 'möchtest',
    options: ['möchtest', 'möchte', 'magst', 'mögt'],
    pronounce: ['du möchtest'],
  },
  {
    id: 'p3-mg-brot-fill',
    day: 3, track: 'private', topicId: MG,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.moechten.cekim'],
    familyId: 'p3-mg-brot',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich ___ ein Brot kaufen. (bir ekmek almak istiyorum)',
    answer: 'möchte',
    pronounce: ['Ich möchte ein Brot kaufen.'],
  },
  {
    id: 'p3-mg-gern-yapi-mc',
    day: 3, track: 'private', topicId: MG,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.gern.kullanim'],
    familyId: 'p3-mg-gern-yapi',
    instruction: '"gern" cümlede nereye gelir?',
    prompt: 'gern',
    answer: 'Bir fiilden hemen sonra',
    options: ['Bir fiilden hemen sonra', 'Cümlenin en başına', 'Bir isimden önce', 'Tek başına kullanılır'],
  },
  {
    id: 'p3-mg-schwimme-gern-fill',
    day: 3, track: 'private', topicId: MG,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.gern.kullanim'],
    familyId: 'p3-mg-schwimme-gern',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich schwimme ___ im Meer. (yüzmeyi severim)',
    answer: 'gern',
    pronounce: ['Ich schwimme gern im Meer.'],
  },
  {
    id: 'p3-mg-esse-gern-order',
    day: 3, track: 'private', topicId: MG,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.gern.kullanim'],
    familyId: 'p3-mg-esse-gern',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / esse / gern / Äpfel.',
    answer: 'Ich esse gern Äpfel.',
    words: ['Ich', 'esse', 'gern', 'Äpfel'],
    pronounce: ['Ich esse gern Äpfel.'],
  },
  {
    id: 'p3-mg-spiele-gern-builder-tr',
    day: 3, track: 'private', topicId: MG,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.gern.kullanim'],
    familyId: 'p3-mg-spiele-gern',
    instruction: 'Cümleyi kur:',
    prompt: 'Ben futbol oynamayı seviyorum.',
    answer: 'Ich spiele gern Fußball.',
    words: ['Ich', 'spiele', 'gern', 'Fußball'],
    pronounce: ['Ich spiele gern Fußball.'],
  },
  {
    id: 'p3-mg-mag-gern-farki-mc',
    day: 3, track: 'private', topicId: MG,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.mogen-gern-farki'],
    familyId: 'p3-mg-farki',
    instruction: '"mag" ile "gern" arasındaki fark nedir?',
    prompt: 'mag ↔ gern',
    answer: 'mag bir ismi doğrudan sever, gern bir fiilden sonra gelir',
    options: [
      'mag bir ismi doğrudan sever, gern bir fiilden sonra gelir',
      'İkisi de tamamen aynı anlama gelir',
      'mag sadece soru cümlelerinde kullanılır',
      'gern sadece olumsuz cümlelerde kullanılır',
    ],
  },
  {
    id: 'p3-mg-tiere-fill',
    day: 3, track: 'private', topicId: MG,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.mogen-gern-farki'],
    familyId: 'p3-mg-tiere',
    instruction: 'Boşluğu doldur — bir ismi seviyorsun:',
    prompt: 'Meine Schwester ___ Tiere. (kardeşim hayvanları çok seviyor)',
    answer: 'mag',
    pronounce: ['Meine Schwester mag Tiere.'],
  },
  {
    id: 'p3-mg-schuhe-free-tr',
    day: 3, track: 'private', topicId: MG,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.moechten.cekim'],
    familyId: 'p3-mg-schuhe',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Ben siyah ayakkabı istiyorum. → ______',
    answer: 'Ich möchte schwarze Schuhe.',
    pronounce: ['Ich möchte schwarze Schuhe.'],
  },
  {
    id: 'p3-mg-wb-brot-tr-de',
    day: 3, track: 'private', topicId: MG,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.moechten.cekim', 'private.day3.moechten-infinitiv'],
    familyId: 'p3-mg-brot',
    instruction: 'Türkçeden Almancaya kur — Bir ekmek almak istiyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Bir ekmek almak istiyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'möchte' }, { id: 't3', text: 'ein' },
        { id: 't4', text: 'Brot' }, { id: 't5', text: 'kaufen.' }, { id: 't6', text: 'mag' },
      ],
      acceptedSequences: [['Ich', 'möchte', 'ein', 'Brot', 'kaufen.']],
    },
    answer: 'Ich möchte ein Brot kaufen.',
    pronounce: ['Ich möchte ein Brot kaufen.'],
  },

  /* ================================================================
   * es gibt — Var / Yok (10)
   * ================================================================ */
  {
    id: 'p3-eg-temel-mc',
    day: 3, track: 'private', topicId: EG,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.esgibt.temel'],
    familyId: 'p3-eg-temel',
    instruction: '"Es gibt" ne demektir?',
    prompt: 'Es gibt',
    answer: '... var',
    options: ['... var', '... yok', '... geliyor', '... gidiyor'],
    pronounce: ['Es gibt'],
  },
  {
    id: 'p3-eg-blumen-fill',
    day: 3, track: 'private', topicId: EG,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.esgibt.temel'],
    familyId: 'p3-eg-blumen',
    instruction: 'Boşluğu doldur:',
    prompt: 'Auf dem Balkon ___ es Blumen. (balkonda çiçekler var)',
    answer: 'gibt',
    pronounce: ['Auf dem Balkon gibt es Blumen.'],
  },
  {
    id: 'p3-eg-leute-fill',
    day: 3, track: 'private', topicId: EG,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.esgibt.temel'],
    familyId: 'p3-eg-leute',
    instruction: 'Boşluğu doldur:',
    prompt: 'Im Markt gibt ___ viele Leute. (markette çok insan var)',
    answer: 'es',
    pronounce: ['Im Markt gibt es viele Leute.'],
  },
  {
    id: 'p3-eg-akkusativ-mc',
    day: 3, track: 'private', topicId: EG,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.esgibt.akkusativ'],
    familyId: 'p3-eg-akkusativ',
    instruction: '"es gibt" hangi hâli ister?',
    prompt: 'es gibt + ...?',
    answer: 'Akkusativ',
    options: ['Akkusativ', 'Dativ', 'Nominativ', 'hiçbiri'],
  },
  {
    id: 'p3-eg-tisch-fill',
    day: 3, track: 'private', topicId: EG,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.esgibt.akkusativ'],
    familyId: 'p3-eg-tisch',
    instruction: 'Boşluğu doldur — der Tisch, es gibt + Akkusativ:',
    prompt: 'In meinem Zimmer gibt es ___ Tisch. (odamda bir masa var)',
    answer: 'einen',
    pronounce: ['In meinem Zimmer gibt es einen Tisch.'],
  },
  {
    id: 'p3-eg-balkon-fill',
    day: 3, track: 'private', topicId: EG,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.esgibt.akkusativ'],
    familyId: 'p3-eg-balkon',
    instruction: 'Boşluğu doldur — der Balkon, haben + Akkusativ:',
    prompt: 'Wir haben ___ Balkon. (bir balkonumuz var)',
    answer: 'einen',
    pronounce: ['Wir haben einen Balkon.'],
  },
  {
    id: 'p3-eg-error-balkon',
    day: 3, track: 'private', topicId: EG,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.esgibt.akkusativ'],
    familyId: 'p3-eg-balkon',
    instruction: 'Hata avı — doğru artikel hangisi?',
    prompt: 'Wir haben ein Balkon.',
    answer: 'Wir haben einen Balkon.',
    explanation: 'der Balkon erildir; haben Akkusativ ister → ein değil einen.',
    pronounce: ['Wir haben einen Balkon.'],
  },
  {
    id: 'p3-eg-genel-cogul-mc',
    day: 3, track: 'private', topicId: EG,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.esgibt.genel-cogul'],
    familyId: 'p3-eg-genel-cogul',
    instruction: '"es gibt" ile genel bir çoğulda artikel nasıl kullanılır?',
    prompt: 'Es gibt + çoğul isim (genel)',
    answer: 'artikelsiz',
    options: ['artikelsiz', 'die ile', 'ein ile', 'kein ile'],
  },
  {
    id: 'p3-eg-error-blumen',
    day: 3, track: 'private', topicId: EG,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.esgibt.genel-cogul'],
    familyId: 'p3-eg-blumen',
    instruction: 'Hata avı — genel ifadede artikel gerekli mi?',
    prompt: 'Auf dem Balkon gibt es die Blumen.',
    answer: 'Auf dem Balkon gibt es Blumen.',
    explanation: 'Genel/sayılamayan bir durumda çoğul isim artikelsiz kullanılır.',
    pronounce: ['Auf dem Balkon gibt es Blumen.'],
  },
  {
    id: 'p3-eg-free-balkon-tr',
    day: 3, track: 'private', topicId: EG,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.esgibt.temel', 'private.day3.esgibt.genel-cogul'],
    familyId: 'p3-eg-blumen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Balkonda çiçekler var. → ______',
    answer: 'Auf dem Balkon gibt es Blumen.',
    pronounce: ['Auf dem Balkon gibt es Blumen.'],
  },

  /* ================================================================
   * Yer, Yön ve Küçük Ama Önemli Kelimeler (26)
   * ================================================================ */
  {
    id: 'p3-yy-zum-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.kontraksiyon.zum'],
    familyId: 'p3-yy-zum',
    instruction: '"zum" hangi iki kelimenin birleşimidir?',
    prompt: 'zum',
    answer: 'zu + dem',
    options: ['zu + dem', 'zu + der', 'in + dem', 'an + dem'],
  },
  {
    id: 'p3-yy-zum-markt-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.kontraksiyon.zum'],
    familyId: 'p3-yy-zum-markt',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Mutter geht ___ Markt. (annem markete gidiyor)',
    answer: 'zum',
    pronounce: ['Meine Mutter geht zum Markt.'],
  },
  {
    id: 'p3-yy-zur-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.kontraksiyon.zur'],
    familyId: 'p3-yy-zur',
    instruction: '"zur" hangi iki kelimenin birleşimidir?',
    prompt: 'zur',
    answer: 'zu + der',
    options: ['zu + der', 'zu + dem', 'in + der', 'an + der'],
  },
  {
    id: 'p3-yy-zur-schule-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.kontraksiyon.zur'],
    familyId: 'p3-yy-zur-schule',
    instruction: 'Boşluğu doldur (2. Günden tekrar):',
    prompt: 'Meine Schwester geht ___ Schule. (kardeşim okula gidiyor)',
    answer: 'zur',
    pronounce: ['Meine Schwester geht zur Schule.'],
  },
  {
    id: 'p3-yy-im-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.kontraksiyon.im'],
    familyId: 'p3-yy-im',
    instruction: '"im" hangi iki kelimenin birleşimidir?',
    prompt: 'im',
    answer: 'in + dem',
    options: ['in + dem', 'in + das', 'an + dem', 'zu + dem'],
  },
  {
    id: 'p3-yy-im-garten-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.kontraksiyon.im'],
    familyId: 'p3-yy-im-garten',
    instruction: 'Boşluğu doldur:',
    prompt: 'Mein Hund spielt ___ Garten. (köpeğim bahçede oynuyor)',
    answer: 'im',
    pronounce: ['Mein Hund spielt im Garten.'],
  },
  {
    id: 'p3-yy-ins-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.kontraksiyon.ins'],
    familyId: 'p3-yy-ins',
    instruction: '"ins" hangi iki kelimenin birleşimidir?',
    prompt: 'ins',
    answer: 'in + das',
    options: ['in + das', 'in + dem', 'an + das', 'zu + dem'],
  },
  {
    id: 'p3-yy-ins-kino-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.kontraksiyon.ins'],
    familyId: 'p3-yy-ins-kino',
    instruction: 'Boşluğu doldur:',
    prompt: 'Wir gehen am Abend ___ Kino. (akşam sinemaya gidiyoruz)',
    answer: 'ins',
    pronounce: ['Wir gehen am Abend ins Kino.'],
  },
  {
    id: 'p3-yy-am-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.kontraksiyon.am'],
    familyId: 'p3-yy-am',
    instruction: '"am" hangi iki kelimenin birleşimidir?',
    prompt: 'am',
    answer: 'an + dem',
    options: ['an + dem', 'in + dem', 'zu + dem', 'an + das'],
  },
  {
    id: 'p3-yy-ans-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.kontraksiyon.ans'],
    familyId: 'p3-yy-ans',
    instruction: 'Boşluğu doldur — an + das = ans:',
    prompt: 'Im Sommer gehe ich ___ Meer. (yazın denize gidiyorum)',
    answer: 'ans',
    pronounce: ['Im Sommer gehe ich ans Meer.'],
  },
  {
    id: 'p3-yy-im-ins-farki-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.im-ins-farki'],
    familyId: 'p3-yy-im-ins-farki',
    instruction: '"im" ile "ins" arasındaki fark nedir?',
    prompt: 'im ↔ ins',
    answer: 'im yerde kalmayı, ins bir yöne gitmeyi anlatır',
    options: [
      'im yerde kalmayı, ins bir yöne gitmeyi anlatır',
      'ikisi de aynı anlama gelir',
      'im sadece mevsimlerde, ins sadece filmlerde kullanılır',
      'im çoğul, ins tekil isimlerde kullanılır',
    ],
  },
  {
    id: 'p3-yy-im-park-vs-in-den-park-matching',
    day: 3, track: 'private', topicId: YY,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.im-ins-farki', 'private.day3.in-akkusativ-yon'],
    familyId: 'p3-yy-park-match',
    instruction: 'Cümleyi doğru anlamla eşleştir.',
    pairs: [
      { left: 'Wir machen einen Spaziergang im Park.', right: 'Parkta yürüyüş yapıyoruz. (konum)' },
      { left: 'Ich gehe mit meinen Freunden in den Park.', right: 'Arkadaşlarımla parka gidiyorum. (yön)' },
    ],
    pronounce: ['Wir machen einen Spaziergang im Park.', 'Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-nach-hause-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.nach-hause'],
    familyId: 'p3-yy-nach-hause',
    instruction: '"nach Hause" ne demektir?',
    prompt: 'nach Hause',
    answer: 'eve (bir yöne gitmek)',
    options: ['eve (bir yöne gitmek)', 'evde (konum)', 'evden', 'ev için'],
  },
  {
    id: 'p3-yy-nach-hause-zurueck-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.nach-hause'],
    familyId: 'p3-yy-nach-hause-abend',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich komme am Abend ___ Hause zurück. (akşam eve dönüyorum)',
    answer: 'nach',
    pronounce: ['Ich komme am Abend nach Hause zurück.'],
  },
  {
    id: 'p3-yy-zu-hause-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.zu-hause'],
    familyId: 'p3-yy-zu-hause',
    instruction: '"zu Hause" ne demektir?',
    prompt: 'zu Hause',
    answer: 'evde (konum)',
    options: ['evde (konum)', 'eve (yön)', 'ev', 'evden'],
  },
  {
    id: 'p3-yy-zu-hause-musik-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.zu-hause'],
    familyId: 'p3-yy-zu-hause-musik',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich höre ___ Hause ein bisschen Musik. (evde biraz müzik dinliyorum)',
    answer: 'zu',
    pronounce: ['Ich höre zu Hause ein bisschen Musik.'],
  },
  {
    id: 'p3-yy-nach-zu-hause-error',
    day: 3, track: 'private', topicId: YY,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.nach-hause', 'private.day3.zu-hause'],
    familyId: 'p3-yy-nach-zu-farki',
    instruction: 'Hata avı — yön mü konum mu?',
    prompt: 'Ich komme um 4 Uhr zu Hause. (eve geliyorum — yön anlatılıyor)',
    answer: 'Ich komme um 4 Uhr nach Hause.',
    explanation: 'Bir yöne (eve doğru) gidildiği için "nach Hause" gerekir, "zu Hause" (evde, konum) değil.',
    pronounce: ['Ich komme um 4 Uhr nach Hause.'],
  },
  {
    id: 'p3-yy-mit-dativ-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.mit-dativ'],
    familyId: 'p3-yy-mit-dativ',
    instruction: '"mit" hangi hâli ister?',
    prompt: 'mit',
    answer: 'Dativ',
    options: ['Dativ', 'Akkusativ', 'Nominativ', 'hiçbiri'],
  },
  {
    id: 'p3-yy-mit-mir-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.mit-dativ'],
    familyId: 'p3-yy-mit-mir',
    instruction: 'Boşluğu doldur:',
    prompt: 'Mein Freund sitzt ___ mir. (arkadaşım benimle oturuyor)',
    answer: 'mit',
    pronounce: ['Mein Freund sitzt mit mir.'],
  },
  {
    id: 'p3-yy-meinen-freunden-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.mit-meinen-freunden'],
    familyId: 'p3-yy-meinen-freunden',
    instruction: 'Boşluğu doldur — mit + Dativ çoğul:',
    prompt: 'Ich gehe mit ___ Freunden in den Park. (arkadaşlarımla parka gidiyorum)',
    answer: 'meinen',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-error-meinen-freunde',
    day: 3, track: 'private', topicId: YY,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.mit-meinen-freunden'],
    familyId: 'p3-yy-meinen-freunde-error',
    instruction: 'Hata avı — Dativ çoğulda ne değişir?',
    prompt: 'Ich gehe mit meinen Freunde ins Park.',
    answer: 'Ich gehe mit meinen Freunden in den Park.',
    explanation: 'mit Dativ ister: isim Dativ çoğulda -n alır (Freunde → Freunden); der Park eril olduğu için yönde "in den Park" olur, "ins Park" değil.',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-der-den-dem-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.der-den-dem'],
    familyId: 'p3-yy-der-den-dem',
    instruction: '"der Regen" cümlenin doğrudan nesnesi olduğunda nasıl olur?',
    prompt: 'der Regen (Akkusativ nesne)',
    answer: 'den Regen',
    options: ['den Regen', 'dem Regen', 'der Regen', 'des Regen'],
  },
  {
    id: 'p3-yy-den-regen-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.der-den-dem'],
    familyId: 'p3-yy-den-regen',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich mag ___ Regen nicht. (yağmuru sevmiyorum)',
    answer: 'den',
    pronounce: ['Ich mag den Regen nicht.'],
  },
  {
    id: 'p3-yy-in-den-park-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.in-akkusativ-yon'],
    familyId: 'p3-yy-in-den-park',
    instruction: 'Boşluğu doldur — yöne gidiyorsun, der Park:',
    prompt: 'Ich gehe mit meinen Freunden in ___ Park.',
    answer: 'den',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-auf-dem-tisch-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.auf-dem'],
    familyId: 'p3-yy-auf-dem-tisch',
    instruction: 'Boşluğu doldur:',
    prompt: 'Auf ___ Tisch gibt es Bücher. (masanın üzerinde kitaplar var)',
    answer: 'dem',
    pronounce: ['Auf dem Tisch gibt es Bücher.'],
  },
  {
    id: 'p3-yy-bei-der-schule-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.bei-der'],
    familyId: 'p3-yy-bei-der-schule',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Wohnung ist nah bei ___ Schule. (evim okula yakın)',
    answer: 'der',
    pronounce: ['Meine Wohnung ist nah bei der Schule.'],
  },
  {
    id: 'p3-yy-wb-freunden-tr-de',
    day: 3, track: 'private', topicId: YY,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.mit-meinen-freunden', 'private.day3.in-akkusativ-yon'],
    familyId: 'p3-yy-meinen-freunden',
    instruction: 'Türkçeden Almancaya kur — Arkadaşlarımla parka gidiyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Arkadaşlarımla parka gidiyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'gehe' }, { id: 't3', text: 'mit' }, { id: 't4', text: 'meinen' },
        { id: 't5', text: 'Freunden' }, { id: 't6', text: 'in' }, { id: 't7', text: 'den' }, { id: 't8', text: 'Park.' },
        { id: 't9', text: 'im' },
      ],
      acceptedSequences: [['Ich', 'gehe', 'mit', 'meinen', 'Freunden', 'in', 'den', 'Park.']],
    },
    answer: 'Ich gehe mit meinen Freunden in den Park.',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-wb-tisch-de-tr',
    day: 3, track: 'private', topicId: YY,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.kontraksiyon.im', 'private.day3.esgibt.temel'],
    familyId: 'p3-yy-zimmer-tisch',
    instruction: 'Almancadan Türkçeye çevir — Odamda bir masa var.',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'In meinem Zimmer gibt es einen Tisch.',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Odamda' }, { id: 't2', text: 'bir' }, { id: 't3', text: 'masa' }, { id: 't4', text: 'var.' },
        { id: 't5', text: 'sandalye' },
      ],
      acceptedSequences: [['Odamda', 'bir', 'masa', 'var.']],
    },
    answer: 'Odamda bir masa var.',
    audio: { prompt: { text: 'In meinem Zimmer gibt es einen Tisch.', language: 'de-DE', role: 'prompt' } },
    pronounce: ['In meinem Zimmer gibt es einen Tisch.'],
  },
  {
    id: 'p3-yy-free-park-tr',
    day: 3, track: 'private', topicId: YY,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.mit-meinen-freunden', 'private.day3.in-akkusativ-yon'],
    familyId: 'p3-yy-park-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Arkadaşlarımla parka gidiyorum. → ______',
    answer: 'Ich gehe mit meinen Freunden in den Park.',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-listen-garten',
    day: 3, track: 'private', topicId: YY,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.kontraksiyon.im'],
    familyId: 'p3-yy-im-garten',
    instruction: 'Duyduğunu seç:',
    prompt: 'Mein Hund spielt im Garten.',
    audioText: 'Mein Hund spielt im Garten.',
    answer: 'Mein Hund spielt im Garten.',
    options: [
      'Mein Hund spielt im Garten.',
      'Mein Hund spielt im Park.',
      'Meine Katze spielt im Garten.',
      'Mein Vater spielt im Garten.',
    ],
    audio: { prompt: { text: 'Mein Hund spielt im Garten.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Ayrılabilen Fiiller (11)
   * ================================================================ */
  {
    id: 'p3-af-kural-mc',
    day: 3, track: 'private', topicId: AF,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.ayrilabilen.kural'],
    familyId: 'p3-af-kural',
    instruction: 'Ayrılabilen fiillerde önek cümlede nereye gider?',
    prompt: 'aufstehen, aufräumen, zurückkommen ...',
    answer: 'Cümlenin en sonuna',
    options: ['Cümlenin en sonuna', 'Fiilden hemen önce', 'Cümlenin en başına', 'Özneden hemen sonra'],
  },
  {
    id: 'p3-af-aufstehen-anlam-mc',
    day: 3, track: 'private', topicId: AF,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.aufstehen'],
    familyId: 'p3-af-aufstehen-anlam',
    instruction: '"aufstehen" ne demektir?',
    prompt: 'aufstehen',
    answer: 'kalkmak',
    options: ['kalkmak', 'oturmak', 'yatmak', 'gelmek'],
    pronounce: ['aufstehen'],
  },
  {
    id: 'p3-af-stehe-auf-fill',
    day: 3, track: 'private', topicId: AF,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.aufstehen'],
    familyId: 'p3-af-stehe-auf',
    instruction: 'Boşluğu doldur — aufstehen ayrılır:',
    prompt: 'Ich stehe jeden Tag früh ___. (her gün erken kalkıyorum)',
    answer: 'auf',
    pronounce: ['Ich stehe jeden Tag früh auf.'],
  },
  {
    id: 'p3-af-order-7uhr',
    day: 3, track: 'private', topicId: AF,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.aufstehen', 'private.day3.zaman.um-uhr'],
    familyId: 'p3-af-7uhr',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / stehe / um / 7 / Uhr / auf.',
    answer: 'Ich stehe um 7 Uhr auf.',
    words: ['Ich', 'stehe', 'um', '7', 'Uhr', 'auf'],
    pronounce: ['Ich stehe um 7 Uhr auf.'],
  },
  {
    id: 'p3-af-error-aufstehe',
    day: 3, track: 'private', topicId: AF,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.aufstehen', 'private.day3.ayrilabilen.kural'],
    familyId: 'p3-af-7uhr',
    instruction: 'Hata avı — önek nereye gitmeli?',
    prompt: 'Ich aufstehe um 7 Uhr.',
    answer: 'Ich stehe um 7 Uhr auf.',
    explanation: 'aufstehen ayrılabilen bir fiildir: fiil ikinci sırada çekilir (stehe), önek (auf) cümlenin en sonuna gider.',
    pronounce: ['Ich stehe um 7 Uhr auf.'],
  },
  {
    id: 'p3-af-aufraeumen-anlam-mc',
    day: 3, track: 'private', topicId: AF,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.aufraeumen'],
    familyId: 'p3-af-aufraeumen-anlam',
    instruction: '"aufräumen" ne demektir?',
    prompt: 'aufräumen',
    answer: 'toplamak / düzenlemek',
    options: ['toplamak / düzenlemek', 'temizlemek (yıkamak)', 'satın almak', 'sulama'],
    pronounce: ['aufräumen'],
  },
  {
    id: 'p3-af-raeumt-auf-fill',
    day: 3, track: 'private', topicId: AF,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.aufraeumen'],
    familyId: 'p3-af-raeumt-auf',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Schwester räumt ihr Bett ___. (yatağını topluyor)',
    answer: 'auf',
    pronounce: ['Meine Schwester räumt ihr Bett auf.'],
  },
  {
    id: 'p3-af-builder-bett-tr',
    day: 3, track: 'private', topicId: AF,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.aufraeumen'],
    familyId: 'p3-af-raeumt-auf',
    instruction: 'Cümleyi kur:',
    prompt: 'Kardeşim yatağını topluyor.',
    answer: 'Meine Schwester räumt ihr Bett auf.',
    words: ['Meine', 'Schwester', 'räumt', 'ihr', 'Bett', 'auf'],
    pronounce: ['Meine Schwester räumt ihr Bett auf.'],
  },
  {
    id: 'p3-af-zurueckkommen-anlam-mc',
    day: 3, track: 'private', topicId: AF,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.zurueckkommen'],
    familyId: 'p3-af-zurueck-anlam',
    instruction: '"zurückkommen" ne demektir?',
    prompt: 'zurückkommen',
    answer: 'geri dönmek',
    options: ['geri dönmek', 'ileri gitmek', 'kalkmak', 'toplamak'],
    pronounce: ['zurückkommen'],
  },
  {
    id: 'p3-af-komme-zurueck-fill',
    day: 3, track: 'private', topicId: AF,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.zurueckkommen'],
    familyId: 'p3-af-komme-zurueck',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich komme am Abend nach Hause ___. (akşam eve dönüyorum)',
    answer: 'zurück',
    pronounce: ['Ich komme am Abend nach Hause zurück.'],
  },
  {
    id: 'p3-af-wb-zurueck-tr-de',
    day: 3, track: 'private', topicId: AF,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.zurueckkommen'],
    familyId: 'p3-af-komme-zurueck',
    instruction: 'Türkçeden Almancaya kur — Akşam eve dönüyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Akşam eve dönüyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'komme' }, { id: 't3', text: 'am' }, { id: 't4', text: 'Abend' },
        { id: 't5', text: 'nach' }, { id: 't6', text: 'Hause' }, { id: 't7', text: 'zurück.' }, { id: 't8', text: 'auf' },
      ],
      acceptedSequences: [['Ich', 'komme', 'am', 'Abend', 'nach', 'Hause', 'zurück.']],
    },
    answer: 'Ich komme am Abend nach Hause zurück.',
    pronounce: ['Ich komme am Abend nach Hause zurück.'],
  },

  /* ================================================================
   * Refleksif Fiiller (9)
   * ================================================================ */
  {
    id: 'p3-rf-temel-mc',
    day: 3, track: 'private', topicId: RF,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.refleksif.temel'],
    familyId: 'p3-rf-temel',
    instruction: '"ich" için refleksif zamir hangisidir?',
    prompt: 'ich → ___',
    answer: 'mich',
    options: ['mich', 'dich', 'sich', 'uns'],
    pronounce: ['mich'],
  },
  {
    id: 'p3-rf-du-fill',
    day: 3, track: 'private', topicId: RF,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.refleksif.temel'],
    familyId: 'p3-rf-du',
    instruction: 'Refleksif zamir:',
    prompt: 'du → ___',
    answer: 'dich',
    pronounce: ['dich'],
  },
  {
    id: 'p3-rf-duschen-anlam-mc',
    day: 3, track: 'private', topicId: RF,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.sich-duschen'],
    familyId: 'p3-rf-duschen-anlam',
    instruction: '"sich duschen" ne demektir?',
    prompt: 'sich duschen',
    answer: 'duş almak',
    options: ['duş almak', 'dinlenmek', 'kalkmak', 'temizlemek'],
    pronounce: ['sich duschen'],
  },
  {
    id: 'p3-rf-dusche-mich-fill',
    day: 3, track: 'private', topicId: RF,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.sich-duschen'],
    familyId: 'p3-rf-dusche-mich',
    instruction: 'Boşluğu doldur:',
    prompt: 'Dann dusche ich ___. (sonra duş alıyorum)',
    answer: 'mich',
    pronounce: ['Dann dusche ich mich.'],
  },
  {
    id: 'p3-rf-ausruhen-anlam-mc',
    day: 3, track: 'private', topicId: RF,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.sich-ausruhen'],
    familyId: 'p3-rf-ausruhen-anlam',
    instruction: '"sich ausruhen" ne demektir?',
    prompt: 'sich ausruhen',
    answer: 'dinlenmek',
    options: ['dinlenmek', 'duş almak', 'toplamak', 'kalkmak'],
    pronounce: ['sich ausruhen'],
  },
  {
    id: 'p3-rf-ruhe-mich-aus-order',
    day: 3, track: 'private', topicId: RF,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.sich-ausruhen', 'private.day3.refleksif-ayrilabilen'],
    familyId: 'p3-rf-ruhe-mich-aus',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / ruhe / mich / am / Abend / ein / bisschen / aus.',
    answer: 'Ich ruhe mich am Abend ein bisschen aus.',
    words: ['Ich', 'ruhe', 'mich', 'am', 'Abend', 'ein', 'bisschen', 'aus'],
    pronounce: ['Ich ruhe mich am Abend ein bisschen aus.'],
  },
  {
    id: 'p3-rf-error-mich-sonda',
    day: 3, track: 'private', topicId: RF,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.refleksif-ayrilabilen'],
    familyId: 'p3-rf-ruhe-mich-aus',
    instruction: 'Hata avı — refleksif zamir nereye gitmeli?',
    prompt: 'Ich ruhe am Abend ein bisschen aus mich.',
    answer: 'Ich ruhe mich am Abend ein bisschen aus.',
    explanation: 'Refleksif zamir (mich) çekimli fiilden hemen sonra gelir; ayrılabilen önek (aus) cümlenin en sonuna gider.',
    pronounce: ['Ich ruhe mich am Abend ein bisschen aus.'],
  },
  {
    id: 'p3-rf-wb-dusche-tr-de',
    day: 3, track: 'private', topicId: RF,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.sich-duschen'],
    familyId: 'p3-rf-dusche-mich',
    instruction: 'Türkçeden Almancaya kur — Sonra duş alıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Sonra duş alıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Dann' }, { id: 't2', text: 'dusche' }, { id: 't3', text: 'ich' }, { id: 't4', text: 'mich.' },
        { id: 't5', text: 'dich' },
      ],
      acceptedSequences: [['Dann', 'dusche', 'ich', 'mich.']],
    },
    answer: 'Dann dusche ich mich.',
    pronounce: ['Dann dusche ich mich.'],
  },
  {
    id: 'p3-rf-free-ausruhen-tr',
    day: 3, track: 'private', topicId: RF,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.sich-ausruhen', 'private.day3.refleksif-ayrilabilen'],
    familyId: 'p3-rf-ausruhen-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Akşam biraz dinleniyorum. → ______',
    answer: 'Ich ruhe mich am Abend ein bisschen aus.',
    pronounce: ['Ich ruhe mich am Abend ein bisschen aus.'],
  },

  /* ================================================================
   * Sıfatlar ve Ekler (9)
   * ================================================================ */
  {
    id: 'p3-sf-yuklem-mc',
    day: 3, track: 'private', topicId: SF,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.sifat.yuklem'],
    familyId: 'p3-sf-yuklem',
    instruction: 'Bir sıfat "sein" fiilinden sonra geldiğinde ek alır mı?',
    prompt: 'Das Kleid ist sehr schön.',
    answer: 'Hayır, ek almaz',
    options: ['Hayır, ek almaz', 'Evet, her zaman -e alır', 'Evet, her zaman -es alır', 'Sadece çoğulda ek alır'],
  },
  {
    id: 'p3-sf-schoen-fill',
    day: 3, track: 'private', topicId: SF,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.sifat.yuklem'],
    familyId: 'p3-sf-schoen',
    instruction: 'Boşluğu doldur (ek yok):',
    prompt: 'Mein Zimmer ist klein, aber ___. (küçük ama güzel)',
    answer: 'schön',
    pronounce: ['Mein Zimmer ist klein, aber schön.'],
  },
  {
    id: 'p3-sf-ein-notr-mc',
    day: 3, track: 'private', topicId: SF,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.sifat.ein-notr'],
    familyId: 'p3-sf-ein-notr',
    instruction: '"ein" + nötr isim + sıfat kalıbında sıfat hangi eki alır?',
    prompt: 'ein ___ T-Shirt (neu)',
    answer: 'neues',
    options: ['neues', 'neue', 'neuer', 'neu'],
  },
  {
    id: 'p3-sf-neues-tshirt-fill',
    day: 3, track: 'private', topicId: SF,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.sifat.ein-notr'],
    familyId: 'p3-sf-neues-tshirt',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich kaufe ein ___ T-Shirt. (yeni bir tişört alıyorum — neu)',
    answer: 'neues',
    pronounce: ['Ich kaufe ein neues T-Shirt.'],
  },
  {
    id: 'p3-sf-cogul-artikelsiz-mc',
    day: 3, track: 'private', topicId: SF,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.sifat.cogul-artikelsiz'],
    familyId: 'p3-sf-cogul-artikelsiz',
    instruction: 'Artikelsiz çoğul isimden önceki sıfat hangi eki alır?',
    prompt: 'schwarz + Schuhe (artikelsiz çoğul)',
    answer: 'schwarze',
    options: ['schwarze', 'schwarzes', 'schwarzer', 'schwarz'],
  },
  {
    id: 'p3-sf-schwarze-schuhe-fill',
    day: 3, track: 'private', topicId: SF,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.sifat.cogul-artikelsiz'],
    familyId: 'p3-sf-schwarze-schuhe',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich möchte ___ Schuhe. (siyah ayakkabı istiyorum — schwarz)',
    answer: 'schwarze',
    pronounce: ['Ich möchte schwarze Schuhe.'],
  },
  {
    id: 'p3-sf-error-eine-schwarze-schuhe',
    day: 3, track: 'private', topicId: SF,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.sifat.cogul-artikelsiz'],
    familyId: 'p3-sf-schwarze-schuhe',
    instruction: 'Hata avı — çoğulda belirsiz artikel var mı?',
    prompt: 'Ich möchte eine schwarze Schuhe.',
    answer: 'Ich möchte schwarze Schuhe.',
    explanation: 'Schuhe çoğuldur; çoğulda belirsiz artikel (eine) kullanılmaz, sıfat artikelsiz -e eki alır.',
    pronounce: ['Ich möchte schwarze Schuhe.'],
  },
  {
    id: 'p3-sf-wb-tshirt-tr-de',
    day: 3, track: 'private', topicId: SF,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.sifat.ein-notr'],
    familyId: 'p3-sf-neues-tshirt',
    instruction: 'Türkçeden Almancaya kur — Ben yeni bir tişört alıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ben yeni bir tişört alıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'kaufe' }, { id: 't3', text: 'ein' }, { id: 't4', text: 'neues' },
        { id: 't5', text: 'T-Shirt.' }, { id: 't6', text: 'neue' },
      ],
      acceptedSequences: [['Ich', 'kaufe', 'ein', 'neues', 'T-Shirt.']],
    },
    answer: 'Ich kaufe ein neues T-Shirt.',
    pronounce: ['Ich kaufe ein neues T-Shirt.'],
  },
  {
    id: 'p3-sf-free-elbise-tr',
    day: 3, track: 'private', topicId: SF,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.sifat.yuklem'],
    familyId: 'p3-sf-elbise',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu elbise çok güzel. → ______',
    answer: 'Das Kleid ist sehr schön.',
    pronounce: ['Das Kleid ist sehr schön.'],
  },

  /* ================================================================
   * İyelik Yapıları — mein, dein, unser, ihr (8)
   * ================================================================ */
  {
    id: 'p3-iy-unser-mc',
    day: 3, track: 'private', topicId: IY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.iyelik.unser'],
    familyId: 'p3-iy-unser',
    instruction: '"unser / unsere" ne demektir?',
    prompt: 'unser / unsere',
    answer: 'bizim',
    options: ['bizim', 'senin', 'onun', 'benim'],
  },
  {
    id: 'p3-iy-unsere-wohnung-fill',
    day: 3, track: 'private', topicId: IY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.iyelik.unser'],
    familyId: 'p3-iy-unsere-wohnung',
    instruction: 'Boşluğu doldur (die Wohnung, dişil):',
    prompt: '___ Wohnung hat drei Zimmer. (evimizde üç oda var)',
    answer: 'Unsere',
    pronounce: ['Unsere Wohnung hat drei Zimmer.'],
  },
  {
    id: 'p3-iy-unser-lehrer-fill',
    day: 3, track: 'private', topicId: IY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.iyelik.unser'],
    familyId: 'p3-iy-unser-lehrer',
    instruction: 'Boşluğu doldur (der Lehrer, eril, eksiz):',
    prompt: '___ Lehrer ist sehr gut. (öğretmenimiz çok iyi)',
    answer: 'Unser',
    pronounce: ['Unser Lehrer ist sehr gut.'],
  },
  {
    id: 'p3-iy-ihr-mc',
    day: 3, track: 'private', topicId: IY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.iyelik.ihr'],
    familyId: 'p3-iy-ihr',
    instruction: '"ihr / ihre" (kadın için) ne demektir?',
    prompt: 'ihr / ihre',
    answer: 'onun (kadın)',
    options: ['onun (kadın)', 'senin', 'bizim', 'onun (erkek)'],
  },
  {
    id: 'p3-iy-ihrem-zimmer-fill',
    day: 3, track: 'private', topicId: IY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.iyelik.ihr'],
    familyId: 'p3-iy-ihrem-zimmer',
    instruction: 'Boşluğu doldur (das Zimmer, nötr, eksiz):',
    prompt: 'Meine Schwester lernt in ___ Zimmer. (odasında ders çalışıyor)',
    answer: 'ihrem',
    pronounce: ['Meine Schwester lernt in ihrem Zimmer.'],
  },
  {
    id: 'p3-iy-ihr-bett-fill',
    day: 3, track: 'private', topicId: IY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.iyelik.ihr'],
    familyId: 'p3-iy-ihr-bett',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Schwester räumt ___ Bett auf. (yatağını topluyor)',
    answer: 'ihr',
    pronounce: ['Meine Schwester räumt ihr Bett auf.'],
  },
  {
    id: 'p3-iy-dativ-cogul-mc',
    day: 3, track: 'private', topicId: IY,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day3.iyelik.dativ-cogul'],
    familyId: 'p3-iy-dativ-cogul',
    instruction: 'Dativ çoğulda iyelik eki nasıl biter?',
    prompt: 'mein → mit ___ Freunden',
    answer: 'meinen',
    options: ['meinen', 'meine', 'mein', 'meiner'],
  },
  {
    id: 'p3-iy-error-dein-bett',
    day: 3, track: 'private', topicId: IY,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.iyelik.ihr'],
    familyId: 'p3-iy-ihr-bett',
    instruction: 'Hata avı — kimin yatağı?',
    prompt: 'Meine Schwester räumt dein Bett auf.',
    answer: 'Meine Schwester räumt ihr Bett auf.',
    explanation: 'Yatak kız kardeşin (3. kişi, kadın) yatağıdır, "dein" (senin) değil "ihr" (onun) kullanılmalı.',
    pronounce: ['Meine Schwester räumt ihr Bett auf.'],
  },

  /* ================================================================
   * Sayılar, Miktarlar ve Çoğullar (9)
   * ================================================================ */
  {
    id: 'p3-mk-flaschen-mc',
    day: 3, track: 'private', topicId: MK,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.miktar.sise'],
    familyId: 'p3-mk-flaschen',
    instruction: '"iki şişe su" nasıl söylenir?',
    prompt: 'iki şişe su',
    answer: 'zwei Flaschen Wasser',
    options: ['zwei Flaschen Wasser', 'zwei Flasche Wasser', 'zwei Flaschen Wassers', 'zwei Flasche Wassers'],
  },
  {
    id: 'p3-mk-flaschen-fill',
    day: 3, track: 'private', topicId: MK,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.miktar.sise'],
    familyId: 'p3-mk-flaschen-fill',
    instruction: 'Boşluğu doldur (Flasche çoğul olur, Wasser tekil kalır):',
    prompt: 'Ich kaufe zwei ___ Wasser. (iki şişe su alıyorum)',
    answer: 'Flaschen',
    pronounce: ['Ich kaufe zwei Flaschen Wasser.'],
  },
  {
    id: 'p3-mk-error-flasche',
    day: 3, track: 'private', topicId: MK,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.miktar.sise'],
    familyId: 'p3-mk-flaschen-fill',
    instruction: 'Hata avı — sayıdan sonra çoğul mu?',
    prompt: 'Ich kaufe zwei Flasche Wasser.',
    answer: 'Ich kaufe zwei Flaschen Wasser.',
    explanation: '"zwei" gibi 1den büyük bir sayıdan sonra kap ismi (Flasche) çoğula döner: Flaschen.',
    pronounce: ['Ich kaufe zwei Flaschen Wasser.'],
  },
  {
    id: 'p3-mk-zimmer-mc',
    day: 3, track: 'private', topicId: MK,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.miktar.oda'],
    familyId: 'p3-mk-zimmer',
    instruction: '"das Zimmer" çoğulda nasıl yazılır?',
    prompt: 'das Zimmer → çoğul',
    answer: 'die Zimmer',
    options: ['die Zimmer', 'die Zimmern', 'die Zimmers', 'das Zimmer'],
  },
  {
    id: 'p3-mk-drei-zimmer-fill',
    day: 3, track: 'private', topicId: MK,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.miktar.oda'],
    familyId: 'p3-mk-drei-zimmer',
    instruction: 'Boşluğu doldur:',
    prompt: 'Unsere Wohnung hat drei ___. (evimizde üç oda var)',
    answer: 'Zimmer',
    pronounce: ['Unsere Wohnung hat drei Zimmer.'],
  },
  {
    id: 'p3-mk-cogul-genel-mc',
    day: 3, track: 'private', topicId: MK,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.cogul.genel'],
    familyId: 'p3-mk-cogul-genel',
    instruction: 'Genel bir ifadede ("hayvanları severim" gibi) çoğul isim nasıl kullanılır?',
    prompt: 'Meine Schwester mag ___. (hayvanları çok seviyor)',
    answer: 'Tiere',
    options: ['Tiere', 'die Tiere', 'ein Tiere', 'einen Tiere'],
  },
  {
    id: 'p3-mk-error-die-tiere',
    day: 3, track: 'private', topicId: MK,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.cogul.genel'],
    familyId: 'p3-mk-cogul-genel',
    instruction: 'Hata avı — genel ifadede artikel gerekli mi?',
    prompt: 'Meine Schwester mag die Tiere.',
    answer: 'Meine Schwester mag Tiere.',
    explanation: 'Belirli hayvanlardan değil, genel olarak hayvanlardan bahsediliyor; genel çoğulda artikel kullanılmaz.',
    pronounce: ['Meine Schwester mag Tiere.'],
  },
  {
    id: 'p3-mk-buecher-mc',
    day: 3, track: 'private', topicId: MK,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.cogul.umlaut'],
    familyId: 'p3-mk-buecher',
    instruction: '"das Buch" çoğulda nasıl olur?',
    prompt: 'das Buch → çoğul',
    answer: 'die Bücher',
    options: ['die Bücher', 'die Buche', 'die Buchs', 'die Buchen'],
  },
  {
    id: 'p3-mk-buecher-fill',
    day: 3, track: 'private', topicId: MK,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.cogul.umlaut'],
    familyId: 'p3-mk-buecher-fill',
    instruction: 'Boşluğu doldur:',
    prompt: 'Auf dem Tisch gibt es ___. (masanın üzerinde kitaplar var — Buch)',
    answer: 'Bücher',
    pronounce: ['Auf dem Tisch gibt es Bücher.'],
  },

  /* ================================================================
   * Zaman İfadeleri (14)
   * ================================================================ */
  {
    id: 'p3-zi-um-uhr-mc',
    day: 3, track: 'private', topicId: ZI,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.zaman.um-uhr'],
    familyId: 'p3-zi-um-uhr',
    instruction: 'Kesin bir saat söylerken hangi edat kullanılır?',
    prompt: 'saat yedide',
    answer: 'um 7 Uhr',
    options: ['um 7 Uhr', 'am 7 Uhr', 'im 7 Uhr', 'in 7 Uhr'],
  },
  {
    id: 'p3-zi-um-8-fill',
    day: 3, track: 'private', topicId: ZI,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.zaman.um-uhr'],
    familyId: 'p3-zi-um-8',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich gehe ___ 8 Uhr zur Schule. (saat sekizde okula gidiyorum)',
    answer: 'um',
    pronounce: ['Ich gehe um 8 Uhr zur Schule.'],
  },
  {
    id: 'p3-zi-beginnt-fill',
    day: 3, track: 'private', topicId: ZI,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.zaman.um-uhr'],
    familyId: 'p3-zi-beginnt',
    instruction: 'Boşluğu doldur (der Unterricht, eril):',
    prompt: '___ Unterricht beginnt um 9 Uhr. (ders saat dokuzda başlıyor)',
    answer: 'Der',
    pronounce: ['Der Unterricht beginnt um 9 Uhr.'],
  },
  {
    id: 'p3-zi-endet-error',
    day: 3, track: 'private', topicId: ZI,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.zaman.um-uhr'],
    familyId: 'p3-zi-endet',
    instruction: 'Hata avı — hangi fiil kendiliğinden bitmeyi anlatır?',
    prompt: 'Die Schule beendet um 3 Uhr.',
    answer: 'Die Schule endet um 3 Uhr.',
    explanation: '"enden" kendiliğinden bitmeyi anlatır (okul kendi kendine biter); "beenden" bir şeyi bitirmeyi anlatır ve nesne ister.',
    pronounce: ['Die Schule endet um 3 Uhr.'],
  },
  {
    id: 'p3-zi-am-morgen-mc',
    day: 3, track: 'private', topicId: ZI,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.zaman.am'],
    familyId: 'p3-zi-am-morgen',
    instruction: '"sabah" hangi kalıpla söylenir?',
    prompt: 'sabah (genel olarak)',
    answer: 'am Morgen',
    options: ['am Morgen', 'im Morgen', 'zum Morgen', 'im Morgens'],
  },
  {
    id: 'p3-zi-am-abend-fill',
    day: 3, track: 'private', topicId: ZI,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.zaman.am'],
    familyId: 'p3-zi-am-abend',
    instruction: 'Boşluğu doldur:',
    prompt: '___ Abend essen wir alle zusammen. (akşam hep birlikte yemek yiyoruz)',
    answer: 'Am',
    pronounce: ['Am Abend essen wir alle zusammen.'],
  },
  {
    id: 'p3-zi-am-wochenende-fill',
    day: 3, track: 'private', topicId: ZI,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.zaman.am'],
    familyId: 'p3-zi-am-wochenende',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich treffe meinen Freund ___ Wochenende. (hafta sonu arkadaşımı görüyorum)',
    answer: 'am',
    pronounce: ['Ich treffe meinen Freund am Wochenende.'],
  },
  {
    id: 'p3-zi-im-winter-mc',
    day: 3, track: 'private', topicId: ZI,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.zaman.im-mevsim'],
    familyId: 'p3-zi-im-winter',
    instruction: '"kışın" hangi kalıpla söylenir?',
    prompt: 'kışın',
    answer: 'im Winter',
    options: ['im Winter', 'am Winter', 'zum Winter', 'in Winter'],
  },
  {
    id: 'p3-zi-im-sommer-fill',
    day: 3, track: 'private', topicId: ZI,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.zaman.im-mevsim'],
    familyId: 'p3-zi-im-sommer',
    instruction: 'Boşluğu doldur:',
    prompt: '___ Sommer gehe ich ans Meer. (yazın denize gidiyorum)',
    answer: 'Im',
    pronounce: ['Im Sommer gehe ich ans Meer.'],
  },
  {
    id: 'p3-zi-dann-mc',
    day: 3, track: 'private', topicId: ZI,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.zaman.dann'],
    familyId: 'p3-zi-dann',
    instruction: '"Dann" ne demektir?',
    prompt: 'Dann',
    answer: 'sonra',
    options: ['sonra', 'şimdi', 'önce', 'her zaman'],
  },
  {
    id: 'p3-zi-dann-order',
    day: 3, track: 'private', topicId: ZI,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.zaman.dann', 'private.day3.dizilisi.zaman-basta'],
    familyId: 'p3-zi-dann-order',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Dann / lese / ich / ein / Buch.',
    answer: 'Dann lese ich ein Buch.',
    words: ['Dann', 'lese', 'ich', 'ein', 'Buch'],
    pronounce: ['Dann lese ich ein Buch.'],
  },
  {
    id: 'p3-zi-morgen-farki-mc',
    day: 3, track: 'private', topicId: ZI,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.zaman.morgen-cift-anlam'],
    familyId: 'p3-zi-morgen-farki',
    instruction: '"morgen" (küçük harf) ile "der Morgen" arasındaki fark nedir?',
    prompt: 'morgen ↔ der Morgen',
    answer: 'morgen = yarın (zarf), der Morgen = sabah (isim)',
    options: [
      'morgen = yarın (zarf), der Morgen = sabah (isim)',
      'ikisi de "sabah" demektir',
      'ikisi de "yarın" demektir',
      'morgen isim, der Morgen zarftır',
    ],
  },
  {
    id: 'p3-zi-morgen-treffe-fill',
    day: 3, track: 'private', topicId: ZI,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.zaman.morgen-cift-anlam'],
    familyId: 'p3-zi-morgen-treffe',
    instruction: 'Boşluğu doldur (yarın, gelecek anlamı için Präsens kullanılır):',
    prompt: '___ treffe ich meine Freunde. (yarın arkadaşlarımla buluşacağım)',
    answer: 'Morgen',
    pronounce: ['Morgen treffe ich meine Freunde.'],
  },

  /* ================================================================
   * Cümle Dizilişi — Verb İkinci Sırada (10)
   * ================================================================ */
  {
    id: 'p3-cd-verb-ikinci-mc',
    day: 3, track: 'private', topicId: CD,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.dizilisi.verb-ikinci'],
    familyId: 'p3-cd-verb-ikinci',
    instruction: 'Almanca ana cümlede fiil kaçıncı sıradadır?',
    prompt: 'Fiil pozisyonu',
    answer: 'her zaman ikinci sırada',
    options: ['her zaman ikinci sırada', 'her zaman ilk sırada', 'her zaman son sırada', 'sırası önemli değil'],
  },
  {
    id: 'p3-cd-zaman-basta-mc',
    day: 3, track: 'private', topicId: CD,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.dizilisi.zaman-basta'],
    familyId: 'p3-cd-zaman-basta',
    instruction: 'Cümle bir zaman ifadesiyle başlarsa özne nereye gider?',
    prompt: 'Am Abend ___ ich nach Hause. (özne nerede?)',
    answer: 'fiilden sonra',
    options: ['fiilden sonra', 'fiilden önce', 'cümlenin en başına', 'cümlenin en sonuna'],
  },
  {
    id: 'p3-cd-heute-order',
    day: 3, track: 'private', topicId: CD,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.dizilisi.zaman-basta'],
    familyId: 'p3-cd-heute-order',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Heute / bin / ich / sehr / glücklich.',
    answer: 'Heute bin ich sehr glücklich.',
    words: ['Heute', 'bin', 'ich', 'sehr', 'glücklich'],
    pronounce: ['Heute bin ich sehr glücklich.'],
  },
  {
    id: 'p3-cd-am-abend-order',
    day: 3, track: 'private', topicId: CD,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.dizilisi.zaman-basta'],
    familyId: 'p3-cd-am-abend-order',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Am / Abend / gehe / ich / nach / Hause.',
    answer: 'Am Abend gehe ich nach Hause.',
    words: ['Am', 'Abend', 'gehe', 'ich', 'nach', 'Hause'],
    pronounce: ['Am Abend gehe ich nach Hause.'],
  },
  {
    id: 'p3-cd-error-heute-ich-bin',
    day: 3, track: 'private', topicId: CD,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.dizilisi.zaman-basta'],
    familyId: 'p3-cd-heute-order',
    instruction: 'Hata avı — fiil hangi sırada olmalı?',
    prompt: 'Heute ich bin sehr glücklich.',
    answer: 'Heute bin ich sehr glücklich.',
    explanation: 'Fiil her zaman ikinci sırada durur; zaman ifadesi (Heute) başa geldiğinde özne (ich) fiilden sonraya kayar.',
    pronounce: ['Heute bin ich sehr glücklich.'],
  },
  {
    id: 'p3-cd-nach-dem-film-builder-tr',
    day: 3, track: 'private', topicId: CD,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.dizilisi.zaman-basta'],
    familyId: 'p3-cd-nach-dem-film',
    instruction: 'Cümleyi kur:',
    prompt: 'Filmden sonra eve gidiyorum.',
    answer: 'Nach dem Film gehe ich nach Hause.',
    words: ['Nach', 'dem', 'Film', 'gehe', 'ich', 'nach', 'Hause'],
    pronounce: ['Nach dem Film gehe ich nach Hause.'],
  },
  {
    id: 'p3-cd-moechten-infinitiv-mc',
    day: 3, track: 'private', topicId: CD,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.moechten-infinitiv'],
    familyId: 'p3-cd-moechten-infinitiv',
    instruction: '"Ich möchte ein Brot kaufen." cümlesinde "kaufen" nerede durur?',
    prompt: 'möchte + ... + fiil (mastar)',
    answer: 'cümlenin en sonunda',
    options: ['cümlenin en sonunda', 'möchte\'den hemen önce', 'cümlenin başında', 'özneden hemen sonra'],
  },
  {
    id: 'p3-cd-moechten-order',
    day: 3, track: 'private', topicId: CD,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.moechten-infinitiv'],
    familyId: 'p3-cd-moechten-order',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / möchte / ein / Brot / kaufen.',
    answer: 'Ich möchte ein Brot kaufen.',
    words: ['Ich', 'möchte', 'ein', 'Brot', 'kaufen'],
    pronounce: ['Ich möchte ein Brot kaufen.'],
  },
  {
    id: 'p3-cd-free-nach-dem-film-tr',
    day: 3, track: 'private', topicId: CD,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.dizilisi.zaman-basta'],
    familyId: 'p3-cd-nach-dem-film',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Filmden sonra eve gidiyorum. → ______',
    answer: 'Nach dem Film gehe ich nach Hause.',
    pronounce: ['Nach dem Film gehe ich nach Hause.'],
  },
  {
    id: 'p3-cd-dictation-am-abend',
    day: 3, track: 'private', topicId: CD,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.dizilisi.zaman-basta'],
    familyId: 'p3-cd-am-abend-order',
    instruction: 'Cümleyi duydun — aynen yaz:',
    audioText: 'Am Abend gehe ich nach Hause.',
    answer: 'Am Abend gehe ich nach Hause.',
    audio: { prompt: { text: 'Am Abend gehe ich nach Hause.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Günlük Hayat, Hava, Hayvanlar ve Alışveriş (24)
   * ================================================================ */
  {
    id: 'p3-gh-wetter-schoen-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.hava.ifadeler'],
    familyId: 'p3-gh-wetter-schoen',
    instruction: 'Boşluğu doldur:',
    prompt: 'Das Wetter ist heute sehr ___. (bugün hava çok güzel)',
    answer: 'schön',
    pronounce: ['Das Wetter ist heute sehr schön.'],
  },
  {
    id: 'p3-gh-wetter-warm-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.hava.ifadeler'],
    familyId: 'p3-gh-wetter-warm',
    instruction: 'Boşluğu doldur:',
    prompt: 'Das Wetter ist ein bisschen ___. (hava biraz sıcak)',
    answer: 'warm',
    pronounce: ['Das Wetter ist ein bisschen warm.'],
  },
  {
    id: 'p3-gh-wetter-kalt-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.hava.ifadeler'],
    familyId: 'p3-gh-wetter-kalt',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Im Winter ist das Wetter kalt.',
    answer: 'Kışın hava soğuk oluyor.',
    options: ['Kışın hava soğuk oluyor.', 'Yazın hava sıcak oluyor.', 'Bugün hava güzel.', 'Hava biraz sıcak.'],
    pronounce: ['Im Winter ist das Wetter kalt.'],
  },
  {
    id: 'p3-gh-katze-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.hayvanlar.kelime'],
    familyId: 'p3-gh-katze',
    instruction: '"die Katze" ne demektir?',
    prompt: 'die Katze',
    answer: 'kedi',
    options: ['kedi', 'köpek', 'hayvan', 'çiçek'],
    pronounce: ['die Katze'],
  },
  {
    id: 'p3-gh-katze-suess-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.hayvanlar.kelime'],
    familyId: 'p3-gh-katze-suess',
    instruction: 'Boşluğu doldur (doğru yazım: ß):',
    prompt: 'Meine Katze ist sehr ___. (kedim çok tatlı)',
    answer: 'süß',
    pronounce: ['Meine Katze ist sehr süß.'],
  },
  {
    id: 'p3-gh-hund-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.hayvanlar.kelime'],
    familyId: 'p3-gh-hund',
    instruction: 'Boşluğu doldur:',
    prompt: 'Mein ___ spielt im Garten. (köpeğim bahçede oynuyor)',
    answer: 'Hund',
    pronounce: ['Mein Hund spielt im Garten.'],
  },
  {
    id: 'p3-gh-lieblingstier-error',
    day: 3, track: 'private', topicId: GH,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.hayvanlar.kelime'],
    familyId: 'p3-gh-lieblingstier',
    instruction: 'Hata avı — tekil mi çoğul mu, artikel var mı?',
    prompt: 'Mein Lieblingstiere ist Katze.',
    answer: 'Mein Lieblingstier ist die Katze.',
    explanation: '"en sevilen hayvan" tekildir (Lieblingstier, Lieblingstiere değil) ve isimden sonra artikel gerekir (die Katze).',
    pronounce: ['Mein Lieblingstier ist die Katze.'],
  },
  {
    id: 'p3-gh-matching-hayvanlar',
    day: 3, track: 'private', topicId: GH,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.hayvanlar.kelime'],
    familyId: 'p3-gh-hayvan-match',
    instruction: 'Hayvan kelimelerini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'die Katze', right: 'kedi' },
      { left: 'der Hund', right: 'köpek' },
      { left: 'das Tier', right: 'hayvan' },
      { left: 'der Garten', right: 'bahçe' },
    ],
    pronounce: ['die Katze', 'der Hund', 'das Tier', 'der Garten'],
  },
  {
    id: 'p3-gh-fussball-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.hobiler.kelime'],
    familyId: 'p3-gh-fussball',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Ich spiele gern Fußball.',
    answer: 'Ben futbol oynamayı seviyorum.',
    options: ['Ben futbol oynamayı seviyorum.', 'Ben yüzmeyi seviyorum.', 'Ben kitap okumayı severim.', 'Ben bisiklete binerim.'],
    pronounce: ['Ich spiele gern Fußball.'],
  },
  {
    id: 'p3-gh-fahrrad-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.hobiler.kelime'],
    familyId: 'p3-gh-fahrrad',
    instruction: 'Boşluğu doldur (fahren: sie fährt):',
    prompt: 'Meine Schwester ___ Fahrrad. (bisiklete biniyor)',
    answer: 'fährt',
    pronounce: ['Meine Schwester fährt Fahrrad.'],
  },
  {
    id: 'p3-gh-fotos-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.hobiler.kelime'],
    familyId: 'p3-gh-fotos',
    instruction: 'Boşluğu doldur (machen ile):',
    prompt: 'Mein Freund macht ___. (fotoğraf çekiyor)',
    answer: 'Fotos',
    pronounce: ['Mein Freund macht Fotos.'],
  },
  {
    id: 'p3-gh-lesen-buecher-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.hobiler.kelime'],
    familyId: 'p3-gh-lesen',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Ich lese gern Bücher.',
    answer: 'Ben kitap okumayı seviyorum.',
    options: ['Ben kitap okumayı seviyorum.', 'Ben bir kitap alıyorum.', 'Ben gazete okuyorum.', 'Ben müzik dinliyorum.'],
    pronounce: ['Ich lese gern Bücher.'],
  },
  {
    id: 'p3-gh-kaufen-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.alisveris.kelime'],
    familyId: 'p3-gh-kaufen',
    instruction: '"kaufen" ne demektir?',
    prompt: 'kaufen',
    answer: 'satın almak',
    options: ['satın almak', 'satmak', 'giymek', 'temizlemek'],
    pronounce: ['kaufen'],
  },
  {
    id: 'p3-gh-hose-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.alisveris.kelime'],
    familyId: 'p3-gh-hose',
    instruction: 'Boşluğu doldur (die Hose, dişil):',
    prompt: '___ Hose ist ein bisschen teuer. (bu pantolon biraz pahalı)',
    answer: 'Die',
    pronounce: ['Die Hose ist ein bisschen teuer.'],
  },
  {
    id: 'p3-gh-error-das-hose',
    day: 3, track: 'private', topicId: GH,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.alisveris.kelime'],
    familyId: 'p3-gh-hose',
    instruction: 'Hata avı — die Hose hangi cinsiyettir?',
    prompt: 'Das hose ist ein Bisschen teuer.',
    answer: 'Die Hose ist ein bisschen teuer.',
    explanation: '"die Hose" dişildir (das değil); isimler her zaman büyük harfle, "bisschen" ise küçük harfle yazılır.',
    pronounce: ['Die Hose ist ein bisschen teuer.'],
  },
  {
    id: 'p3-gh-einkaufszentrum-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.alisveris.kelime'],
    familyId: 'p3-gh-einkaufszentrum',
    instruction: 'Boşluğu doldur:',
    prompt: 'Dann gehen wir ___ Einkaufszentrum. (sonra alışverişe gidiyoruz)',
    answer: 'ins',
    pronounce: ['Dann gehen wir ins Einkaufszentrum.'],
  },
  {
    id: 'p3-gh-wohnung-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.ev-kelime'],
    familyId: 'p3-gh-wohnung',
    instruction: '"die Wohnung" ne demektir?',
    prompt: 'die Wohnung',
    answer: 'ev / daire',
    options: ['ev / daire', 'oda', 'bahçe', 'balkon'],
    pronounce: ['die Wohnung'],
  },
  {
    id: 'p3-gh-kueche-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.ev-kelime'],
    familyId: 'p3-gh-kueche',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Mutter kocht in der ___. (mutfakta yemek yapıyor)',
    answer: 'Küche',
    pronounce: ['Meine Mutter kocht in der Küche.'],
  },
  {
    id: 'p3-gh-wohnzimmer-matching',
    day: 3, track: 'private', topicId: GH,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.ev-kelime'],
    familyId: 'p3-gh-ev-match',
    instruction: 'Ev kelimelerini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'die Wohnung', right: 'ev / daire' },
      { left: 'das Zimmer', right: 'oda' },
      { left: 'der Balkon', right: 'balkon' },
      { left: 'das Wohnzimmer', right: 'salon' },
    ],
    pronounce: ['die Wohnung', 'das Zimmer', 'der Balkon', 'das Wohnzimmer'],
  },
  {
    id: 'p3-gh-fruehstuecken-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-fruehstuecken',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich ___ am Morgen. (sabah kahvaltı yapıyorum)',
    answer: 'frühstücke',
    pronounce: ['Ich frühstücke am Morgen.'],
  },
  {
    id: 'p3-gh-putze-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-putze',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich ___ mein Zimmer. (odamı temizliyorum)',
    answer: 'putze',
    pronounce: ['Ich putze mein Zimmer.'],
  },
  {
    id: 'p3-gh-giesst-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-giesst',
    instruction: 'Boşluğu doldur (gießen: sie gießt):',
    prompt: 'Meine Mutter ___ die Blumen. (çiçekleri suluyor)',
    answer: 'gießt',
    pronounce: ['Meine Mutter gießt die Blumen.'],
  },
  {
    id: 'p3-gh-hoert-wb-tr-de',
    day: 3, track: 'private', topicId: GH,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-hoert',
    instruction: 'Türkçeden Almancaya kur — Annem müzik dinliyor.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Annem müzik dinliyor.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Meine' }, { id: 't2', text: 'Mutter' }, { id: 't3', text: 'hört' }, { id: 't4', text: 'Musik.' },
        { id: 't5', text: 'Vater' },
      ],
      acceptedSequences: [['Meine', 'Mutter', 'hört', 'Musik.']],
    },
    answer: 'Meine Mutter hört Musik.',
    pronounce: ['Meine Mutter hört Musik.'],
  },
  {
    id: 'p3-gh-es-geht-mir-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.es-geht-mir'],
    familyId: 'p3-gh-es-geht-mir',
    instruction: '"Es geht mir gut" ne demektir?',
    prompt: 'Es geht mir gut',
    answer: 'iyiyim',
    options: ['iyiyim', 'kötüyüm', 'yorgunum', 'mutluyum'],
    pronounce: ['Es geht mir gut'],
  },
  {
    id: 'p3-gh-free-mude-tr',
    day: 3, track: 'private', topicId: GH,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.es-geht-mir'],
    familyId: 'p3-gh-mude',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Biraz yorgunum ama iyiyim. → ______',
    answer: 'Ich bin ein bisschen müde, aber es geht mir gut.',
    pronounce: ['Ich bin ein bisschen müde, aber es geht mir gut.'],
  },
  {
    id: 'p3-gh-spoken-tag',
    day: 3, track: 'private', topicId: GH,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day3.gunluk-rutin', 'private.day3.ayrilabilen.kural'],
    familyId: 'p3-gh-spoken-tag',
    instruction: 'Sesli görev: bir gününü anlat.',
    requirements: ['Ich stehe ... auf.', 'Ich frühstücke ...', 'Am Abend ...'],
    sampleAnswer: 'Ich stehe um 7 Uhr auf. Ich frühstücke am Morgen. Am Abend gehe ich nach Hause.',
    pronounce: ['Ich stehe um 7 Uhr auf.', 'Ich frühstücke am Morgen.', 'Am Abend gehe ich nach Hause.'],
  },
  {
    id: 'p3-gh-spoken-hobi',
    day: 3, track: 'private', topicId: GH,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day3.hobiler.kelime', 'private.day3.gern.kullanim'],
    familyId: 'p3-gh-spoken-hobi',
    instruction: 'Sesli görev: sevdiğin bir hobiyi anlat.',
    requirements: ['Ich ... gern ...', 'Mein Lieblingstier ist ...'],
    sampleAnswer: 'Ich spiele gern Fußball. Mein Lieblingstier ist die Katze.',
    pronounce: ['Ich spiele gern Fußball.', 'Mein Lieblingstier ist die Katze.'],
  },
  {
    id: 'p3-gh-dictation-mutter',
    day: 3, track: 'private', topicId: GH,
    type: 'dictation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-giesst',
    instruction: 'Annemle ilgili cümleyi duydun — aynen yaz:',
    audioText: 'Meine Mutter gießt die Blumen.',
    answer: 'Meine Mutter gießt die Blumen.',
    audio: { prompt: { text: 'Meine Mutter gießt die Blumen.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p3-gh-listen-katze',
    day: 3, track: 'private', topicId: GH,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.hayvanlar.kelime'],
    familyId: 'p3-gh-katze',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich habe eine Katze.',
    audioText: 'Ich habe eine Katze.',
    answer: 'Ich habe eine Katze.',
    options: [
      'Ich habe eine Katze.',
      'Ich habe einen Hund.',
      'Ich habe ein Tier.',
      'Ich habe eine Tasche.',
    ],
    audio: { prompt: { text: 'Ich habe eine Katze.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * 80 cümlenin tam kapsamı için ek alıştırmalar (19)
   * ================================================================ */
  {
    id: 'p3-gh-fruehstuck-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.gunluk-rutin', 'private.day3.kontraksiyon.zum'],
    familyId: 'p3-gh-fruehstuck',
    instruction: 'Boşluğu doldur:',
    prompt: '___ Frühstück esse ich Brot. (kahvaltıda ekmek yiyorum)',
    answer: 'Zum',
    pronounce: ['Zum Frühstück esse ich Brot.'],
  },
  {
    id: 'p3-gh-mutter-kaffee-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-mutter-kaffee',
    instruction: 'Boşluğu doldur (trinken):',
    prompt: 'Meine Mutter ___ Kaffee. (annem kahve içiyor)',
    answer: 'trinkt',
    pronounce: ['Meine Mutter trinkt Kaffee.'],
  },
  {
    id: 'p3-yy-vater-arbeit-mc',
    day: 3, track: 'private', topicId: YY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.kontraksiyon.zur'],
    familyId: 'p3-yy-vater-arbeit',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Mein Vater geht zur Arbeit.',
    answer: 'Babam işe gidiyor.',
    options: ['Babam işe gidiyor.', 'Babam evden geliyor.', 'Babam okula gidiyor.', 'Babam eve gidiyor.'],
    pronounce: ['Mein Vater geht zur Arbeit.'],
  },
  {
    id: 'p3-gh-lerne-deutsch-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-lerne-deutsch',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Ich lerne Deutsch.',
    answer: 'Ben Almanca öğreniyorum.',
    options: ['Ben Almanca öğreniyorum.', 'Ben Almanca konuşuyorum.', 'Ben Almanca dersim var.', 'Ben Almanca biliyorum.'],
    pronounce: ['Ich lerne Deutsch.'],
  },
  {
    id: 'p3-gh-deutschunterricht-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-deutschunterricht',
    instruction: 'Boşluğu doldur (haben):',
    prompt: 'Ich ___ heute Deutschunterricht. (bugün Almanca dersim var)',
    answer: 'habe',
    pronounce: ['Ich habe heute Deutschunterricht.'],
  },
  {
    id: 'p3-gh-wohne-istanbul-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.ev-kelime'],
    familyId: 'p3-gh-wohne-istanbul',
    instruction: 'Boşluğu doldur (wohnen — 1. Günden tekrar):',
    prompt: 'Ich ___ in Istanbul. (İstanbul\'da yaşıyorum)',
    answer: 'wohne',
    pronounce: ['Ich wohne in Istanbul.'],
  },
  {
    id: 'p3-gh-vater-fernsehen-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.ev-kelime'],
    familyId: 'p3-gh-vater-fernsehen',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Mein Vater schaut im Wohnzimmer Fernsehen.',
    answer: 'Babam salonda televizyon izliyor.',
    options: [
      'Babam salonda televizyon izliyor.',
      'Babam mutfakta yemek yapıyor.',
      'Babam bahçede oturuyor.',
      'Babam odasında ders çalışıyor.',
    ],
    pronounce: ['Mein Vater schaut im Wohnzimmer Fernsehen.'],
  },
  {
    id: 'p3-mg-bananen-fill',
    day: 3, track: 'private', topicId: MG,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.mogen.cekim'],
    familyId: 'p3-mg-bananen',
    instruction: 'Boşluğu doldur (mögen):',
    prompt: 'Meine Schwester ___ Bananen. (kardeşim muz seviyor)',
    answer: 'mag',
    pronounce: ['Meine Schwester mag Bananen.'],
  },
  {
    id: 'p3-iy-meine-tasche-fill',
    day: 3, track: 'private', topicId: IY,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.iyelik.unser'],
    familyId: 'p3-iy-meine-tasche',
    instruction: 'Boşluğu doldur (die Tasche, dişil):',
    prompt: 'Das ist ___ Tasche. (bu çanta benim)',
    answer: 'meine',
    pronounce: ['Das ist meine Tasche.'],
  },
  {
    id: 'p3-zi-zu-mittag-fill',
    day: 3, track: 'private', topicId: ZI,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.zaman.um-uhr'],
    familyId: 'p3-zi-zu-mittag',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich esse ___ 1 Uhr zu Mittag. (öğle yemeğini saat birde yiyorum)',
    answer: 'um',
    pronounce: ['Ich esse um 1 Uhr zu Mittag.'],
  },
  {
    id: 'p3-zi-essen-8-fill',
    day: 3, track: 'private', topicId: ZI,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.zaman.um-uhr'],
    familyId: 'p3-zi-essen-8',
    instruction: 'Boşluğu doldur:',
    prompt: 'Wir essen ___ 8 Uhr. (saat sekizde yemek yiyoruz)',
    answer: 'um',
    pronounce: ['Wir essen um 8 Uhr.'],
  },
  {
    id: 'p3-yy-ins-bett-fill',
    day: 3, track: 'private', topicId: YY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.kontraksiyon.ins'],
    familyId: 'p3-yy-ins-bett',
    instruction: 'Boşluğu doldur (das Bett, nötr):',
    prompt: 'Ich gehe um 11 Uhr ___ Bett. (saat on birde yatıyorum)',
    answer: 'ins',
    pronounce: ['Ich gehe um 11 Uhr ins Bett.'],
  },
  {
    id: 'p3-gh-zusammen-kaffee-mc',
    day: 3, track: 'private', topicId: GH,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-zusammen-kaffee',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Wir trinken zusammen Kaffee.',
    answer: 'Birlikte kahve içiyoruz.',
    options: ['Birlikte kahve içiyoruz.', 'Birlikte yemek yiyoruz.', 'Ayrı ayrı kahve içiyoruz.', 'Birlikte su içiyoruz.'],
    pronounce: ['Wir trinken zusammen Kaffee.'],
  },
  {
    id: 'p3-gh-freund-kauft-buch-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.alisveris.kelime'],
    familyId: 'p3-gh-freund-kauft-buch',
    instruction: 'Boşluğu doldur (kaufen):',
    prompt: 'Mein Freund ___ ein Buch. (arkadaşım bir kitap alıyor)',
    answer: 'kauft',
    pronounce: ['Mein Freund kauft ein Buch.'],
  },
  {
    id: 'p3-sf-film-gut-fill',
    day: 3, track: 'private', topicId: SF,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day3.sifat.yuklem'],
    familyId: 'p3-sf-film-gut',
    instruction: 'Boşluğu doldur (ek yok):',
    prompt: 'Der Film ist sehr ___. (film çok güzel)',
    answer: 'gut',
    pronounce: ['Der Film ist sehr gut.'],
  },
  {
    id: 'p3-zi-dann-schlafe-mc',
    day: 3, track: 'private', topicId: ZI,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day3.zaman.dann'],
    familyId: 'p3-zi-dann-schlafe',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Dann schlafe ich.',
    answer: 'Sonra uyuyorum.',
    options: ['Sonra uyuyorum.', 'Şimdi uyuyorum.', 'Önce uyudum.', 'Hiç uyumuyorum.'],
    pronounce: ['Dann schlafe ich.'],
  },
  {
    id: 'p3-gh-vater-zeitung-fill',
    day: 3, track: 'private', topicId: GH,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day3.gunluk-rutin'],
    familyId: 'p3-gh-vater-zeitung',
    instruction: 'Boşluğu doldur (lesen: er liest):',
    prompt: 'Mein Vater ___ die Zeitung. (babam gazete okuyor)',
    answer: 'liest',
    pronounce: ['Mein Vater liest die Zeitung.'],
  },
  {
    id: 'p3-sf-error-heute-glucklich',
    day: 3, track: 'private', topicId: SF,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day3.sifat.yuklem'],
    familyId: 'p3-sf-heute-glucklich',
    instruction: 'Hata avı — sıfat büyük harfle mi yazılır?',
    prompt: 'Ich bin heute sehr Glücklich.',
    answer: 'Ich bin heute sehr glücklich.',
    explanation: 'Sıfatlar isim değildir; sein\'den sonra gelse bile küçük harfle yazılır.',
    pronounce: ['Ich bin heute sehr glücklich.'],
  },
  {
    id: 'p3-zi-am-abend-zusammen-order',
    day: 3, track: 'private', topicId: ZI,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day3.zaman.am', 'private.day3.dizilisi.zaman-basta'],
    familyId: 'p3-zi-am-abend-zusammen',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Am / Abend / essen / wir / zusammen.',
    answer: 'Am Abend essen wir zusammen.',
    words: ['Am', 'Abend', 'essen', 'wir', 'zusammen'],
    pronounce: ['Am Abend essen wir zusammen.'],
  },
];
