/**
 * Özel Ders — 1. Gün — yazılmış alıştırma havuzu.
 *
 * Kaynak: el yazısı özel ders notları (6 sayfa). Tüm kavramlar concepts.ts içindeki
 * private.day1.* kavramlarına bağlıdır; özet kapsamı Özel Ders Özet.md üzerinden doğrulanır.
 *
 * Tasarım: 65+ özgün alıştırmada düzenli tekrar yok; aile aralığı, zorluk karması
 * ve üretim ağırlığı korunur. Her önemli kalıp en az iki farklı etkileşim türüyle sorulur.
 */

import type { AuthoredExercise } from '../types.ts';

const VOR = 'private.day1.vorstellung';
const ALT = 'private.day1.alter-herkunft-wohnort';
const BER = 'private.day1.beruf';
const KON = 'private.day1.kontakt-formular';
const FII = 'private.day1.fiil-cekimi';
const DIL = 'private.day1.diller-selamlasma';

export const PRIVATE_DAY1_EXERCISES: AuthoredExercise[] = [
  /* ================================================================
   * Kolay — tanıma (18)
   * ================================================================ */

  {
    id: 'p1-vor-wie-heisst-mc',
    day: 1, track: 'private', topicId: VOR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Doğru soruyu seç — samimi hitap:',
    prompt: 'Arkadaşına adını soruyorsun.',
    answer: 'Wie heißt du?',
    options: ['Wie heißt du?', 'Wie heißen Sie?', 'Wer bist du?', 'Wo wohnst du?'],
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'p1-vor-wie-heissen-sie-mc',
    day: 1, track: 'private', topicId: VOR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Doğru soruyu seç — resmî hitap:',
    prompt: 'Öğretmenine adını soruyorsun.',
    answer: 'Wie heißen Sie?',
    options: ['Wie heißt du?', 'Wie heißen Sie?', 'Wie ist dein Name?', 'Wer bist du?'],
    pronounce: ['Wie heißen Sie?'],
  },
  {
    id: 'p1-vor-wer-bist-du-mc',
    day: 1, track: 'private', topicId: VOR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.vorstellung.wer-bist-du'],
    familyId: 'p1-vor-wer',
    instruction: 'Bu sorunun Türkçesi nedir?',
    prompt: 'Wer bist du?',
    answer: 'Sen kimsin? / Adın ne?',
    options: ['Sen kimsin? / Adın ne?', 'Nerede yaşıyorsun?', 'Nerelisin?', 'Kaç yaşındasın?'],
    pronounce: ['Wer bist du?'],
  },
  {
    id: 'p1-vor-freut-mich-mc',
    day: 1, track: 'private', topicId: VOR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.vorstellung.freut-mich'],
    familyId: 'p1-vor-freut',
    instruction: 'Tanışırken söylenir:',
    prompt: 'Freut mich!',
    answer: 'Memnun oldum!',
    options: ['Memnun oldum!', 'Teşekkürler!', 'Pardon!', 'Güle güle!'],
    pronounce: ['Freut mich!'],
  },
  {
    id: 'p1-alt-wie-alt-mc',
    day: 1, track: 'private', topicId: ALT,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.alter.wie-alt'],
    familyId: 'p1-alt-wie-alt',
    instruction: 'Doğru yaş sorusunu seç (samimi):',
    prompt: 'Sen kaç yaşındasın?',
    answer: 'Wie alt bist du?',
    options: ['Wie alt bist du?', 'Wie alt sind Sie?', 'Wo wohnst du?', 'Woher kommst du?'],
    pronounce: ['Wie alt bist du?'],
  },
  {
    id: 'p1-alt-woher-mc',
    day: 1, track: 'private', topicId: ALT,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.herkunft.woher'],
    familyId: 'p1-alt-woher',
    instruction: 'Bu soru ne sorar?',
    prompt: 'Woher kommst du?',
    answer: 'Nerelisin? / Nereden geliyorsun?',
    options: ['Nerelisin? / Nereden geliyorsun?', 'Nerede yaşıyorsun?', 'Ne iş yapıyorsun?', 'Kaç yaşındasın?'],
    pronounce: ['Woher kommst du?'],
  },
  {
    id: 'p1-alt-wo-wohnst-mc',
    day: 1, track: 'private', topicId: ALT,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.wohnort.wo-wohnst'],
    familyId: 'p1-alt-wo-wohnst',
    instruction: 'Doğru soruyu seç:',
    prompt: 'Nerede yaşıyorsun? (samimi)',
    answer: 'Wo wohnst du?',
    options: ['Wo wohnst du?', 'Wo wohnen Sie?', 'Woher kommst du?', 'Wie heißt du?'],
    pronounce: ['Wo wohnst du?'],
  },
  {
    id: 'p1-ber-frage-mc',
    day: 1, track: 'private', topicId: BER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.beruf.frage'],
    familyId: 'p1-ber-frage',
    instruction: 'Meslek sormanın yaygın yolu:',
    prompt: 'Was machst du beruflich?',
    answer: 'Mesleğin ne?',
    options: ['Mesleğin ne?', 'Nerede yaşıyorsun?', 'Kaç yaşındasın?', 'Adın ne?'],
    pronounce: ['Was machst du beruflich?'],
  },
  {
    id: 'p1-kontakt-email-mc',
    day: 1, track: 'private', topicId: KON,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.kontakt.email'],
    familyId: 'p1-kontakt-email',
    instruction: 'E-posta sorusu (samimi):',
    prompt: 'Wie ist deine E-Mail-Adresse?',
    answer: 'Mailin ne?',
    options: ['Mailin ne?', 'Telefonun ne?', 'Adın ne?', 'Nerede yaşıyorsun?'],
    pronounce: ['Wie ist deine E-Mail-Adresse?'],
  },
  {
    id: 'p1-kontakt-punkt-mc',
    day: 1, track: 'private', topicId: KON,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.kontakt.punkt'],
    familyId: 'p1-kontakt-punkt',
    instruction: 'E-postadaki nokta nasıl okunur?',
    prompt: 'mustafa@gmail.com',
    answer: 'Punkt',
    options: ['Punkt', 'Komma', 'Strich', 'At'],
    pronounce: ['Punkt'],
  },
  {
    id: 'p1-kontakt-telefon-mc',
    day: 1, track: 'private', topicId: KON,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.kontakt.telefon'],
    familyId: 'p1-kontakt-telefon',
    instruction: 'Telefon sorusu (samimi):',
    prompt: 'Wie ist deine Telefonnummer?',
    answer: 'Telefonun ne?',
    options: ['Telefonun ne?', 'Mailin ne?', 'Adın ne?', 'Mesleğin ne?'],
    pronounce: ['Wie ist deine Telefonnummer?'],
  },
  {
    id: 'p1-form-vorname-mc',
    day: 1, track: 'private', topicId: KON,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.formular.felder'],
    familyId: 'p1-form-vorname',
    instruction: 'Form alanı nedir?',
    prompt: 'Vorname',
    answer: 'ad',
    options: ['ad', 'soyad', 'adres', 'meslek'],
    pronounce: ['Vorname'],
  },
  {
    id: 'p1-form-nachname-mc',
    day: 1, track: 'private', topicId: KON,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.formular.felder'],
    familyId: 'p1-form-nachname',
    instruction: 'Form alanı nedir?',
    prompt: 'Familienname / Nachname',
    answer: 'soyad',
    options: ['soyad', 'ad', 'meslek', 'ikamet yeri'],
    pronounce: ['Familienname'],
  },
  {
    id: 'p1-form-familienstand-mc',
    day: 1, track: 'private', topicId: KON,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.formular.familienstand'],
    familyId: 'p1-form-stand',
    instruction: 'Form alanı nedir?',
    prompt: 'Familienstand',
    answer: 'medeni hâl',
    options: ['medeni hâl', 'meslek', 'çocuklar', 'memleket'],
    pronounce: ['Familienstand'],
  },
  {
    id: 'p1-verben-sein-ich-bin-mc',
    day: 1, track: 'private', topicId: FII,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.verben.sein'],
    familyId: 'p1-verb-sein',
    instruction: 'Doğru çekimi seç:',
    prompt: 'ich → sein',
    answer: 'bin',
    options: ['bin', 'bist', 'ist', 'sind'],
    pronounce: ['ich bin'],
  },
  {
    id: 'p1-verben-heissen-ich-mc',
    day: 1, track: 'private', topicId: FII,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.verben.heissen'],
    familyId: 'p1-verb-heissen',
    instruction: 'Doğru çekimi seç:',
    prompt: 'ich → heißen',
    answer: 'heiße',
    options: ['heiße', 'heißt', 'heißen', 'heißst'],
    pronounce: ['ich heiße'],
  },
  {
    id: 'p1-diller-welche-mc',
    day: 1, track: 'private', topicId: DIL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.sprachen.welche'],
    familyId: 'p1-sprachen-welche',
    instruction: 'Soru ne anlama gelir?',
    prompt: 'Welche Sprachen sprichst du?',
    answer: 'Hangi dilleri konuşuyorsun?',
    options: ['Hangi dilleri konuşuyorsun?', 'Nerelisin?', 'Kaç yaşındasın?', 'Ne iş yapıyorsun?'],
    pronounce: ['Welche Sprachen sprichst du?'],
  },
  {
    id: 'p1-selam-hallo-mc',
    day: 1, track: 'private', topicId: DIL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.selamlasma.hallo'],
    familyId: 'p1-selam-hallo',
    instruction: 'Günün her saatinde kullanabileceğin selam:',
    prompt: 'Hallo! / Hi!',
    answer: 'Merhaba! / Selam!',
    options: ['Merhaba! / Selam!', 'Günaydın!', 'İyi akşamlar!', 'İyi geceler!'],
    pronounce: ['Hallo!'],
  },

  /* ================================================================
   * Orta — hatırlama / uygulama (32)
   * ================================================================ */

  {
    id: 'p1-vor-heisse-fill',
    day: 1, track: 'private', topicId: VOR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Boşluğu doldur:',
    prompt: 'Wie _____ du? (heißen)',
    answer: 'heißt',
    validation: { keyboardTolerance: true },
    hint: 'samimi soru, du ile.',
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'p1-vor-heissen-sie-fill',
    day: 1, track: 'private', topicId: VOR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Resmî soruyu tamamla — fiili doğru çek:',
    prompt: 'Wie _____ Sie?',
    answer: 'heißen',
    validation: { keyboardTolerance: true },
    hint: 'Sie/sie çekimi düzenli fiillerde her zaman mastarla aynıdır.',
    pronounce: ['Wie heißen Sie?'],
  },
  {
    id: 'p1-vor-name-fill',
    day: 1, track: 'private', topicId: VOR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.vorstellung.wie-ist-dein-name'],
    familyId: 'p1-vor-name',
    instruction: 'Boşluğu doldur — samimi iyelik zamiri:',
    prompt: 'Wie ist _____ Name?',
    answer: 'dein',
    hint: 'senin (samimi hitap)',
    pronounce: ['Wie ist dein Name?'],
  },
  {
    id: 'p1-vor-wer-bist-fill',
    day: 1, track: 'private', topicId: VOR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.vorstellung.wer-bist-du'],
    familyId: 'p1-vor-wer',
    instruction: 'Boşluğu doldur:',
    prompt: 'Wer _____ du? (sein)',
    answer: 'bist',
    pronounce: ['Wer bist du?'],
  },
  {
    id: 'p1-vor-ich-heisse-fill',
    day: 1, track: 'private', topicId: VOR,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.verben.heissen', 'private.day1.vorstellung.wie-heisst-du'],
    familyId: 'p1-verb-heissen',
    instruction: 'Kendini tanıt:',
    prompt: 'Ich _____ Mustafa. (heißen)',
    answer: 'heiße',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich heiße Mustafa.'],
  },
  {
    id: 'p1-alt-bin-jahre-fill',
    day: 1, track: 'private', topicId: ALT,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.alter.wie-alt', 'private.day1.verben.sein'],
    familyId: 'p1-alt-wie-alt',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich _____ achtzehn Jahre alt. (sein)',
    answer: 'bin',
    pronounce: ['Ich bin achtzehn Jahre alt.'],
  },
  {
    id: 'p1-alt-woher-kommst-fill',
    day: 1, track: 'private', topicId: ALT,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.herkunft.woher'],
    familyId: 'p1-alt-woher',
    instruction: 'Soru kalıbını tamamla:',
    prompt: 'Woher _____ du? (kommen)',
    answer: 'kommst',
    pronounce: ['Woher kommst du?'],
  },
  {
    id: 'p1-alt-wo-wohnst-fill',
    day: 1, track: 'private', topicId: ALT,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.wohnort.wo-wohnst'],
    familyId: 'p1-alt-wo-wohnst',
    instruction: 'Soru kalıbını tamamla:',
    prompt: 'Wo _____ du? (wohnen)',
    answer: 'wohnst',
    pronounce: ['Wo wohnst du?'],
  },
  {
    id: 'p1-alt-komme-aus-fill',
    day: 1, track: 'private', topicId: ALT,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.herkunft.aus', 'private.day1.verben.kommen'],
    familyId: 'p1-alt-aus',
    instruction: 'Cevabı tamamla:',
    prompt: 'Ich _____ aus Sakarya. (kommen)',
    answer: 'komme',
    pronounce: ['Ich komme aus Sakarya.'],
  },
  {
    id: 'p1-alt-wohne-in-fill',
    day: 1, track: 'private', topicId: ALT,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.wohnort.in'],
    familyId: 'p1-alt-in',
    instruction: 'Cevabı tamamla:',
    prompt: 'Ich _____ in Sakarya. (wohnen)',
    answer: 'wohne',
    pronounce: ['Ich wohne in Sakarya.'],
  },
  {
    id: 'p1-ber-was-bist-fill',
    day: 1, track: 'private', topicId: BER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.beruf.frage'],
    familyId: 'p1-ber-frage',
    instruction: 'Meslek sorusunu tamamla:',
    prompt: 'Was _____ du von Beruf? (sein)',
    answer: 'bist',
    pronounce: ['Was bist du von Beruf?'],
  },
  {
    id: 'p1-ber-bin-student-fill',
    day: 1, track: 'private', topicId: BER,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.beruf.antwort-bin'],
    familyId: 'p1-ber-student',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich _____ Student. (sein)',
    answer: 'bin',
    pronounce: ['Ich bin Student.'],
  },
  {
    id: 'p1-ber-als-fill',
    day: 1, track: 'private', topicId: BER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.beruf.als-bei'],
    familyId: 'p1-ber-als',
    instruction: 'Doğru edatı yaz:',
    prompt: 'Ich arbeite _____ Lehrerin.',
    answer: 'als',
    pronounce: ['Ich arbeite als Lehrerin.'],
  },
  {
    id: 'p1-ber-bei-fill',
    day: 1, track: 'private', topicId: BER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.beruf.als-bei'],
    familyId: 'p1-ber-bei',
    instruction: 'Doğru edatı yaz:',
    prompt: 'Ich arbeite _____ Toyota.',
    answer: 'bei',
    pronounce: ['Ich arbeite bei Toyota.'],
  },
  {
    id: 'p1-kontakt-email-adresse-fill',
    day: 1, track: 'private', topicId: KON,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.kontakt.email'],
    familyId: 'p1-kontakt-email',
    instruction: 'Soruyu tamamla — "Mailin ne?" sorusunun Almancası:',
    prompt: 'Wie ist deine _____ ?',
    answer: 'E-Mail-Adresse',
    acceptedAnswers: ['Wie ist deine E-Mail-Adresse?', 'Wie ist deine E-Mail-Adresse', 'wie ist deine e-mail-adresse', 'wie ist deine e-mail-adresse?'],
    validation: { caseSensitive: false },
    pronounce: ['Wie ist deine E-Mail-Adresse?'],
  },
  {
    id: 'p1-kontakt-telefon-fill',
    day: 1, track: 'private', topicId: KON,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.kontakt.telefon'],
    familyId: 'p1-kontakt-telefon',
    instruction: 'Soruyu tamamla — "Telefonun ne?" sorusunun Almancası:',
    prompt: 'Wie ist deine _____ ?',
    answer: 'Telefonnummer',
    acceptedAnswers: ['Wie ist deine Telefonnummer?', 'Wie ist deine Telefonnummer', 'wie ist deine telefonnummer', 'wie ist deine telefonnummer?'],
    validation: { caseSensitive: false },
    pronounce: ['Wie ist deine Telefonnummer?'],
  },
  {
    id: 'p1-form-vorname-fill',
    day: 1, track: 'private', topicId: KON,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.formular.felder'],
    familyId: 'p1-form-vorname',
    instruction: 'Formu doldur — adın Mustafa:',
    prompt: 'Vorname: ______',
    answer: 'Mustafa',
    pronounce: ['Vorname'],
  },
  {
    id: 'p1-form-wohnort-fill',
    day: 1, track: 'private', topicId: KON,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.formular.felder'],
    familyId: 'p1-form-wohnort',
    instruction: 'Formu doldur — Sakarya\'da yaşıyorsun:',
    prompt: 'Wohnort: ______',
    answer: 'Sakarya',
    pronounce: ['Wohnort'],
  },
  {
    id: 'p1-form-familienstand-fill',
    day: 1, track: 'private', topicId: KON,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.formular.familienstand'],
    familyId: 'p1-form-stand',
    instruction: 'Formu doldur — bekârsın:',
    prompt: 'Familienstand → ______',
    answer: 'ledig',
    pronounce: ['ledig'],
  },
  {
    id: 'p1-form-kinder-fill',
    day: 1, track: 'private', topicId: KON,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.formular.kinder'],
    familyId: 'p1-form-kinder',
    instruction: 'Formu doldur — çocuğun yok, tam cümle yaz:',
    prompt: 'Kinder: ______',
    answer: 'Ich habe keine Kinder.',
    pronounce: ['Ich habe keine Kinder.'],
  },
  {
    id: 'p1-verb-sein-du-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.sein'],
    familyId: 'p1-verb-sein',
    instruction: 'sein çekimi:',
    prompt: 'du → ______',
    answer: 'bist',
    pronounce: ['du bist'],
  },
  {
    id: 'p1-verb-sein-ihr-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.sein'],
    familyId: 'p1-verb-sein',
    instruction: 'sein çekimi:',
    prompt: 'ihr → ______',
    answer: 'seid',
    pronounce: ['ihr seid'],
  },
  {
    id: 'p1-verb-kommen-wir-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.kommen'],
    familyId: 'p1-verb-kommen',
    instruction: 'kommen çekimi:',
    prompt: 'wir → ______',
    answer: 'kommen',
    pronounce: ['wir kommen'],
  },
  {
    id: 'p1-verb-sagen-wir-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.sagen'],
    familyId: 'p1-verb-sagen',
    instruction: 'sagen çekimi:',
    prompt: 'wir → ______',
    answer: 'sagen',
    pronounce: ['wir sagen'],
  },
  {
    id: 'p1-verb-sprechen-du-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.sprechen'],
    familyId: 'p1-verb-sprechen',
    instruction: 'sprechen çekimi (düzensiz):',
    prompt: 'du → ______',
    answer: 'sprichst',
    pronounce: ['du sprichst'],
  },
  {
    id: 'p1-verb-essen-du-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.essen'],
    familyId: 'p1-verb-essen',
    instruction: 'essen çekimi (düzensiz):',
    prompt: 'du → ______',
    answer: 'isst',
    pronounce: ['du isst'],
  },
  {
    id: 'p1-verb-kochen-ihr-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.kochen'],
    familyId: 'p1-verb-kochen',
    instruction: 'kochen çekimi:',
    prompt: 'ihr → ______',
    answer: 'kocht',
    pronounce: ['ihr kocht'],
  },
  {
    id: 'p1-form-matching',
    day: 1, track: 'private', topicId: KON,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day1.formular.felder', 'private.day1.formular.heimat'],
    familyId: 'p1-form-match',
    instruction: 'Form alanlarını anlamlarıyla eşleştir.',
    pairs: [
      { left: 'Vorname', right: 'ad' },
      { left: 'Nachname', right: 'soyad' },
      { left: 'Wohnort', right: 'ikamet yeri' },
      { left: 'Heimat', right: 'memleket' },
    ],
    pronounce: ['Vorname', 'Nachname', 'Wohnort', 'Heimat'],
  },
  {
    id: 'p1-beruf-matching',
    day: 1, track: 'private', topicId: BER,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day1.beruf.als-bei', 'private.day1.beruf.antwort-bin'],
    familyId: 'p1-ber-match',
    instruction: 'Meslek kalıplarını eşleştir.',
    pairs: [
      { left: 'Ich bin Student.', right: 'Ben öğrenciyim.' },
      { left: 'Ich arbeite als Lehrerin.', right: 'Öğretmen olarak çalışıyorum.' },
      { left: 'Ich arbeite bei Toyota.', right: 'Toyota\'da çalışıyorum.' },
    ],
    pronounce: ['Ich bin Student.', 'Ich arbeite als Lehrerin.', 'Ich arbeite bei Toyota.'],
  },
  {
    id: 'p1-vorstellung-matching',
    day: 1, track: 'private', topicId: VOR,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du', 'private.day1.vorstellung.wie-ist-dein-name', 'private.day1.vorstellung.wer-bist-du'],
    familyId: 'p1-vor-match',
    instruction: 'Soruları Türkçesiyle eşleştir.',
    pairs: [
      { left: 'Wie heißt du?', right: 'Adın ne?' },
      { left: 'Wie alt bist du?', right: 'Kaç yaşındasın?' },
      { left: 'Wo wohnst du?', right: 'Nerede yaşıyorsun?' },
    ],
    pronounce: ['Wie heißt du?', 'Wie alt bist du?', 'Wo wohnst du?'],
  },

  /* ================================================================
   * Zor — üretim / düzeltme / dönüşüm (18)
   * ================================================================ */

  {
    id: 'p1-du-sie-convert-name',
    day: 1, track: 'private', topicId: VOR,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Samimi soruyu resmî hâle çevir:',
    prompt: 'Wie heißt du? → ______',
    answer: 'Wie heißen Sie?',
    validation: { keyboardTolerance: true },
    hint: 'Fiil de değişir.',
    pronounce: ['Wie heißen Sie?'],
  },
  {
    id: 'p1-du-sie-convert-woher',
    day: 1, track: 'private', topicId: ALT,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.herkunft.woher'],
    familyId: 'p1-alt-woher',
    instruction: 'Samimi soruyu resmî hâle çevir:',
    prompt: 'Woher kommst du? → ______',
    answer: 'Woher kommen Sie?',
    pronounce: ['Woher kommen Sie?'],
  },
  {
    id: 'p1-du-sie-convert-wohnen',
    day: 1, track: 'private', topicId: ALT,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.wohnort.wo-wohnst'],
    familyId: 'p1-alt-wo-wohnst',
    instruction: 'Samimi soruyu resmî hâle çevir:',
    prompt: 'Wo wohnst du? → ______',
    answer: 'Wo wohnen Sie?',
    pronounce: ['Wo wohnen Sie?'],
  },
  {
    id: 'p1-hata-mein-telefon',
    day: 1, track: 'private', topicId: KON,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day1.kontakt.antwort-telefon'],
    familyId: 'p1-kontakt-telefon',
    instruction: 'Hata avı — doğru artikel hangisi?',
    prompt: 'Mein Telefonnummer ist 0532...',
    answer: 'Meine Telefonnummer ist 0532...',
    explanation: 'Telefonnummer dişil: die Telefonnummer → meine.',
    pronounce: ['Meine Telefonnummer ist 05325540710.'],
  },
  {
    id: 'p1-hata-aus-mis',
    day: 1, track: 'private', topicId: ALT,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day1.herkunft.aus'],
    familyId: 'p1-alt-aus',
    instruction: 'Hata avı — edatı düzelt:',
    prompt: 'Ich komme in der Türkei.',
    answer: 'Ich komme aus der Türkei.',
    validation: { keyboardTolerance: true },
    explanation: 'Köken için aus, ikamet için in kullanılır.',
    pronounce: ['Ich komme aus der Türkei.'],
  },
  {
    id: 'p1-hata-sprichst',
    day: 1, track: 'private', topicId: FII,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day1.verben.sprechen'],
    familyId: 'p1-verb-sprechen',
    instruction: 'Hata avı — fiil biçimini düzelt:',
    prompt: 'Du sprechst Englisch.',
    answer: 'Du sprichst Englisch.',
    explanation: 'sprechen düzensiz: du sprichst, er spricht.',
    pronounce: ['Du sprichst Englisch.'],
  },
  {
    id: 'p1-hata-heisst-eszett',
    day: 1, track: 'private', topicId: FII,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day1.verben.heissen'],
    familyId: 'p1-verb-heissen',
    instruction: 'Yazım hatasını düzelt:',
    prompt: 'Wie heisst du?',
    answer: 'Wie heißt du?',
    validation: { keyboardTolerance: true },
    explanation: 'ß harfi: heißt, nicht heisst (resmî yazımda ß).',
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'p1-self-intro-builder',
    day: 1, track: 'private', topicId: VOR,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du', 'private.day1.alter.wie-alt', 'private.day1.herkunft.aus'],
    familyId: 'p1-self-intro',
    instruction: 'Kendini tanıt — kelimeleri doğru sıraya koy:',
    prompt: 'Mustafa / heiße / ich / achtzehn / bin / Jahre / alt',
    answer: 'Ich heiße Mustafa und bin achtzehn Jahre alt.',
    words: ['Ich', 'heiße', 'Mustafa', 'und', 'bin', 'achtzehn', 'Jahre', 'alt'],
    pronounce: ['Ich heiße Mustafa.'],
    explanation: 'İsim + yaş birleştirme.',
  },
  {
    id: 'p1-form-complete-free',
    day: 1, track: 'private', topicId: KON,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.formular.felder', 'private.day1.formular.familienstand', 'private.day1.formular.kinder'],
    familyId: 'p1-form-vorname',
    instruction: 'Formu tamamla — Familienstand alanına ne yazarsın? (bekâr)',
    prompt: 'Familienstand: ______',
    answer: 'ledig',
    pronounce: ['ledig'],
  },
  {
    id: 'p1-vorstellung-dialog-free',
    day: 1, track: 'private', topicId: VOR,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.vorstellung.freut-mich', 'private.day1.vorstellung.sich-vorstellen'],
    familyId: 'p1-vor-freut',
    instruction: 'Mini diyalog: B ne demeli? Kendini tanıt ve memnuniyet belirt.',
    prompt: 'A: Wie heißt du?\nB: ______',
    answer: 'Ich heiße Mustafa. Freut mich!',
    acceptedAnswers: ['Ich heiße Mustafa.', 'Mein Name ist Mustafa. Freut mich!', 'Ich bin Mustafa. Freut mich!'],
    openEnded: true,
    validation: { keyboardTolerance: true },
    pronounce: ['Ich heiße Mustafa.', 'Freut mich!'],
  },
  {
    id: 'p1-alt-dialog-woher-wohnst-free',
    day: 1, track: 'private', topicId: ALT,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.herkunft.aus', 'private.day1.wohnort.in'],
    familyId: 'p1-alt-aus',
    instruction: 'İki soruyu tek bir cevapla birleştir:',
    prompt: 'Woher kommst du und wo wohnst du? (Sakarya)',
    answer: 'Ich komme aus Sakarya und wohne in Sakarya.',
    pronounce: ['Ich komme aus Sakarya und wohne in Sakarya.'],
  },
  {
    id: 'p1-beruf-produktion-free',
    day: 1, track: 'private', topicId: BER,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.beruf.als-bei'],
    familyId: 'p1-ber-als',
    instruction: 'Toyota\'da çalıştığını tek cümlede söyle.',
    prompt: 'Toyota\'da çalışıyorum → ______',
    answer: 'Ich arbeite bei Toyota.',
    acceptedAnswers: ['Ich arbeite bei Toyota'],
    pronounce: ['Ich arbeite bei Toyota.'],
  },

  /* ================================================================
   * Çeviri & Word-Bank (10)
   * ================================================================ */

  {
    id: 'p1-wb-name-de-tr',
    day: 1, track: 'private', topicId: VOR,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Türkçeden Almancaya kur — Adın ne?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Adın ne?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Wie' }, { id: 't2', text: 'heißt' }, { id: 't3', text: 'du?' },
        { id: 't4', text: 'Wo' }, { id: 't5', text: 'bist' }, { id: 't6', text: 'Sie?' },
      ],
      acceptedSequences: [['Wie', 'heißt', 'du?']],
    },
    answer: 'Wie heißt du?',
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'p1-wb-wie-alt-tr-de',
    day: 1, track: 'private', topicId: ALT,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.alter.wie-alt'],
    familyId: 'p1-alt-wie-alt',
    instruction: 'Türkçeden Almancaya kur — Kaç yaşındasın?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Kaç yaşındasın?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Wie' }, { id: 't2', text: 'alt' }, { id: 't3', text: 'bist' }, { id: 't4', text: 'du?' },
        { id: 't5', text: 'Wo' }, { id: 't6', text: 'wohnst' },
      ],
      acceptedSequences: [['Wie', 'alt', 'bist', 'du?']],
    },
    answer: 'Wie alt bist du?',
    pronounce: ['Wie alt bist du?'],
  },
  {
    id: 'p1-wb-woher-tr-de',
    day: 1, track: 'private', topicId: ALT,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.herkunft.woher'],
    familyId: 'p1-alt-woher',
    instruction: 'Türkçeden Almancaya kur — Nerelisin?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Nerelisin?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Woher' }, { id: 't2', text: 'kommst' }, { id: 't3', text: 'du?' },
        { id: 't4', text: 'Wo' }, { id: 't5', text: 'wohnst' }, { id: 't6', text: 'heißt' },
      ],
      acceptedSequences: [['Woher', 'kommst', 'du?']],
    },
    answer: 'Woher kommst du?',
    pronounce: ['Woher kommst du?'],
  },
  {
    id: 'p1-wb-wo-wohnst-tr-de',
    day: 1, track: 'private', topicId: ALT,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.wohnort.wo-wohnst'],
    familyId: 'p1-alt-wo-wohnst',
    instruction: 'Türkçeden Almancaya kur — Nerede yaşıyorsun?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Nerede yaşıyorsun?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Wo' }, { id: 't2', text: 'wohnst' }, { id: 't3', text: 'du?' },
        { id: 't4', text: 'Woher' }, { id: 't5', text: 'kommst' },
      ],
      acceptedSequences: [['Wo', 'wohnst', 'du?']],
    },
    answer: 'Wo wohnst du?',
    pronounce: ['Wo wohnst du?'],
  },
  {
    id: 'p1-wb-beruf-de',
    day: 1, track: 'private', topicId: BER,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.beruf.frage'],
    familyId: 'p1-ber-frage',
    instruction: 'Türkçeden Almancaya kur — Mesleğin ne?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Mesleğin ne?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Was' }, { id: 't2', text: 'machst' }, { id: 't3', text: 'du' }, { id: 't4', text: 'beruflich?' },
        { id: 't5', text: 'Wie' }, { id: 't6', text: 'alt' },
      ],
      acceptedSequences: [['Was', 'machst', 'du', 'beruflich?']],
    },
    answer: 'Was machst du beruflich?',
    pronounce: ['Was machst du beruflich?'],
  },
  {
    id: 'p1-wb-email-de-tr',
    day: 1, track: 'private', topicId: KON,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.kontakt.email'],
    familyId: 'p1-kontakt-email',
    instruction: 'Almancadan Türkçeye çevir — Mailin ne?',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Wie ist deine E-Mail-Adresse?',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Mailin' }, { id: 't2', text: 'ne?' }, { id: 't3', text: 'Telefonun' }, { id: 't4', text: 'Adın' },
      ],
      acceptedSequences: [['Mailin', 'ne?']],
    },
    answer: 'Mailin ne?',
    audio: { prompt: { text: 'Wie ist deine E-Mail-Adresse?', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Wie ist deine E-Mail-Adresse?'],
  },
  {
    id: 'p1-wb-sprachen-tr-de',
    day: 1, track: 'private', topicId: DIL,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.sprachen.welche'],
    familyId: 'p1-sprachen-welche',
    instruction: 'Türkçeden Almancaya kur — Hangi dilleri konuşuyorsun?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Hangi dilleri konuşuyorsun?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Welche' }, { id: 't2', text: 'Sprachen' }, { id: 't3', text: 'sprichst' }, { id: 't4', text: 'du?' },
        { id: 't5', text: 'Wie' }, { id: 't6', text: 'heißt' },
      ],
      acceptedSequences: [['Welche', 'Sprachen', 'sprichst', 'du?']],
    },
    answer: 'Welche Sprachen sprichst du?',
    pronounce: ['Welche Sprachen sprichst du?'],
  },
  {
    id: 'p1-wb-ich-spreche-de-tr',
    day: 1, track: 'private', topicId: DIL,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day1.sprachen.antwort'],
    familyId: 'p1-sprachen-antwort',
    instruction: 'Almancadan Türkçeye çevir — İngilizce konuşuyorum',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Ich spreche Englisch.',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'İngilizce' }, { id: 't2', text: 'konuşuyorum.' }, { id: 't3', text: 'yaşıyorum.' },
      ],
      acceptedSequences: [['İngilizce', 'konuşuyorum.']],
    },
    answer: 'İngilizce konuşuyorum.',
    audio: { prompt: { text: 'Ich spreche Englisch.', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Ich spreche Englisch.'],
  },

  /* ================================================================
   * Sıralama / Listening / Dictation / Spoken (8)
   * ================================================================ */

  {
    id: 'p1-order-wohne-in-sakarya',
    day: 1, track: 'private', topicId: ALT,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.wohnort.in'],
    familyId: 'p1-alt-in',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / wohne / in / Sakarya.',
    answer: 'Ich wohne in Sakarya.',
    words: ['Ich', 'wohne', 'in', 'Sakarya'],
    pronounce: ['Ich wohne in Sakarya.'],
  },
  {
    id: 'p1-order-komme-aus-tuerkei',
    day: 1, track: 'private', topicId: ALT,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.herkunft.aus'],
    familyId: 'p1-alt-aus',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / komme / aus / der / Türkei.',
    answer: 'Ich komme aus der Türkei.',
    words: ['Ich', 'komme', 'aus', 'der', 'Türkei'],
    pronounce: ['Ich komme aus der Türkei.'],
  },
  {
    id: 'p1-listen-wie-heisst-du',
    day: 1, track: 'private', topicId: VOR,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du'],
    familyId: 'p1-listen-heisst',
    instruction: 'Duyduğunu seç:',
    prompt: 'Wie heißt du?',
    audioText: 'Wie heißt du?',
    answer: 'Wie heißt du?',
    options: ['Wie heißt du?', 'Wie alt bist du?', 'Wo wohnst du?', 'Woher kommst du?'],
    audio: { prompt: { text: 'Wie heißt du?', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p1-dictation-telefon',
    day: 1, track: 'private', topicId: KON,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.kontakt.antwort-telefon'],
    familyId: 'p1-kontakt-telefon',
    instruction: 'Telefon numaranı duydun — aynen yaz:',
    audioText: 'Meine Telefonnummer ist 05325540710.',
    answer: 'Meine Telefonnummer ist 05325540710.',
    audio: { prompt: { text: 'Meine Telefonnummer ist 05325540710.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p1-dictation-sprachen',
    day: 1, track: 'private', topicId: DIL,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.sprachen.welche'],
    familyId: 'p1-sprachen-welche',
    instruction: 'Dil sorusunu duydun — aynen yaz:',
    audioText: 'Welche Sprachen sprichst du?',
    answer: 'Welche Sprachen sprichst du?',
    audio: { prompt: { text: 'Welche Sprachen sprichst du?', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p1-spoken-vorstellung',
    day: 1, track: 'private', topicId: VOR,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day1.vorstellung.wie-heisst-du', 'private.day1.vorstellung.freut-mich'],
    familyId: 'p1-spoken-vor',
    instruction: 'Sesli görev: kendini tanıt ve memnuniyet belirt.',
    requirements: ['Ich heiße ...', 'Freut mich!'],
    sampleAnswer: 'Ich heiße Mustafa. Freut mich!',
    pronounce: ['Ich heiße Mustafa.', 'Freut mich!'],
  },
  {
    id: 'p1-spoken-herkunft-wohnort',
    day: 1, track: 'private', topicId: ALT,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day1.herkunft.woher', 'private.day1.wohnort.wo-wohnst'],
    familyId: 'p1-spoken-herkunft',
    instruction: 'Sesli görev: köken ve ikamet söyle.',
    requirements: ['Ich komme aus ...', 'Ich wohne in ...'],
    sampleAnswer: 'Ich komme aus der Türkei. Ich wohne in Sakarya.',
    pronounce: ['Ich komme aus der Türkei.', 'Ich wohne in Sakarya.'],
  },
  {
    id: 'p1-listen-wie-alt',
    day: 1, track: 'private', topicId: ALT,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.alter.wie-alt'],
    familyId: 'p1-listen-alt',
    instruction: 'Duyduğunu seç:',
    prompt: 'Wie alt bist du?',
    audioText: 'Wie alt bist du?',
    answer: 'Wie alt bist du?',
    options: ['Wie alt bist du?', 'Wo wohnst du?', 'Wie heißt du?', 'Was machst du beruflich?'],
    audio: { prompt: { text: 'Wie alt bist du?', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Ekstra — ek sorularla 65+ hedefini garanti
   * ================================================================ */

  {
    id: 'p1-extra-vorstellung-sie-free',
    day: 1, track: 'private', topicId: VOR,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.vorstellung.wie-ist-dein-name'],
    familyId: 'p1-vor-name',
    instruction: 'Resmî soruyu yaz:',
    prompt: 'Adınız ne?',
    answer: 'Wie ist Ihr Name?',
    pronounce: ['Wie ist Ihr Name?'],
  },
  {
    id: 'p1-extra-antwort-freut-free',
    day: 1, track: 'private', topicId: VOR,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day1.vorstellung.freut-mich'],
    familyId: 'p1-vor-freut',
    instruction: 'Tanışırken ne dersin?',
    prompt: 'Memnun oldum! → ______',
    answer: 'Freut mich!',
    acceptedAnswers: ['Ich habe mich gefreut!'],
    pronounce: ['Freut mich!'],
  },
  {
    id: 'p1-extra-heissen-ihr-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.heissen'],
    familyId: 'p1-verb-heissen',
    instruction: 'heißen çekimi:',
    prompt: 'ihr → ______',
    answer: 'heißt',
    validation: { keyboardTolerance: true },
    pronounce: ['ihr heißt'],
  },
  {
    id: 'p1-extra-sein-wir-sind-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.sein'],
    familyId: 'p1-verb-sein',
    instruction: 'sein çekimi:',
    prompt: 'wir → ______',
    answer: 'sind',
    pronounce: ['wir sind'],
  },
  {
    id: 'p1-extra-beruf-was-machen-sie',
    day: 1, track: 'private', topicId: BER,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day1.beruf.frage'],
    familyId: 'p1-ber-frage',
    instruction: 'Resmî meslek sorusunu yaz:',
    prompt: 'Mesleğiniz ne? → ______',
    answer: 'Was machen Sie beruflich?',
    pronounce: ['Was machen Sie beruflich?'],
  },
  {
    id: 'p1-extra-essen-er-isst-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.essen'],
    familyId: 'p1-verb-essen',
    instruction: 'essen çekimi:',
    prompt: 'er → ______',
    answer: 'isst',
    pronounce: ['er isst'],
  },
  {
    id: 'p1-extra-sagen-du-sagst-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.sagen'],
    familyId: 'p1-verb-sagen',
    instruction: 'sagen çekimi:',
    prompt: 'du → ______',
    answer: 'sagst',
    pronounce: ['du sagst'],
  },
  {
    id: 'p1-extra-kochen-er-kocht-fill',
    day: 1, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day1.verben.kochen'],
    familyId: 'p1-verb-kochen',
    instruction: 'kochen çekimi:',
    prompt: 'er → ______',
    answer: 'kocht',
    pronounce: ['er kocht'],
  },
  {
    id: 'p1-nezakaet-entschuldigung-mc',
    day: 1, track: 'private', topicId: DIL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day1.nezaket.entschuldigung'],
    familyId: 'p1-nezakaet',
    instruction: 'Nezaket kalıbı nedir?',
    prompt: 'Entschuldigung',
    answer: 'Affedersiniz / Pardon',
    options: ['Affedersiniz / Pardon', 'Teşekkürler', 'Merhaba', 'Güle güle'],
    pronounce: ['Entschuldigung'],
  },
];
