/**
 * Özel Ders — 10. Gün — yazılmış alıştırma havuzu.
 *
 * 10. Gün bir ÜRETİM günüdür: ayrılabilen fiiller + `Mein Tag` (%60-65),
 * saat söyleme `Uhrzeit` (%25-30), küçük kelime tekrarı (%10-15).
 *
 * Günün üretim hedefi: **öğrenci gününü basit ayrılabilen fiillerle anlatır
 * ve temel saatleri okur.** A1 SINIRI: hiçbir alıştırma Private 1-10 dışında
 * kavram istemez — yan cümle, Perfekt, karşılaştırma ve tam refleksif
 * çekim tablosu YOKTUR (`Ich ziehe mich an.` hazır kalıptır).
 *
 * Kaynak normalizasyonları (defter → kanonik):
 *   - `Ich dusche mich.` → `Ich dusche.`
 *   - `Ich lese Buch.` → `Ich lese ein Buch.`
 *   - `Danach gete ich ins Bett.` → `Danach gehe ich ins Bett.`
 *   - `mit meiner Freunden` → `mit meinen Freunden`
 *   - resmî 20:35 `acht Uhr ...` → `zwanzig Uhr fünfunddreißig`
 *   - günlük `von` → `vor`; 20:45 `Viertel vor acht` → `Viertel vor neun`
 */

import type { AuthoredExercise } from '../types.ts';

const HED = 'private.day10.hedef';
const TRE = 'private.day10.trennbar-nedir';
const VER = 'private.day10.kern-verben';
const SAB = 'private.day10.mein-tag-sabah';
const GUN = 'private.day10.mein-tag-gun';
const AKS = 'private.day10.mein-tag-aksam';
const DAN = 'private.day10.dann-danach';
const KAR = 'private.day10.trennbar-nicht';
const SOR = 'private.day10.uhrzeit-frage';
const RES = 'private.day10.uhrzeit-resmi';
const GUL = 'private.day10.uhrzeit-gunluk';
const HAL = 'private.day10.halb-viertel';
const UMU = 'private.day10.um-uhr';
const TAM = 'private.day10.mein-tag-tam';
const WOR = 'private.day10.wortschatz';

export const PRIVATE_DAY10_EXERCISES: AuthoredExercise[] = [
  /* ================================================================
   * Bugünün Hedefi (2)
   * ================================================================ */
  {
    id: 'p10-hed-giris-mc',
    day: 10, track: 'private', topicId: HED,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.hedef.giris'],
    familyId: 'p10-hed-giris',
    instruction: '10. Günün ana hedefi nedir?',
    prompt: 'Bu gün ne üzerine kuruludur?',
    answer: 'Ayrılabilen fiillerle günümü anlatmak ve saati söylemek',
    options: [
      'Ayrılabilen fiillerle günümü anlatmak ve saati söylemek',
      'Geçmiş zaman çekimlerini öğrenmek',
      'Sıfat karşılaştırma eklerini öğrenmek',
      'Yan cümle kurmayı öğrenmek',
    ],
  },


  /* ================================================================
   * Ayrılabilen Fiil Nedir? (7)
   * ================================================================ */
  {
    id: 'p10-tre-kural-mc',
    day: 10, track: 'private', topicId: TRE,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.trennbar.kural'],
    familyId: 'p10-tre-kural',
    instruction: 'Ayrılabilen fiilin kuralı nedir?',
    prompt: 'aufstehen cümlede nasıl bölünür?',
    answer: 'kök ikinci sırada, önek en sonda',
    options: [
      'kök ikinci sırada, önek en sonda',
      'önek ikinci sırada, kök en sonda',
      'fiil hiç bölünmez, tek parça kalır',
      'önek cümleden tamamen düşer',
    ],
    pronounce: ['aufstehen'],
  },
  {
    id: 'p10-tre-bolme-fill',
    day: 10, track: 'private', topicId: TRE,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day10.trennbar.kural'],
    familyId: 'p10-tre-bolme',
    instruction: 'Öneki yaz:',
    prompt: 'aufstehen → ___ + stehen',
    answer: 'auf',
    validation: { noTypoTolerance: true },
    pronounce: ['aufstehen'],
  },
  {
    id: 'p10-tre-auf-fill',
    day: 10, track: 'private', topicId: TRE,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day10.trennbar.ornek'],
    familyId: 'p10-tre-auf',
    instruction: 'Cümleyi tamamla — Ben saat 7’de kalkıyorum.',
    prompt: 'Ich stehe um 7 Uhr ___.',
    answer: 'auf',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich stehe um 7 Uhr auf.'],
  },
  {
    id: 'p10-tre-wb-aufstehen',
    day: 10, track: 'private', topicId: TRE,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.trennbar.ornek'],
    familyId: 'p10-tre-auf',
    instruction: 'Türkçeden Almancaya kur — Ben saat 7’de kalkıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: "Ben saat 7'de kalkıyorum.",
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'stehe' }, { id: 't3', text: 'um' },
        { id: 't4', text: 'sieben' }, { id: 't5', text: 'Uhr' }, { id: 't6', text: 'auf.' },
        { id: 't7', text: 'an' }, { id: 't8', text: 'ein' },
      ],
      acceptedSequences: [['Ich', 'stehe', 'um', 'sieben', 'Uhr', 'auf.']],
    },
    answer: 'Ich stehe um sieben Uhr auf.',
    pronounce: ['Ich stehe um sieben Uhr auf.'],
  },
  {
    id: 'p10-tre-error-aufstehe',
    day: 10, track: 'private', topicId: TRE,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day10.trennbar.kural', 'private.day10.trennbar.ornek'],
    familyId: 'p10-tre-error',
    instruction: 'Önek yanlış yerde — cümleyi düzelt:',
    prompt: 'Ich aufstehe um 7 Uhr.',
    answer: 'Ich stehe um 7 Uhr auf.',
    explanation: 'Önek (`auf`) fiilin yanında kalmaz; cümlenin en sonuna gider.',
    pronounce: ['Ich stehe um 7 Uhr auf.'],
  },
  {
    id: 'p10-tre-saat-basta-order',
    day: 10, track: 'private', topicId: TRE,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.trennbar.saat-basta'],
    familyId: 'p10-tre-saat-basta',
    instruction: 'Kelimeleri doğru sıraya diz — Saat 7’de kalkıyorum (saat başta).',
    answer: 'Um 7 Uhr stehe ich auf.',
    pronounce: ['Um 7 Uhr stehe ich auf.'],
  },
  {
    id: 'p10-tre-listen-aufstehen',
    day: 10, track: 'private', topicId: TRE,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.trennbar.ornek'],
    familyId: 'p10-tre-listen',
    instruction: 'Duyduğun cümleyi seç:',
    prompt: 'Ich stehe um sieben Uhr auf.',
    audioText: 'Ich stehe um sieben Uhr auf.',
    answer: 'Ich stehe um sieben Uhr auf.',
    options: ['Ich stehe um sieben Uhr auf.', 'Ich wache um sieben Uhr auf.', 'Ich gehe um sieben Uhr auf.', 'Ich stehe um sieben Uhr an.'],
    audio: { prompt: { text: 'Ich stehe um sieben Uhr auf.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * aufstehen / aufwachen + fark (6)
   * ================================================================ */
  {
    id: 'p10-aufstehen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.aufstehen'],
    familyId: 'p10-verb-aufstehen',
    instruction: '"aufstehen" ne demektir?',
    prompt: 'aufstehen',
    answer: 'yataktan kalkmak',
    options: ['yataktan kalkmak', 'gözlerini açmak', 'giyinmek', 'uyumak'],
    pronounce: ['aufstehen'],
  },
  {
    id: 'p10-aufstehen-du-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.aufstehen'],
    familyId: 'p10-verb-aufstehen',
    instruction: 'Fiili çek — Sen kalkıyorsun.',
    prompt: 'Du ___ auf. (aufstehen)',
    answer: 'stehst',
    pronounce: ['Du stehst auf.'],
  },
  {
    id: 'p10-aufwachen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.aufwachen'],
    familyId: 'p10-verb-aufwachen',
    instruction: '"aufwachen" ne demektir?',
    prompt: 'aufwachen',
    answer: 'uyanmak, gözlerini açmak',
    options: ['uyanmak, gözlerini açmak', 'yataktan kalkmak', 'üstünü çıkarmak', 'kahvaltı etmek'],
    pronounce: ['aufwachen'],
  },
  {
    id: 'p10-aufwachen-wache-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.aufwachen'],
    familyId: 'p10-verb-aufwachen',
    instruction: 'Fiili çek — Saat 7’de uyanıyorum.',
    prompt: 'Ich ___ um 7 Uhr auf. (aufwachen)',
    answer: 'wache',
    pronounce: ['Ich wache um 7 Uhr auf.'],
  },
  {
    id: 'p10-fark-saat-mc',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.verb.uyanma-farki'],
    familyId: 'p10-verb-fark',
    instruction: 'Doğru fiili seç — 07:00, gözlerini açıyorsun (yataktan kalkmadan).',
    prompt: '07:00 — gözlerini açıyorsun',
    answer: 'aufwachen',
    options: ['aufwachen', 'aufstehen', 'anziehen', 'frühstücken'],
    pronounce: ['aufwachen'],
  },
  {
    id: 'p10-fark-yatak-free',
    day: 10, track: 'private', topicId: VER,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.verb.uyanma-farki'],
    familyId: 'p10-verb-fark',
    instruction: 'Doğru fiili yaz — 07:05, yataktan kalkıyorsun.',
    prompt: '07:05 — yataktan kalkıyorsun. Fiil: ___',
    answer: 'aufstehen',
    pronounce: ['aufstehen'],
  },

  /* ================================================================
   * anziehen / ausziehen (5)
   * ================================================================ */
  {
    id: 'p10-anziehen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.anziehen'],
    familyId: 'p10-verb-anziehen',
    instruction: '"sich anziehen" ne demektir?',
    prompt: 'sich anziehen',
    answer: 'giyinmek',
    options: ['giyinmek', 'soyunmak', 'yıkanmak', 'uyumak'],
    pronounce: ['sich anziehen'],
  },
  {
    id: 'p10-anziehen-mich-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.anziehen-chunk'],
    familyId: 'p10-verb-anziehen',
    instruction: 'Hazır kalıbı tamamla — Giyiniyorum.',
    prompt: 'Ich ziehe ___ an.',
    answer: 'mich',
    pronounce: ['Ich ziehe mich an.'],
  },
  {
    id: 'p10-anziehen-wb',
    day: 10, track: 'private', topicId: VER,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.verb.anziehen-chunk'],
    familyId: 'p10-verb-anziehen-wb',
    instruction: 'Türkçeden Almancaya kur — Giyiniyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Giyiniyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'ziehe' }, { id: 't3', text: 'mich' },
        { id: 't4', text: 'an.' }, { id: 't5', text: 'dich' }, { id: 't6', text: 'aus.' },
      ],
      acceptedSequences: [['Ich', 'ziehe', 'mich', 'an.']],
    },
    answer: 'Ich ziehe mich an.',
    pronounce: ['Ich ziehe mich an.'],
  },
  {
    id: 'p10-ausziehen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.ausziehen'],
    familyId: 'p10-verb-ausziehen',
    instruction: '"sich ausziehen" ne demektir?',
    prompt: 'sich ausziehen',
    answer: 'üstünü çıkarmak, soyunmak',
    options: ['üstünü çıkarmak, soyunmak', 'giyinmek', 'duş almak', 'taranmak'],
    pronounce: ['sich ausziehen'],
  },
  {
    id: 'p10-ausziehen-free',
    day: 10, track: 'private', topicId: VER,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.verb.ausziehen', 'private.day10.aksam.ausziehen'],
    familyId: 'p10-verb-ausziehen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Üstümü çıkarıyorum. → ______',
    answer: 'Ich ziehe mich aus.',
    pronounce: ['Ich ziehe mich aus.'],
  },

  /* ================================================================
   * einkaufen / aufräumen (6)
   * ================================================================ */
  {
    id: 'p10-einkaufen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.einkaufen'],
    familyId: 'p10-verb-einkaufen',
    instruction: '"einkaufen" ne demektir?',
    prompt: 'einkaufen',
    answer: 'alışveriş yapmak',
    options: ['alışveriş yapmak', 'oda toplamak', 'yemek yapmak', 'para ödemek'],
    pronounce: ['einkaufen'],
  },
  {
    id: 'p10-einkaufen-kaufe-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.einkaufen-cumle'],
    familyId: 'p10-verb-einkaufen',
    instruction: 'Fiili çek — Alışveriş yapıyorum.',
    prompt: 'Ich ___ ein. (einkaufen)',
    answer: 'kaufe',
    pronounce: ['Ich kaufe ein.'],
  },
  {
    id: 'p10-einkaufen-wb',
    day: 10, track: 'private', topicId: VER,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.verb.einkaufen-cumle'],
    familyId: 'p10-verb-einkaufen-wb',
    instruction: 'Türkçeden Almancaya kur — Alışveriş yapıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Alışveriş yapıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'kaufe' }, { id: 't3', text: 'ein.' },
        { id: 't4', text: 'aus.' }, { id: 't5', text: 'verkaufe' },
      ],
      acceptedSequences: [['Ich', 'kaufe', 'ein.']],
    },
    answer: 'Ich kaufe ein.',
    pronounce: ['Ich kaufe ein.'],
  },
  {
    id: 'p10-aufraeumen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.aufraeumen'],
    familyId: 'p10-verb-aufraeumen',
    instruction: '"aufräumen" ne demektir?',
    prompt: 'aufräumen',
    answer: 'odayı toplamak, düzenlemek',
    options: ['odayı toplamak, düzenlemek', 'alışveriş yapmak', 'cam silmek', 'yemek hazırlamak'],
    pronounce: ['aufräumen'],
  },
  {
    id: 'p10-aufraeumen-raeume-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.aufraeumen-cumle'],
    familyId: 'p10-verb-aufraeumen',
    instruction: 'Fiili çek — Odayı topluyorum.',
    prompt: 'Ich ___ auf. (aufräumen)',
    answer: 'räume',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich räume auf.'],
  },
  {
    id: 'p10-aufraeumen-wb-zimmer',
    day: 10, track: 'private', topicId: VER,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.verb.aufraeumen-cumle'],
    familyId: 'p10-verb-aufraeumen-wb',
    instruction: 'Türkçeden Almancaya kur — Odamı topluyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Odamı topluyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'räume' }, { id: 't3', text: 'mein' },
        { id: 't4', text: 'Zimmer' }, { id: 't5', text: 'auf.' },
        { id: 't6', text: 'meine' }, { id: 't7', text: 'an.' },
      ],
      acceptedSequences: [['Ich', 'räume', 'mein', 'Zimmer', 'auf.']],
    },
    answer: 'Ich räume mein Zimmer auf.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich räume mein Zimmer auf.'],
  },

  /* ================================================================
   * anrufen / fernsehen (6)
   * ================================================================ */
  {
    id: 'p10-anrufen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.anrufen'],
    familyId: 'p10-verb-anrufen',
    instruction: '"anrufen" ne demektir?',
    prompt: 'anrufen',
    answer: 'telefonla aramak',
    options: ['telefonla aramak', 'ziyaret etmek', 'davet etmek', 'cevap vermek'],
    pronounce: ['anrufen'],
  },
  {
    id: 'p10-anrufen-rufe-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.anrufen-cumle'],
    familyId: 'p10-verb-anrufen',
    instruction: 'Öneki sona yaz — Seni arıyorum.',
    prompt: 'Ich rufe dich ___. (anrufen)',
    answer: 'an',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich rufe dich an.'],
  },
  {
    id: 'p10-anrufen-free',
    day: 10, track: 'private', topicId: VER,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.verb.anrufen-cumle'],
    familyId: 'p10-verb-anrufen-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Seni arıyorum. → ______',
    answer: 'Ich rufe dich an.',
    pronounce: ['Ich rufe dich an.'],
  },
  {
    id: 'p10-fernsehen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.fernsehen'],
    familyId: 'p10-verb-fernsehen',
    instruction: '"fernsehen" ne demektir?',
    prompt: 'fernsehen',
    answer: 'televizyon izlemek',
    options: ['televizyon izlemek', 'radyo dinlemek', 'telefonla aramak', 'film çekmek'],
    pronounce: ['fernsehen'],
  },
  {
    id: 'p10-fernsehen-sehe-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.fernsehen-cumle'],
    familyId: 'p10-verb-fernsehen',
    instruction: 'Fiili çek — Akşam televizyon izliyorum.',
    prompt: 'Ich ___ am Abend fern. (fernsehen)',
    answer: 'sehe',
    pronounce: ['Ich sehe am Abend fern.'],
  },
  {
    id: 'p10-fernsehen-siehst-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['private.day10.verb.fernsehen-cumle'],
    familyId: 'p10-verb-fernsehen-du',
    instruction: 'Fiili çek — Sen akşam televizyon izliyorsun (e → ie).',
    prompt: 'Du ___ am Abend fern. (fernsehen)',
    answer: 'siehst',
    pronounce: ['Du siehst am Abend fern.'],
  },
  /* ================================================================
   * aufhören / vorbereiten / einladen (5)
   * ================================================================ */
  {
    id: 'p10-aufhoeren-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.aufhoeren'],
    familyId: 'p10-verb-aufhoeren',
    instruction: '"aufhören" ne demektir?',
    prompt: 'aufhören',
    answer: 'bırakmak, son vermek',
    options: ['bırakmak, son vermek', 'başlamak', 'devam etmek', 'dinlenmek'],
    pronounce: ['aufhören'],
  },
  {
    id: 'p10-aufhoeren-hoere-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.aufhoeren'],
    familyId: 'p10-verb-aufhoeren',
    instruction: 'Fiili çek — Bırakıyorum.',
    prompt: 'Ich ___ auf. (aufhören)',
    answer: 'höre',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich höre auf.'],
  },
  {
    id: 'p10-vorbereiten-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.vorbereiten'],
    familyId: 'p10-verb-vorbereiten',
    instruction: '"vorbereiten" ne demektir?',
    prompt: 'vorbereiten',
    answer: 'hazırlamak',
    options: ['hazırlamak', 'yemek', 'taşımak', 'satın almak'],
    pronounce: ['vorbereiten'],
  },
  {
    id: 'p10-vorbereiten-bereite-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.vorbereiten'],
    familyId: 'p10-verb-vorbereiten',
    instruction: 'Fiili çek — Kahvaltıyı hazırlıyorum.',
    prompt: 'Ich ___ das Frühstück vor. (vorbereiten)',
    answer: 'bereite',
    pronounce: ['Ich bereite das Frühstück vor.'],
  },
  {
    id: 'p10-einladen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.einladen'],
    familyId: 'p10-verb-einladen',
    instruction: '"einladen" ne demektir?',
    prompt: 'einladen',
    answer: 'davet etmek',
    options: ['davet etmek', 'uğurlamak', 'karşılamak', 'beklemek'],
    pronounce: ['einladen'],
  },

  /* ================================================================
   * einladen / mitbringen / aufsetzen / zurückkommen / achtgeben (8)
   * ================================================================ */
  {
    id: 'p10-einladen-lade-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.einladen'],
    familyId: 'p10-verb-einladen',
    instruction: 'Fiili çek — Seni davet ediyorum.',
    prompt: 'Ich ___ dich ein. (einladen)',
    answer: 'lade',
    pronounce: ['Ich lade dich ein.'],
  },
  {
    id: 'p10-mitbringen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.mitbringen'],
    familyId: 'p10-verb-mitbringen',
    instruction: '"mitbringen" ne demektir?',
    prompt: 'mitbringen',
    answer: 'beraberinde getirmek',
    options: ['beraberinde getirmek', 'geri götürmek', 'ödünç vermek', 'teslim etmek'],
    pronounce: ['mitbringen'],
  },
  {
    id: 'p10-mitbringen-bringe-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.mitbringen'],
    familyId: 'p10-verb-mitbringen',
    instruction: 'Fiili çek — Bir kitap getiriyorum.',
    prompt: 'Ich ___ ein Buch mit. (mitbringen)',
    answer: 'bringe',
    pronounce: ['Ich bringe ein Buch mit.'],
  },
  {
    id: 'p10-aufsetzen-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.aufsetzen'],
    familyId: 'p10-verb-aufsetzen',
    instruction: '"aufsetzen" ne demektir?',
    prompt: 'aufsetzen',
    answer: 'takmak (gözlük, şapka)',
    options: ['takmak (gözlük, şapka)', 'çıkarmak', 'temizlemek', 'kapatmak'],
    pronounce: ['aufsetzen'],
  },
  {
    id: 'p10-aufsetzen-setze-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.aufsetzen'],
    familyId: 'p10-verb-aufsetzen',
    instruction: 'Fiili çek — Gözlüğü takıyorum.',
    prompt: 'Ich ___ die Brille auf. (aufsetzen)',
    answer: 'setze',
    pronounce: ['Ich setze die Brille auf.'],
  },
  {
    id: 'p10-zurueck-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.zurueckkommen'],
    familyId: 'p10-verb-zurueck',
    instruction: '"zurückkommen" ne demektir?',
    prompt: 'zurückkommen',
    answer: 'geri dönmek',
    options: ['geri dönmek', 'erken gelmek', 'geç kalmak', 'yola çıkmak'],
    pronounce: ['zurückkommen'],
  },
  {
    id: 'p10-zurueck-komme-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.zurueckkommen'],
    familyId: 'p10-verb-zurueck',
    instruction: 'Öneki sona yaz — Sonra eve geri dönüyorum.',
    prompt: 'Danach komme ich nach Hause ___. (zurückkommen)',
    answer: 'zurück',
    validation: { keyboardTolerance: true },
    pronounce: ['Danach komme ich nach Hause zurück.'],
  },
  {
    id: 'p10-achtgeben-gebe-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.achtgeben'],
    familyId: 'p10-verb-achtgeben',
    instruction: 'Fiili çek — Dikkat ediyorum.',
    prompt: 'Ich ___ acht. (achtgeben)',
    answer: 'gebe',
    pronounce: ['Ich gebe acht.'],
  },

  /* ================================================================
   * gern soruları + fiil karışık görevler (6)
   * ================================================================ */
  {
    id: 'p10-achtgeben-mc-anlam',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.achtgeben'],
    familyId: 'p10-verb-achtgeben',
    instruction: '"achtgeben" ne demektir?',
    prompt: 'achtgeben',
    answer: 'dikkat etmek',
    options: ['dikkat etmek', 'sekiz saymak', 'beklemek', 'vermek'],
    pronounce: ['achtgeben'],
  },
  {
    id: 'p10-gern-machst-mc',
    day: 10, track: 'private', topicId: VER,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.verb.gern-sorular'],
    familyId: 'p10-verb-gern',
    instruction: '"Was machst du gern?" ne demektir?',
    prompt: 'Was machst du gern?',
    answer: 'Ne yapmayı seversin?',
    options: ['Ne yapmayı seversin?', 'Ne yapıyorsun?', 'Nereye gidiyorsun?', 'Ne seversin?'],
    pronounce: ['Was machst du gern?'],
  },
  {
    id: 'p10-gern-frueh-fill',
    day: 10, track: 'private', topicId: VER,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.verb.gern-sorular'],
    familyId: 'p10-verb-gern',
    instruction: 'Soruyu tamamla — Erken kalkmayı sever misin?',
    prompt: 'Stehst du gern früh ___?',
    answer: 'auf',
    validation: { noTypoTolerance: true },
    pronounce: ['Stehst du gern früh auf?'],
  },
  {
    id: 'p10-verb-match-prefix',
    day: 10, track: 'private', topicId: VER,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'private.day10.verb.aufstehen',
      'private.day10.verb.einkaufen',
      'private.day10.verb.fernsehen',
      'private.day10.verb.mitbringen',
      'private.day10.verb.zurueckkommen',
    ],
    familyId: 'p10-verb-prefix-match',
    instruction: 'Fiili ayrılan önekiyle eşleştir.',
    pairs: [
      { left: 'aufstehen', right: 'auf' },
      { left: 'einkaufen', right: 'ein' },
      { left: 'fernsehen', right: 'fern' },
      { left: 'mitbringen', right: 'mit' },
      { left: 'zurückkommen', right: 'zurück' },
    ],
    pronounce: ['aufstehen', 'einkaufen', 'fernsehen', 'mitbringen', 'zurückkommen'],
  },
  {
    id: 'p10-verb-error-anrufe',
    day: 10, track: 'private', topicId: VER,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day10.verb.anrufen-cumle'],
    familyId: 'p10-verb-error',
    instruction: 'Fiil bölünmemiş — cümleyi düzelt:',
    prompt: 'Ich anrufe dich.',
    answer: 'Ich rufe dich an.',
    explanation: '`anrufen` ayrılır: kök (`rufe`) ikinci sırada, önek (`an`) sondadır.',
    pronounce: ['Ich rufe dich an.'],
  },
  {
    id: 'p10-verb-builder-rufst',
    day: 10, track: 'private', topicId: VER,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.verb.anrufen-cumle'],
    familyId: 'p10-verb-builder',
    instruction: 'Cümleyi kur:',
    prompt: 'Beni arıyorsun.',
    answer: 'Du rufst mich an.',
    pronounce: ['Du rufst mich an.'],
  },

  /* ================================================================
   * Mein Tag — Sabah (8)
   * ================================================================ */
  {
    id: 'p10-sabah-match-rutin',
    day: 10, track: 'private', topicId: SAB,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: [
      'private.day10.sabah.gesicht',
      'private.day10.sabah.zaehne',
      'private.day10.sabah.duschen',
      'private.day10.verb.anziehen-chunk',
      'private.day10.sabah.fruehstuecken',
    ],
    familyId: 'p10-sabah-match',
    instruction: 'Sabah cümlesini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'Ich wasche mein Gesicht.', right: 'Yüzümü yıkarım.' },
      { left: 'Ich putze meine Zähne.', right: 'Dişlerimi fırçalarım.' },
      { left: 'Ich dusche.', right: 'Duş alırım.' },
      { left: 'Ich ziehe mich an.', right: 'Giyinirim.' },
      { left: 'Ich frühstücke.', right: 'Kahvaltı ederim.' },
    ],
    pronounce: ['Ich wasche mein Gesicht.', 'Ich putze meine Zähne.', 'Ich dusche.', 'Ich ziehe mich an.', 'Ich frühstücke.'],
  },
  {
    id: 'p10-sabah-gesicht-fill',
    day: 10, track: 'private', topicId: SAB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day10.sabah.gesicht'],
    familyId: 'p10-sabah-gesicht',
    instruction: 'Kelimeyi yaz — Yüzümü yıkıyorum.',
    prompt: 'Ich wasche mein ___. (yüz)',
    answer: 'Gesicht',
    pronounce: ['Ich wasche mein Gesicht.'],
  },
  {
    id: 'p10-sabah-zaehne-fill',
    day: 10, track: 'private', topicId: SAB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day10.sabah.zaehne'],
    familyId: 'p10-sabah-zaehne',
    instruction: 'Kelimeyi yaz — Dişlerimi fırçalıyorum.',
    prompt: 'Ich putze meine ___. (dişler)',
    answer: 'Zähne',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich putze meine Zähne.'],
  },
  {
    id: 'p10-sabah-dusche-mc',
    day: 10, track: 'private', topicId: SAB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.sabah.duschen'],
    familyId: 'p10-sabah-dusche',
    instruction: 'Günlük dilde kısası yeterlidir — hangisi?',
    prompt: 'Ich dusche mich. → günlük kısa biçim',
    answer: 'Ich dusche.',
    options: ['Ich dusche.', 'Ich dusche ein.', 'Ich dusche auf.', 'Ich dusche mich aus.'],
    pronounce: ['Ich dusche.'],
  },
  {
    id: 'p10-sabah-fruehstueck-fark-mc',
    day: 10, track: 'private', topicId: SAB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.sabah.fruehstueck-fark'],
    familyId: 'p10-sabah-fark',
    instruction: '"Frühstück machen" ne demektir?',
    prompt: 'Frühstück machen',
    answer: 'kahvaltı hazırlamak',
    options: ['kahvaltı hazırlamak', 'kahvaltı etmek', 'kahvaltı sipariş etmek', 'kahvaltıyı atlamak'],
    pronounce: ['Ich mache Frühstück.'],
  },
  {
    id: 'p10-sabah-fruehstuecke-free',
    day: 10, track: 'private', topicId: SAB,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.sabah.fruehstuecken'],
    familyId: 'p10-sabah-fruehstueck',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kahvaltı ediyorum. → ______',
    answer: 'Ich frühstücke.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich frühstücke.'],
  },
  {
    id: 'p10-sabah-mache-order',
    day: 10, track: 'private', topicId: SAB,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.sabah.fruehstueck-fark'],
    familyId: 'p10-sabah-mache',
    instruction: 'Kelimeleri doğru sıraya diz — Kahvaltı hazırlıyorum.',
    answer: 'Ich mache Frühstück.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich mache Frühstück.'],
  },
  {
    id: 'p10-sabah-wb-gesicht',
    day: 10, track: 'private', topicId: SAB,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.sabah.gesicht'],
    familyId: 'p10-sabah-gesicht-wb',
    instruction: 'Türkçeden Almancaya kur — Yüzümü yıkıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Yüzümü yıkıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'wasche' }, { id: 't3', text: 'mein' },
        { id: 't4', text: 'Gesicht.' }, { id: 't5', text: 'meine' }, { id: 't6', text: 'putze' },
      ],
      acceptedSequences: [['Ich', 'wasche', 'mein', 'Gesicht.']],
    },
    answer: 'Ich wasche mein Gesicht.',
    pronounce: ['Ich wasche mein Gesicht.'],
  },

  /* ================================================================
   * Mein Tag — Gün İçinde (8)
   * ================================================================ */
  {
    id: 'p10-gun-schule-fill',
    day: 10, track: 'private', topicId: GUN,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day10.gun.schule'],
    familyId: 'p10-gun-schule',
    instruction: 'Edatı yaz — Okula gidiyorum.',
    prompt: 'Ich gehe ___ Schule. (okula)',
    answer: 'zur',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich gehe zur Schule.'],
  },
  {
    id: 'p10-gun-lerne-order',
    day: 10, track: 'private', topicId: GUN,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.gun.lernen'],
    familyId: 'p10-gun-lerne',
    instruction: 'Kelimeleri doğru sıraya diz — Okulda Almanca ve Matematik öğreniyorum.',
    answer: 'Ich lerne Deutsch und Mathe in der Schule.',
    pronounce: ['Ich lerne Deutsch und Mathe in der Schule.'],
  },
  {
    id: 'p10-gun-mittag-mc',
    day: 10, track: 'private', topicId: GUN,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.gun.mittag'],
    familyId: 'p10-gun-mittag',
    instruction: 'Hangisi "Öğle yemeği yerim." demektir?',
    prompt: 'Öğle yemeği yerim.',
    answer: 'Ich esse zu Mittag.',
    options: ['Ich esse zu Mittag.', 'Ich esse zu Abend.', 'Ich esse zum Frühstück.', 'Ich trinke zu Mittag.'],
    pronounce: ['Ich esse zu Mittag.'],
  },
  {
    id: 'p10-gun-hausaufgaben-wb',
    day: 10, track: 'private', topicId: GUN,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.gun.hausaufgaben'],
    familyId: 'p10-gun-hausaufgaben',
    instruction: 'Türkçeden Almancaya kur — Ev ödevimi yapıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ev ödevimi yapıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'mache' }, { id: 't3', text: 'meine' },
        { id: 't4', text: 'Hausaufgaben.' }, { id: 't5', text: 'mein' }, { id: 't6', text: 'spiele' },
      ],
      acceptedSequences: [['Ich', 'mache', 'meine', 'Hausaufgaben.']],
    },
    answer: 'Ich mache meine Hausaufgaben.',
    pronounce: ['Ich mache meine Hausaufgaben.'],
  },
  {
    id: 'p10-gun-freunde-wb',
    day: 10, track: 'private', topicId: GUN,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.gun.freunde'],
    familyId: 'p10-gun-freunde',
    instruction: 'Türkçeden Almancaya kur — Arkadaşlarımla oynuyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Arkadaşlarımla oynuyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'spiele' }, { id: 't3', text: 'mit' },
        { id: 't4', text: 'meinen' }, { id: 't5', text: 'Freunden.' },
        { id: 't6', text: 'meiner' }, { id: 't7', text: 'meine' },
      ],
      acceptedSequences: [['Ich', 'spiele', 'mit', 'meinen', 'Freunden.']],
    },
    answer: 'Ich spiele mit meinen Freunden.',
    pronounce: ['Ich spiele mit meinen Freunden.'],
  },
  {
    id: 'p10-gun-meinen-fill',
    day: 10, track: 'private', topicId: GUN,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['private.day10.gun.freunde'],
    familyId: 'p10-gun-meinen',
    instruction: '`mit` Dativ ister — doğru biçimi yaz:',
    prompt: 'Ich spiele mit ___ Freunden. (benim)',
    answer: 'meinen',
    pronounce: ['Ich spiele mit meinen Freunden.'],
  },
  {
    id: 'p10-gun-dictation-lerne',
    day: 10, track: 'private', topicId: GUN,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.gun.lernen'],
    familyId: 'p10-gun-dictation',
    instruction: 'Duyduğun cümleyi aynen yaz:',
    audioText: 'Ich lerne Deutsch und Mathe in der Schule.',
    answer: 'Ich lerne Deutsch und Mathe in der Schule.',
    audio: { prompt: { text: 'Ich lerne Deutsch und Mathe in der Schule.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p10-gun-error-meiner',
    day: 10, track: 'private', topicId: GUN,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day10.gun.freunde'],
    familyId: 'p10-gun-error',
    instruction: 'İyelik biçimi yanlış — cümleyi düzelt:',
    prompt: 'Ich spiele mit meiner Freunden.',
    answer: 'Ich spiele mit meinen Freunden.',
    explanation: '`mit` Dativ ister; çoğulda `meinen Freunden` olur.',
    pronounce: ['Ich spiele mit meinen Freunden.'],
  },

  /* ================================================================
   * Mein Tag — Akşam (7)
   * ================================================================ */
  {
    id: 'p10-aksam-abendessen-fill',
    day: 10, track: 'private', topicId: AKS,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.aksam.abendessen'],
    familyId: 'p10-aksam-abendessen',
    instruction: 'Kelimeyi yaz — Saat dokuzda akşam yemeği yerim.',
    prompt: 'Ich esse um neun Uhr ___. (akşam yemeği)',
    answer: 'Abendessen',
    pronounce: ['Ich esse um neun Uhr Abendessen.'],
  },
  {
    id: 'p10-aksam-aus-order',
    day: 10, track: 'private', topicId: AKS,
    type: 'ordering', difficulty: 'easy', skill: 'production',
    conceptIds: ['private.day10.aksam.ausziehen'],
    familyId: 'p10-aksam-aus',
    instruction: 'Kelimeleri doğru sıraya diz — Üstümü çıkarıyorum.',
    answer: 'Ich ziehe mich aus.',
    pronounce: ['Ich ziehe mich aus.'],
  },
  {
    id: 'p10-aksam-buch-fill',
    day: 10, track: 'private', topicId: AKS,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day10.aksam.buch'],
    familyId: 'p10-aksam-buch',
    instruction: 'Artikeli yaz — Bir kitap okuyorum.',
    prompt: 'Ich lese ___ Buch. (bir)',
    answer: 'ein',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich lese ein Buch.'],
  },
  {
    id: 'p10-aksam-bett-order',
    day: 10, track: 'private', topicId: AKS,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.aksam.bett'],
    familyId: 'p10-aksam-bett',
    instruction: 'Kelimeleri doğru sıraya diz — Sonra yatağa gidiyorum.',
    answer: 'Danach gehe ich ins Bett.',
    pronounce: ['Danach gehe ich ins Bett.'],
  },
  {
    id: 'p10-aksam-spazieren-mc',
    day: 10, track: 'private', topicId: AKS,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.aksam.spazieren'],
    familyId: 'p10-aksam-spazieren',
    instruction: '"spazieren gehen" ne demektir?',
    prompt: 'spazieren gehen',
    answer: 'yürüyüş yapmak',
    options: ['yürüyüş yapmak', 'koşmak', 'eve dönmek', 'gezmek (arabayla)'],
    pronounce: ['spazieren gehen'],
  },
  {
    id: 'p10-aksam-error-buch',
    day: 10, track: 'private', topicId: AKS,
    type: 'error-correction', difficulty: 'medium', skill: 'correction',
    conceptIds: ['private.day10.aksam.buch'],
    familyId: 'p10-aksam-error',
    instruction: 'Artikel eksik — cümleyi düzelt:',
    prompt: 'Ich lese Buch.',
    answer: 'Ich lese ein Buch.',
    explanation: 'Sayılabilen tekil nesne artikel ister: `ein Buch`.',
    pronounce: ['Ich lese ein Buch.'],
  },
  {
    id: 'p10-aksam-free-buch',
    day: 10, track: 'private', topicId: AKS,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.aksam.buch'],
    familyId: 'p10-aksam-buch-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bir kitap okuyorum. → ______',
    answer: 'Ich lese ein Buch.',
    pronounce: ['Ich lese ein Buch.'],
  },
  /* ================================================================
   * Dann ve Danach (5)
   * ================================================================ */
  {
    id: 'p10-dann-fill',
    day: 10, track: 'private', topicId: DAN,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day10.dann.dann'],
    familyId: 'p10-dann-dann',
    instruction: 'Bağlacı yaz — Sonra okula gidiyorum.',
    prompt: '___ gehe ich zur Schule. (sonra)',
    answer: 'Dann',
    pronounce: ['Dann gehe ich zur Schule.'],
  },
  {
    id: 'p10-danach-fill',
    day: 10, track: 'private', topicId: DAN,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.dann.danach'],
    familyId: 'p10-dann-danach',
    instruction: 'Bağlacı yaz — Sonra eve geliyorum.',
    prompt: '___ komme ich nach Hause. (sonra)',
    answer: 'Danach',
    pronounce: ['Danach komme ich nach Hause.'],
  },
  {
    id: 'p10-dann-order',
    day: 10, track: 'private', topicId: DAN,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.dann.v2'],
    familyId: 'p10-dann-order',
    instruction: 'Kelimeleri doğru sıraya diz — Sonra eve geliyorum.',
    answer: 'Danach komme ich nach Hause.',
    pronounce: ['Danach komme ich nach Hause.'],
  },
  {
    id: 'p10-dann-error',
    day: 10, track: 'private', topicId: DAN,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day10.dann.v2'],
    familyId: 'p10-dann-error',
    instruction: 'Söz dizimi yanlış — cümleyi düzelt:',
    prompt: 'Danach ich komme nach Hause.',
    answer: 'Danach komme ich nach Hause.',
    explanation: '`Danach` başa gelirse fiil hemen arkasından ikinci sırada gelir.',
    pronounce: ['Danach komme ich nach Hause.'],
  },
  {
    id: 'p10-dann-alternatif-free',
    day: 10, track: 'private', topicId: DAN,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.dann.danach'],
    familyId: 'p10-dann-alternatif',
    instruction: 'İkinci dizilişi yaz — Sonra eve geliyorum (`danach` sonda).',
    prompt: 'Sonra eve geliyorum (danach sonda). → ______',
    answer: 'Ich komme danach nach Hause.',
    pronounce: ['Ich komme danach nach Hause.'],
  },

  /* ================================================================
   * Ayrılan / Ayrılmayan Karşılaştırması (5)
   * ================================================================ */
  {
    id: 'p10-karsi-mc-besuchen',
    day: 10, track: 'private', topicId: KAR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.karsi.besuchen'],
    familyId: 'p10-karsi-besuchen',
    instruction: 'Trennbar mı, değil mi?',
    prompt: 'besuchen — ayrılır mı?',
    answer: 'hayır, ayrılmaz',
    options: ['hayır, ayrılmaz', 'evet, ayrılır: be + suchen', 'sadece soruda ayrılır', 'sadece olumsuzda ayrılır'],
  },
  {
    id: 'p10-karsi-besuche-fill',
    day: 10, track: 'private', topicId: KAR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.karsi.besuchen'],
    familyId: 'p10-karsi-besuche',
    instruction: 'Fiili tek parça yaz — Seni ziyaret ediyorum.',
    prompt: 'Ich ___ dich. (besuchen)',
    answer: 'besuche',
    pronounce: ['Ich besuche dich.'],
  },
  {
    id: 'p10-karsi-error-be',
    day: 10, track: 'private', topicId: KAR,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day10.karsi.besuchen'],
    familyId: 'p10-karsi-error',
    instruction: 'Yanlış bölünmüş — cümleyi düzelt:',
    prompt: 'Ich suche dich be.',
    answer: 'Ich besuche dich.',
    explanation: '`besuchen` ayrılmaz; fiil tek parça kalır.',
    pronounce: ['Ich besuche dich.'],
  },
  {
    id: 'p10-karsi-prefix-mc',
    day: 10, track: 'private', topicId: KAR,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.karsi.ipucu'],
    familyId: 'p10-karsi-prefix',
    instruction: 'Hangisi bu derste geçen ayrılmayan başlangıçlardandır?',
    prompt: 'be- / emp- / er- / ver- / zer-',
    answer: 'ver- (vergessen)',
    options: ['ver- (vergessen)', 'an- (anrufen)', 'auf- (aufstehen)', 'mit- (mitbringen)'],
  },
  {
    id: 'p10-karsi-match-alti',
    day: 10, track: 'private', topicId: KAR,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'private.day10.karsi.besuchen',
      'private.day10.karsi.liste',
      'private.day10.karsi.ipucu',
    ],
    familyId: 'p10-karsi-match',
    instruction: 'Ayrılmayan fiili Türkçesiyle eşleştir.',
    pairs: [
      { left: 'besuchen', right: 'ziyaret etmek' },
      { left: 'empfinden', right: 'hissetmek' },
      { left: 'erklären', right: 'açıklamak' },
      { left: 'vergessen', right: 'unutmak' },
      { left: 'zerstören', right: 'tahrip etmek' },
      { left: 'zerreißen', right: 'yırtmak' },
    ],
    pronounce: ['besuchen', 'empfinden', 'erklären', 'vergessen', 'zerstören', 'zerreißen'],
  },

  /* ================================================================
   * Saat Kaç? — soru + birimler (5)
   * ================================================================ */
  {
    id: 'p10-uhr-frage-mc',
    day: 10, track: 'private', topicId: SOR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.soru.wie-spaet'],
    familyId: 'p10-uhr-frage',
    instruction: 'Hangisi "Saat kaç?" demektir?',
    prompt: 'Saat kaç?',
    answer: 'Wie spät ist es?',
    options: ['Wie spät ist es?', 'Wie viel Uhr stehst du auf?', 'Wann gehst du ins Bett?', 'Was machst du gern?'],
    pronounce: ['Wie spät ist es?'],
  },
  {
    id: 'p10-uhr-beide-mc',
    day: 10, track: 'private', topicId: SOR,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.soru.wie-viel'],
    familyId: 'p10-uhr-beide',
    instruction: '"Wie viel Uhr ist es?" ne demektir?',
    prompt: 'Wie viel Uhr ist es?',
    answer: 'Saat kaç?',
    options: ['Saat kaç?', 'Saat kaçta?', 'Ne zaman?', 'Kaç saat?'],
    pronounce: ['Wie viel Uhr ist es?'],
  },
  {
    id: 'p10-uhr-match-einheiten',
    day: 10, track: 'private', topicId: SOR,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.soru.einheiten'],
    familyId: 'p10-uhr-match',
    instruction: 'Saat kelimesini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'die Uhr', right: 'saat (alet)' },
      { left: 'die Stunde', right: 'saat (süre)' },
      { left: 'die Minute', right: 'dakika' },
      { left: 'die Sekunde', right: 'saniye' },
      { left: 'das Viertel', right: 'çeyrek' },
    ],
    pronounce: ['die Uhr', 'die Stunde', 'die Minute', 'die Sekunde'],
  },
  {
    id: 'p10-uhr-listen-frage',
    day: 10, track: 'private', topicId: SOR,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.soru.wie-spaet'],
    familyId: 'p10-uhr-listen',
    instruction: 'Duyduğun soruyu seç:',
    prompt: 'Wie spät ist es?',
    audioText: 'Wie spät ist es?',
    answer: 'Wie spät ist es?',
    options: ['Wie spät ist es?', 'Wie viel Uhr ist es?', 'Wann stehst du auf?', 'Was machst du gern?'],
    audio: { prompt: { text: 'Wie spät ist es?', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p10-uhr-de-tr-wb',
    day: 10, track: 'private', topicId: SOR,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.soru.wie-viel'],
    familyId: 'p10-uhr-de-tr',
    instruction: 'Almancadan Türkçeye kur — Saat kaç?',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Wie viel Uhr ist es?',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Saat' }, { id: 't2', text: 'kaç?' },
        { id: 't3', text: 'kaçta?' }, { id: 't4', text: 'Ne' },
      ],
      acceptedSequences: [['Saat', 'kaç?']],
    },
    answer: 'Saat kaç?',
    audio: { prompt: { text: 'Wie viel Uhr ist es?', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Wie viel Uhr ist es?'],
  },


  /* ================================================================
   * Resmî Saatler (5)
   * ================================================================ */

  {
    id: 'p10-resmi-de-tr-wb',
    day: 10, track: 'private', topicId: RES,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.resmi.ornek'],
    familyId: 'p10-resmi-de-tr',
    instruction: 'Almancadan Türkçeye kur — Saat yedi kırk.',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Es ist sieben Uhr vierzig.',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Saat' }, { id: 't2', text: 'yedi' }, { id: 't3', text: 'kırk.' },
        { id: 't4', text: 'yetmiş.' }, { id: 't5', text: 'yirmi.' },
      ],
      acceptedSequences: [['Saat', 'yedi', 'kırk.']],
    },
    answer: 'Saat yedi kırk.',
    audio: { prompt: { text: 'Es ist sieben Uhr vierzig.', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Es ist sieben Uhr vierzig.'],
  },
  {
    id: 'p10-resmi-zwanzig-fill',
    day: 10, track: 'private', topicId: RES,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['private.day10.resmi.kural'],
    familyId: 'p10-resmi-2035',
    instruction: 'Resmî okunuşu tamamla — 20:35:',
    prompt: 'Es ist ___ Uhr fünfunddreißig. (20:35)',
    answer: 'zwanzig',
    pronounce: ['Es ist zwanzig Uhr fünfunddreißig.'],
  },
  {
    id: 'p10-resmi-dictation-820',
    day: 10, track: 'private', topicId: RES,
    type: 'dictation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.resmi.ornek'],
    familyId: 'p10-resmi-dictation',
    instruction: 'Duyduğun resmî saati aynen yaz:',
    audioText: 'Es ist acht Uhr zwanzig.',
    answer: 'Es ist acht Uhr zwanzig.',
    audio: { prompt: { text: 'Es ist acht Uhr zwanzig.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p10-resmi-listen-740',
    day: 10, track: 'private', topicId: RES,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.resmi.kural'],
    familyId: 'p10-resmi-listen',
    instruction: 'Duyduğun resmî saati seç:',
    prompt: 'Es ist sieben Uhr vierzig.',
    audioText: 'Es ist sieben Uhr vierzig.',
    answer: 'Es ist sieben Uhr vierzig.',
    options: ['Es ist sieben Uhr vierzig.', 'Es ist sieben Uhr zwanzig.', 'Es ist acht Uhr vierzig.', 'Es ist halb acht.'],
    audio: { prompt: { text: 'Es ist sieben Uhr vierzig.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Günlük Saatler (6)
   * ================================================================ */

  {
    id: 'p10-gunluk-vor-fill',
    day: 10, track: 'private', topicId: GUL,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.gunluk.nach-vor'],
    familyId: 'p10-gunluk-vor',
    instruction: 'Doğru kelimeyi yaz — `von` DEĞİL:',
    prompt: 'Es ist zwanzig ___ vier. (kala)',
    answer: 'vor',
    validation: { noTypoTolerance: true },
    pronounce: ['Es ist zwanzig vor vier.'],
  },
  {
    id: 'p10-gunluk-viertel-mc',
    day: 10, track: 'private', topicId: GUL,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.gunluk.viertel'],
    familyId: 'p10-gunluk-viertel',
    instruction: '18:15 günlük konuşmada nasıldır?',
    prompt: '18:15 → günlük',
    answer: 'Es ist Viertel nach sechs.',
    options: ['Es ist Viertel nach sechs.', 'Es ist Viertel vor sechs.', 'Es ist halb sieben.', 'Es ist sechs Uhr fünfzehn.'],
    pronounce: ['Es ist Viertel nach sechs.'],
  },
  {
    id: 'p10-gunluk-formal-mc',
    day: 10, track: 'private', topicId: GUL,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day10.gunluk.nach-vor', 'private.day10.resmi.kural'],
    familyId: 'p10-gunluk-formal',
    instruction: '"Es ist zwanzig nach fünf." — resmî karşılığı?',
    prompt: 'Es ist zwanzig nach fünf. → resmî',
    answer: 'Es ist siebzehn Uhr zwanzig.',
    options: ['Es ist siebzehn Uhr zwanzig.', 'Es ist fünf Uhr zwanzig.', 'Es ist siebzehn Uhr fünfzig.', 'Es ist halb sechs.'],
    pronounce: ['Es ist siebzehn Uhr zwanzig.'],
  },
  {
    id: 'p10-gunluk-informal-free',
    day: 10, track: 'private', topicId: GUL,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.gunluk.nach-vor'],
    familyId: 'p10-gunluk-informal',
    instruction: 'Günlük biçimiyle yaz:',
    prompt: '15:40 → günlük ______',
    answer: 'Es ist zwanzig vor vier.',
    pronounce: ['Es ist zwanzig vor vier.'],
  },
  {
    id: 'p10-gunluk-viertel-vor-mc',
    day: 10, track: 'private', topicId: GUL,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.gunluk.viertel'],
    familyId: 'p10-gunluk-viertel-vor',
    instruction: '20:45 günlük konuşmada nasıldır?',
    prompt: '20:45 → günlük',
    answer: 'Es ist Viertel vor neun.',
    options: ['Es ist Viertel vor neun.', 'Es ist Viertel nach neun.', 'Es ist halb neun.', 'Es ist zwanzig Uhr fünfundvierzig.'],
    pronounce: ['Es ist Viertel vor neun.'],
  },

  /* ================================================================
   * halb / Viertel / vor / nach (5)
   * ================================================================ */
  {
    id: 'p10-halb-mc-anlam',
    day: 10, track: 'private', topicId: HAL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.halb.anlam'],
    familyId: 'p10-halb-anlam',
    instruction: '"halb acht" — saat kaç?',
    prompt: 'halb acht = ?',
    answer: '07:30',
    options: ['07:30', '08:30', '06:30', '08:00'],
    pronounce: ['halb acht'],
  },
  {
    id: 'p10-halb-sechs-fill',
    day: 10, track: 'private', topicId: HAL,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.halb.ornek'],
    familyId: 'p10-halb-sechs',
    instruction: 'Doğru saati yaz — 05:30:',
    prompt: 'Es ist halb ___. (05:30)',
    answer: 'sechs',
    pronounce: ['Es ist halb sechs.'],
  },
  {
    id: 'p10-halb-zehn-free',
    day: 10, track: 'private', topicId: HAL,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.halb.ornek'],
    familyId: 'p10-halb-zehn',
    instruction: 'Almancasını yaz:',
    prompt: '09:30 → ______',
    answer: 'Es ist halb zehn.',
    pronounce: ['Es ist halb zehn.'],
  },
  {
    id: 'p10-halb-error-sieben',
    day: 10, track: 'private', topicId: HAL,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day10.halb.anlam'],
    familyId: 'p10-halb-error',
    instruction: 'Yanlış saati düzelt — 07:30:',
    prompt: 'Es ist halb sieben.',
    answer: 'Es ist halb acht.',
    explanation: '`halb` her zaman bir sonrakini söyler: 07:30 = `halb acht`.',
    pronounce: ['Es ist halb acht.'],
  },
  {
    id: 'p10-halb-dictation-acht',
    day: 10, track: 'private', topicId: HAL,
    type: 'dictation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.halb.ornek'],
    familyId: 'p10-halb-dictation',
    instruction: 'Duyduğun saati aynen yaz:',
    audioText: 'Es ist halb acht.',
    answer: 'Es ist halb acht.',
    audio: { prompt: { text: 'Es ist halb acht.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * um ile Saat Söylemek (4)
   * ================================================================ */
  {
    id: 'p10-um-mc-fark',
    day: 10, track: 'private', topicId: UMU,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.um.kural'],
    familyId: 'p10-um-fark',
    instruction: '"Ich stehe um sieben Uhr auf." ne demektir?',
    prompt: 'um sieben Uhr = ?',
    answer: 'saat yedide',
    options: ['saat yedide', 'saat yedi', 'yedi saat', 'yediye kadar'],
    pronounce: ['um sieben Uhr'],
  },
  {
    id: 'p10-um-wb-inversion',
    day: 10, track: 'private', topicId: UMU,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.um.ornek', 'private.day10.trennbar.saat-basta'],
    familyId: 'p10-um-inversion',
    instruction: 'Türkçeden Almancaya kur — Saat yedide kalkıyorum (saat başta).',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Saat yedide kalkıyorum (saat başta).',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Um' }, { id: 't2', text: 'sieben' }, { id: 't3', text: 'Uhr' },
        { id: 't4', text: 'stehe' }, { id: 't5', text: 'ich' }, { id: 't6', text: 'auf.' },
        { id: 't7', text: 'Ich' }, { id: 't8', text: 'um' },
      ],
      acceptedSequences: [['Um', 'sieben', 'Uhr', 'stehe', 'ich', 'auf.']],
    },
    answer: 'Um sieben Uhr stehe ich auf.',
    pronounce: ['Um sieben Uhr stehe ich auf.'],
  },
  {
    id: 'p10-um-error-ohne',
    day: 10, track: 'private', topicId: UMU,
    type: 'error-correction', difficulty: 'medium', skill: 'correction',
    conceptIds: ['private.day10.um.kural'],
    familyId: 'p10-um-error',
    instruction: '`um` eksik — cümleyi düzelt:',
    prompt: 'Ich stehe sieben Uhr auf.',
    answer: 'Ich stehe um sieben Uhr auf.',
    explanation: 'Rutinde saat `um` ile bağlanır: `um sieben Uhr` = saat yedide.',
    pronounce: ['Ich stehe um sieben Uhr auf.'],
  },
  {
    id: 'p10-um-free-sieben',
    day: 10, track: 'private', topicId: UMU,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.um.ornek'],
    familyId: 'p10-um-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Saat yedide kalkıyorum. → ______',
    answer: 'Ich stehe um sieben Uhr auf.',
    pronounce: ['Ich stehe um sieben Uhr auf.'],
  },

  /* ================================================================
   * Karışık: saat + ayrılabilen fiil (6)
   * ================================================================ */
  {
    id: 'p10-mix-wb-wache-sieben',
    day: 10, track: 'private', topicId: TAM,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.verb.aufwachen', 'private.day10.um.ornek'],
    familyId: 'p10-mix-wache',
    instruction: 'Türkçeden Almancaya kur — Saat yedide uyanıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Saat yedide uyanıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'wache' }, { id: 't3', text: 'um' },
        { id: 't4', text: 'sieben' }, { id: 't5', text: 'Uhr' }, { id: 't6', text: 'auf.' },
        { id: 't7', text: 'stehe' }, { id: 't8', text: 'an.' },
      ],
      acceptedSequences: [['Ich', 'wache', 'um', 'sieben', 'Uhr', 'auf.']],
    },
    answer: 'Ich wache um sieben Uhr auf.',
    explanation: 'uyanmak = aufwachen (gözlerini açmak); kalkmak = aufstehen (yataktan kalkmak). `stehe` ile kurulan cümle dilbilgisi olarak doğrudur ama "kalkıyorum" demektir.',
    pronounce: ['Ich wache um sieben Uhr auf.'],
  },
  {
    id: 'p10-mix-fernsehen-20-free',
    day: 10, track: 'private', topicId: TAM,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.verb.fernsehen-cumle', 'private.day10.um.ornek'],
    familyId: 'p10-mix-fernsehen',
    instruction: 'Saat + fiil — 20:00 televizyon izliyorum:',
    prompt: '20:00 + fernsehen → ______',
    answer: 'Ich sehe um acht Uhr fern.',
    pronounce: ['Ich sehe um acht Uhr fern.'],
  },
  {
    id: 'p10-mix-heim-16-order',
    day: 10, track: 'private', topicId: TAM,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.verb.zurueckkommen', 'private.day10.um.kural'],
    familyId: 'p10-mix-heim',
    instruction: 'Kelimeleri doğru sıraya diz — Saat dörtte eve geri dönüyorum.',
    answer: 'Um vier Uhr komme ich nach Hause zurück.',
    validation: { keyboardTolerance: true },
    pronounce: ['Um vier Uhr komme ich nach Hause zurück.'],
  },
  {
    id: 'p10-mix-builder-abend-neun',
    day: 10, track: 'private', topicId: TAM,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.aksam.abendessen'],
    familyId: 'p10-mix-builder',
    instruction: 'Cümleyi kur:',
    prompt: 'Akşam yemeğini saat dokuzda yerim.',
    answer: 'Ich esse um neun Uhr Abendessen.',
    pronounce: ['Ich esse um neun Uhr Abendessen.'],
  },
  {
    id: 'p10-mix-match-zaman',
    day: 10, track: 'private', topicId: TAM,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'private.day10.verb.aufstehen',
      'private.day10.gun.mittag',
      'private.day10.aksam.abendessen',
      'private.day10.aksam.bett',
    ],
    familyId: 'p10-mix-match',
    instruction: 'Rutin cümlesini saatiyle eşleştir.',
    pairs: [
      { left: 'Ich stehe auf.', right: 'um sieben Uhr' },
      { left: 'Ich esse zu Mittag.', right: 'um zwölf Uhr' },
      { left: 'Ich esse Abendessen.', right: 'um neun Uhr' },
      { left: 'Ich gehe ins Bett.', right: 'um zehn Uhr' },
    ],
    pronounce: ['um sieben Uhr', 'um zwölf Uhr', 'um neun Uhr', 'um zehn Uhr'],
  },
  {
    id: 'p10-mix-dictation-tag',
    day: 10, track: 'private', topicId: TAM,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day10.um.ornek'],
    familyId: 'p10-mix-dictation',
    instruction: 'Duyduğun rutin cümlesini aynen yaz:',
    audioText: 'Ich stehe um sieben Uhr auf.',
    answer: 'Ich stehe um sieben Uhr auf.',
    audio: { prompt: { text: 'Ich stehe um sieben Uhr auf.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Küçük tekrar: oda / tanım kelimeleri (5)
   * ================================================================ */
  {
    id: 'p10-rev-ruhig-mc',
    day: 10, track: 'private', topicId: WOR,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day10.wort.ruhig'],
    familyId: 'p10-rev-ruhig',
    instruction: '"ruhig" ne demektir?',
    prompt: 'ruhig',
    answer: 'sessiz, sakin',
    options: ['sessiz, sakin', 'gürültülü', 'kalabalık', 'hızlı'],
    pronounce: ['ruhig'],
  },
  {
    id: 'p10-rev-beide-fill',
    day: 10, track: 'private', topicId: WOR,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day10.wort.beide'],
    familyId: 'p10-rev-beide',
    instruction: 'Türkçesini yaz:',
    prompt: 'beide = ___',
    answer: 'ikisi de',
  },
  {
    id: 'p10-rev-quadrat-fill',
    day: 10, track: 'private', topicId: WOR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day10.wort.zimmer-satz'],
    familyId: 'p10-rev-quadrat',
    instruction: 'Kelimeyi yaz — Oda on metrekare.',
    prompt: 'Das Zimmer ist zehn ___ groß. (metrekare)',
    answer: 'Quadratmeter',
    pronounce: ['Das Zimmer ist zehn Quadratmeter groß.'],
  },
  {
    id: 'p10-rev-kosten-wb',
    day: 10, track: 'private', topicId: WOR,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day10.wort.kosten'],
    familyId: 'p10-rev-kosten',
    instruction: 'Türkçeden Almancaya kur — Ayda sadece 180 euro.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ayda sadece 180 euro.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Es' }, { id: 't2', text: 'kostet' }, { id: 't3', text: 'nur' },
        { id: 't4', text: '180' }, { id: 't5', text: 'Euro' }, { id: 't6', text: 'im' },
        { id: 't7', text: 'Monat.' }, { id: 't8', text: 'teuer' },
      ],
      acceptedSequences: [['Es', 'kostet', 'nur', '180', 'Euro', 'im', 'Monat.']],
    },
    answer: 'Es kostet nur 180 Euro im Monat.',
    pronounce: ['Es kostet nur 180 Euro im Monat.'],
  },
  {
    id: 'p10-rev-ziemlich-mc',
    day: 10, track: 'private', topicId: WOR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day10.wort.ziemlich', 'private.day10.wort.frueh-lange', 'private.day10.wort.badewanne'],
    familyId: 'p10-rev-kelime',
    instruction: 'Hangisi "oldukça" demektir?',
    prompt: 'oldukça',
    answer: 'ziemlich',
    options: ['ziemlich', 'ruhig', 'früh', 'beide'],
    pronounce: ['ziemlich'],
  },
  {
    id: 'p10-rev-match-klein',
    day: 10, track: 'private', topicId: WOR,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: [
      'private.day10.wort.ruhig',
      'private.day10.wort.beide',
      'private.day10.wort.badewanne',
      'private.day10.wort.ziemlich',
      'private.day10.wort.frueh-lange',
    ],
    familyId: 'p10-rev-match',
    instruction: 'Tekrar kelimesini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'ruhig', right: 'sessiz' },
      { left: 'beide', right: 'ikisi de' },
      { left: 'die Badewanne', right: 'küvet' },
      { left: 'ziemlich', right: 'oldukça' },
      { left: 'lange', right: 'uzun' },
    ],
    pronounce: ['ruhig', 'die Badewanne', 'ziemlich'],
  },

  /* ================================================================
   * Mein Tag — Tam Anlatım (4)
   * ================================================================ */
  {
    id: 'p10-tam-free-dort-satir',
    day: 10, track: 'private', topicId: TAM,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [
      'private.day10.tam.model',
      'private.day10.sabah.zaehne',
      'private.day10.sabah.fruehstuecken',
    ],
    familyId: 'p10-tam-dort',
    openEnded: true,
    instruction: 'Sabah rutinini dört cümleyle yaz — ipuçları aşağıda.',
    prompt: 'uyanmak:\nkalkmak:\ndişler:\nkahvaltı:',
    hint: 'Her cümlede ayrılabilen fiilin öneki sonda olsun.',
    answer: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Ich putze meine Zähne. Ich frühstücke.',
    explanation: 'Kısa model: dört sabah cümlesi, her önek cümlenin sonunda.',
    pronounce: ['Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf.'],
  },
  {
    id: 'p10-tam-free-sekiz-satir',
    day: 10, track: 'private', topicId: TAM,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [
      'private.day10.tam.model',
      'private.day10.gun.hausaufgaben',
      'private.day10.gun.freunde',
      'private.day10.aksam.bett',
    ],
    familyId: 'p10-tam-sekiz',
    openEnded: true,
    instruction: 'Gününü sekiz cümleyle yaz — ipuçları aşağıda.',
    prompt: 'uyanmak:\nkalkmak:\nkahvaltı:\nokul:\nöğle:\nödev:\nakşam:\nyatak:',
    hint: '`Dann` ve `Danach` ile bağla; saatleri `um` ile söyle.',
    answer: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Ich frühstücke. Dann gehe ich zur Schule. Ich esse zu Mittag. Ich mache meine Hausaufgaben. Ich esse um neun Uhr Abendessen. Danach gehe ich ins Bett.',
    explanation: 'Orta model: sekiz cümle, bağlaçlar ve saatlerle.',
    pronounce: ['Dann gehe ich zur Schule. Danach gehe ich ins Bett.'],
  },
  {
    id: 'p10-meintag-free-tam-anlatim',
    day: 10, track: 'private', topicId: TAM,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [
      'private.day10.tam.uretim',
      'private.day10.tam.model',
      'private.day10.tam.sablon',
      'private.day10.gun.hausaufgaben',
      'private.day10.aksam.bett',
    ],
    familyId: 'p10-tam-anlatim',
    openEnded: true,
    instruction: 'Gününü Almanca anlat (Erzähle deinen Tag.). En az on iki cümle yaz — ipuçları aşağıda.',
    prompt: 'Aufstehen:\nFrühstück:\nSchule:\nMittagessen:\nNach Hause:\nHausaufgaben:\nFreunde:\nAbendessen:\nBett:',
    hint: 'Kopya iskelet: `Ich stehe um ... Uhr auf. Dann ... Danach ... Ich gehe ... Ich komme ... Ich mache ... Ich esse ... Am Abend ... Danach gehe ich ins Bett.`',
    answer: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Ich wasche mein Gesicht. Ich putze meine Zähne. Ich dusche. Ich ziehe mich an. Ich frühstücke. Dann gehe ich zur Schule. Ich lerne Deutsch und Mathe in der Schule. Ich esse zu Mittag. Danach komme ich nach Hause zurück. Ich mache meine Hausaufgaben. Dann spiele ich mit meinen Freunden. Ich esse um neun Uhr Abendessen. Ich ziehe mich aus. Danach gehe ich ins Bett.',
    explanation: 'Kanonik A1 model: 16 kısa cümle, ayrılabilen fiiller + `dann/danach` + `um` saatleri.',
    pronounce: ['Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Dann gehe ich zur Schule.'],
  },
  {
    id: 'p10-tam-spoken-tam',
    day: 10, track: 'private', topicId: TAM,
    type: 'spoken', difficulty: 'hard', skill: 'speaking',
    conceptIds: ['private.day10.tam.uretim', 'private.day10.tam.model', 'private.day10.um.ornek'],
    familyId: 'p10-tam-spoken',
    instruction: 'İpuçlarına bakmadan gününü baştan sona sesli anlat.',
    requirements: [
      'En az on iki cümle kur.',
      'En az beş ayrılabilen fiil kullan.',
      'Saatleri `um` ile söyle, cümleleri `dann/danach` ile bağla.',
    ],
    sampleAnswer: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Ich wasche mein Gesicht. Ich putze meine Zähne. Ich dusche. Ich ziehe mich an. Ich frühstücke. Dann gehe ich zur Schule. Ich esse zu Mittag. Danach komme ich nach Hause zurück. Ich mache meine Hausaufgaben. Ich esse um neun Uhr Abendessen. Ich ziehe mich aus. Danach gehe ich ins Bett.',
    audio: { targets: [{ text: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Dann gehe ich zur Schule. Danach komme ich nach Hause zurück.', language: 'de-DE', role: 'example' }] },
  },
];
