/**
 * Özel Ders — 5. Gün — yazılmış alıştırma havuzu.
 *
 * Kaynak: öğrencinin el yazısı defter sayfaları — `leben` fiili, sayılar
 * (10–1000 ve bileşik sayı mantığı), kişisel bilgi formu alanları, doğum
 * yeri/köken/ikamet ayrımı, `Familienstand`, genişletilmiş kendini tanıtma,
 * `und/aber` bağlaçları, yeni kelimeler ve yiyecek kelime dağarcığı.
 *
 * Kaynak düzeltmeleri (kanonik Almanca korunmuştur):
 *   - "54 → fünf und Vierzig" el yazısı hatası: bu aslında 45 (fünfundvierzig)
 *     demektir. 54'ün doğru Almancası `vierundfünfzig`dir (birler + und + onlar).
 *   - "205 → zweihundertund fünf": standart yazımda `hundert`den sonra `und`
 *     kullanılmaz → `zweihundertfünf`.
 *   - "Cufthorsa = havaalanı" (okunaksız el yazısı): Türkçe anlamı ("havaalanı")
 *     açık olduğundan kanonik Almanca karşılığı `der Flughafen` olarak yazıldı.
 *   - "achtzen" öğrenci tarafından kendi yazısında `achtzehn` olarak düzeltilmiş;
 *     kanonik biçim `achtzehn` kullanıldı.
 *
 * Tüm kavramlar concepts.ts içindeki private.day5.* kavramlarına bağlıdır;
 * özet kapsamı Özel Ders Özet.md üzerinden doğrulanır.
 */

import type { AuthoredExercise } from '../types.ts';

const HED = 'private.day5.hedef';
const LEB = 'private.day5.leben';
const SON = 'private.day5.sayilar-onluklar';
const SYU = 'private.day5.sayilar-yuzler';
const KB = 'private.day5.kisisel-bilgiler';
const DY = 'private.day5.dogum-yeri';
const MH = 'private.day5.medeni-hal';
const KT = 'private.day5.kendini-tanitma';
const BAG = 'private.day5.baglaclar';
const KEL = 'private.day5.kelimeler';
const YEM = 'private.day5.yiyecek';

export const PRIVATE_DAY5_EXERCISES: AuthoredExercise[] = [
  /* ================================================================
   * Bugünün Hedefi (1)
   * ================================================================ */
  {
    id: 'p5-hed-giris-mc',
    day: 5, track: 'private', topicId: HED,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.hedef.giris'],
    familyId: 'p5-hed-giris',
    instruction: '5. Günün hedefi nedir?',
    prompt: '5. Gün ne üzerine kuruludur?',
    answer: 'leben fiili, sayılar ve kişisel bilgi formu',
    options: [
      'leben fiili, sayılar ve kişisel bilgi formu',
      'Sadece yeni kelime ezberlemek',
      'Sadece dinleme yapmak',
      'Sadece geçmiş zaman',
    ],
  },

  /* ================================================================
   * leben — Yaşamak (12)
   * ================================================================ */
  {
    id: 'p5-leb-anlam-mc',
    day: 5, track: 'private', topicId: LEB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.leben.anlam'],
    familyId: 'p5-leb-anlam',
    instruction: '"leben" ne demektir?',
    prompt: 'leben',
    answer: 'yaşamak',
    options: ['yaşamak', 'gitmek', 'gelmek', 'çalışmak'],
    pronounce: ['leben'],
  },
  {
    id: 'p5-leb-ich-mc',
    day: 5, track: 'private', topicId: LEB,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.leben.cekim'],
    familyId: 'p5-leb-ich',
    instruction: 'leben çekimi — doğru formu seç:',
    prompt: 'ich ___ (leben)',
    answer: 'lebe',
    options: ['lebe', 'lebst', 'lebt', 'leben'],
    pronounce: ['ich lebe'],
  },
  {
    id: 'p5-leb-du-fill',
    day: 5, track: 'private', topicId: LEB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day5.leben.cekim'],
    familyId: 'p5-leb-du',
    instruction: 'leben çekimi:',
    prompt: 'du ___ (leben)',
    answer: 'lebst',
    pronounce: ['du lebst'],
  },
  {
    id: 'p5-leb-er-fill',
    day: 5, track: 'private', topicId: LEB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day5.leben.cekim'],
    familyId: 'p5-leb-er',
    instruction: 'leben çekimi:',
    prompt: 'er / sie / es ___ (leben)',
    answer: 'lebt',
    pronounce: ['er lebt'],
  },
  {
    id: 'p5-leb-wir-mc',
    day: 5, track: 'private', topicId: LEB,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.leben.cekim'],
    familyId: 'p5-leb-wir',
    instruction: 'leben çekimi — doğru formu seç:',
    prompt: 'wir ___ (leben)',
    answer: 'leben',
    options: ['leben', 'lebt', 'lebst', 'lebe'],
    pronounce: ['wir leben'],
  },
  {
    id: 'p5-leb-ihr-fill',
    day: 5, track: 'private', topicId: LEB,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day5.leben.cekim'],
    familyId: 'p5-leb-ihr',
    instruction: 'leben çekimi:',
    prompt: 'ihr ___ (leben)',
    answer: 'lebt',
    pronounce: ['ihr lebt'],
  },
  {
    id: 'p5-leb-sie-mc',
    day: 5, track: 'private', topicId: LEB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.leben.cekim'],
    familyId: 'p5-leb-sie',
    instruction: 'leben çekimi — doğru formu seç:',
    prompt: 'sie / Sie ___ (leben)',
    answer: 'leben',
    options: ['leben', 'lebt', 'lebst', 'lebe'],
    pronounce: ['sie leben'],
  },
  {
    id: 'p5-leb-deutschland-fill',
    day: 5, track: 'private', topicId: LEB,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.leben.wohnen-farki'],
    familyId: 'p5-leb-deutschland',
    instruction: 'Boşluğu doldur (genel yaşam — leben):',
    prompt: 'Ich ___ in Deutschland. (Almanya\'da yaşıyorum)',
    answer: 'lebe',
    pronounce: ['Ich lebe in Deutschland.'],
  },
  {
    id: 'p5-leb-berlin-fill',
    day: 5, track: 'private', topicId: LEB,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.leben.wohnen-farki'],
    familyId: 'p5-leb-berlin',
    instruction: 'Boşluğu doldur (somut ikamet — wohnen):',
    prompt: 'Ich ___ in Berlin. (Berlin\'de oturuyorum)',
    answer: 'wohne',
    pronounce: ['Ich wohne in Berlin.'],
  },
  {
    id: 'p5-leb-farki-mc',
    day: 5, track: 'private', topicId: LEB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.leben.wohnen-farki'],
    familyId: 'p5-leb-farki',
    instruction: '"leben" ile "wohnen" arasındaki pratik fark nedir?',
    prompt: 'leben ↔ wohnen',
    answer: 'leben genel yaşamı, wohnen somut ikameti (adres/şehir) anlatır',
    options: [
      'leben genel yaşamı, wohnen somut ikameti (adres/şehir) anlatır',
      'İkisi de tamamen farklı anlama gelir, hiç ilgileri yoktur',
      'leben sadece geçmiş zamanda kullanılır',
      'wohnen sadece ülkeler için kullanılır',
    ],
  },
  {
    id: 'p5-leb-error-lebst',
    day: 5, track: 'private', topicId: LEB,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day5.leben.cekim'],
    familyId: 'p5-leb-error',
    instruction: 'Hata avı — çekim yanlış:',
    prompt: 'Ich lebst in der Türkei.',
    answer: 'Ich lebe in der Türkei.',
    explanation: '"ich" ile fiil `-e` eki alır (ich lebe); `-st` eki "du" için kullanılır.',
    pronounce: ['Ich lebe in der Türkei.'],
  },
  {
    id: 'p5-leb-listen-deutschland',
    day: 5, track: 'private', topicId: LEB,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.leben.wohnen-farki'],
    familyId: 'p5-leb-listen',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich lebe in Deutschland.',
    audioText: 'Ich lebe in Deutschland.',
    answer: 'Ich lebe in Deutschland.',
    options: [
      'Ich lebe in Deutschland.',
      'Ich wohne in Berlin.',
      'Ich komme aus Deutschland.',
      'Ich bin in Deutschland geboren.',
    ],
    audio: { prompt: { text: 'Ich lebe in Deutschland.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Sayılar 10–100 (25)
   * ================================================================ */
  {
    id: 'p5-son-elf-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day5.sayilar.onlu-sayilar'],
    familyId: 'p5-son-elf',
    instruction: 'Almanca yaz:',
    prompt: '11 → ___',
    answer: 'elf',
    pronounce: ['elf'],
  },
  {
    id: 'p5-son-dreizehn-mc',
    day: 5, track: 'private', topicId: SON,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.onlu-sayilar'],
    familyId: 'p5-son-dreizehn',
    instruction: 'Doğru Almancasını seç:',
    prompt: '13',
    answer: 'dreizehn',
    options: ['dreizehn', 'vierzehn', 'dreißig', 'drei'],
    pronounce: ['dreizehn'],
  },
  {
    id: 'p5-son-sechzehn-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day5.sayilar.onlu-sayilar'],
    familyId: 'p5-son-sechzehn',
    instruction: 'Almanca yaz (istisna: sechs → sech):',
    prompt: '16 → ___',
    answer: 'sechzehn',
    pronounce: ['sechzehn'],
  },
  {
    id: 'p5-son-siebzehn-mc',
    day: 5, track: 'private', topicId: SON,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.onlu-sayilar'],
    familyId: 'p5-son-siebzehn',
    instruction: 'Doğru Almancasını seç (istisna: sieben → sieb):',
    prompt: '17',
    answer: 'siebzehn',
    options: ['siebzehn', 'siebenzehn', 'siebzig', 'sieben'],
    pronounce: ['siebzehn'],
  },
  {
    id: 'p5-son-teens-sequence-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day5.sayilar.onlu-sayilar'],
    familyId: 'p5-son-teens-sequence',
    instruction: 'Diziyi tamamla:',
    prompt: 'elf, zwölf, ___, vierzehn',
    answer: 'dreizehn',
    pronounce: ['dreizehn'],
  },
  {
    id: 'p5-son-zwanzig-mc',
    day: 5, track: 'private', topicId: SON,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.onluklar'],
    familyId: 'p5-son-zwanzig',
    instruction: 'Doğru Almancasını seç:',
    prompt: '20',
    answer: 'zwanzig',
    options: ['zwanzig', 'zehn', 'zwölf', 'zwei'],
    pronounce: ['zwanzig'],
  },
  {
    id: 'p5-son-dreissig-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day5.sayilar.onluklar'],
    familyId: 'p5-son-dreissig',
    instruction: 'Almanca yaz (ß ile):',
    prompt: '30 → ___',
    answer: 'dreißig',
    validation: { keyboardTolerance: true },
    pronounce: ['dreißig'],
  },
  {
    id: 'p5-son-error-dreissig',
    day: 5, track: 'private', topicId: SON,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day5.sayilar.onluklar'],
    familyId: 'p5-son-error-dreissig',
    instruction: 'Hata avı — yazım:',
    prompt: '30 = dreissig',
    answer: '30 = dreißig',
    explanation: '30 her zaman `ß` harfiyle yazılır: `dreißig`, `dreissig` değil.',
    pronounce: ['dreißig'],
  },
  {
    id: 'p5-son-tens-sequence-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day5.sayilar.onluklar'],
    familyId: 'p5-son-tens-sequence',
    instruction: 'Diziyi tamamla:',
    prompt: 'zwanzig, dreißig, vierzig, ___, sechzig',
    answer: 'fünfzig',
    pronounce: ['fünfzig'],
  },
  {
    id: 'p5-son-sechzig-mc',
    day: 5, track: 'private', topicId: SON,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.onluklar'],
    familyId: 'p5-son-sechzig',
    instruction: 'Doğru Almancasını seç (istisna: sechs → sech):',
    prompt: '60',
    answer: 'sechzig',
    options: ['sechzig', 'sechszig', 'sechs', 'sechzehn'],
    pronounce: ['sechzig'],
  },
  {
    id: 'p5-son-25-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'easy', skill: 'production',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-25',
    instruction: 'Almanca yaz (birler + und + onlar):',
    prompt: '25 → ___',
    answer: 'fünfundzwanzig',
    pronounce: ['fünfundzwanzig'],
  },
  {
    id: 'p5-son-46-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-46',
    instruction: 'Almanca yaz:',
    prompt: '46 → ___',
    answer: 'sechsundvierzig',
    pronounce: ['sechsundvierzig'],
  },
  {
    id: 'p5-son-94-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-94',
    instruction: 'Almanca yaz:',
    prompt: '94 → ___',
    answer: 'vierundneunzig',
    pronounce: ['vierundneunzig'],
  },
  {
    id: 'p5-son-83-mc',
    day: 5, track: 'private', topicId: SON,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-83',
    instruction: 'Doğru Almancasını seç:',
    prompt: '83',
    answer: 'dreiundachtzig',
    options: ['dreiundachtzig', 'achtunddreißig', 'dreißigundacht', 'achtzigunddrei'],
    pronounce: ['dreiundachtzig'],
  },
  {
    id: 'p5-son-96-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-96',
    instruction: 'Almanca yaz:',
    prompt: '96 → ___',
    answer: 'sechsundneunzig',
    pronounce: ['sechsundneunzig'],
  },
  {
    id: 'p5-son-79-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-79',
    instruction: 'Almanca yaz:',
    prompt: '79 → ___',
    answer: 'neunundsiebzig',
    pronounce: ['neunundsiebzig'],
  },
  {
    id: 'p5-son-87-mc',
    day: 5, track: 'private', topicId: SON,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-87',
    instruction: 'Doğru Almancasını seç:',
    prompt: '87',
    answer: 'siebenundachtzig',
    options: ['siebenundachtzig', 'achtundsiebzig', 'siebzigundacht', 'achtzigundsieben'],
    pronounce: ['siebenundachtzig'],
  },
  {
    id: 'p5-son-65-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'easy', skill: 'production',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-65',
    instruction: 'Almanca yaz:',
    prompt: '65 → ___',
    answer: 'fünfundsechzig',
    pronounce: ['fünfundsechzig'],
  },
  {
    id: 'p5-son-54-fill',
    day: 5, track: 'private', topicId: SON,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-54',
    instruction: 'Almanca yaz (dikkat — sıra):',
    prompt: '54 → ___',
    answer: 'vierundfünfzig',
    pronounce: ['vierundfünfzig'],
  },
  {
    id: 'p5-son-54-error',
    day: 5, track: 'private', topicId: SON,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-54',
    instruction: 'Hata avı — bu hangi sayının Almancası?',
    prompt: '54 = fünfundvierzig',
    answer: '54 = vierundfünfzig',
    explanation: '`fünfundvierzig` aslında 45 demektir. 54 için önce birler (vier), sonra `und`, sonra onlar (fünfzig): `vierundfünfzig`.',
    pronounce: ['vierundfünfzig'],
  },
  {
    id: 'p5-son-numeric-dreiundachtzig-free',
    day: 5, track: 'private', topicId: SON,
    type: 'free-text', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-83',
    instruction: 'Bu hangi sayı? Rakamla yaz:',
    prompt: 'dreiundachtzig',
    answer: '83',
    pronounce: ['dreiundachtzig'],
  },
  {
    id: 'p5-son-numeric-vierundfuenfzig-free',
    day: 5, track: 'private', topicId: SON,
    type: 'free-text', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-54',
    instruction: 'Bu hangi sayı? Rakamla yaz:',
    prompt: 'vierundfünfzig',
    answer: '54',
    pronounce: ['vierundfünfzig'],
  },
  {
    id: 'p5-son-compare-larger-mc',
    day: 5, track: 'private', topicId: SON,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-compare',
    instruction: 'Hangisi daha büyüktür?',
    prompt: 'vierundachtzig / achtundvierzig / vierzig / achtzig',
    answer: 'vierundachtzig',
    options: ['vierundachtzig', 'achtundvierzig', 'vierzig', 'achtzig'],
    explanation: 'vierundachtzig = 84, achtundvierzig = 48 — sıra karıştırılınca anlam tamamen değişir.',
    pronounce: ['vierundachtzig'],
  },
  {
    id: 'p5-son-listen-46',
    day: 5, track: 'private', topicId: SON,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-46',
    instruction: 'Duyduğun sayıyı seç:',
    prompt: 'sechsundvierzig',
    audioText: 'sechsundvierzig',
    answer: 'sechsundvierzig',
    options: ['sechsundvierzig', 'vierzig', 'sechzehn', 'sechzig'],
    audio: { prompt: { text: 'sechsundvierzig', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-son-listen-94',
    day: 5, track: 'private', topicId: SON,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-94',
    instruction: 'Duyduğun sayıyı seç:',
    prompt: 'vierundneunzig',
    audioText: 'vierundneunzig',
    answer: 'vierundneunzig',
    options: ['vierundneunzig', 'neunzig', 'vierzehn', 'neunzehn'],
    audio: { prompt: { text: 'vierundneunzig', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-son-dictation-65',
    day: 5, track: 'private', topicId: SON,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.sayilar.bilesik'],
    familyId: 'p5-son-65',
    instruction: 'Duyduğun iki basamaklı sayıyı aynen yaz:',
    audioText: 'fünfundsechzig',
    answer: 'fünfundsechzig',
    audio: { prompt: { text: 'fünfundsechzig', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Yüzler ve Bin (9)
   * ================================================================ */
  {
    id: 'p5-syu-hundert-mc',
    day: 5, track: 'private', topicId: SYU,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.yuzler'],
    familyId: 'p5-syu-hundert',
    instruction: 'Doğru Almancasını seç:',
    prompt: '100',
    answer: 'hundert',
    options: ['hundert', 'zehn', 'tausend', 'hundertzehn'],
    pronounce: ['hundert'],
  },
  {
    id: 'p5-syu-200-fill',
    day: 5, track: 'private', topicId: SYU,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day5.sayilar.yuzler'],
    familyId: 'p5-syu-200',
    instruction: 'Almanca yaz:',
    prompt: '200 → ___',
    answer: 'zweihundert',
    pronounce: ['zweihundert'],
  },
  {
    id: 'p5-syu-205-fill',
    day: 5, track: 'private', topicId: SYU,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-205',
    instruction: 'Almanca yaz (hundert\'den sonra und yok):',
    prompt: '205 → ___',
    answer: 'zweihundertfünf',
    pronounce: ['zweihundertfünf'],
  },
  {
    id: 'p5-syu-205-error',
    day: 5, track: 'private', topicId: SYU,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day5.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-205',
    instruction: 'Hata avı:',
    prompt: '205 = zweihundertundfünf',
    answer: '205 = zweihundertfünf',
    explanation: '`hundert`den sonra gelen sayıyla arasına `und` girmez; `und` yalnızca birler-onlar arasında kullanılır.',
    pronounce: ['zweihundertfünf'],
  },
  {
    id: 'p5-syu-1000-mc',
    day: 5, track: 'private', topicId: SYU,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.bin'],
    familyId: 'p5-syu-1000',
    instruction: 'Doğru Almancasını seç:',
    prompt: '1000',
    answer: 'tausend',
    options: ['tausend', 'hundert', 'zweihundert', 'zehn'],
    pronounce: ['tausend'],
  },
  {
    id: 'p5-syu-dictation-205',
    day: 5, track: 'private', topicId: SYU,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-205',
    instruction: 'Duyduğun üç basamaklı sayıyı aynen yaz:',
    audioText: 'zweihundertfünf',
    answer: 'zweihundertfünf',
    audio: { prompt: { text: 'zweihundertfünf', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-syu-listen-zweihundert',
    day: 5, track: 'private', topicId: SYU,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.yuzler'],
    familyId: 'p5-syu-200',
    instruction: 'Duyduğun sayıyı seç:',
    prompt: 'zweihundert',
    audioText: 'zweihundert',
    answer: 'zweihundert',
    options: ['zweihundert', 'zwanzig', 'zweihundertfünf', 'hundert'],
    audio: { prompt: { text: 'zweihundert', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-syu-compare-mc',
    day: 5, track: 'private', topicId: SYU,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-compare',
    instruction: 'Hangisi daha büyüktür?',
    prompt: 'zweihundertfünf / hundert / zwanzig / fünfzig',
    answer: 'zweihundertfünf',
    options: ['zweihundertfünf', 'hundert', 'zwanzig', 'fünfzig'],
    pronounce: ['zweihundertfünf'],
  },
  {
    id: 'p5-syu-225-free',
    day: 5, track: 'private', topicId: SYU,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-225',
    instruction: 'Almanca yaz (yüzler + [birler+und+onlar]):',
    prompt: '225 → ______',
    answer: 'zweihundertfünfundzwanzig',
    pronounce: ['zweihundertfünfundzwanzig'],
  },

  /* ================================================================
   * Kişisel Bilgiler ve Form Alanları (10)
   * ================================================================ */
  {
    id: 'p5-kb-familienname-mc',
    day: 5, track: 'private', topicId: KB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.form.alanlar'],
    familyId: 'p5-kb-familienname',
    instruction: '"der Familienname" ne demektir?',
    prompt: 'der Familienname',
    answer: 'soyadı',
    options: ['soyadı', 'ad', 'doğum yeri', 'telefon numarası'],
    pronounce: ['der Familienname'],
  },
  {
    id: 'p5-kb-vorname-fill',
    day: 5, track: 'private', topicId: KB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day5.form.alanlar'],
    familyId: 'p5-kb-vorname',
    instruction: 'Boşluğu doldur (ad/isim alanı):',
    prompt: 'der ___ = ad, isim',
    answer: 'Vorname',
    pronounce: ['der Vorname'],
  },
  {
    id: 'p5-kb-heimatland-mc',
    day: 5, track: 'private', topicId: KB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.form.alanlar'],
    familyId: 'p5-kb-heimatland',
    instruction: '"das Heimatland" ne demektir?',
    prompt: 'das Heimatland',
    answer: 'memleket / anavatan',
    options: ['memleket / anavatan', 'doğum yeri', 'cadde', 'telefon numarası'],
    pronounce: ['das Heimatland'],
  },
  {
    id: 'p5-kb-strasse-fill',
    day: 5, track: 'private', topicId: KB,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day5.form.alanlar'],
    familyId: 'p5-kb-strasse',
    instruction: 'Boşluğu doldur (cadde/sokak alanı):',
    prompt: 'die ___ = cadde / sokak',
    answer: 'Straße',
    validation: { keyboardTolerance: true },
    pronounce: ['die Straße'],
  },
  {
    id: 'p5-kb-telefonnummer-fill',
    day: 5, track: 'private', topicId: KB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day5.form.alanlar'],
    familyId: 'p5-kb-telefonnummer',
    instruction: 'Boşluğu doldur (telefon numarası alanı):',
    prompt: 'die ___ = telefon numarası',
    answer: 'Telefonnummer',
    pronounce: ['die Telefonnummer'],
  },
  {
    id: 'p5-kb-wohnort-mc',
    day: 5, track: 'private', topicId: KB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.form.alanlar'],
    familyId: 'p5-kb-wohnort',
    instruction: '"der Wohnort" ne demektir?',
    prompt: 'der Wohnort',
    answer: 'ikamet yeri',
    options: ['ikamet yeri', 'doğum yeri', 'soyadı', 'medeni hal'],
    pronounce: ['der Wohnort'],
  },
  {
    id: 'p5-kb-matching-fields',
    day: 5, track: 'private', topicId: KB,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.form.alanlar'],
    familyId: 'p5-kb-matching',
    instruction: 'Form alanlarını Türkçesiyle eşleştir.',
    pairs: [
      { left: 'der Familienname', right: 'soyadı' },
      { left: 'der Vorname', right: 'ad' },
      { left: 'das Heimatland', right: 'memleket' },
      { left: 'der Geburtsort', right: 'doğum yeri' },
      { left: 'die Straße', right: 'cadde / sokak' },
      { left: 'der Wohnort', right: 'ikamet yeri' },
      { left: 'die Telefonnummer', right: 'telefon numarası' },
      { left: 'der Familienstand', right: 'medeni hal' },
    ],
    pronounce: ['der Familienname', 'der Vorname', 'das Heimatland', 'der Geburtsort', 'die Straße', 'der Wohnort', 'die Telefonnummer', 'der Familienstand'],
  },
  {
    id: 'p5-kb-field-to-question-mc',
    day: 5, track: 'private', topicId: KB,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day5.form.alanlar'],
    familyId: 'p5-kb-field-question',
    instruction: '"Wohnort" alanına karşılık gelen soru hangisidir?',
    prompt: 'Wohnort',
    answer: 'Wo wohnst du?',
    options: ['Wo wohnst du?', 'Wie heißt du?', 'Wie alt bist du?', 'Was machst du beruflich?'],
    pronounce: ['Wo wohnst du?'],
  },
  {
    id: 'p5-kb-question-to-field-mc',
    day: 5, track: 'private', topicId: KB,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day5.form.alanlar', 'private.day5.dogum.soru-cevap'],
    familyId: 'p5-kb-question-field',
    instruction: '"Wo bist du geboren?" hangi form alanına karşılık gelir?',
    prompt: 'Wo bist du geboren?',
    answer: 'Geburtsort',
    options: ['Geburtsort', 'Wohnort', 'Familienname', 'Telefonnummer'],
  },
  {
    id: 'p5-kb-kinder-fill',
    day: 5, track: 'private', topicId: KB,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day5.form.kinder'],
    familyId: 'p5-kb-kinder',
    instruction: 'Boşluğu doldur (1. Gün\'den hatırla):',
    prompt: 'Ich habe keine ___. (hiç çocuğum yok)',
    answer: 'Kinder',
    pronounce: ['Ich habe keine Kinder.'],
  },

  /* ================================================================
   * Memleket, Doğum Yeri ve İkamet (13)
   * ================================================================ */
  {
    id: 'p5-dy-geboren-mc',
    day: 5, track: 'private', topicId: DY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.dogum.soru-cevap'],
    familyId: 'p5-dy-geboren',
    instruction: '"geboren" ne demektir?',
    prompt: 'geboren',
    answer: 'doğmuş',
    options: ['doğmuş', 'yaşayan', 'oturan', 'gelen'],
    pronounce: ['geboren'],
  },
  {
    id: 'p5-dy-wo-bist-du-fill',
    day: 5, track: 'private', topicId: DY,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day5.dogum.soru-cevap'],
    familyId: 'p5-dy-wo-bist-du',
    instruction: 'Boşluğu doldur:',
    prompt: '___ bist du geboren? (Nerede doğdun?)',
    answer: 'Wo',
    pronounce: ['Wo bist du geboren?'],
  },
  {
    id: 'p5-dy-wo-sind-sie-mc',
    day: 5, track: 'private', topicId: DY,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.dogum.soru-cevap'],
    familyId: 'p5-dy-formal',
    instruction: '"Wo sind Sie geboren?" hangi hitap şeklidir?',
    prompt: 'Wo sind Sie geboren?',
    answer: 'resmî',
    options: ['resmî', 'samimi', 'çoğul-gündelik', 'soru değil'],
    pronounce: ['Wo sind Sie geboren?'],
  },
  {
    id: 'p5-dy-ich-bin-in-fill',
    day: 5, track: 'private', topicId: DY,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.dogum.soru-cevap'],
    familyId: 'p5-dy-ich-bin-in',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich bin in Sakarya ___. (Sakarya\'da doğdum)',
    answer: 'geboren',
    pronounce: ['Ich bin in Sakarya geboren.'],
  },
  {
    id: 'p5-dy-contrast-woher-mc',
    day: 5, track: 'private', topicId: DY,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.dogum.aciklik'],
    familyId: 'p5-dy-contrast-woher',
    instruction: '"Woher kommst du?" ne sorar?',
    prompt: 'Woher kommst du?',
    answer: 'köken / nereli olduğun',
    options: ['köken / nereli olduğun', 'doğum yerin', 'şu anki ikametin', 'adın'],
  },
  {
    id: 'p5-dy-contrast-geboren-mc',
    day: 5, track: 'private', topicId: DY,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.dogum.aciklik'],
    familyId: 'p5-dy-contrast-geboren',
    instruction: '"Wo bist du geboren?" ne sorar?',
    prompt: 'Wo bist du geboren?',
    answer: 'doğum yerin',
    options: ['doğum yerin', 'köken', 'şu anki ikametin', 'mesleğin'],
  },
  {
    id: 'p5-dy-matching-questions',
    day: 5, track: 'private', topicId: DY,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.dogum.aciklik'],
    familyId: 'p5-dy-matching',
    instruction: 'Soruları hangi bilgiyi istediğiyle eşleştir.',
    pairs: [
      { left: 'Woher kommst du?', right: 'köken' },
      { left: 'Wo bist du geboren?', right: 'doğum yeri' },
      { left: 'Wo wohnst du?', right: 'ikamet' },
    ],
    pronounce: ['Woher kommst du?', 'Wo bist du geboren?', 'Wo wohnst du?'],
  },
  {
    id: 'p5-dy-profile-interpret-geboren-free',
    day: 5, track: 'private', topicId: DY,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.dogum.aciklik'],
    familyId: 'p5-dy-profile-emre',
    instruction: 'Profil: Vorname: Emre / Geburtsort: Ankara / Wohnort: Berlin.\nSoru: Wo ist Emre geboren?',
    prompt: 'Wo ist Emre geboren?',
    answer: 'Emre ist in Ankara geboren.',
    pronounce: ['Emre ist in Ankara geboren.'],
  },
  {
    id: 'p5-dy-profile-interpret-wohnt-free',
    day: 5, track: 'private', topicId: DY,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.dogum.aciklik'],
    familyId: 'p5-dy-profile-emre',
    instruction: 'Profil: Vorname: Emre / Geburtsort: Ankara / Wohnort: Berlin.\nSoru: Wo wohnt Emre?',
    prompt: 'Wo wohnt Emre?',
    answer: 'Emre wohnt in Berlin.',
    pronounce: ['Emre wohnt in Berlin.'],
  },
  {
    id: 'p5-dy-mini-interview-mc',
    day: 5, track: 'private', topicId: DY,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.dogum.soru-cevap'],
    familyId: 'p5-dy-mini-interview',
    instruction: 'Mini diyalog: B ne demeli?',
    prompt: 'A: Wo bist du geboren?\nB: ______',
    answer: 'Ich bin in Izmir geboren.',
    options: ['Ich bin in Izmir geboren.', 'Ich heiße Izmir.', 'Izmir ist schön.', 'Ich wohne Izmir.'],
    pronounce: ['Ich bin in Izmir geboren.'],
  },
  {
    id: 'p5-dy-error-geboren',
    day: 5, track: 'private', topicId: DY,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day5.dogum.aciklik'],
    familyId: 'p5-dy-error',
    instruction: 'Hata avı:',
    prompt: 'Ich bin in Sakarya wohnen.',
    answer: 'Ich bin in Sakarya geboren.',
    explanation: '"geboren" sabit olarak `sein` ile kullanılır; `wohnen` ayrı bir fiildir ve bu kalıpta kullanılmaz.',
    pronounce: ['Ich bin in Sakarya geboren.'],
  },
  {
    id: 'p5-dy-wb-geboren-tr-de',
    day: 5, track: 'private', topicId: DY,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.dogum.soru-cevap'],
    familyId: 'p5-dy-wb-geboren',
    instruction: 'Türkçeden Almancaya kur — Ben Sakarya\'da doğdum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ben Sakarya\'da doğdum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'bin' }, { id: 't3', text: 'in' }, { id: 't4', text: 'Sakarya' }, { id: 't5', text: 'geboren.' },
        { id: 't6', text: 'wohne' }, { id: 't7', text: 'komme' },
      ],
      acceptedSequences: [['Ich', 'bin', 'in', 'Sakarya', 'geboren.']],
    },
    answer: 'Ich bin in Sakarya geboren.',
    pronounce: ['Ich bin in Sakarya geboren.'],
  },
  {
    id: 'p5-dy-spoken-sorular',
    day: 5, track: 'private', topicId: DY,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day5.dogum.aciklik'],
    familyId: 'p5-dy-spoken',
    instruction: 'Sesli görev: Woher kommst du?, Wo bist du geboren? ve Wo wohnst du? sorularını kendi bilgilerinle cevapla.',
    requirements: ['Ich komme aus ...', 'Ich bin in ... geboren.', 'Ich wohne in ...'],
    sampleAnswer: 'Ich komme aus Sakarya. Ich bin in Sakarya geboren. Ich wohne in Istanbul.',
    pronounce: ['Ich komme aus Sakarya.', 'Ich bin in Sakarya geboren.', 'Ich wohne in Istanbul.'],
  },

  /* ================================================================
   * Familienstand — ledig / verheiratet (6)
   * ================================================================ */
  {
    id: 'p5-mh-ledig-mc',
    day: 5, track: 'private', topicId: MH,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-ledig',
    instruction: '"ledig" ne demektir?',
    prompt: 'ledig',
    answer: 'bekar',
    options: ['bekar', 'evli', 'boşanmış', 'dul'],
    pronounce: ['ledig'],
  },
  {
    id: 'p5-mh-verheiratet-mc',
    day: 5, track: 'private', topicId: MH,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-verheiratet',
    instruction: '"verheiratet" ne demektir?',
    prompt: 'verheiratet',
    answer: 'evli',
    options: ['evli', 'bekar', 'çocuklu', 'yaşlı'],
    pronounce: ['verheiratet'],
  },
  {
    id: 'p5-mh-fill-ledig',
    day: 5, track: 'private', topicId: MH,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-fill-ledig',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich bin ___. (Bekarım.)',
    answer: 'ledig',
    pronounce: ['Ich bin ledig.'],
  },
  {
    id: 'p5-mh-fill-verheiratet',
    day: 5, track: 'private', topicId: MH,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-fill-verheiratet',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich bin ___. (Evliyim.)',
    answer: 'verheiratet',
    pronounce: ['Ich bin verheiratet.'],
  },
  {
    id: 'p5-mh-matching',
    day: 5, track: 'private', topicId: MH,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-matching',
    instruction: 'Eşleştir.',
    pairs: [
      { left: 'ledig', right: 'bekar' },
      { left: 'verheiratet', right: 'evli' },
    ],
    pronounce: ['ledig', 'verheiratet'],
  },
  {
    id: 'p5-mh-listen',
    day: 5, track: 'private', topicId: MH,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-listen',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich bin verheiratet.',
    audioText: 'Ich bin verheiratet.',
    answer: 'Ich bin verheiratet.',
    options: ['Ich bin verheiratet.', 'Ich bin ledig.', 'Ich habe keine Kinder.', 'Ich bin Student.'],
    audio: { prompt: { text: 'Ich bin verheiratet.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Kendini Daha Ayrıntılı Tanıtma (11)
   * ================================================================ */
  {
    id: 'p5-kt-model-order',
    day: 5, track: 'private', topicId: KT,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.tanitma.model'],
    familyId: 'p5-kt-order-alt',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / bin / achtzehn / Jahre / alt.',
    answer: 'Ich bin achtzehn Jahre alt.',
    words: ['Ich', 'bin', 'achtzehn', 'Jahre', 'alt'],
    pronounce: ['Ich bin achtzehn Jahre alt.'],
  },
  {
    id: 'p5-kt-model-order2',
    day: 5, track: 'private', topicId: KT,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.tanitma.ornekler'],
    familyId: 'p5-kt-order-und',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / komme / aus / Sakarya / und / ich / wohne / in / Istanbul.',
    answer: 'Ich komme aus Sakarya und ich wohne in Istanbul.',
    words: ['Ich', 'komme', 'aus', 'Sakarya', 'und', 'ich', 'wohne', 'in', 'Istanbul'],
    pronounce: ['Ich komme aus Sakarya und ich wohne in Istanbul.'],
  },
  {
    id: 'p5-kt-mustafa-mc',
    day: 5, track: 'private', topicId: KT,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.tanitma.ornekler'],
    familyId: 'p5-kt-mustafa',
    instruction: 'Örnek 1\'i oku: "Hallo! Ich bin Mustafa. Ich komme aus Sakarya. Ich bin in Sakarya geboren. Ich bin achtzehn Jahre alt. Ich bin Student."\nMustafa kaç yaşındadır?',
    prompt: 'Mustafa kaç yaşındadır?',
    answer: '18',
    options: ['18', '25', '15', '20'],
  },
  {
    id: 'p5-kt-nazar-herkunft-mc',
    day: 5, track: 'private', topicId: KT,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.tanitma.ornekler'],
    familyId: 'p5-kt-nazar-herkunft',
    instruction: 'Örnek 2\'yi oku: "Ich heiße Nazar. Ich bin 25 Jahre alt. Ich komme aus Istanbul und ich wohne in Istanbul. Ich bin in Istanbul geboren."\nNazar nereli?',
    prompt: 'Nazar nereli?',
    answer: 'Istanbul',
    options: ['Istanbul', 'Sakarya', 'Ankara', 'Izmir'],
  },
  {
    id: 'p5-kt-nazar-geboren-mc',
    day: 5, track: 'private', topicId: KT,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.tanitma.ornekler'],
    familyId: 'p5-kt-nazar-geboren',
    instruction: 'Aynı örnekte: Nazar nerede doğdu?',
    prompt: 'Nazar nerede doğdu?',
    answer: 'Istanbul',
    options: ['Istanbul', 'Sakarya', 'Ankara', 'Izmir'],
  },
  {
    id: 'p5-kt-wohnen-leben-mc',
    day: 5, track: 'private', topicId: KT,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.tanitma.model'],
    familyId: 'p5-kt-wohnen-leben',
    instruction: '"Ich wohne in Istanbul und ich bin in Istanbul geboren." cümlesinde ne anlatılıyor?',
    prompt: 'Ich wohne in Istanbul und ich bin in Istanbul geboren.',
    answer: 'Doğum yeri ve ikamet aynı şehir; köken hakkında bilgi verilmiyor',
    options: [
      'Doğum yeri ve ikamet aynı şehir; köken hakkında bilgi verilmiyor',
      'Sadece köken bilgisi veriliyor',
      'Sadece isim veriliyor',
      'Sadece yaş veriliyor',
    ],
  },
  {
    id: 'p5-kt-error',
    day: 5, track: 'private', topicId: KT,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day5.tanitma.model'],
    familyId: 'p5-kt-error',
    instruction: 'Hata avı — cümleler ayrılmalı/bağlanmalı:',
    prompt: 'Ich heiße Nazar, Ich bin 25 Jahre alt komme aus Istanbul.',
    answer: 'Ich heiße Nazar. Ich bin 25 Jahre alt. Ich komme aus Istanbul.',
    explanation: 'Her cümlenin kendi öznesi ve fiili olmalı; cümleler nokta ile ayrılır ya da `und` ile açıkça bağlanır.',
    pronounce: ['Ich heiße Nazar.', 'Ich bin 25 Jahre alt.', 'Ich komme aus Istanbul.'],
  },
  {
    id: 'p5-kt-wb-selfintro-tr-de',
    day: 5, track: 'private', topicId: KT,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.tanitma.model'],
    familyId: 'p5-kt-wb-selfintro',
    instruction: 'Türkçeden Almancaya kur — Merhaba! Sakarya\'dan geliyorum ve Sakarya\'da doğdum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Merhaba! Sakarya\'dan geliyorum ve Sakarya\'da doğdum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Hallo!' }, { id: 't2', text: 'Ich' }, { id: 't3', text: 'komme' }, { id: 't4', text: 'aus' }, { id: 't5', text: 'Sakarya' },
        { id: 't6', text: 'und' }, { id: 't7', text: 'ich' }, { id: 't8', text: 'bin' }, { id: 't9', text: 'in' }, { id: 't10', text: 'geboren.' },
        { id: 't11', text: 'Sakarya' }, { id: 't12', text: 'wohne' },
      ],
      acceptedSequences: [['Hallo!', 'Ich', 'komme', 'aus', 'Sakarya', 'und', 'ich', 'bin', 'in', 'Sakarya', 'geboren.']],
    },
    answer: 'Hallo! Ich komme aus Sakarya und ich bin in Sakarya geboren.',
    pronounce: ['Hallo! Ich komme aus Sakarya und ich bin in Sakarya geboren.'],
  },
  {
    id: 'p5-kt-spoken-tanitim',
    day: 5, track: 'private', topicId: KT,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day5.tanitma.model'],
    familyId: 'p5-kt-spoken',
    instruction: 'Sesli görev: Kendini ayrıntılı tanıt — adını, yaşını, memleketini, doğum yerini ve ikametini söyle.',
    requirements: ['Ich heiße ...', 'Ich bin ... Jahre alt.', 'Ich komme aus ...', 'Ich bin in ... geboren.', 'Ich wohne in ...'],
    sampleAnswer: 'Ich heiße Mustafa. Ich bin achtzehn Jahre alt. Ich komme aus Sakarya. Ich bin in Sakarya geboren. Ich wohne in Istanbul.',
    pronounce: ['Ich heiße Mustafa.', 'Ich bin achtzehn Jahre alt.', 'Ich komme aus Sakarya.', 'Ich bin in Sakarya geboren.', 'Ich wohne in Istanbul.'],
  },
  {
    id: 'p5-kt-profile-builder-spoken',
    day: 5, track: 'private', topicId: KT,
    type: 'spoken', difficulty: 'hard', skill: 'speaking',
    conceptIds: ['private.day5.tanitma.model', 'private.day5.dogum.aciklik'],
    familyId: 'p5-kt-profile-builder',
    instruction: 'Sesli görev: Lena adlı kurgusal kişiyi tanıt (21 yaşında, Almanya\'dan, München\'de doğdu, Berlin\'de yaşıyor).',
    requirements: ['Sie heißt ...', 'Sie ist ... Jahre alt.', 'Sie kommt aus ...', 'Sie ist in ... geboren.', 'Sie wohnt in ...'],
    sampleAnswer: 'Sie heißt Lena. Sie ist 21 Jahre alt. Sie kommt aus Deutschland. Sie ist in München geboren. Sie wohnt in Berlin.',
    pronounce: ['Sie heißt Lena.', 'Sie ist 21 Jahre alt.', 'Sie kommt aus Deutschland.', 'Sie ist in München geboren.', 'Sie wohnt in Berlin.'],
  },
  {
    id: 'p5-kt-dictation',
    day: 5, track: 'private', topicId: KT,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.tanitma.model'],
    familyId: 'p5-kt-order-alt',
    instruction: 'Kendini tanıtma cümlesini duydun — aynen yaz:',
    audioText: 'Ich bin achtzehn Jahre alt.',
    answer: 'Ich bin achtzehn Jahre alt.',
    audio: { prompt: { text: 'Ich bin achtzehn Jahre alt.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * und / aber — Bağlaçlar (8)
   * ================================================================ */
  {
    id: 'p5-bag-und-mc',
    day: 5, track: 'private', topicId: BAG,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.baglac.und'],
    familyId: 'p5-bag-und-mc',
    instruction: '"und" ne demektir?',
    prompt: 'und',
    answer: 've',
    options: ['ve', 'ama', 'ile', 'veya'],
    pronounce: ['und'],
  },
  {
    id: 'p5-bag-aber-mc',
    day: 5, track: 'private', topicId: BAG,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.baglac.aber'],
    familyId: 'p5-bag-aber-mc',
    instruction: '"aber" ne demektir?',
    prompt: 'aber',
    answer: 'ama',
    options: ['ama', 've', 'çünkü', 'ile'],
    pronounce: ['aber'],
  },
  {
    id: 'p5-bag-choose-und-fill',
    day: 5, track: 'private', topicId: BAG,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.baglac.und'],
    familyId: 'p5-bag-choose-und',
    instruction: 'Boşluğu doldur (uyumlu bilgi — ekleme):',
    prompt: 'Ich komme aus Sakarya ___ ich wohne in Istanbul.',
    answer: 'und',
    pronounce: ['Ich komme aus Sakarya und ich wohne in Istanbul.'],
  },
  {
    id: 'p5-bag-choose-aber-fill',
    day: 5, track: 'private', topicId: BAG,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.baglac.aber'],
    familyId: 'p5-bag-choose-aber',
    instruction: 'Boşluğu doldur (zıtlık vurgusu):',
    prompt: 'Ich komme aus Sakarya, ___ ich wohne in Istanbul.',
    answer: 'aber',
    pronounce: ['Ich komme aus Sakarya, aber ich wohne in Istanbul.'],
  },
  {
    id: 'p5-bag-secim-mc',
    day: 5, track: 'private', topicId: BAG,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day5.baglac.aber', 'private.day5.baglac.und'],
    familyId: 'p5-bag-secim',
    instruction: 'Hangisi uyar? (öğrenciyim, ama aynı zamanda çalışıyorum da — beklenmedik)',
    prompt: 'Ich bin Student, ___ ich arbeite auch.',
    answer: 'aber',
    options: ['aber', 'und', 'seit', 'mehr'],
    pronounce: ['Ich bin Student, aber ich arbeite auch.'],
  },
  {
    id: 'p5-bag-order',
    day: 5, track: 'private', topicId: BAG,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.baglac.aber'],
    familyId: 'p5-bag-order',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / bin / Student, / aber / ich / arbeite / auch.',
    answer: 'Ich bin Student, aber ich arbeite auch.',
    words: ['Ich', 'bin', 'Student,', 'aber', 'ich', 'arbeite', 'auch'],
    pronounce: ['Ich bin Student, aber ich arbeite auch.'],
  },
  {
    id: 'p5-bag-wb-aber-tr-de',
    day: 5, track: 'private', topicId: BAG,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.baglac.aber'],
    familyId: 'p5-bag-wb-aber',
    instruction: 'Türkçeden Almancaya kur — Sakarya\'dan geliyorum ama İstanbul\'da oturuyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Sakarya\'dan geliyorum ama İstanbul\'da oturuyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'komme' }, { id: 't3', text: 'aus' }, { id: 't4', text: 'Sakarya,' }, { id: 't5', text: 'aber' },
        { id: 't6', text: 'ich' }, { id: 't7', text: 'wohne' }, { id: 't8', text: 'in' }, { id: 't9', text: 'Istanbul.' }, { id: 't10', text: 'und' },
      ],
      acceptedSequences: [['Ich', 'komme', 'aus', 'Sakarya,', 'aber', 'ich', 'wohne', 'in', 'Istanbul.']],
    },
    answer: 'Ich komme aus Sakarya, aber ich wohne in Istanbul.',
    pronounce: ['Ich komme aus Sakarya, aber ich wohne in Istanbul.'],
  },
  {
    id: 'p5-bag-error',
    day: 5, track: 'private', topicId: BAG,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day5.baglac.aber'],
    familyId: 'p5-bag-error',
    instruction: 'Hata avı — virgül yeri:',
    prompt: 'Ich komme aus Sakarya aber, ich wohne in Istanbul.',
    answer: 'Ich komme aus Sakarya, aber ich wohne in Istanbul.',
    explanation: 'Virgül `aber`den önce gelir, sonra değil.',
    pronounce: ['Ich komme aus Sakarya, aber ich wohne in Istanbul.'],
  },

  /* ================================================================
   * Yeni Faydalı Kelimeler (11)
   * ================================================================ */
  {
    id: 'p5-kel-leider-mc',
    day: 5, track: 'private', topicId: KEL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.kelime.leider'],
    familyId: 'p5-kel-leider',
    instruction: '"leider" ne demektir?',
    prompt: 'leider',
    answer: 'maalesef / ne yazık ki',
    options: ['maalesef / ne yazık ki', 'belki', 'elbette', 'asla'],
    pronounce: ['leider'],
  },
  {
    id: 'p5-kel-mehr-mc',
    day: 5, track: 'private', topicId: KEL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.kelime.mehr'],
    familyId: 'p5-kel-mehr',
    instruction: '"mehr" ne demektir?',
    prompt: 'mehr',
    answer: 'daha fazla',
    options: ['daha fazla', 'daha az', 'hiç', 'çok az'],
    pronounce: ['mehr'],
  },
  {
    id: 'p5-kel-geschwister-mc',
    day: 5, track: 'private', topicId: KEL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.kelime.geschwister'],
    familyId: 'p5-kel-geschwister',
    instruction: '"die Geschwister" ne demektir?',
    prompt: 'die Geschwister',
    answer: 'kardeşler',
    options: ['kardeşler', 'ebeveynler', 'çocuklar', 'arkadaşlar'],
    pronounce: ['die Geschwister'],
  },
  {
    id: 'p5-kel-seit-mc',
    day: 5, track: 'private', topicId: KEL,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.kelime.seit'],
    familyId: 'p5-kel-seit',
    instruction: '"seit" ne demektir?',
    prompt: 'seit',
    answer: '-den beri',
    options: ['-den beri', '-e kadar', '-den önce', '-den sonra'],
    pronounce: ['seit'],
  },
  {
    id: 'p5-kel-flughafen-mc',
    day: 5, track: 'private', topicId: KEL,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.kelime.flughafen'],
    familyId: 'p5-kel-flughafen',
    instruction: '"der Flughafen" ne demektir?',
    prompt: 'der Flughafen',
    answer: 'havaalanı',
    options: ['havaalanı', 'tren istasyonu', 'otobüs durağı', 'liman'],
    pronounce: ['der Flughafen'],
  },
  {
    id: 'p5-kel-moment-mc',
    day: 5, track: 'private', topicId: KEL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.kelime.moment'],
    familyId: 'p5-kel-moment',
    instruction: '"der Moment" ne demektir?',
    prompt: 'der Moment',
    answer: 'an / bir dakika',
    options: ['an / bir dakika', 'gün', 'hafta', 'saat'],
    pronounce: ['der Moment'],
  },
  {
    id: 'p5-kel-matching',
    day: 5, track: 'private', topicId: KEL,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.kelime.leider', 'private.day5.kelime.mehr', 'private.day5.kelime.geschwister', 'private.day5.kelime.seit', 'private.day5.kelime.flughafen', 'private.day5.kelime.moment'],
    familyId: 'p5-kel-matching',
    instruction: 'Kelimeleri Türkçesiyle eşleştir.',
    pairs: [
      { left: 'leider', right: 'maalesef' },
      { left: 'mehr', right: 'daha fazla' },
      { left: 'die Geschwister', right: 'kardeşler' },
      { left: 'seit', right: '-den beri' },
      { left: 'der Flughafen', right: 'havaalanı' },
      { left: 'der Moment', right: 'an' },
    ],
    pronounce: ['leider', 'mehr', 'die Geschwister', 'seit', 'der Flughafen', 'der Moment'],
  },
  {
    id: 'p5-kel-fill-geschwister',
    day: 5, track: 'private', topicId: KEL,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.kelime.geschwister'],
    familyId: 'p5-kel-fill-geschwister',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich habe keine ___. (Hiç kardeşim yok.)',
    answer: 'Geschwister',
    pronounce: ['Ich habe keine Geschwister.'],
  },
  {
    id: 'p5-kel-fill-seit',
    day: 5, track: 'private', topicId: KEL,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day5.kelime.seit'],
    familyId: 'p5-kel-fill-seit',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich lebe ___ zwei Jahren in Berlin. (İki yıldır Berlin\'de yaşıyorum.)',
    answer: 'seit',
    pronounce: ['Ich lebe seit zwei Jahren in Berlin.'],
  },
  {
    id: 'p5-kel-dictation-flughafen',
    day: 5, track: 'private', topicId: KEL,
    type: 'dictation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.kelime.flughafen'],
    familyId: 'p5-kel-flughafen',
    instruction: 'Havaalanı cümlesini duydun — aynen yaz:',
    audioText: 'Der Flughafen ist sehr groß.',
    answer: 'Der Flughafen ist sehr groß.',
    audio: { prompt: { text: 'Der Flughafen ist sehr groß.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-kel-wb-leider-tr-de',
    day: 5, track: 'private', topicId: KEL,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.kelime.leider'],
    familyId: 'p5-kel-wb-leider',
    instruction: 'Türkçeden Almancaya kur — Maalesef bugün vaktim yok.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Maalesef bugün vaktim yok.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Leider' }, { id: 't2', text: 'habe' }, { id: 't3', text: 'ich' }, { id: 't4', text: 'heute' }, { id: 't5', text: 'keine' }, { id: 't6', text: 'Zeit.' },
        { id: 't7', text: 'mehr' },
      ],
      acceptedSequences: [['Leider', 'habe', 'ich', 'heute', 'keine', 'Zeit.']],
    },
    answer: 'Leider habe ich heute keine Zeit.',
    pronounce: ['Leider habe ich heute keine Zeit.'],
  },

  /* ================================================================
   * Yiyecek ve Mutfak Kelimeleri (11)
   * ================================================================ */
  {
    id: 'p5-yem-ei-mc',
    day: 5, track: 'private', topicId: YEM,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-ei',
    instruction: '"das Ei" ne demektir?',
    prompt: 'das Ei',
    answer: 'yumurta',
    options: ['yumurta', 'un', 'ekmek', 'kek'],
    pronounce: ['das Ei'],
  },
  {
    id: 'p5-yem-mehl-mc',
    day: 5, track: 'private', topicId: YEM,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-mehl',
    instruction: '"das Mehl" ne demektir?',
    prompt: 'das Mehl',
    answer: 'un',
    options: ['un', 'yumurta', 'armut', 'meyve suyu'],
    pronounce: ['das Mehl'],
  },
  {
    id: 'p5-yem-pfannkuchen-mc',
    day: 5, track: 'private', topicId: YEM,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-pfannkuchen',
    instruction: '"der Pfannkuchen" ne demektir?',
    prompt: 'der Pfannkuchen',
    answer: 'krep / gözleme (pankek)',
    options: ['krep / gözleme (pankek)', 'kek', 'ekmek', 'armut'],
    pronounce: ['der Pfannkuchen'],
  },
  {
    id: 'p5-yem-kuchen-fill',
    day: 5, track: 'private', topicId: YEM,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-kuchen',
    instruction: 'Boşluğu doldur (der Kuchen — kek çok lezzetli):',
    prompt: '___ Kuchen ist sehr lecker.',
    answer: 'Der',
    pronounce: ['Der Kuchen ist sehr lecker.'],
  },
  {
    id: 'p5-yem-broetchen-mc',
    day: 5, track: 'private', topicId: YEM,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-broetchen',
    instruction: '"das Brötchen" ne demektir?',
    prompt: 'das Brötchen',
    answer: 'küçük ekmek / sandviç ekmeği',
    options: ['küçük ekmek / sandviç ekmeği', 'büyük ekmek', 'kek', 'pankek'],
    pronounce: ['das Brötchen'],
  },
  {
    id: 'p5-yem-birne-fill',
    day: 5, track: 'private', topicId: YEM,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-birne',
    instruction: 'Boşluğu doldur (armut):',
    prompt: 'die ___ = armut',
    answer: 'Birne',
    pronounce: ['die Birne'],
  },
  {
    id: 'p5-yem-saft-fill',
    day: 5, track: 'private', topicId: YEM,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-saft',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich möchte einen ___, bitte. (Bir meyve suyu istiyorum.)',
    answer: 'Saft',
    pronounce: ['Ich möchte einen Saft, bitte.'],
  },
  {
    id: 'p5-yem-matching',
    day: 5, track: 'private', topicId: YEM,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-matching',
    instruction: 'Yiyecek kelimelerini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'das Ei', right: 'yumurta' },
      { left: 'das Mehl', right: 'un' },
      { left: 'der Pfannkuchen', right: 'krep / gözleme' },
      { left: 'der Kuchen', right: 'kek / pasta' },
      { left: 'das Brötchen', right: 'küçük ekmek' },
      { left: 'die Birne', right: 'armut' },
      { left: 'der Saft', right: 'meyve suyu' },
    ],
    pronounce: ['das Ei', 'das Mehl', 'der Pfannkuchen', 'der Kuchen', 'das Brötchen', 'die Birne', 'der Saft'],
  },
  {
    id: 'p5-yem-artikel-mc',
    day: 5, track: 'private', topicId: YEM,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-artikel',
    instruction: '___ Ei, ___ Saft, ___ Birne — doğru artikel sırası hangisidir?',
    prompt: '___ Ei, ___ Saft, ___ Birne',
    answer: 'das, der, die',
    options: ['das, der, die', 'der, das, die', 'die, der, das', 'das, die, der'],
  },
  {
    id: 'p5-yem-listen',
    day: 5, track: 'private', topicId: YEM,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-listen',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich esse ein Ei zum Frühstück.',
    audioText: 'Ich esse ein Ei zum Frühstück.',
    answer: 'Ich esse ein Ei zum Frühstück.',
    options: [
      'Ich esse ein Ei zum Frühstück.',
      'Ich esse einen Kuchen.',
      'Ich trinke einen Saft.',
      'Ich möchte ein Brötchen.',
    ],
    audio: { prompt: { text: 'Ich esse ein Ei zum Frühstück.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-yem-wb-saft-tr-de',
    day: 5, track: 'private', topicId: YEM,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day5.yiyecek.kelimeler'],
    familyId: 'p5-yem-wb-saft',
    instruction: 'Türkçeden Almancaya kur — Bir meyve suyu istiyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Bir meyve suyu istiyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'möchte' }, { id: 't3', text: 'einen' }, { id: 't4', text: 'Saft.' },
        { id: 't5', text: 'Birne.' },
      ],
      acceptedSequences: [['Ich', 'möchte', 'einen', 'Saft.']],
    },
    answer: 'Ich möchte einen Saft.',
    pronounce: ['Ich möchte einen Saft.'],
  },
];
