/**
 * Özel Ders — 7. Gün — yazılmış alıştırma havuzu.
 *
 * 7. Gün bir DİLBİLGİSİ günü değil, bir KELİME ETKİNLEŞTİRME günüdür:
 * evin odaları, mobilyalar, tarif sıfatları (`hell/dunkel/breit/schmal`),
 * artikelden kişi zamirine geçiş (`der → er`, `das → es`, `die → sie`),
 * dört yeni fiil (`kennen`, `geben`, `anrufen`, `stellen`), `gefallen`
 * kalıbı, `gern` ile yemek-içecek tercihleri, sıklık kelimeleri, miktar
 * kalıpları, yeni yiyecek/alışveriş kelimeleri, fiyat sorma ve `brauchen`.
 *
 * Günün üretim hedefi tek bir görevdir: **öğrencinin kendi evini anlatması.**
 * Bu yüzden havuzun en büyük ve en zor bölümü `Evimi Anlatıyorum` konusudur;
 * kolay tanıma sorularından başlayıp adım adım serbest üretime çıkar.
 *
 * A1 SINIRI: hiçbir alıştırma 1–7. Günlerde öğretilmemiş bir yapı istemez.
 * Özellikle KARŞILAŞTIRMA (`größer als`), GENITIV ve YAN CÜMLE kullanılmaz;
 * "ablamın odası daha büyük" gibi Türkçe fikirler iki ayrı A1 cümlesine
 * bölünerek korunur (bkz. `private.day7.evim.karsilastirma-yok`).
 */

import type { AuthoredExercise } from '../types.ts';

const HED = 'private.day7.hedef';
const EV = 'private.day7.ev-odalar';
const MOB = 'private.day7.mobilyalar';
const TAR = 'private.day7.evi-tarif';
const ZAM = 'private.day7.artikel-zamir';
const FII = 'private.day7.yeni-fiiller';
const GEF = 'private.day7.gefallen';
const ESS = 'private.day7.essen-trinken';
const ALI = 'private.day7.alisveris-siklik';
const MIK = 'private.day7.miktar';
const YIY = 'private.day7.yeni-yiyecek';
const FIY = 'private.day7.fiyat';
const BRA = 'private.day7.brauchen';
const KEL = 'private.day7.faydali-kelimeler';
const EVIM = 'private.day7.evimi-anlatiyorum';
const KAL = 'private.day7.kaliplar';

export const PRIVATE_DAY7_EXERCISES: AuthoredExercise[] = [
  /* ================================================================
   * Bugünün Hedefi (2)
   * ================================================================ */
  {
    id: 'p7-hed-giris-mc',
    day: 7, track: 'private', topicId: HED,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.hedef.giris'],
    familyId: 'p7-hed-giris',
    instruction: '7. Günün ana hedefi nedir?',
    prompt: 'Bu gün ne üzerine kuruludur?',
    answer: 'Ev kelimelerini öğrenip kendi evimi Almanca anlatmak',
    options: [
      'Ev kelimelerini öğrenip kendi evimi Almanca anlatmak',
      'Geçmiş zaman çekimlerini öğrenmek',
      'Sıfat karşılaştırma eklerini öğrenmek',
      'Yan cümle kurmayı öğrenmek',
    ],
  },
  {
    id: 'p7-hed-cekirdek-mc',
    day: 7, track: 'private', topicId: HED,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.hedef.cekirdek'],
    familyId: 'p7-hed-cekirdek',
    instruction: 'Özetteki "Bugün Mutlaka Bilmem Gerekenler" listesinde ne var?',
    prompt: 'Bu liste neyi içerir?',
    answer: 'Günün en öncelikli 26 kelime ve kalıbı',
    options: [
      'Günün en öncelikli 26 kelime ve kalıbı',
      'Tüm Almanca fiillerin listesi',
      'Sadece sayılar',
      'Sadece sıfat ekleri',
    ],
  },

  /* ================================================================
   * Ev ve Odalar (11)
   * ================================================================ */
  {
    id: 'p7-ev-match-odalar',
    day: 7, track: 'private', topicId: EV,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'private.day7.ev.bad',
      'private.day7.ev.schlafzimmer',
      'private.day7.ev.flur',
      'private.day7.ev.kueche',
      'private.day7.ev.wohnzimmer',
    ],
    familyId: 'p7-ev-match',
    instruction: 'Oda adını Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'das Bad', right: 'banyo' },
      { left: 'das Schlafzimmer', right: 'yatak odası' },
      { left: 'der Flur', right: 'koridor' },
      { left: 'die Küche', right: 'mutfak' },
      { left: 'das Wohnzimmer', right: 'salon' },
    ],
    pronounce: ['das Bad', 'das Schlafzimmer', 'der Flur', 'die Küche', 'das Wohnzimmer'],
  },
  {
    id: 'p7-ev-kueche-artikel',
    day: 7, track: 'private', topicId: EV,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.ev.kueche'],
    familyId: 'p7-ev-kueche',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Küche (mutfak)',
    answer: 'die',
    validation: { noTypoTolerance: true },
    pronounce: ['die Küche'],
  },
  {
    id: 'p7-ev-flur-artikel',
    day: 7, track: 'private', topicId: EV,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.ev.flur'],
    familyId: 'p7-ev-flur',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Flur (koridor)',
    answer: 'der',
    validation: { noTypoTolerance: true },
    pronounce: ['der Flur'],
  },
  {
    id: 'p7-ev-schlafzimmer-artikel',
    day: 7, track: 'private', topicId: EV,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.ev.schlafzimmer'],
    familyId: 'p7-ev-schlafzimmer',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Schlafzimmer (yatak odası)',
    answer: 'das',
    validation: { noTypoTolerance: true },
    pronounce: ['das Schlafzimmer'],
  },
  {
    id: 'p7-ev-bad-mc',
    day: 7, track: 'private', topicId: EV,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.ev.bad'],
    familyId: 'p7-ev-bad',
    instruction: 'Hangisi "banyo" demektir?',
    prompt: 'banyo',
    answer: 'das Bad',
    options: ['das Bad', 'der Flur', 'das Regal', 'die Küche'],
    pronounce: ['das Bad'],
  },
  {
    id: 'p7-ev-wohnung-mc',
    day: 7, track: 'private', topicId: EV,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.ev.wohnung'],
    familyId: 'p7-ev-wohnung',
    instruction: '"die Wohnung" ne demektir?',
    prompt: 'die Wohnung',
    answer: 'ev, daire',
    options: ['ev, daire', 'koridor', 'mutfak', 'balkon'],
    pronounce: ['die Wohnung'],
  },
  {
    id: 'p7-ev-toilette-fill',
    day: 7, track: 'private', topicId: EV,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.ev.toilette'],
    familyId: 'p7-ev-toilette',
    instruction: 'Boşluğu doldur — "tuvalet" kelimesinin çoğulunu yaz:',
    prompt: 'Wir haben drei ___. (Üç tuvaletimiz var.)',
    answer: 'Toiletten',
    pronounce: ['Wir haben drei Toiletten.'],
  },
  {
    id: 'p7-ev-kochen-mc',
    day: 7, track: 'private', topicId: EV,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.ev.kueche'],
    familyId: 'p7-ev-kochen',
    instruction: 'Hangi odada yemek pişirirsin?',
    prompt: 'Hier koche ich.',
    answer: 'die Küche',
    options: ['die Küche', 'das Bad', 'der Flur', 'das Wohnzimmer'],
    pronounce: ['die Küche'],
  },
  {
    id: 'p7-ev-schlafen-mc',
    day: 7, track: 'private', topicId: EV,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.ev.schlafzimmer'],
    familyId: 'p7-ev-schlafen',
    instruction: 'Hangi oda "uyuduğun oda"dır?',
    prompt: 'yatak odası',
    answer: 'das Schlafzimmer',
    options: ['das Schlafzimmer', 'das Wohnzimmer', 'die Küche', 'das Bad'],
    pronounce: ['das Schlafzimmer'],
  },
  {
    id: 'p7-ev-listen-flur',
    day: 7, track: 'private', topicId: EV,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.ev.flur'],
    familyId: 'p7-ev-listen-flur',
    instruction: 'Duyduğun kelimeyi seç:',
    prompt: 'der Flur',
    audioText: 'der Flur',
    answer: 'der Flur',
    options: ['der Flur', 'das Bad', 'die Küche', 'der Sessel'],
    audio: { prompt: { text: 'der Flur', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p7-ev-listen-wohnzimmer',
    day: 7, track: 'private', topicId: EV,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.ev.wohnzimmer'],
    familyId: 'p7-ev-listen-wohnzimmer',
    instruction: 'Duyduğun oda adını seç:',
    prompt: 'das Wohnzimmer',
    audioText: 'das Wohnzimmer',
    answer: 'das Wohnzimmer',
    options: ['das Wohnzimmer', 'das Schlafzimmer', 'die Wohnung', 'das Waschbecken'],
    audio: { prompt: { text: 'das Wohnzimmer', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p7-ev-tr-de-kueche',
    day: 7, track: 'private', topicId: EV,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.ev.kueche', 'private.day7.tarif.hell'],
    familyId: 'p7-ev-tr-kueche',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Mutfak açık renkli. → ______',
    answer: 'Die Küche ist hell.',
    pronounce: ['Die Küche ist hell.'],
  },

  /* ================================================================
   * Mobilyalar ve Ev Eşyaları (12)
   * ================================================================ */
  {
    id: 'p7-mob-match-1',
    day: 7, track: 'private', topicId: MOB,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'private.day7.moebel.schrank',
      'private.day7.moebel.bett',
      'private.day7.moebel.sofa',
      'private.day7.moebel.sessel',
    ],
    familyId: 'p7-mob-match-1',
    instruction: 'Mobilyayı Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'der Schrank', right: 'dolap' },
      { left: 'das Bett', right: 'yatak' },
      { left: 'das Sofa', right: 'kanepe' },
      { left: 'der Sessel', right: 'koltuk' },
    ],
    pronounce: ['der Schrank', 'das Bett', 'das Sofa', 'der Sessel'],
  },
  {
    id: 'p7-mob-match-2',
    day: 7, track: 'private', topicId: MOB,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'private.day7.moebel.fernseher',
      'private.day7.moebel.teppich-regal',
      'private.day7.moebel.herd-bad',
    ],
    familyId: 'p7-mob-match-2',
    instruction: 'Ev eşyasını Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'der Fernseher', right: 'televizyon' },
      { left: 'der Teppich', right: 'halı' },
      { left: 'das Regal', right: 'raf' },
      { left: 'der Herd', right: 'ocak' },
      { left: 'die Badewanne', right: 'küvet' },
      { left: 'das Waschbecken', right: 'lavabo' },
    ],
    pronounce: ['der Fernseher', 'der Teppich', 'das Regal', 'der Herd', 'die Badewanne', 'das Waschbecken'],
  },
  {
    id: 'p7-mob-moebel-mc',
    day: 7, track: 'private', topicId: MOB,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.moebel.genel'],
    familyId: 'p7-mob-moebel',
    instruction: '"die Möbel" ne demektir?',
    prompt: 'die Möbel',
    answer: 'mobilyalar',
    options: ['mobilyalar', 'odalar', 'komşular', 'misafirler'],
    pronounce: ['die Möbel'],
  },
  {
    id: 'p7-mob-schrank-artikel',
    day: 7, track: 'private', topicId: MOB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.moebel.schrank'],
    familyId: 'p7-mob-schrank',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Schrank (dolap)',
    answer: 'der',
    validation: { noTypoTolerance: true },
    pronounce: ['der Schrank'],
  },
  {
    id: 'p7-mob-regal-artikel',
    day: 7, track: 'private', topicId: MOB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.moebel.teppich-regal'],
    familyId: 'p7-mob-regal',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Regal (raf)',
    answer: 'das',
    validation: { noTypoTolerance: true },
    pronounce: ['das Regal'],
  },
  {
    id: 'p7-mob-sessel-artikel',
    day: 7, track: 'private', topicId: MOB,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.moebel.sessel'],
    familyId: 'p7-mob-sessel',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Sessel (koltuk)',
    answer: 'der',
    validation: { noTypoTolerance: true },
    pronounce: ['der Sessel'],
  },
  {
    id: 'p7-mob-sessel-satz',
    day: 7, track: 'private', topicId: MOB,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.moebel.sessel', 'private.day7.tarif.grau'],
    familyId: 'p7-mob-sessel-satz',
    instruction: 'Boşluğu doldur — "koltuk" kelimesini yaz:',
    prompt: 'Der ___ ist grau. (Koltuk gri.)',
    answer: 'Sessel',
    pronounce: ['Der Sessel ist grau.'],
  },
  {
    id: 'p7-mob-bett-tr-de',
    day: 7, track: 'private', topicId: MOB,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.moebel.bett'],
    familyId: 'p7-mob-bett-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Yatak küçük. → ______',
    answer: 'Das Bett ist klein.',
    pronounce: ['Das Bett ist klein.'],
  },
  {
    id: 'p7-mob-fernseher-tr-de',
    day: 7, track: 'private', topicId: MOB,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.moebel.fernseher'],
    familyId: 'p7-mob-fernseher-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Televizyon büyük. → ______',
    answer: 'Der Fernseher ist groß.',
    validation: { keyboardTolerance: true },
    pronounce: ['Der Fernseher ist groß.'],
  },
  {
    id: 'p7-mob-schlafen-mc',
    day: 7, track: 'private', topicId: MOB,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.moebel.bett'],
    familyId: 'p7-mob-schlafen',
    instruction: 'Hangi eşyada uyursun?',
    prompt: 'Hier schlafe ich.',
    answer: 'das Bett',
    options: ['das Bett', 'der Schrank', 'der Herd', 'das Regal'],
    pronounce: ['das Bett'],
  },
  {
    id: 'p7-mob-auf-dem-sessel-wb',
    day: 7, track: 'private', topicId: MOB,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.moebel.auf-dem-sessel'],
    familyId: 'p7-mob-auf-dem-sessel',
    instruction: 'Türkçeden Almancaya kur — Kedi koltukta.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Kedi koltukta.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Die' }, { id: 't2', text: 'Katze' }, { id: 't3', text: 'ist' },
        { id: 't4', text: 'auf' }, { id: 't5', text: 'dem' }, { id: 't6', text: 'Sessel.' },
        { id: 't7', text: 'in' }, { id: 't8', text: 'der' },
      ],
      acceptedSequences: [['Die', 'Katze', 'ist', 'auf', 'dem', 'Sessel.']],
    },
    answer: 'Die Katze ist auf dem Sessel.',
    pronounce: ['Die Katze ist auf dem Sessel.'],
  },
  {
    id: 'p7-mob-dictation-schrank',
    day: 7, track: 'private', topicId: MOB,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.moebel.schrank'],
    familyId: 'p7-mob-dictation-schrank',
    instruction: 'Duyduğun cümleyi aynen yaz:',
    audioText: 'Der Schrank ist groß.',
    answer: 'Der Schrank ist groß.',
    validation: { keyboardTolerance: true },
    audio: { prompt: { text: 'Der Schrank ist groß.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Evi Tarif Etmek — hell / dunkel / groß / klein (9)
   * ================================================================ */
  {
    id: 'p7-tar-hell-mc',
    day: 7, track: 'private', topicId: TAR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.tarif.hell'],
    familyId: 'p7-tar-hell',
    instruction: '"hell" ne demektir?',
    prompt: 'hell',
    answer: 'açık, ferah',
    options: ['açık, ferah', 'koyu, karanlık', 'dar', 'pahalı'],
    pronounce: ['hell'],
  },
  {
    id: 'p7-tar-dunkel-mc',
    day: 7, track: 'private', topicId: TAR,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.tarif.dunkel'],
    familyId: 'p7-tar-dunkel',
    instruction: '"dunkel" ne demektir?',
    prompt: 'dunkel',
    answer: 'koyu, karanlık',
    options: ['koyu, karanlık', 'açık, ferah', 'geniş', 'serin'],
    pronounce: ['dunkel'],
  },
  {
    id: 'p7-tar-zit-fill',
    day: 7, track: 'private', topicId: TAR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.tarif.gross-klein', 'private.day7.tarif.dunkel'],
    familyId: 'p7-tar-zit',
    instruction: 'Zıt anlamlıyı yaz:',
    prompt: 'hell ↔ ___',
    answer: 'dunkel',
    pronounce: ['dunkel'],
  },
  {
    id: 'p7-tar-breit-schmal-match',
    day: 7, track: 'private', topicId: TAR,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.tarif.breit', 'private.day7.tarif.schmal', 'private.day7.tarif.kuehl', 'private.day7.tarif.grau'],
    familyId: 'p7-tar-sifat-match',
    instruction: 'Sıfatı Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'breit', right: 'geniş' },
      { left: 'schmal', right: 'dar' },
      { left: 'kühl', right: 'serin' },
      { left: 'grau', right: 'gri' },
    ],
    pronounce: ['breit', 'schmal', 'kühl', 'grau'],
  },
  {
    id: 'p7-tar-flur-schmal-fill',
    day: 7, track: 'private', topicId: TAR,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.tarif.schmal'],
    familyId: 'p7-tar-flur-schmal',
    instruction: 'Boşluğu doldur — "dar" sıfatını yaz:',
    prompt: 'Der Flur ist ___. (Koridor dar.)',
    answer: 'schmal',
    pronounce: ['Der Flur ist schmal.'],
  },
  {
    id: 'p7-tar-zimmer-dunkel-tr-de',
    day: 7, track: 'private', topicId: TAR,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.tarif.dunkel'],
    familyId: 'p7-tar-zimmer-dunkel',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Oda karanlık. → ______',
    answer: 'Das Zimmer ist dunkel.',
    pronounce: ['Das Zimmer ist dunkel.'],
  },
  {
    id: 'p7-tar-sein-sifat-mc',
    day: 7, track: 'private', topicId: TAR,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.tarif.sein-sifat'],
    familyId: 'p7-tar-sein-sifat',
    instruction: 'Hangisi doğru?',
    prompt: 'Yatak odası karanlık.',
    answer: 'Das Schlafzimmer ist dunkel.',
    options: [
      'Das Schlafzimmer ist dunkel.',
      'Das Schlafzimmer ist dunkele.',
      'Das Schlafzimmer dunkel ist.',
      'Das dunkele Schlafzimmer ist.',
    ],
    explanation: '`sein` fiilinden sonra gelen sıfat hiçbir ek almaz.',
    pronounce: ['Das Schlafzimmer ist dunkel.'],
  },
  {
    id: 'p7-tar-error-helle',
    day: 7, track: 'private', topicId: TAR,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day7.tarif.sein-sifat', 'private.day7.tarif.hell'],
    familyId: 'p7-tar-error-helle',
    instruction: 'Cümledeki hatayı düzelt:',
    prompt: 'Das Bad ist helle.',
    answer: 'Das Bad ist hell.',
    explanation: 'Yüklem sıfatı ek almaz: `hell`, `helle` değil.',
    pronounce: ['Das Bad ist hell.'],
  },
  {
    id: 'p7-tar-listen-hell-dunkel',
    day: 7, track: 'private', topicId: TAR,
    type: 'listen-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.tarif.hell'],
    familyId: 'p7-tar-listen',
    instruction: 'Duyduğun cümleyi seç:',
    prompt: 'Die Küche ist hell.',
    audioText: 'Die Küche ist hell.',
    answer: 'Die Küche ist hell.',
    options: ['Die Küche ist hell.', 'Die Küche ist dunkel.', 'Das Bad ist hell.', 'Der Flur ist hell.'],
    audio: { prompt: { text: 'Die Küche ist hell.', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Artikelden Kişi Zamirine — der/das/die (8)
   * ================================================================ */
  {
    id: 'p7-zam-match',
    day: 7, track: 'private', topicId: ZAM,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.zamir.der-er', 'private.day7.zamir.das-es', 'private.day7.zamir.die-sie'],
    familyId: 'p7-zam-match',
    instruction: 'Artikeli doğru kişi zamiriyle eşleştir.',
    pairs: [
      { left: 'der', right: 'er' },
      { left: 'das', right: 'es' },
      { left: 'die', right: 'sie' },
    ],
  },
  {
    id: 'p7-zam-der-schrank',
    day: 7, track: 'private', topicId: ZAM,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.zamir.der-er'],
    familyId: 'p7-zam-der',
    instruction: 'Hangi kişi zamiri kullanılır?',
    prompt: 'der Schrank → ___',
    answer: 'er',
    validation: { noTypoTolerance: true },
    pronounce: ['er'],
  },
  {
    id: 'p7-zam-die-kueche',
    day: 7, track: 'private', topicId: ZAM,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.zamir.die-sie'],
    familyId: 'p7-zam-die',
    instruction: 'Hangi kişi zamiri kullanılır?',
    prompt: 'die Küche → ___',
    answer: 'sie',
    validation: { noTypoTolerance: true },
    pronounce: ['sie'],
  },
  {
    id: 'p7-zam-das-bett',
    day: 7, track: 'private', topicId: ZAM,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.zamir.das-es'],
    familyId: 'p7-zam-das',
    instruction: 'Hangi kişi zamiri kullanılır?',
    prompt: 'das Bett → ___',
    answer: 'es',
    validation: { noTypoTolerance: true },
    pronounce: ['es'],
  },
  {
    id: 'p7-zam-context-schrank',
    day: 7, track: 'private', topicId: ZAM,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.zamir.cumlede'],
    familyId: 'p7-zam-context-schrank',
    instruction: 'Boşluğa doğru kişi zamirini yaz:',
    prompt: 'Der Schrank ist groß. ___ ist grau.',
    answer: 'Er',
    validation: { caseSensitive: true, noTypoTolerance: true },
    pronounce: ['Der Schrank ist groß.', 'Er ist grau.'],
  },
  {
    id: 'p7-zam-context-kueche',
    day: 7, track: 'private', topicId: ZAM,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.zamir.cumlede', 'private.day7.zamir.die-sie'],
    familyId: 'p7-zam-context-kueche',
    instruction: 'Boşluğa doğru kişi zamirini yaz:',
    prompt: 'Die Küche ist hell. ___ ist schön.',
    answer: 'Sie',
    validation: { caseSensitive: true, noTypoTolerance: true },
    pronounce: ['Die Küche ist hell.', 'Sie ist schön.'],
  },
  {
    id: 'p7-zam-context-bett',
    day: 7, track: 'private', topicId: ZAM,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.zamir.cumlede', 'private.day7.zamir.das-es'],
    familyId: 'p7-zam-context-bett',
    instruction: 'Boşluğa doğru kişi zamirini yaz:',
    prompt: 'Das Bett ist klein. ___ ist grau.',
    answer: 'Es',
    validation: { caseSensitive: true, noTypoTolerance: true },
    pronounce: ['Das Bett ist klein.', 'Es ist grau.'],
  },
  {
    id: 'p7-zam-error-teppich',
    day: 7, track: 'private', topicId: ZAM,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day7.zamir.cumlede', 'private.day7.moebel.teppich-regal'],
    familyId: 'p7-zam-error-teppich',
    instruction: 'İkinci cümledeki zamir hatasını düzelt:',
    prompt: 'Der Teppich ist breit. Sie ist grau.',
    answer: 'Der Teppich ist breit. Er ist grau.',
    explanation: '`der Teppich` eril olduğu için zamir `er` olur.',
    pronounce: ['Der Teppich ist breit. Er ist grau.'],
  },

  /* ================================================================
   * Yeni Fiiller — kennen / geben / anrufen / stellen (11)
   * ================================================================ */
  {
    id: 'p7-fii-kennen-mc',
    day: 7, track: 'private', topicId: FII,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.fiil.kennen'],
    familyId: 'p7-fii-kennen',
    instruction: '"kennen" ne demektir?',
    prompt: 'kennen',
    answer: 'tanımak',
    options: ['tanımak', 'vermek', 'koymak', 'aramak'],
    pronounce: ['kennen'],
  },
  {
    id: 'p7-fii-kennen-du-fill',
    day: 7, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.fiil.kennen-cekim'],
    familyId: 'p7-fii-kennen-cekim',
    instruction: 'Fiili doğru çek:',
    prompt: 'Du ___ meine Schwester. (kennen)',
    answer: 'kennst',
    pronounce: ['Du kennst meine Schwester.'],
  },
  {
    id: 'p7-fii-kennen-tr-de',
    day: 7, track: 'private', topicId: FII,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.fiil.kennen-cekim'],
    familyId: 'p7-fii-kennen-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Mustafa\'yı tanıyorum. → ______',
    answer: 'Ich kenne Mustafa.',
    pronounce: ['Ich kenne Mustafa.'],
  },
  {
    id: 'p7-fii-geben-mc',
    day: 7, track: 'private', topicId: FII,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.fiil.geben'],
    familyId: 'p7-fii-geben',
    instruction: '"geben" ne demektir?',
    prompt: 'geben',
    answer: 'vermek',
    options: ['vermek', 'tanımak', 'almak', 'koymak'],
    pronounce: ['geben'],
  },
  {
    id: 'p7-fii-geben-du-fill',
    day: 7, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.fiil.geben-gibt'],
    familyId: 'p7-fii-geben-du',
    instruction: 'Fiili doğru çek (dikkat: düzensiz):',
    prompt: 'Du ___ mir das Buch. (geben)',
    answer: 'gibst',
    pronounce: ['Du gibst mir das Buch.'],
  },
  {
    id: 'p7-fii-geben-er-mc',
    day: 7, track: 'private', topicId: FII,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.fiil.geben-gibt'],
    familyId: 'p7-fii-geben-er',
    instruction: '"geben" fiilinin `er` biçimi hangisidir?',
    prompt: 'er ___',
    answer: 'gibt',
    options: ['gibt', 'gebt', 'gebe', 'geben'],
    pronounce: ['er gibt'],
  },
  {
    id: 'p7-fii-es-gibt-mc',
    day: 7, track: 'private', topicId: FII,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day7.fiil.es-gibt-fark'],
    familyId: 'p7-fii-es-gibt',
    instruction: '`geben` ile `es gibt` arasındaki fark nedir?',
    prompt: 'geben ↔ es gibt',
    answer: '`geben` = vermek; `es gibt` = var (hazır kalıp)',
    options: [
      '`geben` = vermek; `es gibt` = var (hazır kalıp)',
      'İkisi de "vermek" demektir',
      '`geben` = var; `es gibt` = vermek',
      'İkisi de "almak" demektir',
    ],
  },
  {
    id: 'p7-fii-anrufen-mc',
    day: 7, track: 'private', topicId: FII,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.fiil.anrufen'],
    familyId: 'p7-fii-anrufen',
    instruction: '"anrufen" ne demektir?',
    prompt: 'anrufen',
    answer: 'telefonla aramak',
    options: ['telefonla aramak', 'tanımak', 'vermek', 'beğenmek'],
    pronounce: ['anrufen'],
  },
  {
    id: 'p7-fii-anrufen-order',
    day: 7, track: 'private', topicId: FII,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.fiil.anrufen-ayrilabilen'],
    familyId: 'p7-fii-anrufen-order',
    instruction: 'Kelimeleri doğru sıraya diz — Seni arıyorum.',
    answer: 'Ich rufe dich an.',
    pronounce: ['Ich rufe dich an.'],
  },
  {
    id: 'p7-fii-anrufen-fill-uns',
    day: 7, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['private.day7.fiil.anrufen-ayrilabilen'],
    familyId: 'p7-fii-anrufen-uns',
    instruction: 'Ayrılabilen fiilin önekini doğru yere yaz:',
    prompt: 'Du rufst uns ___. (anrufen)',
    answer: 'an',
    validation: { noTypoTolerance: true },
    pronounce: ['Du rufst uns an.'],
  },
  {
    id: 'p7-fii-stellen-fill',
    day: 7, track: 'private', topicId: FII,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.fiil.stellen', 'private.day3.kontraksiyon.ins'],
    familyId: 'p7-fii-stellen',
    instruction: 'Boşluğu doldur — "koymak" fiilini çek:',
    prompt: 'Ich ___ das Regal ins Zimmer. (stellen)',
    answer: 'stelle',
    pronounce: ['Ich stelle das Regal ins Zimmer.'],
  },
  {
    id: 'p7-fii-nicht-order',
    day: 7, track: 'private', topicId: FII,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.fiil.nicht-yeri'],
    familyId: 'p7-fii-nicht-order',
    instruction: 'Kelimeleri doğru sıraya diz — Bugün gelmiyorum.',
    answer: 'Ich komme heute nicht.',
    pronounce: ['Ich komme heute nicht.'],
  },
  {
    id: 'p7-fii-nicht-error',
    day: 7, track: 'private', topicId: FII,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day7.fiil.nicht-yeri'],
    familyId: 'p7-fii-nicht-error',
    instruction: '`nicht` yanlış yerde — cümleyi düzelt:',
    prompt: 'Ich nicht komme heute.',
    answer: 'Ich komme heute nicht.',
    explanation: '`nicht` fiilden ve zaman bilgisinden sonra, cümlenin sonuna gider.',
  },

  /* ================================================================
   * gefallen — Beğenmek (3)
   * ================================================================ */
  {
    id: 'p7-gef-anlam-mc',
    day: 7, track: 'private', topicId: GEF,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.gefallen.anlam'],
    familyId: 'p7-gef-anlam',
    instruction: '"gefallen" ne demektir?',
    prompt: 'gefallen',
    answer: 'beğenmek, hoşuna gitmek',
    options: ['beğenmek, hoşuna gitmek', 'düşmek', 'vermek', 'aramak'],
    pronounce: ['gefallen'],
  },
  {
    id: 'p7-gef-kalip-fill',
    day: 7, track: 'private', topicId: GEF,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.gefallen.kalip'],
    familyId: 'p7-gef-kalip',
    instruction: 'Kalıbı tamamla:',
    prompt: 'Das ___ mir. (Bu hoşuma gidiyor.)',
    answer: 'gefällt',
    validation: { keyboardTolerance: true },
    pronounce: ['Das gefällt mir.'],
  },
  {
    id: 'p7-gef-tr-de',
    day: 7, track: 'private', topicId: GEF,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.gefallen.kalip', 'private.day7.moebel.teppich-regal'],
    familyId: 'p7-gef-tr-de',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Halı hoşuma gidiyor. → ______',
    answer: 'Der Teppich gefällt mir.',
    validation: { keyboardTolerance: true },
    pronounce: ['Der Teppich gefällt mir.'],
  },


  /* ================================================================
   * Essen und Trinken — gern / nicht gern (11)
   * ================================================================ */
  {
    id: 'p7-ess-frage-mc',
    day: 7, track: 'private', topicId: ESS,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.essen.frage'],
    familyId: 'p7-ess-frage',
    instruction: '"Was isst du gern?" ne demektir?',
    prompt: 'Was isst du gern?',
    answer: 'Ne yemeyi seversin?',
    options: ['Ne yemeyi seversin?', 'Ne içmeyi seversin?', 'Ne kadar yiyorsun?', 'Nerede yiyorsun?'],
    pronounce: ['Was isst du gern?'],
  },
  {
    id: 'p7-ess-sie-form-fill',
    day: 7, track: 'private', topicId: ESS,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.essen.frage'],
    familyId: 'p7-ess-sie-form',
    instruction: 'Soruyu resmî (Sie) hâle çevir:',
    prompt: 'Was isst du gern? → Was ___ Sie gern?',
    answer: 'essen',
    pronounce: ['Was essen Sie gern?'],
  },
  {
    id: 'p7-ess-antwort-wb',
    day: 7, track: 'private', topicId: ESS,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.essen.antwort', 'private.day7.essen.kelimeler'],
    familyId: 'p7-ess-antwort',
    instruction: 'Türkçeden Almancaya kur — Patates kızartması yemeyi severim.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Patates kızartması yemeyi severim.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'esse' }, { id: 't3', text: 'gern' }, { id: 't4', text: 'Pommes.' },
        { id: 't5', text: 'trinke' }, { id: 't6', text: 'nicht' },
      ],
      acceptedSequences: [['Ich', 'esse', 'gern', 'Pommes.']],
    },
    answer: 'Ich esse gern Pommes.',
    pronounce: ['Ich esse gern Pommes.'],
  },
  {
    id: 'p7-ess-nicht-gern-tr-de',
    day: 7, track: 'private', topicId: ESS,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.essen.nicht-gern'],
    familyId: 'p7-ess-nicht-gern',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Pizza yemeyi sevmiyorum. → ______',
    answer: 'Ich esse nicht gern Pizza.',
    pronounce: ['Ich esse nicht gern Pizza.'],
  },
  {
    id: 'p7-ess-lieblingsessen-fill',
    day: 7, track: 'private', topicId: ESS,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.essen.lieblingsessen'],
    familyId: 'p7-ess-lieblingsessen',
    instruction: 'Soruyu tamamla:',
    prompt: 'Was ist dein ___? (En sevdiğin yemek nedir?)',
    answer: 'Lieblingsessen',
    pronounce: ['Was ist dein Lieblingsessen?'],
  },
  {
    id: 'p7-ess-lieblingsessen-antwort',
    day: 7, track: 'private', topicId: ESS,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.essen.lieblingsessen', 'private.day7.essen.kelimeler'],
    familyId: 'p7-ess-lieblingsessen-antwort',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'En sevdiğim yemek pilav. → ______',
    answer: 'Mein Lieblingsessen ist Reis.',
    pronounce: ['Mein Lieblingsessen ist Reis.'],
  },
  {
    id: 'p7-ess-trinken-frage-fill',
    day: 7, track: 'private', topicId: ESS,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.trinken.frage'],
    familyId: 'p7-ess-trinken-frage',
    instruction: 'Soruyu tamamla:',
    prompt: 'Was ___ du gern? (Ne içmeyi seversin?)',
    answer: 'trinkst',
    pronounce: ['Was trinkst du gern?'],
  },
  {
    id: 'p7-ess-trinken-antwort-tr-de',
    day: 7, track: 'private', topicId: ESS,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.trinken.frage', 'private.day7.getraenke.kelimeler'],
    familyId: 'p7-ess-trinken-antwort',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Portakal suyu içmeyi severim. → ______',
    answer: 'Ich trinke gern Orangensaft.',
    pronounce: ['Ich trinke gern Orangensaft.'],
  },
  {
    id: 'p7-ess-lieblingsgetraenk-tr-de',
    day: 7, track: 'private', topicId: ESS,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.trinken.lieblingsgetraenk', 'private.day7.getraenke.kelimeler'],
    familyId: 'p7-ess-lieblingsgetraenk',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'En sevdiğim içecek elma suyu. → ______',
    answer: 'Mein Lieblingsgetränk ist Apfelsaft.',
    validation: { keyboardTolerance: true },
    pronounce: ['Mein Lieblingsgetränk ist Apfelsaft.'],
  },
  {
    id: 'p7-ess-hunger-durst-match',
    day: 7, track: 'private', topicId: ESS,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.essen.hunger-durst'],
    familyId: 'p7-ess-hunger-durst',
    instruction: 'Kalıbı Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'Ich habe Hunger.', right: 'Acıktım.' },
      { left: 'Ich habe Durst.', right: 'Susadım.' },
    ],
    pronounce: ['Ich habe Hunger.', 'Ich habe Durst.'],
  },
  {
    id: 'p7-ess-dialog-spoken',
    day: 7, track: 'private', topicId: ESS,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day7.essen.frage', 'private.day7.trinken.frage'],
    familyId: 'p7-ess-dialog',
    instruction: 'Mini diyaloğu sesli tamamla — kendi cevabını ver.',
    prompt: 'A: Was isst du gern?\nB: ...\nA: Was trinkst du gern?\nB: ...',
    requirements: [
      '`Ich esse gern ...` kalıbıyla cevap ver.',
      '`Ich trinke gern ...` kalıbıyla cevap ver.',
      'Sevmediğin bir şeyi `nicht gern` ile söyle.',
    ],
    sampleAnswer: 'Ich esse gern Pommes. Ich trinke gern Orangensaft. Ich trinke nicht gern Kaffee.',
    audio: { targets: [{ text: 'Ich esse gern Pommes. Ich trinke gern Orangensaft. Ich trinke nicht gern Kaffee.', language: 'de-DE', role: 'example' }] },
  },

  /* ================================================================
   * Alışveriş ve Sıklık (11)
   * ================================================================ */
  {
    id: 'p7-ali-frage-mc',
    day: 7, track: 'private', topicId: ALI,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.kaufen.frage'],
    familyId: 'p7-ali-frage',
    instruction: '"Was kaufst du oft?" ne demektir?',
    prompt: 'Was kaufst du oft?',
    answer: 'Sık sık ne satın alırsın?',
    options: ['Sık sık ne satın alırsın?', 'Ne kadar ödüyorsun?', 'Nereden alışveriş yapıyorsun?', 'Ne zaman alışveriş yaparsın?'],
    pronounce: ['Was kaufst du oft?'],
  },
  {
    id: 'p7-ali-siklik-match',
    day: 7, track: 'private', topicId: ALI,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'private.day7.siklik.immer',
      'private.day7.siklik.meistens',
      'private.day7.siklik.oft',
      'private.day7.siklik.manchmal',
      'private.day7.siklik.nie',
    ],
    familyId: 'p7-ali-siklik-match',
    instruction: 'Sıklık kelimesini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'immer', right: 'her zaman' },
      { left: 'meistens', right: 'çoğunlukla' },
      { left: 'oft', right: 'sık sık' },
      { left: 'manchmal', right: 'bazen' },
      { left: 'nie', right: 'asla' },
    ],
    pronounce: ['immer', 'meistens', 'oft', 'manchmal', 'nie'],
  },
  {
    id: 'p7-ali-nie-mc',
    day: 7, track: 'private', topicId: ALI,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.siklik.nie'],
    familyId: 'p7-ali-nie',
    instruction: 'Hangisi "asla, hiç" demektir?',
    prompt: 'asla, hiç',
    answer: 'nie',
    options: ['nie', 'immer', 'oft', 'manchmal'],
    pronounce: ['nie'],
  },
  {
    id: 'p7-ali-siklik-order-mc',
    day: 7, track: 'private', topicId: ALI,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day7.siklik.immer', 'private.day7.siklik.manchmal', 'private.day7.siklik.nie'],
    familyId: 'p7-ali-siklik-order',
    instruction: 'Hangi sıralama "çoktan aza" doğrudur?',
    prompt: 'sıklık ölçeği',
    answer: 'immer → meistens → oft → manchmal → nie',
    options: [
      'immer → meistens → oft → manchmal → nie',
      'nie → immer → oft → manchmal → meistens',
      'oft → nie → immer → meistens → manchmal',
      'manchmal → immer → nie → oft → meistens',
    ],
  },
  {
    id: 'p7-ali-immer-obst-fill',
    day: 7, track: 'private', topicId: ALI,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.siklik.cumlede', 'private.day7.yiyecek.temel'],
    familyId: 'p7-ali-immer-obst',
    instruction: 'Boşluğu doldur — "her zaman" kelimesini yaz:',
    prompt: 'Ich kaufe ___ Obst. (Her zaman meyve alırım.)',
    answer: 'immer',
    pronounce: ['Ich kaufe immer Obst.'],
  },
  {
    id: 'p7-ali-manchmal-tr-de',
    day: 7, track: 'private', topicId: ALI,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.siklik.manchmal', 'private.day7.yiyecek.temel'],
    familyId: 'p7-ali-manchmal',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bazen şarap alırım. → ______',
    answer: 'Ich kaufe manchmal Wein.',
    pronounce: ['Ich kaufe manchmal Wein.'],
  },
  {
    id: 'p7-ali-nie-tr-de',
    day: 7, track: 'private', topicId: ALI,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.siklik.nie'],
    familyId: 'p7-ali-nie-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Hiç un almam. → ______',
    answer: 'Ich kaufe nie Mehl.',
    pronounce: ['Ich kaufe nie Mehl.'],
  },
  {
    id: 'p7-ali-meistens-order',
    day: 7, track: 'private', topicId: ALI,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.siklik.meistens', 'private.day7.yiyecek.temel'],
    familyId: 'p7-ali-meistens-order',
    instruction: 'Kelimeleri doğru sıraya diz — Çoğunlukla sebze alırım.',
    answer: 'Ich kaufe meistens Gemüse.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich kaufe meistens Gemüse.'],
  },
  {
    id: 'p7-ali-pro-woche-fill',
    day: 7, track: 'private', topicId: ALI,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['private.day7.kaufen.pro-woche'],
    familyId: 'p7-ali-pro-woche',
    instruction: 'Boşluğu doldur — "haftada iki kez" ifadesini tamamla:',
    prompt: 'Ich kaufe pro Woche ___. (haftada iki kez)',
    answer: 'zweimal',
    pronounce: ['Ich kaufe pro Woche zweimal.'],
  },
  {
    id: 'p7-ali-zettel-wagen-match',
    day: 7, track: 'private', topicId: ALI,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.alisveris.einkaufszettel', 'private.day7.alisveris.einkaufswagen'],
    familyId: 'p7-ali-zettel-wagen',
    instruction: 'Alışveriş kelimesini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'der Einkaufszettel', right: 'alışveriş listesi' },
      { left: 'der Einkaufswagen', right: 'alışveriş arabası' },
    ],
    pronounce: ['der Einkaufszettel', 'der Einkaufswagen'],
  },
  {
    id: 'p7-ali-ifadeler-mc',
    day: 7, track: 'private', topicId: ALI,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.alisveris.ifadeler'],
    familyId: 'p7-ali-ifadeler',
    instruction: 'Satıcı "Sonst noch etwas?" diyor. Ne soruyor?',
    prompt: 'Sonst noch etwas?',
    answer: 'Başka bir şey var mı?',
    options: ['Başka bir şey var mı?', 'Kaç para?', 'Nakit mi kart mı?', 'Poşet ister misiniz?'],
    pronounce: ['Sonst noch etwas?'],
  },
  {
    id: 'p7-ali-natuerlich-fill',
    day: 7, track: 'private', topicId: ALI,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.alisveris.ifadeler'],
    familyId: 'p7-ali-natuerlich',
    instruction: 'Boşluğu doldur — "tabii ki" kelimesini yaz:',
    prompt: '___ (Tabii ki.)',
    answer: 'Natürlich',
    validation: { keyboardTolerance: true },
    pronounce: ['Natürlich.'],
  },


  /* ================================================================
   * Miktar ve Paket Kelimeleri (7)
   * ================================================================ */
  {
    id: 'p7-mik-match',
    day: 7, track: 'private', topicId: MIK,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'private.day7.miktar.flasche',
      'private.day7.miktar.packung',
      'private.day7.miktar.dose',
      'private.day7.miktar.becher',
    ],
    familyId: 'p7-mik-match',
    instruction: 'Miktar kalıbını Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'eine Flasche', right: 'bir şişe' },
      { left: 'eine Packung', right: 'bir paket' },
      { left: 'eine Dose', right: 'bir kutu (konserve)' },
      { left: 'ein Becher', right: 'bir kutu (krema)' },
    ],
    pronounce: ['eine Flasche', 'eine Packung', 'eine Dose', 'ein Becher'],
  },
  {
    id: 'p7-mik-becher-fill',
    day: 7, track: 'private', topicId: MIK,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.miktar.becher', 'private.day7.yiyecek.sahne'],
    familyId: 'p7-mik-becher',
    instruction: 'Boşluğu doldur:',
    prompt: 'ein Becher ___ (bir kutu krema)',
    answer: 'Sahne',
    pronounce: ['ein Becher Sahne'],
  },
  {
    id: 'p7-mik-dose-tr-de',
    day: 7, track: 'private', topicId: MIK,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.miktar.dose', 'private.day7.yiyecek.sahne'],
    familyId: 'p7-mik-dose',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'bir kutu domates → ______',
    answer: 'eine Dose Tomaten',
    pronounce: ['eine Dose Tomaten'],
  },
  {
    id: 'p7-mik-packung-tr-de',
    day: 7, track: 'private', topicId: MIK,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.miktar.packung'],
    familyId: 'p7-mik-packung',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'bir paket un → ______',
    answer: 'eine Packung Mehl',
    pronounce: ['eine Packung Mehl'],
  },
  {
    id: 'p7-mik-bund-fill',
    day: 7, track: 'private', topicId: MIK,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['private.day7.miktar.bund', 'private.day7.yiyecek.zwiebel'],
    familyId: 'p7-mik-bund',
    instruction: 'Boşluğu doldur — "demet" kelimesini yaz:',
    prompt: 'ein ___ Frühlingszwiebeln (bir demet taze soğan)',
    answer: 'Bund',
    pronounce: ['ein Bund Frühlingszwiebeln'],
  },
  {
    id: 'p7-mik-portion-mc',
    day: 7, track: 'private', topicId: MIK,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.miktar.portion', 'private.day7.yiyecek.haehnchen'],
    familyId: 'p7-mik-portion',
    instruction: '"eine Portion Gemüsesuppe" ne demektir?',
    prompt: 'eine Portion Gemüsesuppe',
    answer: 'bir porsiyon sebze çorbası',
    options: ['bir porsiyon sebze çorbası', 'bir kutu sebze konservesi', 'bir paket sebze', 'bir şişe sebze suyu'],
    pronounce: ['eine Portion Gemüsesuppe'],
  },
  {
    id: 'p7-mik-artikel-mc',
    day: 7, track: 'private', topicId: MIK,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day7.miktar.artikel'],
    familyId: 'p7-mik-artikel',
    instruction: '`ein` mi `eine` mi? Doğru olanı seç.',
    prompt: '___ Flasche Wasser (der Becher / die Flasche)',
    answer: 'eine',
    options: ['eine', 'ein', 'einen', 'einem'],
    explanation: '`die Flasche` dişil olduğu için `eine Flasche`.',
    pronounce: ['eine Flasche Wasser'],
  },

  /* ================================================================
   * Yeni Yiyecek Kelimeleri (9)
   * ================================================================ */
  {
    id: 'p7-yiy-temel-match',
    day: 7, track: 'private', topicId: YIY,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.yiyecek.temel', 'private.day7.yiyecek.zwiebel'],
    familyId: 'p7-yiy-temel-match',
    instruction: 'Yiyeceği Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'das Fleisch', right: 'et' },
      { left: 'der Wein', right: 'şarap' },
      { left: 'das Obst', right: 'meyve' },
      { left: 'das Gemüse', right: 'sebze' },
      { left: 'die Zwiebel', right: 'soğan' },
    ],
    pronounce: ['das Fleisch', 'der Wein', 'das Obst', 'das Gemüse', 'die Zwiebel'],
  },
  {
    id: 'p7-yiy-gurke-match',
    day: 7, track: 'private', topicId: YIY,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.yiyecek.gurke', 'private.day7.yiyecek.essig', 'private.day7.yiyecek.oel-pfeffer'],
    familyId: 'p7-yiy-gurke-match',
    instruction: 'Salata ve baharat kelimelerini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'die Salatgurke', right: 'salatalık' },
      { left: 'saure Gurken', right: 'turşu' },
      { left: 'der Essig', right: 'sirke' },
      { left: 'das Öl', right: 'yağ' },
      { left: 'der Pfeffer', right: 'kara biber' },
    ],
    pronounce: ['die Salatgurke', 'saure Gurken', 'der Essig', 'das Öl', 'der Pfeffer'],
  },
  {
    id: 'p7-yiy-nuesse-match',
    day: 7, track: 'private', topicId: YIY,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.yiyecek.nuesse', 'private.day7.yiyecek.haehnchen'],
    familyId: 'p7-yiy-nuesse-match',
    instruction: 'Kuruyemiş, tatlı ve et kelimelerini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'die Nüsse', right: 'kuruyemiş' },
      { left: 'die Rosinen', right: 'kuru üzüm' },
      { left: 'der Staubzucker', right: 'pudra şekeri' },
      { left: 'das Hähnchen', right: 'tavuk' },
    ],
    pronounce: ['die Nüsse', 'die Rosinen', 'der Staubzucker', 'das Hähnchen'],
  },
  {
    id: 'p7-yiy-zwiebel-artikel',
    day: 7, track: 'private', topicId: YIY,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.yiyecek.zwiebel'],
    familyId: 'p7-yiy-zwiebel',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Zwiebel (soğan)',
    answer: 'die',
    validation: { noTypoTolerance: true },
    pronounce: ['die Zwiebel'],
  },
  {
    id: 'p7-yiy-oel-artikel',
    day: 7, track: 'private', topicId: YIY,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.yiyecek.oel-pfeffer'],
    familyId: 'p7-yiy-oel',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Öl (yağ)',
    answer: 'das',
    validation: { noTypoTolerance: true },
    pronounce: ['das Öl'],
  },
  {
    id: 'p7-yiy-knoblauch-mc',
    day: 7, track: 'private', topicId: YIY,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.yiyecek.zwiebel'],
    familyId: 'p7-yiy-knoblauch',
    instruction: '"die Knoblauchzehe" ne demektir?',
    prompt: 'die Knoblauchzehe',
    answer: 'sarımsak dişi',
    options: ['sarımsak dişi', 'soğan halkası', 'taze soğan', 'salatalık'],
    pronounce: ['die Knoblauchzehe'],
  },
  {
    id: 'p7-yiy-kaese-mc',
    day: 7, track: 'private', topicId: YIY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.yiyecek.sahne'],
    familyId: 'p7-yiy-kaese',
    instruction: '"der Käse" ne demektir?',
    prompt: 'der Käse',
    answer: 'peynir',
    options: ['peynir', 'krema', 'süt', 'tereyağı'],
    pronounce: ['der Käse'],
  },
  {
    id: 'p7-yiy-listen-gemuese',
    day: 7, track: 'private', topicId: YIY,
    type: 'listen-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.yiyecek.temel'],
    familyId: 'p7-yiy-listen-gemuese',
    instruction: 'Duyduğun kelimeyi seç:',
    prompt: 'das Gemüse',
    audioText: 'das Gemüse',
    answer: 'das Gemüse',
    options: ['das Gemüse', 'das Obst', 'das Fleisch', 'der Käse'],
    audio: { prompt: { text: 'das Gemüse', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p7-yiy-dictation-haehnchen',
    day: 7, track: 'private', topicId: YIY,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.yiyecek.haehnchen'],
    familyId: 'p7-yiy-dictation',
    instruction: 'Duyduğun kelimeyi artikeliyle birlikte yaz:',
    audioText: 'das Hähnchen',
    answer: 'das Hähnchen',
    validation: { keyboardTolerance: true },
    audio: { prompt: { text: 'das Hähnchen', language: 'de-DE', role: 'prompt' } },
  },

  /* ================================================================
   * Fiyat Sormak (5)
   * ================================================================ */
  {
    id: 'p7-fiy-kosten-mc',
    day: 7, track: 'private', topicId: FIY,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.fiyat.kosten'],
    familyId: 'p7-fiy-kosten',
    instruction: '"kosten" ne demektir?',
    prompt: 'kosten',
    answer: 'fiyatında olmak (kaç para tutmak)',
    options: ['fiyatında olmak (kaç para tutmak)', 'satın almak', 'ödemek', 'saymak'],
    pronounce: ['kosten'],
  },
  {
    id: 'p7-fiy-was-kostet-fill',
    day: 7, track: 'private', topicId: FIY,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.fiyat.was-kostet'],
    familyId: 'p7-fiy-was-kostet',
    instruction: 'Soruyu tamamla:',
    prompt: 'Was ___ das? (Bu kaç para?)',
    answer: 'kostet',
    pronounce: ['Was kostet das?'],
  },
  {
    id: 'p7-fiy-antwort-wb',
    day: 7, track: 'private', topicId: FIY,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.fiyat.antwort'],
    familyId: 'p7-fiy-antwort',
    instruction: 'Türkçeden Almancaya kur — Bu beş euro.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Bu beş euro.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Das' }, { id: 't2', text: 'kostet' }, { id: 't3', text: 'fünf' }, { id: 't4', text: 'Euro.' },
        { id: 't5', text: 'ist' }, { id: 't6', text: 'vier' },
      ],
      acceptedSequences: [['Das', 'kostet', 'fünf', 'Euro.'], ['Das', 'ist', 'fünf', 'Euro.']],
    },
    answer: 'Das kostet fünf Euro.',
    validation: { keyboardTolerance: true },
    pronounce: ['Das kostet fünf Euro.'],
  },
  {
    id: 'p7-fiy-wie-viel-tr-de',
    day: 7, track: 'private', topicId: FIY,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.fiyat.wie-viel'],
    familyId: 'p7-fiy-wie-viel',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bir kilo domates kaç para? → ______',
    answer: 'Wie viel kostet ein Kilo Tomaten?',
    pronounce: ['Wie viel kostet ein Kilo Tomaten?'],
  },
  {
    id: 'p7-fiy-teuer-fill',
    day: 7, track: 'private', topicId: FIY,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.fiyat.teuer', 'private.day7.yiyecek.temel'],
    familyId: 'p7-fiy-teuer',
    instruction: 'Boşluğu doldur — "pahalı" sıfatını yaz:',
    prompt: 'Der Wein ist ___. (Şarap pahalı.)',
    answer: 'teuer',
    pronounce: ['Der Wein ist teuer.'],
  },

  /* ================================================================
   * brauchen — İhtiyaç Duymak (3)
   * ================================================================ */
  {
    id: 'p7-bra-frage-mc',
    day: 7, track: 'private', topicId: BRA,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.brauchen.frage'],
    familyId: 'p7-bra-frage',
    instruction: '"Was brauchst du?" ne demektir?',
    prompt: 'Was brauchst du?',
    answer: 'Neye ihtiyacın var?',
    options: ['Neye ihtiyacın var?', 'Ne yapıyorsun?', 'Ne alıyorsun?', 'Ne kadar lazım?'],
    pronounce: ['Was brauchst du?'],
  },
  {
    id: 'p7-bra-antwort-fill',
    day: 7, track: 'private', topicId: BRA,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.brauchen.antwort'],
    familyId: 'p7-bra-antwort',
    instruction: 'Fiili doğru çek:',
    prompt: 'Ich ___ den Apfel. (brauchen)',
    answer: 'brauche',
    pronounce: ['Ich brauche den Apfel.'],
  },
  {
    id: 'p7-bra-kein-tr-de',
    day: 7, track: 'private', topicId: BRA,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.brauchen.kein'],
    familyId: 'p7-bra-kein',
    instruction: 'Türkçeden Almancaya çevir (olumsuz cevap):',
    prompt: 'Hayır, una ihtiyacım yok. → ______',
    answer: 'Nein, ich brauche kein Mehl.',
    pronounce: ['Nein, ich brauche kein Mehl.'],
  },

  /* ================================================================
   * Günlük Hayattan Yeni Kelimeler (7)
   * ================================================================ */
  {
    id: 'p7-kel-match-1',
    day: 7, track: 'private', topicId: KEL,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.kelime.gluecklich', 'private.day7.kelime.gast-leute'],
    familyId: 'p7-kel-match-1',
    instruction: 'Duygu ve kişi kelimelerini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'glücklich', right: 'mutlu' },
      { left: 'der Traum', right: 'hayal' },
      { left: 'der Gast', right: 'misafir' },
      { left: 'die Leute', right: 'insanlar' },
    ],
    pronounce: ['glücklich', 'der Traum', 'der Gast', 'die Leute'],
  },
  {
    id: 'p7-kel-match-2',
    day: 7, track: 'private', topicId: KEL,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.kelime.fuer-dafuer', 'private.day7.kelime.nur-etwas-viele', 'private.day7.kelime.dazu-fertig-schmeckt'],
    familyId: 'p7-kel-match-2',
    instruction: 'Küçük yardımcı kelimeleri Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'für', right: 'için' },
      { left: 'dafür', right: 'bunun için' },
      { left: 'nur', right: 'sadece' },
      { left: 'viele', right: 'bir çok' },
      { left: 'fertig', right: 'hazır' },
    ],
    pronounce: ['für', 'dafür', 'nur', 'viele', 'fertig'],
  },
  {
    id: 'p7-kel-zusammen-fill',
    day: 7, track: 'private', topicId: KEL,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.kelime.zusammen-dort'],
    familyId: 'p7-kel-zusammen',
    instruction: 'Boşluğu doldur — "birlikte" kelimesini yaz:',
    prompt: 'Wir essen ___. (Birlikte yiyoruz.)',
    answer: 'zusammen',
    pronounce: ['Wir essen zusammen.'],
  },
  {
    id: 'p7-kel-dort-fill',
    day: 7, track: 'private', topicId: KEL,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.kelime.zusammen-dort', 'private.day7.moebel.teppich-regal'],
    familyId: 'p7-kel-dort',
    instruction: 'Boşluğu doldur — "orada" kelimesini yaz:',
    prompt: 'Das Regal ist ___. (Raf orada.)',
    answer: 'dort',
    pronounce: ['Das Regal ist dort.'],
  },
  {
    id: 'p7-kel-auch-mc',
    day: 7, track: 'private', topicId: KEL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.kelime.auch'],
    familyId: 'p7-kel-auch',
    instruction: '"auch" ne demektir?',
    prompt: 'auch',
    answer: 'de, da, ayrıca',
    options: ['de, da, ayrıca', 'ama', 'çünkü', 'sadece'],
    pronounce: ['auch'],
  },
  {
    id: 'p7-kel-gluecklich-tr-de',
    day: 7, track: 'private', topicId: KEL,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.kelime.gluecklich'],
    familyId: 'p7-kel-gluecklich-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Mutluyum. → ______',
    answer: 'Ich bin glücklich.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich bin glücklich.'],
  },
  {
    id: 'p7-kel-mensa-mc',
    day: 7, track: 'private', topicId: KEL,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.kelime.gast-leute'],
    familyId: 'p7-kel-mensa',
    instruction: '"in der Mensa" ne demektir?',
    prompt: 'in der Mensa',
    answer: 'yemekhanede',
    options: ['yemekhanede', 'markette', 'mutfakta', 'salonda'],
    pronounce: ['in der Mensa'],
  },
  {
    id: 'p7-kel-schmeckt-fill',
    day: 7, track: 'private', topicId: KEL,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['private.day7.kelime.dazu-fertig-schmeckt', 'private.day7.yiyecek.haehnchen'],
    familyId: 'p7-kel-schmeckt',
    instruction: 'Boşluğu doldur — "tadı güzel" fiilini yaz:',
    prompt: 'Die Gemüsesuppe ___ gut. (Sebze çorbasının tadı güzel.)',
    answer: 'schmeckt',
    pronounce: ['Die Gemüsesuppe schmeckt gut.'],
  },


  /* ================================================================
   * Evimi Anlatmak İçin Cümle Kalıpları (5)
   * ================================================================ */
  {
    id: 'p7-kal-wir-haben-mc',
    day: 7, track: 'private', topicId: KAL,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['private.day7.kalip.wir-haben'],
    familyId: 'p7-kal-wir-haben',
    instruction: 'Evde ne olduğunu söylemek için hangi kalıbı kullanırsın?',
    prompt: 'Mutfağımız var.',
    answer: 'Wir haben eine Küche.',
    options: ['Wir haben eine Küche.', 'Wir sind eine Küche.', 'Wir eine Küche haben.', 'Unser Küche ist.'],
    pronounce: ['Wir haben eine Küche.'],
  },
  {
    id: 'p7-kal-ist-sifat-fill',
    day: 7, track: 'private', topicId: KAL,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['private.day7.kalip.ist-sifat'],
    familyId: 'p7-kal-ist-sifat',
    instruction: 'Tarif kalıbını tamamla:',
    prompt: 'Das Wohnzimmer ___ groß. (Salon büyük.)',
    answer: 'ist',
    validation: { noTypoTolerance: true },
    pronounce: ['Das Wohnzimmer ist groß.'],
  },
  {
    id: 'p7-kal-hat-auch-order',
    day: 7, track: 'private', topicId: KAL,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.kalip.hat-auch'],
    familyId: 'p7-kal-hat-auch',
    instruction: 'Kelimeleri doğru sıraya diz — Kedimin de bir odası var.',
    answer: 'Meine Katze hat auch ein Zimmer.',
    pronounce: ['Meine Katze hat auch ein Zimmer.'],
  },
  {
    id: 'p7-kal-es-gibt-tr-de',
    day: 7, track: 'private', topicId: KAL,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.kalip.es-gibt', 'private.day7.ev.wohnzimmer'],
    familyId: 'p7-kal-es-gibt',
    instruction: 'Türkçeden Almancaya çevir (`es gibt` kalıbıyla):',
    prompt: 'Salonda bir balkon var. → ______',
    answer: 'Im Wohnzimmer gibt es einen Balkon.',
    hint: '`der Balkon` eril → `einen`.',
    pronounce: ['Im Wohnzimmer gibt es einen Balkon.'],
  },
  {
    id: 'p7-kal-sira-mc',
    day: 7, track: 'private', topicId: KAL,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.kalip.sira'],
    familyId: 'p7-kal-sira',
    instruction: 'Evini anlatırken önerilen sıra hangisidir?',
    prompt: 'anlatım sırası',
    answer: 'odalar ve tuvaletler → benim odam → ablamın odası → salon ve balkon → mutfak → kedi',
    options: [
      'odalar ve tuvaletler → benim odam → ablamın odası → salon ve balkon → mutfak → kedi',
      'kedi → mutfak → benim odam → tuvaletler',
      'mutfak → tuvaletler → kedi → balkon',
      'balkon → kedi → benim odam → salon',
    ],
  },

  /* ================================================================
   * Evimi Anlatıyorum — Meine Wohnung (16)
   * Aşamalı ilerleme: tanıma → küçük cümle → kelime bankası →
   * Türkçe→Almanca → doğru/yanlış → hata düzeltme → serbest üretim.
   * ================================================================ */
  {
    id: 'p7-evim-toiletten-tr-de',
    day: 7, track: 'private', topicId: EVIM,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.evim.toiletten'],
    familyId: 'p7-evim-toiletten',
    instruction: 'Kendi evinden bahsediyorsun. Türkçeden Almancaya çevir:',
    prompt: 'Evimizde üç tuvalet var. → ______',
    answer: 'Wir haben drei Toiletten.',
    pronounce: ['Wir haben drei Toiletten.'],
  },
  {
    id: 'p7-evim-ich-habe-zimmer-wb',
    day: 7, track: 'private', topicId: EVIM,
    type: 'word-bank-translation', difficulty: 'easy', skill: 'production',
    conceptIds: ['private.day7.evim.model'],
    familyId: 'p7-evim-ich-habe-zimmer',
    instruction: 'Türkçeden Almancaya kur — Benim bir odam var.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Benim bir odam var.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'habe' }, { id: 't3', text: 'ein' }, { id: 't4', text: 'Zimmer.' },
        { id: 't5', text: 'bin' }, { id: 't6', text: 'eine' },
      ],
      acceptedSequences: [['Ich', 'habe', 'ein', 'Zimmer.']],
    },
    answer: 'Ich habe ein Zimmer.',
    pronounce: ['Ich habe ein Zimmer.'],
  },
  {
    id: 'p7-evim-schwester-wb',
    day: 7, track: 'private', topicId: EVIM,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.evim.schwester'],
    familyId: 'p7-evim-schwester',
    instruction: 'Türkçeden Almancaya kur — Ablamın da bir odası var.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ablamın da bir odası var.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Meine' }, { id: 't2', text: 'Schwester' }, { id: 't3', text: 'hat' },
        { id: 't4', text: 'auch' }, { id: 't5', text: 'ein' }, { id: 't6', text: 'Zimmer.' },
        { id: 't7', text: 'ist' }, { id: 't8', text: 'und' },
      ],
      acceptedSequences: [['Meine', 'Schwester', 'hat', 'auch', 'ein', 'Zimmer.']],
    },
    answer: 'Meine Schwester hat auch ein Zimmer.',
    pronounce: ['Meine Schwester hat auch ein Zimmer.'],
  },
  {
    id: 'p7-evim-ihr-zimmer-hell-fill',
    day: 7, track: 'private', topicId: EVIM,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['private.day7.evim.ihr-zimmer'],
    familyId: 'p7-evim-ihr-zimmer-hell',
    instruction: 'Boşluğu doldur — "onun (ablamın)" iyelik zamirini yaz:',
    prompt: '___ Zimmer ist hell. (Onun odası açık renkli.)',
    answer: 'Ihr',
    validation: { caseSensitive: true, noTypoTolerance: true },
    pronounce: ['Ihr Zimmer ist hell.'],
  },
  {
    id: 'p7-evim-ihr-zimmer-gross-tr-de',
    day: 7, track: 'private', topicId: EVIM,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.evim.ihr-zimmer'],
    familyId: 'p7-evim-ihr-zimmer-gross',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onun odası büyük. → ______',
    answer: 'Ihr Zimmer ist groß.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ihr Zimmer ist groß.'],
  },
  {
    id: 'p7-evim-mein-zimmer-grau-tr-de',
    day: 7, track: 'private', topicId: EVIM,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.evim.mein-zimmer'],
    familyId: 'p7-evim-mein-zimmer-grau',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Benim odam gri. → ______',
    answer: 'Mein Zimmer ist grau.',
    pronounce: ['Mein Zimmer ist grau.'],
  },
  {
    id: 'p7-evim-mein-zimmer-dunkel-order',
    day: 7, track: 'private', topicId: EVIM,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.evim.mein-zimmer', 'private.day7.tarif.dunkel'],
    familyId: 'p7-evim-mein-zimmer-dunkel',
    instruction: 'Kelimeleri doğru sıraya diz — Benim odam karanlık ve küçük.',
    answer: 'Mein Zimmer ist dunkel und klein.',
    pronounce: ['Mein Zimmer ist dunkel und klein.'],
  },
  {
    id: 'p7-evim-wohnzimmer-tr-de',
    day: 7, track: 'private', topicId: EVIM,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.evim.wohnzimmer'],
    familyId: 'p7-evim-wohnzimmer',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Salonumuz var. → ______',
    answer: 'Wir haben ein Wohnzimmer.',
    pronounce: ['Wir haben ein Wohnzimmer.'],
  },
  {
    id: 'p7-evim-balkon-fill',
    day: 7, track: 'private', topicId: EVIM,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['private.day7.evim.balkon'],
    familyId: 'p7-evim-balkon',
    instruction: 'Boşluğa doğru belirsiz artikeli yaz (`der Balkon` → Akkusativ):',
    prompt: 'Wir haben ___ Balkon. (Balkonumuz var.)',
    answer: 'einen',
    validation: { noTypoTolerance: true },
    explanation: '`haben` nesneyi Akkusativ ister; eril `ein` → `einen`.',
    pronounce: ['Wir haben einen Balkon.'],
  },
  {
    id: 'p7-evim-balkon-gross-tr-de',
    day: 7, track: 'private', topicId: EVIM,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['private.day7.evim.balkon', 'private.day7.tarif.gross-klein'],
    familyId: 'p7-evim-balkon-gross',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Balkon büyük. → ______',
    answer: 'Der Balkon ist groß.',
    validation: { keyboardTolerance: true },
    pronounce: ['Der Balkon ist groß.'],
  },
  {
    id: 'p7-evim-kueche-unsere-tr-de',
    day: 7, track: 'private', topicId: EVIM,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.evim.kueche'],
    familyId: 'p7-evim-kueche-unsere',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Mutfağımız ferah. → ______',
    answer: 'Unsere Küche ist hell.',
    hint: '"ferah / açık renkli" için bugünkü kelime: `hell`.',
    pronounce: ['Unsere Küche ist hell.'],
  },
  {
    id: 'p7-evim-katze-wb',
    day: 7, track: 'private', topicId: EVIM,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.evim.katze'],
    familyId: 'p7-evim-katze',
    instruction: 'Türkçeden Almancaya kur — Kedimizin de bir odası var.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Kedimizin de bir odası var.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Unsere' }, { id: 't2', text: 'Katze' }, { id: 't3', text: 'hat' },
        { id: 't4', text: 'auch' }, { id: 't5', text: 'ein' }, { id: 't6', text: 'Zimmer.' },
        { id: 't7', text: 'Unser' }, { id: 't8', text: 'ist' },
      ],
      acceptedSequences: [['Unsere', 'Katze', 'hat', 'auch', 'ein', 'Zimmer.']],
    },
    answer: 'Unsere Katze hat auch ein Zimmer.',
    pronounce: ['Unsere Katze hat auch ein Zimmer.'],
  },
  {
    id: 'p7-evim-richtig-falsch-mein-zimmer',
    day: 7, track: 'private', topicId: EVIM,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['private.day7.evim.mein-zimmer'],
    familyId: 'p7-evim-rf-mein-zimmer',
    instruction: 'Kendi evine göre doğru mu yanlış mı? (Senin odan gri ve karanlık.)',
    prompt: 'Mein Zimmer ist hell.',
    answer: 'falsch — Mein Zimmer ist dunkel.',
    options: [
      'falsch — Mein Zimmer ist dunkel.',
      'richtig — Mein Zimmer ist hell.',
      'falsch — Mein Zimmer ist groß.',
      'richtig — Mein Zimmer ist grau und hell.',
    ],
    pronounce: ['Mein Zimmer ist dunkel.'],
  },
  {
    id: 'p7-evim-error-kueche-dunkel',
    day: 7, track: 'private', topicId: EVIM,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day7.evim.kueche', 'private.day7.tarif.hell'],
    familyId: 'p7-evim-error-kueche',
    instruction: 'Evinin bilgisine göre cümle yanlış — düzelt: (Mutfağınız açık renkli ve ferah.)',
    prompt: 'Unsere Küche ist dunkel.',
    answer: 'Unsere Küche ist hell.',
    pronounce: ['Unsere Küche ist hell.'],
  },
  {
    id: 'p7-evim-error-schwester-klein',
    day: 7, track: 'private', topicId: EVIM,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['private.day7.evim.ihr-zimmer', 'private.day7.evim.karsilastirma-yok'],
    familyId: 'p7-evim-error-schwester',
    instruction: 'Evinin bilgisine göre cümle yanlış — düzelt: (Ablanın odası büyük.)',
    prompt: 'Ihr Zimmer ist klein.',
    answer: 'Ihr Zimmer ist groß.',
    validation: { keyboardTolerance: true },
    explanation: 'Karşılaştırma eki henüz öğrenilmedi; bilgiyi iki ayrı cümleyle veriyoruz: `Ihr Zimmer ist groß.` + `Mein Zimmer ist klein.`',
    pronounce: ['Ihr Zimmer ist groß.'],
  },
  {
    id: 'p7-evim-karsilastirma-mc',
    day: 7, track: 'private', topicId: EVIM,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['private.day7.evim.karsilastirma-yok'],
    familyId: 'p7-evim-karsilastirma',
    instruction: '"Ablamın odası benim odamdan daha büyük." fikrini bugünkü bilgiyle nasıl söylersin?',
    prompt: 'Ablamın odası daha büyük.',
    answer: 'Ihr Zimmer ist groß. Mein Zimmer ist klein.',
    options: [
      'Ihr Zimmer ist groß. Mein Zimmer ist klein.',
      'Ihr Zimmer ist mehr groß.',
      'Ihr Zimmer groß ist, mein Zimmer klein ist.',
      'Ihr Zimmer ist groß und klein.',
    ],
    explanation: 'Türkçedeki "daha büyük" için Almancada ayrı bir karşılaştırma eki gerekir; o ek 1–7. Günlerde öğretilmedi. Aynı anlamı iki basit cümleyle koruruz.',
    pronounce: ['Ihr Zimmer ist groß.', 'Mein Zimmer ist klein.'],
  },
  {
    id: 'p7-evim-dictation-model',
    day: 7, track: 'private', topicId: EVIM,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['private.day7.evim.model'],
    familyId: 'p7-evim-dictation',
    instruction: 'Evini anlatan cümleyi duy ve aynen yaz:',
    audioText: 'Wir haben eine Wohnung.',
    answer: 'Wir haben eine Wohnung.',
    audio: { prompt: { text: 'Wir haben eine Wohnung.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p7-evim-spoken-kisa',
    day: 7, track: 'private', topicId: EVIM,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['private.day7.evim.model', 'private.day7.evim.toiletten', 'private.day7.evim.mein-zimmer'],
    familyId: 'p7-evim-spoken-kisa',
    instruction: 'Evini 4–6 cümleyle sesli anlat. İpuçları aşağıda.',
    prompt: 'Toiletten:\nmein Zimmer:\nWohnzimmer:\nKüche:',
    requirements: [
      'Kaç tuvaletiniz olduğunu söyle (`Wir haben ...`).',
      'Kendi odanı iki sıfatla tarif et (`Mein Zimmer ist ...`).',
      'Salondan ve mutfaktan bahset.',
    ],
    sampleAnswer: 'Wir haben drei Toiletten. Mein Zimmer ist grau und klein. Wir haben ein Wohnzimmer. Unsere Küche ist hell.',
    audio: { targets: [{ text: 'Wir haben drei Toiletten. Mein Zimmer ist grau und klein. Wir haben ein Wohnzimmer. Unsere Küche ist hell.', language: 'de-DE', role: 'example' }] },
  },
  {
    id: 'p7-evim-free-tam-anlatim',
    day: 7, track: 'private', topicId: EVIM,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [
      'private.day7.evim.model',
      'private.day7.evim.toiletten',
      'private.day7.evim.schwester',
      'private.day7.evim.balkon',
      'private.day7.evim.katze',
    ],
    familyId: 'p7-evim-free-tam',
    openEnded: true,
    instruction: 'Evini Almanca olarak anlat. En az sekiz cümle yaz — ipuçları aşağıda.',
    prompt: 'Toiletten:\nmein Zimmer:\nZimmer meiner Schwester:\nWohnzimmer:\nBalkon:\nKüche:\nKatze:',
    hint: 'Sadece `Wir haben ...`, `Ich habe ...`, `... ist ...` ve `... hat auch ...` kalıplarını kullan. Karşılaştırma yapma.',
    answer: 'Wir haben eine Wohnung. Wir haben drei Toiletten. Ich habe ein Zimmer. Meine Schwester hat auch ein Zimmer. Ihr Zimmer ist hell und groß. Mein Zimmer ist grau, dunkel und klein. Wir haben ein Wohnzimmer. Wir haben einen Balkon. Der Balkon ist groß. Wir haben eine Küche. Unsere Küche ist hell. Wir haben eine Katze. Unsere Katze hat auch ein Zimmer.',
    explanation: 'Kanonik A1 model: karşılaştırma, genitif ve yan cümle içermez — her bilgi ayrı basit cümledir.',
    pronounce: ['Wir haben eine Wohnung. Wir haben drei Toiletten. Ich habe ein Zimmer. Meine Schwester hat auch ein Zimmer.'],
  },
  {
    id: 'p7-evim-spoken-tam',
    day: 7, track: 'private', topicId: EVIM,
    type: 'spoken', difficulty: 'hard', skill: 'speaking',
    conceptIds: ['private.day7.evim.model', 'private.day7.evim.kueche', 'private.day7.evim.katze'],
    familyId: 'p7-evim-spoken-tam',
    instruction: 'İpuçlarına bakmadan evini baştan sona sesli anlat.',
    requirements: [
      'En az on cümle kur.',
      'Odaları, renkleri, balkonu, mutfağı ve kediyi anlat.',
      'Karşılaştırma yapma — her bilgiyi ayrı cümlede söyle.',
    ],
    sampleAnswer: 'Wir haben eine Wohnung. Wir haben drei Toiletten. Ich habe ein Zimmer. Meine Schwester hat auch ein Zimmer. Ihr Zimmer ist hell. Mein Zimmer ist grau. Wir haben einen Balkon. Unsere Küche ist hell. Wir haben eine Katze. Unsere Katze hat auch ein Zimmer.',
    audio: { targets: [{ text: 'Wir haben eine Wohnung. Wir haben drei Toiletten. Ich habe ein Zimmer. Meine Schwester hat auch ein Zimmer. Ihr Zimmer ist hell. Mein Zimmer ist grau. Wir haben einen Balkon. Unsere Küche ist hell. Wir haben eine Katze. Unsere Katze hat auch ein Zimmer.', language: 'de-DE', role: 'example' }] },
  },

];
