/**
 * Present Perfect — çekirdek alıştırma bankası, bölüm 1.
 *
 * A. have/has + yapı (15) · B. V3 (30) · C. for/since (20)
 */

import { EN, EXACT_EN, listenEn, answerEn, pp, tok } from './helpers.ts';
import type { Exercise } from '../types.ts';

const FORMULA = 'pp.formula.core';
const TABLE = 'pp.have-has.table';
const CONTR = 'pp.have-has.contractions';
const V3 = 'pp.v3.irregular-core';
const V3REG = 'pp.v3.regular';
const V3CHAIN = 'pp.v3.v1v2v3';
const FORSINCE = 'pp.for-since.rule';
const FORSINCE_S = 'pp.for-since.states';

export const EN_EXERCISES_CORE: Exercise[] = [
  /* ================================================================
   * A. have/has + yapı (15)
   * ================================================================ */
  pp('en-pp-formula-mc-structure', 'multiple-choice', 'easy', 'recognition', [FORMULA], {
    familyId: 'en-pp-formula-structure',
    instruction: 'Present Perfect iskeletini seç:',
    prompt: 'I ___ this film ___.',
    answer: 'have … seen (have başta, V3 sonda)',
    options: [
      'have … seen (have başta, V3 sonda)',
      'seen … have (V3 başta, have sonda)',
      'see … seen (yardımcı yok)',
      'have … see (sonda V1)',
    ],
  }),
  pp('en-pp-formula-mc-visual', 'multiple-choice', 'easy', 'recognition', [FORMULA], {
    familyId: 'en-pp-formula-structure',
    instruction: 'Cümlede have ve V3 nerededir?',
    prompt: 'I have seen this film.',
    answer: 'have ikinci sırada, seen en sonda',
    options: [
      'have ikinci sırada, seen en sonda',
      'have en sonda, seen ikinci sırada',
      'ikisi de ikinci sırada',
      'ikisi de en sonda',
    ],
  }),
  pp('en-pp-have-fill-i', 'fill-blank', 'easy', 'recall', [FORMULA, TABLE], {
    familyId: 'en-pp-have-i',
    instruction: 'Yardımcıyı yaz — Bu filmi gördüm.',
    prompt: 'I ___ seen this film.',
    answer: 'have',
    validation: EXACT_EN,
  }),
  pp('en-pp-have-fill-she', 'fill-blank', 'easy', 'recall', [TABLE], {
    familyId: 'en-pp-have-she',
    instruction: 'Yardımcıyı yaz — Ödevini bitirdi.',
    prompt: 'She ___ finished her homework.',
    answer: 'has',
    validation: EXACT_EN,
  }),
  pp('en-pp-have-fill-they', 'fill-blank', 'easy', 'recall', [TABLE], {
    familyId: 'en-pp-have-they',
    instruction: 'Yardımcıyı yaz — Üç yıldır burada yaşıyorlar.',
    prompt: 'They ___ lived here for three years.',
    answer: 'have',
    validation: EXACT_EN,
  }),
  pp('en-pp-have-fill-he', 'fill-blank', 'easy', 'recall', [TABLE], {
    familyId: 'en-pp-have-he',
    instruction: 'Yardımcıyı yaz — Çoktan yemek yedi.',
    prompt: 'He ___ already eaten.',
    answer: 'has',
    validation: EXACT_EN,
  }),
  pp('en-pp-have-fill-we', 'fill-blank', 'easy', 'recall', [TABLE], {
    familyId: 'en-pp-have-we',
    instruction: 'Yardımcıyı yaz — Üç yıldır İngilizce çalışıyoruz.',
    prompt: 'We ___ studied English for three years.',
    answer: 'have',
    validation: EXACT_EN,
  }),
  pp('en-pp-have-fill-it', 'fill-blank', 'medium', 'recall', [TABLE], {
    familyId: 'en-pp-have-it',
    instruction: 'Yardımcıyı yaz — Az önce başladı.',
    prompt: 'It ___ just started.',
    answer: 'has',
    validation: EXACT_EN,
  }),
  pp('en-pp-have-table-match', 'matching', 'easy', 'recognition', [TABLE, CONTR], {
    familyId: 'en-pp-have-table',
    instruction: 'Özneyi kısaltmasıyla eşleştir.',
    pairs: [
      { left: 'I', right: "I've" },
      { left: 'you', right: "you've" },
      { left: 'he', right: "he's" },
      { left: 'she', right: "she's" },
      { left: 'it', right: "it's" },
      { left: 'we', right: "we've" },
      { left: 'they', right: "they've" },
    ],
    explanation: "I've = I have; he/she/it ile has kısalır: he's = he has.",
  }),
  pp('en-pp-formula-order-seen', 'ordering', 'medium', 'production', [FORMULA], {
    familyId: 'en-pp-formula-order',
    instruction: 'Kelimeleri doğru sıraya diz — Bu filmi gördüm.',
    prompt: 'seen / film. / have / this / I',
    answer: 'I have seen this film.',
    words: ['film.', 'I', 'seen', 'have', 'this'],
  }),
  pp('en-pp-formula-order-lived', 'ordering', 'medium', 'production', [FORMULA, FORSINCE_S], {
    familyId: 'en-pp-formula-order',
    instruction: 'Kelimeleri doğru sıraya diz — Üç yıldır burada yaşıyoruz.',
    prompt: 'lived / for / have / here / years. / We / three',
    answer: 'We have lived here for three years.',
    words: ['three', 'We', 'lived', 'years.', 'have', 'for', 'here'],
  }),
  pp('en-pp-formula-wb-seen', 'word-bank-translation', 'medium', 'production', [FORMULA], {
    familyId: 'en-pp-formula-wb',
    instruction: 'Kutucuklarla kur — Bu filmi gördüm.',
    answer: 'I have seen this film.',
    wordBank: {
      direction: 'tr-to-en', sourceText: 'Bu filmi gördüm.', targetLanguage: 'en',
      tokens: tok('I', 'have', 'seen', 'this', 'film.', 'see', 'has', 'saw'),
      acceptedSequences: [['I', 'have', 'seen', 'this', 'film.']],
    },
  }),
  pp('en-pp-formula-listen-seen', 'listen-choice', 'easy', 'recognition', [FORMULA], {
    familyId: 'en-pp-formula-listen',
    instruction: 'Duyduğun cümleyi seç:',
    audioText: 'I have seen this film.',
    answer: 'I have seen this film.',
    options: ['I have seen this film.', 'I see this film.', 'I have see this film.', 'I saw this film yesterday.'],
    audio: listenEn('I have seen this film.'),
  }),
  pp('en-pp-contraction-mc-ive', 'multiple-choice', 'easy', 'recognition', [CONTR], {
    familyId: 'en-pp-contr-ive',
    instruction: "I've ne demektir?",
    prompt: "I've seen this film.",
    answer: 'I have',
    options: ['I have', 'I am', 'I will', 'I had'],
  }),
  pp('en-pp-contraction-mc-hes', 'multiple-choice', 'medium', 'recognition', [CONTR], {
    familyId: 'en-pp-contr-hes',
    instruction: "Bu cümlede he's ne demektir?",
    prompt: "He's finished.",
    answer: 'he has (bitirdi)',
    options: ['he has (bitirdi)', 'he is (bitkindir)', 'he will (bitirecek)', 'he does (bitirir)'],
    explanation: "'He's finished.' cümlesinde he's = he has. Ama 'He's tired.' cümlesinde he's = he is olur — devamına bak.",
  }),

  /* ================================================================
   * B. V3 (30)
   * ================================================================ */
  pp('en-pp-v3-mc-see', 'multiple-choice', 'easy', 'recognition', [V3], {
    familyId: 'en-pp-v3-see',
    instruction: 'Doğru V3 hangisi? — see',
    prompt: 'see → ?',
    answer: 'seen',
    options: ['seen', 'saw', 'sees', 'seed'],
  }),
  pp('en-pp-v3-mc-go', 'multiple-choice', 'easy', 'recognition', [V3], {
    familyId: 'en-pp-v3-go',
    instruction: 'Doğru V3 hangisi? — go',
    prompt: 'go → ?',
    answer: 'gone',
    options: ['gone', 'went', 'goes', 'going'],
  }),
  pp('en-pp-v3-mc-write', 'multiple-choice', 'medium', 'recognition', [V3], {
    familyId: 'en-pp-v3-write',
    instruction: 'Doğru V3 hangisi? — write',
    prompt: 'write → ?',
    answer: 'written',
    options: ['written', 'wrote', 'writed', 'writing'],
  }),
  pp('en-pp-v3-mc-take', 'multiple-choice', 'medium', 'recognition', [V3], {
    familyId: 'en-pp-v3-take',
    instruction: 'Doğru V3 hangisi? — take',
    prompt: 'take → ?',
    answer: 'taken',
    options: ['taken', 'took', 'taked', 'taking'],
  }),
  pp('en-pp-v3-mc-know', 'multiple-choice', 'medium', 'recognition', [V3], {
    familyId: 'en-pp-v3-know',
    instruction: 'Doğru V3 hangisi? — know',
    prompt: 'know → ?',
    answer: 'known',
    options: ['known', 'knew', 'knowed', 'knowing'],
  }),
  pp('en-pp-v3-mc-eat', 'multiple-choice', 'easy', 'recognition', [V3], {
    familyId: 'en-pp-v3-eat',
    instruction: 'Doğru V3 hangisi? — eat',
    prompt: 'eat → ?',
    answer: 'eaten',
    options: ['eaten', 'ate', 'eated', 'eating'],
  }),
  pp('en-pp-v3-fill-seen', 'fill-blank', 'easy', 'recall', [V3], {
    familyId: 'en-pp-v3f-seen',
    instruction: 'V3’ü yaz:',
    prompt: 'see → ___',
    answer: 'seen',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-gone', 'fill-blank', 'easy', 'recall', [V3], {
    familyId: 'en-pp-v3f-gone',
    instruction: 'V3’ü yaz:',
    prompt: 'go → ___',
    answer: 'gone',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-done', 'fill-blank', 'easy', 'recall', [V3], {
    familyId: 'en-pp-v3f-done',
    instruction: 'V3’ü yaz:',
    prompt: 'do → ___',
    answer: 'done',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-known', 'fill-blank', 'medium', 'recall', [V3], {
    familyId: 'en-pp-v3f-known',
    instruction: 'V3’ü yaz:',
    prompt: 'know → ___',
    answer: 'known',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-made', 'fill-blank', 'easy', 'recall', [V3], {
    familyId: 'en-pp-v3f-made',
    instruction: 'V3’ü yaz:',
    prompt: 'make → ___',
    answer: 'made',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-taken', 'fill-blank', 'medium', 'recall', [V3], {
    familyId: 'en-pp-v3f-taken',
    instruction: 'V3’ü yaz:',
    prompt: 'take → ___',
    answer: 'taken',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-written', 'fill-blank', 'medium', 'recall', [V3], {
    familyId: 'en-pp-v3f-written',
    instruction: 'V3’ü yaz:',
    prompt: 'write → ___',
    answer: 'written',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-spoken', 'fill-blank', 'medium', 'recall', [V3], {
    familyId: 'en-pp-v3f-spoken',
    instruction: 'V3’ü yaz:',
    prompt: 'speak → ___',
    answer: 'spoken',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-eaten', 'fill-blank', 'easy', 'recall', [V3], {
    familyId: 'en-pp-v3f-eaten',
    instruction: 'V3’ü yaz:',
    prompt: 'eat → ___',
    answer: 'eaten',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-come', 'fill-blank', 'medium', 'recall', [V3], {
    familyId: 'en-pp-v3f-come',
    instruction: 'V3’ü yaz (dikkat: V2’den farklı):',
    prompt: 'come → ___',
    answer: 'come',
    validation: EXACT_EN,
    explanation: 'come → came → come: V1 ile V3 aynı yazılır.',
  }),
  pp('en-pp-v3-fill-met', 'fill-blank', 'medium', 'recall', [V3], {
    familyId: 'en-pp-v3f-met',
    instruction: 'V3’ü yaz:',
    prompt: 'meet → ___',
    answer: 'met',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-thought', 'fill-blank', 'hard', 'recall', [V3], {
    familyId: 'en-pp-v3f-thought',
    instruction: 'V3’ü yaz:',
    prompt: 'think → ___',
    answer: 'thought',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-match-core', 'matching', 'medium', 'recognition', [V3], {
    familyId: 'en-pp-v3-match',
    instruction: 'Fiili V3 ile eşleştir.',
    pairs: [
      { left: 'see', right: 'seen' },
      { left: 'go', right: 'gone' },
      { left: 'do', right: 'done' },
      { left: 'know', right: 'known' },
      { left: 'make', right: 'made' },
      { left: 'take', right: 'taken' },
    ],
  }),
  pp('en-pp-v3-match-more', 'matching', 'medium', 'recognition', [V3], {
    familyId: 'en-pp-v3-match-more',
    instruction: 'Fiili V3 ile eşleştir.',
    pairs: [
      { left: 'write', right: 'written' },
      { left: 'speak', right: 'spoken' },
      { left: 'eat', right: 'eaten' },
      { left: 'come', right: 'come' },
      { left: 'meet', right: 'met' },
      { left: 'think', right: 'thought' },
    ],
  }),
  pp('en-pp-v3-chain-see', 'free-text', 'easy', 'production', [V3CHAIN], {
    familyId: 'en-pp-v3chain-see',
    instruction: 'Zinciri tamamla (test V3’tedir):',
    prompt: 'see → saw → ___',
    answer: 'seen',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-chain-go', 'free-text', 'easy', 'production', [V3CHAIN], {
    familyId: 'en-pp-v3chain-go',
    instruction: 'Zinciri tamamla (test V3’tedir):',
    prompt: 'go → went → ___',
    answer: 'gone',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-chain-write', 'free-text', 'hard', 'production', [V3CHAIN], {
    familyId: 'en-pp-v3chain-write',
    instruction: 'Zinciri tamamla (test V3’tedir):',
    prompt: 'write → wrote → ___',
    answer: 'written',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-chain-take', 'free-text', 'hard', 'production', [V3CHAIN], {
    familyId: 'en-pp-v3chain-take',
    instruction: 'Zinciri tamamla (test V3’tedir):',
    prompt: 'take → took → ___',
    answer: 'taken',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-worked', 'fill-blank', 'easy', 'recall', [V3REG], {
    familyId: 'en-pp-v3f-worked',
    instruction: 'Düzenli V3’ü yaz:',
    prompt: 'work → ___',
    answer: 'worked',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-studied', 'fill-blank', 'easy', 'recall', [V3REG], {
    familyId: 'en-pp-v3f-studied',
    instruction: 'Düzenli V3’ü yaz (yazıma dikkat):',
    prompt: 'study → ___',
    answer: 'studied',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-fill-finished', 'fill-blank', 'easy', 'recall', [V3REG], {
    familyId: 'en-pp-v3f-finished',
    instruction: 'Düzenli V3’ü yaz:',
    prompt: 'finish → ___',
    answer: 'finished',
    validation: EXACT_EN,
  }),
  pp('en-pp-v3-mc-regular', 'multiple-choice', 'medium', 'recognition', [V3REG, V3], {
    familyId: 'en-pp-v3-regular-mc',
    instruction: 'Hangisi DÜZENLİ V3’tür?',
    prompt: 'düzenli → ?',
    answer: 'finished',
    options: ['finished', 'seen', 'gone', 'written'],
  }),
  pp('en-pp-v3-free-written', 'free-text', 'hard', 'production', [V3, FORMULA], {
    familyId: 'en-pp-v3-written-sent',
    instruction: 'Türkçeden İngilizceye çevir:',
    prompt: 'Bir e-posta yazdım. → ______',
    answer: 'I have written an email.',
    acceptedAnswers: ["I've written an email."],
    validation: EN,
    audio: answerEn('I have written an email.'),
  }),
  pp('en-pp-v3-free-gone', 'free-text', 'hard', 'production', [V3, FORMULA], {
    familyId: 'en-pp-v3-gone-sent',
    instruction: 'Türkçeden İngilizceye çevir:',
    prompt: 'Eve gitti. (She …) → ______',
    answer: 'She has gone home.',
    acceptedAnswers: ["She's gone home."],
    validation: EN,
    audio: answerEn('She has gone home.'),
  }),

  /* ================================================================
   * C. for/since (20)
   * ================================================================ */
  pp('en-pp-fs-mc-three-years', 'multiple-choice', 'easy', 'recognition', [FORSINCE], {
    familyId: 'en-pp-fs-rapid',
    instruction: 'Hızlı tanıma — hangisi gelir?',
    prompt: '___ three years',
    answer: 'for',
    options: ['for', 'since', 'from', 'at'],
  }),
  pp('en-pp-fs-mc-monday', 'multiple-choice', 'easy', 'recognition', [FORSINCE], {
    familyId: 'en-pp-fs-rapid',
    instruction: 'Hızlı tanıma — hangisi gelir?',
    prompt: '___ Monday',
    answer: 'since',
    options: ['for', 'since', 'from', 'at'],
  }),
  pp('en-pp-fs-mc-2024', 'multiple-choice', 'easy', 'recognition', [FORSINCE], {
    familyId: 'en-pp-fs-rapid',
    instruction: 'Hızlı tanıma — hangisi gelir?',
    prompt: '___ 2024',
    answer: 'since',
    options: ['for', 'since', 'from', 'at'],
  }),
  pp('en-pp-fs-mc-two-hours', 'multiple-choice', 'easy', 'recognition', [FORSINCE], {
    familyId: 'en-pp-fs-rapid',
    instruction: 'Hızlı tanıma — hangisi gelir?',
    prompt: '___ two hours',
    answer: 'for',
    options: ['for', 'since', 'from', 'at'],
  }),
  pp('en-pp-fs-mc-child', 'multiple-choice', 'medium', 'recognition', [FORSINCE], {
    familyId: 'en-pp-fs-rapid',
    instruction: 'Hızlı tanıma — hangisi gelir?',
    prompt: '___ I was a child',
    answer: 'since',
    options: ['for', 'since', 'from', 'at'],
  }),
  pp('en-pp-fs-mc-long-time', 'multiple-choice', 'easy', 'recognition', [FORSINCE], {
    familyId: 'en-pp-fs-rapid',
    instruction: 'Hızlı tanıma — hangisi gelir?',
    prompt: '___ a long time',
    answer: 'for',
    options: ['for', 'since', 'from', 'at'],
  }),
  pp('en-pp-fs-mc-january', 'multiple-choice', 'easy', 'recognition', [FORSINCE], {
    familyId: 'en-pp-fs-rapid',
    instruction: 'Hızlı tanıma — hangisi gelir?',
    prompt: '___ January',
    answer: 'since',
    options: ['for', 'since', 'from', 'at'],
  }),
  pp('en-pp-fs-mc-five-minutes', 'multiple-choice', 'easy', 'recognition', [FORSINCE], {
    familyId: 'en-pp-fs-rapid',
    instruction: 'Hızlı tanıma — hangisi gelir?',
    prompt: '___ five minutes',
    answer: 'for',
    options: ['for', 'since', 'from', 'at'],
  }),
  pp('en-pp-fs-fill-years', 'fill-blank', 'easy', 'recall', [FORSINCE, FORSINCE_S], {
    familyId: 'en-pp-fs-years',
    instruction: 'for mu since mi? — Üç yıldır burada yaşıyorum.',
    prompt: 'I have lived here ___ three years.',
    answer: 'for',
    validation: EXACT_EN,
  }),
  pp('en-pp-fs-fill-2023', 'fill-blank', 'easy', 'recall', [FORSINCE, FORSINCE_S], {
    familyId: 'en-pp-fs-2023',
    instruction: 'for mu since mi? — 2023’ten beri burada yaşıyorum.',
    prompt: 'I have lived here ___ 2023.',
    answer: 'since',
    validation: EXACT_EN,
  }),
  pp('en-pp-fs-fill-hours', 'fill-blank', 'easy', 'recall', [FORSINCE], {
    familyId: 'en-pp-fs-hours',
    instruction: 'for mu since mi?',
    prompt: 'We have waited ___ two hours.',
    answer: 'for',
    validation: EXACT_EN,
  }),
  pp('en-pp-fs-fill-last-year', 'fill-blank', 'medium', 'recall', [FORSINCE], {
    familyId: 'en-pp-fs-last-year',
    instruction: 'for mu since mi?',
    prompt: 'She has worked here ___ last year.',
    answer: 'since',
    validation: EXACT_EN,
  }),
  pp('en-pp-fs-fill-long-time', 'fill-blank', 'easy', 'recall', [FORSINCE], {
    familyId: 'en-pp-fs-long-time',
    instruction: 'for mu since mi?',
    prompt: 'I have known him ___ a long time.',
    answer: 'for',
    validation: EXACT_EN,
  }),
  pp('en-pp-fs-fill-monday', 'fill-blank', 'medium', 'recall', [FORSINCE], {
    familyId: 'en-pp-fs-monday',
    instruction: 'for mu since mi?',
    prompt: 'They have studied together ___ Monday.',
    answer: 'since',
    validation: EXACT_EN,
  }),
  pp('en-pp-fs-free-lived-for', 'free-text', 'hard', 'production', [FORSINCE_S], {
    familyId: 'en-pp-fs-lived-for',
    instruction: 'Türkçeden İngilizceye çevir:',
    prompt: 'Üç yıldır burada yaşıyorum. → ______',
    answer: 'I have lived here for three years.',
    acceptedAnswers: ["I've lived here for three years."],
    validation: EN,
    audio: answerEn('I have lived here for three years.'),
  }),
  pp('en-pp-fs-free-lived-since', 'free-text', 'hard', 'production', [FORSINCE_S], {
    familyId: 'en-pp-fs-lived-since',
    instruction: 'Türkçeden İngilizceye çevir:',
    prompt: '2024’ten beri burada yaşıyorum. → ______',
    answer: 'I have lived here since 2024.',
    acceptedAnswers: ["I've lived here since 2024."],
    validation: EN,
    audio: answerEn('I have lived here since 2024.'),
  }),
  pp('en-pp-fs-free-known', 'free-text', 'hard', 'production', [FORSINCE_S, 'pp.states.know-live'], {
    familyId: 'en-pp-fs-known',
    instruction: 'Türkçeden İngilizceye çevir:',
    prompt: 'Onu üç yıldır tanıyorum. → ______',
    answer: 'I have known him for three years.',
    acceptedAnswers: ["I've known him for three years.", 'I have known her for three years.'],
    validation: EN,
    audio: answerEn('I have known him for three years.'),
  }),
  pp('en-pp-fs-free-worked-since', 'free-text', 'hard', 'production', [FORSINCE_S, 'pp.states.know-live'], {
    familyId: 'en-pp-fs-worked-since',
    instruction: 'Türkçeden İngilizceye çevir:',
    prompt: 'Ocak’tan beri burada çalışıyor. (She …) → ______',
    answer: 'She has worked here since January.',
    acceptedAnswers: ["She's worked here since January."],
    validation: EN,
    audio: answerEn('She has worked here since January.'),
  }),
  pp('en-pp-fs-err-since-years', 'error-correction', 'medium', 'correction', [FORSINCE, 'pp.mistakes.for-since'], {
    familyId: 'en-pp-fs-err-since',
    instruction: 'for/since yanlış — cümleyi düzelt:',
    prompt: 'I have lived here since three years.',
    answer: 'I have lived here for three years.',
    explanation: 'Üç yıl bir SÜREDİR → for.',
    validation: EN,
  }),
  pp('en-pp-fs-err-for-year', 'error-correction', 'medium', 'correction', [FORSINCE, 'pp.mistakes.for-since'], {
    familyId: 'en-pp-fs-err-for',
    instruction: 'for/since yanlış — cümleyi düzelt:',
    prompt: 'She has worked here since three years.',
    answer: 'She has worked here for three years.',
    explanation: 'Üç yıl bir SÜREDİR → for.',
    validation: EN,
  }),
];
