/**
 * Sıfatlar — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const ADJECTIVES_EXERCISES: AuthoredExercise[] = [
  /* ---- Sıfatlar ve Ekler (11) ---- */
  {
    id: 'p3-sf-yuklem-mc',
    topicId: T.adjectives, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['adjectives.sifat.yuklem'],
    familyId: 'p3-sf-yuklem',
    instruction: 'Bir sıfat "sein" fiilinden sonra geldiğinde ek alır mı?',
    prompt: 'Das Kleid ist sehr schön.',
    answer: 'Hayır, ek almaz',
    options: ['Hayır, ek almaz', 'Evet, her zaman -e alır', 'Evet, her zaman -es alır', 'Sadece çoğulda ek alır'],
  },
  {
    id: 'p3-sf-schoen-fill',
    topicId: T.adjectives, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['adjectives.sifat.yuklem'],
    familyId: 'p3-sf-schoen',
    instruction: 'Boşluğu doldur (ek yok):',
    prompt: 'Mein Zimmer ist klein, aber ___. (küçük ama güzel)',
    answer: 'schön',
    pronounce: ['Mein Zimmer ist klein, aber schön.'],
  },
  {
    id: 'p3-sf-ein-notr-mc',
    topicId: T.adjectives, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['adjectives.sifat.ein-notr'],
    familyId: 'p3-sf-ein-notr',
    instruction: '"ein" + nötr isim + sıfat kalıbında sıfat hangi eki alır?',
    prompt: 'ein ___ T-Shirt (neu)',
    answer: 'neues',
    options: ['neues', 'neue', 'neuer', 'neu'],
  },
  {
    id: 'p3-sf-neues-tshirt-fill',
    topicId: T.adjectives, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['adjectives.sifat.ein-notr'],
    familyId: 'p3-sf-neues-tshirt',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich kaufe ein ___ T-Shirt. (yeni bir tişört alıyorum — neu)',
    answer: 'neues',
    pronounce: ['Ich kaufe ein neues T-Shirt.'],
  },
  {
    id: 'p3-sf-cogul-artikelsiz-mc',
    topicId: T.adjectives, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['adjectives.sifat.cogul-artikelsiz'],
    familyId: 'p3-sf-cogul-artikelsiz',
    instruction: 'Artikelsiz çoğul isimden önceki sıfat hangi eki alır?',
    prompt: 'schwarz + Schuhe (artikelsiz çoğul)',
    answer: 'schwarze',
    options: ['schwarze', 'schwarzes', 'schwarzer', 'schwarz'],
  },
  {
    id: 'p3-sf-schwarze-schuhe-fill',
    topicId: T.adjectives, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['adjectives.sifat.cogul-artikelsiz'],
    familyId: 'p3-sf-schwarze-schuhe',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich möchte ___ Schuhe. (siyah ayakkabı istiyorum — schwarz)',
    answer: 'schwarze',
    pronounce: ['Ich möchte schwarze Schuhe.'],
  },
  {
    id: 'p3-sf-error-eine-schwarze-schuhe',
    topicId: T.adjectives, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['adjectives.sifat.cogul-artikelsiz'],
    familyId: 'p3-sf-schwarze-schuhe',
    instruction: 'Hata avı — çoğulda belirsiz artikel var mı?',
    prompt: 'Ich möchte eine schwarze Schuhe.',
    answer: 'Ich möchte schwarze Schuhe.',
    explanation: 'Schuhe çoğuldur; çoğulda belirsiz artikel (eine) kullanılmaz, sıfat artikelsiz -e eki alır.',
    pronounce: ['Ich möchte schwarze Schuhe.'],
  },
  {
    id: 'p3-sf-wb-tshirt-tr-de',
    topicId: T.adjectives, legacyDay: 3,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['adjectives.sifat.ein-notr'],
    familyId: 'p3-sf-neues-tshirt',
    instruction: 'Türkçeden Almancaya kur — Ben yeni bir tişört alıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ben yeni bir tişört alıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'kaufe' }, { id: 't3', text: 'ein' }, { id: 't4', text: 'neues' },
        { id: 't5', text: 'T-Shirt.' }, { id: 't6', text: 'neue' },
      ],
      acceptedSequences: [['Ich', 'kaufe', 'ein', 'neues', 'T-Shirt.']],
    },
    answer: 'Ich kaufe ein neues T-Shirt.',
    pronounce: ['Ich kaufe ein neues T-Shirt.'],
  },
  {
    id: 'p3-sf-free-elbise-tr',
    topicId: T.adjectives, legacyDay: 3,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['adjectives.sifat.yuklem'],
    familyId: 'p3-sf-elbise',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu elbise çok güzel. → ______',
    answer: 'Das Kleid ist sehr schön.',
    pronounce: ['Das Kleid ist sehr schön.'],
  },
  {
    id: 'p3-sf-film-gut-fill',
    topicId: T.adjectives, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['adjectives.sifat.yuklem'],
    familyId: 'p3-sf-film-gut',
    instruction: 'Boşluğu doldur (ek yok):',
    prompt: 'Der Film ist sehr ___. (film çok güzel)',
    answer: 'gut',
    pronounce: ['Der Film ist sehr gut.'],
  },
  {
    id: 'p3-sf-error-heute-glucklich',
    topicId: T.adjectives, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['adjectives.sifat.yuklem'],
    familyId: 'p3-sf-heute-glucklich',
    instruction: 'Hata avı — sıfat büyük harfle mi yazılır?',
    prompt: 'Ich bin heute sehr Glücklich.',
    answer: 'Ich bin heute sehr glücklich.',
    explanation: 'Sıfatlar isim değildir; sein\'den sonra gelse bile küçük harfle yazılır.',
    pronounce: ['Ich bin heute sehr glücklich.'],
  },

  /* ---- Tarif Sıfatları — hell, dunkel, groß, klein (9) ---- */
  {
    id: 'p7-tar-hell-mc',
    topicId: T.adjectives, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['adjectives.tarif.hell'],
    familyId: 'p7-tar-hell',
    instruction: '"hell" ne demektir?',
    prompt: 'hell',
    answer: 'açık, ferah',
    options: ['açık, ferah', 'koyu, karanlık', 'dar', 'pahalı'],
    pronounce: ['hell'],
  },
  {
    id: 'p7-tar-dunkel-mc',
    topicId: T.adjectives, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['adjectives.tarif.dunkel'],
    familyId: 'p7-tar-dunkel',
    instruction: '"dunkel" ne demektir?',
    prompt: 'dunkel',
    answer: 'koyu, karanlık',
    options: ['koyu, karanlık', 'açık, ferah', 'geniş', 'serin'],
    pronounce: ['dunkel'],
  },
  {
    id: 'p7-tar-zit-fill',
    topicId: T.adjectives, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['adjectives.tarif.gross-klein', 'adjectives.tarif.dunkel'],
    familyId: 'p7-tar-zit',
    instruction: 'Zıt anlamlıyı yaz:',
    prompt: 'hell ↔ ___',
    answer: 'dunkel',
    pronounce: ['dunkel'],
  },
  {
    id: 'p7-tar-breit-schmal-match',
    topicId: T.adjectives, legacyDay: 7,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['adjectives.tarif.breit', 'adjectives.tarif.schmal', 'adjectives.tarif.kuehl', 'adjectives.tarif.grau'],
    familyId: 'p7-tar-sifat-match',
    instruction: 'Sıfatı Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'breit', right: 'geniş' },
      { left: 'schmal', right: 'dar' },
      { left: 'kühl', right: 'serin' },
      { left: 'grau', right: 'gri' },
    ],
    pronounce: ['breit', 'schmal', 'kühl', 'grau'],
  },
  {
    id: 'p7-tar-flur-schmal-fill',
    topicId: T.adjectives, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['adjectives.tarif.schmal'],
    familyId: 'p7-tar-flur-schmal',
    instruction: 'Boşluğu doldur — "dar" sıfatını yaz:',
    prompt: 'Der Flur ist ___. (Koridor dar.)',
    answer: 'schmal',
    pronounce: ['Der Flur ist schmal.'],
  },
  {
    id: 'p7-tar-zimmer-dunkel-tr-de',
    topicId: T.adjectives, legacyDay: 7,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['adjectives.tarif.dunkel'],
    familyId: 'p7-tar-zimmer-dunkel',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Oda karanlık. → ______',
    answer: 'Das Zimmer ist dunkel.',
    pronounce: ['Das Zimmer ist dunkel.'],
  },
  {
    id: 'p7-tar-sein-sifat-mc',
    topicId: T.adjectives, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['adjectives.tarif.sein-sifat'],
    familyId: 'p7-tar-sein-sifat',
    instruction: 'Hangisi doğru?',
    prompt: 'Yatak odası karanlık.',
    answer: 'Das Schlafzimmer ist dunkel.',
    options: [
      'Das Schlafzimmer ist dunkel.',
      'Das Schlafzimmer ist dunkele.',
      'Das Schlafzimmer dunkel ist.',
      'Das dunkele Schlafzimmer ist.',
    ],
    explanation: '`sein` fiilinden sonra gelen sıfat hiçbir ek almaz.',
    pronounce: ['Das Schlafzimmer ist dunkel.'],
  },
  {
    id: 'p7-tar-error-helle',
    topicId: T.adjectives, legacyDay: 7,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['adjectives.tarif.sein-sifat', 'adjectives.tarif.hell'],
    familyId: 'p7-tar-error-helle',
    instruction: 'Cümledeki hatayı düzelt:',
    prompt: 'Das Bad ist helle.',
    answer: 'Das Bad ist hell.',
    explanation: 'Yüklem sıfatı ek almaz: `hell`, `helle` değil.',
    pronounce: ['Das Bad ist hell.'],
  },
  {
    id: 'p7-tar-listen-hell-dunkel',
    topicId: T.adjectives, legacyDay: 7,
    type: 'listen-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['adjectives.tarif.hell'],
    familyId: 'p7-tar-listen',
    instruction: 'Duyduğun cümleyi seç:',
    prompt: 'Die Küche ist hell.',
    audioText: 'Die Küche ist hell.',
    answer: 'Die Küche ist hell.',
    options: ['Die Küche ist hell.', 'Die Küche ist dunkel.', 'Das Bad ist hell.', 'Der Flur ist hell.'],
    audio: { prompt: { text: 'Die Küche ist hell.', language: 'de-DE', role: 'prompt' } },
  },
];
