/**
 * Akkusativ — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const AKKUSATIV_EXERCISES: AuthoredExercise[] = [
  /* ---- es gibt — Var / Yok (10) ---- */
  {
    id: 'p3-eg-temel-mc',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['akkusativ.esgibt.temel'],
    familyId: 'p3-eg-temel',
    instruction: '"Es gibt" ne demektir?',
    prompt: 'Es gibt',
    answer: '... var',
    options: ['... var', '... yok', '... geliyor', '... gidiyor'],
    pronounce: ['Es gibt'],
  },
  {
    id: 'p3-eg-blumen-fill',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['akkusativ.esgibt.temel'],
    familyId: 'p3-eg-blumen',
    instruction: 'Boşluğu doldur:',
    prompt: 'Auf dem Balkon ___ es Blumen. (balkonda çiçekler var)',
    answer: 'gibt',
    pronounce: ['Auf dem Balkon gibt es Blumen.'],
  },
  {
    id: 'p3-eg-leute-fill',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['akkusativ.esgibt.temel'],
    familyId: 'p3-eg-leute',
    instruction: 'Boşluğu doldur:',
    prompt: 'Im Markt gibt ___ viele Leute. (markette çok insan var)',
    answer: 'es',
    pronounce: ['Im Markt gibt es viele Leute.'],
  },
  {
    id: 'p3-eg-akkusativ-mc',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['akkusativ.esgibt.akkusativ'],
    familyId: 'p3-eg-akkusativ',
    instruction: '"es gibt" hangi hâli ister?',
    prompt: 'es gibt + ...?',
    answer: 'Akkusativ',
    options: ['Akkusativ', 'Dativ', 'Nominativ', 'hiçbiri'],
  },
  {
    id: 'p3-eg-tisch-fill',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['akkusativ.esgibt.akkusativ'],
    familyId: 'p3-eg-tisch',
    instruction: 'Boşluğu doldur — der Tisch, es gibt + Akkusativ:',
    prompt: 'In meinem Zimmer gibt es ___ Tisch. (odamda bir masa var)',
    answer: 'einen',
    pronounce: ['In meinem Zimmer gibt es einen Tisch.'],
  },
  {
    id: 'p3-eg-balkon-fill',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['akkusativ.esgibt.akkusativ'],
    familyId: 'p3-eg-balkon',
    instruction: 'Boşluğu doldur — der Balkon, haben + Akkusativ:',
    prompt: 'Wir haben ___ Balkon. (bir balkonumuz var)',
    answer: 'einen',
    pronounce: ['Wir haben einen Balkon.'],
  },
  {
    id: 'p3-eg-error-balkon',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['akkusativ.esgibt.akkusativ'],
    familyId: 'p3-eg-balkon',
    instruction: 'Hata avı — doğru artikel hangisi?',
    prompt: 'Wir haben ein Balkon.',
    answer: 'Wir haben einen Balkon.',
    explanation: 'der Balkon erildir; haben Akkusativ ister → ein değil einen.',
    pronounce: ['Wir haben einen Balkon.'],
  },
  {
    id: 'p3-eg-genel-cogul-mc',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['akkusativ.esgibt.genel-cogul'],
    familyId: 'p3-eg-genel-cogul',
    instruction: '"es gibt" ile genel bir çoğulda artikel nasıl kullanılır?',
    prompt: 'Es gibt + çoğul isim (genel)',
    answer: 'artikelsiz',
    options: ['artikelsiz', 'die ile', 'ein ile', 'kein ile'],
  },
  {
    id: 'p3-eg-error-blumen',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['akkusativ.esgibt.genel-cogul'],
    familyId: 'p3-eg-blumen',
    instruction: 'Hata avı — genel ifadede artikel gerekli mi?',
    prompt: 'Auf dem Balkon gibt es die Blumen.',
    answer: 'Auf dem Balkon gibt es Blumen.',
    explanation: 'Genel/sayılamayan bir durumda çoğul isim artikelsiz kullanılır.',
    pronounce: ['Auf dem Balkon gibt es Blumen.'],
  },
  {
    id: 'p3-eg-free-balkon-tr',
    topicId: T.akkusativ, legacyDay: 3,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['akkusativ.esgibt.temel', 'akkusativ.esgibt.genel-cogul'],
    familyId: 'p3-eg-blumen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Balkonda çiçekler var. → ______',
    answer: 'Auf dem Balkon gibt es Blumen.',
    pronounce: ['Auf dem Balkon gibt es Blumen.'],
  },

  /* ---- Akkusativ pekiştirme: der → den, ein → einen, mein → meinen ---- */
  {
    id: 'akk-nedir-mc',
    topicId: T.akkusativ,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['akkusativ.nedir'],
    familyId: 'akk-nedir',
    instruction: 'Akkusativ nedir?',
    prompt: 'Ich kaufe einen Kuchen.',
    answer: 'nesne hâli (neyi? kimi?)',
    options: ['nesne hâli (neyi? kimi?)', 'özne hâli (kim?)', 'yer hâli (nerede?)', 'geçmiş zaman'],
    pronounce: ['Ich kaufe einen Kuchen.'],
  },
  {
    id: 'akk-der-den-fill',
    topicId: T.akkusativ,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['akkusativ.der-den', 'vocabulary.nehmen', 'vocabulary.schluessel'],
    familyId: 'akk-der-den',
    instruction: 'Doğru artikeli yaz (der Schlüssel) — Anahtarı alıyorum.',
    prompt: 'Ich nehme ___ Schlüssel.',
    answer: 'den',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich nehme den Schlüssel.'],
  },
  {
    id: 'akk-ein-einen-fill',
    topicId: T.akkusativ,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['akkusativ.ein-einen', 'food.yiyecek.kelimeler'],
    familyId: 'akk-ein-einen',
    instruction: 'Doğru artikeli yaz (ein Kuchen) — Bir kek alıyorum.',
    prompt: 'Ich kaufe ___ Kuchen.',
    answer: 'einen',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich kaufe einen Kuchen.'],
  },
  {
    id: 'akk-die-das-mc',
    topicId: T.akkusativ,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['akkusativ.die-das', 'vocabulary.tasche-zeitung'],
    familyId: 'akk-die-das',
    instruction: 'Doğru biçimi seç (die Tasche):',
    prompt: 'Ich nehme ___ Tasche.',
    answer: 'die',
    options: ['die', 'den', 'der', 'dem'],
    explanation: 'Dişil isim Akkusativ\'te değişmez: `die Tasche`.',
    pronounce: ['Ich nehme die Tasche.'],
  },
  {
    id: 'akk-mein-meinen-fill',
    topicId: T.akkusativ,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['akkusativ.mein-meinen', 'vocabulary.schluessel'],
    familyId: 'akk-mein-meinen',
    instruction: 'Doğru iyeliği yaz (mein Schlüssel) — Anahtarımı alıyorum.',
    prompt: 'Ich nehme ___ Schlüssel.',
    answer: 'meinen',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich nehme meinen Schlüssel.'],
  },
  {
    id: 'akk-kein-keinen-fill',
    topicId: T.akkusativ,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['akkusativ.kein-keinen'],
    familyId: 'akk-kein-keinen',
    instruction: 'Olumsuz artikeli yaz (kein Kuchen) — Hiç kekim yok.',
    prompt: 'Ich habe ___ Kuchen.',
    answer: 'keinen',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich habe keinen Kuchen.'],
  },
  {
    id: 'akk-sein-yok-mc',
    topicId: T.akkusativ,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['akkusativ.sein-yok'],
    familyId: 'akk-sein-yok',
    instruction: 'Doğru cümle hangisi? — Bu bir kek.',
    answer: 'Das ist ein Kuchen.',
    options: ['Das ist ein Kuchen.', 'Das ist einen Kuchen.', 'Das ist einem Kuchen.', 'Das ist eine Kuchen.'],
    explanation: '`sein` Akkusativ istemez: `sein`den sonra isim özne gibi kalır.',
    pronounce: ['Das ist ein Kuchen.'],
  },
  {
    id: 'akk-mein-error',
    topicId: T.akkusativ,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['akkusativ.mein-meinen', 'vocabulary.nehmen'],
    familyId: 'akk-mein-error',
    instruction: 'Hatayı düzelt:',
    prompt: 'Ich nehme mein Schlüssel.',
    answer: 'Ich nehme meinen Schlüssel.',
    validation: { keyboardTolerance: true },
    explanation: '`der Schlüssel` eril: nesne olunca `mein` → `meinen`.',
    pronounce: ['Ich nehme meinen Schlüssel.'],
  },
  {
    id: 'akk-vater-kuchen-tr',
    topicId: T.akkusativ,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['akkusativ.ein-einen'],
    familyId: 'akk-vater-kuchen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Babam bir kek alıyor.',
    answer: 'Mein Vater kauft einen Kuchen.',
    pronounce: ['Mein Vater kauft einen Kuchen.'],
  },
  {
    id: 'akk-donusum-match',
    topicId: T.akkusativ,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['akkusativ.der-den', 'akkusativ.ein-einen', 'akkusativ.mein-meinen', 'akkusativ.die-das'],
    familyId: 'akk-donusum-match',
    instruction: 'Özne biçimini nesne (Akkusativ) biçimiyle eşleştir.',
    pairs: [
      { left: 'der Brief', right: 'den Brief' },
      { left: 'ein Kuchen', right: 'einen Kuchen' },
      { left: 'mein Schlüssel', right: 'meinen Schlüssel' },
      { left: 'die Tasche', right: 'die Tasche' },
    ],
  },
];
