/**
 * Artikeller ve Olumsuzluk — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const ARTICLES_EXERCISES: AuthoredExercise[] = [
  /* ---- Belirli ve Belirsiz Artikeller — der, die, das / ein, eine (15) ---- */
  {
    id: 'p2-art-vater-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.artikel.der-die-das-die-pl', 'articles.wortschatz.nesneler'],
    familyId: 'p2-art-vater',
    instruction: 'Doğru belirli artikeli seç:',
    prompt: '_____ Vater (baba)',
    answer: 'der',
    options: ['der', 'die', 'das', 'ein'],
    pronounce: ['der Vater'],
  },
  {
    id: 'p2-art-mutter-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.artikel.der-die-das-die-pl', 'articles.wortschatz.nesneler'],
    familyId: 'p2-art-mutter',
    instruction: 'Doğru belirli artikeli seç:',
    prompt: '_____ Mutter (anne)',
    answer: 'die',
    options: ['der', 'die', 'das', 'eine'],
    pronounce: ['die Mutter'],
  },
  {
    id: 'p2-art-kind-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.artikel.der-die-das-die-pl', 'articles.wortschatz.nesneler'],
    familyId: 'p2-art-kind',
    instruction: 'Doğru belirli artikeli seç:',
    prompt: '_____ Kind (çocuk)',
    answer: 'das',
    options: ['der', 'die', 'das', 'ein'],
    pronounce: ['das Kind'],
  },
  {
    id: 'p2-art-blumen-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.artikel.der-die-das-die-pl'],
    familyId: 'p2-art-blumen',
    instruction: 'Çoğul isimde doğru artikeli seç:',
    prompt: '_____ Blumen (çiçekler)',
    answer: 'die',
    options: ['der', 'die', 'das', 'ein'],
    pronounce: ['die Blumen'],
  },
  {
    id: 'p2-art-tisch-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.der-die-das-die-pl', 'articles.wortschatz.nesneler'],
    familyId: 'p2-art-tisch',
    instruction: 'Boşluğu doldur:',
    prompt: '_____ Tisch (masa)',
    answer: 'der',
    pronounce: ['der Tisch'],
  },
  {
    id: 'p2-art-tasche-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.der-die-das-die-pl', 'articles.wortschatz.nesneler'],
    familyId: 'p2-art-tasche',
    instruction: 'Boşluğu doldur:',
    prompt: '_____ Tasche (çanta)',
    answer: 'die',
    pronounce: ['die Tasche'],
  },
  {
    id: 'p2-art-ein-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.artikel.ein-eine'],
    familyId: 'p2-art-ein-vater',
    instruction: 'Doğru belirsiz artikeli seç:',
    prompt: 'der Vater → _____ Vater',
    answer: 'ein',
    options: ['ein', 'eine', 'kein', 'keine'],
    pronounce: ['ein Vater'],
  },
  {
    id: 'p2-art-eine-mutter-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.ein-eine'],
    familyId: 'p2-art-eine-mutter',
    instruction: 'Belirsiz artikele çevir:',
    prompt: 'die Mutter → _____ Mutter',
    answer: 'eine',
    pronounce: ['eine Mutter'],
  },
  {
    id: 'p2-art-ein-kind-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.ein-eine'],
    familyId: 'p2-art-ein-kind',
    instruction: 'Belirsiz artikele çevir:',
    prompt: 'das Kind → _____ Kind',
    answer: 'ein',
    pronounce: ['ein Kind'],
  },
  {
    id: 'p2-art-cogul-belirsiz-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['articles.artikel.cogul-belirsiz-yok'],
    familyId: 'p2-art-cogul',
    instruction: 'Çoğul isimlerde belirsiz artikel nasıldır?',
    prompt: 'die Blumen → belirsiz hâli nedir?',
    answer: 'Belirsiz artikel yoktur, artikelsiz kullanılır (Blumen).',
    options: [
      'Belirsiz artikel yoktur, artikelsiz kullanılır (Blumen).',
      'eine Blumen',
      'ein Blumen',
      'die Blumen',
    ],
  },
  {
    id: 'p2-art-was-ist-das-wasser-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.artikel.was-ist-das'],
    familyId: 'p2-art-was-ist-das',
    instruction: '"Was ist das?" sorusuna doğru cevabı seç:',
    prompt: 'Was ist das? (su)',
    answer: 'Das ist ein Wasser.',
    options: ['Das ist ein Wasser.', 'Das ist das Wasser.', 'Das ist eine Wasser.', 'Das Wasser ist.'],
    pronounce: ['Was ist das?', 'Das ist ein Wasser.'],
  },
  {
    id: 'p2-art-was-ist-das-tasche-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.artikel.was-ist-das'],
    familyId: 'p2-art-was-ist-das-tasche',
    instruction: 'Bir nesneyi tanıt:',
    prompt: 'Was ist das? → Das ist _____ Tasche.',
    answer: 'eine',
    pronounce: ['Das ist eine Tasche.'],
  },
  {
    id: 'p2-art-was-ist-das-buch-free',
    topicId: T.articles, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['articles.artikel.was-ist-das', 'articles.wortschatz.nesneler'],
    familyId: 'p2-art-was-ist-das-buch',
    instruction: '"Bu bir kitap." cümlesini Almanca yaz:',
    prompt: 'Bu bir kitap. → ______',
    answer: 'Das ist ein Buch.',
    pronounce: ['Das ist ein Buch.'],
  },
  {
    id: 'p2-art-nesneler-matching',
    topicId: T.articles, legacyDay: 2,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['articles.wortschatz.nesneler'],
    familyId: 'p2-art-nesneler-match',
    instruction: 'Temel nesneleri Türkçesiyle eşleştir.',
    pairs: [
      { left: 'der Stuhl', right: 'sandalye' },
      { left: 'das Heft', right: 'defter' },
      { left: 'die Schuhe', right: 'ayakkabılar' },
      { left: 'das Buch', right: 'kitap' },
    ],
    pronounce: ['der Stuhl', 'das Heft', 'die Schuhe', 'das Buch'],
  },
  {
    id: 'p2-wb-artikel-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['articles.artikel.der-die-das-die-pl', 'articles.wortschatz.nesneler'],
    familyId: 'p2-art-heft',
    instruction: 'Doğru belirli artikeli seç:',
    prompt: '_____ Heft (defter)',
    answer: 'das',
    options: ['der', 'die', 'das', 'ein'],
    pronounce: ['das Heft'],
  },

  /* ---- Artikel Zinciri — kein, dein, mein (15) ---- */
  {
    id: 'p2-kmd-kein-vater-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.kein-keine'],
    familyId: 'p2-kmd-kein-vater',
    instruction: 'Olumsuz artikele çevir:',
    prompt: 'ein Vater → _____ Vater',
    answer: 'kein',
    pronounce: ['kein Vater'],
  },
  {
    id: 'p2-kmd-keine-mutter-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.kein-keine'],
    familyId: 'p2-kmd-keine-mutter',
    instruction: 'Olumsuz artikele çevir:',
    prompt: 'eine Mutter → _____ Mutter',
    answer: 'keine',
    pronounce: ['keine Mutter'],
  },
  {
    id: 'p2-kmd-kein-handy-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.artikel.kein-keine'],
    familyId: 'p2-kmd-kein-handy',
    instruction: 'Doğru olumsuz artikeli seç:',
    prompt: 'das Handy → ein Handy → _____ Handy',
    answer: 'kein',
    options: ['kein', 'keine', 'dein', 'mein'],
    pronounce: ['kein Handy'],
  },
  {
    id: 'p2-kmd-keine-blumen-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.artikel.kein-keine'],
    familyId: 'p2-kmd-keine-blumen',
    instruction: 'Doğru olumsuz artikeli seç:',
    prompt: 'die Blumen → _____ Blumen',
    answer: 'keine',
    options: ['kein', 'keine', 'dein', 'mein'],
    pronounce: ['keine Blumen'],
  },
  {
    id: 'p2-kmd-mein-vater-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.mein-meine'],
    familyId: 'p2-kmd-mein-vater',
    instruction: 'İyelik artikeline çevir (benim):',
    prompt: 'kein Vater → _____ Vater',
    answer: 'mein',
    pronounce: ['mein Vater'],
  },
  {
    id: 'p2-kmd-meine-mutter-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.mein-meine'],
    familyId: 'p2-kmd-meine-mutter',
    instruction: 'İyelik artikeline çevir (benim):',
    prompt: 'keine Mutter → _____ Mutter',
    answer: 'meine',
    pronounce: ['meine Mutter'],
  },
  {
    id: 'p2-kmd-dein-handy-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.dein-deine'],
    familyId: 'p2-kmd-dein-handy',
    instruction: 'İyelik artikeline çevir (senin):',
    prompt: 'kein Handy → _____ Handy',
    answer: 'dein',
    pronounce: ['dein Handy'],
  },
  {
    id: 'p2-kmd-deine-tante-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.dein-deine'],
    familyId: 'p2-kmd-deine-tante',
    instruction: 'İyelik artikeline çevir (senin):',
    prompt: 'keine Tante → _____ Tante',
    answer: 'deine',
    pronounce: ['deine Tante'],
  },
  {
    id: 'p2-kmd-chain-wasser-free',
    topicId: T.articles, legacyDay: 2,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['articles.artikel.zincir'],
    familyId: 'p2-kmd-chain-wasser',
    instruction: 'Artikel zincirinin devamını doğru sırada diz: das Wasser → ein Wasser → ? → ? → ?',
    prompt: 'kein Wasser / dein Wasser / mein Wasser',
    answer: 'kein Wasser dein Wasser mein Wasser',
    words: ['kein Wasser', 'dein Wasser', 'mein Wasser'],
    pronounce: ['kein Wasser', 'dein Wasser', 'mein Wasser'],
  },
  {
    id: 'p2-kmd-chain-kinder-free',
    topicId: T.articles, legacyDay: 2,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['articles.artikel.zincir'],
    familyId: 'p2-kmd-chain-kinder',
    instruction: 'Artikel zincirinin devamını doğru sırada diz: die Kinder → ? → ? → ?',
    prompt: 'keine Kinder / deine Kinder / meine Kinder',
    answer: 'keine Kinder deine Kinder meine Kinder',
    words: ['keine Kinder', 'deine Kinder', 'meine Kinder'],
    pronounce: ['keine Kinder', 'deine Kinder', 'meine Kinder'],
  },
  {
    id: 'p2-kmd-wie-ist-dein-buch-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.artikel.wie-ist-dein'],
    familyId: 'p2-kmd-wie-ist-dein-buch',
    instruction: 'Boşluğu doldur (senin):',
    prompt: 'Wie ist _____ Buch?',
    answer: 'dein',
    pronounce: ['Wie ist dein Buch?'],
  },
  {
    id: 'p2-kmd-mein-buch-ist-gut-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.artikel.wie-ist-dein'],
    familyId: 'p2-kmd-mein-buch-ist-gut',
    instruction: 'Cevap ver (benim):',
    prompt: '_____ Buch ist gut.',
    answer: 'Mein',
    pronounce: ['Mein Buch ist gut.'],
  },
  {
    id: 'p2-kmd-wie-ist-deine-schokolade-free',
    topicId: T.articles, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['articles.artikel.wie-ist-dein'],
    familyId: 'p2-kmd-wie-ist-deine-schokolade',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Senin çikolatan nasıl? → ______',
    answer: 'Wie ist deine Schokolade?',
    pronounce: ['Wie ist deine Schokolade?'],
  },
  {
    id: 'p2-kmd-error-eine-vater',
    topicId: T.articles, legacyDay: 2,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['articles.artikel.ein-eine', 'articles.artikel.der-die-das-die-pl'],
    familyId: 'p2-art-ein-vater',
    instruction: 'Hata avı — doğru artikel hangisi?',
    prompt: 'Eine Vater ist zu Hause.',
    answer: 'Ein Vater ist zu Hause.',
    explanation: 'der Vater eril bir isimdir → ein, eine değil.',
    pronounce: ['Ein Vater ist zu Hause.'],
  },
  {
    id: 'p2-wb-kein-vater-tr-de',
    topicId: T.articles, legacyDay: 2,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['articles.artikel.kein-keine'],
    familyId: 'p2-kmd-kein-vater',
    instruction: 'Türkçeden Almancaya kur — hiç baba değil',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'hiç baba değil',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'kein' }, { id: 't2', text: 'Vater' }, { id: 't3', text: 'ein' }, { id: 't4', text: 'mein' },
      ],
      acceptedSequences: [['kein', 'Vater']],
    },
    answer: 'kein Vater',
    pronounce: ['kein Vater'],
  },

  /* ---- Çoğul (6) ---- */
  {
    id: 'p3-mk-zimmer-mc',
    topicId: T.articles, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.miktar.oda'],
    familyId: 'p3-mk-zimmer',
    instruction: '"das Zimmer" çoğulda nasıl yazılır?',
    prompt: 'das Zimmer → çoğul',
    answer: 'die Zimmer',
    options: ['die Zimmer', 'die Zimmern', 'die Zimmers', 'das Zimmer'],
  },
  {
    id: 'p3-mk-drei-zimmer-fill',
    topicId: T.articles, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.miktar.oda'],
    familyId: 'p3-mk-drei-zimmer',
    instruction: 'Boşluğu doldur:',
    prompt: 'Unsere Wohnung hat drei ___. (evimizde üç oda var)',
    answer: 'Zimmer',
    pronounce: ['Unsere Wohnung hat drei Zimmer.'],
  },
  {
    id: 'p3-mk-cogul-genel-mc',
    topicId: T.articles, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['articles.cogul.genel'],
    familyId: 'p3-mk-cogul-genel',
    instruction: 'Genel bir ifadede ("hayvanları severim" gibi) çoğul isim nasıl kullanılır?',
    prompt: 'Meine Schwester mag ___. (hayvanları çok seviyor)',
    answer: 'Tiere',
    options: ['Tiere', 'die Tiere', 'ein Tiere', 'einen Tiere'],
  },
  {
    id: 'p3-mk-error-die-tiere',
    topicId: T.articles, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['articles.cogul.genel'],
    familyId: 'p3-mk-cogul-genel',
    instruction: 'Hata avı — genel ifadede artikel gerekli mi?',
    prompt: 'Meine Schwester mag die Tiere.',
    answer: 'Meine Schwester mag Tiere.',
    explanation: 'Belirli hayvanlardan değil, genel olarak hayvanlardan bahsediliyor; genel çoğulda artikel kullanılmaz.',
    pronounce: ['Meine Schwester mag Tiere.'],
  },
  {
    id: 'p3-mk-buecher-mc',
    topicId: T.articles, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['articles.cogul.umlaut'],
    familyId: 'p3-mk-buecher',
    instruction: '"das Buch" çoğulda nasıl olur?',
    prompt: 'das Buch → çoğul',
    answer: 'die Bücher',
    options: ['die Bücher', 'die Buche', 'die Buchs', 'die Buchen'],
  },
  {
    id: 'p3-mk-buecher-fill',
    topicId: T.articles, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.cogul.umlaut'],
    familyId: 'p3-mk-buecher-fill',
    instruction: 'Boşluğu doldur:',
    prompt: 'Auf dem Tisch gibt es ___. (masanın üzerinde kitaplar var — Buch)',
    answer: 'Bücher',
    pronounce: ['Auf dem Tisch gibt es Bücher.'],
  },

  /* ---- Olumsuz Cümle — nicht / kein (20) ---- */
  {
    id: 'p2-neg-nicht-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.olumsuzluk.nicht'],
    familyId: 'p2-neg-nicht-kural',
    instruction: '"nicht" neyi olumsuzlar?',
    prompt: 'nicht',
    answer: 'fiili / diğer bilgiyi',
    options: ['fiili / diğer bilgiyi', 'yalnızca isimleri', 'yalnızca artikelleri', 'yalnızca zamirleri'],
  },
  {
    id: 'p2-neg-kein-haben-mc',
    topicId: T.articles, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['articles.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-kein-kural',
    instruction: '"kein/keine" en çok hangi fiille birlikte nesneyi olumsuzlar?',
    prompt: 'kein / keine',
    answer: 'haben',
    options: ['haben', 'gehen', 'machen', 'trinken'],
  },
  {
    id: 'p2-neg-arbeite-nicht-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.olumsuzluk.nicht'],
    familyId: 'p2-neg-arbeiten',
    instruction: 'Cümleyi olumsuz yap:',
    prompt: 'Ich arbeite heute _____.',
    answer: 'nicht',
    pronounce: ['Ich arbeite heute nicht.'],
  },
  {
    id: 'p2-neg-geht-nicht-schule-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.olumsuzluk.nicht'],
    familyId: 'p2-neg-gehen',
    instruction: 'Cümleyi olumsuz yap:',
    prompt: 'Sie geht heute _____ zur Schule.',
    answer: 'nicht',
    pronounce: ['Sie geht heute nicht zur Schule.'],
  },
  {
    id: 'p2-neg-kommt-nicht-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['articles.olumsuzluk.nicht'],
    familyId: 'p2-neg-kommen',
    instruction: 'Boşluğu doldur (kommen):',
    prompt: 'Er _____ heute nicht zur Schule.',
    answer: 'kommt',
    pronounce: ['Er kommt heute nicht zur Schule.'],
  },
  {
    id: 'p2-neg-isst-nicht-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['articles.olumsuzluk.nicht'],
    familyId: 'p2-neg-essen',
    instruction: 'Cümleyi olumsuz yap:',
    prompt: 'Meine Mutter isst _____.',
    answer: 'nicht',
    pronounce: ['Meine Mutter isst nicht.'],
  },
  {
    id: 'p2-neg-habe-kein-geld-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-geld',
    instruction: 'Cümleyi olumsuz yap — nesneyi olumsuzla:',
    prompt: 'Ich habe _____ Geld.',
    answer: 'kein',
    pronounce: ['Ich habe kein Geld.'],
  },
  {
    id: 'p2-neg-habe-keine-schwester-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-schwester',
    instruction: 'Cümleyi olumsuz yap — nesneyi olumsuzla:',
    prompt: 'Ich habe _____ Schwester.',
    answer: 'keine',
    pronounce: ['Ich habe keine Schwester.'],
  },
  {
    id: 'p2-neg-hat-keine-tasche-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-tasche',
    instruction: 'Cümleyi olumsuz yap — nesneyi olumsuzla:',
    prompt: 'Sie hat _____ Tasche.',
    answer: 'keine',
    pronounce: ['Sie hat keine Tasche.'],
  },
  {
    id: 'p2-neg-donusum-arbeiten-free',
    topicId: T.articles, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['articles.olumsuzluk.donusum', 'articles.olumsuzluk.nicht'],
    familyId: 'p2-neg-arbeiten',
    instruction: 'Olumsuz yap:',
    prompt: 'Ich arbeite heute. → ______',
    answer: 'Ich arbeite heute nicht.',
    pronounce: ['Ich arbeite heute nicht.'],
  },
  {
    id: 'p2-neg-donusum-haben-free',
    topicId: T.articles, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['articles.olumsuzluk.donusum', 'articles.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-geld',
    instruction: 'Olumsuz yap:',
    prompt: 'Ich habe Geld. → ______',
    answer: 'Ich habe kein Geld.',
    pronounce: ['Ich habe kein Geld.'],
  },
  {
    id: 'p2-neg-error-keine-schwester',
    topicId: T.articles, legacyDay: 2,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['articles.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-schwester',
    instruction: 'Hata avı — doğru artikel hangisi?',
    prompt: 'Ich habe kein Schwester.',
    answer: 'Ich habe keine Schwester.',
    explanation: 'die Schwester dişildir → keine.',
    pronounce: ['Ich habe keine Schwester.'],
  },
  {
    id: 'p2-neg-error-vater-arbeitet',
    topicId: T.articles, legacyDay: 2,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['articles.olumsuzluk.nicht', 'sentence-building.verben.gehen-zur'],
    familyId: 'p2-neg-vater-arbeit',
    instruction: 'Hata avı — doğru fiil hangisi?',
    prompt: 'Mein Vater arbeitet nicht jeden Tag zur Arbeit.',
    answer: 'Mein Vater geht nicht jeden Tag zur Arbeit.',
    explanation: '"zur Arbeit" gehen fiiliyle kullanılır, arbeiten ile değil.',
    pronounce: ['Mein Vater geht nicht jeden Tag zur Arbeit.'],
  },
  {
    id: 'p2-neg-free-tante-kommt',
    topicId: T.articles, legacyDay: 2,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.olumsuzluk.donusum', 'articles.olumsuzluk.nicht'],
    familyId: 'p2-pos-tante-kommt',
    instruction: 'Olumsuz yap:',
    prompt: 'Meine Tante kommt heute. → ______',
    answer: 'Meine Tante kommt heute nicht.',
    pronounce: ['Meine Tante kommt heute nicht.'],
  },
  {
    id: 'p2-neg-order-wir-schule',
    topicId: T.articles, legacyDay: 2,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.olumsuzluk.nicht', 'sentence-building.verben.gehen-zur'],
    familyId: 'p2-pos-wir-schule',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Wir / gehen / heute / nicht / zur / Schule.',
    answer: 'Wir gehen heute nicht zur Schule.',
    words: ['Wir', 'gehen', 'heute', 'nicht', 'zur', 'Schule'],
    pronounce: ['Wir gehen heute nicht zur Schule.'],
  },
  {
    id: 'p2-neg-free-kind-isst-tr',
    topicId: T.articles, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['articles.olumsuzluk.nicht'],
    familyId: 'p2-neg-kind-isst',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Çocuğum bugün yemek yemiyor. → ______',
    answer: 'Mein Kind isst heute nicht.',
    pronounce: ['Mein Kind isst heute nicht.'],
  },
  {
    id: 'p2-neg-ich-habe-keine-tasche-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-tasche',
    instruction: 'Cümleyi olumsuz yap — nesneyi olumsuzla:',
    prompt: 'Ich habe _____ Tasche.',
    answer: 'keine',
    pronounce: ['Ich habe keine Tasche.'],
  },
  {
    id: 'p2-neg-free-schwester-liest-tr',
    topicId: T.articles, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['articles.olumsuzluk.nicht', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-schwester-buch',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kız kardeşim her gün okumaz. → ______',
    answer: 'Meine Schwester liest nicht jeden Tag.',
    pronounce: ['Meine Schwester liest nicht jeden Tag.'],
  },
  {
    id: 'p2-neg-wb-wasser-tr-de',
    topicId: T.articles, legacyDay: 2,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-wasser',
    instruction: 'Türkçeden Almancaya kur — Bizim suyumuz yok.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Bizim suyumuz yok.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Wir' }, { id: 't2', text: 'haben' }, { id: 't3', text: 'kein' }, { id: 't4', text: 'Wasser.' },
        { id: 't5', text: 'keine' }, { id: 't6', text: 'nicht' },
      ],
      acceptedSequences: [['Wir', 'haben', 'kein', 'Wasser.']],
    },
    answer: 'Wir haben kein Wasser.',
    pronounce: ['Wir haben kein Wasser.'],
  },
  {
    id: 'p2-neg-extra-lese-nicht-fill',
    topicId: T.articles, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.olumsuzluk.nicht'],
    familyId: 'p2-gun-buch',
    instruction: 'Cümleyi olumsuz yap:',
    prompt: 'Ich lese _____ jeden Tag.',
    answer: 'nicht',
    pronounce: ['Ich lese nicht jeden Tag.'],
  },

  /* ---- nicht Nereye Gider? (2) ---- */
  {
    id: 'p7-fii-nicht-order',
    topicId: T.articles, legacyDay: 7,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.fiil.nicht-yeri'],
    familyId: 'p7-fii-nicht-order',
    instruction: 'Kelimeleri doğru sıraya diz — Bugün gelmiyorum.',
    answer: 'Ich komme heute nicht.',
    pronounce: ['Ich komme heute nicht.'],
  },
  {
    id: 'p7-fii-nicht-error',
    topicId: T.articles, legacyDay: 7,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['articles.fiil.nicht-yeri'],
    familyId: 'p7-fii-nicht-error',
    instruction: '`nicht` yanlış yerde — cümleyi düzelt:',
    prompt: 'Ich nicht komme heute.',
    answer: 'Ich komme heute nicht.',
    explanation: '`nicht` fiilden ve zaman bilgisinden sonra, cümlenin sonuna gider.',
  },
];
