/**
 * Mein Tag — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const DAILY_ROUTINE_EXERCISES: AuthoredExercise[] = [
  /* ---- Günlük Hayat Cümleleri (11) ---- */
  {
    id: 'p2-gun-order-arbeit',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.gunluk.okul-is'],
    familyId: 'p2-gun-arbeit',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Mein / Vater / geht / jeden / Tag / zur / Arbeit.',
    answer: 'Mein Vater geht jeden Tag zur Arbeit.',
    words: ['Mein', 'Vater', 'geht', 'jeden', 'Tag', 'zur', 'Arbeit'],
    pronounce: ['Mein Vater geht jeden Tag zur Arbeit.'],
  },
  {
    id: 'p2-gun-order-schule',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.gunluk.okul-is'],
    familyId: 'p2-gun-schule',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Er / geht / um / 2 / Uhr / zur / Schule.',
    answer: 'Er geht um 2 Uhr zur Schule.',
    words: ['Er', 'geht', 'um', '2', 'Uhr', 'zur', 'Schule'],
    pronounce: ['Er geht um 2 Uhr zur Schule.'],
  },
  {
    id: 'p2-gun-listen-kaffee',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['daily-routine.gunluk.kahve-spor'],
    familyId: 'p2-gun-kaffee',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich trinke jeden Morgen ein Kaffee.',
    audioText: 'Ich trinke jeden Morgen ein Kaffee.',
    answer: 'Ich trinke jeden Morgen ein Kaffee.',
    options: [
      'Ich trinke jeden Morgen ein Kaffee.',
      'Ich mache jeden Tag Sport.',
      'Ich esse jeden Tag ein Brot.',
      'Ich lese jeden Tag ein Buch.',
    ],
    audio: { prompt: { text: 'Ich trinke jeden Morgen ein Kaffee.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p2-gun-listen-buch',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['daily-routine.gunluk.kitap-okuma'],
    familyId: 'p2-gun-buch',
    instruction: 'Duyduğunu seç:',
    prompt: 'Liest du jeden Tag ein Buch?',
    audioText: 'Liest du jeden Tag ein Buch?',
    answer: 'Liest du jeden Tag ein Buch?',
    options: [
      'Liest du jeden Tag ein Buch?',
      'Machst du jeden Tag Sport?',
      'Trinkst du jeden Tag ein Kaffee?',
      'Gehst du jeden Tag zur Schule?',
    ],
    audio: { prompt: { text: 'Liest du jeden Tag ein Buch?', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p2-gun-dictation-schule',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['daily-routine.gunluk.okul-is'],
    familyId: 'p2-gun-schule',
    instruction: 'Okul cümlesini duydun — aynen yaz:',
    audioText: 'Er geht um 2 Uhr zur Schule.',
    answer: 'Er geht um 2 Uhr zur Schule.',
    audio: { prompt: { text: 'Er geht um 2 Uhr zur Schule.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p2-gun-dictation-sport',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['daily-routine.gunluk.kahve-spor'],
    familyId: 'p2-gun-sport-dictation',
    instruction: 'Spor cümlesini duydun — aynen yaz:',
    audioText: 'Ich mache jeden Tag Sport.',
    answer: 'Ich mache jeden Tag Sport.',
    audio: { prompt: { text: 'Ich mache jeden Tag Sport.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p2-gun-spoken-tanitim',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['daily-routine.gunluk.okul-is', 'daily-routine.gunluk.kahve-spor'],
    familyId: 'p2-gun-spoken',
    instruction: 'Sesli görev: günlük rutinini anlat.',
    requirements: ['Ich mache ...', 'Ich gehe ...'],
    sampleAnswer: 'Ich mache jeden Tag Sport. Ich gehe um 2 Uhr zur Schule.',
    pronounce: ['Ich mache jeden Tag Sport.', 'Ich gehe um 2 Uhr zur Schule.'],
  },
  {
    id: 'p2-gun-spoken-olumsuz',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['articles.olumsuzluk.nicht', 'articles.olumsuzluk.kein-haben'],
    familyId: 'p2-gun-spoken-neg',
    instruction: 'Sesli görev: bir şeyin olmadığını söyle.',
    requirements: ['Ich habe kein/keine ...', 'Ich ... nicht.'],
    sampleAnswer: 'Ich habe kein Geld. Ich arbeite heute nicht.',
    pronounce: ['Ich habe kein Geld.', 'Ich arbeite heute nicht.'],
  },
  {
    id: 'p2-gun-mini-dialog-schule-free',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.gunluk.mini-dialog'],
    familyId: 'p2-gun-dialog',
    instruction: 'Mini diyalog: B ne demeli?',
    prompt: 'A: Gehst du heute zur Schule?\nB: ______',
    answer: 'Ja, ich gehe heute zur Schule.',
    acceptedAnswers: ['Nein, ich gehe heute nicht zur Schule.'],
    openEnded: true,
    pronounce: ['Ja, ich gehe heute zur Schule.'],
  },
  {
    id: 'p2-gun-mini-dialog-schwester-free',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.gunluk.mini-dialog'],
    familyId: 'p2-gun-dialog',
    instruction: 'Mini diyalog: B ne demeli?',
    prompt: 'A: Hast du eine Schwester?\nB: ______',
    answer: 'Nein, ich habe keine Schwester.',
    acceptedAnswers: ['Ja, ich habe eine Schwester.'],
    openEnded: true,
    pronounce: ['Nein, ich habe keine Schwester.'],
  },
  {
    id: 'p2-gun-wb-geld-tr-de',
    topicId: T.dailyRoutine, legacyDay: 2,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['articles.olumsuzluk.kein-haben'],
    familyId: 'p2-neg-geld',
    instruction: 'Türkçeden Almancaya kur — Param yok.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Param yok.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'habe' }, { id: 't3', text: 'kein' }, { id: 't4', text: 'Geld.' },
        { id: 't5', text: 'keine' }, { id: 't6', text: 'Schwester.' },
      ],
      acceptedSequences: [['Ich', 'habe', 'kein', 'Geld.']],
    },
    answer: 'Ich habe kein Geld.',
    pronounce: ['Ich habe kein Geld.'],
  },

  /* ---- Günlük Rutin Fiilleri (12) ---- */
  {
    id: 'p3-gh-fruehstuecken-fill',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-fruehstuecken',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich ___ am Morgen. (sabah kahvaltı yapıyorum)',
    answer: 'frühstücke',
    pronounce: ['Ich frühstücke am Morgen.'],
  },
  {
    id: 'p3-gh-putze-fill',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-putze',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich ___ mein Zimmer. (odamı temizliyorum)',
    answer: 'putze',
    pronounce: ['Ich putze mein Zimmer.'],
  },
  {
    id: 'p3-gh-giesst-fill',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-giesst',
    instruction: 'Boşluğu doldur (gießen: sie gießt):',
    prompt: 'Meine Mutter ___ die Blumen. (çiçekleri suluyor)',
    answer: 'gießt',
    pronounce: ['Meine Mutter gießt die Blumen.'],
  },
  {
    id: 'p3-gh-hoert-wb-tr-de',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-hoert',
    instruction: 'Türkçeden Almancaya kur — Annem müzik dinliyor.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Annem müzik dinliyor.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Meine' }, { id: 't2', text: 'Mutter' }, { id: 't3', text: 'hört' }, { id: 't4', text: 'Musik.' },
        { id: 't5', text: 'Vater' },
      ],
      acceptedSequences: [['Meine', 'Mutter', 'hört', 'Musik.']],
    },
    answer: 'Meine Mutter hört Musik.',
    pronounce: ['Meine Mutter hört Musik.'],
  },
  {
    id: 'p3-gh-spoken-tag',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['daily-routine.gunluk-rutin', 'separable-verbs.ayrilabilen.kural'],
    familyId: 'p3-gh-spoken-tag',
    instruction: 'Sesli görev: bir gününü anlat.',
    requirements: ['Ich stehe ... auf.', 'Ich frühstücke ...', 'Am Abend ...'],
    sampleAnswer: 'Ich stehe um 7 Uhr auf. Ich frühstücke am Morgen. Am Abend gehe ich nach Hause.',
    pronounce: ['Ich stehe um 7 Uhr auf.', 'Ich frühstücke am Morgen.', 'Am Abend gehe ich nach Hause.'],
  },
  {
    id: 'p3-gh-dictation-mutter',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'dictation', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-giesst',
    instruction: 'Annemle ilgili cümleyi duydun — aynen yaz:',
    audioText: 'Meine Mutter gießt die Blumen.',
    answer: 'Meine Mutter gießt die Blumen.',
    audio: { prompt: { text: 'Meine Mutter gießt die Blumen.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p3-gh-fruehstuck-fill',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['daily-routine.gunluk-rutin', 'places.kontraksiyon.zum'],
    familyId: 'p3-gh-fruehstuck',
    instruction: 'Boşluğu doldur:',
    prompt: '___ Frühstück esse ich Brot. (kahvaltıda ekmek yiyorum)',
    answer: 'Zum',
    pronounce: ['Zum Frühstück esse ich Brot.'],
  },
  {
    id: 'p3-gh-mutter-kaffee-fill',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-mutter-kaffee',
    instruction: 'Boşluğu doldur (trinken):',
    prompt: 'Meine Mutter ___ Kaffee. (annem kahve içiyor)',
    answer: 'trinkt',
    pronounce: ['Meine Mutter trinkt Kaffee.'],
  },
  {
    id: 'p3-gh-lerne-deutsch-mc',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-lerne-deutsch',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Ich lerne Deutsch.',
    answer: 'Ben Almanca öğreniyorum.',
    options: ['Ben Almanca öğreniyorum.', 'Ben Almanca konuşuyorum.', 'Ben Almanca dersim var.', 'Ben Almanca biliyorum.'],
    pronounce: ['Ich lerne Deutsch.'],
  },
  {
    id: 'p3-gh-deutschunterricht-fill',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-deutschunterricht',
    instruction: 'Boşluğu doldur (haben):',
    prompt: 'Ich ___ heute Deutschunterricht. (bugün Almanca dersim var)',
    answer: 'habe',
    pronounce: ['Ich habe heute Deutschunterricht.'],
  },
  {
    id: 'p3-gh-zusammen-kaffee-mc',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-zusammen-kaffee',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Wir trinken zusammen Kaffee.',
    answer: 'Birlikte kahve içiyoruz.',
    options: ['Birlikte kahve içiyoruz.', 'Birlikte yemek yiyoruz.', 'Ayrı ayrı kahve içiyoruz.', 'Birlikte su içiyoruz.'],
    pronounce: ['Wir trinken zusammen Kaffee.'],
  },
  {
    id: 'p3-gh-vater-zeitung-fill',
    topicId: T.dailyRoutine, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['daily-routine.gunluk-rutin'],
    familyId: 'p3-gh-vater-zeitung',
    instruction: 'Boşluğu doldur (lesen: er liest):',
    prompt: 'Mein Vater ___ die Zeitung. (babam gazete okuyor)',
    answer: 'liest',
    pronounce: ['Mein Vater liest die Zeitung.'],
  },

  /* ---- Mein Tag — Sabah (8) ---- */
  {
    id: 'p10-sabah-match-rutin',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: [
      'daily-routine.sabah.gesicht',
      'daily-routine.sabah.zaehne',
      'daily-routine.sabah.duschen',
      'separable-verbs.verb.anziehen-chunk',
      'daily-routine.sabah.fruehstuecken',
    ],
    familyId: 'p10-sabah-match',
    instruction: 'Sabah cümlesini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'Ich wasche mein Gesicht.', right: 'Yüzümü yıkarım.' },
      { left: 'Ich putze meine Zähne.', right: 'Dişlerimi fırçalarım.' },
      { left: 'Ich dusche.', right: 'Duş alırım.' },
      { left: 'Ich ziehe mich an.', right: 'Giyinirim.' },
      { left: 'Ich frühstücke.', right: 'Kahvaltı ederim.' },
    ],
    pronounce: ['Ich wasche mein Gesicht.', 'Ich putze meine Zähne.', 'Ich dusche.', 'Ich ziehe mich an.', 'Ich frühstücke.'],
  },
  {
    id: 'p10-sabah-gesicht-fill',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['daily-routine.sabah.gesicht'],
    familyId: 'p10-sabah-gesicht',
    instruction: 'Kelimeyi yaz — Yüzümü yıkıyorum.',
    prompt: 'Ich wasche mein ___. (yüz)',
    answer: 'Gesicht',
    pronounce: ['Ich wasche mein Gesicht.'],
  },
  {
    id: 'p10-sabah-zaehne-fill',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['daily-routine.sabah.zaehne'],
    familyId: 'p10-sabah-zaehne',
    instruction: 'Kelimeyi yaz — Dişlerimi fırçalıyorum.',
    prompt: 'Ich putze meine ___. (dişler)',
    answer: 'Zähne',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich putze meine Zähne.'],
  },
  {
    id: 'p10-sabah-dusche-mc',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['daily-routine.sabah.duschen'],
    familyId: 'p10-sabah-dusche',
    instruction: 'Günlük dilde kısası yeterlidir — hangisi?',
    prompt: 'Ich dusche mich. → günlük kısa biçim',
    answer: 'Ich dusche.',
    options: ['Ich dusche.', 'Ich dusche ein.', 'Ich dusche auf.', 'Ich dusche mich aus.'],
    pronounce: ['Ich dusche.'],
  },
  {
    id: 'p10-sabah-fruehstueck-fark-mc',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['daily-routine.sabah.fruehstueck-fark'],
    familyId: 'p10-sabah-fark',
    instruction: '"Frühstück machen" ne demektir?',
    prompt: 'Frühstück machen',
    answer: 'kahvaltı hazırlamak',
    options: ['kahvaltı hazırlamak', 'kahvaltı etmek', 'kahvaltı sipariş etmek', 'kahvaltıyı atlamak'],
    pronounce: ['Ich mache Frühstück.'],
  },
  {
    id: 'p10-sabah-fruehstuecke-free',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['daily-routine.sabah.fruehstuecken'],
    familyId: 'p10-sabah-fruehstueck',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kahvaltı ediyorum. → ______',
    answer: 'Ich frühstücke.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich frühstücke.'],
  },
  {
    id: 'p10-sabah-mache-order',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.sabah.fruehstueck-fark'],
    familyId: 'p10-sabah-mache',
    instruction: 'Kelimeleri doğru sıraya diz — Kahvaltı hazırlıyorum.',
    answer: 'Ich mache Frühstück.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich mache Frühstück.'],
  },
  {
    id: 'p10-sabah-wb-gesicht',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.sabah.gesicht'],
    familyId: 'p10-sabah-gesicht-wb',
    instruction: 'Türkçeden Almancaya kur — Yüzümü yıkıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Yüzümü yıkıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'wasche' }, { id: 't3', text: 'mein' },
        { id: 't4', text: 'Gesicht.' }, { id: 't5', text: 'meine' }, { id: 't6', text: 'putze' },
      ],
      acceptedSequences: [['Ich', 'wasche', 'mein', 'Gesicht.']],
    },
    answer: 'Ich wasche mein Gesicht.',
    pronounce: ['Ich wasche mein Gesicht.'],
  },

  /* ---- Mein Tag — Gün İçinde (8) ---- */
  {
    id: 'p10-gun-schule-fill',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['daily-routine.gun.schule'],
    familyId: 'p10-gun-schule',
    instruction: 'Edatı yaz — Okula gidiyorum.',
    prompt: 'Ich gehe ___ Schule. (okula)',
    answer: 'zur',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich gehe zur Schule.'],
  },
  {
    id: 'p10-gun-lerne-order',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.gun.lernen'],
    familyId: 'p10-gun-lerne',
    instruction: 'Kelimeleri doğru sıraya diz — Okulda Almanca ve Matematik öğreniyorum.',
    answer: 'Ich lerne Deutsch und Mathe in der Schule.',
    pronounce: ['Ich lerne Deutsch und Mathe in der Schule.'],
  },
  {
    id: 'p10-gun-mittag-mc',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['daily-routine.gun.mittag'],
    familyId: 'p10-gun-mittag',
    instruction: 'Hangisi "Öğle yemeği yerim." demektir?',
    prompt: 'Öğle yemeği yerim.',
    answer: 'Ich esse zu Mittag.',
    options: ['Ich esse zu Mittag.', 'Ich esse zu Abend.', 'Ich esse zum Frühstück.', 'Ich trinke zu Mittag.'],
    pronounce: ['Ich esse zu Mittag.'],
  },
  {
    id: 'p10-gun-hausaufgaben-wb',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.gun.hausaufgaben'],
    familyId: 'p10-gun-hausaufgaben',
    instruction: 'Türkçeden Almancaya kur — Ev ödevimi yapıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ev ödevimi yapıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'mache' }, { id: 't3', text: 'meine' },
        { id: 't4', text: 'Hausaufgaben.' }, { id: 't5', text: 'mein' }, { id: 't6', text: 'spiele' },
      ],
      acceptedSequences: [['Ich', 'mache', 'meine', 'Hausaufgaben.']],
    },
    answer: 'Ich mache meine Hausaufgaben.',
    pronounce: ['Ich mache meine Hausaufgaben.'],
  },
  {
    id: 'p10-gun-freunde-wb',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['daily-routine.gun.freunde'],
    familyId: 'p10-gun-freunde',
    instruction: 'Türkçeden Almancaya kur — Arkadaşlarımla oynuyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Arkadaşlarımla oynuyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'spiele' }, { id: 't3', text: 'mit' },
        { id: 't4', text: 'meinen' }, { id: 't5', text: 'Freunden.' },
        { id: 't6', text: 'meiner' }, { id: 't7', text: 'meine' },
      ],
      acceptedSequences: [['Ich', 'spiele', 'mit', 'meinen', 'Freunden.']],
    },
    answer: 'Ich spiele mit meinen Freunden.',
    pronounce: ['Ich spiele mit meinen Freunden.'],
  },
  {
    id: 'p10-gun-meinen-fill',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['daily-routine.gun.freunde'],
    familyId: 'p10-gun-meinen',
    instruction: '`mit` Dativ ister — doğru biçimi yaz:',
    prompt: 'Ich spiele mit ___ Freunden. (benim)',
    answer: 'meinen',
    pronounce: ['Ich spiele mit meinen Freunden.'],
  },
  {
    id: 'p10-gun-dictation-lerne',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['daily-routine.gun.lernen'],
    familyId: 'p10-gun-dictation',
    instruction: 'Duyduğun cümleyi aynen yaz:',
    audioText: 'Ich lerne Deutsch und Mathe in der Schule.',
    answer: 'Ich lerne Deutsch und Mathe in der Schule.',
    audio: { prompt: { text: 'Ich lerne Deutsch und Mathe in der Schule.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p10-gun-error-meiner',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['daily-routine.gun.freunde'],
    familyId: 'p10-gun-error',
    instruction: 'İyelik biçimi yanlış — cümleyi düzelt:',
    prompt: 'Ich spiele mit meiner Freunden.',
    answer: 'Ich spiele mit meinen Freunden.',
    explanation: '`mit` Dativ ister; çoğulda `meinen Freunden` olur.',
    pronounce: ['Ich spiele mit meinen Freunden.'],
  },

  /* ---- Mein Tag — Akşam (7) ---- */
  {
    id: 'p10-aksam-abendessen-fill',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['daily-routine.aksam.abendessen'],
    familyId: 'p10-aksam-abendessen',
    instruction: 'Kelimeyi yaz — Saat dokuzda akşam yemeği yerim.',
    prompt: 'Ich esse um neun Uhr ___. (akşam yemeği)',
    answer: 'Abendessen',
    pronounce: ['Ich esse um neun Uhr Abendessen.'],
  },
  {
    id: 'p10-aksam-aus-order',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'ordering', difficulty: 'easy', skill: 'production',
    conceptIds: ['daily-routine.aksam.ausziehen'],
    familyId: 'p10-aksam-aus',
    instruction: 'Kelimeleri doğru sıraya diz — Üstümü çıkarıyorum.',
    answer: 'Ich ziehe mich aus.',
    pronounce: ['Ich ziehe mich aus.'],
  },
  {
    id: 'p10-aksam-buch-fill',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['daily-routine.aksam.buch'],
    familyId: 'p10-aksam-buch',
    instruction: 'Artikeli yaz — Bir kitap okuyorum.',
    prompt: 'Ich lese ___ Buch. (bir)',
    answer: 'ein',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich lese ein Buch.'],
  },
  {
    id: 'p10-aksam-bett-order',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.aksam.bett'],
    familyId: 'p10-aksam-bett',
    instruction: 'Kelimeleri doğru sıraya diz — Sonra yatağa gidiyorum.',
    answer: 'Danach gehe ich ins Bett.',
    pronounce: ['Danach gehe ich ins Bett.'],
  },
  {
    id: 'p10-aksam-spazieren-mc',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['daily-routine.aksam.spazieren'],
    familyId: 'p10-aksam-spazieren',
    instruction: '"spazieren gehen" ne demektir?',
    prompt: 'spazieren gehen',
    answer: 'yürüyüş yapmak',
    options: ['yürüyüş yapmak', 'koşmak', 'eve dönmek', 'gezmek (arabayla)'],
    pronounce: ['spazieren gehen'],
  },
  {
    id: 'p10-aksam-error-buch',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'error-correction', difficulty: 'medium', skill: 'correction',
    conceptIds: ['daily-routine.aksam.buch'],
    familyId: 'p10-aksam-error',
    instruction: 'Artikel eksik — cümleyi düzelt:',
    prompt: 'Ich lese Buch.',
    answer: 'Ich lese ein Buch.',
    explanation: 'Sayılabilen tekil nesne artikel ister: `ein Buch`.',
    pronounce: ['Ich lese ein Buch.'],
  },
  {
    id: 'p10-aksam-free-buch',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['daily-routine.aksam.buch'],
    familyId: 'p10-aksam-buch-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bir kitap okuyorum. → ______',
    answer: 'Ich lese ein Buch.',
    pronounce: ['Ich lese ein Buch.'],
  },

  /* ---- Mein Tag — Tam Anlatım (10) ---- */
  {
    id: 'p10-mix-wb-wache-sieben',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.verb.aufwachen', 'time.um.ornek'],
    familyId: 'p10-mix-wache',
    instruction: 'Türkçeden Almancaya kur — Saat yedide uyanıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Saat yedide uyanıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'wache' }, { id: 't3', text: 'um' },
        { id: 't4', text: 'sieben' }, { id: 't5', text: 'Uhr' }, { id: 't6', text: 'auf.' },
        { id: 't7', text: 'stehe' }, { id: 't8', text: 'an.' },
      ],
      acceptedSequences: [['Ich', 'wache', 'um', 'sieben', 'Uhr', 'auf.']],
    },
    answer: 'Ich wache um sieben Uhr auf.',
    explanation: 'uyanmak = aufwachen (gözlerini açmak); kalkmak = aufstehen (yataktan kalkmak). `stehe` ile kurulan cümle dilbilgisi olarak doğrudur ama "kalkıyorum" demektir.',
    pronounce: ['Ich wache um sieben Uhr auf.'],
  },
  {
    id: 'p10-mix-fernsehen-20-free',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.verb.fernsehen-cumle', 'time.um.ornek'],
    familyId: 'p10-mix-fernsehen',
    instruction: 'Saat + fiil — 20:00 televizyon izliyorum:',
    prompt: '20:00 + fernsehen → ______',
    answer: 'Ich sehe um acht Uhr fern.',
    pronounce: ['Ich sehe um acht Uhr fern.'],
  },
  {
    id: 'p10-mix-heim-16-order',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.verb.zurueckkommen', 'time.um.kural'],
    familyId: 'p10-mix-heim',
    instruction: 'Kelimeleri doğru sıraya diz — Saat dörtte eve geri dönüyorum.',
    answer: 'Um vier Uhr komme ich nach Hause zurück.',
    validation: { keyboardTolerance: true },
    pronounce: ['Um vier Uhr komme ich nach Hause zurück.'],
  },
  {
    id: 'p10-mix-builder-abend-neun',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['daily-routine.aksam.abendessen'],
    familyId: 'p10-mix-builder',
    instruction: 'Cümleyi kur:',
    prompt: 'Akşam yemeğini saat dokuzda yerim.',
    answer: 'Ich esse um neun Uhr Abendessen.',
    pronounce: ['Ich esse um neun Uhr Abendessen.'],
  },
  {
    id: 'p10-mix-match-zaman',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'separable-verbs.verb.aufstehen',
      'daily-routine.gun.mittag',
      'daily-routine.aksam.abendessen',
      'daily-routine.aksam.bett',
    ],
    familyId: 'p10-mix-match',
    instruction: 'Rutin cümlesini saatiyle eşleştir.',
    pairs: [
      { left: 'Ich stehe auf.', right: 'um sieben Uhr' },
      { left: 'Ich esse zu Mittag.', right: 'um zwölf Uhr' },
      { left: 'Ich esse Abendessen.', right: 'um neun Uhr' },
      { left: 'Ich gehe ins Bett.', right: 'um zehn Uhr' },
    ],
    pronounce: ['um sieben Uhr', 'um zwölf Uhr', 'um neun Uhr', 'um zehn Uhr'],
  },
  {
    id: 'p10-mix-dictation-tag',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['time.um.ornek'],
    familyId: 'p10-mix-dictation',
    instruction: 'Duyduğun rutin cümlesini aynen yaz:',
    audioText: 'Ich stehe um sieben Uhr auf.',
    answer: 'Ich stehe um sieben Uhr auf.',
    audio: { prompt: { text: 'Ich stehe um sieben Uhr auf.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p10-tam-free-dort-satir',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [
      'daily-routine.tam.model',
      'daily-routine.sabah.zaehne',
      'daily-routine.sabah.fruehstuecken',
    ],
    familyId: 'p10-tam-dort',
    openEnded: true,
    instruction: 'Sabah rutinini dört cümleyle yaz — ipuçları aşağıda.',
    prompt: 'uyanmak:\nkalkmak:\ndişler:\nkahvaltı:',
    hint: 'Her cümlede ayrılabilen fiilin öneki sonda olsun.',
    answer: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Ich putze meine Zähne. Ich frühstücke.',
    explanation: 'Kısa model: dört sabah cümlesi, her önek cümlenin sonunda.',
    pronounce: ['Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf.'],
  },
  {
    id: 'p10-tam-free-sekiz-satir',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [
      'daily-routine.tam.model',
      'daily-routine.gun.hausaufgaben',
      'daily-routine.gun.freunde',
      'daily-routine.aksam.bett',
    ],
    familyId: 'p10-tam-sekiz',
    openEnded: true,
    instruction: 'Gününü sekiz cümleyle yaz — ipuçları aşağıda.',
    prompt: 'uyanmak:\nkalkmak:\nkahvaltı:\nokul:\nöğle:\nödev:\nakşam:\nyatak:',
    hint: '`Dann` ve `Danach` ile bağla; saatleri `um` ile söyle.',
    answer: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Ich frühstücke. Dann gehe ich zur Schule. Ich esse zu Mittag. Ich mache meine Hausaufgaben. Ich esse um neun Uhr Abendessen. Danach gehe ich ins Bett.',
    explanation: 'Orta model: sekiz cümle, bağlaçlar ve saatlerle.',
    pronounce: ['Dann gehe ich zur Schule. Danach gehe ich ins Bett.'],
  },
  {
    id: 'p10-meintag-free-tam-anlatim',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [
      'daily-routine.tam.uretim',
      'daily-routine.tam.model',
      'daily-routine.tam.sablon',
      'daily-routine.gun.hausaufgaben',
      'daily-routine.aksam.bett',
    ],
    familyId: 'p10-tam-anlatim',
    openEnded: true,
    instruction: 'Gününü Almanca anlat (Erzähle deinen Tag.). En az on iki cümle yaz — ipuçları aşağıda.',
    prompt: 'Aufstehen:\nFrühstück:\nSchule:\nMittagessen:\nNach Hause:\nHausaufgaben:\nFreunde:\nAbendessen:\nBett:',
    hint: 'Kopya iskelet: `Ich stehe um ... Uhr auf. Dann ... Danach ... Ich gehe ... Ich komme ... Ich mache ... Ich esse ... Am Abend ... Danach gehe ich ins Bett.`',
    answer: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Ich wasche mein Gesicht. Ich putze meine Zähne. Ich dusche. Ich ziehe mich an. Ich frühstücke. Dann gehe ich zur Schule. Ich lerne Deutsch und Mathe in der Schule. Ich esse zu Mittag. Danach komme ich nach Hause zurück. Ich mache meine Hausaufgaben. Dann spiele ich mit meinen Freunden. Ich esse um neun Uhr Abendessen. Ich ziehe mich aus. Danach gehe ich ins Bett.',
    explanation: 'Kanonik A1 model: 16 kısa cümle, ayrılabilen fiiller + `dann/danach` + `um` saatleri.',
    pronounce: ['Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Dann gehe ich zur Schule.'],
  },
  {
    id: 'p10-tam-spoken-tam',
    topicId: T.dailyRoutine, legacyDay: 10,
    type: 'spoken', difficulty: 'hard', skill: 'speaking',
    conceptIds: ['daily-routine.tam.uretim', 'daily-routine.tam.model', 'time.um.ornek'],
    familyId: 'p10-tam-spoken',
    instruction: 'İpuçlarına bakmadan gününü baştan sona sesli anlat.',
    requirements: [
      'En az on iki cümle kur.',
      'En az beş ayrılabilen fiil kullan.',
      'Saatleri `um` ile söyle, cümleleri `dann/danach` ile bağla.',
    ],
    sampleAnswer: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Ich wasche mein Gesicht. Ich putze meine Zähne. Ich dusche. Ich ziehe mich an. Ich frühstücke. Dann gehe ich zur Schule. Ich esse zu Mittag. Danach komme ich nach Hause zurück. Ich mache meine Hausaufgaben. Ich esse um neun Uhr Abendessen. Ich ziehe mich aus. Danach gehe ich ins Bett.',
    audio: { targets: [{ text: 'Ich wache um sieben Uhr auf. Ich stehe um sieben Uhr auf. Dann gehe ich zur Schule. Danach komme ich nach Hause zurück.', language: 'de-DE', role: 'example' }] },
  },

  /* ---- Yarın ne yapmak istiyorsun? — Mein Tag + Modalverben ---- */
  {
    id: 'mt-plan-um-sieben-tr',
    topicId: T.dailyRoutine,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['daily-routine.plans', 'modal-verbs.trennbar', 'time.um.kural'],
    familyId: 'mt-plan-um-sieben',
    instruction: 'Türkçeden Almancaya çevir (wollen):',
    prompt: 'Saat yedide kalkmak istiyorum.',
    answer: 'Ich will um sieben Uhr aufstehen.',
    acceptedAnswers: ['Um sieben Uhr will ich aufstehen.'],
    explanation: 'Saat + Modalverb + ayrılabilen fiil: `will` ikinci sırada, `aufstehen` bölünmeden en sonda.',
    pronounce: ['Ich will um sieben Uhr aufstehen.'],
  },
  {
    id: 'mt-plan-freunde-order',
    topicId: T.dailyRoutine,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['daily-routine.plans', 'sentence-building.dann.danach', 'modal-verbs.moechten.kullanim'],
    familyId: 'mt-plan-freunde',
    instruction: 'Kelimeleri doğru sıraya diz — Sonra arkadaşlarımla buluşmak istiyorum.',
    prompt: 'Sonra arkadaşlarımla buluşmak istiyorum. (Danach …)',
    answer: 'Danach möchte ich meine Freunde treffen.',
    pronounce: ['Danach möchte ich meine Freunde treffen.'],
  },
  {
    id: 'mt-plan-free',
    topicId: T.dailyRoutine,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['daily-routine.plans', 'modal-verbs.wollen.kullanim', 'modal-verbs.sollen.kullanim'],
    familyId: 'mt-plan-free',
    instruction: 'Yarınki gününü 4 cümleyle planla (`will`, `möchte`, `soll` kullan).',
    prompt: '4 cümle: kalkış saati, bir görev, bir istek, akşam planı.',
    answer: 'Ich will um sieben Uhr aufstehen. Ich soll meine Hausaufgaben machen. Ich möchte meine Schwester anrufen. Am Abend möchte ich fernsehen.',
    validation: { keyboardTolerance: true },
    openEnded: true,
    hint: 'Ayrılabilen fiil Modalverb ile bölünmez: `Ich will … aufstehen.`',
    sampleAnswer: 'Ich will um sieben Uhr aufstehen. Ich soll meine Hausaufgaben machen. Ich möchte meine Schwester anrufen. Am Abend möchte ich fernsehen.',
    explanation: 'Model cevapla karşılaştır. Farklı ama doğru cümlelerin varsa “yine de doğruydu” diyebilirsin.',
  },
];
