/**
 * Essen und Trinken — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const FOOD_EXERCISES: AuthoredExercise[] = [
  /* ---- Essen und Trinken — gern / nicht gern (11) ---- */
  {
    id: 'p7-ess-frage-mc',
    topicId: T.food, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.essen.frage'],
    familyId: 'p7-ess-frage',
    instruction: '"Was isst du gern?" ne demektir?',
    prompt: 'Was isst du gern?',
    answer: 'Ne yemeyi seversin?',
    options: ['Ne yemeyi seversin?', 'Ne içmeyi seversin?', 'Ne kadar yiyorsun?', 'Nerede yiyorsun?'],
    pronounce: ['Was isst du gern?'],
  },
  {
    id: 'p7-ess-sie-form-fill',
    topicId: T.food, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['food.essen.frage'],
    familyId: 'p7-ess-sie-form',
    instruction: 'Soruyu resmî (Sie) hâle çevir:',
    prompt: 'Was isst du gern? → Was ___ Sie gern?',
    answer: 'essen',
    pronounce: ['Was essen Sie gern?'],
  },
  {
    id: 'p7-ess-antwort-wb',
    topicId: T.food, legacyDay: 7,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['food.essen.antwort', 'food.essen.kelimeler'],
    familyId: 'p7-ess-antwort',
    instruction: 'Türkçeden Almancaya kur — Patates kızartması yemeyi severim.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Patates kızartması yemeyi severim.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'esse' }, { id: 't3', text: 'gern' }, { id: 't4', text: 'Pommes.' },
        { id: 't5', text: 'trinke' }, { id: 't6', text: 'nicht' },
      ],
      acceptedSequences: [['Ich', 'esse', 'gern', 'Pommes.']],
    },
    answer: 'Ich esse gern Pommes.',
    pronounce: ['Ich esse gern Pommes.'],
  },
  {
    id: 'p7-ess-nicht-gern-tr-de',
    topicId: T.food, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['food.essen.nicht-gern'],
    familyId: 'p7-ess-nicht-gern',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Pizza yemeyi sevmiyorum. → ______',
    answer: 'Ich esse nicht gern Pizza.',
    pronounce: ['Ich esse nicht gern Pizza.'],
  },
  {
    id: 'p7-ess-lieblingsessen-fill',
    topicId: T.food, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['food.essen.lieblingsessen'],
    familyId: 'p7-ess-lieblingsessen',
    instruction: 'Soruyu tamamla:',
    prompt: 'Was ist dein ___? (En sevdiğin yemek nedir?)',
    answer: 'Lieblingsessen',
    pronounce: ['Was ist dein Lieblingsessen?'],
  },
  {
    id: 'p7-ess-lieblingsessen-antwort',
    topicId: T.food, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['food.essen.lieblingsessen', 'food.essen.kelimeler'],
    familyId: 'p7-ess-lieblingsessen-antwort',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'En sevdiğim yemek pilav. → ______',
    answer: 'Mein Lieblingsessen ist Reis.',
    pronounce: ['Mein Lieblingsessen ist Reis.'],
  },
  {
    id: 'p7-ess-trinken-frage-fill',
    topicId: T.food, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['food.trinken.frage'],
    familyId: 'p7-ess-trinken-frage',
    instruction: 'Soruyu tamamla:',
    prompt: 'Was ___ du gern? (Ne içmeyi seversin?)',
    answer: 'trinkst',
    pronounce: ['Was trinkst du gern?'],
  },
  {
    id: 'p7-ess-trinken-antwort-tr-de',
    topicId: T.food, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['food.trinken.frage', 'food.getraenke.kelimeler'],
    familyId: 'p7-ess-trinken-antwort',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Portakal suyu içmeyi severim. → ______',
    answer: 'Ich trinke gern Orangensaft.',
    pronounce: ['Ich trinke gern Orangensaft.'],
  },
  {
    id: 'p7-ess-lieblingsgetraenk-tr-de',
    topicId: T.food, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['food.trinken.lieblingsgetraenk', 'food.getraenke.kelimeler'],
    familyId: 'p7-ess-lieblingsgetraenk',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'En sevdiğim içecek elma suyu. → ______',
    answer: 'Mein Lieblingsgetränk ist Apfelsaft.',
    validation: { keyboardTolerance: true },
    pronounce: ['Mein Lieblingsgetränk ist Apfelsaft.'],
  },
  {
    id: 'p7-ess-hunger-durst-match',
    topicId: T.food, legacyDay: 7,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.essen.hunger-durst'],
    familyId: 'p7-ess-hunger-durst',
    instruction: 'Kalıbı Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'Ich habe Hunger.', right: 'Acıktım.' },
      { left: 'Ich habe Durst.', right: 'Susadım.' },
    ],
    pronounce: ['Ich habe Hunger.', 'Ich habe Durst.'],
  },
  {
    id: 'p7-ess-dialog-spoken',
    topicId: T.food, legacyDay: 7,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['food.essen.frage', 'food.trinken.frage'],
    familyId: 'p7-ess-dialog',
    instruction: 'Mini diyaloğu sesli tamamla — kendi cevabını ver.',
    prompt: 'A: Was isst du gern?\nB: ...\nA: Was trinkst du gern?\nB: ...',
    requirements: [
      '`Ich esse gern ...` kalıbıyla cevap ver.',
      '`Ich trinke gern ...` kalıbıyla cevap ver.',
      'Sevmediğin bir şeyi `nicht gern` ile söyle.',
    ],
    sampleAnswer: 'Ich esse gern Pommes. Ich trinke gern Orangensaft. Ich trinke nicht gern Kaffee.',
    audio: { targets: [{ text: 'Ich esse gern Pommes. Ich trinke gern Orangensaft. Ich trinke nicht gern Kaffee.', language: 'de-DE', role: 'example' }] },
  },

  /* ---- Yiyecek ve Mutfak Kelimeleri (11) ---- */
  {
    id: 'p5-yem-ei-mc',
    topicId: T.food, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-ei',
    instruction: '"das Ei" ne demektir?',
    prompt: 'das Ei',
    answer: 'yumurta',
    options: ['yumurta', 'un', 'ekmek', 'kek'],
    pronounce: ['das Ei'],
  },
  {
    id: 'p5-yem-mehl-mc',
    topicId: T.food, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-mehl',
    instruction: '"das Mehl" ne demektir?',
    prompt: 'das Mehl',
    answer: 'un',
    options: ['un', 'yumurta', 'armut', 'meyve suyu'],
    pronounce: ['das Mehl'],
  },
  {
    id: 'p5-yem-pfannkuchen-mc',
    topicId: T.food, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-pfannkuchen',
    instruction: '"der Pfannkuchen" ne demektir?',
    prompt: 'der Pfannkuchen',
    answer: 'krep / gözleme (pankek)',
    options: ['krep / gözleme (pankek)', 'kek', 'ekmek', 'armut'],
    pronounce: ['der Pfannkuchen'],
  },
  {
    id: 'p5-yem-kuchen-fill',
    topicId: T.food, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-kuchen',
    instruction: 'Boşluğu doldur (der Kuchen — kek çok lezzetli):',
    prompt: '___ Kuchen ist sehr lecker.',
    answer: 'Der',
    pronounce: ['Der Kuchen ist sehr lecker.'],
  },
  {
    id: 'p5-yem-broetchen-mc',
    topicId: T.food, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-broetchen',
    instruction: '"das Brötchen" ne demektir?',
    prompt: 'das Brötchen',
    answer: 'küçük ekmek / sandviç ekmeği',
    options: ['küçük ekmek / sandviç ekmeği', 'büyük ekmek', 'kek', 'pankek'],
    pronounce: ['das Brötchen'],
  },
  {
    id: 'p5-yem-birne-fill',
    topicId: T.food, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-birne',
    instruction: 'Boşluğu doldur (armut):',
    prompt: 'die ___ = armut',
    answer: 'Birne',
    pronounce: ['die Birne'],
  },
  {
    id: 'p5-yem-saft-fill',
    topicId: T.food, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-saft',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich möchte einen ___, bitte. (Bir meyve suyu istiyorum.)',
    answer: 'Saft',
    pronounce: ['Ich möchte einen Saft, bitte.'],
  },
  {
    id: 'p5-yem-matching',
    topicId: T.food, legacyDay: 5,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-matching',
    instruction: 'Yiyecek kelimelerini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'das Ei', right: 'yumurta' },
      { left: 'das Mehl', right: 'un' },
      { left: 'der Pfannkuchen', right: 'krep / gözleme' },
      { left: 'der Kuchen', right: 'kek / pasta' },
      { left: 'das Brötchen', right: 'küçük ekmek' },
      { left: 'die Birne', right: 'armut' },
      { left: 'der Saft', right: 'meyve suyu' },
    ],
    pronounce: ['das Ei', 'das Mehl', 'der Pfannkuchen', 'der Kuchen', 'das Brötchen', 'die Birne', 'der Saft'],
  },
  {
    id: 'p5-yem-artikel-mc',
    topicId: T.food, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-artikel',
    instruction: '___ Ei, ___ Saft, ___ Birne — doğru artikel sırası hangisidir?',
    prompt: '___ Ei, ___ Saft, ___ Birne',
    answer: 'das, der, die',
    options: ['das, der, die', 'der, das, die', 'die, der, das', 'das, die, der'],
  },
  {
    id: 'p5-yem-listen',
    topicId: T.food, legacyDay: 5,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-listen',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich esse ein Ei zum Frühstück.',
    audioText: 'Ich esse ein Ei zum Frühstück.',
    answer: 'Ich esse ein Ei zum Frühstück.',
    options: [
      'Ich esse ein Ei zum Frühstück.',
      'Ich esse einen Kuchen.',
      'Ich trinke einen Saft.',
      'Ich möchte ein Brötchen.',
    ],
    audio: { prompt: { text: 'Ich esse ein Ei zum Frühstück.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-yem-wb-saft-tr-de',
    topicId: T.food, legacyDay: 5,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['food.yiyecek.kelimeler'],
    familyId: 'p5-yem-wb-saft',
    instruction: 'Türkçeden Almancaya kur — Bir meyve suyu istiyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Bir meyve suyu istiyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'möchte' }, { id: 't3', text: 'einen' }, { id: 't4', text: 'Saft.' },
        { id: 't5', text: 'Birne.' },
      ],
      acceptedSequences: [['Ich', 'möchte', 'einen', 'Saft.']],
    },
    answer: 'Ich möchte einen Saft.',
    pronounce: ['Ich möchte einen Saft.'],
  },

  /* ---- Diğer Yiyecek Kelimeleri (9) ---- */
  {
    id: 'p7-yiy-temel-match',
    topicId: T.food, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['food.yiyecek.temel', 'food.yiyecek.zwiebel'],
    familyId: 'p7-yiy-temel-match',
    instruction: 'Yiyeceği Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'das Fleisch', right: 'et' },
      { left: 'der Wein', right: 'şarap' },
      { left: 'das Obst', right: 'meyve' },
      { left: 'das Gemüse', right: 'sebze' },
      { left: 'die Zwiebel', right: 'soğan' },
    ],
    pronounce: ['das Fleisch', 'der Wein', 'das Obst', 'das Gemüse', 'die Zwiebel'],
  },
  {
    id: 'p7-yiy-gurke-match',
    topicId: T.food, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['food.yiyecek.gurke', 'food.yiyecek.essig', 'food.yiyecek.oel-pfeffer'],
    familyId: 'p7-yiy-gurke-match',
    instruction: 'Salata ve baharat kelimelerini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'die Salatgurke', right: 'salatalık' },
      { left: 'saure Gurken', right: 'turşu' },
      { left: 'der Essig', right: 'sirke' },
      { left: 'das Öl', right: 'yağ' },
      { left: 'der Pfeffer', right: 'kara biber' },
    ],
    pronounce: ['die Salatgurke', 'saure Gurken', 'der Essig', 'das Öl', 'der Pfeffer'],
  },
  {
    id: 'p7-yiy-nuesse-match',
    topicId: T.food, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['food.yiyecek.nuesse', 'food.yiyecek.haehnchen'],
    familyId: 'p7-yiy-nuesse-match',
    instruction: 'Kuruyemiş, tatlı ve et kelimelerini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'die Nüsse', right: 'kuruyemiş' },
      { left: 'die Rosinen', right: 'kuru üzüm' },
      { left: 'der Staubzucker', right: 'pudra şekeri' },
      { left: 'das Hähnchen', right: 'tavuk' },
    ],
    pronounce: ['die Nüsse', 'die Rosinen', 'der Staubzucker', 'das Hähnchen'],
  },
  {
    id: 'p7-yiy-zwiebel-artikel',
    topicId: T.food, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['food.yiyecek.zwiebel'],
    familyId: 'p7-yiy-zwiebel',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Zwiebel (soğan)',
    answer: 'die',
    validation: { noTypoTolerance: true },
    pronounce: ['die Zwiebel'],
  },
  {
    id: 'p7-yiy-oel-artikel',
    topicId: T.food, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['food.yiyecek.oel-pfeffer'],
    familyId: 'p7-yiy-oel',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Öl (yağ)',
    answer: 'das',
    validation: { noTypoTolerance: true },
    pronounce: ['das Öl'],
  },
  {
    id: 'p7-yiy-knoblauch-mc',
    topicId: T.food, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['food.yiyecek.zwiebel'],
    familyId: 'p7-yiy-knoblauch',
    instruction: '"die Knoblauchzehe" ne demektir?',
    prompt: 'die Knoblauchzehe',
    answer: 'sarımsak dişi',
    options: ['sarımsak dişi', 'soğan halkası', 'taze soğan', 'salatalık'],
    pronounce: ['die Knoblauchzehe'],
  },
  {
    id: 'p7-yiy-kaese-mc',
    topicId: T.food, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.yiyecek.sahne'],
    familyId: 'p7-yiy-kaese',
    instruction: '"der Käse" ne demektir?',
    prompt: 'der Käse',
    answer: 'peynir',
    options: ['peynir', 'krema', 'süt', 'tereyağı'],
    pronounce: ['der Käse'],
  },
  {
    id: 'p7-yiy-listen-gemuese',
    topicId: T.food, legacyDay: 7,
    type: 'listen-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['food.yiyecek.temel'],
    familyId: 'p7-yiy-listen-gemuese',
    instruction: 'Duyduğun kelimeyi seç:',
    prompt: 'das Gemüse',
    audioText: 'das Gemüse',
    answer: 'das Gemüse',
    options: ['das Gemüse', 'das Obst', 'das Fleisch', 'der Käse'],
    audio: { prompt: { text: 'das Gemüse', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p7-yiy-dictation-haehnchen',
    topicId: T.food, legacyDay: 7,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['food.yiyecek.haehnchen'],
    familyId: 'p7-yiy-dictation',
    instruction: 'Duyduğun kelimeyi artikeliyle birlikte yaz:',
    audioText: 'das Hähnchen',
    answer: 'das Hähnchen',
    validation: { keyboardTolerance: true },
    audio: { prompt: { text: 'das Hähnchen', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Sofrada: die Suppe, der Teller, die Lebensmittel ---- */
  {
    id: 'food-suppe-artikel-mc',
    topicId: T.food,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.suppe-teller'],
    familyId: 'food-suppe',
    instruction: 'Doğru artikeli seç — çorba:',
    prompt: 'Suppe',
    answer: 'die',
    options: ['der', 'die', 'das'],
    pronounce: ['die Suppe'],
  },
  {
    id: 'food-teller-artikel-fill',
    topicId: T.food,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['food.suppe-teller'],
    familyId: 'food-teller',
    instruction: 'Artikeli yaz — tabak:',
    prompt: '___ Teller',
    answer: 'der',
    validation: { noTypoTolerance: true },
    pronounce: ['der Teller'],
  },
  {
    id: 'food-suppe-essen-tr',
    topicId: T.food,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['food.suppe-teller', 'verbs.verben.essen'],
    familyId: 'food-suppe-essen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bir çorba içiyorum.',
    answer: 'Ich esse eine Suppe.',
    explanation: 'Türkçede çorba "içilir", Almancada "yenir": `Ich esse eine Suppe.`',
    pronounce: ['Ich esse eine Suppe.'],
  },
  {
    id: 'food-lebensmittel-mc',
    topicId: T.food,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.lebensmittel'],
    familyId: 'food-lebensmittel',
    instruction: 'Anlamını seç:',
    prompt: 'die Lebensmittel',
    answer: 'gıda, yiyecekler',
    options: ['gıda, yiyecekler', 'mutfak eşyaları', 'ilaçlar', 'içecekler'],
    pronounce: ['die Lebensmittel'],
  },
  {
    id: 'food-suppe-heiss-listen',
    topicId: T.food,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['food.suppe-teller'],
    familyId: 'food-suppe-heiss',
    instruction: 'Duyduğun cümleyi seç:',
    prompt: 'Die Suppe ist heiß.',
    audioText: 'Die Suppe ist heiß.',
    answer: 'Die Suppe ist heiß.',
    options: ['Die Suppe ist heiß.', 'Die Suppe ist kalt.', 'Der Teller ist heiß.', 'Die Suppe ist groß.'],
    audio: { prompt: { text: 'Die Suppe ist heiß.', language: 'de-DE', role: 'prompt' } },
  },
];
