/**
 * Selamlaşma ve Tanışma — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const GREETINGS_EXERCISES: AuthoredExercise[] = [
  /* ---- Selamlaşma, Nezaket ve Diller (6) ---- */
  {
    id: 'p1-diller-welche-mc',
    topicId: T.greetings, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['greetings.sprachen.welche'],
    familyId: 'p1-sprachen-welche',
    instruction: 'Soru ne anlama gelir?',
    prompt: 'Welche Sprachen sprichst du?',
    answer: 'Hangi dilleri konuşuyorsun?',
    options: ['Hangi dilleri konuşuyorsun?', 'Nerelisin?', 'Kaç yaşındasın?', 'Ne iş yapıyorsun?'],
    pronounce: ['Welche Sprachen sprichst du?'],
  },
  {
    id: 'p1-selam-hallo-mc',
    topicId: T.greetings, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['greetings.selamlasma.hallo'],
    familyId: 'p1-selam-hallo',
    instruction: 'Günün her saatinde kullanabileceğin selam:',
    prompt: 'Hallo! / Hi!',
    answer: 'Merhaba! / Selam!',
    options: ['Merhaba! / Selam!', 'Günaydın!', 'İyi akşamlar!', 'İyi geceler!'],
    pronounce: ['Hallo!'],
  },
  {
    id: 'p1-wb-sprachen-tr-de',
    topicId: T.greetings, legacyDay: 1,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['greetings.sprachen.welche'],
    familyId: 'p1-sprachen-welche',
    instruction: 'Türkçeden Almancaya kur — Hangi dilleri konuşuyorsun?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Hangi dilleri konuşuyorsun?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Welche' }, { id: 't2', text: 'Sprachen' }, { id: 't3', text: 'sprichst' }, { id: 't4', text: 'du?' },
        { id: 't5', text: 'Wie' }, { id: 't6', text: 'heißt' },
      ],
      acceptedSequences: [['Welche', 'Sprachen', 'sprichst', 'du?']],
    },
    answer: 'Welche Sprachen sprichst du?',
    pronounce: ['Welche Sprachen sprichst du?'],
  },
  {
    id: 'p1-wb-ich-spreche-de-tr',
    topicId: T.greetings, legacyDay: 1,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['greetings.sprachen.antwort'],
    familyId: 'p1-sprachen-antwort',
    instruction: 'Almancadan Türkçeye çevir — İngilizce konuşuyorum',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Ich spreche Englisch.',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'İngilizce' }, { id: 't2', text: 'konuşuyorum.' }, { id: 't3', text: 'yaşıyorum.' },
      ],
      acceptedSequences: [['İngilizce', 'konuşuyorum.']],
    },
    answer: 'İngilizce konuşuyorum.',
    audio: { prompt: { text: 'Ich spreche Englisch.', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Ich spreche Englisch.'],
  },
  {
    id: 'p1-dictation-sprachen',
    topicId: T.greetings, legacyDay: 1,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['greetings.sprachen.welche'],
    familyId: 'p1-sprachen-welche',
    instruction: 'Dil sorusunu duydun — aynen yaz:',
    audioText: 'Welche Sprachen sprichst du?',
    answer: 'Welche Sprachen sprichst du?',
    audio: { prompt: { text: 'Welche Sprachen sprichst du?', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p1-nezakaet-entschuldigung-mc',
    topicId: T.greetings, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['greetings.nezaket.entschuldigung'],
    familyId: 'p1-nezakaet',
    instruction: 'Nezaket kalıbı nedir?',
    prompt: 'Entschuldigung',
    answer: 'Affedersiniz / Pardon',
    options: ['Affedersiniz / Pardon', 'Teşekkürler', 'Merhaba', 'Güle güle'],
    pronounce: ['Entschuldigung'],
  },

  /* ---- İsim Sorma ve Tanışma (18) ---- */
  {
    id: 'p1-vor-wie-heisst-mc',
    topicId: T.greetings, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['greetings.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Doğru soruyu seç — samimi hitap:',
    prompt: 'Arkadaşına adını soruyorsun.',
    answer: 'Wie heißt du?',
    options: ['Wie heißt du?', 'Wie heißen Sie?', 'Wer bist du?', 'Wo wohnst du?'],
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'p1-vor-wie-heissen-sie-mc',
    topicId: T.greetings, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['greetings.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Doğru soruyu seç — resmî hitap:',
    prompt: 'Öğretmenine adını soruyorsun.',
    answer: 'Wie heißen Sie?',
    options: ['Wie heißt du?', 'Wie heißen Sie?', 'Wie ist dein Name?', 'Wer bist du?'],
    pronounce: ['Wie heißen Sie?'],
  },
  {
    id: 'p1-vor-wer-bist-du-mc',
    topicId: T.greetings, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['greetings.vorstellung.wer-bist-du'],
    familyId: 'p1-vor-wer',
    instruction: 'Bu sorunun Türkçesi nedir?',
    prompt: 'Wer bist du?',
    answer: 'Sen kimsin? / Adın ne?',
    options: ['Sen kimsin? / Adın ne?', 'Nerede yaşıyorsun?', 'Nerelisin?', 'Kaç yaşındasın?'],
    pronounce: ['Wer bist du?'],
  },
  {
    id: 'p1-vor-freut-mich-mc',
    topicId: T.greetings, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['greetings.vorstellung.freut-mich'],
    familyId: 'p1-vor-freut',
    instruction: 'Tanışırken söylenir:',
    prompt: 'Freut mich!',
    answer: 'Memnun oldum!',
    options: ['Memnun oldum!', 'Teşekkürler!', 'Pardon!', 'Güle güle!'],
    pronounce: ['Freut mich!'],
  },
  {
    id: 'p1-vor-heisse-fill',
    topicId: T.greetings, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['greetings.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Boşluğu doldur:',
    prompt: 'Wie _____ du? (heißen)',
    answer: 'heißt',
    validation: { keyboardTolerance: true },
    hint: 'samimi soru, du ile.',
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'p1-vor-heissen-sie-fill',
    topicId: T.greetings, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['greetings.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Resmî soruyu tamamla — fiili doğru çek:',
    prompt: 'Wie _____ Sie?',
    answer: 'heißen',
    validation: { keyboardTolerance: true },
    hint: 'Sie/sie çekimi düzenli fiillerde her zaman mastarla aynıdır.',
    pronounce: ['Wie heißen Sie?'],
  },
  {
    id: 'p1-vor-name-fill',
    topicId: T.greetings, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['greetings.vorstellung.wie-ist-dein-name'],
    familyId: 'p1-vor-name',
    instruction: 'Boşluğu doldur — samimi iyelik zamiri:',
    prompt: 'Wie ist _____ Name?',
    answer: 'dein',
    hint: 'senin (samimi hitap)',
    pronounce: ['Wie ist dein Name?'],
  },
  {
    id: 'p1-vor-wer-bist-fill',
    topicId: T.greetings, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['greetings.vorstellung.wer-bist-du'],
    familyId: 'p1-vor-wer',
    instruction: 'Boşluğu doldur:',
    prompt: 'Wer _____ du? (sein)',
    answer: 'bist',
    pronounce: ['Wer bist du?'],
  },
  {
    id: 'p1-vor-ich-heisse-fill',
    topicId: T.greetings, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['verbs.verben.heissen', 'greetings.vorstellung.wie-heisst-du'],
    familyId: 'p1-verb-heissen',
    instruction: 'Kendini tanıt:',
    prompt: 'Ich _____ Mustafa. (heißen)',
    answer: 'heiße',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich heiße Mustafa.'],
  },
  {
    id: 'p1-vorstellung-matching',
    topicId: T.greetings, legacyDay: 1,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['greetings.vorstellung.wie-heisst-du', 'greetings.vorstellung.wie-ist-dein-name', 'greetings.vorstellung.wer-bist-du'],
    familyId: 'p1-vor-match',
    instruction: 'Soruları Türkçesiyle eşleştir.',
    pairs: [
      { left: 'Wie heißt du?', right: 'Adın ne?' },
      { left: 'Wie alt bist du?', right: 'Kaç yaşındasın?' },
      { left: 'Wo wohnst du?', right: 'Nerede yaşıyorsun?' },
    ],
    pronounce: ['Wie heißt du?', 'Wie alt bist du?', 'Wo wohnst du?'],
  },
  {
    id: 'p1-du-sie-convert-name',
    topicId: T.greetings, legacyDay: 1,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['greetings.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Samimi soruyu resmî hâle çevir:',
    prompt: 'Wie heißt du? → ______',
    answer: 'Wie heißen Sie?',
    validation: { keyboardTolerance: true },
    hint: 'Fiil de değişir.',
    pronounce: ['Wie heißen Sie?'],
  },
  {
    id: 'p1-self-intro-builder',
    topicId: T.greetings, legacyDay: 1,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['greetings.vorstellung.wie-heisst-du', 'personal-info.alter.wie-alt', 'personal-info.herkunft.aus'],
    familyId: 'p1-self-intro',
    instruction: 'Kendini tanıt — kelimeleri doğru sıraya koy:',
    prompt: 'Mustafa / heiße / ich / achtzehn / bin / Jahre / alt',
    answer: 'Ich heiße Mustafa und bin achtzehn Jahre alt.',
    words: ['Ich', 'heiße', 'Mustafa', 'und', 'bin', 'achtzehn', 'Jahre', 'alt'],
    pronounce: ['Ich heiße Mustafa.'],
    explanation: 'İsim + yaş birleştirme.',
  },
  {
    id: 'p1-vorstellung-dialog-free',
    topicId: T.greetings, legacyDay: 1,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['greetings.vorstellung.freut-mich', 'greetings.vorstellung.sich-vorstellen'],
    familyId: 'p1-vor-freut',
    instruction: 'Mini diyalog: B ne demeli? Kendini tanıt ve memnuniyet belirt.',
    prompt: 'A: Wie heißt du?\nB: ______',
    answer: 'Ich heiße Mustafa. Freut mich!',
    acceptedAnswers: ['Ich heiße Mustafa.', 'Mein Name ist Mustafa. Freut mich!', 'Ich bin Mustafa. Freut mich!'],
    openEnded: true,
    validation: { keyboardTolerance: true },
    pronounce: ['Ich heiße Mustafa.', 'Freut mich!'],
  },
  {
    id: 'p1-wb-name-de-tr',
    topicId: T.greetings, legacyDay: 1,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['greetings.vorstellung.wie-heisst-du'],
    familyId: 'p1-vor-heisst',
    instruction: 'Türkçeden Almancaya kur — Adın ne?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Adın ne?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Wie' }, { id: 't2', text: 'heißt' }, { id: 't3', text: 'du?' },
        { id: 't4', text: 'Wo' }, { id: 't5', text: 'bist' }, { id: 't6', text: 'Sie?' },
      ],
      acceptedSequences: [['Wie', 'heißt', 'du?']],
    },
    answer: 'Wie heißt du?',
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'p1-listen-wie-heisst-du',
    topicId: T.greetings, legacyDay: 1,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['greetings.vorstellung.wie-heisst-du'],
    familyId: 'p1-listen-heisst',
    instruction: 'Duyduğunu seç:',
    prompt: 'Wie heißt du?',
    audioText: 'Wie heißt du?',
    answer: 'Wie heißt du?',
    options: ['Wie heißt du?', 'Wie alt bist du?', 'Wo wohnst du?', 'Woher kommst du?'],
    audio: { prompt: { text: 'Wie heißt du?', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p1-spoken-vorstellung',
    topicId: T.greetings, legacyDay: 1,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['greetings.vorstellung.wie-heisst-du', 'greetings.vorstellung.freut-mich'],
    familyId: 'p1-spoken-vor',
    instruction: 'Sesli görev: kendini tanıt ve memnuniyet belirt.',
    requirements: ['Ich heiße ...', 'Freut mich!'],
    sampleAnswer: 'Ich heiße Mustafa. Freut mich!',
    pronounce: ['Ich heiße Mustafa.', 'Freut mich!'],
  },
  {
    id: 'p1-extra-vorstellung-sie-free',
    topicId: T.greetings, legacyDay: 1,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['greetings.vorstellung.wie-ist-dein-name'],
    familyId: 'p1-vor-name',
    instruction: 'Resmî soruyu yaz:',
    prompt: 'Adınız ne?',
    answer: 'Wie ist Ihr Name?',
    pronounce: ['Wie ist Ihr Name?'],
  },
  {
    id: 'p1-extra-antwort-freut-free',
    topicId: T.greetings, legacyDay: 1,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['greetings.vorstellung.freut-mich'],
    familyId: 'p1-vor-freut',
    instruction: 'Tanışırken ne dersin?',
    prompt: 'Memnun oldum! → ______',
    answer: 'Freut mich!',
    acceptedAnswers: ['Ich habe mich gefreut!'],
    pronounce: ['Freut mich!'],
  },

  /* ---- Nasılsın? — Es geht mir gut (2) ---- */
  {
    id: 'p3-gh-es-geht-mir-mc',
    topicId: T.greetings, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['greetings.es-geht-mir'],
    familyId: 'p3-gh-es-geht-mir',
    instruction: '"Es geht mir gut" ne demektir?',
    prompt: 'Es geht mir gut',
    answer: 'iyiyim',
    options: ['iyiyim', 'kötüyüm', 'yorgunum', 'mutluyum'],
    pronounce: ['Es geht mir gut'],
  },
  {
    id: 'p3-gh-free-mude-tr',
    topicId: T.greetings, legacyDay: 3,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['greetings.es-geht-mir'],
    familyId: 'p3-gh-mude',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Biraz yorgunum ama iyiyim. → ______',
    answer: 'Ich bin ein bisschen müde, aber es geht mir gut.',
    pronounce: ['Ich bin ein bisschen müde, aber es geht mir gut.'],
  },
];
