/**
 * Ev ve Mobilyalar — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const HOME_EXERCISES: AuthoredExercise[] = [
  /* ---- Ev ve Odalar (17) ---- */
  {
    id: 'p3-gh-wohnung-mc',
    topicId: T.home, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.ev-kelime'],
    familyId: 'p3-gh-wohnung',
    instruction: '"ev / daire" Almancada hangisi?',
    prompt: 'ev / daire',
    answer: 'die Wohnung',
    options: ['die Wohnung', 'das Zimmer', 'der Garten', 'der Balkon'],
    pronounce: ['die Wohnung'],
  },
  {
    id: 'p3-gh-kueche-fill',
    topicId: T.home, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['home.ev-kelime'],
    familyId: 'p3-gh-kueche',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Mutter kocht in der ___. (mutfakta yemek yapıyor)',
    answer: 'Küche',
    pronounce: ['Meine Mutter kocht in der Küche.'],
  },
  {
    id: 'p3-gh-wohnzimmer-matching',
    topicId: T.home, legacyDay: 3,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.ev-kelime'],
    familyId: 'p3-gh-ev-match',
    instruction: 'Ev kelimelerini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'die Wohnung', right: 'ev / daire' },
      { left: 'das Zimmer', right: 'oda' },
      { left: 'der Balkon', right: 'balkon' },
      { left: 'das Wohnzimmer', right: 'salon' },
    ],
    pronounce: ['die Wohnung', 'das Zimmer', 'der Balkon', 'das Wohnzimmer'],
  },
  {
    id: 'p3-gh-wohne-istanbul-fill',
    topicId: T.home, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['home.ev-kelime'],
    familyId: 'p3-gh-wohne-istanbul',
    instruction: 'Boşluğu doldur (wohnen — tekrar):',
    prompt: 'Ich ___ in Istanbul. (İstanbul\'da yaşıyorum)',
    answer: 'wohne',
    pronounce: ['Ich wohne in Istanbul.'],
  },
  {
    id: 'p3-gh-vater-fernsehen-mc',
    topicId: T.home, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['home.ev-kelime'],
    familyId: 'p3-gh-vater-fernsehen',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Mein Vater schaut im Wohnzimmer Fernsehen.',
    answer: 'Babam salonda televizyon izliyor.',
    options: [
      'Babam salonda televizyon izliyor.',
      'Babam mutfakta yemek yapıyor.',
      'Babam bahçede oturuyor.',
      'Babam odasında ders çalışıyor.',
    ],
    pronounce: ['Mein Vater schaut im Wohnzimmer Fernsehen.'],
  },
  {
    id: 'p7-ev-match-odalar',
    topicId: T.home, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'home.ev.bad',
      'home.ev.schlafzimmer',
      'home.ev.flur',
      'home.ev.kueche',
      'home.ev.wohnzimmer',
    ],
    familyId: 'p7-ev-match',
    instruction: 'Oda adını Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'das Bad', right: 'banyo' },
      { left: 'das Schlafzimmer', right: 'yatak odası' },
      { left: 'der Flur', right: 'koridor' },
      { left: 'die Küche', right: 'mutfak' },
      { left: 'das Wohnzimmer', right: 'salon' },
    ],
    pronounce: ['das Bad', 'das Schlafzimmer', 'der Flur', 'die Küche', 'das Wohnzimmer'],
  },
  {
    id: 'p7-ev-kueche-artikel',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['home.ev.kueche'],
    familyId: 'p7-ev-kueche',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Küche (mutfak)',
    answer: 'die',
    validation: { noTypoTolerance: true },
    pronounce: ['die Küche'],
  },
  {
    id: 'p7-ev-flur-artikel',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['home.ev.flur'],
    familyId: 'p7-ev-flur',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Flur (koridor)',
    answer: 'der',
    validation: { noTypoTolerance: true },
    pronounce: ['der Flur'],
  },
  {
    id: 'p7-ev-schlafzimmer-artikel',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['home.ev.schlafzimmer'],
    familyId: 'p7-ev-schlafzimmer',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Schlafzimmer (yatak odası)',
    answer: 'das',
    validation: { noTypoTolerance: true },
    pronounce: ['das Schlafzimmer'],
  },
  {
    id: 'p7-ev-bad-mc',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.ev.bad'],
    familyId: 'p7-ev-bad',
    instruction: 'Hangisi "banyo" demektir?',
    prompt: 'banyo',
    answer: 'das Bad',
    options: ['das Bad', 'der Flur', 'das Regal', 'die Küche'],
    pronounce: ['das Bad'],
  },
  {
    id: 'p7-ev-wohnung-mc',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.ev.wohnung'],
    familyId: 'p7-ev-wohnung',
    instruction: '"die Wohnung" ne demektir?',
    prompt: 'die Wohnung',
    answer: 'ev, daire',
    options: ['ev, daire', 'koridor', 'mutfak', 'balkon'],
    pronounce: ['die Wohnung'],
  },
  {
    id: 'p7-ev-toilette-fill',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['home.ev.toilette'],
    familyId: 'p7-ev-toilette',
    instruction: 'Boşluğu doldur — "tuvalet" kelimesinin çoğulunu yaz:',
    prompt: 'Wir haben drei ___. (Üç tuvaletimiz var.)',
    answer: 'Toiletten',
    pronounce: ['Wir haben drei Toiletten.'],
  },
  {
    id: 'p7-ev-kochen-mc',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['home.ev.kueche'],
    familyId: 'p7-ev-kochen',
    instruction: 'Hangi odada yemek pişirirsin?',
    prompt: 'Hier koche ich.',
    answer: 'die Küche',
    options: ['die Küche', 'das Bad', 'der Flur', 'das Wohnzimmer'],
    pronounce: ['die Küche'],
  },
  {
    id: 'p7-ev-schlafen-mc',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['home.ev.schlafzimmer'],
    familyId: 'p7-ev-schlafen',
    instruction: 'Hangi oda "uyuduğun oda"dır?',
    prompt: 'yatak odası',
    answer: 'das Schlafzimmer',
    options: ['das Schlafzimmer', 'das Wohnzimmer', 'die Küche', 'das Bad'],
    pronounce: ['das Schlafzimmer'],
  },
  {
    id: 'p7-ev-listen-flur',
    topicId: T.home, legacyDay: 7,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.ev.flur'],
    familyId: 'p7-ev-listen-flur',
    instruction: 'Duyduğun kelimeyi seç:',
    prompt: 'der Flur',
    audioText: 'der Flur',
    answer: 'der Flur',
    options: ['der Flur', 'das Bad', 'die Küche', 'der Sessel'],
    audio: { prompt: { text: 'der Flur', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p7-ev-listen-wohnzimmer',
    topicId: T.home, legacyDay: 7,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.ev.wohnzimmer'],
    familyId: 'p7-ev-listen-wohnzimmer',
    instruction: 'Duyduğun oda adını seç:',
    prompt: 'das Wohnzimmer',
    audioText: 'das Wohnzimmer',
    answer: 'das Wohnzimmer',
    options: ['das Wohnzimmer', 'das Schlafzimmer', 'die Wohnung', 'das Waschbecken'],
    audio: { prompt: { text: 'das Wohnzimmer', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p7-ev-tr-de-kueche',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.ev.kueche', 'adjectives.tarif.hell'],
    familyId: 'p7-ev-tr-kueche',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Mutfak açık renkli. → ______',
    answer: 'Die Küche ist hell.',
    pronounce: ['Die Küche ist hell.'],
  },

  /* ---- Mobilyalar ve Ev Eşyaları (12) ---- */
  {
    id: 'p7-mob-match-1',
    topicId: T.home, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'home.moebel.schrank',
      'home.moebel.bett',
      'home.moebel.sofa',
      'home.moebel.sessel',
    ],
    familyId: 'p7-mob-match-1',
    instruction: 'Mobilyayı Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'der Schrank', right: 'dolap' },
      { left: 'das Bett', right: 'yatak' },
      { left: 'das Sofa', right: 'kanepe' },
      { left: 'der Sessel', right: 'koltuk' },
    ],
    pronounce: ['der Schrank', 'das Bett', 'das Sofa', 'der Sessel'],
  },
  {
    id: 'p7-mob-match-2',
    topicId: T.home, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'home.moebel.fernseher',
      'home.moebel.teppich-regal',
      'home.moebel.herd-bad',
    ],
    familyId: 'p7-mob-match-2',
    instruction: 'Ev eşyasını Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'der Fernseher', right: 'televizyon' },
      { left: 'der Teppich', right: 'halı' },
      { left: 'das Regal', right: 'raf' },
      { left: 'der Herd', right: 'ocak' },
      { left: 'die Badewanne', right: 'küvet' },
      { left: 'das Waschbecken', right: 'lavabo' },
    ],
    pronounce: ['der Fernseher', 'der Teppich', 'das Regal', 'der Herd', 'die Badewanne', 'das Waschbecken'],
  },
  {
    id: 'p7-mob-moebel-mc',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.moebel.genel'],
    familyId: 'p7-mob-moebel',
    instruction: '"die Möbel" ne demektir?',
    prompt: 'die Möbel',
    answer: 'mobilyalar',
    options: ['mobilyalar', 'odalar', 'komşular', 'misafirler'],
    pronounce: ['die Möbel'],
  },
  {
    id: 'p7-mob-schrank-artikel',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['home.moebel.schrank'],
    familyId: 'p7-mob-schrank',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Schrank (dolap)',
    answer: 'der',
    validation: { noTypoTolerance: true },
    pronounce: ['der Schrank'],
  },
  {
    id: 'p7-mob-regal-artikel',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['home.moebel.teppich-regal'],
    familyId: 'p7-mob-regal',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Regal (raf)',
    answer: 'das',
    validation: { noTypoTolerance: true },
    pronounce: ['das Regal'],
  },
  {
    id: 'p7-mob-sessel-artikel',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['home.moebel.sessel'],
    familyId: 'p7-mob-sessel',
    instruction: 'Doğru artikeli yaz:',
    prompt: '___ Sessel (koltuk)',
    answer: 'der',
    validation: { noTypoTolerance: true },
    pronounce: ['der Sessel'],
  },
  {
    id: 'p7-mob-sessel-satz',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['home.moebel.sessel', 'adjectives.tarif.grau'],
    familyId: 'p7-mob-sessel-satz',
    instruction: 'Boşluğu doldur — "koltuk" kelimesini yaz:',
    prompt: 'Der ___ ist grau. (Koltuk gri.)',
    answer: 'Sessel',
    pronounce: ['Der Sessel ist grau.'],
  },
  {
    id: 'p7-mob-bett-tr-de',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.moebel.bett'],
    familyId: 'p7-mob-bett-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Yatak küçük. → ______',
    answer: 'Das Bett ist klein.',
    pronounce: ['Das Bett ist klein.'],
  },
  {
    id: 'p7-mob-fernseher-tr-de',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.moebel.fernseher'],
    familyId: 'p7-mob-fernseher-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Televizyon büyük. → ______',
    answer: 'Der Fernseher ist groß.',
    validation: { keyboardTolerance: true },
    pronounce: ['Der Fernseher ist groß.'],
  },
  {
    id: 'p7-mob-schlafen-mc',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['home.moebel.bett'],
    familyId: 'p7-mob-schlafen',
    instruction: 'Hangi eşyada uyursun?',
    prompt: 'Hier schlafe ich.',
    answer: 'das Bett',
    options: ['das Bett', 'der Schrank', 'der Herd', 'das Regal'],
    pronounce: ['das Bett'],
  },
  {
    id: 'p7-mob-auf-dem-sessel-wb',
    topicId: T.home, legacyDay: 7,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.moebel.auf-dem-sessel'],
    familyId: 'p7-mob-auf-dem-sessel',
    instruction: 'Türkçeden Almancaya kur — Kedi koltukta.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Kedi koltukta.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Die' }, { id: 't2', text: 'Katze' }, { id: 't3', text: 'ist' },
        { id: 't4', text: 'auf' }, { id: 't5', text: 'dem' }, { id: 't6', text: 'Sessel.' },
        { id: 't7', text: 'in' }, { id: 't8', text: 'der' },
      ],
      acceptedSequences: [['Die', 'Katze', 'ist', 'auf', 'dem', 'Sessel.']],
    },
    answer: 'Die Katze ist auf dem Sessel.',
    pronounce: ['Die Katze ist auf dem Sessel.'],
  },
  {
    id: 'p7-mob-dictation-schrank',
    topicId: T.home, legacyDay: 7,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.moebel.schrank'],
    familyId: 'p7-mob-dictation-schrank',
    instruction: 'Duyduğun cümleyi aynen yaz:',
    audioText: 'Der Schrank ist groß.',
    answer: 'Der Schrank ist groß.',
    validation: { keyboardTolerance: true },
    audio: { prompt: { text: 'Der Schrank ist groß.', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Evimi Anlatıyorum — Meine Wohnung (21) ---- */
  {
    id: 'p7-evim-toiletten-tr-de',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.evim.toiletten'],
    familyId: 'p7-evim-toiletten',
    instruction: 'Kendi evinden bahsediyorsun. Türkçeden Almancaya çevir:',
    prompt: 'Evimizde üç tuvalet var. → ______',
    answer: 'Wir haben drei Toiletten.',
    pronounce: ['Wir haben drei Toiletten.'],
  },
  {
    id: 'p7-evim-ich-habe-zimmer-wb',
    topicId: T.home, legacyDay: 7,
    type: 'word-bank-translation', difficulty: 'easy', skill: 'production',
    conceptIds: ['home.evim.model'],
    familyId: 'p7-evim-ich-habe-zimmer',
    instruction: 'Türkçeden Almancaya kur — Benim bir odam var.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Benim bir odam var.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'habe' }, { id: 't3', text: 'ein' }, { id: 't4', text: 'Zimmer.' },
        { id: 't5', text: 'bin' }, { id: 't6', text: 'eine' },
      ],
      acceptedSequences: [['Ich', 'habe', 'ein', 'Zimmer.']],
    },
    answer: 'Ich habe ein Zimmer.',
    pronounce: ['Ich habe ein Zimmer.'],
  },
  {
    id: 'p7-evim-schwester-wb',
    topicId: T.home, legacyDay: 7,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.evim.schwester'],
    familyId: 'p7-evim-schwester',
    instruction: 'Türkçeden Almancaya kur — Ablamın da bir odası var.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ablamın da bir odası var.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Meine' }, { id: 't2', text: 'Schwester' }, { id: 't3', text: 'hat' },
        { id: 't4', text: 'auch' }, { id: 't5', text: 'ein' }, { id: 't6', text: 'Zimmer.' },
        { id: 't7', text: 'ist' }, { id: 't8', text: 'und' },
      ],
      acceptedSequences: [['Meine', 'Schwester', 'hat', 'auch', 'ein', 'Zimmer.']],
    },
    answer: 'Meine Schwester hat auch ein Zimmer.',
    pronounce: ['Meine Schwester hat auch ein Zimmer.'],
  },
  {
    id: 'p7-evim-ihr-zimmer-hell-fill',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['home.evim.ihr-zimmer'],
    familyId: 'p7-evim-ihr-zimmer-hell',
    instruction: 'Boşluğu doldur — "onun (ablamın)" iyelik zamirini yaz:',
    prompt: '___ Zimmer ist hell. (Onun odası açık renkli.)',
    answer: 'Ihr',
    validation: { caseSensitive: true, noTypoTolerance: true },
    pronounce: ['Ihr Zimmer ist hell.'],
  },
  {
    id: 'p7-evim-ihr-zimmer-gross-tr-de',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.evim.ihr-zimmer'],
    familyId: 'p7-evim-ihr-zimmer-gross',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onun odası büyük. → ______',
    answer: 'Ihr Zimmer ist groß.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ihr Zimmer ist groß.'],
  },
  {
    id: 'p7-evim-mein-zimmer-grau-tr-de',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.evim.mein-zimmer'],
    familyId: 'p7-evim-mein-zimmer-grau',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Benim odam gri. → ______',
    answer: 'Mein Zimmer ist grau.',
    pronounce: ['Mein Zimmer ist grau.'],
  },
  {
    id: 'p7-evim-mein-zimmer-dunkel-order',
    topicId: T.home, legacyDay: 7,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.evim.mein-zimmer', 'adjectives.tarif.dunkel'],
    familyId: 'p7-evim-mein-zimmer-dunkel',
    instruction: 'Kelimeleri doğru sıraya diz — Benim odam karanlık ve küçük.',
    answer: 'Mein Zimmer ist dunkel und klein.',
    pronounce: ['Mein Zimmer ist dunkel und klein.'],
  },
  {
    id: 'p7-evim-wohnzimmer-tr-de',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.evim.wohnzimmer'],
    familyId: 'p7-evim-wohnzimmer',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Salonumuz var. → ______',
    answer: 'Wir haben ein Wohnzimmer.',
    pronounce: ['Wir haben ein Wohnzimmer.'],
  },
  {
    id: 'p7-evim-balkon-fill',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['home.evim.balkon'],
    familyId: 'p7-evim-balkon',
    instruction: 'Boşluğa doğru belirsiz artikeli yaz (`der Balkon` → Akkusativ):',
    prompt: 'Wir haben ___ Balkon. (Balkonumuz var.)',
    answer: 'einen',
    validation: { noTypoTolerance: true },
    explanation: '`haben` nesneyi Akkusativ ister; eril `ein` → `einen`.',
    pronounce: ['Wir haben einen Balkon.'],
  },
  {
    id: 'p7-evim-balkon-gross-tr-de',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.evim.balkon', 'adjectives.tarif.gross-klein'],
    familyId: 'p7-evim-balkon-gross',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Balkon büyük. → ______',
    answer: 'Der Balkon ist groß.',
    validation: { keyboardTolerance: true },
    pronounce: ['Der Balkon ist groß.'],
  },
  {
    id: 'p7-evim-kueche-unsere-tr-de',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.evim.kueche'],
    familyId: 'p7-evim-kueche-unsere',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Mutfağımız ferah. → ______',
    answer: 'Unsere Küche ist hell.',
    hint: '"ferah / açık renkli" için bugünkü kelime: `hell`.',
    pronounce: ['Unsere Küche ist hell.'],
  },
  {
    id: 'p7-evim-katze-wb',
    topicId: T.home, legacyDay: 7,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.evim.katze'],
    familyId: 'p7-evim-katze',
    instruction: 'Türkçeden Almancaya kur — Kedimizin de bir odası var.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Kedimizin de bir odası var.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Unsere' }, { id: 't2', text: 'Katze' }, { id: 't3', text: 'hat' },
        { id: 't4', text: 'auch' }, { id: 't5', text: 'ein' }, { id: 't6', text: 'Zimmer.' },
        { id: 't7', text: 'Unser' }, { id: 't8', text: 'ist' },
      ],
      acceptedSequences: [['Unsere', 'Katze', 'hat', 'auch', 'ein', 'Zimmer.']],
    },
    answer: 'Unsere Katze hat auch ein Zimmer.',
    pronounce: ['Unsere Katze hat auch ein Zimmer.'],
  },
  {
    id: 'p7-evim-richtig-falsch-mein-zimmer',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['home.evim.mein-zimmer'],
    familyId: 'p7-evim-rf-mein-zimmer',
    instruction: 'Kendi evine göre doğru mu yanlış mı? (Senin odan gri ve karanlık.)',
    prompt: 'Mein Zimmer ist hell.',
    answer: 'falsch — Mein Zimmer ist dunkel.',
    options: [
      'falsch — Mein Zimmer ist dunkel.',
      'richtig — Mein Zimmer ist hell.',
      'falsch — Mein Zimmer ist groß.',
      'richtig — Mein Zimmer ist grau und hell.',
    ],
    pronounce: ['Mein Zimmer ist dunkel.'],
  },
  {
    id: 'p7-evim-error-kueche-dunkel',
    topicId: T.home, legacyDay: 7,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['home.evim.kueche', 'adjectives.tarif.hell'],
    familyId: 'p7-evim-error-kueche',
    instruction: 'Evinin bilgisine göre cümle yanlış — düzelt: (Mutfağınız açık renkli ve ferah.)',
    prompt: 'Unsere Küche ist dunkel.',
    answer: 'Unsere Küche ist hell.',
    pronounce: ['Unsere Küche ist hell.'],
  },
  {
    id: 'p7-evim-error-schwester-klein',
    topicId: T.home, legacyDay: 7,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['home.evim.ihr-zimmer', 'home.evim.karsilastirma-yok'],
    familyId: 'p7-evim-error-schwester',
    instruction: 'Evinin bilgisine göre cümle yanlış — düzelt: (Ablanın odası büyük.)',
    prompt: 'Ihr Zimmer ist klein.',
    answer: 'Ihr Zimmer ist groß.',
    validation: { keyboardTolerance: true },
    explanation: 'Karşılaştırma eki henüz öğrenilmedi; bilgiyi iki ayrı cümleyle veriyoruz: `Ihr Zimmer ist groß.` + `Mein Zimmer ist klein.`',
    pronounce: ['Ihr Zimmer ist groß.'],
  },
  {
    id: 'p7-evim-karsilastirma-mc',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['home.evim.karsilastirma-yok'],
    familyId: 'p7-evim-karsilastirma',
    instruction: '"Ablamın odası benim odamdan daha büyük." fikrini bugünkü bilgiyle nasıl söylersin?',
    prompt: 'Ablamın odası daha büyük.',
    answer: 'Ihr Zimmer ist groß. Mein Zimmer ist klein.',
    options: [
      'Ihr Zimmer ist groß. Mein Zimmer ist klein.',
      'Ihr Zimmer ist mehr groß.',
      'Ihr Zimmer groß ist, mein Zimmer klein ist.',
      'Ihr Zimmer ist groß und klein.',
    ],
    explanation: 'Türkçedeki "daha büyük" için Almancada ayrı bir karşılaştırma eki gerekir; o ek henüz öğretilmedi. Aynı anlamı iki basit cümleyle koruruz.',
    pronounce: ['Ihr Zimmer ist groß.', 'Mein Zimmer ist klein.'],
  },
  {
    id: 'p7-evim-dictation-model',
    topicId: T.home, legacyDay: 7,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.evim.model'],
    familyId: 'p7-evim-dictation',
    instruction: 'Evini anlatan cümleyi duy ve aynen yaz:',
    audioText: 'Wir haben eine Wohnung.',
    answer: 'Wir haben eine Wohnung.',
    audio: { prompt: { text: 'Wir haben eine Wohnung.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p7-evim-spoken-kisa',
    topicId: T.home, legacyDay: 7,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['home.evim.model', 'home.evim.toiletten', 'home.evim.mein-zimmer'],
    familyId: 'p7-evim-spoken-kisa',
    instruction: 'Evini 4–6 cümleyle sesli anlat. İpuçları aşağıda.',
    prompt: 'Toiletten:\nmein Zimmer:\nWohnzimmer:\nKüche:',
    requirements: [
      'Kaç tuvaletiniz olduğunu söyle (`Wir haben ...`).',
      'Kendi odanı iki sıfatla tarif et (`Mein Zimmer ist ...`).',
      'Salondan ve mutfaktan bahset.',
    ],
    sampleAnswer: 'Wir haben drei Toiletten. Mein Zimmer ist grau und klein. Wir haben ein Wohnzimmer. Unsere Küche ist hell.',
    audio: { targets: [{ text: 'Wir haben drei Toiletten. Mein Zimmer ist grau und klein. Wir haben ein Wohnzimmer. Unsere Küche ist hell.', language: 'de-DE', role: 'example' }] },
  },
  {
    id: 'p7-evim-free-tam-anlatim',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [
      'home.evim.model',
      'home.evim.toiletten',
      'home.evim.schwester',
      'home.evim.balkon',
      'home.evim.katze',
    ],
    familyId: 'p7-evim-free-tam',
    openEnded: true,
    instruction: 'Evini Almanca olarak anlat. En az sekiz cümle yaz — ipuçları aşağıda.',
    prompt: 'Toiletten:\nmein Zimmer:\nZimmer meiner Schwester:\nWohnzimmer:\nBalkon:\nKüche:\nKatze:',
    hint: 'Sadece `Wir haben ...`, `Ich habe ...`, `... ist ...` ve `... hat auch ...` kalıplarını kullan. Karşılaştırma yapma.',
    answer: 'Wir haben eine Wohnung. Wir haben drei Toiletten. Ich habe ein Zimmer. Meine Schwester hat auch ein Zimmer. Ihr Zimmer ist hell und groß. Mein Zimmer ist grau, dunkel und klein. Wir haben ein Wohnzimmer. Wir haben einen Balkon. Der Balkon ist groß. Wir haben eine Küche. Unsere Küche ist hell. Wir haben eine Katze. Unsere Katze hat auch ein Zimmer.',
    explanation: 'Kanonik A1 model: karşılaştırma, genitif ve yan cümle içermez — her bilgi ayrı basit cümledir.',
    pronounce: ['Wir haben eine Wohnung. Wir haben drei Toiletten. Ich habe ein Zimmer. Meine Schwester hat auch ein Zimmer.'],
  },
  {
    id: 'p7-evim-spoken-tam',
    topicId: T.home, legacyDay: 7,
    type: 'spoken', difficulty: 'hard', skill: 'speaking',
    conceptIds: ['home.evim.model', 'home.evim.kueche', 'home.evim.katze'],
    familyId: 'p7-evim-spoken-tam',
    instruction: 'İpuçlarına bakmadan evini baştan sona sesli anlat.',
    requirements: [
      'En az on cümle kur.',
      'Odaları, renkleri, balkonu, mutfağı ve kediyi anlat.',
      'Karşılaştırma yapma — her bilgiyi ayrı cümlede söyle.',
    ],
    sampleAnswer: 'Wir haben eine Wohnung. Wir haben drei Toiletten. Ich habe ein Zimmer. Meine Schwester hat auch ein Zimmer. Ihr Zimmer ist hell. Mein Zimmer ist grau. Wir haben einen Balkon. Unsere Küche ist hell. Wir haben eine Katze. Unsere Katze hat auch ein Zimmer.',
    audio: { targets: [{ text: 'Wir haben eine Wohnung. Wir haben drei Toiletten. Ich habe ein Zimmer. Meine Schwester hat auch ein Zimmer. Ihr Zimmer ist hell. Mein Zimmer ist grau. Wir haben einen Balkon. Unsere Küche ist hell. Wir haben eine Katze. Unsere Katze hat auch ein Zimmer.', language: 'de-DE', role: 'example' }] },
  },
  {
    id: 'p10-rev-quadrat-fill',
    topicId: T.home, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['home.wort.zimmer-satz'],
    familyId: 'p10-rev-quadrat',
    instruction: 'Kelimeyi yaz — Oda on metrekare.',
    prompt: 'Das Zimmer ist zehn ___ groß. (metrekare)',
    answer: 'Quadratmeter',
    pronounce: ['Das Zimmer ist zehn Quadratmeter groß.'],
  },

  /* ---- Evimi Anlatmak İçin Cümle Kalıpları (5) ---- */
  {
    id: 'p7-kal-wir-haben-mc',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.kalip.wir-haben'],
    familyId: 'p7-kal-wir-haben',
    instruction: 'Evde ne olduğunu söylemek için hangi kalıbı kullanırsın?',
    prompt: 'Mutfağımız var.',
    answer: 'Wir haben eine Küche.',
    options: ['Wir haben eine Küche.', 'Wir sind eine Küche.', 'Wir eine Küche haben.', 'Unser Küche ist.'],
    pronounce: ['Wir haben eine Küche.'],
  },
  {
    id: 'p7-kal-ist-sifat-fill',
    topicId: T.home, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['home.kalip.ist-sifat'],
    familyId: 'p7-kal-ist-sifat',
    instruction: 'Tarif kalıbını tamamla:',
    prompt: 'Das Wohnzimmer ___ groß. (Salon büyük.)',
    answer: 'ist',
    validation: { noTypoTolerance: true },
    pronounce: ['Das Wohnzimmer ist groß.'],
  },
  {
    id: 'p7-kal-hat-auch-order',
    topicId: T.home, legacyDay: 7,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.kalip.hat-auch'],
    familyId: 'p7-kal-hat-auch',
    instruction: 'Kelimeleri doğru sıraya diz — Kedimin de bir odası var.',
    answer: 'Meine Katze hat auch ein Zimmer.',
    pronounce: ['Meine Katze hat auch ein Zimmer.'],
  },
  {
    id: 'p7-kal-es-gibt-tr-de',
    topicId: T.home, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['home.kalip.es-gibt', 'home.ev.wohnzimmer'],
    familyId: 'p7-kal-es-gibt',
    instruction: 'Türkçeden Almancaya çevir (`es gibt` kalıbıyla):',
    prompt: 'Salonda bir balkon var. → ______',
    answer: 'Im Wohnzimmer gibt es einen Balkon.',
    hint: '`der Balkon` eril → `einen`.',
    pronounce: ['Im Wohnzimmer gibt es einen Balkon.'],
  },
  {
    id: 'p7-kal-sira-mc',
    topicId: T.home, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['home.kalip.sira'],
    familyId: 'p7-kal-sira',
    instruction: 'Evini anlatırken önerilen sıra hangisidir?',
    prompt: 'anlatım sırası',
    answer: 'odalar ve tuvaletler → benim odam → ablamın odası → salon ve balkon → mutfak → kedi',
    options: [
      'odalar ve tuvaletler → benim odam → ablamın odası → salon ve balkon → mutfak → kedi',
      'kedi → mutfak → benim odam → tuvaletler',
      'mutfak → tuvaletler → kedi → balkon',
      'balkon → kedi → benim odam → salon',
    ],
  },

  /* ---- Pencere, perde ve evde işler ---- */
  {
    id: 'ev-fenster-artikel-fill',
    topicId: T.home,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['home.fenster-vorhang'],
    familyId: 'ev-fenster',
    instruction: 'Artikeli yaz — pencere:',
    prompt: '___ Fenster',
    answer: 'das',
    validation: { noTypoTolerance: true },
    pronounce: ['das Fenster'],
  },
  {
    id: 'ev-vorhang-mc',
    topicId: T.home,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.fenster-vorhang'],
    familyId: 'ev-vorhang',
    instruction: '"perde" Almancada hangisi?',
    prompt: 'perde',
    answer: 'der Vorhang',
    options: ['der Vorhang', 'das Seil', 'das Fenster', 'der Teppich'],
    pronounce: ['der Vorhang'],
  },
  {
    id: 'ev-vorhang-grau-sb',
    topicId: T.home,
    type: 'sentence-builder', difficulty: 'easy', skill: 'production',
    conceptIds: ['home.fenster-vorhang', 'adjectives.tarif.grau'],
    familyId: 'ev-vorhang-grau',
    instruction: 'Cümleyi kur — fazladan bir kelime var:',
    prompt: 'Perde gri.',
    answer: 'Der Vorhang ist grau.',
    pronounce: ['Der Vorhang ist grau.'],
  },
  {
    id: 'ev-giessen-tr',
    topicId: T.home,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.giessen'],
    familyId: 'ev-giessen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Çiçekleri suluyorum.',
    answer: 'Ich gieße die Blumen.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich gieße die Blumen.'],
  },
  {
    id: 'ev-spuelen-tr',
    topicId: T.home,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.spuelen'],
    familyId: 'ev-spuelen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bulaşıkları yıkıyorum.',
    answer: 'Ich spüle das Geschirr.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich spüle das Geschirr.'],
  },
  {
    id: 'ev-reparieren-tr',
    topicId: T.home,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['home.reparieren', 'home.fenster-vorhang'],
    familyId: 'ev-reparieren',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Babam pencereyi tamir ediyor.',
    answer: 'Mein Vater repariert das Fenster.',
    pronounce: ['Mein Vater repariert das Fenster.'],
  },
  {
    id: 'ev-hausarbeit-match',
    topicId: T.home,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['home.giessen', 'home.spuelen', 'home.reparieren'],
    familyId: 'ev-hausarbeit',
    instruction: 'Ev işlerini anlamlarıyla eşleştir.',
    pairs: [
      { left: 'putzen', right: 'temizlemek' },
      { left: 'gießen', right: 'sulamak' },
      { left: 'spülen', right: '(bulaşık) yıkamak' },
      { left: 'reparieren', right: 'tamir etmek' },
    ],
  },
];
