/**
 * Sevmek ve Beğenmek — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const LIKES_EXERCISES: AuthoredExercise[] = [
  /* ---- mögen ve gern — Sevmek (10) ---- */
  {
    id: 'p3-mg-mag-cekim-mc',
    topicId: T.likes, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['likes.mogen.cekim'],
    familyId: 'p3-mg-mag-cekim',
    instruction: 'mögen çekimi — doğru formu seç:',
    prompt: 'ich ___ (mögen)',
    answer: 'mag',
    options: ['mag', 'magst', 'möchte', 'gern'],
    pronounce: ['ich mag'],
  },
  {
    id: 'p3-mg-magst-fill',
    topicId: T.likes, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['likes.mogen.cekim'],
    familyId: 'p3-mg-magst',
    instruction: 'mögen çekimi:',
    prompt: 'du ___ (mögen)',
    answer: 'magst',
    pronounce: ['du magst'],
  },
  {
    id: 'p3-mg-katzen-fill',
    topicId: T.likes, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['likes.mogen.cekim'],
    familyId: 'p3-mg-katzen',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich ___ Katzen. (kedileri severim)',
    answer: 'mag',
    pronounce: ['Ich mag Katzen.'],
  },
  {
    id: 'p3-mg-gern-yapi-mc',
    topicId: T.likes, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['likes.gern.kullanim'],
    familyId: 'p3-mg-gern-yapi',
    instruction: '"gern" cümlede nereye gelir?',
    prompt: 'gern',
    answer: 'Bir fiilden hemen sonra',
    options: ['Bir fiilden hemen sonra', 'Cümlenin en başına', 'Bir isimden önce', 'Tek başına kullanılır'],
  },
  {
    id: 'p3-mg-schwimme-gern-fill',
    topicId: T.likes, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['likes.gern.kullanim'],
    familyId: 'p3-mg-schwimme-gern',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich schwimme ___ im Meer. (yüzmeyi severim)',
    answer: 'gern',
    pronounce: ['Ich schwimme gern im Meer.'],
  },
  {
    id: 'p3-mg-esse-gern-order',
    topicId: T.likes, legacyDay: 3,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['likes.gern.kullanim'],
    familyId: 'p3-mg-esse-gern',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / esse / gern / Äpfel.',
    answer: 'Ich esse gern Äpfel.',
    words: ['Ich', 'esse', 'gern', 'Äpfel'],
    pronounce: ['Ich esse gern Äpfel.'],
  },
  {
    id: 'p3-mg-spiele-gern-builder-tr',
    topicId: T.likes, legacyDay: 3,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['likes.gern.kullanim'],
    familyId: 'p3-mg-spiele-gern',
    instruction: 'Cümleyi kur:',
    prompt: 'Ben futbol oynamayı seviyorum.',
    answer: 'Ich spiele gern Fußball.',
    words: ['Ich', 'spiele', 'gern', 'Fußball'],
    pronounce: ['Ich spiele gern Fußball.'],
  },
  {
    id: 'p3-mg-mag-gern-farki-mc',
    topicId: T.likes, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['likes.mogen-gern-farki'],
    familyId: 'p3-mg-farki',
    instruction: '"mag" ile "gern" arasındaki fark nedir?',
    prompt: 'mag ↔ gern',
    answer: 'mag bir ismi doğrudan sever, gern bir fiilden sonra gelir',
    options: [
      'mag bir ismi doğrudan sever, gern bir fiilden sonra gelir',
      'İkisi de tamamen aynı anlama gelir',
      'mag sadece soru cümlelerinde kullanılır',
      'gern sadece olumsuz cümlelerde kullanılır',
    ],
  },
  {
    id: 'p3-mg-tiere-fill',
    topicId: T.likes, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['likes.mogen-gern-farki'],
    familyId: 'p3-mg-tiere',
    instruction: 'Boşluğu doldur — bir ismi seviyorsun:',
    prompt: 'Meine Schwester ___ Tiere. (kardeşim hayvanları çok seviyor)',
    answer: 'mag',
    pronounce: ['Meine Schwester mag Tiere.'],
  },
  {
    id: 'p3-mg-bananen-fill',
    topicId: T.likes, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['likes.mogen.cekim'],
    familyId: 'p3-mg-bananen',
    instruction: 'Boşluğu doldur (mögen):',
    prompt: 'Meine Schwester ___ Bananen. (kardeşim muz seviyor)',
    answer: 'mag',
    pronounce: ['Meine Schwester mag Bananen.'],
  },

  /* ---- gefallen — Beğenmek (3) ---- */
  {
    id: 'p7-gef-anlam-mc',
    topicId: T.likes, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['likes.gefallen.anlam'],
    familyId: 'p7-gef-anlam',
    instruction: '"gefallen" ne demektir?',
    prompt: 'gefallen',
    answer: 'beğenmek, hoşuna gitmek',
    options: ['beğenmek, hoşuna gitmek', 'düşmek', 'vermek', 'aramak'],
    pronounce: ['gefallen'],
  },
  {
    id: 'p7-gef-kalip-fill',
    topicId: T.likes, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['likes.gefallen.kalip'],
    familyId: 'p7-gef-kalip',
    instruction: 'Kalıbı tamamla:',
    prompt: 'Das ___ mir. (Bu hoşuma gidiyor.)',
    answer: 'gefällt',
    validation: { keyboardTolerance: true },
    pronounce: ['Das gefällt mir.'],
  },
  {
    id: 'p7-gef-tr-de',
    topicId: T.likes, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['likes.gefallen.kalip', 'home.moebel.teppich-regal'],
    familyId: 'p7-gef-tr-de',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Halı hoşuma gidiyor. → ______',
    answer: 'Der Teppich gefällt mir.',
    validation: { keyboardTolerance: true },
    pronounce: ['Der Teppich gefällt mir.'],
  },
];
