/**
 * Sayılar — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const NUMBERS_EXERCISES: AuthoredExercise[] = [
  /* ---- Sayılar 10–100 (26) ---- */
  {
    id: 'p5-son-elf-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['numbers.sayilar.onlu-sayilar'],
    familyId: 'p5-son-elf',
    instruction: 'Almanca yaz:',
    prompt: '11 → ___',
    answer: 'elf',
    pronounce: ['elf'],
  },
  {
    id: 'p5-son-dreizehn-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['numbers.sayilar.onlu-sayilar'],
    familyId: 'p5-son-dreizehn',
    instruction: 'Doğru Almancasını seç:',
    prompt: '13',
    answer: 'dreizehn',
    options: ['dreizehn', 'vierzehn', 'dreißig', 'drei'],
    pronounce: ['dreizehn'],
  },
  {
    id: 'p5-son-sechzehn-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['numbers.sayilar.onlu-sayilar'],
    familyId: 'p5-son-sechzehn',
    instruction: 'Almanca yaz (istisna: sechs → sech):',
    prompt: '16 → ___',
    answer: 'sechzehn',
    pronounce: ['sechzehn'],
  },
  {
    id: 'p5-son-siebzehn-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['numbers.sayilar.onlu-sayilar'],
    familyId: 'p5-son-siebzehn',
    instruction: 'Doğru Almancasını seç (istisna: sieben → sieb):',
    prompt: '17',
    answer: 'siebzehn',
    options: ['siebzehn', 'siebenzehn', 'siebzig', 'sieben'],
    pronounce: ['siebzehn'],
  },
  {
    id: 'p5-son-teens-sequence-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['numbers.sayilar.onlu-sayilar'],
    familyId: 'p5-son-teens-sequence',
    instruction: 'Diziyi tamamla:',
    prompt: 'elf, zwölf, ___, vierzehn',
    answer: 'dreizehn',
    pronounce: ['dreizehn'],
  },
  {
    id: 'p5-son-zwanzig-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['numbers.sayilar.onluklar'],
    familyId: 'p5-son-zwanzig',
    instruction: 'Doğru Almancasını seç:',
    prompt: '20',
    answer: 'zwanzig',
    options: ['zwanzig', 'zehn', 'zwölf', 'zwei'],
    pronounce: ['zwanzig'],
  },
  {
    id: 'p5-son-dreissig-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['numbers.sayilar.onluklar'],
    familyId: 'p5-son-dreissig',
    instruction: 'Almanca yaz (ß ile):',
    prompt: '30 → ___',
    answer: 'dreißig',
    validation: { keyboardTolerance: true },
    pronounce: ['dreißig'],
  },
  {
    id: 'p5-son-error-dreissig',
    topicId: T.numbers, legacyDay: 5,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['numbers.sayilar.onluklar'],
    familyId: 'p5-son-error-dreissig',
    instruction: 'Hata avı — yazım:',
    prompt: '30 = dreissig',
    answer: '30 = dreißig',
    explanation: '30 her zaman `ß` harfiyle yazılır: `dreißig`, `dreissig` değil.',
    pronounce: ['dreißig'],
  },
  {
    id: 'p5-son-tens-sequence-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['numbers.sayilar.onluklar'],
    familyId: 'p5-son-tens-sequence',
    instruction: 'Diziyi tamamla:',
    prompt: 'zwanzig, dreißig, vierzig, ___, sechzig',
    answer: 'fünfzig',
    pronounce: ['fünfzig'],
  },
  {
    id: 'p5-son-sechzig-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['numbers.sayilar.onluklar'],
    familyId: 'p5-son-sechzig',
    instruction: 'Doğru Almancasını seç (istisna: sechs → sech):',
    prompt: '60',
    answer: 'sechzig',
    options: ['sechzig', 'sechszig', 'sechs', 'sechzehn'],
    pronounce: ['sechzig'],
  },
  {
    id: 'p5-son-25-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'production',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-25',
    instruction: 'Almanca yaz (birler + und + onlar):',
    prompt: '25 → ___',
    answer: 'fünfundzwanzig',
    pronounce: ['fünfundzwanzig'],
  },
  {
    id: 'p5-son-46-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-46',
    instruction: 'Almanca yaz:',
    prompt: '46 → ___',
    answer: 'sechsundvierzig',
    pronounce: ['sechsundvierzig'],
  },
  {
    id: 'p5-son-94-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-94',
    instruction: 'Almanca yaz:',
    prompt: '94 → ___',
    answer: 'vierundneunzig',
    pronounce: ['vierundneunzig'],
  },
  {
    id: 'p5-son-83-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-83',
    instruction: 'Doğru Almancasını seç:',
    prompt: '83',
    answer: 'dreiundachtzig',
    options: ['dreiundachtzig', 'achtunddreißig', 'dreißigundacht', 'achtzigunddrei'],
    pronounce: ['dreiundachtzig'],
  },
  {
    id: 'p5-son-96-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-96',
    instruction: 'Almanca yaz:',
    prompt: '96 → ___',
    answer: 'sechsundneunzig',
    pronounce: ['sechsundneunzig'],
  },
  {
    id: 'p5-son-79-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-79',
    instruction: 'Almanca yaz:',
    prompt: '79 → ___',
    answer: 'neunundsiebzig',
    pronounce: ['neunundsiebzig'],
  },
  {
    id: 'p5-son-87-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-87',
    instruction: 'Doğru Almancasını seç:',
    prompt: '87',
    answer: 'siebenundachtzig',
    options: ['siebenundachtzig', 'achtundsiebzig', 'siebzigundacht', 'achtzigundsieben'],
    pronounce: ['siebenundachtzig'],
  },
  {
    id: 'p5-son-65-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'production',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-65',
    instruction: 'Almanca yaz:',
    prompt: '65 → ___',
    answer: 'fünfundsechzig',
    pronounce: ['fünfundsechzig'],
  },
  {
    id: 'p5-son-54-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-54',
    instruction: 'Almanca yaz (dikkat — sıra):',
    prompt: '54 → ___',
    answer: 'vierundfünfzig',
    pronounce: ['vierundfünfzig'],
  },
  {
    id: 'p5-son-54-error',
    topicId: T.numbers, legacyDay: 5,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-54',
    instruction: 'Hata avı — bu hangi sayının Almancası?',
    prompt: '54 = fünfundvierzig',
    answer: '54 = vierundfünfzig',
    explanation: '`fünfundvierzig` aslında 45 demektir. 54 için önce birler (vier), sonra `und`, sonra onlar (fünfzig): `vierundfünfzig`.',
    pronounce: ['vierundfünfzig'],
  },
  {
    id: 'p5-son-numeric-dreiundachtzig-free',
    topicId: T.numbers, legacyDay: 5,
    type: 'free-text', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-83',
    instruction: 'Bu hangi sayı? Rakamla yaz:',
    prompt: 'dreiundachtzig',
    answer: '83',
    pronounce: ['dreiundachtzig'],
  },
  {
    id: 'p5-son-numeric-vierundfuenfzig-free',
    topicId: T.numbers, legacyDay: 5,
    type: 'free-text', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-54',
    instruction: 'Bu hangi sayı? Rakamla yaz:',
    prompt: 'vierundfünfzig',
    answer: '54',
    pronounce: ['vierundfünfzig'],
  },
  {
    id: 'p5-son-compare-larger-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-compare',
    instruction: 'Hangisi daha büyüktür?',
    prompt: 'vierundachtzig / achtundvierzig / vierzig / achtzig',
    answer: 'vierundachtzig',
    options: ['vierundachtzig', 'achtundvierzig', 'vierzig', 'achtzig'],
    explanation: 'vierundachtzig = 84, achtundvierzig = 48 — sıra karıştırılınca anlam tamamen değişir.',
    pronounce: ['vierundachtzig'],
  },
  {
    id: 'p5-son-listen-46',
    topicId: T.numbers, legacyDay: 5,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-46',
    instruction: 'Duyduğun sayıyı seç:',
    prompt: 'sechsundvierzig',
    audioText: 'sechsundvierzig',
    answer: 'sechsundvierzig',
    options: ['sechsundvierzig', 'vierzig', 'sechzehn', 'sechzig'],
    audio: { prompt: { text: 'sechsundvierzig', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-son-listen-94',
    topicId: T.numbers, legacyDay: 5,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-94',
    instruction: 'Duyduğun sayıyı seç:',
    prompt: 'vierundneunzig',
    audioText: 'vierundneunzig',
    answer: 'vierundneunzig',
    options: ['vierundneunzig', 'neunzig', 'vierzehn', 'neunzehn'],
    audio: { prompt: { text: 'vierundneunzig', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-son-dictation-65',
    topicId: T.numbers, legacyDay: 5,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['numbers.sayilar.bilesik'],
    familyId: 'p5-son-65',
    instruction: 'Duyduğun iki basamaklı sayıyı aynen yaz:',
    audioText: 'fünfundsechzig',
    answer: 'fünfundsechzig',
    audio: { prompt: { text: 'fünfundsechzig', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Yüzler ve Bin (9) ---- */
  {
    id: 'p5-syu-hundert-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['numbers.sayilar.yuzler'],
    familyId: 'p5-syu-hundert',
    instruction: 'Doğru Almancasını seç:',
    prompt: '100',
    answer: 'hundert',
    options: ['hundert', 'zehn', 'tausend', 'hundertzehn'],
    pronounce: ['hundert'],
  },
  {
    id: 'p5-syu-200-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['numbers.sayilar.yuzler'],
    familyId: 'p5-syu-200',
    instruction: 'Almanca yaz:',
    prompt: '200 → ___',
    answer: 'zweihundert',
    pronounce: ['zweihundert'],
  },
  {
    id: 'p5-syu-205-fill',
    topicId: T.numbers, legacyDay: 5,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['numbers.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-205',
    instruction: 'Almanca yaz (hundert\'den sonra und yok):',
    prompt: '205 → ___',
    answer: 'zweihundertfünf',
    pronounce: ['zweihundertfünf'],
  },
  {
    id: 'p5-syu-205-error',
    topicId: T.numbers, legacyDay: 5,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['numbers.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-205',
    instruction: 'Hata avı:',
    prompt: '205 = zweihundertundfünf',
    answer: '205 = zweihundertfünf',
    explanation: '`hundert`den sonra gelen sayıyla arasına `und` girmez; `und` yalnızca birler-onlar arasında kullanılır.',
    pronounce: ['zweihundertfünf'],
  },
  {
    id: 'p5-syu-1000-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['numbers.sayilar.bin'],
    familyId: 'p5-syu-1000',
    instruction: 'Doğru Almancasını seç:',
    prompt: '1000',
    answer: 'tausend',
    options: ['tausend', 'hundert', 'zweihundert', 'zehn'],
    pronounce: ['tausend'],
  },
  {
    id: 'p5-syu-dictation-205',
    topicId: T.numbers, legacyDay: 5,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['numbers.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-205',
    instruction: 'Duyduğun üç basamaklı sayıyı aynen yaz:',
    audioText: 'zweihundertfünf',
    answer: 'zweihundertfünf',
    audio: { prompt: { text: 'zweihundertfünf', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-syu-listen-zweihundert',
    topicId: T.numbers, legacyDay: 5,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['numbers.sayilar.yuzler'],
    familyId: 'p5-syu-200',
    instruction: 'Duyduğun sayıyı seç:',
    prompt: 'zweihundert',
    audioText: 'zweihundert',
    answer: 'zweihundert',
    options: ['zweihundert', 'zwanzig', 'zweihundertfünf', 'hundert'],
    audio: { prompt: { text: 'zweihundert', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-syu-compare-mc',
    topicId: T.numbers, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['numbers.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-compare',
    instruction: 'Hangisi daha büyüktür?',
    prompt: 'zweihundertfünf / hundert / zwanzig / fünfzig',
    answer: 'zweihundertfünf',
    options: ['zweihundertfünf', 'hundert', 'zwanzig', 'fünfzig'],
    pronounce: ['zweihundertfünf'],
  },
  {
    id: 'p5-syu-225-free',
    topicId: T.numbers, legacyDay: 5,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['numbers.sayilar.yuzler-bilesik'],
    familyId: 'p5-syu-225',
    instruction: 'Almanca yaz (yüzler + [birler+und+onlar]):',
    prompt: '225 → ______',
    answer: 'zweihundertfünfundzwanzig',
    pronounce: ['zweihundertfünfundzwanzig'],
  },
];
