/**
 * Kişisel Bilgiler — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const PERSONAL_INFO_EXERCISES: AuthoredExercise[] = [
  /* ---- Yaş, Köken ve İkamet (19) ---- */
  {
    id: 'p1-alt-wie-alt-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.alter.wie-alt'],
    familyId: 'p1-alt-wie-alt',
    instruction: 'Doğru yaş sorusunu seç (samimi):',
    prompt: 'Sen kaç yaşındasın?',
    answer: 'Wie alt bist du?',
    options: ['Wie alt bist du?', 'Wie alt sind Sie?', 'Wo wohnst du?', 'Woher kommst du?'],
    pronounce: ['Wie alt bist du?'],
  },
  {
    id: 'p1-alt-woher-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.herkunft.woher'],
    familyId: 'p1-alt-woher',
    instruction: 'Bu soru ne sorar?',
    prompt: 'Woher kommst du?',
    answer: 'Nerelisin? / Nereden geliyorsun?',
    options: ['Nerelisin? / Nereden geliyorsun?', 'Nerede yaşıyorsun?', 'Ne iş yapıyorsun?', 'Kaç yaşındasın?'],
    pronounce: ['Woher kommst du?'],
  },
  {
    id: 'p1-alt-wo-wohnst-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.wohnort.wo-wohnst'],
    familyId: 'p1-alt-wo-wohnst',
    instruction: 'Doğru soruyu seç:',
    prompt: 'Nerede yaşıyorsun? (samimi)',
    answer: 'Wo wohnst du?',
    options: ['Wo wohnst du?', 'Wo wohnen Sie?', 'Woher kommst du?', 'Wie heißt du?'],
    pronounce: ['Wo wohnst du?'],
  },
  {
    id: 'p1-alt-bin-jahre-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.alter.wie-alt', 'verbs.verben.sein'],
    familyId: 'p1-alt-wie-alt',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich _____ achtzehn Jahre alt. (sein)',
    answer: 'bin',
    pronounce: ['Ich bin achtzehn Jahre alt.'],
  },
  {
    id: 'p1-alt-woher-kommst-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.herkunft.woher'],
    familyId: 'p1-alt-woher',
    instruction: 'Soru kalıbını tamamla:',
    prompt: 'Woher _____ du? (kommen)',
    answer: 'kommst',
    pronounce: ['Woher kommst du?'],
  },
  {
    id: 'p1-alt-wo-wohnst-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.wohnort.wo-wohnst'],
    familyId: 'p1-alt-wo-wohnst',
    instruction: 'Soru kalıbını tamamla:',
    prompt: 'Wo _____ du? (wohnen)',
    answer: 'wohnst',
    pronounce: ['Wo wohnst du?'],
  },
  {
    id: 'p1-alt-komme-aus-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.herkunft.aus', 'verbs.verben.kommen'],
    familyId: 'p1-alt-aus',
    instruction: 'Cevabı tamamla:',
    prompt: 'Ich _____ aus Sakarya. (kommen)',
    answer: 'komme',
    pronounce: ['Ich komme aus Sakarya.'],
  },
  {
    id: 'p1-alt-wohne-in-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.wohnort.in'],
    familyId: 'p1-alt-in',
    instruction: 'Cevabı tamamla:',
    prompt: 'Ich _____ in Sakarya. (wohnen)',
    answer: 'wohne',
    pronounce: ['Ich wohne in Sakarya.'],
  },
  {
    id: 'p1-du-sie-convert-woher',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.herkunft.woher'],
    familyId: 'p1-alt-woher',
    instruction: 'Samimi soruyu resmî hâle çevir:',
    prompt: 'Woher kommst du? → ______',
    answer: 'Woher kommen Sie?',
    pronounce: ['Woher kommen Sie?'],
  },
  {
    id: 'p1-du-sie-convert-wohnen',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.wohnort.wo-wohnst'],
    familyId: 'p1-alt-wo-wohnst',
    instruction: 'Samimi soruyu resmî hâle çevir:',
    prompt: 'Wo wohnst du? → ______',
    answer: 'Wo wohnen Sie?',
    pronounce: ['Wo wohnen Sie?'],
  },
  {
    id: 'p1-hata-aus-mis',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['personal-info.herkunft.aus'],
    familyId: 'p1-alt-aus',
    instruction: 'Hata avı — edatı düzelt:',
    prompt: 'Ich komme in der Türkei.',
    answer: 'Ich komme aus der Türkei.',
    validation: { keyboardTolerance: true },
    explanation: 'Köken için aus, ikamet için in kullanılır.',
    pronounce: ['Ich komme aus der Türkei.'],
  },
  {
    id: 'p1-alt-dialog-woher-wohnst-free',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.herkunft.aus', 'personal-info.wohnort.in'],
    familyId: 'p1-alt-aus',
    instruction: 'İki soruyu tek bir cevapla birleştir:',
    prompt: 'Woher kommst du und wo wohnst du? (Sakarya)',
    answer: 'Ich komme aus Sakarya und wohne in Sakarya.',
    pronounce: ['Ich komme aus Sakarya und wohne in Sakarya.'],
  },
  {
    id: 'p1-wb-wie-alt-tr-de',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.alter.wie-alt'],
    familyId: 'p1-alt-wie-alt',
    instruction: 'Türkçeden Almancaya kur — Kaç yaşındasın?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Kaç yaşındasın?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Wie' }, { id: 't2', text: 'alt' }, { id: 't3', text: 'bist' }, { id: 't4', text: 'du?' },
        { id: 't5', text: 'Wo' }, { id: 't6', text: 'wohnst' },
      ],
      acceptedSequences: [['Wie', 'alt', 'bist', 'du?']],
    },
    answer: 'Wie alt bist du?',
    pronounce: ['Wie alt bist du?'],
  },
  {
    id: 'p1-wb-woher-tr-de',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.herkunft.woher'],
    familyId: 'p1-alt-woher',
    instruction: 'Türkçeden Almancaya kur — Nerelisin?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Nerelisin?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Woher' }, { id: 't2', text: 'kommst' }, { id: 't3', text: 'du?' },
        { id: 't4', text: 'Wo' }, { id: 't5', text: 'wohnst' }, { id: 't6', text: 'heißt' },
      ],
      acceptedSequences: [['Woher', 'kommst', 'du?']],
    },
    answer: 'Woher kommst du?',
    pronounce: ['Woher kommst du?'],
  },
  {
    id: 'p1-wb-wo-wohnst-tr-de',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.wohnort.wo-wohnst'],
    familyId: 'p1-alt-wo-wohnst',
    instruction: 'Türkçeden Almancaya kur — Nerede yaşıyorsun?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Nerede yaşıyorsun?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Wo' }, { id: 't2', text: 'wohnst' }, { id: 't3', text: 'du?' },
        { id: 't4', text: 'Woher' }, { id: 't5', text: 'kommst' },
      ],
      acceptedSequences: [['Wo', 'wohnst', 'du?']],
    },
    answer: 'Wo wohnst du?',
    pronounce: ['Wo wohnst du?'],
  },
  {
    id: 'p1-order-wohne-in-sakarya',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.wohnort.in'],
    familyId: 'p1-alt-in',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / wohne / in / Sakarya.',
    answer: 'Ich wohne in Sakarya.',
    words: ['Ich', 'wohne', 'in', 'Sakarya'],
    pronounce: ['Ich wohne in Sakarya.'],
  },
  {
    id: 'p1-order-komme-aus-tuerkei',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.herkunft.aus'],
    familyId: 'p1-alt-aus',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / komme / aus / der / Türkei.',
    answer: 'Ich komme aus der Türkei.',
    words: ['Ich', 'komme', 'aus', 'der', 'Türkei'],
    pronounce: ['Ich komme aus der Türkei.'],
  },
  {
    id: 'p1-spoken-herkunft-wohnort',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['personal-info.herkunft.woher', 'personal-info.wohnort.wo-wohnst'],
    familyId: 'p1-spoken-herkunft',
    instruction: 'Sesli görev: köken ve ikamet söyle.',
    requirements: ['Ich komme aus ...', 'Ich wohne in ...'],
    sampleAnswer: 'Ich komme aus der Türkei. Ich wohne in Sakarya.',
    pronounce: ['Ich komme aus der Türkei.', 'Ich wohne in Sakarya.'],
  },
  {
    id: 'p1-listen-wie-alt',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.alter.wie-alt'],
    familyId: 'p1-listen-alt',
    instruction: 'Duyduğunu seç:',
    prompt: 'Wie alt bist du?',
    audioText: 'Wie alt bist du?',
    answer: 'Wie alt bist du?',
    options: ['Wie alt bist du?', 'Wo wohnst du?', 'Wie heißt du?', 'Was machst du beruflich?'],
    audio: { prompt: { text: 'Wie alt bist du?', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Memleket, Doğum Yeri ve İkamet (13) ---- */
  {
    id: 'p5-dy-geboren-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.dogum.soru-cevap'],
    familyId: 'p5-dy-geboren',
    instruction: '"geboren" ne demektir?',
    prompt: 'geboren',
    answer: 'doğmuş',
    options: ['doğmuş', 'yaşayan', 'oturan', 'gelen'],
    pronounce: ['geboren'],
  },
  {
    id: 'p5-dy-wo-bist-du-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['personal-info.dogum.soru-cevap'],
    familyId: 'p5-dy-wo-bist-du',
    instruction: 'Boşluğu doldur:',
    prompt: '___ bist du geboren? (Nerede doğdun?)',
    answer: 'Wo',
    pronounce: ['Wo bist du geboren?'],
  },
  {
    id: 'p5-dy-wo-sind-sie-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.dogum.soru-cevap'],
    familyId: 'p5-dy-formal',
    instruction: '"Wo sind Sie geboren?" hangi hitap şeklidir?',
    prompt: 'Wo sind Sie geboren?',
    answer: 'resmî',
    options: ['resmî', 'samimi', 'çoğul-gündelik', 'soru değil'],
    pronounce: ['Wo sind Sie geboren?'],
  },
  {
    id: 'p5-dy-ich-bin-in-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.dogum.soru-cevap'],
    familyId: 'p5-dy-ich-bin-in',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich bin in Sakarya ___. (Sakarya\'da doğdum)',
    answer: 'geboren',
    pronounce: ['Ich bin in Sakarya geboren.'],
  },
  {
    id: 'p5-dy-contrast-woher-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.dogum.aciklik'],
    familyId: 'p5-dy-contrast-woher',
    instruction: '"Woher kommst du?" ne sorar?',
    prompt: 'Woher kommst du?',
    answer: 'köken / nereli olduğun',
    options: ['köken / nereli olduğun', 'doğum yerin', 'şu anki ikametin', 'adın'],
  },
  {
    id: 'p5-dy-contrast-geboren-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.dogum.aciklik'],
    familyId: 'p5-dy-contrast-geboren',
    instruction: '"Wo bist du geboren?" ne sorar?',
    prompt: 'Wo bist du geboren?',
    answer: 'doğum yerin',
    options: ['doğum yerin', 'köken', 'şu anki ikametin', 'mesleğin'],
  },
  {
    id: 'p5-dy-matching-questions',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.dogum.aciklik'],
    familyId: 'p5-dy-matching',
    instruction: 'Soruları hangi bilgiyi istediğiyle eşleştir.',
    pairs: [
      { left: 'Woher kommst du?', right: 'köken' },
      { left: 'Wo bist du geboren?', right: 'doğum yeri' },
      { left: 'Wo wohnst du?', right: 'ikamet' },
    ],
    pronounce: ['Woher kommst du?', 'Wo bist du geboren?', 'Wo wohnst du?'],
  },
  {
    id: 'p5-dy-profile-interpret-geboren-free',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.dogum.aciklik'],
    familyId: 'p5-dy-profile-emre',
    instruction: 'Profil: Vorname: Emre / Geburtsort: Ankara / Wohnort: Berlin.\nSoru: Wo ist Emre geboren?',
    prompt: 'Wo ist Emre geboren?',
    answer: 'Emre ist in Ankara geboren.',
    pronounce: ['Emre ist in Ankara geboren.'],
  },
  {
    id: 'p5-dy-profile-interpret-wohnt-free',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.dogum.aciklik'],
    familyId: 'p5-dy-profile-emre',
    instruction: 'Profil: Vorname: Emre / Geburtsort: Ankara / Wohnort: Berlin.\nSoru: Wo wohnt Emre?',
    prompt: 'Wo wohnt Emre?',
    answer: 'Emre wohnt in Berlin.',
    pronounce: ['Emre wohnt in Berlin.'],
  },
  {
    id: 'p5-dy-mini-interview-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.dogum.soru-cevap'],
    familyId: 'p5-dy-mini-interview',
    instruction: 'Mini diyalog: B ne demeli?',
    prompt: 'A: Wo bist du geboren?\nB: ______',
    answer: 'Ich bin in Izmir geboren.',
    options: ['Ich bin in Izmir geboren.', 'Ich heiße Izmir.', 'Izmir ist schön.', 'Ich wohne Izmir.'],
    pronounce: ['Ich bin in Izmir geboren.'],
  },
  {
    id: 'p5-dy-error-geboren',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['personal-info.dogum.aciklik'],
    familyId: 'p5-dy-error',
    instruction: 'Hata avı:',
    prompt: 'Ich bin in Sakarya wohnen.',
    answer: 'Ich bin in Sakarya geboren.',
    explanation: '"geboren" sabit olarak `sein` ile kullanılır; `wohnen` ayrı bir fiildir ve bu kalıpta kullanılmaz.',
    pronounce: ['Ich bin in Sakarya geboren.'],
  },
  {
    id: 'p5-dy-wb-geboren-tr-de',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.dogum.soru-cevap'],
    familyId: 'p5-dy-wb-geboren',
    instruction: 'Türkçeden Almancaya kur — Ben Sakarya\'da doğdum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ben Sakarya\'da doğdum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'bin' }, { id: 't3', text: 'in' }, { id: 't4', text: 'Sakarya' }, { id: 't5', text: 'geboren.' },
        { id: 't6', text: 'wohne' }, { id: 't7', text: 'komme' },
      ],
      acceptedSequences: [['Ich', 'bin', 'in', 'Sakarya', 'geboren.']],
    },
    answer: 'Ich bin in Sakarya geboren.',
    pronounce: ['Ich bin in Sakarya geboren.'],
  },
  {
    id: 'p5-dy-spoken-sorular',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['personal-info.dogum.aciklik'],
    familyId: 'p5-dy-spoken',
    instruction: 'Sesli görev: Woher kommst du?, Wo bist du geboren? ve Wo wohnst du? sorularını kendi bilgilerinle cevapla.',
    requirements: ['Ich komme aus ...', 'Ich bin in ... geboren.', 'Ich wohne in ...'],
    sampleAnswer: 'Ich komme aus Sakarya. Ich bin in Sakarya geboren. Ich wohne in Istanbul.',
    pronounce: ['Ich komme aus Sakarya.', 'Ich bin in Sakarya geboren.', 'Ich wohne in Istanbul.'],
  },

  /* ---- leben — Yaşamak (12) ---- */
  {
    id: 'p5-leb-anlam-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.leben.anlam'],
    familyId: 'p5-leb-anlam',
    instruction: '"leben" ne demektir?',
    prompt: 'leben',
    answer: 'yaşamak',
    options: ['yaşamak', 'gitmek', 'gelmek', 'çalışmak'],
    pronounce: ['leben'],
  },
  {
    id: 'p5-leb-ich-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.leben.cekim'],
    familyId: 'p5-leb-ich',
    instruction: 'leben çekimi — doğru formu seç:',
    prompt: 'ich ___ (leben)',
    answer: 'lebe',
    options: ['lebe', 'lebst', 'lebt', 'leben'],
    pronounce: ['ich lebe'],
  },
  {
    id: 'p5-leb-du-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['personal-info.leben.cekim'],
    familyId: 'p5-leb-du',
    instruction: 'leben çekimi:',
    prompt: 'du ___ (leben)',
    answer: 'lebst',
    pronounce: ['du lebst'],
  },
  {
    id: 'p5-leb-er-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['personal-info.leben.cekim'],
    familyId: 'p5-leb-er',
    instruction: 'leben çekimi:',
    prompt: 'er / sie / es ___ (leben)',
    answer: 'lebt',
    pronounce: ['er lebt'],
  },
  {
    id: 'p5-leb-wir-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.leben.cekim'],
    familyId: 'p5-leb-wir',
    instruction: 'leben çekimi — doğru formu seç:',
    prompt: 'wir ___ (leben)',
    answer: 'leben',
    options: ['leben', 'lebt', 'lebst', 'lebe'],
    pronounce: ['wir leben'],
  },
  {
    id: 'p5-leb-ihr-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.leben.cekim'],
    familyId: 'p5-leb-ihr',
    instruction: 'leben çekimi:',
    prompt: 'ihr ___ (leben)',
    answer: 'lebt',
    pronounce: ['ihr lebt'],
  },
  {
    id: 'p5-leb-sie-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.leben.cekim'],
    familyId: 'p5-leb-sie',
    instruction: 'leben çekimi — doğru formu seç:',
    prompt: 'sie / Sie ___ (leben)',
    answer: 'leben',
    options: ['leben', 'lebt', 'lebst', 'lebe'],
    pronounce: ['sie leben'],
  },
  {
    id: 'p5-leb-deutschland-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.leben.wohnen-farki'],
    familyId: 'p5-leb-deutschland',
    instruction: 'Boşluğu doldur (genel yaşam — leben):',
    prompt: 'Ich ___ in Deutschland. (Almanya\'da yaşıyorum)',
    answer: 'lebe',
    pronounce: ['Ich lebe in Deutschland.'],
  },
  {
    id: 'p5-leb-berlin-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.leben.wohnen-farki'],
    familyId: 'p5-leb-berlin',
    instruction: 'Boşluğu doldur (somut ikamet — wohnen):',
    prompt: 'Ich ___ in Berlin. (Berlin\'de oturuyorum)',
    answer: 'wohne',
    pronounce: ['Ich wohne in Berlin.'],
  },
  {
    id: 'p5-leb-farki-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.leben.wohnen-farki'],
    familyId: 'p5-leb-farki',
    instruction: '"leben" ile "wohnen" arasındaki pratik fark nedir?',
    prompt: 'leben ↔ wohnen',
    answer: 'leben genel yaşamı, wohnen somut ikameti (adres/şehir) anlatır',
    options: [
      'leben genel yaşamı, wohnen somut ikameti (adres/şehir) anlatır',
      'İkisi de tamamen farklı anlama gelir, hiç ilgileri yoktur',
      'leben sadece geçmiş zamanda kullanılır',
      'wohnen sadece ülkeler için kullanılır',
    ],
  },
  {
    id: 'p5-leb-error-lebst',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['personal-info.leben.cekim'],
    familyId: 'p5-leb-error',
    instruction: 'Hata avı — çekim yanlış:',
    prompt: 'Ich lebst in der Türkei.',
    answer: 'Ich lebe in der Türkei.',
    explanation: '"ich" ile fiil `-e` eki alır (ich lebe); `-st` eki "du" için kullanılır.',
    pronounce: ['Ich lebe in der Türkei.'],
  },
  {
    id: 'p5-leb-listen-deutschland',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.leben.wohnen-farki'],
    familyId: 'p5-leb-listen',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich lebe in Deutschland.',
    audioText: 'Ich lebe in Deutschland.',
    answer: 'Ich lebe in Deutschland.',
    options: [
      'Ich lebe in Deutschland.',
      'Ich wohne in Berlin.',
      'Ich komme aus Deutschland.',
      'Ich bin in Deutschland geboren.',
    ],
    audio: { prompt: { text: 'Ich lebe in Deutschland.', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Meslek — Ne İş Yapıyorsun? (9) ---- */
  {
    id: 'p1-ber-frage-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.beruf.frage'],
    familyId: 'p1-ber-frage',
    instruction: 'Meslek sormanın yaygın yolu:',
    prompt: 'Was machst du beruflich?',
    answer: 'Mesleğin ne?',
    options: ['Mesleğin ne?', 'Nerede yaşıyorsun?', 'Kaç yaşındasın?', 'Adın ne?'],
    pronounce: ['Was machst du beruflich?'],
  },
  {
    id: 'p1-ber-was-bist-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.beruf.frage'],
    familyId: 'p1-ber-frage',
    instruction: 'Meslek sorusunu tamamla:',
    prompt: 'Was _____ du von Beruf? (sein)',
    answer: 'bist',
    pronounce: ['Was bist du von Beruf?'],
  },
  {
    id: 'p1-ber-bin-student-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.beruf.antwort-bin'],
    familyId: 'p1-ber-student',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich _____ Student. (sein)',
    answer: 'bin',
    pronounce: ['Ich bin Student.'],
  },
  {
    id: 'p1-ber-als-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.beruf.als-bei'],
    familyId: 'p1-ber-als',
    instruction: 'Doğru edatı yaz:',
    prompt: 'Ich arbeite _____ Lehrerin.',
    answer: 'als',
    pronounce: ['Ich arbeite als Lehrerin.'],
  },
  {
    id: 'p1-ber-bei-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.beruf.als-bei'],
    familyId: 'p1-ber-bei',
    instruction: 'Doğru edatı yaz:',
    prompt: 'Ich arbeite _____ Toyota.',
    answer: 'bei',
    pronounce: ['Ich arbeite bei Toyota.'],
  },
  {
    id: 'p1-beruf-matching',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.beruf.als-bei', 'personal-info.beruf.antwort-bin'],
    familyId: 'p1-ber-match',
    instruction: 'Meslek kalıplarını eşleştir.',
    pairs: [
      { left: 'Ich bin Student.', right: 'Ben öğrenciyim.' },
      { left: 'Ich arbeite als Lehrerin.', right: 'Öğretmen olarak çalışıyorum.' },
      { left: 'Ich arbeite bei Toyota.', right: 'Toyota\'da çalışıyorum.' },
    ],
    pronounce: ['Ich bin Student.', 'Ich arbeite als Lehrerin.', 'Ich arbeite bei Toyota.'],
  },
  {
    id: 'p1-beruf-produktion-free',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.beruf.als-bei'],
    familyId: 'p1-ber-als',
    instruction: 'Toyota\'da çalıştığını tek cümlede söyle.',
    prompt: 'Toyota\'da çalışıyorum → ______',
    answer: 'Ich arbeite bei Toyota.',
    acceptedAnswers: ['Ich arbeite bei Toyota'],
    pronounce: ['Ich arbeite bei Toyota.'],
  },
  {
    id: 'p1-wb-beruf-de',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.beruf.frage'],
    familyId: 'p1-ber-frage',
    instruction: 'Türkçeden Almancaya kur — Mesleğin ne?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Mesleğin ne?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Was' }, { id: 't2', text: 'machst' }, { id: 't3', text: 'du' }, { id: 't4', text: 'beruflich?' },
        { id: 't5', text: 'Wie' }, { id: 't6', text: 'alt' },
      ],
      acceptedSequences: [['Was', 'machst', 'du', 'beruflich?']],
    },
    answer: 'Was machst du beruflich?',
    pronounce: ['Was machst du beruflich?'],
  },
  {
    id: 'p1-extra-beruf-was-machen-sie',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.beruf.frage'],
    familyId: 'p1-ber-frage',
    instruction: 'Resmî meslek sorusunu yaz:',
    prompt: 'Mesleğiniz ne? → ______',
    answer: 'Was machen Sie beruflich?',
    pronounce: ['Was machen Sie beruflich?'],
  },

  /* ---- İletişim — E-posta ve Telefon (17) ---- */
  {
    id: 'p1-kontakt-email-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.kontakt.email'],
    familyId: 'p1-kontakt-email',
    instruction: 'E-posta sorusu (samimi):',
    prompt: 'Wie ist deine E-Mail-Adresse?',
    answer: 'Mailin ne?',
    options: ['Mailin ne?', 'Telefonun ne?', 'Adın ne?', 'Nerede yaşıyorsun?'],
    pronounce: ['Wie ist deine E-Mail-Adresse?'],
  },
  {
    id: 'p1-kontakt-punkt-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.kontakt.punkt'],
    familyId: 'p1-kontakt-punkt',
    instruction: 'E-postadaki nokta nasıl okunur?',
    prompt: 'mustafa@gmail.com',
    answer: 'Punkt',
    options: ['Punkt', 'Komma', 'Strich', 'At'],
    pronounce: ['Punkt'],
  },
  {
    id: 'p1-kontakt-telefon-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.kontakt.telefon'],
    familyId: 'p1-kontakt-telefon',
    instruction: 'Telefon sorusu (samimi):',
    prompt: 'Wie ist deine Telefonnummer?',
    answer: 'Telefonun ne?',
    options: ['Telefonun ne?', 'Mailin ne?', 'Adın ne?', 'Mesleğin ne?'],
    pronounce: ['Wie ist deine Telefonnummer?'],
  },
  {
    id: 'p1-form-vorname-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.formular.felder'],
    familyId: 'p1-form-vorname',
    instruction: 'Form alanı nedir?',
    prompt: 'Vorname',
    answer: 'ad',
    options: ['ad', 'soyad', 'adres', 'meslek'],
    pronounce: ['Vorname'],
  },
  {
    id: 'p1-form-nachname-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.formular.felder'],
    familyId: 'p1-form-nachname',
    instruction: 'Form alanı nedir?',
    prompt: 'Familienname / Nachname',
    answer: 'soyad',
    options: ['soyad', 'ad', 'meslek', 'ikamet yeri'],
    pronounce: ['Familienname'],
  },
  {
    id: 'p1-form-familienstand-mc',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.formular.familienstand'],
    familyId: 'p1-form-stand',
    instruction: 'Form alanı nedir?',
    prompt: 'Familienstand',
    answer: 'medeni hâl',
    options: ['medeni hâl', 'meslek', 'çocuklar', 'memleket'],
    pronounce: ['Familienstand'],
  },
  {
    id: 'p1-kontakt-email-adresse-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.kontakt.email'],
    familyId: 'p1-kontakt-email',
    instruction: 'Soruyu tamamla — "Mailin ne?" sorusunun Almancası:',
    prompt: 'Wie ist deine _____ ?',
    answer: 'E-Mail-Adresse',
    acceptedAnswers: ['Wie ist deine E-Mail-Adresse?', 'Wie ist deine E-Mail-Adresse', 'wie ist deine e-mail-adresse', 'wie ist deine e-mail-adresse?'],
    validation: { caseSensitive: false },
    pronounce: ['Wie ist deine E-Mail-Adresse?'],
  },
  {
    id: 'p1-kontakt-telefon-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.kontakt.telefon'],
    familyId: 'p1-kontakt-telefon',
    instruction: 'Soruyu tamamla — "Telefonun ne?" sorusunun Almancası:',
    prompt: 'Wie ist deine _____ ?',
    answer: 'Telefonnummer',
    acceptedAnswers: ['Wie ist deine Telefonnummer?', 'Wie ist deine Telefonnummer', 'wie ist deine telefonnummer', 'wie ist deine telefonnummer?'],
    validation: { caseSensitive: false },
    pronounce: ['Wie ist deine Telefonnummer?'],
  },
  {
    id: 'p1-form-vorname-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.formular.felder'],
    familyId: 'p1-form-vorname',
    instruction: 'Formu doldur — adın Mustafa:',
    prompt: 'Vorname: ______',
    answer: 'Mustafa',
    pronounce: ['Vorname'],
  },
  {
    id: 'p1-form-wohnort-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.formular.felder'],
    familyId: 'p1-form-wohnort',
    instruction: 'Formu doldur — Sakarya\'da yaşıyorsun:',
    prompt: 'Wohnort: ______',
    answer: 'Sakarya',
    pronounce: ['Wohnort'],
  },
  {
    id: 'p1-form-familienstand-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.formular.familienstand'],
    familyId: 'p1-form-stand',
    instruction: 'Formu doldur — bekârsın:',
    prompt: 'Familienstand → ______',
    answer: 'ledig',
    pronounce: ['ledig'],
  },
  {
    id: 'p1-form-kinder-fill',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.formular.kinder'],
    familyId: 'p1-form-kinder',
    instruction: 'Formu doldur — çocuğun yok, tam cümle yaz:',
    prompt: 'Kinder: ______',
    answer: 'Ich habe keine Kinder.',
    pronounce: ['Ich habe keine Kinder.'],
  },
  {
    id: 'p1-form-matching',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.formular.felder', 'personal-info.formular.heimat'],
    familyId: 'p1-form-match',
    instruction: 'Form alanlarını anlamlarıyla eşleştir.',
    pairs: [
      { left: 'Vorname', right: 'ad' },
      { left: 'Nachname', right: 'soyad' },
      { left: 'Wohnort', right: 'ikamet yeri' },
      { left: 'Heimat', right: 'memleket' },
    ],
    pronounce: ['Vorname', 'Nachname', 'Wohnort', 'Heimat'],
  },
  {
    id: 'p1-hata-mein-telefon',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['personal-info.kontakt.antwort-telefon'],
    familyId: 'p1-kontakt-telefon',
    instruction: 'Hata avı — doğru artikel hangisi?',
    prompt: 'Mein Telefonnummer ist 0532...',
    answer: 'Meine Telefonnummer ist 0532...',
    explanation: 'Telefonnummer dişil: die Telefonnummer → meine.',
    pronounce: ['Meine Telefonnummer ist 05325540710.'],
  },
  {
    id: 'p1-form-complete-free',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.formular.felder', 'personal-info.formular.familienstand', 'personal-info.formular.kinder'],
    familyId: 'p1-form-vorname',
    instruction: 'Formu tamamla — Familienstand alanına ne yazarsın? (bekâr)',
    prompt: 'Familienstand: ______',
    answer: 'ledig',
    pronounce: ['ledig'],
  },
  {
    id: 'p1-wb-email-de-tr',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.kontakt.email'],
    familyId: 'p1-kontakt-email',
    instruction: 'Almancadan Türkçeye çevir — Mailin ne?',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Wie ist deine E-Mail-Adresse?',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Mailin' }, { id: 't2', text: 'ne?' }, { id: 't3', text: 'Telefonun' }, { id: 't4', text: 'Adın' },
      ],
      acceptedSequences: [['Mailin', 'ne?']],
    },
    answer: 'Mailin ne?',
    audio: { prompt: { text: 'Wie ist deine E-Mail-Adresse?', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Wie ist deine E-Mail-Adresse?'],
  },
  {
    id: 'p1-dictation-telefon',
    topicId: T.personalInfo, legacyDay: 1,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.kontakt.antwort-telefon'],
    familyId: 'p1-kontakt-telefon',
    instruction: 'Telefon numaranı duydun — aynen yaz:',
    audioText: 'Meine Telefonnummer ist 05325540710.',
    answer: 'Meine Telefonnummer ist 05325540710.',
    audio: { prompt: { text: 'Meine Telefonnummer ist 05325540710.', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Form Alanları (10) ---- */
  {
    id: 'p5-kb-familienname-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.form.alanlar'],
    familyId: 'p5-kb-familienname',
    instruction: '"der Familienname" ne demektir?',
    prompt: 'der Familienname',
    answer: 'soyadı',
    options: ['soyadı', 'ad', 'doğum yeri', 'telefon numarası'],
    pronounce: ['der Familienname'],
  },
  {
    id: 'p5-kb-vorname-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['personal-info.form.alanlar'],
    familyId: 'p5-kb-vorname',
    instruction: 'Boşluğu doldur (ad/isim alanı):',
    prompt: 'der ___ = ad, isim',
    answer: 'Vorname',
    pronounce: ['der Vorname'],
  },
  {
    id: 'p5-kb-heimatland-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.form.alanlar'],
    familyId: 'p5-kb-heimatland',
    instruction: '"das Heimatland" ne demektir?',
    prompt: 'das Heimatland',
    answer: 'memleket / anavatan',
    options: ['memleket / anavatan', 'doğum yeri', 'cadde', 'telefon numarası'],
    pronounce: ['das Heimatland'],
  },
  {
    id: 'p5-kb-strasse-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.form.alanlar'],
    familyId: 'p5-kb-strasse',
    instruction: 'Boşluğu doldur (cadde/sokak alanı):',
    prompt: 'die ___ = cadde / sokak',
    answer: 'Straße',
    validation: { keyboardTolerance: true },
    pronounce: ['die Straße'],
  },
  {
    id: 'p5-kb-telefonnummer-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['personal-info.form.alanlar'],
    familyId: 'p5-kb-telefonnummer',
    instruction: 'Boşluğu doldur (telefon numarası alanı):',
    prompt: 'die ___ = telefon numarası',
    answer: 'Telefonnummer',
    pronounce: ['die Telefonnummer'],
  },
  {
    id: 'p5-kb-wohnort-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.form.alanlar'],
    familyId: 'p5-kb-wohnort',
    instruction: '"der Wohnort" ne demektir?',
    prompt: 'der Wohnort',
    answer: 'ikamet yeri',
    options: ['ikamet yeri', 'doğum yeri', 'soyadı', 'medeni hal'],
    pronounce: ['der Wohnort'],
  },
  {
    id: 'p5-kb-matching-fields',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.form.alanlar'],
    familyId: 'p5-kb-matching',
    instruction: 'Form alanlarını Türkçesiyle eşleştir.',
    pairs: [
      { left: 'der Familienname', right: 'soyadı' },
      { left: 'der Vorname', right: 'ad' },
      { left: 'das Heimatland', right: 'memleket' },
      { left: 'der Geburtsort', right: 'doğum yeri' },
      { left: 'die Straße', right: 'cadde / sokak' },
      { left: 'der Wohnort', right: 'ikamet yeri' },
      { left: 'die Telefonnummer', right: 'telefon numarası' },
      { left: 'der Familienstand', right: 'medeni hal' },
    ],
    pronounce: ['der Familienname', 'der Vorname', 'das Heimatland', 'der Geburtsort', 'die Straße', 'der Wohnort', 'die Telefonnummer', 'der Familienstand'],
  },
  {
    id: 'p5-kb-field-to-question-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['personal-info.form.alanlar'],
    familyId: 'p5-kb-field-question',
    instruction: '"Wohnort" alanına karşılık gelen soru hangisidir?',
    prompt: 'Wohnort',
    answer: 'Wo wohnst du?',
    options: ['Wo wohnst du?', 'Wie heißt du?', 'Wie alt bist du?', 'Was machst du beruflich?'],
    pronounce: ['Wo wohnst du?'],
  },
  {
    id: 'p5-kb-question-to-field-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['personal-info.form.alanlar', 'personal-info.dogum.soru-cevap'],
    familyId: 'p5-kb-question-field',
    instruction: '"Wo bist du geboren?" hangi form alanına karşılık gelir?',
    prompt: 'Wo bist du geboren?',
    answer: 'Geburtsort',
    options: ['Geburtsort', 'Wohnort', 'Familienname', 'Telefonnummer'],
  },
  {
    id: 'p5-kb-kinder-fill',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['personal-info.form.kinder'],
    familyId: 'p5-kb-kinder',
    instruction: 'Boşluğu doldur (form alanından hatırla):',
    prompt: 'Ich habe keine ___. (hiç çocuğum yok)',
    answer: 'Kinder',
    pronounce: ['Ich habe keine Kinder.'],
  },

  /* ---- Familienstand — ledig / verheiratet (6) ---- */
  {
    id: 'p5-mh-ledig-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-ledig',
    instruction: '"ledig" ne demektir?',
    prompt: 'ledig',
    answer: 'bekar',
    options: ['bekar', 'evli', 'boşanmış', 'dul'],
    pronounce: ['ledig'],
  },
  {
    id: 'p5-mh-verheiratet-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-verheiratet',
    instruction: '"verheiratet" ne demektir?',
    prompt: 'verheiratet',
    answer: 'evli',
    options: ['evli', 'bekar', 'çocuklu', 'yaşlı'],
    pronounce: ['verheiratet'],
  },
  {
    id: 'p5-mh-fill-ledig',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-fill-ledig',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich bin ___. (Bekarım.)',
    answer: 'ledig',
    pronounce: ['Ich bin ledig.'],
  },
  {
    id: 'p5-mh-fill-verheiratet',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-fill-verheiratet',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich bin ___. (Evliyim.)',
    answer: 'verheiratet',
    pronounce: ['Ich bin verheiratet.'],
  },
  {
    id: 'p5-mh-matching',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-matching',
    instruction: 'Eşleştir.',
    pairs: [
      { left: 'ledig', right: 'bekar' },
      { left: 'verheiratet', right: 'evli' },
    ],
    pronounce: ['ledig', 'verheiratet'],
  },
  {
    id: 'p5-mh-listen',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.medeni-hal.ledig-verheiratet'],
    familyId: 'p5-mh-listen',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich bin verheiratet.',
    audioText: 'Ich bin verheiratet.',
    answer: 'Ich bin verheiratet.',
    options: ['Ich bin verheiratet.', 'Ich bin ledig.', 'Ich habe keine Kinder.', 'Ich bin Student.'],
    audio: { prompt: { text: 'Ich bin verheiratet.', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Kendini Ayrıntılı Tanıtma (11) ---- */
  {
    id: 'p5-kt-model-order',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.tanitma.model'],
    familyId: 'p5-kt-order-alt',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / bin / achtzehn / Jahre / alt.',
    answer: 'Ich bin achtzehn Jahre alt.',
    words: ['Ich', 'bin', 'achtzehn', 'Jahre', 'alt'],
    pronounce: ['Ich bin achtzehn Jahre alt.'],
  },
  {
    id: 'p5-kt-model-order2',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['personal-info.tanitma.ornekler'],
    familyId: 'p5-kt-order-und',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / komme / aus / Sakarya / und / ich / wohne / in / Istanbul.',
    answer: 'Ich komme aus Sakarya und ich wohne in Istanbul.',
    words: ['Ich', 'komme', 'aus', 'Sakarya', 'und', 'ich', 'wohne', 'in', 'Istanbul'],
    pronounce: ['Ich komme aus Sakarya und ich wohne in Istanbul.'],
  },
  {
    id: 'p5-kt-mustafa-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.tanitma.ornekler'],
    familyId: 'p5-kt-mustafa',
    instruction: 'Örnek 1\'i oku: "Hallo! Ich bin Mustafa. Ich komme aus Sakarya. Ich bin in Sakarya geboren. Ich bin achtzehn Jahre alt. Ich bin Student."\nMustafa kaç yaşındadır?',
    prompt: 'Mustafa kaç yaşındadır?',
    answer: '18',
    options: ['18', '25', '15', '20'],
  },
  {
    id: 'p5-kt-nazar-herkunft-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['personal-info.tanitma.ornekler'],
    familyId: 'p5-kt-nazar-herkunft',
    instruction: 'Örnek 2\'yi oku: "Ich heiße Nazar. Ich bin 25 Jahre alt. Ich komme aus Istanbul und ich wohne in Istanbul. Ich bin in Istanbul geboren."\nNazar nereli?',
    prompt: 'Nazar nereli?',
    answer: 'Istanbul',
    options: ['Istanbul', 'Sakarya', 'Ankara', 'Izmir'],
  },
  {
    id: 'p5-kt-nazar-geboren-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.tanitma.ornekler'],
    familyId: 'p5-kt-nazar-geboren',
    instruction: 'Aynı örnekte: Nazar nerede doğdu?',
    prompt: 'Nazar nerede doğdu?',
    answer: 'Istanbul',
    options: ['Istanbul', 'Sakarya', 'Ankara', 'Izmir'],
  },
  {
    id: 'p5-kt-wohnen-leben-mc',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['personal-info.tanitma.model'],
    familyId: 'p5-kt-wohnen-leben',
    instruction: '"Ich wohne in Istanbul und ich bin in Istanbul geboren." cümlesinde ne anlatılıyor?',
    prompt: 'Ich wohne in Istanbul und ich bin in Istanbul geboren.',
    answer: 'Doğum yeri ve ikamet aynı şehir; köken hakkında bilgi verilmiyor',
    options: [
      'Doğum yeri ve ikamet aynı şehir; köken hakkında bilgi verilmiyor',
      'Sadece köken bilgisi veriliyor',
      'Sadece isim veriliyor',
      'Sadece yaş veriliyor',
    ],
  },
  {
    id: 'p5-kt-error',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['personal-info.tanitma.model'],
    familyId: 'p5-kt-error',
    instruction: 'Hata avı — cümleler ayrılmalı/bağlanmalı:',
    prompt: 'Ich heiße Nazar, Ich bin 25 Jahre alt komme aus Istanbul.',
    answer: 'Ich heiße Nazar. Ich bin 25 Jahre alt. Ich komme aus Istanbul.',
    explanation: 'Her cümlenin kendi öznesi ve fiili olmalı; cümleler nokta ile ayrılır ya da `und` ile açıkça bağlanır.',
    pronounce: ['Ich heiße Nazar.', 'Ich bin 25 Jahre alt.', 'Ich komme aus Istanbul.'],
  },
  {
    id: 'p5-kt-wb-selfintro-tr-de',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.tanitma.model'],
    familyId: 'p5-kt-wb-selfintro',
    instruction: 'Türkçeden Almancaya kur — Merhaba! Sakarya\'dan geliyorum ve Sakarya\'da doğdum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Merhaba! Sakarya\'dan geliyorum ve Sakarya\'da doğdum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Hallo!' }, { id: 't2', text: 'Ich' }, { id: 't3', text: 'komme' }, { id: 't4', text: 'aus' }, { id: 't5', text: 'Sakarya' },
        { id: 't6', text: 'und' }, { id: 't7', text: 'ich' }, { id: 't8', text: 'bin' }, { id: 't9', text: 'in' }, { id: 't10', text: 'geboren.' },
        { id: 't11', text: 'Sakarya' }, { id: 't12', text: 'wohne' },
      ],
      acceptedSequences: [['Hallo!', 'Ich', 'komme', 'aus', 'Sakarya', 'und', 'ich', 'bin', 'in', 'Sakarya', 'geboren.']],
    },
    answer: 'Hallo! Ich komme aus Sakarya und ich bin in Sakarya geboren.',
    pronounce: ['Hallo! Ich komme aus Sakarya und ich bin in Sakarya geboren.'],
  },
  {
    id: 'p5-kt-spoken-tanitim',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['personal-info.tanitma.model'],
    familyId: 'p5-kt-spoken',
    instruction: 'Sesli görev: Kendini ayrıntılı tanıt — adını, yaşını, memleketini, doğum yerini ve ikametini söyle.',
    requirements: ['Ich heiße ...', 'Ich bin ... Jahre alt.', 'Ich komme aus ...', 'Ich bin in ... geboren.', 'Ich wohne in ...'],
    sampleAnswer: 'Ich heiße Mustafa. Ich bin achtzehn Jahre alt. Ich komme aus Sakarya. Ich bin in Sakarya geboren. Ich wohne in Istanbul.',
    pronounce: ['Ich heiße Mustafa.', 'Ich bin achtzehn Jahre alt.', 'Ich komme aus Sakarya.', 'Ich bin in Sakarya geboren.', 'Ich wohne in Istanbul.'],
  },
  {
    id: 'p5-kt-profile-builder-spoken',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'spoken', difficulty: 'hard', skill: 'speaking',
    conceptIds: ['personal-info.tanitma.model', 'personal-info.dogum.aciklik'],
    familyId: 'p5-kt-profile-builder',
    instruction: 'Sesli görev: Lena adlı kurgusal kişiyi tanıt (21 yaşında, Almanya\'dan, München\'de doğdu, Berlin\'de yaşıyor).',
    requirements: ['Sie heißt ...', 'Sie ist ... Jahre alt.', 'Sie kommt aus ...', 'Sie ist in ... geboren.', 'Sie wohnt in ...'],
    sampleAnswer: 'Sie heißt Lena. Sie ist 21 Jahre alt. Sie kommt aus Deutschland. Sie ist in München geboren. Sie wohnt in Berlin.',
    pronounce: ['Sie heißt Lena.', 'Sie ist 21 Jahre alt.', 'Sie kommt aus Deutschland.', 'Sie ist in München geboren.', 'Sie wohnt in Berlin.'],
  },
  {
    id: 'p5-kt-dictation',
    topicId: T.personalInfo, legacyDay: 5,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['personal-info.tanitma.model'],
    familyId: 'p5-kt-order-alt',
    instruction: 'Kendini tanıtma cümlesini duydun — aynen yaz:',
    audioText: 'Ich bin achtzehn Jahre alt.',
    answer: 'Ich bin achtzehn Jahre alt.',
    audio: { prompt: { text: 'Ich bin achtzehn Jahre alt.', language: 'de-DE', role: 'prompt' } },
  },
];
