/**
 * Yer ve Yön — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const PLACES_EXERCISES: AuthoredExercise[] = [
  /* ---- Yer, Yön ve Küçük Ama Önemli Kelimeler (32) ---- */
  {
    id: 'p3-yy-zum-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['places.kontraksiyon.zum'],
    familyId: 'p3-yy-zum',
    instruction: '"zum" hangi iki kelimenin birleşimidir?',
    prompt: 'zum',
    answer: 'zu + dem',
    options: ['zu + dem', 'zu + der', 'in + dem', 'an + dem'],
  },
  {
    id: 'p3-yy-zum-markt-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['places.kontraksiyon.zum'],
    familyId: 'p3-yy-zum-markt',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Mutter geht ___ Markt. (annem markete gidiyor)',
    answer: 'zum',
    pronounce: ['Meine Mutter geht zum Markt.'],
  },
  {
    id: 'p3-yy-zur-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['places.kontraksiyon.zur'],
    familyId: 'p3-yy-zur',
    instruction: '"zur" hangi iki kelimenin birleşimidir?',
    prompt: 'zur',
    answer: 'zu + der',
    options: ['zu + der', 'zu + dem', 'in + der', 'an + der'],
  },
  {
    id: 'p3-yy-zur-schule-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['places.kontraksiyon.zur'],
    familyId: 'p3-yy-zur-schule',
    instruction: 'Boşluğu doldur (tekrar):',
    prompt: 'Meine Schwester geht ___ Schule. (kardeşim okula gidiyor)',
    answer: 'zur',
    pronounce: ['Meine Schwester geht zur Schule.'],
  },
  {
    id: 'p3-yy-im-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['places.kontraksiyon.im'],
    familyId: 'p3-yy-im',
    instruction: '"im" hangi iki kelimenin birleşimidir?',
    prompt: 'im',
    answer: 'in + dem',
    options: ['in + dem', 'in + das', 'an + dem', 'zu + dem'],
  },
  {
    id: 'p3-yy-im-garten-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['places.kontraksiyon.im'],
    familyId: 'p3-yy-im-garten',
    instruction: 'Boşluğu doldur:',
    prompt: 'Mein Hund spielt ___ Garten. (köpeğim bahçede oynuyor)',
    answer: 'im',
    pronounce: ['Mein Hund spielt im Garten.'],
  },
  {
    id: 'p3-yy-ins-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['places.kontraksiyon.ins'],
    familyId: 'p3-yy-ins',
    instruction: '"ins" hangi iki kelimenin birleşimidir?',
    prompt: 'ins',
    answer: 'in + das',
    options: ['in + das', 'in + dem', 'an + das', 'zu + dem'],
  },
  {
    id: 'p3-yy-ins-kino-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['places.kontraksiyon.ins'],
    familyId: 'p3-yy-ins-kino',
    instruction: 'Boşluğu doldur:',
    prompt: 'Wir gehen am Abend ___ Kino. (akşam sinemaya gidiyoruz)',
    answer: 'ins',
    pronounce: ['Wir gehen am Abend ins Kino.'],
  },
  {
    id: 'p3-yy-am-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['places.kontraksiyon.am'],
    familyId: 'p3-yy-am',
    instruction: '"am" hangi iki kelimenin birleşimidir?',
    prompt: 'am',
    answer: 'an + dem',
    options: ['an + dem', 'in + dem', 'zu + dem', 'an + das'],
  },
  {
    id: 'p3-yy-ans-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['places.kontraksiyon.ans'],
    familyId: 'p3-yy-ans',
    instruction: 'Boşluğu doldur — an + das = ans:',
    prompt: 'Im Sommer gehe ich ___ Meer. (yazın denize gidiyorum)',
    answer: 'ans',
    pronounce: ['Im Sommer gehe ich ans Meer.'],
  },
  {
    id: 'p3-yy-im-ins-farki-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['places.im-ins-farki'],
    familyId: 'p3-yy-im-ins-farki',
    instruction: '"im" ile "ins" arasındaki fark nedir?',
    prompt: 'im ↔ ins',
    answer: 'im yerde kalmayı, ins bir yöne gitmeyi anlatır',
    options: [
      'im yerde kalmayı, ins bir yöne gitmeyi anlatır',
      'ikisi de aynı anlama gelir',
      'im sadece mevsimlerde, ins sadece filmlerde kullanılır',
      'im çoğul, ins tekil isimlerde kullanılır',
    ],
  },
  {
    id: 'p3-yy-im-park-vs-in-den-park-matching',
    topicId: T.places, legacyDay: 3,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['places.im-ins-farki', 'places.in-akkusativ-yon'],
    familyId: 'p3-yy-park-match',
    instruction: 'Cümleyi doğru anlamla eşleştir.',
    pairs: [
      { left: 'Wir machen einen Spaziergang im Park.', right: 'Parkta yürüyüş yapıyoruz. (konum)' },
      { left: 'Ich gehe mit meinen Freunden in den Park.', right: 'Arkadaşlarımla parka gidiyorum. (yön)' },
    ],
    pronounce: ['Wir machen einen Spaziergang im Park.', 'Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-nach-hause-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['places.nach-hause'],
    familyId: 'p3-yy-nach-hause',
    instruction: '"nach Hause" ne demektir?',
    prompt: 'nach Hause',
    answer: 'eve (bir yöne gitmek)',
    options: ['eve (bir yöne gitmek)', 'evde (konum)', 'evden', 'ev için'],
  },
  {
    id: 'p3-yy-nach-hause-zurueck-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['places.nach-hause'],
    familyId: 'p3-yy-nach-hause-abend',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich komme am Abend ___ Hause zurück. (akşam eve dönüyorum)',
    answer: 'nach',
    pronounce: ['Ich komme am Abend nach Hause zurück.'],
  },
  {
    id: 'p3-yy-zu-hause-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['places.zu-hause'],
    familyId: 'p3-yy-zu-hause',
    instruction: '"zu Hause" ne demektir?',
    prompt: 'zu Hause',
    answer: 'evde (konum)',
    options: ['evde (konum)', 'eve (yön)', 'ev', 'evden'],
  },
  {
    id: 'p3-yy-zu-hause-musik-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['places.zu-hause'],
    familyId: 'p3-yy-zu-hause-musik',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich höre ___ Hause ein bisschen Musik. (evde biraz müzik dinliyorum)',
    answer: 'zu',
    pronounce: ['Ich höre zu Hause ein bisschen Musik.'],
  },
  {
    id: 'p3-yy-nach-zu-hause-error',
    topicId: T.places, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['places.nach-hause', 'places.zu-hause'],
    familyId: 'p3-yy-nach-zu-farki',
    instruction: 'Hata avı — yön mü konum mu?',
    prompt: 'Ich komme um 4 Uhr zu Hause. (eve geliyorum — yön anlatılıyor)',
    answer: 'Ich komme um 4 Uhr nach Hause.',
    explanation: 'Bir yöne (eve doğru) gidildiği için "nach Hause" gerekir, "zu Hause" (evde, konum) değil.',
    pronounce: ['Ich komme um 4 Uhr nach Hause.'],
  },
  {
    id: 'p3-yy-mit-dativ-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['places.mit-dativ'],
    familyId: 'p3-yy-mit-dativ',
    instruction: '"mit" hangi hâli ister?',
    prompt: 'mit',
    answer: 'Dativ',
    options: ['Dativ', 'Akkusativ', 'Nominativ', 'hiçbiri'],
  },
  {
    id: 'p3-yy-mit-mir-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['places.mit-dativ'],
    familyId: 'p3-yy-mit-mir',
    instruction: 'Boşluğu doldur:',
    prompt: 'Mein Freund sitzt ___ mir. (arkadaşım benimle oturuyor)',
    answer: 'mit',
    pronounce: ['Mein Freund sitzt mit mir.'],
  },
  {
    id: 'p3-yy-meinen-freunden-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['places.mit-meinen-freunden'],
    familyId: 'p3-yy-meinen-freunden',
    instruction: 'Boşluğu doldur — mit + Dativ çoğul:',
    prompt: 'Ich gehe mit ___ Freunden in den Park. (arkadaşlarımla parka gidiyorum)',
    answer: 'meinen',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-error-meinen-freunde',
    topicId: T.places, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['places.mit-meinen-freunden'],
    familyId: 'p3-yy-meinen-freunde-error',
    instruction: 'Hata avı — Dativ çoğulda ne değişir?',
    prompt: 'Ich gehe mit meinen Freunde ins Park.',
    answer: 'Ich gehe mit meinen Freunden in den Park.',
    explanation: 'mit Dativ ister: isim Dativ çoğulda -n alır (Freunde → Freunden); der Park eril olduğu için yönde "in den Park" olur, "ins Park" değil.',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-der-den-dem-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['places.der-den-dem'],
    familyId: 'p3-yy-der-den-dem',
    instruction: '"der Regen" cümlenin doğrudan nesnesi olduğunda nasıl olur?',
    prompt: 'der Regen (Akkusativ nesne)',
    answer: 'den Regen',
    options: ['den Regen', 'dem Regen', 'der Regen', 'des Regen'],
  },
  {
    id: 'p3-yy-den-regen-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['places.der-den-dem'],
    familyId: 'p3-yy-den-regen',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich mag ___ Regen nicht. (yağmuru sevmiyorum)',
    answer: 'den',
    pronounce: ['Ich mag den Regen nicht.'],
  },
  {
    id: 'p3-yy-in-den-park-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['places.in-akkusativ-yon'],
    familyId: 'p3-yy-in-den-park',
    instruction: 'Boşluğu doldur — yöne gidiyorsun, der Park:',
    prompt: 'Ich gehe mit meinen Freunden in ___ Park.',
    answer: 'den',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-auf-dem-tisch-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['places.auf-dem'],
    familyId: 'p3-yy-auf-dem-tisch',
    instruction: 'Boşluğu doldur:',
    prompt: 'Auf ___ Tisch gibt es Bücher. (masanın üzerinde kitaplar var)',
    answer: 'dem',
    pronounce: ['Auf dem Tisch gibt es Bücher.'],
  },
  {
    id: 'p3-yy-bei-der-schule-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['places.bei-der'],
    familyId: 'p3-yy-bei-der-schule',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Wohnung ist nah bei ___ Schule. (evim okula yakın)',
    answer: 'der',
    pronounce: ['Meine Wohnung ist nah bei der Schule.'],
  },
  {
    id: 'p3-yy-wb-freunden-tr-de',
    topicId: T.places, legacyDay: 3,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['places.mit-meinen-freunden', 'places.in-akkusativ-yon'],
    familyId: 'p3-yy-meinen-freunden',
    instruction: 'Türkçeden Almancaya kur — Arkadaşlarımla parka gidiyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Arkadaşlarımla parka gidiyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'gehe' }, { id: 't3', text: 'mit' }, { id: 't4', text: 'meinen' },
        { id: 't5', text: 'Freunden' }, { id: 't6', text: 'in' }, { id: 't7', text: 'den' }, { id: 't8', text: 'Park.' },
        { id: 't9', text: 'im' },
      ],
      acceptedSequences: [['Ich', 'gehe', 'mit', 'meinen', 'Freunden', 'in', 'den', 'Park.']],
    },
    answer: 'Ich gehe mit meinen Freunden in den Park.',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-wb-tisch-de-tr',
    topicId: T.places, legacyDay: 3,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['places.kontraksiyon.im', 'akkusativ.esgibt.temel'],
    familyId: 'p3-yy-zimmer-tisch',
    instruction: 'Almancadan Türkçeye çevir — Odamda bir masa var.',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'In meinem Zimmer gibt es einen Tisch.',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Odamda' }, { id: 't2', text: 'bir' }, { id: 't3', text: 'masa' }, { id: 't4', text: 'var.' },
        { id: 't5', text: 'sandalye' },
      ],
      acceptedSequences: [['Odamda', 'bir', 'masa', 'var.']],
    },
    answer: 'Odamda bir masa var.',
    audio: { prompt: { text: 'In meinem Zimmer gibt es einen Tisch.', language: 'de-DE', role: 'prompt' } },
    pronounce: ['In meinem Zimmer gibt es einen Tisch.'],
  },
  {
    id: 'p3-yy-free-park-tr',
    topicId: T.places, legacyDay: 3,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['places.mit-meinen-freunden', 'places.in-akkusativ-yon'],
    familyId: 'p3-yy-park-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Arkadaşlarımla parka gidiyorum. → ______',
    answer: 'Ich gehe mit meinen Freunden in den Park.',
    pronounce: ['Ich gehe mit meinen Freunden in den Park.'],
  },
  {
    id: 'p3-yy-listen-garten',
    topicId: T.places, legacyDay: 3,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['places.kontraksiyon.im'],
    familyId: 'p3-yy-im-garten',
    instruction: 'Duyduğunu seç:',
    prompt: 'Mein Hund spielt im Garten.',
    audioText: 'Mein Hund spielt im Garten.',
    answer: 'Mein Hund spielt im Garten.',
    options: [
      'Mein Hund spielt im Garten.',
      'Mein Hund spielt im Park.',
      'Meine Katze spielt im Garten.',
      'Mein Vater spielt im Garten.',
    ],
    audio: { prompt: { text: 'Mein Hund spielt im Garten.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p3-yy-vater-arbeit-mc',
    topicId: T.places, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['places.kontraksiyon.zur'],
    familyId: 'p3-yy-vater-arbeit',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Mein Vater geht zur Arbeit.',
    answer: 'Babam işe gidiyor.',
    options: ['Babam işe gidiyor.', 'Babam evden geliyor.', 'Babam okula gidiyor.', 'Babam eve gidiyor.'],
    pronounce: ['Mein Vater geht zur Arbeit.'],
  },
  {
    id: 'p3-yy-ins-bett-fill',
    topicId: T.places, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['places.kontraksiyon.ins'],
    familyId: 'p3-yy-ins-bett',
    instruction: 'Boşluğu doldur (das Bett, nötr):',
    prompt: 'Ich gehe um 11 Uhr ___ Bett. (saat on birde yatıyorum)',
    answer: 'ins',
    pronounce: ['Ich gehe um 11 Uhr ins Bett.'],
  },
];
