/**
 * Zamirler ve İyelik — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

const DEIN = 'articles.artikel.dein-deine';
const IHR = 'pronouns.iyelik.ihr';
const KALIP = 'pronouns.cumle.kalip';
const MEIN = 'articles.artikel.mein-meine';
const SEIN = 'pronouns.iyelik.sein-onun';
const UNSER = 'pronouns.iyelik.unser';

export const PRONOUNS_EXERCISES: AuthoredExercise[] = [
  /* ---- İyelik Zamirleri — Tam Tablo (3) ---- */
  {
    id: 'p6-iye-sein-mc',
    topicId: T.pronouns, legacyDay: 6,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: [SEIN],
    familyId: 'p6-iye-sein',
    instruction: '"sein" iyelik zamiri ne demektir?',
    prompt: 'sein (iyelik zamiri)',
    answer: 'onun (erkek/nötr)',
    options: ['onun (erkek/nötr)', 'benim', 'senin', 'bizim'],
    pronounce: ['sein'],
  },
  {
    id: 'p6-iye-sein-fill',
    topicId: T.pronouns, legacyDay: 6,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: [SEIN],
    familyId: 'p6-iye-sein',
    instruction: 'Doğru iyelik zamirini yaz:',
    prompt: 'Er hat ein Auto. Das ist ___ Auto.',
    answer: 'sein',
    pronounce: ['Das ist sein Auto.'],
  },
  {
    id: 'p6-iye-tablo-match',
    topicId: T.pronouns, legacyDay: 6,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['pronouns.iyelik.zincir'],
    familyId: 'p6-iye-tablo',
    instruction: 'Kişi zamirini doğru iyelik zamiriyle eşleştir.',
    pairs: [
      { left: 'ich', right: 'mein' },
      { left: 'du', right: 'dein' },
      { left: 'er', right: 'sein' },
      { left: 'wir', right: 'unser' },
      { left: 'sie (onlar)', right: 'ihr' },
    ],
  },

  /* ---- İyelik Yapıları — unser, ihr (9) ---- */
  {
    id: 'p3-iy-unser-mc',
    topicId: T.pronouns, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['pronouns.iyelik.unser'],
    familyId: 'p3-iy-unser',
    instruction: '"unser / unsere" ne demektir?',
    prompt: 'unser / unsere',
    answer: 'bizim',
    options: ['bizim', 'senin', 'onun', 'benim'],
  },
  {
    id: 'p3-iy-unsere-wohnung-fill',
    topicId: T.pronouns, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['pronouns.iyelik.unser'],
    familyId: 'p3-iy-unsere-wohnung',
    instruction: 'Boşluğu doldur (die Wohnung, dişil):',
    prompt: '___ Wohnung hat drei Zimmer. (evimizde üç oda var)',
    answer: 'Unsere',
    pronounce: ['Unsere Wohnung hat drei Zimmer.'],
  },
  {
    id: 'p3-iy-unser-lehrer-fill',
    topicId: T.pronouns, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['pronouns.iyelik.unser'],
    familyId: 'p3-iy-unser-lehrer',
    instruction: 'Boşluğu doldur (der Lehrer, eril, eksiz):',
    prompt: '___ Lehrer ist sehr gut. (öğretmenimiz çok iyi)',
    answer: 'Unser',
    pronounce: ['Unser Lehrer ist sehr gut.'],
  },
  {
    id: 'p3-iy-ihr-mc',
    topicId: T.pronouns, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['pronouns.iyelik.ihr'],
    familyId: 'p3-iy-ihr',
    instruction: '"ihr / ihre" (kadın için) ne demektir?',
    prompt: 'ihr / ihre',
    answer: 'onun (kadın)',
    options: ['onun (kadın)', 'senin', 'bizim', 'onun (erkek)'],
  },
  {
    id: 'p3-iy-ihrem-zimmer-fill',
    topicId: T.pronouns, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['pronouns.iyelik.ihr'],
    familyId: 'p3-iy-ihrem-zimmer',
    instruction: 'Boşluğu doldur (das Zimmer, nötr, eksiz):',
    prompt: 'Meine Schwester lernt in ___ Zimmer. (odasında ders çalışıyor)',
    answer: 'ihrem',
    pronounce: ['Meine Schwester lernt in ihrem Zimmer.'],
  },
  {
    id: 'p3-iy-ihr-bett-fill',
    topicId: T.pronouns, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['pronouns.iyelik.ihr'],
    familyId: 'p3-iy-ihr-bett',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Schwester räumt ___ Bett auf. (yatağını topluyor)',
    answer: 'ihr',
    pronounce: ['Meine Schwester räumt ihr Bett auf.'],
  },
  {
    id: 'p3-iy-dativ-cogul-mc',
    topicId: T.pronouns, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['pronouns.iyelik.dativ-cogul'],
    familyId: 'p3-iy-dativ-cogul',
    instruction: 'Dativ çoğulda iyelik eki nasıl biter?',
    prompt: 'mein → mit ___ Freunden',
    answer: 'meinen',
    options: ['meinen', 'meine', 'mein', 'meiner'],
  },
  {
    id: 'p3-iy-error-dein-bett',
    topicId: T.pronouns, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['pronouns.iyelik.ihr'],
    familyId: 'p3-iy-ihr-bett',
    instruction: 'Hata avı — kimin yatağı?',
    prompt: 'Meine Schwester räumt dein Bett auf.',
    answer: 'Meine Schwester räumt ihr Bett auf.',
    explanation: 'Yatak kız kardeşin (3. kişi, kadın) yatağıdır, "dein" (senin) değil "ihr" (onun) kullanılmalı.',
    pronounce: ['Meine Schwester räumt ihr Bett auf.'],
  },
  {
    id: 'p3-iy-meine-tasche-fill',
    topicId: T.pronouns, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['pronouns.iyelik.unser'],
    familyId: 'p3-iy-meine-tasche',
    instruction: 'Boşluğu doldur (die Tasche, dişil):',
    prompt: 'Das ist ___ Tasche. (bu çanta benim)',
    answer: 'meine',
    pronounce: ['Das ist meine Tasche.'],
  },

  /* ---- Kişi Zamiri + İyelik Zamiri ile Cümle Kurma (50) ---- */
  {
    id: 'p6-cum-mein-01', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-01',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu benim kitabım. → ______',
    answer: 'Das ist mein Buch.',
    pronounce: ['Das ist mein Buch.'],
  },
  {
    id: 'p6-cum-mein-02', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-02',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Benim arabam burada. → ______',
    answer: 'Mein Auto ist hier.',
    pronounce: ['Mein Auto ist hier.'],
  },
  {
    id: 'p6-cum-mein-03', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-03',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Benim çantam nerede? → ______',
    answer: 'Wo ist meine Tasche?',
    pronounce: ['Wo ist meine Tasche?'],
  },
  {
    id: 'p6-cum-mein-04', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-04',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kitabımı seviyorum. → ______',
    answer: 'Ich mag mein Buch.',
    pronounce: ['Ich mag mein Buch.'],
  },
  {
    id: 'p6-cum-mein-05', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-05',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Ailemi seviyorum. → ______',
    answer: 'Ich mag meine Familie.',
    pronounce: ['Ich mag meine Familie.'],
  },
  {
    id: 'p6-cum-mein-06', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-06',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Benim kedim çok güzel. → ______',
    answer: 'Meine Katze ist sehr schön.',
    pronounce: ['Meine Katze ist sehr schön.'],
  },
  {
    id: 'p6-cum-mein-07', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-07',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Babam Berlin\'de yaşıyor. → ______',
    answer: 'Mein Vater wohnt in Berlin.',
    pronounce: ['Mein Vater wohnt in Berlin.'],
  },
  {
    id: 'p6-cum-mein-08', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-08',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kız kardeşimin adı Ayşe. → ______',
    answer: 'Meine Schwester heißt Ayşe.',
    pronounce: ['Meine Schwester heißt Ayşe.'],
  },
  {
    id: 'p6-cum-mein-09', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-09',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu benim telefon numaram. → ______',
    answer: 'Das ist meine Telefonnummer.',
    pronounce: ['Das ist meine Telefonnummer.'],
  },
  {
    id: 'p6-cum-mein-10', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [MEIN, KALIP], familyId: 'p6-cum-mein-10',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Benim evim küçük. → ______',
    answer: 'Meine Wohnung ist klein.',
    pronounce: ['Meine Wohnung ist klein.'],
  },
  {
    id: 'p6-cum-dein-01', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-01',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu senin kitabın mı? → ______',
    answer: 'Ist das dein Buch?',
    pronounce: ['Ist das dein Buch?'],
  },
  {
    id: 'p6-cum-dein-02', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-02',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Senin araban nerede? → ______',
    answer: 'Wo ist dein Auto?',
    pronounce: ['Wo ist dein Auto?'],
  },
  {
    id: 'p6-cum-dein-03', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-03',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Senin çantan çok güzel. → ______',
    answer: 'Deine Tasche ist sehr schön.',
    pronounce: ['Deine Tasche ist sehr schön.'],
  },
  {
    id: 'p6-cum-dein-04', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-04',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kedini seviyor musun? → ______',
    answer: 'Magst du deine Katze?',
    pronounce: ['Magst du deine Katze?'],
  },
  {
    id: 'p6-cum-dein-05', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-05',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Baban nerede yaşıyor? → ______',
    answer: 'Wo wohnt dein Vater?',
    pronounce: ['Wo wohnt dein Vater?'],
  },
  {
    id: 'p6-cum-dein-06', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-06',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kardeşinin adı ne? → ______',
    answer: 'Wie heißt dein Bruder?',
    pronounce: ['Wie heißt dein Bruder?'],
  },
  {
    id: 'p6-cum-dein-07', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-07',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Senin evin büyük mü? → ______',
    answer: 'Ist deine Wohnung groß?',
    pronounce: ['Ist deine Wohnung groß?'],
  },
  {
    id: 'p6-cum-dein-08', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-08',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu senin telefon numaran mı? → ______',
    answer: 'Ist das deine Telefonnummer?',
    pronounce: ['Ist das deine Telefonnummer?'],
  },
  {
    id: 'p6-cum-dein-09', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-09',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Senin arkadaşın nereli? → ______',
    answer: 'Woher kommt dein Freund?',
    pronounce: ['Woher kommt dein Freund?'],
  },
  {
    id: 'p6-cum-dein-10', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [DEIN, KALIP], familyId: 'p6-cum-dein-10',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Senin adresin ne? → ______',
    answer: 'Wie ist deine Adresse?',
    pronounce: ['Wie ist deine Adresse?'],
  },
  {
    id: 'p6-cum-sein-01', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [SEIN, KALIP], familyId: 'p6-cum-sein-01',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu onun (erkek) kitabı. → ______',
    answer: 'Das ist sein Buch.',
    pronounce: ['Das ist sein Buch.'],
  },
  {
    id: 'p6-cum-sein-02', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [SEIN, KALIP], familyId: 'p6-cum-sein-02',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onun (erkek) arabası kırmızı. → ______',
    answer: 'Sein Auto ist rot.',
    pronounce: ['Sein Auto ist rot.'],
  },
  {
    id: 'p6-cum-sein-03', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [SEIN, KALIP], familyId: 'p6-cum-sein-03',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'O (erkek) kedisini seviyor. → ______',
    answer: 'Er mag seine Katze.',
    pronounce: ['Er mag seine Katze.'],
  },
  {
    id: 'p6-cum-sein-04', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [SEIN, KALIP], familyId: 'p6-cum-sein-04',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onun (erkek) babası öğretmen. → ______',
    answer: 'Sein Vater ist Lehrer.',
    pronounce: ['Sein Vater ist Lehrer.'],
  },
  {
    id: 'p6-cum-sein-05', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [SEIN, KALIP], familyId: 'p6-cum-sein-05',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onun (erkek) kız kardeşi Almanya\'dan geliyor. → ______',
    answer: 'Seine Schwester kommt aus Deutschland.',
    pronounce: ['Seine Schwester kommt aus Deutschland.'],
  },
  {
    id: 'p6-cum-sein-06', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [SEIN, KALIP], familyId: 'p6-cum-sein-06',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu onun (erkek) telefon numarası. → ______',
    answer: 'Das ist seine Telefonnummer.',
    pronounce: ['Das ist seine Telefonnummer.'],
  },
  {
    id: 'p6-cum-es-07', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [SEIN, KALIP], familyId: 'p6-cum-es-07',
    instruction: 'Türkçeden Almancaya çevir: (bebek hakkında)',
    prompt: 'Onun adı Tom. → ______',
    answer: 'Es heißt Tom.',
    pronounce: ['Es heißt Tom.'],
  },
  {
    id: 'p6-cum-ihr-08', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihr-08',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu onun (kadın) çantası. → ______',
    answer: 'Das ist ihre Tasche.',
    pronounce: ['Das ist ihre Tasche.'],
  },
  {
    id: 'p6-cum-ihr-09', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihr-09',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onun (kadın) evi küçük. → ______',
    answer: 'Ihre Wohnung ist klein.',
    pronounce: ['Ihre Wohnung ist klein.'],
  },
  {
    id: 'p6-cum-ihr-10', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihr-10',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'O (kadın) ailesini seviyor. → ______',
    answer: 'Sie mag ihre Familie.',
    pronounce: ['Sie mag ihre Familie.'],
  },
  {
    id: 'p6-cum-unser-01', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-01',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu bizim evimiz. → ______',
    answer: 'Das ist unsere Wohnung.',
    pronounce: ['Das ist unsere Wohnung.'],
  },
  {
    id: 'p6-cum-unser-02', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-02',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bizim arabamız burada. → ______',
    answer: 'Unser Auto ist hier.',
    pronounce: ['Unser Auto ist hier.'],
  },
  {
    id: 'p6-cum-unser-03', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-03',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Ailemizi seviyoruz. → ______',
    answer: 'Wir mögen unsere Familie.',
    pronounce: ['Wir mögen unsere Familie.'],
  },
  {
    id: 'p6-cum-unser-04', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-04',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bizim öğretmenimiz Almanca konuşuyor. → ______',
    answer: 'Unser Lehrer spricht Deutsch.',
    pronounce: ['Unser Lehrer spricht Deutsch.'],
  },
  {
    id: 'p6-cum-unser-05', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-05',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu bizim kedimiz. → ______',
    answer: 'Das ist unsere Katze.',
    pronounce: ['Das ist unsere Katze.'],
  },
  {
    id: 'p6-cum-unser-06', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-06',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bizim kitabımız masada. → ______',
    answer: 'Unser Buch ist auf dem Tisch.',
    pronounce: ['Unser Buch ist auf dem Tisch.'],
  },
  {
    id: 'p6-cum-unser-07', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-07',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kedimizi seviyoruz. → ______',
    answer: 'Wir mögen unsere Katze.',
    pronounce: ['Wir mögen unsere Katze.'],
  },
  {
    id: 'p6-cum-unser-08', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-08',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu bizim adresimiz. → ______',
    answer: 'Das ist unsere Adresse.',
    pronounce: ['Das ist unsere Adresse.'],
  },
  {
    id: 'p6-cum-unser-09', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-09',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bizim köpeğimiz çok tatlı. → ______',
    answer: 'Unser Hund ist sehr süß.',
    pronounce: ['Unser Hund ist sehr süß.'],
  },
  {
    id: 'p6-cum-unser-10', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [UNSER, KALIP], familyId: 'p6-cum-unser-10',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu bizim telefon numaramız değil. → ______',
    answer: 'Das ist nicht unsere Telefonnummer.',
    pronounce: ['Das ist nicht unsere Telefonnummer.'],
  },
  {
    id: 'p6-cum-ihrpl-01', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-01',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu onların evi. → ______',
    answer: 'Das ist ihre Wohnung.',
    pronounce: ['Das ist ihre Wohnung.'],
  },
  {
    id: 'p6-cum-ihrpl-02', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-02',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onların arabası kırmızı. → ______',
    answer: 'Ihr Auto ist rot.',
    pronounce: ['Ihr Auto ist rot.'],
  },
  {
    id: 'p6-cum-ihrpl-03', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-03',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onlar ailelerini seviyor. → ______',
    answer: 'Sie mögen ihre Familie.',
    pronounce: ['Sie mögen ihre Familie.'],
  },
  {
    id: 'p6-cum-ihrpl-04', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-04',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onların öğretmeni Almanca konuşuyor. → ______',
    answer: 'Ihr Lehrer spricht Deutsch.',
    pronounce: ['Ihr Lehrer spricht Deutsch.'],
  },
  {
    id: 'p6-cum-ihrpl-05', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-05',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu onların kedisi. → ______',
    answer: 'Das ist ihre Katze.',
    pronounce: ['Das ist ihre Katze.'],
  },
  {
    id: 'p6-cum-ihrpl-06', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-06',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onların kitabı masada. → ______',
    answer: 'Ihr Buch ist auf dem Tisch.',
    pronounce: ['Ihr Buch ist auf dem Tisch.'],
  },
  {
    id: 'p6-cum-ihrpl-07', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-07',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onlar evlerini seviyor. → ______',
    answer: 'Sie mögen ihre Wohnung.',
    pronounce: ['Sie mögen ihre Wohnung.'],
  },
  {
    id: 'p6-cum-ihrpl-08', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-08',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu onların adresi. → ______',
    answer: 'Das ist ihre Adresse.',
    pronounce: ['Das ist ihre Adresse.'],
  },
  {
    id: 'p6-cum-ihrpl-09', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-09',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Onların çocuğu çok tatlı. → ______',
    answer: 'Ihr Kind ist sehr süß.',
    pronounce: ['Ihr Kind ist sehr süß.'],
  },
  {
    id: 'p6-cum-ihrpl-10', topicId: T.pronouns, legacyDay: 6,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: [IHR, KALIP], familyId: 'p6-cum-ihrpl-10',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bu onların telefon numarası değil. → ______',
    answer: 'Das ist nicht ihre Telefonnummer.',
    pronounce: ['Das ist nicht ihre Telefonnummer.'],
  },

  /* ---- Artikelden Kişi Zamirine — der, die, das (8) ---- */
  {
    id: 'p7-zam-match',
    topicId: T.pronouns, legacyDay: 7,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['pronouns.zamir.der-er', 'pronouns.zamir.das-es', 'pronouns.zamir.die-sie'],
    familyId: 'p7-zam-match',
    instruction: 'Artikeli doğru kişi zamiriyle eşleştir.',
    pairs: [
      { left: 'der', right: 'er' },
      { left: 'das', right: 'es' },
      { left: 'die', right: 'sie' },
    ],
  },
  {
    id: 'p7-zam-der-schrank',
    topicId: T.pronouns, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['pronouns.zamir.der-er'],
    familyId: 'p7-zam-der',
    instruction: 'Hangi kişi zamiri kullanılır?',
    prompt: 'der Schrank → ___',
    answer: 'er',
    validation: { noTypoTolerance: true },
    pronounce: ['er'],
  },
  {
    id: 'p7-zam-die-kueche',
    topicId: T.pronouns, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['pronouns.zamir.die-sie'],
    familyId: 'p7-zam-die',
    instruction: 'Hangi kişi zamiri kullanılır?',
    prompt: 'die Küche → ___',
    answer: 'sie',
    validation: { noTypoTolerance: true },
    pronounce: ['sie'],
  },
  {
    id: 'p7-zam-das-bett',
    topicId: T.pronouns, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['pronouns.zamir.das-es'],
    familyId: 'p7-zam-das',
    instruction: 'Hangi kişi zamiri kullanılır?',
    prompt: 'das Bett → ___',
    answer: 'es',
    validation: { noTypoTolerance: true },
    pronounce: ['es'],
  },
  {
    id: 'p7-zam-context-schrank',
    topicId: T.pronouns, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['pronouns.zamir.cumlede'],
    familyId: 'p7-zam-context-schrank',
    instruction: 'Boşluğa doğru kişi zamirini yaz:',
    prompt: 'Der Schrank ist groß. ___ ist grau.',
    answer: 'Er',
    validation: { caseSensitive: true, noTypoTolerance: true },
    pronounce: ['Der Schrank ist groß.', 'Er ist grau.'],
  },
  {
    id: 'p7-zam-context-kueche',
    topicId: T.pronouns, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['pronouns.zamir.cumlede', 'pronouns.zamir.die-sie'],
    familyId: 'p7-zam-context-kueche',
    instruction: 'Boşluğa doğru kişi zamirini yaz:',
    prompt: 'Die Küche ist hell. ___ ist schön.',
    answer: 'Sie',
    validation: { caseSensitive: true, noTypoTolerance: true },
    pronounce: ['Die Küche ist hell.', 'Sie ist schön.'],
  },
  {
    id: 'p7-zam-context-bett',
    topicId: T.pronouns, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['pronouns.zamir.cumlede', 'pronouns.zamir.das-es'],
    familyId: 'p7-zam-context-bett',
    instruction: 'Boşluğa doğru kişi zamirini yaz:',
    prompt: 'Das Bett ist klein. ___ ist grau.',
    answer: 'Es',
    validation: { caseSensitive: true, noTypoTolerance: true },
    pronounce: ['Das Bett ist klein.', 'Es ist grau.'],
  },
  {
    id: 'p7-zam-error-teppich',
    topicId: T.pronouns, legacyDay: 7,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['pronouns.zamir.cumlede', 'home.moebel.teppich-regal'],
    familyId: 'p7-zam-error-teppich',
    instruction: 'İkinci cümledeki zamir hatasını düzelt:',
    prompt: 'Der Teppich ist breit. Sie ist grau.',
    answer: 'Der Teppich ist breit. Er ist grau.',
    explanation: '`der Teppich` eril olduğu için zamir `er` olur.',
    pronounce: ['Der Teppich ist breit. Er ist grau.'],
  },
];
