/**
 * Soru Kurma — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const QUESTIONS_EXERCISES: AuthoredExercise[] = [
  /* ---- Evet/Hayır Soruları (11) ---- */
  {
    id: 'p2-sor-yapi-mc',
    topicId: T.questions, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['questions.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-yapi',
    instruction: 'Evet/hayır sorusunda fiil cümlenin neresinde durur?',
    prompt: 'Fiil + Özne + ... ?',
    answer: 'cümlenin başında',
    options: ['cümlenin başında', 'cümlenin ortasında', 'cümlenin sonunda', 'özneden sonra'],
  },
  {
    id: 'p2-sor-gehst-du-fill',
    topicId: T.questions, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['questions.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-gehen',
    instruction: 'Soruyu tamamla:',
    prompt: '_____ du heute zur Schule? (gehen)',
    answer: 'Gehst',
    pronounce: ['Gehst du heute zur Schule?'],
  },
  {
    id: 'p2-sor-machst-du-mc',
    topicId: T.questions, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['questions.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-machen',
    instruction: 'Doğru soruyu seç:',
    prompt: 'Spor yapıyor musun?',
    answer: 'Machst du Sport?',
    options: ['Machst du Sport?', 'Du machst Sport?', 'Machst Sport du?', 'Macht du Sport?'],
    pronounce: ['Machst du Sport?'],
  },
  {
    id: 'p2-sor-trinkst-du-fill',
    topicId: T.questions, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['questions.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-trinken',
    instruction: 'Soruyu tamamla:',
    prompt: '_____ du ein Kaffee? (trinken)',
    answer: 'Trinkst',
    pronounce: ['Trinkst du ein Kaffee?'],
  },
  {
    id: 'p2-sor-hast-du-fill',
    topicId: T.questions, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['questions.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-haben',
    instruction: 'Soruyu tamamla:',
    prompt: '_____ du eine Schwester? (haben)',
    answer: 'Hast',
    pronounce: ['Hast du eine Schwester?'],
  },
  {
    id: 'p2-sor-liest-du-mc',
    topicId: T.questions, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['questions.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-lesen',
    instruction: 'Bu sorunun Türkçesi nedir?',
    prompt: 'Liest du jeden Tag ein Buch?',
    answer: 'Her gün kitap okuyor musun?',
    options: ['Her gün kitap okuyor musun?', 'Her gün spor yapıyor musun?', 'Bugün okula gidiyor musun?', 'Bir kahve içer misin?'],
    pronounce: ['Liest du jeden Tag ein Buch?'],
  },
  {
    id: 'p2-sor-donusum-free',
    topicId: T.questions, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['questions.sorular.donusum'],
    familyId: 'p2-sor-machen',
    instruction: 'Cümleyi soruya çevir:',
    prompt: 'Du machst Sport. → ______',
    answer: 'Machst du Sport?',
    pronounce: ['Machst du Sport?'],
  },
  {
    id: 'p2-sor-ja-antwort-free',
    topicId: T.questions, legacyDay: 2,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['questions.sorular.ja-nein-cevap'],
    familyId: 'p2-sor-gehen',
    instruction: 'Olumlu tam cümle ile cevap ver:',
    prompt: 'Gehst du heute zur Schule? → Ja, ______',
    answer: 'ich gehe heute zur Schule.',
    pronounce: ['Ja, ich gehe heute zur Schule.'],
  },
  {
    id: 'p2-sor-nein-antwort-schwester-free',
    topicId: T.questions, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['questions.sorular.ja-nein-cevap'],
    familyId: 'p2-sor-haben',
    instruction: 'Olumsuz tam cümle ile cevap ver:',
    prompt: 'Hast du eine Schwester? → Nein, ______',
    answer: 'ich habe keine Schwester.',
    pronounce: ['Nein, ich habe keine Schwester.'],
  },
  {
    id: 'p2-sor-nein-antwort-kaffee-free',
    topicId: T.questions, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['questions.sorular.ja-nein-cevap'],
    familyId: 'p2-sor-trinken',
    instruction: 'Olumsuz tam cümle ile cevap ver:',
    prompt: 'Trinkst du ein Kaffee? → Nein, ______',
    answer: 'ich trinke heute nicht.',
    pronounce: ['Nein, ich trinke heute nicht.'],
  },
  {
    id: 'p2-wb-schule-tr-de',
    topicId: T.questions, legacyDay: 2,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['questions.sorular.evet-hayir-yapi'],
    familyId: 'p2-sor-gehen',
    instruction: 'Türkçeden Almancaya kur — Bugün okula gidiyor musun?',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Bugün okula gidiyor musun?',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Gehst' }, { id: 't2', text: 'du' }, { id: 't3', text: 'heute' }, { id: 't4', text: 'zur' }, { id: 't5', text: 'Schule?' },
        { id: 't6', text: 'Machst' }, { id: 't7', text: 'Sport' },
      ],
      acceptedSequences: [['Gehst', 'du', 'heute', 'zur', 'Schule?']],
    },
    answer: 'Gehst du heute zur Schule?',
    pronounce: ['Gehst du heute zur Schule?'],
  },

  /* ---- W-soruları ---- */
  {
    id: 'w-wo-fill',
    topicId: T.questions,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['questions.w-woerter'],
    familyId: 'w-wo',
    instruction: 'Soru kelimesini yaz — Nerede oturuyorsun?',
    prompt: '___ wohnst du?',
    answer: 'Wo',
    validation: { caseSensitive: false, noTypoTolerance: true },
    pronounce: ['Wo wohnst du?'],
  },
  {
    id: 'w-woher-fill',
    topicId: T.questions,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['questions.w-woerter'],
    familyId: 'w-woher',
    instruction: 'Soru kelimesini yaz — Nerelisin? (nereden)',
    prompt: '___ kommst du?',
    answer: 'Woher',
    validation: { caseSensitive: false, noTypoTolerance: true },
    pronounce: ['Woher kommst du?'],
  },
  {
    id: 'w-wann-mc',
    topicId: T.questions,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['questions.w-woerter'],
    familyId: 'w-wann',
    instruction: '"Ne zaman kalkıyorsun?" sorusu hangi kelimeyle başlar?',
    prompt: '___ stehst du auf?',
    answer: 'Wann',
    options: ['Wann', 'Wo', 'Wer', 'Was'],
    pronounce: ['Wann stehst du auf?'],
  },
  {
    id: 'w-wer-koennen-tr',
    topicId: T.questions,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['questions.w-woerter', 'modal-verbs.koennen.kullanim'],
    familyId: 'w-wer-koennen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kim Almanca konuşabiliyor?',
    answer: 'Wer kann Deutsch sprechen?',
    explanation: '`Wer` 3. tekil gibi çekilir: `Wer kann …?`; mastar yine en sonda.',
    pronounce: ['Wer kann Deutsch sprechen?'],
  },
  {
    id: 'w-was-trinken-order',
    topicId: T.questions,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['questions.w-woerter', 'modal-verbs.moechten.cekim'],
    familyId: 'w-was-trinken',
    instruction: 'Kelimeleri doğru sıraya diz — Ne içmek istersin?',
    prompt: 'Ne içmek istersin?',
    answer: 'Was möchtest du trinken?',
    pronounce: ['Was möchtest du trinken?'],
  },
  {
    id: 'w-woerter-match',
    topicId: T.questions,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['questions.w-woerter'],
    familyId: 'w-woerter-match',
    instruction: 'Soru kelimelerini anlamlarıyla eşleştir.',
    pairs: [
      { left: 'Wer?', right: 'kim?' },
      { left: 'Was?', right: 'ne?' },
      { left: 'Wo?', right: 'nerede?' },
      { left: 'Woher?', right: 'nereden?' },
      { left: 'Wann?', right: 'ne zaman?' },
    ],
  },
];
