/**
 * Cümle Kurma — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const SENTENCE_BUILDING_EXERCISES: AuthoredExercise[] = [
  /* ---- Olumlu Cümle Kurma (17) ---- */
  {
    id: 'p2-pos-machen-mc',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['sentence-building.verben.machen'],
    familyId: 'p2-pos-machen',
    instruction: '"machen" fiilinin anlamı nedir?',
    prompt: 'machen',
    answer: 'yapmak',
    options: ['yapmak', 'gitmek', 'içmek', 'gelmek'],
    pronounce: ['machen'],
  },
  {
    id: 'p2-pos-mache-sport-fill',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['sentence-building.verben.machen', 'sentence-building.cumle.olumlu-yapi'],
    familyId: 'p2-pos-sport',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich _____ Sport. (machen)',
    answer: 'mache',
    pronounce: ['Ich mache Sport.'],
  },
  {
    id: 'p2-pos-order-sport',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.cumle.olumlu-yapi', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-sport',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / mache / jeden / Tag / Sport.',
    answer: 'Ich mache jeden Tag Sport.',
    words: ['Ich', 'mache', 'jeden', 'Tag', 'Sport'],
    pronounce: ['Ich mache jeden Tag Sport.'],
  },
  {
    id: 'p2-pos-trinke-kaffee-fill',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['sentence-building.zaman.jeden-tag-heute', 'sentence-building.cumle.olumlu-yapi'],
    familyId: 'p2-pos-kaffee',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich _____ jeden Morgen ein Kaffee. (trinken)',
    answer: 'trinke',
    pronounce: ['Ich trinke jeden Morgen ein Kaffee.'],
  },
  {
    id: 'p2-pos-isst-um4-fill',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-isst',
    instruction: 'Boşluğu doldur (essen — tekrar):',
    prompt: 'Er _____ um 4 Uhr. (essen)',
    answer: 'isst',
    pronounce: ['Er isst um 4 Uhr.'],
  },
  {
    id: 'p2-pos-kochen-heute-fill',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['sentence-building.cumle.olumlu-yapi'],
    familyId: 'p2-pos-kochen',
    instruction: 'Boşluğu doldur (kochen — tekrar):',
    prompt: 'Ich _____ heute.',
    answer: 'koche',
    pronounce: ['Ich koche heute.'],
  },
  {
    id: 'p2-pos-zur-fill',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['sentence-building.verben.gehen-zur'],
    familyId: 'p2-pos-zur-arbeit',
    instruction: 'Boşluğu doldur — "zu" ve "der" kaynaşır:',
    prompt: 'Mein Vater geht jeden Tag _____ Arbeit.',
    answer: 'zur',
    pronounce: ['Mein Vater geht jeden Tag zur Arbeit.'],
  },
  {
    id: 'p2-pos-zur-schule-mc',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['sentence-building.verben.gehen-zur'],
    familyId: 'p2-pos-zur-schule',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Er geht zur Schule.',
    answer: 'O okula gider.',
    options: ['O okula gider.', 'O işe gider.', 'O eve gider.', 'O okuldan gelir.'],
    pronounce: ['Er geht zur Schule.'],
  },
  {
    id: 'p2-pos-builder-sport-tr',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['sentence-building.verben.machen', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-sport',
    instruction: 'Cümleyi kur:',
    prompt: 'Ben her gün spor yapıyorum.',
    answer: 'Ich mache jeden Tag Sport.',
    words: ['Ich', 'mache', 'jeden', 'Tag', 'Sport'],
    pronounce: ['Ich mache jeden Tag Sport.'],
  },
  {
    id: 'p2-pos-free-lesen',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['sentence-building.cumle.olumlu-yapi', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-gun-buch',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Her gün kitap okurum. → ______',
    answer: 'Ich lese jeden Tag ein Buch.',
    hint: 'lesen düzensizdir ama ich her zaman düzenli -e alır.',
    pronounce: ['Ich lese jeden Tag ein Buch.'],
  },
  {
    id: 'p2-pos-order-mutter-kocht',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.cumle.olumlu-yapi', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-mutter-kocht',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Meine / Mutter / kocht / heute.',
    answer: 'Meine Mutter kocht heute.',
    words: ['Meine', 'Mutter', 'kocht', 'heute'],
    pronounce: ['Meine Mutter kocht heute.'],
  },
  {
    id: 'p2-pos-builder-vater-wasser-tr',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['sentence-building.cumle.olumlu-yapi', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-vater-wasser',
    instruction: 'Cümleyi kur:',
    prompt: 'Babam her sabah bir su içer.',
    answer: 'Mein Vater trinkt jeden Morgen ein Wasser.',
    words: ['Mein', 'Vater', 'trinkt', 'jeden', 'Morgen', 'ein', 'Wasser'],
    pronounce: ['Mein Vater trinkt jeden Morgen ein Wasser.'],
  },
  {
    id: 'p2-pos-free-wir-schule',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['sentence-building.verben.gehen-zur', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-wir-schule',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Biz her gün okula gideriz. → ______',
    answer: 'Wir gehen jeden Tag zur Schule.',
    pronounce: ['Wir gehen jeden Tag zur Schule.'],
  },
  {
    id: 'p2-pos-wb-schwester-buch-tr',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.cumle.olumlu-yapi', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-schwester-buch',
    instruction: 'Türkçeden Almancaya kur — Kız kardeşim her gün kitap okur.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Kız kardeşim her gün kitap okur.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Meine' }, { id: 't2', text: 'Schwester' }, { id: 't3', text: 'liest' },
        { id: 't4', text: 'jeden' }, { id: 't5', text: 'Tag' }, { id: 't6', text: 'ein' }, { id: 't7', text: 'Buch.' },
        { id: 't8', text: 'nicht' },
      ],
      acceptedSequences: [['Meine', 'Schwester', 'liest', 'jeden', 'Tag', 'ein', 'Buch.']],
    },
    answer: 'Meine Schwester liest jeden Tag ein Buch.',
    pronounce: ['Meine Schwester liest jeden Tag ein Buch.'],
  },
  {
    id: 'p2-pos-order-tante-kommt',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'ordering', difficulty: 'easy', skill: 'production',
    conceptIds: ['sentence-building.cumle.olumlu-yapi', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-tante-kommt',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Meine / Tante / kommt / heute.',
    answer: 'Meine Tante kommt heute.',
    words: ['Meine', 'Tante', 'kommt', 'heute'],
    pronounce: ['Meine Tante kommt heute.'],
  },
  {
    id: 'p2-pos-builder-kinder-sport-tr',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'sentence-builder', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.cumle.olumlu-yapi', 'sentence-building.zaman.jeden-tag-heute'],
    familyId: 'p2-pos-kinder-sport',
    instruction: 'Cümleyi kur:',
    prompt: 'Çocuklar her gün spor yapar.',
    answer: 'Die Kinder machen jeden Tag Sport.',
    words: ['Die', 'Kinder', 'machen', 'jeden', 'Tag', 'Sport'],
    pronounce: ['Die Kinder machen jeden Tag Sport.'],
  },
  {
    id: 'p2-wb-vater-de-tr',
    topicId: T.sentenceBuilding, legacyDay: 2,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['sentence-building.verben.gehen-zur'],
    familyId: 'p2-pos-zur-arbeit',
    instruction: 'Almancadan Türkçeye çevir — Babam her gün işe gider.',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Mein Vater geht jeden Tag zur Arbeit.',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Babam' }, { id: 't2', text: 'her' }, { id: 't3', text: 'gün' }, { id: 't4', text: 'işe' }, { id: 't5', text: 'gider.' },
        { id: 't6', text: 'okula' },
      ],
      acceptedSequences: [['Babam', 'her', 'gün', 'işe', 'gider.']],
    },
    answer: 'Babam her gün işe gider.',
    audio: { prompt: { text: 'Mein Vater geht jeden Tag zur Arbeit.', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Mein Vater geht jeden Tag zur Arbeit.'],
  },

  /* ---- Cümle Dizilişi — Fiil İkinci Sırada (8) ---- */
  {
    id: 'p3-cd-verb-ikinci-mc',
    topicId: T.sentenceBuilding, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['sentence-building.dizilisi.verb-ikinci'],
    familyId: 'p3-cd-verb-ikinci',
    instruction: 'Almanca ana cümlede fiil kaçıncı sıradadır?',
    prompt: 'Fiil pozisyonu',
    answer: 'her zaman ikinci sırada',
    options: ['her zaman ikinci sırada', 'her zaman ilk sırada', 'her zaman son sırada', 'sırası önemli değil'],
  },
  {
    id: 'p3-cd-zaman-basta-mc',
    topicId: T.sentenceBuilding, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['sentence-building.dizilisi.zaman-basta'],
    familyId: 'p3-cd-zaman-basta',
    instruction: 'Cümle bir zaman ifadesiyle başlarsa özne nereye gider?',
    prompt: 'Am Abend ___ ich nach Hause. (özne nerede?)',
    answer: 'fiilden sonra',
    options: ['fiilden sonra', 'fiilden önce', 'cümlenin en başına', 'cümlenin en sonuna'],
  },
  {
    id: 'p3-cd-heute-order',
    topicId: T.sentenceBuilding, legacyDay: 3,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.dizilisi.zaman-basta'],
    familyId: 'p3-cd-heute-order',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Heute / bin / ich / sehr / glücklich.',
    answer: 'Heute bin ich sehr glücklich.',
    words: ['Heute', 'bin', 'ich', 'sehr', 'glücklich'],
    pronounce: ['Heute bin ich sehr glücklich.'],
  },
  {
    id: 'p3-cd-am-abend-order',
    topicId: T.sentenceBuilding, legacyDay: 3,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.dizilisi.zaman-basta'],
    familyId: 'p3-cd-am-abend-order',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Am / Abend / gehe / ich / nach / Hause.',
    answer: 'Am Abend gehe ich nach Hause.',
    words: ['Am', 'Abend', 'gehe', 'ich', 'nach', 'Hause'],
    pronounce: ['Am Abend gehe ich nach Hause.'],
  },
  {
    id: 'p3-cd-error-heute-ich-bin',
    topicId: T.sentenceBuilding, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['sentence-building.dizilisi.zaman-basta'],
    familyId: 'p3-cd-heute-order',
    instruction: 'Hata avı — fiil hangi sırada olmalı?',
    prompt: 'Heute ich bin sehr glücklich.',
    answer: 'Heute bin ich sehr glücklich.',
    explanation: 'Fiil her zaman ikinci sırada durur; zaman ifadesi (Heute) başa geldiğinde özne (ich) fiilden sonraya kayar.',
    pronounce: ['Heute bin ich sehr glücklich.'],
  },
  {
    id: 'p3-cd-nach-dem-film-builder-tr',
    topicId: T.sentenceBuilding, legacyDay: 3,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['sentence-building.dizilisi.zaman-basta'],
    familyId: 'p3-cd-nach-dem-film',
    instruction: 'Cümleyi kur:',
    prompt: 'Filmden sonra eve gidiyorum.',
    answer: 'Nach dem Film gehe ich nach Hause.',
    words: ['Nach', 'dem', 'Film', 'gehe', 'ich', 'nach', 'Hause'],
    pronounce: ['Nach dem Film gehe ich nach Hause.'],
  },
  {
    id: 'p3-cd-free-nach-dem-film-tr',
    topicId: T.sentenceBuilding, legacyDay: 3,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['sentence-building.dizilisi.zaman-basta'],
    familyId: 'p3-cd-nach-dem-film',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Filmden sonra eve gidiyorum. → ______',
    answer: 'Nach dem Film gehe ich nach Hause.',
    pronounce: ['Nach dem Film gehe ich nach Hause.'],
  },
  {
    id: 'p3-cd-dictation-am-abend',
    topicId: T.sentenceBuilding, legacyDay: 3,
    type: 'dictation', difficulty: 'hard', skill: 'production',
    conceptIds: ['sentence-building.dizilisi.zaman-basta'],
    familyId: 'p3-cd-am-abend-order',
    instruction: 'Cümleyi duydun — aynen yaz:',
    audioText: 'Am Abend gehe ich nach Hause.',
    answer: 'Am Abend gehe ich nach Hause.',
    audio: { prompt: { text: 'Am Abend gehe ich nach Hause.', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- und / aber — Bağlaçlar (8) ---- */
  {
    id: 'p5-bag-und-mc',
    topicId: T.sentenceBuilding, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['sentence-building.baglac.und'],
    familyId: 'p5-bag-und-mc',
    instruction: '"und" ne demektir?',
    prompt: 'und',
    answer: 've',
    options: ['ve', 'ama', 'ile', 'veya'],
    pronounce: ['und'],
  },
  {
    id: 'p5-bag-aber-mc',
    topicId: T.sentenceBuilding, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['sentence-building.baglac.aber'],
    familyId: 'p5-bag-aber-mc',
    instruction: '"aber" ne demektir?',
    prompt: 'aber',
    answer: 'ama',
    options: ['ama', 've', 'çünkü', 'ile'],
    pronounce: ['aber'],
  },
  {
    id: 'p5-bag-choose-und-fill',
    topicId: T.sentenceBuilding, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.baglac.und'],
    familyId: 'p5-bag-choose-und',
    instruction: 'Boşluğu doldur (uyumlu bilgi — ekleme):',
    prompt: 'Ich komme aus Sakarya ___ ich wohne in Istanbul.',
    answer: 'und',
    pronounce: ['Ich komme aus Sakarya und ich wohne in Istanbul.'],
  },
  {
    id: 'p5-bag-choose-aber-fill',
    topicId: T.sentenceBuilding, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.baglac.aber'],
    familyId: 'p5-bag-choose-aber',
    instruction: 'Boşluğu doldur (zıtlık vurgusu):',
    prompt: 'Ich komme aus Sakarya, ___ ich wohne in Istanbul.',
    answer: 'aber',
    pronounce: ['Ich komme aus Sakarya, aber ich wohne in Istanbul.'],
  },
  {
    id: 'p5-bag-secim-mc',
    topicId: T.sentenceBuilding, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['sentence-building.baglac.aber', 'sentence-building.baglac.und'],
    familyId: 'p5-bag-secim',
    instruction: 'Hangisi uyar? (öğrenciyim, ama aynı zamanda çalışıyorum da — beklenmedik)',
    prompt: 'Ich bin Student, ___ ich arbeite auch.',
    answer: 'aber',
    options: ['aber', 'und', 'seit', 'mehr'],
    pronounce: ['Ich bin Student, aber ich arbeite auch.'],
  },
  {
    id: 'p5-bag-order',
    topicId: T.sentenceBuilding, legacyDay: 5,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.baglac.aber'],
    familyId: 'p5-bag-order',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / bin / Student, / aber / ich / arbeite / auch.',
    answer: 'Ich bin Student, aber ich arbeite auch.',
    words: ['Ich', 'bin', 'Student,', 'aber', 'ich', 'arbeite', 'auch'],
    pronounce: ['Ich bin Student, aber ich arbeite auch.'],
  },
  {
    id: 'p5-bag-wb-aber-tr-de',
    topicId: T.sentenceBuilding, legacyDay: 5,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['sentence-building.baglac.aber'],
    familyId: 'p5-bag-wb-aber',
    instruction: 'Türkçeden Almancaya kur — Sakarya\'dan geliyorum ama İstanbul\'da oturuyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Sakarya\'dan geliyorum ama İstanbul\'da oturuyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'komme' }, { id: 't3', text: 'aus' }, { id: 't4', text: 'Sakarya,' }, { id: 't5', text: 'aber' },
        { id: 't6', text: 'ich' }, { id: 't7', text: 'wohne' }, { id: 't8', text: 'in' }, { id: 't9', text: 'Istanbul.' }, { id: 't10', text: 'und' },
      ],
      acceptedSequences: [['Ich', 'komme', 'aus', 'Sakarya,', 'aber', 'ich', 'wohne', 'in', 'Istanbul.']],
    },
    answer: 'Ich komme aus Sakarya, aber ich wohne in Istanbul.',
    pronounce: ['Ich komme aus Sakarya, aber ich wohne in Istanbul.'],
  },
  {
    id: 'p5-bag-error',
    topicId: T.sentenceBuilding, legacyDay: 5,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['sentence-building.baglac.aber'],
    familyId: 'p5-bag-error',
    instruction: 'Hata avı — virgül yeri:',
    prompt: 'Ich komme aus Sakarya aber, ich wohne in Istanbul.',
    answer: 'Ich komme aus Sakarya, aber ich wohne in Istanbul.',
    explanation: 'Virgül `aber`den önce gelir, sonra değil.',
    pronounce: ['Ich komme aus Sakarya, aber ich wohne in Istanbul.'],
  },

  /* ---- dann / danach — Sıralama (5) ---- */
  {
    id: 'p10-dann-fill',
    topicId: T.sentenceBuilding, legacyDay: 10,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['sentence-building.dann.dann'],
    familyId: 'p10-dann-dann',
    instruction: 'Bağlacı yaz — Sonra okula gidiyorum.',
    prompt: '___ gehe ich zur Schule. (sonra)',
    answer: 'Dann',
    pronounce: ['Dann gehe ich zur Schule.'],
  },
  {
    id: 'p10-danach-fill',
    topicId: T.sentenceBuilding, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['sentence-building.dann.danach'],
    familyId: 'p10-dann-danach',
    instruction: 'Bağlacı yaz — Sonra eve geliyorum.',
    prompt: '___ komme ich nach Hause. (sonra)',
    answer: 'Danach',
    pronounce: ['Danach komme ich nach Hause.'],
  },
  {
    id: 'p10-dann-order',
    topicId: T.sentenceBuilding, legacyDay: 10,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['sentence-building.dann.v2'],
    familyId: 'p10-dann-order',
    instruction: 'Kelimeleri doğru sıraya diz — Sonra eve geliyorum.',
    answer: 'Danach komme ich nach Hause.',
    pronounce: ['Danach komme ich nach Hause.'],
  },
  {
    id: 'p10-dann-error',
    topicId: T.sentenceBuilding, legacyDay: 10,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['sentence-building.dann.v2'],
    familyId: 'p10-dann-error',
    instruction: 'Söz dizimi yanlış — cümleyi düzelt:',
    prompt: 'Danach ich komme nach Hause.',
    answer: 'Danach komme ich nach Hause.',
    explanation: '`Danach` başa gelirse fiil hemen arkasından ikinci sırada gelir.',
    pronounce: ['Danach komme ich nach Hause.'],
  },
  {
    id: 'p10-dann-alternatif-free',
    topicId: T.sentenceBuilding, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['sentence-building.dann.danach'],
    familyId: 'p10-dann-alternatif',
    instruction: 'İkinci dizilişi yaz — Sonra eve geliyorum (`danach` sonda).',
    prompt: 'Sonra eve geliyorum (danach sonda). → ______',
    answer: 'Ich komme danach nach Hause.',
    pronounce: ['Ich komme danach nach Hause.'],
  },
];
