/**
 * Ayrılabilen Fiiller — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const SEPARABLE_VERBS_EXERCISES: AuthoredExercise[] = [
  /* ---- Ayrılabilen Fiil Nedir? (7) ---- */
  {
    id: 'p10-tre-kural-mc',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['separable-verbs.trennbar.kural'],
    familyId: 'p10-tre-kural',
    instruction: 'Ayrılabilen fiilin kuralı nedir?',
    prompt: 'aufstehen cümlede nasıl bölünür?',
    answer: 'kök ikinci sırada, önek en sonda',
    options: [
      'kök ikinci sırada, önek en sonda',
      'önek ikinci sırada, kök en sonda',
      'fiil hiç bölünmez, tek parça kalır',
      'önek cümleden tamamen düşer',
    ],
    pronounce: ['aufstehen'],
  },
  {
    id: 'p10-tre-bolme-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['separable-verbs.trennbar.kural'],
    familyId: 'p10-tre-bolme',
    instruction: 'Öneki yaz:',
    prompt: 'aufstehen → ___ + stehen',
    answer: 'auf',
    validation: { noTypoTolerance: true },
    pronounce: ['aufstehen'],
  },
  {
    id: 'p10-tre-auf-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['separable-verbs.trennbar.ornek'],
    familyId: 'p10-tre-auf',
    instruction: 'Cümleyi tamamla — Ben saat 7’de kalkıyorum.',
    prompt: 'Ich stehe um 7 Uhr ___.',
    answer: 'auf',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich stehe um 7 Uhr auf.'],
  },
  {
    id: 'p10-tre-wb-aufstehen',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.trennbar.ornek'],
    familyId: 'p10-tre-auf',
    instruction: 'Türkçeden Almancaya kur — Ben saat 7’de kalkıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: "Ben saat 7'de kalkıyorum.",
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'stehe' }, { id: 't3', text: 'um' },
        { id: 't4', text: 'sieben' }, { id: 't5', text: 'Uhr' }, { id: 't6', text: 'auf.' },
        { id: 't7', text: 'an' }, { id: 't8', text: 'ein' },
      ],
      acceptedSequences: [['Ich', 'stehe', 'um', 'sieben', 'Uhr', 'auf.']],
    },
    answer: 'Ich stehe um sieben Uhr auf.',
    pronounce: ['Ich stehe um sieben Uhr auf.'],
  },
  {
    id: 'p10-tre-error-aufstehe',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['separable-verbs.trennbar.kural', 'separable-verbs.trennbar.ornek'],
    familyId: 'p10-tre-error',
    instruction: 'Önek yanlış yerde — cümleyi düzelt:',
    prompt: 'Ich aufstehe um 7 Uhr.',
    answer: 'Ich stehe um 7 Uhr auf.',
    explanation: 'Önek (`auf`) fiilin yanında kalmaz; cümlenin en sonuna gider.',
    pronounce: ['Ich stehe um 7 Uhr auf.'],
  },
  {
    id: 'p10-tre-saat-basta-order',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.trennbar.saat-basta'],
    familyId: 'p10-tre-saat-basta',
    instruction: 'Kelimeleri doğru sıraya diz — Saat 7’de kalkıyorum (saat başta).',
    answer: 'Um 7 Uhr stehe ich auf.',
    pronounce: ['Um 7 Uhr stehe ich auf.'],
  },
  {
    id: 'p10-tre-listen-aufstehen',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.trennbar.ornek'],
    familyId: 'p10-tre-listen',
    instruction: 'Duyduğun cümleyi seç:',
    prompt: 'Ich stehe um sieben Uhr auf.',
    audioText: 'Ich stehe um sieben Uhr auf.',
    answer: 'Ich stehe um sieben Uhr auf.',
    options: ['Ich stehe um sieben Uhr auf.', 'Ich wache um sieben Uhr auf.', 'Ich gehe um sieben Uhr auf.', 'Ich stehe um sieben Uhr an.'],
    audio: { prompt: { text: 'Ich stehe um sieben Uhr auf.', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Temel Kural — Önek Cümlenin Sonuna (11) ---- */
  {
    id: 'p3-af-kural-mc',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.ayrilabilen.kural'],
    familyId: 'p3-af-kural',
    instruction: 'Ayrılabilen fiillerde önek cümlede nereye gider?',
    prompt: 'aufstehen, aufräumen, zurückkommen ...',
    answer: 'Cümlenin en sonuna',
    options: ['Cümlenin en sonuna', 'Fiilden hemen önce', 'Cümlenin en başına', 'Özneden hemen sonra'],
  },
  {
    id: 'p3-af-aufstehen-anlam-mc',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.aufstehen'],
    familyId: 'p3-af-aufstehen-anlam',
    instruction: '"kalkmak" Almancada hangisi?',
    prompt: 'kalkmak',
    answer: 'aufstehen',
    options: ['aufstehen', 'aufräumen', 'zurückkommen', 'einkaufen'],
    pronounce: ['aufstehen'],
  },
  {
    id: 'p3-af-stehe-auf-fill',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.aufstehen'],
    familyId: 'p3-af-stehe-auf',
    instruction: 'Boşluğu doldur — aufstehen ayrılır:',
    prompt: 'Ich stehe jeden Tag früh ___. (her gün erken kalkıyorum)',
    answer: 'auf',
    pronounce: ['Ich stehe jeden Tag früh auf.'],
  },
  {
    id: 'p3-af-order-7uhr',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.aufstehen', 'time.zaman.um-uhr'],
    familyId: 'p3-af-7uhr',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / stehe / um / 7 / Uhr / auf.',
    answer: 'Ich stehe um 7 Uhr auf.',
    words: ['Ich', 'stehe', 'um', '7', 'Uhr', 'auf'],
    pronounce: ['Ich stehe um 7 Uhr auf.'],
  },
  {
    id: 'p3-af-error-aufstehe',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['separable-verbs.aufstehen', 'separable-verbs.ayrilabilen.kural'],
    familyId: 'p3-af-7uhr',
    instruction: 'Hata avı — önek nereye gitmeli?',
    prompt: 'Ich aufstehe jeden Tag früh.',
    answer: 'Ich stehe jeden Tag früh auf.',
    explanation: 'aufstehen ayrılabilen bir fiildir: fiil ikinci sırada çekilir (stehe), önek (auf) cümlenin en sonuna gider.',
    pronounce: ['Ich stehe jeden Tag früh auf.'],
  },
  {
    id: 'p3-af-aufraeumen-anlam-mc',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.aufraeumen'],
    familyId: 'p3-af-aufraeumen-anlam',
    instruction: '"toplamak / düzenlemek" Almancada hangisi?',
    prompt: 'toplamak / düzenlemek',
    answer: 'aufräumen',
    options: ['aufräumen', 'aufstehen', 'anrufen', 'zurückkommen'],
    pronounce: ['aufräumen'],
  },
  {
    id: 'p3-af-raeumt-auf-fill',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.aufraeumen'],
    familyId: 'p3-af-raeumt-auf',
    instruction: 'Boşluğu doldur:',
    prompt: 'Meine Schwester räumt ihr Bett ___. (yatağını topluyor)',
    answer: 'auf',
    pronounce: ['Meine Schwester räumt ihr Bett auf.'],
  },
  {
    id: 'p3-af-builder-bett-tr',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.aufraeumen'],
    familyId: 'p3-af-raeumt-auf',
    instruction: 'Cümleyi kur:',
    prompt: 'Kardeşim yatağını topluyor.',
    answer: 'Meine Schwester räumt ihr Bett auf.',
    words: ['Meine', 'Schwester', 'räumt', 'ihr', 'Bett', 'auf'],
    pronounce: ['Meine Schwester räumt ihr Bett auf.'],
  },
  {
    id: 'p3-af-zurueckkommen-anlam-mc',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.zurueckkommen'],
    familyId: 'p3-af-zurueck-anlam',
    instruction: '"geri dönmek" Almancada hangisi?',
    prompt: 'geri dönmek',
    answer: 'zurückkommen',
    options: ['zurückkommen', 'aufstehen', 'aufräumen', 'einkaufen'],
    pronounce: ['zurückkommen'],
  },
  {
    id: 'p3-af-komme-zurueck-fill',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.zurueckkommen'],
    familyId: 'p3-af-komme-zurueck',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich komme am Abend nach Hause ___. (akşam eve dönüyorum)',
    answer: 'zurück',
    pronounce: ['Ich komme am Abend nach Hause zurück.'],
  },
  {
    id: 'p3-af-wb-zurueck-tr-de',
    topicId: T.separableVerbs, legacyDay: 3,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.zurueckkommen'],
    familyId: 'p3-af-komme-zurueck',
    instruction: 'Türkçeden Almancaya kur — Akşam eve dönüyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Akşam eve dönüyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'komme' }, { id: 't3', text: 'am' }, { id: 't4', text: 'Abend' },
        { id: 't5', text: 'nach' }, { id: 't6', text: 'Hause' }, { id: 't7', text: 'zurück.' }, { id: 't8', text: 'auf' },
      ],
      acceptedSequences: [['Ich', 'komme', 'am', 'Abend', 'nach', 'Hause', 'zurück.']],
    },
    answer: 'Ich komme am Abend nach Hause zurück.',
    pronounce: ['Ich komme am Abend nach Hause zurück.'],
  },

  /* ---- En Önemli Ayrılabilen Fiiller (42) ---- */
  {
    id: 'p10-aufstehen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.aufstehen'],
    familyId: 'p10-verb-aufstehen',
    instruction: '"aufstehen" ne demektir?',
    prompt: 'aufstehen',
    answer: 'yataktan kalkmak',
    options: ['yataktan kalkmak', 'gözlerini açmak', 'giyinmek', 'uyumak'],
    pronounce: ['aufstehen'],
  },
  {
    id: 'p10-aufstehen-du-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.aufstehen'],
    familyId: 'p10-verb-aufstehen',
    instruction: 'Fiili çek — Sen kalkıyorsun.',
    prompt: 'Du ___ auf. (aufstehen)',
    answer: 'stehst',
    pronounce: ['Du stehst auf.'],
  },
  {
    id: 'p10-aufwachen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.aufwachen'],
    familyId: 'p10-verb-aufwachen',
    instruction: '"aufwachen" ne demektir?',
    prompt: 'aufwachen',
    answer: 'uyanmak, gözlerini açmak',
    options: ['uyanmak, gözlerini açmak', 'yataktan kalkmak', 'üstünü çıkarmak', 'kahvaltı etmek'],
    pronounce: ['aufwachen'],
  },
  {
    id: 'p10-aufwachen-wache-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.aufwachen'],
    familyId: 'p10-verb-aufwachen',
    instruction: 'Fiili çek — Saat 7’de uyanıyorum.',
    prompt: 'Ich ___ um 7 Uhr auf. (aufwachen)',
    answer: 'wache',
    pronounce: ['Ich wache um 7 Uhr auf.'],
  },
  {
    id: 'p10-fark-saat-mc',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.uyanma-farki'],
    familyId: 'p10-verb-fark',
    instruction: 'Doğru fiili seç — 07:00, gözlerini açıyorsun (yataktan kalkmadan).',
    prompt: '07:00 — gözlerini açıyorsun',
    answer: 'aufwachen',
    options: ['aufwachen', 'aufstehen', 'anziehen', 'frühstücken'],
    pronounce: ['aufwachen'],
  },
  {
    id: 'p10-fark-yatak-free',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.verb.uyanma-farki'],
    familyId: 'p10-verb-fark',
    instruction: 'Doğru fiili yaz — 07:05, yataktan kalkıyorsun.',
    prompt: '07:05 — yataktan kalkıyorsun. Fiil: ___',
    answer: 'aufstehen',
    pronounce: ['aufstehen'],
  },
  {
    id: 'p10-anziehen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.anziehen'],
    familyId: 'p10-verb-anziehen',
    instruction: '"sich anziehen" ne demektir?',
    prompt: 'sich anziehen',
    answer: 'giyinmek',
    options: ['giyinmek', 'soyunmak', 'yıkanmak', 'uyumak'],
    pronounce: ['sich anziehen'],
  },
  {
    id: 'p10-anziehen-mich-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.anziehen-chunk'],
    familyId: 'p10-verb-anziehen',
    instruction: 'Hazır kalıbı tamamla — Giyiniyorum.',
    prompt: 'Ich ziehe ___ an.',
    answer: 'mich',
    pronounce: ['Ich ziehe mich an.'],
  },
  {
    id: 'p10-anziehen-wb',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.verb.anziehen-chunk'],
    familyId: 'p10-verb-anziehen-wb',
    instruction: 'Türkçeden Almancaya kur — Giyiniyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Giyiniyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'ziehe' }, { id: 't3', text: 'mich' },
        { id: 't4', text: 'an.' }, { id: 't5', text: 'dich' }, { id: 't6', text: 'aus.' },
      ],
      acceptedSequences: [['Ich', 'ziehe', 'mich', 'an.']],
    },
    answer: 'Ich ziehe mich an.',
    pronounce: ['Ich ziehe mich an.'],
  },
  {
    id: 'p10-ausziehen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.ausziehen'],
    familyId: 'p10-verb-ausziehen',
    instruction: '"sich ausziehen" ne demektir?',
    prompt: 'sich ausziehen',
    answer: 'üstünü çıkarmak, soyunmak',
    options: ['üstünü çıkarmak, soyunmak', 'giyinmek', 'duş almak', 'taranmak'],
    pronounce: ['sich ausziehen'],
  },
  {
    id: 'p10-ausziehen-free',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.verb.ausziehen', 'daily-routine.aksam.ausziehen'],
    familyId: 'p10-verb-ausziehen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Üstümü çıkarıyorum. → ______',
    answer: 'Ich ziehe mich aus.',
    pronounce: ['Ich ziehe mich aus.'],
  },
  {
    id: 'p10-einkaufen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.einkaufen'],
    familyId: 'p10-verb-einkaufen',
    instruction: '"einkaufen" ne demektir?',
    prompt: 'einkaufen',
    answer: 'alışveriş yapmak',
    options: ['alışveriş yapmak', 'oda toplamak', 'yemek yapmak', 'para ödemek'],
    pronounce: ['einkaufen'],
  },
  {
    id: 'p10-einkaufen-kaufe-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.einkaufen-cumle'],
    familyId: 'p10-verb-einkaufen',
    instruction: 'Fiili çek — Alışveriş yapıyorum.',
    prompt: 'Ich ___ ein. (einkaufen)',
    answer: 'kaufe',
    pronounce: ['Ich kaufe ein.'],
  },
  {
    id: 'p10-einkaufen-wb',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.verb.einkaufen-cumle'],
    familyId: 'p10-verb-einkaufen-wb',
    instruction: 'Türkçeden Almancaya kur — Alışveriş yapıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Alışveriş yapıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'kaufe' }, { id: 't3', text: 'ein.' },
        { id: 't4', text: 'aus.' }, { id: 't5', text: 'verkaufe' },
      ],
      acceptedSequences: [['Ich', 'kaufe', 'ein.']],
    },
    answer: 'Ich kaufe ein.',
    pronounce: ['Ich kaufe ein.'],
  },
  {
    id: 'p10-aufraeumen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.aufraeumen'],
    familyId: 'p10-verb-aufraeumen',
    instruction: '"aufräumen" ne demektir?',
    prompt: 'aufräumen',
    answer: 'odayı toplamak, düzenlemek',
    options: ['odayı toplamak, düzenlemek', 'alışveriş yapmak', 'cam silmek', 'yemek hazırlamak'],
    pronounce: ['aufräumen'],
  },
  {
    id: 'p10-aufraeumen-raeume-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.aufraeumen-cumle'],
    familyId: 'p10-verb-aufraeumen',
    instruction: 'Fiili çek — Odayı topluyorum.',
    prompt: 'Ich ___ auf. (aufräumen)',
    answer: 'räume',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich räume auf.'],
  },
  {
    id: 'p10-aufraeumen-wb-zimmer',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.verb.aufraeumen-cumle'],
    familyId: 'p10-verb-aufraeumen-wb',
    instruction: 'Türkçeden Almancaya kur — Odamı topluyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Odamı topluyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'räume' }, { id: 't3', text: 'mein' },
        { id: 't4', text: 'Zimmer' }, { id: 't5', text: 'auf.' },
        { id: 't6', text: 'meine' }, { id: 't7', text: 'an.' },
      ],
      acceptedSequences: [['Ich', 'räume', 'mein', 'Zimmer', 'auf.']],
    },
    answer: 'Ich räume mein Zimmer auf.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich räume mein Zimmer auf.'],
  },
  {
    id: 'p10-anrufen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.anrufen'],
    familyId: 'p10-verb-anrufen',
    instruction: '"anrufen" ne demektir?',
    prompt: 'anrufen',
    answer: 'telefonla aramak',
    options: ['telefonla aramak', 'ziyaret etmek', 'davet etmek', 'cevap vermek'],
    pronounce: ['anrufen'],
  },
  {
    id: 'p10-anrufen-rufe-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.anrufen-cumle'],
    familyId: 'p10-verb-anrufen',
    instruction: 'Öneki sona yaz — Seni arıyorum.',
    prompt: 'Ich rufe dich ___. (anrufen)',
    answer: 'an',
    validation: { noTypoTolerance: true },
    pronounce: ['Ich rufe dich an.'],
  },
  {
    id: 'p10-anrufen-free',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.verb.anrufen-cumle'],
    familyId: 'p10-verb-anrufen-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Seni arıyorum. → ______',
    answer: 'Ich rufe dich an.',
    pronounce: ['Ich rufe dich an.'],
  },
  {
    id: 'p10-fernsehen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.fernsehen'],
    familyId: 'p10-verb-fernsehen',
    instruction: '"fernsehen" ne demektir?',
    prompt: 'fernsehen',
    answer: 'televizyon izlemek',
    options: ['televizyon izlemek', 'radyo dinlemek', 'telefonla aramak', 'film çekmek'],
    pronounce: ['fernsehen'],
  },
  {
    id: 'p10-fernsehen-sehe-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.fernsehen-cumle'],
    familyId: 'p10-verb-fernsehen',
    instruction: 'Fiili çek — Akşam televizyon izliyorum.',
    prompt: 'Ich ___ am Abend fern. (fernsehen)',
    answer: 'sehe',
    pronounce: ['Ich sehe am Abend fern.'],
  },
  {
    id: 'p10-fernsehen-siehst-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['separable-verbs.verb.fernsehen-cumle'],
    familyId: 'p10-verb-fernsehen-du',
    instruction: 'Fiili çek — Sen akşam televizyon izliyorsun (e → ie).',
    prompt: 'Du ___ am Abend fern. (fernsehen)',
    answer: 'siehst',
    pronounce: ['Du siehst am Abend fern.'],
  },
  {
    id: 'p10-aufhoeren-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.aufhoeren'],
    familyId: 'p10-verb-aufhoeren',
    instruction: '"aufhören" ne demektir?',
    prompt: 'aufhören',
    answer: 'bırakmak, son vermek',
    options: ['bırakmak, son vermek', 'başlamak', 'devam etmek', 'dinlenmek'],
    pronounce: ['aufhören'],
  },
  {
    id: 'p10-aufhoeren-hoere-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.aufhoeren'],
    familyId: 'p10-verb-aufhoeren',
    instruction: 'Fiili çek — Bırakıyorum.',
    prompt: 'Ich ___ auf. (aufhören)',
    answer: 'höre',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich höre auf.'],
  },
  {
    id: 'p10-vorbereiten-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.vorbereiten'],
    familyId: 'p10-verb-vorbereiten',
    instruction: '"vorbereiten" ne demektir?',
    prompt: 'vorbereiten',
    answer: 'hazırlamak',
    options: ['hazırlamak', 'yemek', 'taşımak', 'satın almak'],
    pronounce: ['vorbereiten'],
  },
  {
    id: 'p10-vorbereiten-bereite-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.vorbereiten'],
    familyId: 'p10-verb-vorbereiten',
    instruction: 'Fiili çek — Kahvaltıyı hazırlıyorum.',
    prompt: 'Ich ___ das Frühstück vor. (vorbereiten)',
    answer: 'bereite',
    pronounce: ['Ich bereite das Frühstück vor.'],
  },
  {
    id: 'p10-einladen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.einladen'],
    familyId: 'p10-verb-einladen',
    instruction: '"einladen" ne demektir?',
    prompt: 'einladen',
    answer: 'davet etmek',
    options: ['davet etmek', 'uğurlamak', 'karşılamak', 'beklemek'],
    pronounce: ['einladen'],
  },
  {
    id: 'p10-einladen-lade-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.einladen'],
    familyId: 'p10-verb-einladen',
    instruction: 'Fiili çek — Seni davet ediyorum.',
    prompt: 'Ich ___ dich ein. (einladen)',
    answer: 'lade',
    pronounce: ['Ich lade dich ein.'],
  },
  {
    id: 'p10-mitbringen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.mitbringen'],
    familyId: 'p10-verb-mitbringen',
    instruction: '"mitbringen" ne demektir?',
    prompt: 'mitbringen',
    answer: 'beraberinde getirmek',
    options: ['beraberinde getirmek', 'geri götürmek', 'ödünç vermek', 'teslim etmek'],
    pronounce: ['mitbringen'],
  },
  {
    id: 'p10-mitbringen-bringe-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.mitbringen'],
    familyId: 'p10-verb-mitbringen',
    instruction: 'Fiili çek — Bir kitap getiriyorum.',
    prompt: 'Ich ___ ein Buch mit. (mitbringen)',
    answer: 'bringe',
    pronounce: ['Ich bringe ein Buch mit.'],
  },
  {
    id: 'p10-aufsetzen-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.aufsetzen'],
    familyId: 'p10-verb-aufsetzen',
    instruction: '"aufsetzen" ne demektir?',
    prompt: 'aufsetzen',
    answer: 'takmak (gözlük, şapka)',
    options: ['takmak (gözlük, şapka)', 'çıkarmak', 'temizlemek', 'kapatmak'],
    pronounce: ['aufsetzen'],
  },
  {
    id: 'p10-aufsetzen-setze-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.aufsetzen'],
    familyId: 'p10-verb-aufsetzen',
    instruction: 'Fiili çek — Gözlüğü takıyorum.',
    prompt: 'Ich ___ die Brille auf. (aufsetzen)',
    answer: 'setze',
    pronounce: ['Ich setze die Brille auf.'],
  },
  {
    id: 'p10-zurueck-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.zurueckkommen'],
    familyId: 'p10-verb-zurueck',
    instruction: '"zurückkommen" ne demektir?',
    prompt: 'zurückkommen',
    answer: 'geri dönmek',
    options: ['geri dönmek', 'erken gelmek', 'geç kalmak', 'yola çıkmak'],
    pronounce: ['zurückkommen'],
  },
  {
    id: 'p10-zurueck-komme-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.zurueckkommen'],
    familyId: 'p10-verb-zurueck',
    instruction: 'Öneki sona yaz — Sonra eve geri dönüyorum.',
    prompt: 'Danach komme ich nach Hause ___. (zurückkommen)',
    answer: 'zurück',
    validation: { keyboardTolerance: true },
    pronounce: ['Danach komme ich nach Hause zurück.'],
  },
  {
    id: 'p10-achtgeben-gebe-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.achtgeben'],
    familyId: 'p10-verb-achtgeben',
    instruction: 'Fiili çek — Dikkat ediyorum.',
    prompt: 'Ich ___ acht. (achtgeben)',
    answer: 'gebe',
    pronounce: ['Ich gebe acht.'],
  },
  {
    id: 'p10-achtgeben-mc-anlam',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.achtgeben'],
    familyId: 'p10-verb-achtgeben',
    instruction: '"achtgeben" ne demektir?',
    prompt: 'achtgeben',
    answer: 'dikkat etmek',
    options: ['dikkat etmek', 'sekiz saymak', 'beklemek', 'vermek'],
    pronounce: ['achtgeben'],
  },
  {
    id: 'p10-gern-machst-mc',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.verb.gern-sorular'],
    familyId: 'p10-verb-gern',
    instruction: '"Was machst du gern?" ne demektir?',
    prompt: 'Was machst du gern?',
    answer: 'Ne yapmayı seversin?',
    options: ['Ne yapmayı seversin?', 'Ne yapıyorsun?', 'Nereye gidiyorsun?', 'Ne seversin?'],
    pronounce: ['Was machst du gern?'],
  },
  {
    id: 'p10-gern-frueh-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.verb.gern-sorular'],
    familyId: 'p10-verb-gern',
    instruction: 'Soruyu tamamla — Erken kalkmayı sever misin?',
    prompt: 'Stehst du gern früh ___?',
    answer: 'auf',
    validation: { noTypoTolerance: true },
    pronounce: ['Stehst du gern früh auf?'],
  },
  {
    id: 'p10-verb-match-prefix',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'separable-verbs.verb.aufstehen',
      'separable-verbs.verb.einkaufen',
      'separable-verbs.verb.fernsehen',
      'separable-verbs.verb.mitbringen',
      'separable-verbs.verb.zurueckkommen',
    ],
    familyId: 'p10-verb-prefix-match',
    instruction: 'Fiili ayrılan önekiyle eşleştir.',
    pairs: [
      { left: 'aufstehen', right: 'auf' },
      { left: 'einkaufen', right: 'ein' },
      { left: 'fernsehen', right: 'fern' },
      { left: 'mitbringen', right: 'mit' },
      { left: 'zurückkommen', right: 'zurück' },
    ],
    pronounce: ['aufstehen', 'einkaufen', 'fernsehen', 'mitbringen', 'zurückkommen'],
  },
  {
    id: 'p10-verb-error-anrufe',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['separable-verbs.verb.anrufen-cumle'],
    familyId: 'p10-verb-error',
    instruction: 'Fiil bölünmemiş — cümleyi düzelt:',
    prompt: 'Ich anrufe dich.',
    answer: 'Ich rufe dich an.',
    explanation: '`anrufen` ayrılır: kök (`rufe`) ikinci sırada, önek (`an`) sondadır.',
    pronounce: ['Ich rufe dich an.'],
  },
  {
    id: 'p10-verb-builder-rufst',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'sentence-builder', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.verb.anrufen-cumle'],
    familyId: 'p10-verb-builder',
    instruction: 'Cümleyi kur:',
    prompt: 'Beni arıyorsun.',
    answer: 'Du rufst mich an.',
    pronounce: ['Du rufst mich an.'],
  },

  /* ---- anrufen — Telefonla Aramak (3) ---- */
  {
    id: 'p7-fii-anrufen-mc',
    topicId: T.separableVerbs, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.fiil.anrufen'],
    familyId: 'p7-fii-anrufen',
    instruction: '"telefonla aramak" Almancada hangisi?',
    prompt: 'telefonla aramak',
    answer: 'anrufen',
    options: ['anrufen', 'kennen', 'geben', 'besuchen'],
    pronounce: ['anrufen'],
  },
  {
    id: 'p7-fii-anrufen-order',
    topicId: T.separableVerbs, legacyDay: 7,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.fiil.anrufen-ayrilabilen'],
    familyId: 'p7-fii-anrufen-order',
    instruction: 'Kelimeleri doğru sıraya diz — Seni arıyorum.',
    answer: 'Ich rufe dich an.',
    pronounce: ['Ich rufe dich an.'],
  },
  {
    id: 'p7-fii-anrufen-fill-uns',
    topicId: T.separableVerbs, legacyDay: 7,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['separable-verbs.fiil.anrufen-ayrilabilen'],
    familyId: 'p7-fii-anrufen-uns',
    instruction: 'Ayrılabilen fiilin önekini doğru yere yaz:',
    prompt: 'Du rufst uns ___. (anrufen)',
    answer: 'an',
    validation: { noTypoTolerance: true },
    pronounce: ['Du rufst uns an.'],
  },

  /* ---- Ayrılan / Ayrılmayan Fiil Karşılaştırması (5) ---- */
  {
    id: 'p10-karsi-mc-besuchen',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.karsi.besuchen'],
    familyId: 'p10-karsi-besuchen',
    instruction: 'Trennbar mı, değil mi?',
    prompt: 'besuchen — ayrılır mı?',
    answer: 'hayır, ayrılmaz',
    options: ['hayır, ayrılmaz', 'evet, ayrılır: be + suchen', 'sadece soruda ayrılır', 'sadece olumsuzda ayrılır'],
  },
  {
    id: 'p10-karsi-besuche-fill',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['separable-verbs.karsi.besuchen'],
    familyId: 'p10-karsi-besuche',
    instruction: 'Fiili tek parça yaz — Seni ziyaret ediyorum.',
    prompt: 'Ich ___ dich. (besuchen)',
    answer: 'besuche',
    pronounce: ['Ich besuche dich.'],
  },
  {
    id: 'p10-karsi-error-be',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['separable-verbs.karsi.besuchen'],
    familyId: 'p10-karsi-error',
    instruction: 'Yanlış bölünmüş — cümleyi düzelt:',
    prompt: 'Ich suche dich be.',
    answer: 'Ich besuche dich.',
    explanation: '`besuchen` ayrılmaz; fiil tek parça kalır.',
    pronounce: ['Ich besuche dich.'],
  },
  {
    id: 'p10-karsi-prefix-mc',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['separable-verbs.karsi.ipucu'],
    familyId: 'p10-karsi-prefix',
    instruction: 'Hangisi bu derste geçen ayrılmayan başlangıçlardandır?',
    prompt: 'be- / emp- / er- / ver- / zer-',
    answer: 'ver- (vergessen)',
    options: ['ver- (vergessen)', 'an- (anrufen)', 'auf- (aufstehen)', 'mit- (mitbringen)'],
  },
  {
    id: 'p10-karsi-match-alti',
    topicId: T.separableVerbs, legacyDay: 10,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'separable-verbs.karsi.besuchen',
      'separable-verbs.karsi.liste',
      'separable-verbs.karsi.ipucu',
    ],
    familyId: 'p10-karsi-match',
    instruction: 'Ayrılmayan fiili Türkçesiyle eşleştir.',
    pairs: [
      { left: 'besuchen', right: 'ziyaret etmek' },
      { left: 'empfinden', right: 'hissetmek' },
      { left: 'erklären', right: 'açıklamak' },
      { left: 'vergessen', right: 'unutmak' },
      { left: 'zerstören', right: 'tahrip etmek' },
      { left: 'zerreißen', right: 'yırtmak' },
    ],
    pronounce: ['besuchen', 'empfinden', 'erklären', 'vergessen', 'zerstören', 'zerreißen'],
  },

  /* ---- Soru ve olumsuzluk ---- */
  {
    id: 'sep-frage-frueh-tr',
    topicId: T.separableVerbs,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.frage', 'separable-verbs.verb.aufstehen'],
    familyId: 'sep-frage-frueh',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Erken kalkar mısın?',
    answer: 'Stehst du früh auf?',
    validation: { keyboardTolerance: true },
    explanation: 'Soruda çekimli kök (`stehst`) başa gelir; önek (`auf`) yine en sonda.',
    pronounce: ['Stehst du früh auf?'],
  },
  {
    id: 'sep-frage-anrufen',
    topicId: T.separableVerbs,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.frage', 'separable-verbs.verb.anrufen'],
    familyId: 'sep-frage-anrufen',
    instruction: 'Soruya çevir:',
    prompt: 'Du rufst mich an.',
    answer: 'Rufst du mich an?',
    pronounce: ['Rufst du mich an?'],
  },
  {
    id: 'sep-nicht-anrufen-tr',
    topicId: T.separableVerbs,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['separable-verbs.nicht', 'separable-verbs.verb.anrufen'],
    familyId: 'sep-nicht-anrufen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Seni bugün aramıyorum.',
    answer: 'Ich rufe dich heute nicht an.',
    explanation: '`nicht` önekten (`an`) önce gelir; önek her zaman en sonda kalır.',
    pronounce: ['Ich rufe dich heute nicht an.'],
  },
  {
    id: 'sep-nicht-mc',
    topicId: T.separableVerbs,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.nicht'],
    familyId: 'sep-nicht-mc',
    instruction: 'Doğru olumsuz cümle hangisi? — Bugün kalkmıyorum.',
    answer: 'Ich stehe heute nicht auf.',
    options: ['Ich stehe heute nicht auf.', 'Ich stehe heute auf nicht.', 'Ich nicht stehe heute auf.', 'Ich aufstehe heute nicht.'],
    pronounce: ['Ich stehe heute nicht auf.'],
  },

  /* ---- Modalverb ile kullanım ---- */
  {
    id: 'sep-einnehmen-mc',
    topicId: T.separableVerbs,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['separable-verbs.einnehmen'],
    familyId: 'sep-einnehmen',
    instruction: 'Anlamını seç:',
    prompt: 'einnehmen',
    answer: '(ilaç) almak',
    options: ['(ilaç) almak', 'davet etmek', 'getirmek', 'takmak'],
    pronounce: ['einnehmen'],
  },
  {
    id: 'sep-mit-modal-fill',
    topicId: T.separableVerbs,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['separable-verbs.mit-modal', 'separable-verbs.verb.aufstehen'],
    familyId: 'sep-mit-modal-fill',
    instruction: 'Fiili tek kelime olarak yaz — Erken kalkmak istiyorum.',
    prompt: 'Ich will früh ___. (aufstehen)',
    answer: 'aufstehen',
    validation: { noTypoTolerance: true },
    explanation: 'Modalverb varsa ayrılabilen fiil bölünmez: mastar tek kelime, en sonda.',
    pronounce: ['Ich will früh aufstehen.'],
  },
  {
    id: 'sep-mit-modal-error',
    topicId: T.separableVerbs,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['separable-verbs.mit-modal', 'separable-verbs.verb.einkaufen'],
    familyId: 'sep-mit-modal-error',
    instruction: 'Hatayı düzelt:',
    prompt: 'Ich möchte Lebensmittel kaufen ein.',
    answer: 'Ich möchte Lebensmittel einkaufen.',
    validation: { keyboardTolerance: true },
    explanation: 'Modalverb cümlesinde `einkaufen` bölünmez; mastar tek kelime olarak en sonda.',
    pronounce: ['Ich möchte Lebensmittel einkaufen.'],
  },
  {
    id: 'sep-mit-modal-fernsehen-wb',
    topicId: T.separableVerbs,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['separable-verbs.mit-modal', 'separable-verbs.verb.fernsehen'],
    familyId: 'sep-mit-modal-fernsehen',
    instruction: 'Kutucuklarla kur — Bugün televizyon izlemek istemiyorum.',
    answer: 'Ich will heute nicht fernsehen.',
    wordBank: {
      direction: 'tr-to-de', sourceText: 'Bugün televizyon izlemek istemiyorum.', targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Ich' }, { id: 't2', text: 'will' }, { id: 't3', text: 'heute' }, { id: 't4', text: 'nicht' },
        { id: 't5', text: 'fernsehen.' }, { id: 't6', text: 'sehe' }, { id: 't7', text: 'fern.' },
      ],
      acceptedSequences: [['Ich', 'will', 'heute', 'nicht', 'fernsehen.']],
    },
    pronounce: ['Ich will heute nicht fernsehen.'],
  },
];
