/**
 * Alışveriş ve Fiyatlar — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const SHOPPING_EXERCISES: AuthoredExercise[] = [
  /* ---- Alışveriş ve Sıklık (17) ---- */
  {
    id: 'p3-gh-kaufen-mc',
    topicId: T.shopping, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['shopping.alisveris.kelime'],
    familyId: 'p3-gh-kaufen',
    instruction: '"kaufen" ne demektir?',
    prompt: 'kaufen',
    answer: 'satın almak',
    options: ['satın almak', 'satmak', 'giymek', 'temizlemek'],
    pronounce: ['kaufen'],
  },
  {
    id: 'p3-gh-hose-fill',
    topicId: T.shopping, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['shopping.alisveris.kelime'],
    familyId: 'p3-gh-hose',
    instruction: 'Boşluğu doldur (die Hose, dişil):',
    prompt: '___ Hose ist ein bisschen teuer. (bu pantolon biraz pahalı)',
    answer: 'Die',
    pronounce: ['Die Hose ist ein bisschen teuer.'],
  },
  {
    id: 'p3-gh-error-das-hose',
    topicId: T.shopping, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['shopping.alisveris.kelime'],
    familyId: 'p3-gh-hose',
    instruction: 'Hata avı — die Hose hangi cinsiyettir?',
    prompt: 'Das hose ist ein Bisschen teuer.',
    answer: 'Die Hose ist ein bisschen teuer.',
    explanation: '"die Hose" dişildir (das değil); isimler her zaman büyük harfle, "bisschen" ise küçük harfle yazılır.',
    pronounce: ['Die Hose ist ein bisschen teuer.'],
  },
  {
    id: 'p3-gh-einkaufszentrum-fill',
    topicId: T.shopping, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['shopping.alisveris.kelime'],
    familyId: 'p3-gh-einkaufszentrum',
    instruction: 'Boşluğu doldur:',
    prompt: 'Dann gehen wir ___ Einkaufszentrum. (sonra alışverişe gidiyoruz)',
    answer: 'ins',
    pronounce: ['Dann gehen wir ins Einkaufszentrum.'],
  },
  {
    id: 'p3-gh-freund-kauft-buch-fill',
    topicId: T.shopping, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['shopping.alisveris.kelime'],
    familyId: 'p3-gh-freund-kauft-buch',
    instruction: 'Boşluğu doldur (kaufen):',
    prompt: 'Mein Freund ___ ein Buch. (arkadaşım bir kitap alıyor)',
    answer: 'kauft',
    pronounce: ['Mein Freund kauft ein Buch.'],
  },
  {
    id: 'p7-ali-frage-mc',
    topicId: T.shopping, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['shopping.kaufen.frage'],
    familyId: 'p7-ali-frage',
    instruction: '"Was kaufst du oft?" ne demektir?',
    prompt: 'Was kaufst du oft?',
    answer: 'Sık sık ne satın alırsın?',
    options: ['Sık sık ne satın alırsın?', 'Ne kadar ödüyorsun?', 'Nereden alışveriş yapıyorsun?', 'Ne zaman alışveriş yaparsın?'],
    pronounce: ['Was kaufst du oft?'],
  },
  {
    id: 'p7-ali-siklik-match',
    topicId: T.shopping, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'shopping.siklik.immer',
      'shopping.siklik.meistens',
      'shopping.siklik.oft',
      'shopping.siklik.manchmal',
      'shopping.siklik.nie',
    ],
    familyId: 'p7-ali-siklik-match',
    instruction: 'Sıklık kelimesini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'immer', right: 'her zaman' },
      { left: 'meistens', right: 'çoğunlukla' },
      { left: 'oft', right: 'sık sık' },
      { left: 'manchmal', right: 'bazen' },
      { left: 'nie', right: 'asla' },
    ],
    pronounce: ['immer', 'meistens', 'oft', 'manchmal', 'nie'],
  },
  {
    id: 'p7-ali-nie-mc',
    topicId: T.shopping, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['shopping.siklik.nie'],
    familyId: 'p7-ali-nie',
    instruction: 'Hangisi "asla, hiç" demektir?',
    prompt: 'asla, hiç',
    answer: 'nie',
    options: ['nie', 'immer', 'oft', 'manchmal'],
    pronounce: ['nie'],
  },
  {
    id: 'p7-ali-siklik-order-mc',
    topicId: T.shopping, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['shopping.siklik.immer', 'shopping.siklik.manchmal', 'shopping.siklik.nie'],
    familyId: 'p7-ali-siklik-order',
    instruction: 'Hangi sıralama "çoktan aza" doğrudur?',
    prompt: 'sıklık ölçeği',
    answer: 'immer → meistens → oft → manchmal → nie',
    options: [
      'immer → meistens → oft → manchmal → nie',
      'nie → immer → oft → manchmal → meistens',
      'oft → nie → immer → meistens → manchmal',
      'manchmal → immer → nie → oft → meistens',
    ],
  },
  {
    id: 'p7-ali-immer-obst-fill',
    topicId: T.shopping, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['shopping.siklik.cumlede', 'food.yiyecek.temel'],
    familyId: 'p7-ali-immer-obst',
    instruction: 'Boşluğu doldur — "her zaman" kelimesini yaz:',
    prompt: 'Ich kaufe ___ Obst. (Her zaman meyve alırım.)',
    answer: 'immer',
    pronounce: ['Ich kaufe immer Obst.'],
  },
  {
    id: 'p7-ali-manchmal-tr-de',
    topicId: T.shopping, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['shopping.siklik.manchmal', 'food.yiyecek.temel'],
    familyId: 'p7-ali-manchmal',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bazen şarap alırım. → ______',
    answer: 'Ich kaufe manchmal Wein.',
    pronounce: ['Ich kaufe manchmal Wein.'],
  },
  {
    id: 'p7-ali-nie-tr-de',
    topicId: T.shopping, legacyDay: 7,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['shopping.siklik.nie'],
    familyId: 'p7-ali-nie-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Hiç un almam. → ______',
    answer: 'Ich kaufe nie Mehl.',
    pronounce: ['Ich kaufe nie Mehl.'],
  },
  {
    id: 'p7-ali-meistens-order',
    topicId: T.shopping, legacyDay: 7,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['shopping.siklik.meistens', 'food.yiyecek.temel'],
    familyId: 'p7-ali-meistens-order',
    instruction: 'Kelimeleri doğru sıraya diz — Çoğunlukla sebze alırım.',
    answer: 'Ich kaufe meistens Gemüse.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich kaufe meistens Gemüse.'],
  },
  {
    id: 'p7-ali-pro-woche-fill',
    topicId: T.shopping, legacyDay: 7,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['shopping.kaufen.pro-woche'],
    familyId: 'p7-ali-pro-woche',
    instruction: 'Boşluğu doldur — "haftada iki kez" ifadesini tamamla:',
    prompt: 'Ich kaufe pro Woche ___. (haftada iki kez)',
    answer: 'zweimal',
    pronounce: ['Ich kaufe pro Woche zweimal.'],
  },
  {
    id: 'p7-ali-zettel-wagen-match',
    topicId: T.shopping, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['shopping.alisveris.einkaufszettel', 'shopping.alisveris.einkaufswagen'],
    familyId: 'p7-ali-zettel-wagen',
    instruction: 'Alışveriş kelimesini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'der Einkaufszettel', right: 'alışveriş listesi' },
      { left: 'der Einkaufswagen', right: 'alışveriş arabası' },
    ],
    pronounce: ['der Einkaufszettel', 'der Einkaufswagen'],
  },
  {
    id: 'p7-ali-ifadeler-mc',
    topicId: T.shopping, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['shopping.alisveris.ifadeler'],
    familyId: 'p7-ali-ifadeler',
    instruction: 'Satıcı "Sonst noch etwas?" diyor. Ne soruyor?',
    prompt: 'Sonst noch etwas?',
    answer: 'Başka bir şey var mı?',
    options: ['Başka bir şey var mı?', 'Kaç para?', 'Nakit mi kart mı?', 'Poşet ister misiniz?'],
    pronounce: ['Sonst noch etwas?'],
  },
  {
    id: 'p7-ali-natuerlich-fill',
    topicId: T.shopping, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['shopping.alisveris.ifadeler'],
    familyId: 'p7-ali-natuerlich',
    instruction: 'Boşluğu doldur — "tabii ki" kelimesini yaz:',
    prompt: '___ (Tabii ki.)',
    answer: 'Natürlich',
    validation: { keyboardTolerance: true },
    pronounce: ['Natürlich.'],
  },

  /* ---- Miktar ve Paket Kelimeleri (10) ---- */
  {
    id: 'p3-mk-flaschen-mc',
    topicId: T.shopping, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['shopping.miktar.sise'],
    familyId: 'p3-mk-flaschen',
    instruction: '"iki şişe su" nasıl söylenir?',
    prompt: 'iki şişe su',
    answer: 'zwei Flaschen Wasser',
    options: ['zwei Flaschen Wasser', 'zwei Flasche Wasser', 'zwei Flaschen Wassers', 'zwei Flasche Wassers'],
  },
  {
    id: 'p3-mk-flaschen-fill',
    topicId: T.shopping, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['shopping.miktar.sise'],
    familyId: 'p3-mk-flaschen-fill',
    instruction: 'Boşluğu doldur (Flasche çoğul olur, Wasser tekil kalır):',
    prompt: 'Ich kaufe zwei ___ Wasser. (iki şişe su alıyorum)',
    answer: 'Flaschen',
    pronounce: ['Ich kaufe zwei Flaschen Wasser.'],
  },
  {
    id: 'p3-mk-error-flasche',
    topicId: T.shopping, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['shopping.miktar.sise'],
    familyId: 'p3-mk-flaschen-fill',
    instruction: 'Hata avı — sayıdan sonra çoğul mu?',
    prompt: 'Ich kaufe zwei Flasche Wasser.',
    answer: 'Ich kaufe zwei Flaschen Wasser.',
    explanation: '"zwei" gibi 1den büyük bir sayıdan sonra kap ismi (Flasche) çoğula döner: Flaschen.',
    pronounce: ['Ich kaufe zwei Flaschen Wasser.'],
  },
  {
    id: 'p7-mik-match',
    topicId: T.shopping, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: [
      'shopping.miktar.flasche',
      'shopping.miktar.packung',
      'shopping.miktar.dose',
      'shopping.miktar.becher',
    ],
    familyId: 'p7-mik-match',
    instruction: 'Miktar kalıbını Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'eine Flasche', right: 'bir şişe' },
      { left: 'eine Packung', right: 'bir paket' },
      { left: 'eine Dose', right: 'bir kutu (konserve)' },
      { left: 'ein Becher', right: 'bir kutu (krema)' },
    ],
    pronounce: ['eine Flasche', 'eine Packung', 'eine Dose', 'ein Becher'],
  },
  {
    id: 'p7-mik-becher-fill',
    topicId: T.shopping, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['shopping.miktar.becher', 'food.yiyecek.sahne'],
    familyId: 'p7-mik-becher',
    instruction: 'Boşluğu doldur:',
    prompt: 'ein Becher ___ (bir kutu krema)',
    answer: 'Sahne',
    pronounce: ['ein Becher Sahne'],
  },
  {
    id: 'p7-mik-dose-tr-de',
    topicId: T.shopping, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['shopping.miktar.dose', 'food.yiyecek.sahne'],
    familyId: 'p7-mik-dose',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'bir kutu domates → ______',
    answer: 'eine Dose Tomaten',
    pronounce: ['eine Dose Tomaten'],
  },
  {
    id: 'p7-mik-packung-tr-de',
    topicId: T.shopping, legacyDay: 7,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['shopping.miktar.packung'],
    familyId: 'p7-mik-packung',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'bir paket un → ______',
    answer: 'eine Packung Mehl',
    pronounce: ['eine Packung Mehl'],
  },
  {
    id: 'p7-mik-bund-fill',
    topicId: T.shopping, legacyDay: 7,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['shopping.miktar.bund', 'food.yiyecek.zwiebel'],
    familyId: 'p7-mik-bund',
    instruction: 'Boşluğu doldur — "demet" kelimesini yaz:',
    prompt: 'ein ___ Frühlingszwiebeln (bir demet taze soğan)',
    answer: 'Bund',
    pronounce: ['ein Bund Frühlingszwiebeln'],
  },
  {
    id: 'p7-mik-portion-mc',
    topicId: T.shopping, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['shopping.miktar.portion', 'food.yiyecek.haehnchen'],
    familyId: 'p7-mik-portion',
    instruction: '"eine Portion Gemüsesuppe" ne demektir?',
    prompt: 'eine Portion Gemüsesuppe',
    answer: 'bir porsiyon sebze çorbası',
    options: ['bir porsiyon sebze çorbası', 'bir kutu sebze konservesi', 'bir paket sebze', 'bir şişe sebze suyu'],
    pronounce: ['eine Portion Gemüsesuppe'],
  },
  {
    id: 'p7-mik-artikel-mc',
    topicId: T.shopping, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['shopping.miktar.artikel'],
    familyId: 'p7-mik-artikel',
    instruction: '`ein` mi `eine` mi? Doğru olanı seç.',
    prompt: '___ Flasche Wasser (der Becher / die Flasche)',
    answer: 'eine',
    options: ['eine', 'ein', 'einen', 'einem'],
    explanation: '`die Flasche` dişil olduğu için `eine Flasche`.',
    pronounce: ['eine Flasche Wasser'],
  },

  /* ---- Fiyat Sormak (6) ---- */
  {
    id: 'p7-fiy-kosten-mc',
    topicId: T.shopping, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['shopping.fiyat.kosten'],
    familyId: 'p7-fiy-kosten',
    instruction: '"kosten" ne demektir?',
    prompt: 'kosten',
    answer: 'fiyatında olmak (kaç para tutmak)',
    options: ['fiyatında olmak (kaç para tutmak)', 'satın almak', 'ödemek', 'saymak'],
    pronounce: ['kosten'],
  },
  {
    id: 'p7-fiy-was-kostet-fill',
    topicId: T.shopping, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['shopping.fiyat.was-kostet'],
    familyId: 'p7-fiy-was-kostet',
    instruction: 'Soruyu tamamla:',
    prompt: 'Was ___ das? (Bu kaç para?)',
    answer: 'kostet',
    pronounce: ['Was kostet das?'],
  },
  {
    id: 'p7-fiy-antwort-wb',
    topicId: T.shopping, legacyDay: 7,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['shopping.fiyat.antwort'],
    familyId: 'p7-fiy-antwort',
    instruction: 'Türkçeden Almancaya kur — Bu beş euro.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Bu beş euro.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Das' }, { id: 't2', text: 'kostet' }, { id: 't3', text: 'fünf' }, { id: 't4', text: 'Euro.' },
        { id: 't5', text: 'ist' }, { id: 't6', text: 'vier' },
      ],
      acceptedSequences: [['Das', 'kostet', 'fünf', 'Euro.'], ['Das', 'ist', 'fünf', 'Euro.']],
    },
    answer: 'Das kostet fünf Euro.',
    validation: { keyboardTolerance: true },
    pronounce: ['Das kostet fünf Euro.'],
  },
  {
    id: 'p7-fiy-wie-viel-tr-de',
    topicId: T.shopping, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['shopping.fiyat.wie-viel'],
    familyId: 'p7-fiy-wie-viel',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bir kilo domates kaç para? → ______',
    answer: 'Wie viel kostet ein Kilo Tomaten?',
    pronounce: ['Wie viel kostet ein Kilo Tomaten?'],
  },
  {
    id: 'p7-fiy-teuer-fill',
    topicId: T.shopping, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['shopping.fiyat.teuer', 'food.yiyecek.temel'],
    familyId: 'p7-fiy-teuer',
    instruction: 'Boşluğu doldur — "pahalı" sıfatını yaz:',
    prompt: 'Der Wein ist ___. (Şarap pahalı.)',
    answer: 'teuer',
    pronounce: ['Der Wein ist teuer.'],
  },
  {
    id: 'p10-rev-kosten-wb',
    topicId: T.shopping, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['shopping.wort.kosten'],
    familyId: 'p10-rev-kosten',
    instruction: 'Türkçeden Almancaya kur — Ayda sadece 180 euro.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Ayda sadece 180 euro.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Es' }, { id: 't2', text: 'kostet' }, { id: 't3', text: 'nur' },
        { id: 't4', text: '180' }, { id: 't5', text: 'Euro' }, { id: 't6', text: 'im' },
        { id: 't7', text: 'Monat.' }, { id: 't8', text: 'teuer' },
      ],
      acceptedSequences: [['Es', 'kostet', 'nur', '180', 'Euro', 'im', 'Monat.']],
    },
    answer: 'Es kostet nur 180 Euro im Monat.',
    pronounce: ['Es kostet nur 180 Euro im Monat.'],
  },

  /* ---- brauchen — İhtiyaç Duymak (3) ---- */
  {
    id: 'p7-bra-frage-mc',
    topicId: T.shopping, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['shopping.brauchen.frage'],
    familyId: 'p7-bra-frage',
    instruction: '"Was brauchst du?" ne demektir?',
    prompt: 'Was brauchst du?',
    answer: 'Neye ihtiyacın var?',
    options: ['Neye ihtiyacın var?', 'Ne yapıyorsun?', 'Ne alıyorsun?', 'Ne kadar lazım?'],
    pronounce: ['Was brauchst du?'],
  },
  {
    id: 'p7-bra-antwort-fill',
    topicId: T.shopping, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['shopping.brauchen.antwort'],
    familyId: 'p7-bra-antwort',
    instruction: 'Fiili doğru çek:',
    prompt: 'Ich ___ den Apfel. (brauchen)',
    answer: 'brauche',
    pronounce: ['Ich brauche den Apfel.'],
  },
  {
    id: 'p7-bra-kein-tr-de',
    topicId: T.shopping, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['shopping.brauchen.kein'],
    familyId: 'p7-bra-kein',
    instruction: 'Türkçeden Almancaya çevir (olumsuz cevap):',
    prompt: 'Hayır, una ihtiyacım yok. → ______',
    answer: 'Nein, ich brauche kein Mehl.',
    pronounce: ['Nein, ich brauche kein Mehl.'],
  },

  /* ---- kaufen ↔ verkaufen ---- */
  {
    id: 'shop-verkaufen-mc',
    topicId: T.shopping,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['shopping.verkaufen'],
    familyId: 'shop-verkaufen',
    instruction: 'Anlamını seç:',
    prompt: 'verkaufen',
    answer: 'satmak',
    options: ['satmak', 'satın almak', 'alışveriş yapmak', 'göndermek'],
    pronounce: ['verkaufen'],
  },
  {
    id: 'shop-verkaufen-tr',
    topicId: T.shopping,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['shopping.verkaufen', 'pronouns.iyelik.sein-onun'],
    familyId: 'shop-verkaufen-auto',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Babam arabasını satıyor.',
    answer: 'Mein Vater verkauft sein Auto.',
    pronounce: ['Mein Vater verkauft sein Auto.'],
  },
  {
    id: 'shop-kaufen-verkaufen-fill',
    topicId: T.shopping,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['shopping.verkaufen', 'shopping.alisveris.kelime', 'vocabulary.ticket'],
    familyId: 'shop-kaufen-ticket',
    instruction: 'Doğru fiili yaz — Bir bilet satın alıyorum.',
    prompt: 'Ich ___ ein Ticket. (satın almak)',
    answer: 'kaufe',
    validation: { noTypoTolerance: true },
    explanation: '`kaufen` = satın almak, `verkaufen` = satmak.',
    pronounce: ['Ich kaufe ein Ticket.'],
  },
];
