/**
 * Saatler ve Zaman — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const TIME_EXERCISES: AuthoredExercise[] = [
  /* ---- Saat Kaç? — Wie spät ist es? (5) ---- */
  {
    id: 'p10-uhr-frage-mc',
    topicId: T.time, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['time.soru.wie-spaet'],
    familyId: 'p10-uhr-frage',
    instruction: 'Hangisi "Saat kaç?" demektir?',
    prompt: 'Saat kaç?',
    answer: 'Wie spät ist es?',
    options: ['Wie spät ist es?', 'Wie viel Uhr stehst du auf?', 'Wann gehst du ins Bett?', 'Was machst du gern?'],
    pronounce: ['Wie spät ist es?'],
  },
  {
    id: 'p10-uhr-beide-mc',
    topicId: T.time, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['time.soru.wie-viel'],
    familyId: 'p10-uhr-beide',
    instruction: '"Wie viel Uhr ist es?" ne demektir?',
    prompt: 'Wie viel Uhr ist es?',
    answer: 'Saat kaç?',
    options: ['Saat kaç?', 'Saat kaçta?', 'Ne zaman?', 'Kaç saat?'],
    pronounce: ['Wie viel Uhr ist es?'],
  },
  {
    id: 'p10-uhr-match-einheiten',
    topicId: T.time, legacyDay: 10,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['time.soru.einheiten'],
    familyId: 'p10-uhr-match',
    instruction: 'Saat kelimesini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'die Uhr', right: 'saat (alet)' },
      { left: 'die Stunde', right: 'saat (süre)' },
      { left: 'die Minute', right: 'dakika' },
      { left: 'die Sekunde', right: 'saniye' },
      { left: 'das Viertel', right: 'çeyrek' },
    ],
    pronounce: ['die Uhr', 'die Stunde', 'die Minute', 'die Sekunde'],
  },
  {
    id: 'p10-uhr-listen-frage',
    topicId: T.time, legacyDay: 10,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['time.soru.wie-spaet'],
    familyId: 'p10-uhr-listen',
    instruction: 'Duyduğun soruyu seç:',
    prompt: 'Wie spät ist es?',
    audioText: 'Wie spät ist es?',
    answer: 'Wie spät ist es?',
    options: ['Wie spät ist es?', 'Wie viel Uhr ist es?', 'Wann stehst du auf?', 'Was machst du gern?'],
    audio: { prompt: { text: 'Wie spät ist es?', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p10-uhr-de-tr-wb',
    topicId: T.time, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['time.soru.wie-viel'],
    familyId: 'p10-uhr-de-tr',
    instruction: 'Almancadan Türkçeye kur — Saat kaç?',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Wie viel Uhr ist es?',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Saat' }, { id: 't2', text: 'kaç?' },
        { id: 't3', text: 'kaçta?' }, { id: 't4', text: 'Ne' },
      ],
      acceptedSequences: [['Saat', 'kaç?']],
    },
    answer: 'Saat kaç?',
    audio: { prompt: { text: 'Wie viel Uhr ist es?', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Wie viel Uhr ist es?'],
  },

  /* ---- Resmî Saatler (4) ---- */
  {
    id: 'p10-resmi-de-tr-wb',
    topicId: T.time, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['time.resmi.ornek'],
    familyId: 'p10-resmi-de-tr',
    instruction: 'Almancadan Türkçeye kur — Saat yedi kırk.',
    wordBank: {
      direction: 'de-to-tr',
      sourceText: 'Es ist sieben Uhr vierzig.',
      targetLanguage: 'tr',
      tokens: [
        { id: 't1', text: 'Saat' }, { id: 't2', text: 'yedi' }, { id: 't3', text: 'kırk.' },
        { id: 't4', text: 'yetmiş.' }, { id: 't5', text: 'yirmi.' },
      ],
      acceptedSequences: [['Saat', 'yedi', 'kırk.']],
    },
    answer: 'Saat yedi kırk.',
    audio: { prompt: { text: 'Es ist sieben Uhr vierzig.', language: 'de-DE', role: 'prompt' } },
    pronounce: ['Es ist sieben Uhr vierzig.'],
  },
  {
    id: 'p10-resmi-zwanzig-fill',
    topicId: T.time, legacyDay: 10,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['time.resmi.kural'],
    familyId: 'p10-resmi-2035',
    instruction: 'Resmî okunuşu tamamla — 20:35:',
    prompt: 'Es ist ___ Uhr fünfunddreißig. (20:35)',
    answer: 'zwanzig',
    pronounce: ['Es ist zwanzig Uhr fünfunddreißig.'],
  },
  {
    id: 'p10-resmi-dictation-820',
    topicId: T.time, legacyDay: 10,
    type: 'dictation', difficulty: 'medium', skill: 'production',
    conceptIds: ['time.resmi.ornek'],
    familyId: 'p10-resmi-dictation',
    instruction: 'Duyduğun resmî saati aynen yaz:',
    audioText: 'Es ist acht Uhr zwanzig.',
    answer: 'Es ist acht Uhr zwanzig.',
    audio: { prompt: { text: 'Es ist acht Uhr zwanzig.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p10-resmi-listen-740',
    topicId: T.time, legacyDay: 10,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['time.resmi.kural'],
    familyId: 'p10-resmi-listen',
    instruction: 'Duyduğun resmî saati seç:',
    prompt: 'Es ist sieben Uhr vierzig.',
    audioText: 'Es ist sieben Uhr vierzig.',
    answer: 'Es ist sieben Uhr vierzig.',
    options: ['Es ist sieben Uhr vierzig.', 'Es ist sieben Uhr zwanzig.', 'Es ist acht Uhr vierzig.', 'Es ist halb acht.'],
    audio: { prompt: { text: 'Es ist sieben Uhr vierzig.', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Günlük Saatler (5) ---- */
  {
    id: 'p10-gunluk-vor-fill',
    topicId: T.time, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['time.gunluk.nach-vor'],
    familyId: 'p10-gunluk-vor',
    instruction: 'Doğru kelimeyi yaz — `von` DEĞİL:',
    prompt: 'Es ist zwanzig ___ vier. (kala)',
    answer: 'vor',
    validation: { noTypoTolerance: true },
    pronounce: ['Es ist zwanzig vor vier.'],
  },
  {
    id: 'p10-gunluk-viertel-mc',
    topicId: T.time, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['time.gunluk.viertel'],
    familyId: 'p10-gunluk-viertel',
    instruction: '18:15 günlük konuşmada nasıldır?',
    prompt: '18:15 → günlük',
    answer: 'Es ist Viertel nach sechs.',
    options: ['Es ist Viertel nach sechs.', 'Es ist Viertel vor sechs.', 'Es ist halb sieben.', 'Es ist sechs Uhr fünfzehn.'],
    pronounce: ['Es ist Viertel nach sechs.'],
  },
  {
    id: 'p10-gunluk-formal-mc',
    topicId: T.time, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['time.gunluk.nach-vor', 'time.resmi.kural'],
    familyId: 'p10-gunluk-formal',
    instruction: '"Es ist zwanzig nach fünf." — resmî karşılığı?',
    prompt: 'Es ist zwanzig nach fünf. → resmî',
    answer: 'Es ist siebzehn Uhr zwanzig.',
    options: ['Es ist siebzehn Uhr zwanzig.', 'Es ist fünf Uhr zwanzig.', 'Es ist siebzehn Uhr fünfzig.', 'Es ist halb sechs.'],
    pronounce: ['Es ist siebzehn Uhr zwanzig.'],
  },
  {
    id: 'p10-gunluk-informal-free',
    topicId: T.time, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['time.gunluk.nach-vor'],
    familyId: 'p10-gunluk-informal',
    instruction: 'Günlük biçimiyle yaz:',
    prompt: '15:40 → günlük ______',
    answer: 'Es ist zwanzig vor vier.',
    pronounce: ['Es ist zwanzig vor vier.'],
  },
  {
    id: 'p10-gunluk-viertel-vor-mc',
    topicId: T.time, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['time.gunluk.viertel'],
    familyId: 'p10-gunluk-viertel-vor',
    instruction: '20:45 günlük konuşmada nasıldır?',
    prompt: '20:45 → günlük',
    answer: 'Es ist Viertel vor neun.',
    options: ['Es ist Viertel vor neun.', 'Es ist Viertel nach neun.', 'Es ist halb neun.', 'Es ist zwanzig Uhr fünfundvierzig.'],
    pronounce: ['Es ist Viertel vor neun.'],
  },

  /* ---- halb / Viertel / vor / nach (5) ---- */
  {
    id: 'p10-halb-mc-anlam',
    topicId: T.time, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['time.halb.anlam'],
    familyId: 'p10-halb-anlam',
    instruction: '"halb acht" — saat kaç?',
    prompt: 'halb acht = ?',
    answer: '07:30',
    options: ['07:30', '08:30', '06:30', '08:00'],
    pronounce: ['halb acht'],
  },
  {
    id: 'p10-halb-sechs-fill',
    topicId: T.time, legacyDay: 10,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['time.halb.ornek'],
    familyId: 'p10-halb-sechs',
    instruction: 'Doğru saati yaz — 05:30:',
    prompt: 'Es ist halb ___. (05:30)',
    answer: 'sechs',
    pronounce: ['Es ist halb sechs.'],
  },
  {
    id: 'p10-halb-zehn-free',
    topicId: T.time, legacyDay: 10,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['time.halb.ornek'],
    familyId: 'p10-halb-zehn',
    instruction: 'Almancasını yaz:',
    prompt: '09:30 → ______',
    answer: 'Es ist halb zehn.',
    pronounce: ['Es ist halb zehn.'],
  },
  {
    id: 'p10-halb-error-sieben',
    topicId: T.time, legacyDay: 10,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['time.halb.anlam'],
    familyId: 'p10-halb-error',
    instruction: 'Yanlış saati düzelt — 07:30:',
    prompt: 'Es ist halb sieben.',
    answer: 'Es ist halb acht.',
    explanation: '`halb` her zaman bir sonrakini söyler: 07:30 = `halb acht`.',
    pronounce: ['Es ist halb acht.'],
  },
  {
    id: 'p10-halb-dictation-acht',
    topicId: T.time, legacyDay: 10,
    type: 'dictation', difficulty: 'medium', skill: 'production',
    conceptIds: ['time.halb.ornek'],
    familyId: 'p10-halb-dictation',
    instruction: 'Duyduğun saati aynen yaz:',
    audioText: 'Es ist halb acht.',
    answer: 'Es ist halb acht.',
    audio: { prompt: { text: 'Es ist halb acht.', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- `um` ile Saat Söylemek (4) ---- */
  {
    id: 'p10-um-mc-fark',
    topicId: T.time, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['time.um.kural'],
    familyId: 'p10-um-fark',
    instruction: '"Ich stehe um sieben Uhr auf." ne demektir?',
    prompt: 'um sieben Uhr = ?',
    answer: 'saat yedide',
    options: ['saat yedide', 'saat yedi', 'yedi saat', 'yediye kadar'],
    pronounce: ['um sieben Uhr'],
  },
  {
    id: 'p10-um-wb-inversion',
    topicId: T.time, legacyDay: 10,
    type: 'word-bank-translation', difficulty: 'hard', skill: 'production',
    conceptIds: ['time.um.ornek', 'separable-verbs.trennbar.saat-basta'],
    familyId: 'p10-um-inversion',
    instruction: 'Türkçeden Almancaya kur — Saat yedide kalkıyorum (saat başta).',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Saat yedide kalkıyorum (saat başta).',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Um' }, { id: 't2', text: 'sieben' }, { id: 't3', text: 'Uhr' },
        { id: 't4', text: 'stehe' }, { id: 't5', text: 'ich' }, { id: 't6', text: 'auf.' },
        { id: 't7', text: 'Ich' }, { id: 't8', text: 'um' },
      ],
      acceptedSequences: [['Um', 'sieben', 'Uhr', 'stehe', 'ich', 'auf.']],
    },
    answer: 'Um sieben Uhr stehe ich auf.',
    pronounce: ['Um sieben Uhr stehe ich auf.'],
  },
  {
    id: 'p10-um-error-ohne',
    topicId: T.time, legacyDay: 10,
    type: 'error-correction', difficulty: 'medium', skill: 'correction',
    conceptIds: ['time.um.kural'],
    familyId: 'p10-um-error',
    instruction: '`um` eksik — cümleyi düzelt:',
    prompt: 'Ich stehe sieben Uhr auf.',
    answer: 'Ich stehe um sieben Uhr auf.',
    explanation: 'Rutinde saat `um` ile bağlanır: `um sieben Uhr` = saat yedide.',
    pronounce: ['Ich stehe um sieben Uhr auf.'],
  },
  {
    id: 'p10-um-free-sieben',
    topicId: T.time, legacyDay: 10,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['time.um.ornek'],
    familyId: 'p10-um-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Saat yedide kalkıyorum. → ______',
    answer: 'Ich stehe um sieben Uhr auf.',
    pronounce: ['Ich stehe um sieben Uhr auf.'],
  },

  /* ---- Zaman İfadeleri (17) ---- */
  {
    id: 'p3-zi-um-uhr-mc',
    topicId: T.time, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['time.zaman.um-uhr'],
    familyId: 'p3-zi-um-uhr',
    instruction: 'Kesin bir saat söylerken hangi edat kullanılır?',
    prompt: 'saat yedide',
    answer: 'um 7 Uhr',
    options: ['um 7 Uhr', 'am 7 Uhr', 'im 7 Uhr', 'in 7 Uhr'],
  },
  {
    id: 'p3-zi-um-8-fill',
    topicId: T.time, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['time.zaman.um-uhr'],
    familyId: 'p3-zi-um-8',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich gehe ___ 8 Uhr zur Schule. (saat sekizde okula gidiyorum)',
    answer: 'um',
    pronounce: ['Ich gehe um 8 Uhr zur Schule.'],
  },
  {
    id: 'p3-zi-beginnt-fill',
    topicId: T.time, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['time.zaman.um-uhr'],
    familyId: 'p3-zi-beginnt',
    instruction: 'Boşluğu doldur (der Unterricht, eril):',
    prompt: '___ Unterricht beginnt um 9 Uhr. (ders saat dokuzda başlıyor)',
    answer: 'Der',
    pronounce: ['Der Unterricht beginnt um 9 Uhr.'],
  },
  {
    id: 'p3-zi-endet-error',
    topicId: T.time, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['time.zaman.um-uhr'],
    familyId: 'p3-zi-endet',
    instruction: 'Hata avı — hangi fiil kendiliğinden bitmeyi anlatır?',
    prompt: 'Die Schule beendet um 3 Uhr.',
    answer: 'Die Schule endet um 3 Uhr.',
    explanation: '"enden" kendiliğinden bitmeyi anlatır (okul kendi kendine biter); "beenden" bir şeyi bitirmeyi anlatır ve nesne ister.',
    pronounce: ['Die Schule endet um 3 Uhr.'],
  },
  {
    id: 'p3-zi-am-morgen-mc',
    topicId: T.time, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['time.zaman.am'],
    familyId: 'p3-zi-am-morgen',
    instruction: '"sabah" hangi kalıpla söylenir?',
    prompt: 'sabah (genel olarak)',
    answer: 'am Morgen',
    options: ['am Morgen', 'im Morgen', 'zum Morgen', 'im Morgens'],
  },
  {
    id: 'p3-zi-am-abend-fill',
    topicId: T.time, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['time.zaman.am'],
    familyId: 'p3-zi-am-abend',
    instruction: 'Boşluğu doldur:',
    prompt: '___ Abend essen wir alle zusammen. (akşam hep birlikte yemek yiyoruz)',
    answer: 'Am',
    pronounce: ['Am Abend essen wir alle zusammen.'],
  },
  {
    id: 'p3-zi-am-wochenende-fill',
    topicId: T.time, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['time.zaman.am'],
    familyId: 'p3-zi-am-wochenende',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich treffe meinen Freund ___ Wochenende. (hafta sonu arkadaşımı görüyorum)',
    answer: 'am',
    pronounce: ['Ich treffe meinen Freund am Wochenende.'],
  },
  {
    id: 'p3-zi-im-winter-mc',
    topicId: T.time, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['time.zaman.im-mevsim'],
    familyId: 'p3-zi-im-winter',
    instruction: '"kışın" hangi kalıpla söylenir?',
    prompt: 'kışın',
    answer: 'im Winter',
    options: ['im Winter', 'am Winter', 'zum Winter', 'in Winter'],
  },
  {
    id: 'p3-zi-im-sommer-fill',
    topicId: T.time, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['time.zaman.im-mevsim'],
    familyId: 'p3-zi-im-sommer',
    instruction: 'Boşluğu doldur:',
    prompt: '___ Sommer gehe ich ans Meer. (yazın denize gidiyorum)',
    answer: 'Im',
    pronounce: ['Im Sommer gehe ich ans Meer.'],
  },
  {
    id: 'p3-zi-dann-mc',
    topicId: T.time, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['time.zaman.dann'],
    familyId: 'p3-zi-dann',
    instruction: '"Dann" ne demektir?',
    prompt: 'Dann',
    answer: 'sonra',
    options: ['sonra', 'şimdi', 'önce', 'her zaman'],
  },
  {
    id: 'p3-zi-dann-order',
    topicId: T.time, legacyDay: 3,
    type: 'ordering', difficulty: 'medium', skill: 'production',
    conceptIds: ['time.zaman.dann', 'sentence-building.dizilisi.zaman-basta'],
    familyId: 'p3-zi-dann-order',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Dann / lese / ich / ein / Buch.',
    answer: 'Dann lese ich ein Buch.',
    words: ['Dann', 'lese', 'ich', 'ein', 'Buch'],
    pronounce: ['Dann lese ich ein Buch.'],
  },
  {
    id: 'p3-zi-morgen-farki-mc',
    topicId: T.time, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['time.zaman.morgen-cift-anlam'],
    familyId: 'p3-zi-morgen-farki',
    instruction: '"morgen" (küçük harf) ile "der Morgen" arasındaki fark nedir?',
    prompt: 'morgen ↔ der Morgen',
    answer: 'morgen = yarın (zarf), der Morgen = sabah (isim)',
    options: [
      'morgen = yarın (zarf), der Morgen = sabah (isim)',
      'ikisi de "sabah" demektir',
      'ikisi de "yarın" demektir',
      'morgen isim, der Morgen zarftır',
    ],
  },
  {
    id: 'p3-zi-morgen-treffe-fill',
    topicId: T.time, legacyDay: 3,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['time.zaman.morgen-cift-anlam'],
    familyId: 'p3-zi-morgen-treffe',
    instruction: 'Boşluğu doldur (yarın, gelecek anlamı için Präsens kullanılır):',
    prompt: '___ treffe ich meine Freunde. (yarın arkadaşlarımla buluşacağım)',
    answer: 'Morgen',
    pronounce: ['Morgen treffe ich meine Freunde.'],
  },
  {
    id: 'p3-zi-zu-mittag-fill',
    topicId: T.time, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['time.zaman.um-uhr'],
    familyId: 'p3-zi-zu-mittag',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich esse ___ 1 Uhr zu Mittag. (öğle yemeğini saat birde yiyorum)',
    answer: 'um',
    pronounce: ['Ich esse um 1 Uhr zu Mittag.'],
  },
  {
    id: 'p3-zi-essen-8-fill',
    topicId: T.time, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['time.zaman.um-uhr'],
    familyId: 'p3-zi-essen-8',
    instruction: 'Boşluğu doldur:',
    prompt: 'Wir essen ___ 8 Uhr. (saat sekizde yemek yiyoruz)',
    answer: 'um',
    pronounce: ['Wir essen um 8 Uhr.'],
  },
  {
    id: 'p3-zi-dann-schlafe-mc',
    topicId: T.time, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['time.zaman.dann'],
    familyId: 'p3-zi-dann-schlafe',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Dann schlafe ich.',
    answer: 'Sonra uyuyorum.',
    options: ['Sonra uyuyorum.', 'Şimdi uyuyorum.', 'Önce uyudum.', 'Hiç uyumuyorum.'],
    pronounce: ['Dann schlafe ich.'],
  },
  {
    id: 'p3-zi-am-abend-zusammen-order',
    topicId: T.time, legacyDay: 3,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['time.zaman.am', 'sentence-building.dizilisi.zaman-basta'],
    familyId: 'p3-zi-am-abend-zusammen',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Am / Abend / essen / wir / zusammen.',
    answer: 'Am Abend essen wir zusammen.',
    words: ['Am', 'Abend', 'essen', 'wir', 'zusammen'],
    pronounce: ['Am Abend essen wir zusammen.'],
  },
];
