/**
 * Fiiller ve Çekim — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const VERBS_EXERCISES: AuthoredExercise[] = [
  /* ---- Fiil Çekimi — Düzenli ve Düzensiz Fiiller (16) ---- */
  {
    id: 'p1-verben-sein-ich-bin-mc',
    topicId: T.verbs, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['verbs.verben.sein'],
    familyId: 'p1-verb-sein',
    instruction: 'Doğru çekimi seç:',
    prompt: 'ich → sein',
    answer: 'bin',
    options: ['bin', 'bist', 'ist', 'sind'],
    pronounce: ['ich bin'],
  },
  {
    id: 'p1-verben-heissen-ich-mc',
    topicId: T.verbs, legacyDay: 1,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['verbs.verben.heissen'],
    familyId: 'p1-verb-heissen',
    instruction: 'Doğru çekimi seç:',
    prompt: 'ich → heißen',
    answer: 'heiße',
    options: ['heiße', 'heißt', 'heißen', 'heißst'],
    pronounce: ['ich heiße'],
  },
  {
    id: 'p1-verb-sein-du-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.sein'],
    familyId: 'p1-verb-sein',
    instruction: 'sein çekimi:',
    prompt: 'du → ______',
    answer: 'bist',
    pronounce: ['du bist'],
  },
  {
    id: 'p1-verb-sein-ihr-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.sein'],
    familyId: 'p1-verb-sein',
    instruction: 'sein çekimi:',
    prompt: 'ihr → ______',
    answer: 'seid',
    pronounce: ['ihr seid'],
  },
  {
    id: 'p1-verb-kommen-wir-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.kommen'],
    familyId: 'p1-verb-kommen',
    instruction: 'kommen çekimi:',
    prompt: 'wir → ______',
    answer: 'kommen',
    pronounce: ['wir kommen'],
  },
  {
    id: 'p1-verb-sagen-wir-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.sagen'],
    familyId: 'p1-verb-sagen',
    instruction: 'sagen çekimi:',
    prompt: 'wir → ______',
    answer: 'sagen',
    pronounce: ['wir sagen'],
  },
  {
    id: 'p1-verb-sprechen-du-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.sprechen'],
    familyId: 'p1-verb-sprechen',
    instruction: 'sprechen çekimi (düzensiz):',
    prompt: 'du → ______',
    answer: 'sprichst',
    pronounce: ['du sprichst'],
  },
  {
    id: 'p1-verb-essen-du-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.essen'],
    familyId: 'p1-verb-essen',
    instruction: 'essen çekimi (düzensiz):',
    prompt: 'du → ______',
    answer: 'isst',
    pronounce: ['du isst'],
  },
  {
    id: 'p1-verb-kochen-ihr-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.kochen'],
    familyId: 'p1-verb-kochen',
    instruction: 'kochen çekimi:',
    prompt: 'ihr → ______',
    answer: 'kocht',
    pronounce: ['ihr kocht'],
  },
  {
    id: 'p1-hata-sprichst',
    topicId: T.verbs, legacyDay: 1,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['verbs.verben.sprechen'],
    familyId: 'p1-verb-sprechen',
    instruction: 'Hata avı — fiil biçimini düzelt:',
    prompt: 'Du sprechst Englisch.',
    answer: 'Du sprichst Englisch.',
    explanation: 'sprechen düzensiz: du sprichst, er spricht.',
    pronounce: ['Du sprichst Englisch.'],
  },
  {
    id: 'p1-hata-heisst-eszett',
    topicId: T.verbs, legacyDay: 1,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['verbs.verben.heissen'],
    familyId: 'p1-verb-heissen',
    instruction: 'Yazım hatasını düzelt:',
    prompt: 'Wie heisst du?',
    answer: 'Wie heißt du?',
    validation: { keyboardTolerance: true },
    explanation: 'ß harfi: heißt, nicht heisst (resmî yazımda ß).',
    pronounce: ['Wie heißt du?'],
  },
  {
    id: 'p1-extra-heissen-ihr-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.heissen'],
    familyId: 'p1-verb-heissen',
    instruction: 'heißen çekimi:',
    prompt: 'ihr → ______',
    answer: 'heißt',
    validation: { keyboardTolerance: true },
    pronounce: ['ihr heißt'],
  },
  {
    id: 'p1-extra-sein-wir-sind-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.sein'],
    familyId: 'p1-verb-sein',
    instruction: 'sein çekimi:',
    prompt: 'wir → ______',
    answer: 'sind',
    pronounce: ['wir sind'],
  },
  {
    id: 'p1-extra-essen-er-isst-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.essen'],
    familyId: 'p1-verb-essen',
    instruction: 'essen çekimi:',
    prompt: 'er → ______',
    answer: 'isst',
    pronounce: ['er isst'],
  },
  {
    id: 'p1-extra-sagen-du-sagst-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.sagen'],
    familyId: 'p1-verb-sagen',
    instruction: 'sagen çekimi:',
    prompt: 'du → ______',
    answer: 'sagst',
    pronounce: ['du sagst'],
  },
  {
    id: 'p1-extra-kochen-er-kocht-fill',
    topicId: T.verbs, legacyDay: 1,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.verben.kochen'],
    familyId: 'p1-verb-kochen',
    instruction: 'kochen çekimi:',
    prompt: 'er → ______',
    answer: 'kocht',
    pronounce: ['er kocht'],
  },

  /* ---- haben ve sein (9) ---- */
  {
    id: 'p2-hs-habe-fill',
    topicId: T.verbs, legacyDay: 2,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['verbs.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'ich → ______',
    answer: 'habe',
    pronounce: ['ich habe'],
  },
  {
    id: 'p2-hs-hast-fill',
    topicId: T.verbs, legacyDay: 2,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['verbs.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'du → ______',
    answer: 'hast',
    pronounce: ['du hast'],
  },
  {
    id: 'p2-hs-hat-fill',
    topicId: T.verbs, legacyDay: 2,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['verbs.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'er/sie/es → ______',
    answer: 'hat',
    pronounce: ['er hat'],
  },
  {
    id: 'p2-hs-haben-wir-fill',
    topicId: T.verbs, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'wir → ______',
    answer: 'haben',
    pronounce: ['wir haben'],
  },
  {
    id: 'p2-hs-habt-fill',
    topicId: T.verbs, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'ihr → ______',
    answer: 'habt',
    pronounce: ['ihr habt'],
  },
  {
    id: 'p2-hs-sein-review-mc',
    topicId: T.verbs, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['verbs.sein.tekrar'],
    familyId: 'p2-hs-sein',
    instruction: 'sein çekimi (tekrar):',
    prompt: 'du → sein',
    answer: 'bist',
    options: ['bin', 'bist', 'ist', 'sind'],
    pronounce: ['du bist'],
  },
  {
    id: 'p2-hs-haben-vs-sein-mc',
    topicId: T.verbs, legacyDay: 2,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['verbs.haben.tablo', 'verbs.sein.tekrar'],
    familyId: 'p2-hs-fark',
    instruction: '"Sahip olmak" anlamına gelen fiil hangisidir?',
    prompt: 'sahip olmak',
    answer: 'haben',
    options: ['haben', 'sein', 'machen', 'gehen'],
  },
  {
    id: 'p2-hs-kein-geld-matching',
    topicId: T.verbs, legacyDay: 2,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['verbs.haben.kein-ile'],
    familyId: 'p2-hs-kein-match',
    instruction: '"haben + kein/keine" cümlelerini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'Ich habe kein Geld.', right: 'Param yok.' },
      { left: 'Ich habe keine Schwester.', right: 'Kız kardeşim yok.' },
      { left: 'Sie hat keine Tasche.', right: 'Onun çantası yok.' },
    ],
    pronounce: ['Ich habe kein Geld.', 'Ich habe keine Schwester.', 'Sie hat keine Tasche.'],
  },
  {
    id: 'p2-hs-extra-sind-fill',
    topicId: T.verbs, legacyDay: 2,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.haben.tablo'],
    familyId: 'p2-hs-haben',
    instruction: 'haben çekimi:',
    prompt: 'sie/Sie → ______',
    answer: 'haben',
    pronounce: ['sie haben'],
  },

  /* ---- Diğer Temel Fiiller — kennen, geben, stellen (8) ---- */
  {
    id: 'p7-fii-kennen-mc',
    topicId: T.verbs, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['verbs.fiil.kennen'],
    familyId: 'p7-fii-kennen',
    instruction: '"kennen" ne demektir?',
    prompt: 'kennen',
    answer: 'tanımak',
    options: ['tanımak', 'vermek', 'koymak', 'aramak'],
    pronounce: ['kennen'],
  },
  {
    id: 'p7-fii-kennen-du-fill',
    topicId: T.verbs, legacyDay: 7,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['verbs.fiil.kennen-cekim'],
    familyId: 'p7-fii-kennen-cekim',
    instruction: 'Fiili doğru çek:',
    prompt: 'Du ___ meine Schwester. (kennen)',
    answer: 'kennst',
    pronounce: ['Du kennst meine Schwester.'],
  },
  {
    id: 'p7-fii-kennen-tr-de',
    topicId: T.verbs, legacyDay: 7,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['verbs.fiil.kennen-cekim'],
    familyId: 'p7-fii-kennen-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Mustafa\'yı tanıyorum. → ______',
    answer: 'Ich kenne Mustafa.',
    pronounce: ['Ich kenne Mustafa.'],
  },
  {
    id: 'p7-fii-geben-mc',
    topicId: T.verbs, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['verbs.fiil.geben'],
    familyId: 'p7-fii-geben',
    instruction: '"geben" ne demektir?',
    prompt: 'geben',
    answer: 'vermek',
    options: ['vermek', 'tanımak', 'almak', 'koymak'],
    pronounce: ['geben'],
  },
  {
    id: 'p7-fii-geben-du-fill',
    topicId: T.verbs, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.fiil.geben-gibt'],
    familyId: 'p7-fii-geben-du',
    instruction: 'Fiili doğru çek (dikkat: düzensiz):',
    prompt: 'Du ___ mir das Buch. (geben)',
    answer: 'gibst',
    pronounce: ['Du gibst mir das Buch.'],
  },
  {
    id: 'p7-fii-geben-er-mc',
    topicId: T.verbs, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['verbs.fiil.geben-gibt'],
    familyId: 'p7-fii-geben-er',
    instruction: '"geben" fiilinin `er` biçimi hangisidir?',
    prompt: 'er ___',
    answer: 'gibt',
    options: ['gibt', 'gebt', 'gebe', 'geben'],
    pronounce: ['er gibt'],
  },
  {
    id: 'p7-fii-es-gibt-mc',
    topicId: T.verbs, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'hard', skill: 'recognition',
    conceptIds: ['verbs.fiil.es-gibt-fark'],
    familyId: 'p7-fii-es-gibt',
    instruction: '`geben` ile `es gibt` arasındaki fark nedir?',
    prompt: 'geben ↔ es gibt',
    answer: '`geben` = vermek; `es gibt` = var (hazır kalıp)',
    options: [
      '`geben` = vermek; `es gibt` = var (hazır kalıp)',
      'İkisi de "vermek" demektir',
      '`geben` = var; `es gibt` = vermek',
      'İkisi de "almak" demektir',
    ],
  },
  {
    id: 'p7-fii-stellen-fill',
    topicId: T.verbs, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.fiil.stellen', 'places.kontraksiyon.ins'],
    familyId: 'p7-fii-stellen',
    instruction: 'Boşluğu doldur — "koymak" fiilini çek:',
    prompt: 'Ich ___ das Regal ins Zimmer. (stellen)',
    answer: 'stelle',
    pronounce: ['Ich stelle das Regal ins Zimmer.'],
  },

  /* ---- Refleksif Fiiller (9) ---- */
  {
    id: 'p3-rf-temel-mc',
    topicId: T.verbs, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['verbs.refleksif.temel'],
    familyId: 'p3-rf-temel',
    instruction: '"ich" için refleksif zamir hangisidir?',
    prompt: 'ich → ___',
    answer: 'mich',
    options: ['mich', 'dich', 'sich', 'uns'],
    pronounce: ['mich'],
  },
  {
    id: 'p3-rf-du-fill',
    topicId: T.verbs, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['verbs.refleksif.temel'],
    familyId: 'p3-rf-du',
    instruction: 'Refleksif zamir:',
    prompt: 'du → ___',
    answer: 'dich',
    pronounce: ['dich'],
  },
  {
    id: 'p3-rf-duschen-anlam-mc',
    topicId: T.verbs, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['verbs.sich-duschen'],
    familyId: 'p3-rf-duschen-anlam',
    instruction: '"sich duschen" ne demektir?',
    prompt: 'sich duschen',
    answer: 'duş almak',
    options: ['duş almak', 'dinlenmek', 'kalkmak', 'temizlemek'],
    pronounce: ['sich duschen'],
  },
  {
    id: 'p3-rf-dusche-mich-fill',
    topicId: T.verbs, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['verbs.sich-duschen'],
    familyId: 'p3-rf-dusche-mich',
    instruction: 'Boşluğu doldur:',
    prompt: 'Dann dusche ich ___. (sonra duş alıyorum)',
    answer: 'mich',
    pronounce: ['Dann dusche ich mich.'],
  },
  {
    id: 'p3-rf-ausruhen-anlam-mc',
    topicId: T.verbs, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['verbs.sich-ausruhen'],
    familyId: 'p3-rf-ausruhen-anlam',
    instruction: '"sich ausruhen" ne demektir?',
    prompt: 'sich ausruhen',
    answer: 'dinlenmek',
    options: ['dinlenmek', 'duş almak', 'toplamak', 'kalkmak'],
    pronounce: ['sich ausruhen'],
  },
  {
    id: 'p3-rf-ruhe-mich-aus-order',
    topicId: T.verbs, legacyDay: 3,
    type: 'ordering', difficulty: 'hard', skill: 'production',
    conceptIds: ['verbs.sich-ausruhen', 'verbs.refleksif-ayrilabilen'],
    familyId: 'p3-rf-ruhe-mich-aus',
    instruction: 'Kelime kartlarını doğru sıraya koy:',
    prompt: 'Ich / ruhe / mich / am / Abend / ein / bisschen / aus.',
    answer: 'Ich ruhe mich am Abend ein bisschen aus.',
    words: ['Ich', 'ruhe', 'mich', 'am', 'Abend', 'ein', 'bisschen', 'aus'],
    pronounce: ['Ich ruhe mich am Abend ein bisschen aus.'],
  },
  {
    id: 'p3-rf-error-mich-sonda',
    topicId: T.verbs, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['verbs.refleksif-ayrilabilen'],
    familyId: 'p3-rf-ruhe-mich-aus',
    instruction: 'Hata avı — refleksif zamir nereye gitmeli?',
    prompt: 'Ich ruhe am Abend ein bisschen aus mich.',
    answer: 'Ich ruhe mich am Abend ein bisschen aus.',
    explanation: 'Refleksif zamir (mich) çekimli fiilden hemen sonra gelir; ayrılabilen önek (aus) cümlenin en sonuna gider.',
    pronounce: ['Ich ruhe mich am Abend ein bisschen aus.'],
  },
  {
    id: 'p3-rf-wb-dusche-tr-de',
    topicId: T.verbs, legacyDay: 3,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['verbs.sich-duschen'],
    familyId: 'p3-rf-dusche-mich',
    instruction: 'Türkçeden Almancaya kur — Sonra duş alıyorum.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Sonra duş alıyorum.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Dann' }, { id: 't2', text: 'dusche' }, { id: 't3', text: 'ich' }, { id: 't4', text: 'mich.' },
        { id: 't5', text: 'dich' },
      ],
      acceptedSequences: [['Dann', 'dusche', 'ich', 'mich.']],
    },
    answer: 'Dann dusche ich mich.',
    pronounce: ['Dann dusche ich mich.'],
  },
  {
    id: 'p3-rf-free-ausruhen-tr',
    topicId: T.verbs, legacyDay: 3,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['verbs.sich-ausruhen', 'verbs.refleksif-ayrilabilen'],
    familyId: 'p3-rf-ausruhen-free',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Akşam biraz dinleniyorum. → ______',
    answer: 'Ich ruhe mich am Abend ein bisschen aus.',
    pronounce: ['Ich ruhe mich am Abend ein bisschen aus.'],
  },
];
