/**
 * Kelime Haznesi — konu alıştırma bankası.
 *
 * Özel ders notlarından taşınan alıştırmalar; `legacyDay` yalnızca kaynak
 * izidir ve hiçbir davranışı sürmez. Kimlikler kalıcı ilerleme için korunur.
 */

import type { AuthoredExercise } from '../types.ts';
import { T } from '../../curriculum/topics.ts';

export const VOCABULARY_EXERCISES: AuthoredExercise[] = [
  /* ---- Faydalı Küçük Kelimeler (11) ---- */
  {
    id: 'p5-kel-leider-mc',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.leider'],
    familyId: 'p5-kel-leider',
    instruction: '"leider" ne demektir?',
    prompt: 'leider',
    answer: 'maalesef / ne yazık ki',
    options: ['maalesef / ne yazık ki', 'belki', 'elbette', 'asla'],
    pronounce: ['leider'],
  },
  {
    id: 'p5-kel-mehr-mc',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.mehr'],
    familyId: 'p5-kel-mehr',
    instruction: '"mehr" ne demektir?',
    prompt: 'mehr',
    answer: 'daha fazla',
    options: ['daha fazla', 'daha az', 'hiç', 'çok az'],
    pronounce: ['mehr'],
  },
  {
    id: 'p5-kel-geschwister-mc',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.geschwister'],
    familyId: 'p5-kel-geschwister',
    instruction: '"die Geschwister" ne demektir?',
    prompt: 'die Geschwister',
    answer: 'kardeşler',
    options: ['kardeşler', 'ebeveynler', 'çocuklar', 'arkadaşlar'],
    pronounce: ['die Geschwister'],
  },
  {
    id: 'p5-kel-seit-mc',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.seit'],
    familyId: 'p5-kel-seit',
    instruction: '"seit" ne demektir?',
    prompt: 'seit',
    answer: '-den beri',
    options: ['-den beri', '-e kadar', '-den önce', '-den sonra'],
    pronounce: ['seit'],
  },
  {
    id: 'p5-kel-flughafen-mc',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.flughafen'],
    familyId: 'p5-kel-flughafen',
    instruction: '"der Flughafen" ne demektir?',
    prompt: 'der Flughafen',
    answer: 'havaalanı',
    options: ['havaalanı', 'tren istasyonu', 'otobüs durağı', 'liman'],
    pronounce: ['der Flughafen'],
  },
  {
    id: 'p5-kel-moment-mc',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.moment'],
    familyId: 'p5-kel-moment',
    instruction: '"der Moment" ne demektir?',
    prompt: 'der Moment',
    answer: 'an / bir dakika',
    options: ['an / bir dakika', 'gün', 'hafta', 'saat'],
    pronounce: ['der Moment'],
  },
  {
    id: 'p5-kel-matching',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.leider', 'vocabulary.kelime.mehr', 'vocabulary.kelime.geschwister', 'vocabulary.kelime.seit', 'vocabulary.kelime.flughafen', 'vocabulary.kelime.moment'],
    familyId: 'p5-kel-matching',
    instruction: 'Kelimeleri Türkçesiyle eşleştir.',
    pairs: [
      { left: 'leider', right: 'maalesef' },
      { left: 'mehr', right: 'daha fazla' },
      { left: 'die Geschwister', right: 'kardeşler' },
      { left: 'seit', right: '-den beri' },
      { left: 'der Flughafen', right: 'havaalanı' },
      { left: 'der Moment', right: 'an' },
    ],
    pronounce: ['leider', 'mehr', 'die Geschwister', 'seit', 'der Flughafen', 'der Moment'],
  },
  {
    id: 'p5-kel-fill-geschwister',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'fill-blank', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.kelime.geschwister'],
    familyId: 'p5-kel-fill-geschwister',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich habe keine ___. (Hiç kardeşim yok.)',
    answer: 'Geschwister',
    pronounce: ['Ich habe keine Geschwister.'],
  },
  {
    id: 'p5-kel-fill-seit',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'fill-blank', difficulty: 'hard', skill: 'production',
    conceptIds: ['vocabulary.kelime.seit'],
    familyId: 'p5-kel-fill-seit',
    instruction: 'Boşluğu doldur:',
    prompt: 'Ich lebe ___ zwei Jahren in Berlin. (İki yıldır Berlin\'de yaşıyorum.)',
    answer: 'seit',
    pronounce: ['Ich lebe seit zwei Jahren in Berlin.'],
  },
  {
    id: 'p5-kel-dictation-flughafen',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'dictation', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.kelime.flughafen'],
    familyId: 'p5-kel-flughafen',
    instruction: 'Havaalanı cümlesini duydun — aynen yaz:',
    audioText: 'Der Flughafen ist sehr groß.',
    answer: 'Der Flughafen ist sehr groß.',
    audio: { prompt: { text: 'Der Flughafen ist sehr groß.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'p5-kel-wb-leider-tr-de',
    topicId: T.vocabulary, legacyDay: 5,
    type: 'word-bank-translation', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.kelime.leider'],
    familyId: 'p5-kel-wb-leider',
    instruction: 'Türkçeden Almancaya kur — Maalesef bugün vaktim yok.',
    wordBank: {
      direction: 'tr-to-de',
      sourceText: 'Maalesef bugün vaktim yok.',
      targetLanguage: 'de',
      tokens: [
        { id: 't1', text: 'Leider' }, { id: 't2', text: 'habe' }, { id: 't3', text: 'ich' }, { id: 't4', text: 'heute' }, { id: 't5', text: 'keine' }, { id: 't6', text: 'Zeit.' },
        { id: 't7', text: 'mehr' },
      ],
      acceptedSequences: [['Leider', 'habe', 'ich', 'heute', 'keine', 'Zeit.']],
    },
    answer: 'Leider habe ich heute keine Zeit.',
    pronounce: ['Leider habe ich heute keine Zeit.'],
  },

  /* ---- Günlük Hayattan Kelimeler (8) ---- */
  {
    id: 'p7-kel-match-1',
    topicId: T.vocabulary, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.gluecklich', 'vocabulary.kelime.gast-leute'],
    familyId: 'p7-kel-match-1',
    instruction: 'Duygu ve kişi kelimelerini Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'glücklich', right: 'mutlu' },
      { left: 'der Traum', right: 'hayal' },
      { left: 'der Gast', right: 'misafir' },
      { left: 'die Leute', right: 'insanlar' },
    ],
    pronounce: ['glücklich', 'der Traum', 'der Gast', 'die Leute'],
  },
  {
    id: 'p7-kel-match-2',
    topicId: T.vocabulary, legacyDay: 7,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.fuer-dafuer', 'vocabulary.kelime.nur-etwas-viele', 'vocabulary.kelime.dazu-fertig-schmeckt'],
    familyId: 'p7-kel-match-2',
    instruction: 'Küçük yardımcı kelimeleri Türkçe karşılığıyla eşleştir.',
    pairs: [
      { left: 'für', right: 'için' },
      { left: 'dafür', right: 'bunun için' },
      { left: 'nur', right: 'sadece' },
      { left: 'viele', right: 'bir çok' },
      { left: 'fertig', right: 'hazır' },
    ],
    pronounce: ['für', 'dafür', 'nur', 'viele', 'fertig'],
  },
  {
    id: 'p7-kel-zusammen-fill',
    topicId: T.vocabulary, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['vocabulary.kelime.zusammen-dort'],
    familyId: 'p7-kel-zusammen',
    instruction: 'Boşluğu doldur — "birlikte" kelimesini yaz:',
    prompt: 'Wir essen ___. (Birlikte yiyoruz.)',
    answer: 'zusammen',
    pronounce: ['Wir essen zusammen.'],
  },
  {
    id: 'p7-kel-dort-fill',
    topicId: T.vocabulary, legacyDay: 7,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['vocabulary.kelime.zusammen-dort', 'home.moebel.teppich-regal'],
    familyId: 'p7-kel-dort',
    instruction: 'Boşluğu doldur — "orada" kelimesini yaz:',
    prompt: 'Das Regal ist ___. (Raf orada.)',
    answer: 'dort',
    pronounce: ['Das Regal ist dort.'],
  },
  {
    id: 'p7-kel-auch-mc',
    topicId: T.vocabulary, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.auch'],
    familyId: 'p7-kel-auch',
    instruction: '"auch" ne demektir?',
    prompt: 'auch',
    answer: 'de, da, ayrıca',
    options: ['de, da, ayrıca', 'ama', 'çünkü', 'sadece'],
    pronounce: ['auch'],
  },
  {
    id: 'p7-kel-gluecklich-tr-de',
    topicId: T.vocabulary, legacyDay: 7,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.kelime.gluecklich'],
    familyId: 'p7-kel-gluecklich-tr',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Mutluyum. → ______',
    answer: 'Ich bin glücklich.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich bin glücklich.'],
  },
  {
    id: 'p7-kel-mensa-mc',
    topicId: T.vocabulary, legacyDay: 7,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.kelime.gast-leute'],
    familyId: 'p7-kel-mensa',
    instruction: '"in der Mensa" ne demektir?',
    prompt: 'in der Mensa',
    answer: 'yemekhanede',
    options: ['yemekhanede', 'markette', 'mutfakta', 'salonda'],
    pronounce: ['in der Mensa'],
  },
  {
    id: 'p7-kel-schmeckt-fill',
    topicId: T.vocabulary, legacyDay: 7,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['vocabulary.kelime.dazu-fertig-schmeckt', 'food.yiyecek.haehnchen'],
    familyId: 'p7-kel-schmeckt',
    instruction: 'Boşluğu doldur — "tadı güzel" fiilini yaz:',
    prompt: 'Die Gemüsesuppe ___ gut. (Sebze çorbasının tadı güzel.)',
    answer: 'schmeckt',
    pronounce: ['Die Gemüsesuppe schmeckt gut.'],
  },

  /* ---- Diğer Kelimeler — ruhig, beide, ziemlich (4) ---- */
  {
    id: 'p10-rev-ruhig-mc',
    topicId: T.vocabulary, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.wort.ruhig'],
    familyId: 'p10-rev-ruhig',
    instruction: '"ruhig" ne demektir?',
    prompt: 'ruhig',
    answer: 'sessiz, sakin',
    options: ['sessiz, sakin', 'gürültülü', 'kalabalık', 'hızlı'],
    pronounce: ['ruhig'],
  },
  {
    id: 'p10-rev-beide-fill',
    topicId: T.vocabulary, legacyDay: 10,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['vocabulary.wort.beide'],
    familyId: 'p10-rev-beide',
    instruction: 'Türkçesini yaz:',
    prompt: 'beide = ___',
    answer: 'ikisi de',
  },
  {
    id: 'p10-rev-ziemlich-mc',
    topicId: T.vocabulary, legacyDay: 10,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.wort.ziemlich', 'vocabulary.wort.frueh-lange', 'home.wort.badewanne'],
    familyId: 'p10-rev-kelime',
    instruction: 'Hangisi "oldukça" demektir?',
    prompt: 'oldukça',
    answer: 'ziemlich',
    options: ['ziemlich', 'ruhig', 'früh', 'beide'],
    pronounce: ['ziemlich'],
  },
  {
    id: 'p10-rev-match-klein',
    topicId: T.vocabulary, legacyDay: 10,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: [
      'vocabulary.wort.ruhig',
      'vocabulary.wort.beide',
      'home.wort.badewanne',
      'vocabulary.wort.ziemlich',
      'vocabulary.wort.frueh-lange',
    ],
    familyId: 'p10-rev-match',
    instruction: 'Tekrar kelimesini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'ruhig', right: 'sessiz' },
      { left: 'beide', right: 'ikisi de' },
      { left: 'die Badewanne', right: 'küvet' },
      { left: 'ziemlich', right: 'oldukça' },
      { left: 'lange', right: 'uzun' },
    ],
    pronounce: ['ruhig', 'die Badewanne', 'ziemlich'],
  },

  /* ---- Hava, Hayvanlar ve Hobiler (14) ---- */
  {
    id: 'p3-gh-wetter-schoen-fill',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['vocabulary.hava.ifadeler'],
    familyId: 'p3-gh-wetter-schoen',
    instruction: 'Boşluğu doldur:',
    prompt: 'Das Wetter ist heute sehr ___. (bugün hava çok güzel)',
    answer: 'schön',
    pronounce: ['Das Wetter ist heute sehr schön.'],
  },
  {
    id: 'p3-gh-wetter-warm-fill',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['vocabulary.hava.ifadeler'],
    familyId: 'p3-gh-wetter-warm',
    instruction: 'Boşluğu doldur:',
    prompt: 'Das Wetter ist ein bisschen ___. (hava biraz sıcak)',
    answer: 'warm',
    pronounce: ['Das Wetter ist ein bisschen warm.'],
  },
  {
    id: 'p3-gh-wetter-kalt-mc',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.hava.ifadeler'],
    familyId: 'p3-gh-wetter-kalt',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Im Winter ist das Wetter kalt.',
    answer: 'Kışın hava soğuk oluyor.',
    options: ['Kışın hava soğuk oluyor.', 'Yazın hava sıcak oluyor.', 'Bugün hava güzel.', 'Hava biraz sıcak.'],
    pronounce: ['Im Winter ist das Wetter kalt.'],
  },
  {
    id: 'p3-gh-katze-mc',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.hayvanlar.kelime'],
    familyId: 'p3-gh-katze',
    instruction: '"die Katze" ne demektir?',
    prompt: 'die Katze',
    answer: 'kedi',
    options: ['kedi', 'köpek', 'hayvan', 'çiçek'],
    pronounce: ['die Katze'],
  },
  {
    id: 'p3-gh-katze-suess-fill',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['vocabulary.hayvanlar.kelime'],
    familyId: 'p3-gh-katze-suess',
    instruction: 'Boşluğu doldur (doğru yazım: ß):',
    prompt: 'Meine Katze ist sehr ___. (kedim çok tatlı)',
    answer: 'süß',
    pronounce: ['Meine Katze ist sehr süß.'],
  },
  {
    id: 'p3-gh-hund-fill',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['vocabulary.hayvanlar.kelime'],
    familyId: 'p3-gh-hund',
    instruction: 'Boşluğu doldur:',
    prompt: 'Mein ___ spielt im Garten. (köpeğim bahçede oynuyor)',
    answer: 'Hund',
    pronounce: ['Mein Hund spielt im Garten.'],
  },
  {
    id: 'p3-gh-lieblingstier-error',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'error-correction', difficulty: 'hard', skill: 'correction',
    conceptIds: ['vocabulary.hayvanlar.kelime'],
    familyId: 'p3-gh-lieblingstier',
    instruction: 'Hata avı — tekil mi çoğul mu, artikel var mı?',
    prompt: 'Mein Lieblingstiere ist Katze.',
    answer: 'Mein Lieblingstier ist die Katze.',
    explanation: '"en sevilen hayvan" tekildir (Lieblingstier, Lieblingstiere değil) ve isimden sonra artikel gerekir (die Katze).',
    pronounce: ['Mein Lieblingstier ist die Katze.'],
  },
  {
    id: 'p3-gh-matching-hayvanlar',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.hayvanlar.kelime'],
    familyId: 'p3-gh-hayvan-match',
    instruction: 'Hayvan kelimelerini Türkçesiyle eşleştir.',
    pairs: [
      { left: 'die Katze', right: 'kedi' },
      { left: 'der Hund', right: 'köpek' },
      { left: 'das Tier', right: 'hayvan' },
      { left: 'der Garten', right: 'bahçe' },
    ],
    pronounce: ['die Katze', 'der Hund', 'das Tier', 'der Garten'],
  },
  {
    id: 'p3-gh-fussball-mc',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.hobiler.kelime'],
    familyId: 'p3-gh-fussball',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Ich spiele gern Fußball.',
    answer: 'Ben futbol oynamayı seviyorum.',
    options: ['Ben futbol oynamayı seviyorum.', 'Ben yüzmeyi seviyorum.', 'Ben kitap okumayı severim.', 'Ben bisiklete binerim.'],
    pronounce: ['Ich spiele gern Fußball.'],
  },
  {
    id: 'p3-gh-fahrrad-fill',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['vocabulary.hobiler.kelime'],
    familyId: 'p3-gh-fahrrad',
    instruction: 'Boşluğu doldur (fahren: sie fährt):',
    prompt: 'Meine Schwester ___ Fahrrad. (bisiklete biniyor)',
    answer: 'fährt',
    pronounce: ['Meine Schwester fährt Fahrrad.'],
  },
  {
    id: 'p3-gh-fotos-fill',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['vocabulary.hobiler.kelime'],
    familyId: 'p3-gh-fotos',
    instruction: 'Boşluğu doldur (machen ile):',
    prompt: 'Mein Freund macht ___. (fotoğraf çekiyor)',
    answer: 'Fotos',
    pronounce: ['Mein Freund macht Fotos.'],
  },
  {
    id: 'p3-gh-lesen-buecher-mc',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.hobiler.kelime'],
    familyId: 'p3-gh-lesen',
    instruction: 'Bu cümlenin Türkçesi nedir?',
    prompt: 'Ich lese gern Bücher.',
    answer: 'Ben kitap okumayı seviyorum.',
    options: ['Ben kitap okumayı seviyorum.', 'Ben bir kitap alıyorum.', 'Ben gazete okuyorum.', 'Ben müzik dinliyorum.'],
    pronounce: ['Ich lese gern Bücher.'],
  },
  {
    id: 'p3-gh-spoken-hobi',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'spoken', difficulty: 'medium', skill: 'speaking',
    conceptIds: ['vocabulary.hobiler.kelime', 'likes.gern.kullanim'],
    familyId: 'p3-gh-spoken-hobi',
    instruction: 'Sesli görev: sevdiğin bir hobiyi anlat.',
    requirements: ['Ich ... gern ...', 'Mein Lieblingstier ist ...'],
    sampleAnswer: 'Ich spiele gern Fußball. Mein Lieblingstier ist die Katze.',
    pronounce: ['Ich spiele gern Fußball.', 'Mein Lieblingstier ist die Katze.'],
  },
  {
    id: 'p3-gh-listen-katze',
    topicId: T.vocabulary, legacyDay: 3,
    type: 'listen-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.hayvanlar.kelime'],
    familyId: 'p3-gh-katze',
    instruction: 'Duyduğunu seç:',
    prompt: 'Ich habe eine Katze.',
    audioText: 'Ich habe eine Katze.',
    answer: 'Ich habe eine Katze.',
    options: [
      'Ich habe eine Katze.',
      'Ich habe einen Hund.',
      'Ich habe ein Tier.',
      'Ich habe eine Tasche.',
    ],
    audio: { prompt: { text: 'Ich habe eine Katze.', language: 'de-DE', role: 'prompt' } },
  },

  /* ---- Yeni kelimeler: eşyalar, yeni fiiller, derste ---- */
  {
    id: 'vok-brief-artikel-fill',
    topicId: T.vocabulary,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['vocabulary.brief'],
    familyId: 'vok-brief',
    instruction: 'Artikeli yaz — mektup:',
    prompt: '___ Brief',
    answer: 'der',
    validation: { noTypoTolerance: true },
    pronounce: ['der Brief'],
  },
  {
    id: 'vok-schluessel-artikel-mc',
    topicId: T.vocabulary,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.schluessel'],
    familyId: 'vok-schluessel',
    instruction: 'Doğru artikeli seç — anahtar:',
    prompt: 'Schlüssel',
    answer: 'der',
    options: ['der', 'die', 'das'],
    explanation: 'Defterde `die Schlüssel` yazılmış; tekil doğru biçim `der Schlüssel`. (`die Schlüssel` çoğuldur: anahtarlar.)',
    pronounce: ['der Schlüssel'],
  },
  {
    id: 'vok-seil-artikel-mc',
    topicId: T.vocabulary,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.spielzeug-seil'],
    familyId: 'vok-seil',
    instruction: 'Doğru artikeli seç — ip:',
    prompt: 'Seil',
    answer: 'das',
    options: ['der', 'die', 'das'],
    explanation: 'Doğrusu `das Seil` (ip). Defterdeki `der Seil` yanlıştır; `der Vorhang` ise perdedir.',
    pronounce: ['das Seil'],
  },
  {
    id: 'vok-ticket-artikel-fill',
    topicId: T.vocabulary,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['vocabulary.ticket'],
    familyId: 'vok-ticket',
    instruction: 'Artikeli yaz — bilet:',
    prompt: '___ Ticket',
    answer: 'das',
    validation: { noTypoTolerance: true },
    pronounce: ['das Ticket'],
  },
  {
    id: 'vok-dinge-match',
    topicId: T.vocabulary,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.brief', 'vocabulary.tasche-zeitung', 'vocabulary.ticket', 'vocabulary.schluessel', 'vocabulary.spielzeug-seil'],
    familyId: 'vok-dinge-match',
    instruction: 'Eşyaları Türkçesiyle eşleştir.',
    pairs: [
      { left: 'der Brief', right: 'mektup' },
      { left: 'die Tasche', right: 'çanta' },
      { left: 'das Ticket', right: 'bilet' },
      { left: 'der Schlüssel', right: 'anahtar' },
      { left: 'das Spielzeug', right: 'oyuncak' },
    ],
  },
  {
    id: 'vok-klasse-match',
    topicId: T.vocabulary,
    type: 'matching', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.wort-satz', 'vocabulary.frage-antwort', 'vocabulary.fehler-falsch'],
    familyId: 'vok-klasse-match',
    instruction: 'Derste kullanılan kelimeleri eşleştir.',
    pairs: [
      { left: 'das Wort', right: 'kelime' },
      { left: 'der Satz', right: 'cümle' },
      { left: 'die Frage', right: 'soru' },
      { left: 'die Antwort', right: 'cevap' },
      { left: 'der Fehler', right: 'hata' },
    ],
  },
  {
    id: 'vok-verben-match',
    topicId: T.vocabulary,
    type: 'matching', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.nehmen', 'vocabulary.schicken', 'vocabulary.warten', 'vocabulary.verlieren', 'vocabulary.halten-tragen'],
    familyId: 'vok-verben-match',
    instruction: 'Fiilleri anlamlarıyla eşleştir.',
    pairs: [
      { left: 'nehmen', right: 'almak' },
      { left: 'schicken', right: 'göndermek' },
      { left: 'warten', right: 'beklemek' },
      { left: 'verlieren', right: 'kaybetmek' },
      { left: 'tragen', right: 'taşımak' },
    ],
  },
  {
    id: 'vok-maeppchen-mc',
    topicId: T.vocabulary,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.maeppchen'],
    familyId: 'vok-maeppchen',
    instruction: 'Anlamını seç:',
    prompt: 'das Mäppchen',
    answer: 'kalem kutusu',
    options: ['kalem kutusu', 'harita', 'çanta', 'defter'],
    explanation: 'Defterde "harita" yazılmış; `das Mäppchen` kalem kutusudur. Harita `die Karte`.',
    pronounce: ['das Mäppchen'],
  },
  {
    id: 'vok-maeppchen-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.maeppchen', 'shopping.brauchen.antwort'],
    familyId: 'vok-maeppchen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kalem kutuma ihtiyacım var.',
    answer: 'Ich brauche mein Mäppchen.',
    validation: { keyboardTolerance: true },
    explanation: '`das Mäppchen` nötr; Akkusativ\'te `mein` değişmez: `mein Mäppchen`.',
    pronounce: ['Ich brauche mein Mäppchen.'],
  },
  {
    id: 'vok-weiss-fill',
    topicId: T.vocabulary,
    type: 'fill-blank', difficulty: 'medium', skill: 'recall',
    conceptIds: ['vocabulary.wissen'],
    familyId: 'vok-weiss',
    instruction: 'Boşluğu doldur — Bilmiyorum.',
    prompt: 'Ich ___ nicht. (wissen)',
    answer: 'weiß',
    validation: { noTypoTolerance: true, keyboardTolerance: true },
    explanation: '`wissen` düzensizdir: `ich weiß`, `du weißt`, `er weiß` — `ich` ve `er` biçimi aynı (Modalverbler gibi).',
    pronounce: ['Ich weiß nicht.'],
  },
  {
    id: 'vok-benutzen-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.benutzen'],
    familyId: 'vok-benutzen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Telefonumu kullanıyorum.',
    answer: 'Ich benutze mein Handy.',
    pronounce: ['Ich benutze mein Handy.'],
  },
  {
    id: 'vok-schicken-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.schicken', 'vocabulary.brief', 'akkusativ.der-den'],
    familyId: 'vok-schicken',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Mektubu gönderiyorum.',
    answer: 'Ich schicke den Brief.',
    explanation: '`der Brief` nesne olunca `den Brief` olur (Akkusativ).',
    pronounce: ['Ich schicke den Brief.'],
  },
  {
    id: 'vok-nehmen-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.nehmen', 'vocabulary.schluessel', 'akkusativ.der-den'],
    familyId: 'vok-nehmen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Anahtarı alıyorum.',
    answer: 'Ich nehme den Schlüssel.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich nehme den Schlüssel.'],
  },
  {
    id: 'vok-nimmt-fill',
    topicId: T.vocabulary,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['vocabulary.nehmen'],
    familyId: 'vok-nimmt',
    instruction: 'Boşluğu doldur — O (kadın) çantayı alıyor.',
    prompt: 'Sie ___ die Tasche. (nehmen)',
    answer: 'nimmt',
    validation: { noTypoTolerance: true },
    explanation: '`nehmen` düzensizdir: `du nimmst`, `er/sie nimmt` (e → i).',
    pronounce: ['Sie nimmt die Tasche.'],
  },
  {
    id: 'vok-traegt-fill',
    topicId: T.vocabulary,
    type: 'fill-blank', difficulty: 'hard', skill: 'recall',
    conceptIds: ['vocabulary.halten-tragen', 'vocabulary.baby-nachbar'],
    familyId: 'vok-traegt',
    instruction: 'Boşluğu doldur — Annem bebeği taşıyor.',
    prompt: 'Meine Mutter ___ das Baby. (tragen)',
    answer: 'trägt',
    validation: { noTypoTolerance: true, keyboardTolerance: true },
    explanation: '`tragen` düzensizdir: `du trägst`, `er/sie trägt` (a → ä).',
    pronounce: ['Meine Mutter trägt das Baby.'],
  },
  {
    id: 'vok-schneiden-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.schneiden', 'akkusativ.der-den'],
    familyId: 'vok-schneiden',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Keki kesiyorum.',
    answer: 'Ich schneide den Kuchen.',
    pronounce: ['Ich schneide den Kuchen.'],
  },
  {
    id: 'vok-untersuchen-mc',
    topicId: T.vocabulary,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.kontrollieren-untersuchen'],
    familyId: 'vok-untersuchen',
    instruction: 'Anlamını seç:',
    prompt: 'untersuchen',
    answer: 'muayene etmek',
    options: ['muayene etmek', 'kontrol etmek', 'tamir etmek', 'açıklamak'],
    pronounce: ['untersuchen'],
  },
  {
    id: 'vok-kontrollieren-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.kontrollieren-untersuchen', 'daily-routine.gun.hausaufgaben'],
    familyId: 'vok-kontrollieren',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Ödevimi kontrol ediyorum.',
    answer: 'Ich kontrolliere meine Hausaufgaben.',
    pronounce: ['Ich kontrolliere meine Hausaufgaben.'],
  },
  {
    id: 'vok-erklaert-mc',
    topicId: T.vocabulary,
    type: 'multiple-choice', difficulty: 'medium', skill: 'recognition',
    conceptIds: ['vocabulary.erzaehlen-erklaeren', 'vocabulary.wort-satz'],
    familyId: 'vok-erklaert',
    instruction: 'Doğru fiili seç — Öğretmen cümleyi açıklıyor.',
    prompt: 'Der Lehrer ___ den Satz.',
    answer: 'erklärt',
    options: ['erklärt', 'erzählt', 'schickt', 'verliert'],
    explanation: '`erklären` = açıklamak; `erzählen` = (bir olayı) anlatmak.',
    pronounce: ['Der Lehrer erklärt den Satz.'],
  },
  {
    id: 'vok-wiederholen-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.uebersetzen-wiederholen', 'vocabulary.wort-satz'],
    familyId: 'vok-wiederholen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Kelimeyi tekrar ediyorum.',
    answer: 'Ich wiederhole das Wort.',
    pronounce: ['Ich wiederhole das Wort.'],
  },
  {
    id: 'vok-uebersetzen-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.uebersetzen-wiederholen', 'vocabulary.wort-satz', 'akkusativ.der-den'],
    familyId: 'vok-uebersetzen',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Cümleyi çeviriyorum.',
    answer: 'Ich übersetze den Satz.',
    validation: { keyboardTolerance: true },
    pronounce: ['Ich übersetze den Satz.'],
  },
  {
    id: 'vok-frage-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'easy', skill: 'production',
    conceptIds: ['vocabulary.frage-antwort'],
    familyId: 'vok-frage',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bir sorum var.',
    answer: 'Ich habe eine Frage.',
    pronounce: ['Ich habe eine Frage.'],
  },
  {
    id: 'vok-falsch-fill',
    topicId: T.vocabulary,
    type: 'fill-blank', difficulty: 'easy', skill: 'recall',
    conceptIds: ['vocabulary.fehler-falsch', 'vocabulary.frage-antwort'],
    familyId: 'vok-falsch',
    instruction: 'Boşluğu doldur — Cevap yanlış.',
    prompt: 'Die Antwort ist ___.',
    answer: 'falsch',
    validation: { noTypoTolerance: true },
    explanation: '`falsch` = yanlış (sıfat); `der Fehler` = hata (isim).',
    pronounce: ['Die Antwort ist falsch.'],
  },
  {
    id: 'vok-lied-dictation',
    topicId: T.vocabulary,
    type: 'dictation', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.lied-kleid'],
    familyId: 'vok-lied',
    instruction: 'Duyduğun cümleyi aynen yaz (şarkı):',
    audioText: 'Ich höre ein Lied.',
    answer: 'Ich höre ein Lied.',
    validation: { keyboardTolerance: true },
    audio: { prompt: { text: 'Ich höre ein Lied.', language: 'de-DE', role: 'prompt' } },
  },
  {
    id: 'vok-nachbar-mc',
    topicId: T.vocabulary,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.baby-nachbar'],
    familyId: 'vok-nachbar',
    instruction: 'Anlamını seç:',
    prompt: 'der Nachbar',
    answer: 'komşu',
    options: ['komşu', 'misafir', 'arkadaş', 'öğretmen'],
    explanation: 'Sözlük biçimi `der Nachbar`; defterdeki `Nachbarn` çoğul (komşular) ya da Akkusativ biçimidir.',
    pronounce: ['der Nachbar'],
  },
  {
    id: 'vok-spielzeug-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'medium', skill: 'production',
    conceptIds: ['vocabulary.spielzeug-seil', 'vocabulary.baby-nachbar'],
    familyId: 'vok-spielzeug',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Bebeğin bir oyuncağı var.',
    answer: 'Das Baby hat ein Spielzeug.',
    pronounce: ['Das Baby hat ein Spielzeug.'],
  },
  {
    id: 'vok-warten-mc',
    topicId: T.vocabulary,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.warten'],
    familyId: 'vok-warten',
    instruction: 'Cümlenin anlamını seç:',
    prompt: 'Ich warte auf dich.',
    answer: 'Seni bekliyorum.',
    options: ['Seni bekliyorum.', 'Seni arıyorum.', 'Seni tanıyorum.', 'Seni ziyaret ediyorum.'],
    pronounce: ['Ich warte auf dich.'],
  },
  {
    id: 'vok-verlieren-tr',
    topicId: T.vocabulary,
    type: 'free-text', difficulty: 'hard', skill: 'production',
    conceptIds: ['vocabulary.verlieren', 'akkusativ.mein-meinen', 'shopping.siklik.oft'],
    familyId: 'vok-verlieren',
    instruction: 'Türkçeden Almancaya çevir:',
    prompt: 'Anahtarımı sık sık kaybediyorum.',
    answer: 'Ich verliere oft meinen Schlüssel.',
    validation: { keyboardTolerance: true },
    explanation: 'Sıklık kelimesi fiilden hemen sonra; `mein Schlüssel` nesne olunca `meinen Schlüssel`.',
    pronounce: ['Ich verliere oft meinen Schlüssel.'],
  },
  {
    id: 'vok-malen-mc',
    topicId: T.vocabulary,
    type: 'multiple-choice', difficulty: 'easy', skill: 'recognition',
    conceptIds: ['vocabulary.malen-tanzen'],
    familyId: 'vok-malen',
    instruction: 'Anlamını seç:',
    prompt: 'malen',
    answer: 'resim yapmak, boyamak',
    options: ['resim yapmak, boyamak', 'dans etmek', 'kesmek', 'göndermek'],
    pronounce: ['malen'],
  },
];
